- crates/noirc_frontend/src/parser/parser.rs
> Fix: Parser was not skipping comments in expression places

- crates/acir/src/native_types/arithmetic.rs
- crates/acir/src/optimiser/csat_optimiser.rs
- crates/acvm/src/pwg/arithmetic.rs
> Fix ACIR width reduction

- crates/noirc_frontend/src/hir/def_collector/dc_crate.rs
- crates/noirc_frontend/src/hir/def_collector/errors.rs
- crates/noirc_frontend/src/hir/def_map/module_data.rs
- crates/noirc_frontend/src/hir/resolution/import.rs
> Fixes import resolution

- crates/acvm/src/backends/csat_3_plonk_aztec/pwg/gadget_call.rs
I removed a function that was not used.
> Remove dead function: log2()

- crates/noirc_frontend/src/hir/def_collector/errors.rs
> Fixes Clippy Warnings

- crates/aztec_backend/src/serialiser/mod.rs
- crates/nargo/examples/main.rs
- crates/nargo/src/cli/build_cmd.rs
- crates/nargo/src/cli/contract_cmd.rs
- crates/nargo/src/cli/mod.rs
- crates/nargo/src/cli/new_cmd.rs
- crates/nargo/src/cli/prove_cmd.rs
- crates/nargo/src/cli/verify_cmd.rs
- crates/nargo/src/errors.rs
- crates/nargo/src/lib.rs
- crates/nargo/src/resolver.rs
- crates/nargo/src/toml.rs
> Remove proliferation of write_stderr

- crates/noirc_frontend/src/lexer/errors.rs
- crates/noirc_frontend/src/lexer/lexer.rs
- crates/noirc_frontend/src/lexer/token.rs
> Remove explicit Lexer aborts

- crates/aztec_backend/src/contract/cryptography/pairings_bn254.rs
- crates/aztec_backend/src/contract/cryptography/polynomial_eval.rs
- crates/aztec_backend/src/contract/cryptography/transcript.rs
- crates/aztec_backend/src/contract/cryptography/turbo_plonk.rs
- crates/aztec_backend/src/contract/cryptography/types.rs
- crates/aztec_backend/src/contract/turbo_verifier.rs
> Fix smart contract regression

- crates/noirc_evaluator/src/low_level_function_impl/blake2s.rs
- crates/noirc_evaluator/src/low_level_function_impl/ecdsa_secp256k1.rs
- crates/noirc_evaluator/src/low_level_function_impl/fixed_based_scalar_mul.rs
- crates/noirc_evaluator/src/low_level_function_impl/hash_to_field.rs
- crates/noirc_evaluator/src/low_level_function_impl/merkle_membership.rs
- crates/noirc_evaluator/src/low_level_function_impl/mod.rs
- crates/noirc_evaluator/src/low_level_function_impl/pedersen.rs
- crates/noirc_evaluator/src/low_level_function_impl/schnorr.rs
- crates/noirc_evaluator/src/low_level_function_impl/sha256.rs
> Refactor FFI prepare inputs

- crates/noirc_frontend/src/hir/type_check/expr.rs
> Change reported span on type mismatch for call expressions

- crates/noirc_frontend/src/hir/type_check/expr.rs
> Fix Typo in operand rules

- crates/acir/Cargo.toml
- crates/acir/src/native_types/arithmetic.rs
- crates/acir/src/native_types/witness.rs
- crates/acir/src/optimiser/csat_optimiser.rs
- crates/acir/src/optimiser/general_optimiser.rs
- crates/acvm/Cargo.toml
- crates/acvm/src/compiler.rs
- crates/noirc_evaluator/src/binary_op/cast.rs
- crates/noirc_evaluator/src/lib.rs
> Fixes indeterminate equations

- Cargo.lock
- crates/aztec_backend/Cargo.toml
- crates/aztec_backend/src/acvm_interop/pwg/gadget_call.rs
- crates/nargo/src/cli/mod.rs
- crates/noirc_abi/src/lib.rs
- crates/noirc_errors/src/position.rs
- crates/noirc_frontend/src/hir/resolution/resolver.rs
- crates/noirc_frontend/src/hir_def/function.rs
Reference branch which fixes the MacOS compilation issue
> Fixes MacOS compilation with C++

- crates/noirc_frontend/src/parser/parser.rs
These made made it in through the parser combinators PR
> Remove printlns

- crates/noirc_frontend/src/parser/parser.rs
Adds the ability to parse constructor field shorthand syntax: `MyStruct { shorthand, longform: expr, shorthand2 }`. This desugars right in the parser into `MyStruct { shorthand: shorthand, longform: expr, shorthand2: shorthand2 }` so no further changes are need in name resolution or onward.
> Parse constructor field shorthand

- crates/noirc_frontend/src/hir/def_collector/dc_crate.rs
- crates/noirc_frontend/src/hir/resolution/resolver.rs
- crates/noirc_frontend/src/hir/type_check/errors.rs
- crates/noirc_frontend/src/hir/type_check/expr.rs
- crates/noirc_frontend/src/hir/type_check/stmt.rs
Not intended to have any observable changes - other than the removal of a println I found
> Small Cleanup

- crates/noirc_evaluator/src/ssa/code_gen.rs
- crates/noirc_evaluator/src/ssa/integer.rs
- crates/noirc_frontend/src/lexer/token.rs
Clippy nightly has a new "warning: unneeded late initalization" check
> Fix new clippy nightly suggestions

- crates/aztec_backend/Cargo.toml
> Revert "Fix Issue #202"

- crates/noirc_frontend/src/lexer/errors.rs
- crates/noirc_frontend/src/lexer/lexer.rs
From the old issue brought up during sprint planning.
> Add error when trying to use Logical Or operator

- crates/noirc_evaluator/src/ssa/acir_gen.rs
for bitwise operator and multiplication
> Fix constraints generation

- crates/nargo/tests/test_data/7_function/src/main.nr
- crates/noirc_evaluator/src/ssa/code_gen.rs
Only one line changed but cargo fmt has modified many more. I wonder if it gives consistent result on all systems.
> Parse block expression in the ssa pass

- crates/nargo/tests/test_data/7_function/src/main.nr
- crates/noirc_evaluator/src/ssa/code_gen.rs
- crates/noirc_evaluator/src/ssa/function.rs
- crates/noirc_evaluator/src/ssa/mem.rs
- crates/noirc_evaluator/src/ssa/ssa_form.rs
Nodes are created recursively from the type of the arguments
> Support struct and tuple for function arguments

- crates/noirc_evaluator/src/ssa/inline.rs
There was a bad merge causing master to fail to compile, this fixes it.
> Fix bad merge

- crates/acir/src/optimiser/general_optimiser.rs
- crates/acvm/src/lib.rs
- crates/acvm/src/pwg/arithmetic.rs
- crates/acvm/src/pwg/signature/ecdsa.rs
- crates/fm/src/file_reader.rs
- crates/nargo/src/cli/mod.rs
- crates/nargo/src/cli/prove_cmd.rs
- crates/noirc_evaluator/src/environment.rs
- crates/noirc_evaluator/src/ssa/code_gen.rs
- crates/noirc_frontend/src/hir/def_collector/dc_crate.rs
- crates/noirc_frontend/src/hir/type_check/errors.rs
- crates/noirc_frontend/src/hir/type_check/expr.rs
- crates/noirc_frontend/src/hir/type_check/stmt.rs
We check constraints are satisfied during the witness generation
> Check constraints are satisifed

- crates/noirc_frontend/src/hir/resolution/errors.rs
Improve the error message by suggesting a workaround.
> Help for unused variables error

- crates/noirc_evaluator/src/ssa/code_gen.rs
- crates/noirc_evaluator/src/ssa/context.rs
- crates/noirc_evaluator/src/ssa/function.rs
- crates/noirc_evaluator/src/ssa/mem.rs
- crates/noirc_evaluator/src/ssa/node.rs
- crates/noirc_evaluator/src/ssa/optim.rs
- crates/noirc_frontend/src/hir/def_collector/dc_crate.rs
We do not restrict indexed expression to only array identifiers
> implement indexed expressions

- crates/noirc_evaluator/src/lib.rs
- crates/noirc_evaluator/src/ssa/code_gen.rs
- crates/noirc_evaluator/src/ssa/function.rs
I think it is a regression because it was working before, but anyway now the error is properly displayed.
> report an error when constrain is  false

- crates/noirc_frontend/src/hir/type_check/stmt.rs
Fixes a crash during type checking when type checking programs like the following:
```rs
fn main() {
z = 3;
}
```
Now we will issue the correct error without crashing.
> Fix crash when assigning to variables that don't exist

- crates/noirc_frontend/src/hir/resolution/errors.rs
- crates/noirc_frontend/src/hir/resolution/resolver.rs
Just adding an error message if main return type is not 'pub'
> Mandatory 'pub' on main return type

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
Test it out at [Globallager/noir](https://github.com/Globallager/noir).
Preview:
> Create Issue & PR Templates

- crates/nargo/tests/test_data/2_div/src/main.nr
- crates/noirc_evaluator/src/interpreter.rs
- crates/noirc_evaluator/src/ssa/node.rs
- crates/noirc_frontend/src/ast/expression.rs
- crates/noirc_frontend/src/parser/mod.rs
Modulo operator was already implemented, I just connect it with the % token
> Enable modulo operator

- .gitignore
This PR adds the output of `nargo prove` and `nargo compile` to gitignore to avoid accidentally committing artifacts from using `nargo` on `nargo/tests/test_data`.
N/A
N/A
N/A
> Add proofs, circuits and witnesses to gitignore

- crates/noirc_evaluator/src/interpreter.rs
I'm just merging the two arms for `AbiType::Field` to handle visibility in a similar way to how we do for the other `AbiType`s
N/A
N/A
N/A
> refactor match statement arms in `parse_abi`

- crates/noirc_abi/src/input_parser/toml.rs
Resolves #429
Auto-generates a Verifier.toml file if it does not already exist.
(Describe the changes in this PR. Point out breaking changes if any.)
> Create Verifier.toml if it does not already exist

- crates/nargo/tests/test_data/9_conditional/src/main.nr
- crates/noirc_evaluator/src/ssa/conditional.rs
Resolves #547 
De-activate the flatten simple mode as it works only for simple cases
Regression test added to 9_conditional
> Deactivate the flatten simple mode

- crates/nargo/src/errors.rs
(If it does not already exist, first create a GitHub issue that describes the problem this Pull Request (PR) solves before creating the PR and link it here.)
Resolves #608 
(Describe the changes in this PR. Point out breaking changes if any.)
> Return Failure ExitCode when an error is encountered in CLI

- crates/acvm/src/pwg/signature/ecdsa.rs
- crates/noirc_driver/src/lib.rs
- crates/noirc_evaluator/src/ssa/acir_gen.rs
- crates/noirc_evaluator/src/ssa/anchor.rs
- crates/noirc_evaluator/src/ssa/block.rs
- crates/noirc_evaluator/src/ssa/flatten.rs
Resolves #599
Removes every instance of the `dbg!` macro
> Remove dbg macro instances

- crates/noirc_evaluator/src/ssa/acir_gen.rs
Create witness if needed when dividing expressions
> create witness if needed

- .github/workflows/rust.yml
Resolves # 
This is a comment from when the aztec_backend was in the same repository as the compiler
> Remove outdated comment

- barretenberg_dep.sh
> Remove unused barretenberg_dep.sh

- crates/nargo/src/cli/mod.rs
- crates/noirc_driver/src/lib.rs
- crates/noirc_evaluator/src/ssa/acir_gen.rs
- crates/noirc_evaluator/src/ssa/context.rs
- crates/noirc_frontend/src/monomorphisation/printer.rs
Resolves # 
This PR fixes new clippy warnings that have appeared. Reproducible by running `cargo clippy`
> Fix Clippy Warnings

- crates/nargo/src/cli/check_cmd.rs
- crates/noirc_abi/src/errors.rs
- crates/noirc_driver/src/lib.rs
- crates/noirc_frontend/src/ast/mod.rs
- crates/noirc_frontend/src/hir/type_check/expr.rs
- crates/noirc_frontend/src/hir_def/types.rs
- crates/noirc_frontend/src/monomorphisation/ast.rs
Leftover for https://github.com/noir-lang/noir/issues/657
change `build` function name to `check` in driver
> fix driver function name

- Cargo.lock
- crates/nargo/Cargo.toml
Resolves #662 
I accidentally squashed my PR for Noir lang before `aztec_backend` for this PR: https://github.com/noir-lang/aztec_backend/pull/48
> update aztec backend commit to master

- crates/nargo/src/cli/mod.rs
Per @LHerskind's suggestion on Slack, this updates the help description of `nargo contract` to more accurately reflect that the command generates a **Solidity verifier** smart contract.
> Revise `nargo contract` Description

- crates/nargo/src/cli/prove_cmd.rs
- crates/noirc_evaluator/src/lib.rs
- crates/noirc_evaluator/src/ssa/acir_gen.rs
Minor refactor so no issue.
This PR just collects a couple of smalls changes which remove unnecessary code and improve readability imo.
N/A
N/A
> chore: minor readability improvements

- Cargo.toml
- crates/wasm/Cargo.toml
Resolves https://github.com/noir-lang/noir/issues/715
change version number of dependencies from "*" to actual version number
same as above
> explicit versions for dependencies

- crates/noirc_evaluator/src/ssa/conditional.rs
- crates/noirc_evaluator/src/ssa/inline.rs
> Rename methods that use `conditionalize` to be more descriptive

- crates/nargo/tests/test_data/9_conditional/src/main.nr
- crates/noirc_evaluator/src/ssa/node.rs
- crates/noirc_evaluator/src/ssa/optimizations.rs
delete instructions with false predicate
Regression added in 9_conditional
- [] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
> fix(ssa): delete instructions with false predicate

- crates/noirc_evaluator/src/ssa/acir_gen.rs
- crates/noirc_evaluator/src/ssa/acir_gen/constraints.rs
- crates/noirc_evaluator/src/ssa/acir_gen/internal_var.rs
- crates/noirc_evaluator/src/ssa/acir_gen/internal_var_cache.rs
- crates/noirc_evaluator/src/ssa/acir_gen/intrinsics.rs
- crates/noirc_evaluator/src/ssa/acir_gen/memory_map.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/binary.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/bitwise.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/cmp.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/condition.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/constrain.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/intrinsics.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/load.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/not.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/return.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/store.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/truncate.rs
Resolves # 
This should be merged in after #749 
- Adding doc comments to methods
- Smoke tests
- Refactoring method names
- Separate methods into different modules
> chore(ssa): refactor ACIR generation code

- crates/nargo/tests/test_data/9_conditional/src/main.nr
- crates/noirc_evaluator/src/ssa/conditional.rs
- crates/noirc_evaluator/src/ssa/context.rs
- crates/noirc_evaluator/src/ssa/optimizations.rs
This PR fixes the synchronisation of ELSE/THEN branches. As a result, we now need to properly optimise result instructions coming from the branches.
Test case added in 9_conditional
> fix(ssa): synchronisation for functions

- .github/workflows/rust.yml
Resolves # 
This renames our workflows to keep things consistent and because we need to re-assign our required checks.
> chore(ci): Rename workflows

- crates/noirc_frontend/src/hir/resolution/errors.rs
> chore: fix clippy

- crates/nargo/src/cli/mod.rs
Resolves # 
@Lasse brought up the fact that if you are not using nargo to read the proof output file, you need to know exactly what the format is. This tells the user that the file is a hex encoded string
> chore: Document structure of proof file

- Cargo.lock
- crates/nargo/Cargo.toml
- crates/nargo/src/main.rs
Related to #818.
Register a panic hook before starting the `nargo` cli.
Added [`color_eyre`](https://docs.rs/color-eyre/latest/color_eyre/).
N/A
> feat(nargo): Add panic hook

- crates/nargo/src/cli/prove_cmd.rs
We now use a doc comment rather than a regular comment so clap knows to display this on the CLI.
> fix: display command description in CLI for `nargo prove`

- crates/noirc_evaluator/src/ssa/ssa_gen.rs
Resolves #852
Add documentation for get_current_value
> chore(ssa): document get_current_value

- crates/noirc_frontend/src/hir/resolution/resolver.rs
- crates/noirc_frontend/src/hir/type_check/errors.rs
- crates/noirc_frontend/src/hir/type_check/expr.rs
- crates/noirc_frontend/src/hir/type_check/mod.rs
- crates/noirc_frontend/src/hir/type_check/stmt.rs
- crates/noirc_frontend/src/lib.rs
Resolves #919 for `noirc_frontend` crate
Rebasing up this branch I made circa https://github.com/noir-lang/noir/pull/920.
> chore: restrict visibility of pub functions in `noirc_frontend`

- LICENSE-MIT
Updates license
Updates license to reflect current year
> chore: Update License

- crates/noirc_evaluator/src/lib.rs
- crates/noirc_evaluator/src/ssa/acir_gen.rs
- crates/noirc_evaluator/src/ssa/acir_gen/acir_mem.rs
- crates/noirc_evaluator/src/ssa/acir_gen/constraints.rs
- crates/noirc_evaluator/src/ssa/acir_gen/internal_var.rs
- crates/noirc_evaluator/src/ssa/acir_gen/internal_var_cache.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/cmp.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/condition.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/constrain.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/sort.rs
- crates/noirc_evaluator/src/ssa/anchor.rs
- crates/noirc_evaluator/src/ssa/block.rs
- crates/noirc_evaluator/src/ssa/builtin.rs
- crates/noirc_evaluator/src/ssa/conditional.rs
- crates/noirc_evaluator/src/ssa/context.rs
- crates/noirc_evaluator/src/ssa/flatten.rs
- crates/noirc_evaluator/src/ssa/function.rs
- crates/noirc_evaluator/src/ssa/inline.rs
- crates/noirc_evaluator/src/ssa/integer.rs
- crates/noirc_evaluator/src/ssa/mem.rs
- crates/noirc_evaluator/src/ssa/mod.rs
- crates/noirc_evaluator/src/ssa/node.rs
- crates/noirc_evaluator/src/ssa/optimizations.rs
- crates/noirc_evaluator/src/ssa/ssa_form.rs
- crates/noirc_evaluator/src/ssa/ssa_gen.rs
- crates/noirc_evaluator/src/ssa/value.rs
Resolves https://github.com/noir-lang/noir/issues/919 for noirc_evaluator crate
Rebasing up this branch I made circa https://github.com/noir-lang/noir/pull/920.
> chore: restrict visibility of pub functions in `noirc_evaluator`

- Cargo.lock
- crates/nargo/src/cli/check_cmd.rs
- crates/wasm/Cargo.toml
Resolves # 
I've addressed some clippy warnings (unnecessary mut on `config` and an unused dependency)
> chore: clippy fixes

- .github/pull_request_template.md
Adding a `` comment under the "Documentation needs" section of the PR template.
A small summary of doc needs when needed is immensely helpful. Much appreciated.
> chore(github): Add Describe Doc Needs Reminder to PR Template

- crates/noirc_evaluator/src/lib.rs
- crates/noirc_evaluator/src/ssa/acir_gen/constraints.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/constrain.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/intrinsics.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/sort.rs
Remove usage of Truncate and Oddrange directives and abstract addition of opcodes inside a function.
> chore: Remove usage of truncate and oddrange directives

- .github/workflows/wasm.yml
Resolves # 
This PR adds a CI workflow to check that the `build-wasm` script will succeed.
> chore(ci): add check that the wasm crate builds

- README.md
> chore: fix broken installation link in readme

- crates/noirc_evaluator/src/ssa/mem.rs
> chore(ssa): document MemArray

- Cargo.lock
- Cargo.toml
- crates/nargo_cli/Cargo.toml
- crates/nargo_cli/src/cli/execute_cmd.rs
- crates/nargo_cli/src/cli/test_cmd.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/sort.rs
> chore: Handle unresovled output from PWG

- crates/wasm/build-wasm
Resolves https://github.com/noir-lang/noir/issues/1181
Bumps noir-source-resolver to 1.1.2
Bumps noir-source-resolver to 1.1.2
Required for testing noir_wasm
> feat: bump noir-source-resolver version

- flake.nix
> chore: update flake version to match current release

- crates/nargo_cli/src/main.rs
> chore(nargo): update panic message to suggest searching for similar issues

- crates/noirc_evaluator/src/ssa_refactor/ir/map.rs
Resolves # 
Addresses a clippy warning
> chore: fix clippy warning

- crates/noirc_evaluator/src/frontend.rs
Resolves # 
This is a small cleanup from 1284. (This file is not being used nor is it in the crate hierachy)
> chore: Remove unused `frontend` file

- crates/noirc_evaluator/src/lib.rs
Resolves # 
This comment is no longe true, arrays can be set as public for example
> chore: Remove outdated comment

- README.md
Fixes https://github.com/noir-lang/noir/issues/1089#issuecomment-1539010915 (again)
> chore: fix installation link in readme

- crates/noirc_evaluator/src/ssa_refactor.rs
- crates/noirc_evaluator/src/ssa_refactor/abi_gen/mod.rs
- crates/noirc_evaluator/src/ssa_refactor/acir_gen/generated_acir.rs
- crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs
SSA refactor Milestone 0: compile an empty program with no return value (i.e. hook up ABI generation).
Given the empty program:
```rs
fn main(x : Field, y : pub Field) {}
```
`nargo compile --experimental-ssa` now outputs a valid ABI and empty circuit.
> chore(ssa refactor): ssa milestone 0

- crates/nargo_cli/src/cli/mod.rs
- crates/nargo_cli/tests/prove_and_verify.rs
- crates/nargo_cli/tests/test_data_ssa_refactor/config.toml
This PR will allows us to test code compiled using the experimental ssa code in a seperate test directory. Its separate so that we can add in new test cases and slowly copy over the existing test cases.
Note: Although prove_and_verify method is modified (adding the experimental-ssa boolean), it is only meant to be used for tests, which is why I marked it as non-breaking.
Resolves 
Before:
```
```
After:
```
```
> chore: Add test directory for experimental-ssa

- .github/workflows/test.yml
There seems to be some memory issues with the switch to UP, so adding ubuntu-large to temporarily mitigate these
Resolves 
Before:
```
```
After:
```
```
> chore(ci): Switch to ubuntu-large

- crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/acir_variable.rs
- crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/generated_acir.rs
- crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs
Resolves 
Before:
```
```
After:
```
```
> chore(ssa refactor): Add code to handle `truncate` instruction

- crates/noirc_evaluator/src/brillig/artifact.rs
- crates/noirc_evaluator/src/brillig/brillig_gen.rs
- crates/noirc_evaluator/src/brillig/mod.rs
- crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs
Using the america spelling to appease spell.
> chore: change `artefact` to `artifact`

- crates/noirc_evaluator/src/ssa_refactor/ir/cfg.rs
Resolves #1520
Prevents CFG from adding edges from unreachable nodes.
> fix(ssa refactor): filter unreachable blocks from cfg

- crates/noirc_evaluator/src/ssa_refactor/ir/post_order.rs
> chore(ssa refactor): switch test to use function builder

- Cargo.lock
- Cargo.toml
This updates to acvm 0.14.1 to include the fix [here](https://github.com/noir-lang/acvm/pull/343)
Resolves 
Before:
```
```
After:
```
```
> chore: update to acvm 0.14.1

- .gitignore
- crates/wasm/build.sh
- crates/wasm/buildPhaseCargoCommand.sh
- crates/wasm/installPhase.sh
- flake.nix
Refactors flake approach
Resolves 
Before:
```
```
After:
```
```
> Kh noir wasm nix flake

- crates/noirc_evaluator/src/ssa_refactor/ssa_gen/context.rs
Resolves #1665
Before:
```
```
After:
```
```
> fix(ssa refactor): Translate strings as arrays of characters

- crates/noirc_evaluator/src/ssa_refactor.rs
SSA passes always show, which chokes the CI test logs
SSA passes now only show when using the existing `--show-ssa` flag.
> chore(ssa refactor): print ssa passes on flag only

- crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/generated_acir.rs
Resolves GH-1697
Prevent u32 overflow in radix calculation
> fix(ssa refactor): BigUint for radix

- crates/nargo/src/ops/execute.rs
> fix: Oracle output resolution

- crates/noirc_evaluator/src/brillig/brillig_ir.rs
- crates/noirc_evaluator/src/brillig/brillig_ir/debug_show.rs
Scrappy debug printing for brillig. Aims to be higher level than a literal write out of brillig, using high level comments or short terms (e.g. ASSERT as a pseudo-opcode). Meant to be augmented with additional prints as traces are needed. Longer term we'll have a proper debug data format, but perhaps might not be for a while.
Example:
```
f1:
CONST R3 = 1
R2 = R1 i32::+ R3
MOV R4, R2
STORE *Stack = R1
CONST R5 = 1
Stack = Stack + R5
STORE *Stack = R2
CONST R5 = 1
Stack = Stack + R5
STORE *Stack = R3
CONST R5 = 1
Stack = Stack + R5
STORE *Stack = R4
CONST R5 = 1
Stack = Stack + R5
MOV R5, R4
MOV R1, R5
CALL f8
MOV R6, R1
CONST R7 = 1
Stack = Stack - R7
LOAD R4 = *Stack
CONST R7 = 1
Stack = Stack - R7
LOAD R3 = *Stack
CONST R7 = 1
Stack = Stack - R7
LOAD R2 = *Stack
CONST R7 = 1
Stack = …
```
> chore: high level brillig ir printer

- crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/generated_acir.rs
Add documentation in the code for bound_constraint_with_offset(..) function
> chore(acir): Document bound_constraint_with_offset(..) function

- README.md
Updating README to include a note about the latest interfaces not being updated to support Marlin backend
Resolves
> chore: Update README note on the marlin backend

- crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
- crates/noirc_evaluator/src/brillig/brillig_ir.rs
- crates/noirc_evaluator/src/brillig/brillig_ir/debug_show.rs
Implement bitwise not for brillig
Related to #1763
> chore: bitwise not for brillig

- release-please-config.json
Resolves 
The new release PR doesn't use the naming we want. This should fix it because we don't have a "group" currently.
> chore(ci): Add pull-request-title-pattern since there is no group currently

- crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/acir_variable.rs
- crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/generated_acir.rs
- crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs
> chore(ssa refactor): Pass predicate to brillig opcodes

- crates/wasm/README.md
- crates/wasm/installPhase.sh
Resolves 
This fixes the README that we copy when building wasm. It also appends the "tracking" information that we want in the `noir_wasm` repo.
> chore(wasm): Update the readme and copy the correct one during install

- .github/workflows/test.yml
- flake.nix
> chore: Run CI on `ubuntu-latest` runner

- crates/noirc_abi/src/input_parser/mod.rs
Resolves 
This code is completely unused and so can be removed.
> chore: remove unused `InitialWitnessParser` trait

- crates/noirc_evaluator/src/errors.rs
- crates/noirc_evaluator/src/ssa/acir_gen/constraints.rs
- crates/noirc_evaluator/src/ssa/acir_gen/operations/return.rs
- crates/noirc_evaluator/src/ssa/conditional.rs
- crates/noirc_evaluator/src/ssa/context.rs
- crates/noirc_evaluator/src/ssa/node.rs
- crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/errors.rs
remove `RuntimeErrorKind::{Spanless, UnstructuredError}`
Towards #11
> chore: remove `RuntimeErrorKind::{Spanless, UnstructuredError}`

- crates/nargo_cli/src/cli/info_cmd.rs
- crates/nargo_cli/src/cli/mod.rs
- crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs
Resolves #714
Rename nargo gates to nargo info
> chore(nargo)!: Rename nargo gates to nargo info

- crates/noirc_frontend/src/parser/errors.rs
- crates/noirc_frontend/src/parser/parser.rs
improve error for patterns
Resolves #351
> chore: improve error for patterns

- crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/acir_variable.rs
> chore: document truncate

- crates/noirc_evaluator/src/ssa.rs
Resolves 
This comment is now stale as it refers to the old removed SSA code. We also do require returning a `Result` from `create_circuit` as the ACIR generation step can return errors.
> chore: update stale comment on `create_circuit`

- crates/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
Resolves 
The frontend does shout.
> chore: remove stale comment

- crates/nargo_cli/tests/execution_success/config.toml
- crates/nargo_cli/tests/test_data
Resolves 
`aztec-packages` has been updated to pull from the new directory so this is unnecessary.
> chore: Remove symlink and dummy config file

- .github/workflows/publish.yml
Resolves 
This runs the publish workflow against PRs. We need this so we can make required checks for this.
> chore(ci): Run publish workflow against PRs

- release-please-config.json
Resolves 
See https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#sentence-case
> chore(ci): automatically convert changelog entries to sentence case

- crates/wasm/package.json
> chore: update noir-source-resolver from `1.1.2` to `^1.1.3`

- crates/noirc_frontend/src/lexer/lexer.rs
> chore: clippy fix

- crates/noirc_evaluator/src/ssa/ssa_gen/mod.rs
- crates/noirc_frontend/src/hir/resolution/resolver.rs
- crates/noirc_frontend/src/hir/type_check/expr.rs
- crates/noirc_frontend/src/monomorphization/mod.rs
Resolves 
This PR runs `cargo fmt` on the repo to address any issues.
> chore: Run `cargo fmt`

- Cargo.lock
- crates/nargo_cli/Cargo.toml
Resolves 
`nargo_cli` doesn't use `dirs` anymore so we can remove this dependency.
> chore: remove unused dependency

- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/wasm.yml
Bumps the github action to the new version
> chore(ci): bump checkout action to v4

- Cargo.lock
- crates/acvm_backend_barretenberg/Cargo.toml
- crates/acvm_backend_barretenberg/src/bb.rs
- crates/acvm_backend_barretenberg/src/proof_system.rs
- crates/acvm_backend_barretenberg/src/smart_contract.rs
Resolves 
This solves the issues which @jfecher is running into (once the old binary has been cleared out)
> chore: bump `bb` version to 0.5.1

- .github/workflows/release-abi_wasm.yml
- .github/workflows/release-source-resolver.yml
Change publish token to use NPM_PUBLISH_TOKEN
Resolves
> chore: update npm token

- .github/workflows/publish.yml
Resolves 
See https://github.com/noir-lang/acvm/pull/536.
> chore(ci): install `cross` as prebuilt binary

- .github/workflows/publish-abi_wasm.yml
- release-please-config.json
> chore: add abi_wasm to release-please

- tooling/nargo_cli/tests/compile_failure/brillig_assert_fail/src/main.nr
- tooling/nargo_cli/tests/execution_success/brillig_assert/src/main.nr
- tooling/nargo_cli/tests/execution_success/brillig_not/src/main.nr
> chore: revert some unwanted small changes from PR2180

- .github/workflows/publish-abi_wasm.yml
- .github/workflows/release-source-resolver.yml
- .github/workflows/release.yml
> chore: fix `noirc_abi_wasm` publish for release-please

- .github/workflows/test-integration.yml
- compiler/integration-tests/package.json
- tooling/noirc_abi_wasm/test/browser/abi_encode.test.ts
- yarn.lock
Resolves [nightly test-integration failed#2708](https://github.com/noir-lang/noir/issues/2708)
Resolves
> fix: failing js tests

- .github/workflows/test-integration.yml
Resolves 
We should ensure that any PRs which modify the integration tests do not break them.
> chore(ci): run integration tests on PRs which change them

- .github/workflows/test-integration.yml
Resolves: nightly test-integration failed #2731
Resolves
> fix: nightly js test

- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
Some minor code cleanup from the comments in #2716. I can't suggest changes and apply them in that PR so I figured a separate PR would be faster.
Resolves
> chore: Minor code cleanup for PR 2716

- compiler/noirc_frontend/src/parser/errors.rs
- compiler/noirc_frontend/src/parser/parser.rs
Using constrain keyword now result into an error.
Resolves
> feat!: constrain is now a hard error

- compiler/noirc_frontend/src/hir/resolution/resolver.rs
Resolves 
This PR fixes the formatting broken in #2733
> chore: fix formatting

- compiler/integration-tests/test/integration/browser/compile_prove_verify.test.ts
- tooling/noir_js/src/index.ts
Resolves #2785 
This PR updates the imports in the integration test so that it can pass again.
> chore(ci): fix integration tests imports

- tooling/nargo_cli/tests/execution_success/conditional_regression_to_bits/Nargo.toml
Resolves [CI failure](https://github.com/noir-lang/noir/actions/runs/6280420429/job/17057684190)
#2774 broke CI due to a typo in the package name.
> chore(ci): fix artifact rebuild script

- .github/NIGHTLY_TEST_FAILURE.md
> chore(ci): don't assign blaine to nightly integration test failures

- .github/workflows/noir-js.yml
- .github/workflows/publish-abi_wasm.yml
- .github/workflows/release-source-resolver.yml
Resolves #2819
This PR uses yarn to publish our NPM packages so we correctly rewrite the workspace dependencies.
> chore: use yarn to publish NPM packages

- .github/workflows/abi_wasm.yml
- .github/workflows/acvm-rust.yml
Resolves 
#2813 left some caching steps behind which this PR cleans up.
> chore(ci): remove stale job steps

- SUPPORT.md
Updates the discord link to one that does not expire
Resolves
> chore: update discord link

- compiler/integration-tests/package.json
Indicating that it is not meant for publishing.
Resolves
> chore: mark integration test as private

- .github/workflows/auto-pr-rebuild-script.yml
> chore: Add back rebuild script

- .github/workflows/test-integration.yml
- compiler/integration-tests/package.json
- compiler/integration-tests/web-test-runner.config.mjs
- compiler/wasm/package.json
- tooling/noirc_abi_wasm/package.json
- yarn.lock
> chore(ci): replace webdriver with playwright

- compiler/integration-tests/package.json
- package.json
- release-please-config.json
- release-tests/package.json
- tooling/noir_js_types/package.json
Aligns versions for all releasable packages.
Resolves
> chore: align versions for js packages

- tooling/nargo_cli/tests/execution_success/trait_override_implementation/src/main.nr
Add Test trait override of MutableReference of struct
> chore(tests): Test trait override of MutableReference of struct

- Cargo.lock
- tooling/nargo_fmt/Cargo.toml
- tooling/nargo_fmt/build.rs
- tooling/nargo_fmt/src/lib.rs
prettier test diff output via `similar-asserts`
> chore(formatter): prettier test diff output via `similar-asserts`

- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
Resolves 
This PR removes unused imports from some tests
> chore: clippy

- acvm-repo/acvm/src/compiler/transformers/fallback.rs
> fix: Determinism of fallback transformer

- compiler/noirc_frontend/src/ast/expression.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/parser/parser.rs
- tooling/nargo_fmt/src/visitor/expr.rs
- tooling/nargo_fmt/tests/expected/expr.nr
- tooling/nargo_fmt/tests/input/expr.nr
> chore(fmt): format parentheses expression

- compiler/noirc_frontend/src/hir/aztec_library.rs
> chore: set `check_type` to false in lookup method

- docs/docs/language_concepts/01_functions.md
Update the documentation for the PR #3045, fixing the issue #526.
Resolves 
- [O] I have tested the changes locally.
- [O] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.
> chore: add doc for the field attribute

- docs/versioned_docs/version-0.10.5/standard_library/recursion.md
This PR fixes and outdated link on the recursion page of the docs.
Resolves
> fix: Update link to recursion example

- tooling/noir_js/src/index.ts
Resolves 
This PR adds proper exports for black box function solvers and useful types from acvm_js from noir_js.
> feat: add exports of JS black box solvers to noirJS

- .github/workflows/recrawler.yml
Related to #3330 
Resolves 
Check one:
> chore: comment out algolia recrawler workflow as its failing master

- .github/workflows/publish-docs.yml
This PR makes release-please also trigger a commit with the new docs version
After the changes in the release-please to cut new versions, dumb me forgot to make it actually commit the files to the repo
> chore(docs): making release-please commit new version to the repo

- tooling/nargo_fmt/src/lib.rs
- tooling/nargo_fmt/src/rewrite.rs
- tooling/nargo_fmt/src/rewrite/infix.rs
- tooling/nargo_fmt/src/utils.rs
- tooling/nargo_fmt/src/visitor.rs
- tooling/nargo_fmt/src/visitor/expr.rs
- tooling/nargo_fmt/tests/expected/expr.nr
- tooling/nargo_fmt/tests/expected/infix.nr
- tooling/nargo_fmt/tests/input/infix.nr
> chore: format infix expression

- compiler/readme.md
- tooling/readme.md
> chore: update internal documentation

- tooling/bb_abstraction_leaks/build.rs
- tooling/noir_js_backend_barretenberg/package.json
- yarn.lock
> chore: Updates bb dependency to 0.15.1

- release-please-config.json
Continuation of #3645 
Resolves 
Check one:
> chore: fix relative paths in reease please

- acvm-repo/acir/acir_docs.md
Resolves 
Reference document for ACIR.
Check one:
> chore: initial draft of acir documentation

- Cargo.lock
> chore: fix lockfile

- .github/workflows/release.yml
> chore: Update acvm version along with the lockfile

- Cargo.toml
> chore: correct MSRV listed in `Cargo.toml`

- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
Resolves 
This PR remove some duplicate implementations or too-low-level calls to logic operations in `AcirContext`.
Check one:
> feat: prefer `AcirContext`-native methods for performing logic operations

- compiler/noirc_frontend/src/resolve_locations.rs
Resolves 
feat(lsp): goto global definition #3728
Allows user to go to global definition.
Check one:
> feat(lsp): goto global

- compiler/noirc_evaluator/src/ssa.rs
Resolves 
RIP `bubble_up_constrains` 2024-2024
Check one:
> feat: disable constraint bubbling pass

- .github/workflows/publish-es-packages.yml
Resolves 
One more attempt after #4165 :sweat_smile: 
Check one:
> chore: Update publish-es-packages.yml

- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
Resolves 
Consider the program
```rust
unconstrained fn identity(x: u8) -> u8 {
x
}
fn main(x: u8, y: pub Field) {
assert(identity(x) as Field == 1000);
}
```
From looking at the type information, this program should be unsatisfiable. A `u8` should not be able to contain the value `1000` so the assertion should always fail. If we look at the generated ACIR however we see that the return value of `identity()` doesn't need to be a valid `u8` and so can be set by the prover to be `1000`.
```
BLACKBOX::RANGE [(_0, num_bits: 8)] [ ]
BRILLIG: inputs: [Single(Expression { mul_terms: [], linear_combinations: [(1, Witness(0))], q_c: 0 })]
outputs: [Simple(Witness(2))]
[Mov { destination: RegisterIndex(2), source: RegisterIndex(0) }, Const { destination: RegisterIndex(0), value: Value { inner: 0 } …
```
> fix: apply range constraints to return values from unconstrained functions

- cspell.json
Resolves 
master CI failing after https://github.com/noir-lang/noir/pull/4204
Check one:
> chore: add taiko to Cspell

- compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs
Partial work towards https://github.com/noir-lang/noir/issues/4275
Check one:
> fix: Ssa typing of make_offset

- docs/docs/noir/concepts/data_types/fields.md
- docs/docs/noir/standard_library/bn254.md
- noir_stdlib/src/field/bn254.nr
Resolves #4138
Add some small docs and add code comments to explain the not-obvious checks.
Check one:
> chore: Document bn254 lib

- docs/package.json
- docs/src/pages/index.jsx
- yarn.lock
Resolves #4092
This PR deletes the Noir playground off of the homepage of the docs so it doesn't interfere.
Check one:
> chore(docs): remove playground

- docs/src/pages/index.jsx
Resolves 
Not sure why CI didn't catch this on a PR but this link is dead.
Check one:
> chore: fix dead link in docs

- docs/versioned_docs/version-v0.19.0/language_concepts/data_types/01_integers.md
- docs/versioned_docs/version-v0.19.1/language_concepts/data_types/01_integers.md
- docs/versioned_docs/version-v0.19.2/language_concepts/data_types/01_integers.md
- docs/versioned_docs/version-v0.19.3/language_concepts/data_types/01_integers.md
- docs/versioned_docs/version-v0.22.0/noir/syntax/data_types/integers.md
Resolves #4272 
Addresses typos
Check one:
> chore: fix typos

- docs/docs/getting_started/installation/other_install_methods.md
- docs/versioned_docs/version-v0.23.0/getting_started/installation/other_install_methods.md
- docs/versioned_docs/version-v0.24.0/getting_started/installation/other_install_methods.md
Updates the install scripts to reference the correct versions.
Resolves 
#4271 
Check one:
> fix(docs): update install versions

- compiler/wasm/src/lib.rs
Resolves https://github.com/noir-lang/noir/issues/3879
Check one:
> chore: rename parameter 'filter' to 'level' in 'init_log_level'

- compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs
Resolves 
This removes some unwanted prints which were left in from #4376
Check one:
> chore: remove unwanted prints

- noir_stdlib/src/collections/bounded_vec.nr
- noir_stdlib/src/hash/poseidon2.nr
Resolves 
This PR fixes the formatting CI
Check one:
> chore: nargo fmt

- compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs
Resolves #4449 
The issue is fixed by implementing an iterative version of the flattening pass.
Check one:
> fix: iterative flattening pass

- tooling/bb_abstraction_leaks/build.rs
- tooling/noir_js_backend_barretenberg/package.json
- yarn.lock
Resolves #4468
Throwing this up here so we're ready for when the artifacts are finally published on GH.
Check one:
> chore: bump bb to 0.26.3

- Cargo.lock
- acvm-repo/bn254_blackbox_solver/Cargo.toml
> chore: update various dependencies

- .github/ACVM_NOT_PUBLISHABLE.md
- .github/CRATES_IO_PUBLISH_FAILED.md
- .github/DEAD_LINKS_IN_DOCS.md
- .github/JS_PUBLISH_FAILED.md
Resolves 
We're not opening issues when we should from CI because of missing commas in the lists of assignees. I've also removed Kev from being pinged.
Check one:
> chore: fix assignees for opening issues

- docs/docs/noir/concepts/data_types/integers.md
> chore: Update integers.md to note support for Fields using `from_integer`

- compiler/noirc_evaluator/src/ssa.rs
Resolves https://github.com/noir-lang/noir/pull/4659#discussion_r1543090914
Check one:
> chore: Add `time` helper

- .github/Cross.toml
Resolves 
Followup to #4703 and #4705.
Check one:
> chore: remove unused env vars from `Cross.toml`

- acvm-repo/acir/src/circuit/opcodes/black_box_function_call.rs
Resolves 
This function is unused.
Check one:
> chore: remove `FunctionInput::dummy`

- .github/workflows/gates_report.yml
Resolves this comment https://github.com/noir-lang/noir/pull/4719#issuecomment-2040362061. We want to test going back to handling the reference content the same way.
Check one:
> fix: Update gates report commit 

- .github/workflows/publish-es-packages.yml
Resolves 
This does some fixes to the publishing workflow to account for #4679 
Check one:
> chore: update JS publish workflow to upload build artifacts correctly.

- .github/workflows/release.yml
Resolves 
This is not triggering correctly atm so I'm switching to a more explicit syntax.
Check one:
> chore: update condition for clearing warning comment on release PRs

- .github/workflows/gates_report.yml
Resolves https://github.com/noir-lang/noir/pull/4764#issuecomment-2047911499
This is the noir-gates-diff PR this commit update references: https://github.com/TomAFrench/noir-gates-diff/pull/3.
Check one:
> fix: Update commit for noir-gates-diff

- .github/workflows/test-rust-workspace-msrv.yml
Resolves 
This workflow was failing due to the checkout step being skipped.
Check one:
> chore: fix alerts on rust msrv

- test_programs/execution_success/regression_3051/Nargo.toml
- test_programs/execution_success/regression_3051/src/main.nr
Resolves #3051
This issue has been fixed and so I'm added a regression test.
Check one:
> chore: add regression test for #3051

- compiler/wasm/src/compile.rs
- compiler/wasm/src/compile_new.rs
Resolves 
We don't need to construct these manually as we have functions for this.
Check one:
> chore: avoid manual creation of contract artifact in wasm

- Cargo.lock
- compiler/noirc_driver/src/abi_gen.rs
- compiler/noirc_driver/src/lib.rs
- tooling/noirc_abi/Cargo.toml
- tooling/noirc_abi/src/lib.rs
Resolves 
I'm not sure why this code was placed here. This code is only relevant for ABI gen so I've pushed it into the`abi_gen` module. This simplifies the dependency graph.
Check one:
> chore: push code related to ABI gen into `noirc_driver`

- tooling/nargo_cli/src/cli/compile_cmd.rs
Resolves 
This PR pulls across the changes from https://github.com/AztecProtocol/aztec-packages/pull/6488 to avoid making changes in aztec-packages unnecessarily and get around the CI issues over there.
Check one:
> chore: simplify compilation flow to write to file immediately

- noir_stdlib/src/compat.nr
Resolves 
This PR addresses a TODO in the stdlib now that #5245 is resolved.
Check one:
> chore: address TODO in `compat.nr`

- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
Resolves 
Applies the macro processors when we're using the elaborator too.
I wasn't able to test this well since running `nargo t` in `aztec-nr` produces quite a few errors regardless of whether we're using the elaborator or legacy code.
Check one:
> fix: Run macro processors in the elaborator

- docs/docs/explainers/explainer-oracle.md
- docs/docs/how_to/how-to-oracles.md
- docs/docs/how_to/how-to-recursion.md
- docs/docs/how_to/how-to-solidity-verifier.md
Thanks omahs for https://github.com/noir-lang/noir/pull/5486. Our policy is to redo typo changes to dissuade metric farming. This is an automated script.
> chore: redo typo PR by omahs

- .github/workflows/test-js-packages.yml
Resolves 
This PR resolves the issue where CI isn't running the end step.
Check one:
> chore(ci): remove bad colon in yaml file

- compiler/noirc_frontend/src/elaborator/expressions.rs
Resolves https://github.com/noir-lang/noir/issues/5539
Use `try_definition` instead of `definition` in case there is an error when resolving a macro.
Check one:
> fix: Don't panic when a macro fails to resolve

- .github/workflows/test-js-packages.yml
> chore: disable aztec-packages CI checks

- compiler/noirc_frontend/src/tests.rs
Resolves #2548
Just adds a regression test.
None.
Check one:
> chore: Add a regression test for bit not on untyped integer

- docs/docusaurus.config.ts
- docs/src/components/Notes/_blackbox.mdx
The trailing slash saga that keeps on giving. Removed pretty links from netlify but that came with another issue. Let's hope this PR fixes it (waiting for the preview)
> chore(docs): nasty linky

- docs/docs/noir/standard_library/containers/hashmap.md
- noir_stdlib/src/collections/map.nr
Part of https://github.com/noir-lang/noir/issues/5797
Check one:
> chore: document HashMap

- docs/docs/noir/concepts/generics.md
- test_programs/compile_failure/arithmetic_generics_intermediate_underflow/src/main.nr
- test_programs/compile_failure/arithmetic_generics_underflow/src/main.nr
> fix: Fix some mistakes in arithmetic generics docs

- compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
Resolves 
https://github.com/noir-lang/noir/pull/5935 added logic to remove trivial stores, however, it also had to track whether the alst instruction was an `inc_rc` or `dec_rc` instruction. After https://github.com/AztecProtocol/aztec-packages/pull/8448 we can remove that logic.
Removes `inside_rc_reload` from mem2reg, its tracking method, and its ussage.
Before https://github.com/AztecProtocol/aztec-packages/pull/8448 we were creating extra trivial stores. The majority of the code size benefit comes from that PR avoiding the creation of those stores in the first place. This PR is truly simply a clean-up that removes unnecessary logic. I do not foresee large bytecode size increases from this removal as the majority of the benefit came in the new array layout.
Check one:
> chore: Remove RC tracking in mem2reg

- noir_stdlib/src/meta/ctstring.nr
> chore: Fix docs

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- docs/docs/noir/standard_library/meta/expr.md
- noir_stdlib/src/meta/expr.nr
- test_programs/noir_test_success/comptime_expr/src/main.nr
> feat: add `Expr::as_for` and `Expr::as_for_range`

- test_programs/compile_success_empty/type_path/src/main.nr
> chore: fix broken formatting on master

- .github/workflows/mirror-external_libs.yml
- .github/workflows/test-js-packages.yml
Resolves 
Testing these again now that aztec-nr doesn't have 40k warnings.
Check one:
> chore: enable tests on aztec-nr and contracts

- test_programs/noir_test_success/bounded_vec/src/main.nr
> chore: fix typo in code snippet

- compiler/noirc_evaluator/src/ssa/opt/normalize_value_ids.rs
> fix: handle dfg databus in SSA normalization

- noir_stdlib/src/schnorr.nr
Resolves #6266 
This PR adds the fix specified in #6266, thanks to @jewelofchaos9 for raising this issue :pray: 
Check one:
> fix: address inactive public key check in `verify_signature_noir`

- docs/docs/explainers/explainer-writing-noir.md
Update title
Feedback from target audience
Check one:
> chore: Update title from feedback

- compiler/noirc_evaluator/src/ssa/function_builder/mod.rs
Resolves 
@jfecher mentioned in 1:1 that we should not be incrementing the reference count here.
Check one:
> feat: do not increment reference counts on arrays through references

- README.md
Not sure when the directory structure was changed, there may be more, but dead link in README is not gud :(
Check one:
> chore: Replace dead link with updated route in README

- compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs
Resolves 
This PR just replaces some tests using the `FunctionBuilder` with usage of the SSA parser for greater readability.
Check one:
> chore: convert some tests to use SSA parser

- .github/workflows/test-js-packages.yml
> chore: pin foundry version in CI

- test_programs/memory_report.sh
Resolves 
This PR adds the case that @vezenovm suggested to the memory report.
Check one:
> chore: add `ram_blowup_regression` to memory report

- .github/workflows/release.yml
Resolves 
The current release-please action is deprecated so I'm migrating to the new one.
Check one:
> chore: update release-please action

- docs/docs/noir/standard_library/meta/op.md
Thanks Madmaxs2 for https://github.com/noir-lang/noir/pull/6602. Our policy is to redo typo changes to dissuade metric farming. This is an automated script.
> chore: redo typo PR by Madmaxs2

- docs/docs/noir/concepts/data_types/fields.md
Resolves #6839 
Fixes the docs issue flagged in #6839
Check one:
> chore: quick docs fix for #6839

- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- compiler/noirc_frontend/src/parser/errors.rs
- compiler/noirc_frontend/src/parser/parser/impls.rs
- compiler/noirc_frontend/src/parser/parser/traits.rs
- tooling/lsp/src/requests/mod.rs
- tooling/nargo_fmt/src/formatter/function.rs
- tooling/nargo_fmt/src/formatter/impls.rs
- tooling/nargo_fmt/src/formatter/item.rs
- tooling/nargo_fmt/src/formatter/trait_impl.rs
- tooling/nargo_fmt/src/formatter/traits.rs
- tooling/nargo_fmt/src/lib.rs
> feat: warn on trait method visibility

- .github/workflows/reports.yml
> chore: bump `noir-gates-diff`

- tooling/nargo_cli/build.rs
> chore: Move comment as part of #6945

- noir_stdlib/src/uint128.nr
> feat: impl Default for U128

- compiler/noirc_frontend/src/elaborator/types.rs
> chore: clippy warning fix

- .github/workflows/reports.yml
> chore: relax threshold for reporting regressions

- .github/workflows/reports.yml
> chore: bump gates diff

- .github/workflows/test-js-packages.yml
- EXTERNAL_NOIR_LIBRARIES.yml
> chore: replace benchmarks on fast test suites with a cut-off

- test_programs/memory_report.sh
> chore: fix memory reports in CI

- compiler/noirc_evaluator/src/ssa/checks/check_for_underconstrained_values.rs
Resolves 
clippy fixes
Check one:
> chore: fix warnings

- acvm-repo/brillig_vm/src/arithmetic.rs
- acvm-repo/brillig_vm/src/lib.rs
- compiler/noirc_evaluator/src/ssa/ir/instruction/binary.rs
- compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs
> fix: made changes to the shifts

- noir_stdlib/src/hash/keccak.nr
Resolves 
Followup to #7351 
Check one:
> chore: deprecate keccak256

- .github/benchmark_projects.yml
- EXTERNAL_NOIR_LIBRARIES.yml
> chore: bump aztec-packages commit

- Cargo.lock
- deny.toml
> chore: bump ring to address advisory

- tooling/acvm_cli/src/cli/execute_cmd.rs
Resolves 
Supercedes https://github.com/AztecProtocol/aztec-packages/pull/10343
Check one:
> feat: add optional oracle resolver url in `acvm_cli`

- .github/benchmark_projects.yml
- EXTERNAL_NOIR_LIBRARIES.yml
Resolves 
people are complaining
Check one:
> chore: fixing timeouts

- compiler/wasm/scripts/install_wasm-pack.sh
> chore: bump wasm-pack to 0.13.1

- README.md
noir-lang.org/docs (without slash) is currently broken
Check one:
> chore: Update README.md to add trailing docs `/`

- Cargo.lock
- deny.toml
- tooling/acvm_cli/Cargo.toml
> chore: add cargo deny advisory

- .github/workflows/rustdoc.yml
- compiler/noirc_frontend/src/tests.rs
- docs/docs/noir/concepts/data_types/references.md
- docs/docs/noir/concepts/mutability.md
Resolves #7698 
This issue was resolved by https://github.com/noir-lang/noir/pull/7488. I have included an additional regression test for the snippet within the issue.
Check one:
> chore(frontend): Regression test for creating a mutable reference to an array element

- docs/docusaurus.config.ts
> chore: update docusaurus config to correct trailing slash issue

- compiler/noirc_frontend/src/elaborator/patterns.rs
No issue, small bug 
```
^^^^^
solve these
```
Is invalid in a Rust block
Check one:
> chore: Fix rustdocs error

- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/infix.rs
Resolves #7440
This PR breaks out a few functions which are really pure so we can add more testing for them in future.
Check one:
> chore: pull out pure functions from interpreter

- .github/workflows/test-js-packages.yml
- EXTERNAL_NOIR_LIBRARIES.yml
> chore: add more test suites to CI

- docs/README.md
It is not clear what version of node or yarn to use to run the docs locally.
This PR adds versions that work.
Check one:
> chore(docs): Add docs dev prereqs to README

- tooling/lsp/src/requests/hover.rs
- tooling/lsp/src/requests/hover/from_reference.rs
- tooling/lsp/test_programs/workspace/two/src/lib.nr
> fix(LSP): bring back global values on hover

- noir_stdlib/src/array/check_shuffle.nr
Resolves 
This PR resolves some warnings in the stdlib added by #7820 
Check one:
> fix: address warnings in stdlib

- tooling/nargo_fmt/src/formatter/types.rs
> fix(formatter): format `&[...]` type

- tooling/noir_codegen/src/utils/typings_generator.ts
- tooling/noir_codegen/test/index.test.ts
- tooling/noir_codegen/test/test_lib/src/lib.nr
> fix(noir_codegen): allow exporting argless functions

- docs/docs/tooling/profiler.md
- docs/versioned_docs/version-v1.0.0-beta.0/getting_started/setting_up_shell_completions.md
- docs/versioned_docs/version-v1.0.0-beta.1/getting_started/setting_up_shell_completions.md
- docs/versioned_docs/version-v1.0.0-beta.2/getting_started/setting_up_shell_completions.md
- docs/versioned_docs/version-v1.0.0-beta.3/getting_started/setting_up_shell_completions.md
Resolves #7921 
Resolves #7938 
Check one:
> chore: fix documentation nits

- acvm-repo/acvm/benches/arithmetic_solver.rs
> chore: correct name of acvm benchmark

- tooling/ast_fuzzer/src/program/func.rs
> fix(fuzz): remove duplicate gen_loop, move unconstrained generators up

- compiler/noirc_evaluator/src/brillig/brillig_ir/instructions.rs
- compiler/noirc_evaluator/src/ssa/parser/tests.rs
- tooling/ssa_fuzzer/src/lib.rs
Resolves https://github.com/noir-lang/noir/issues/8083
Check one:
> fix(ssa): fix possibility to `Field % Field` operaions in Brillig from SSA

- compiler/noirc_evaluator/src/ssa/parser/into_ssa.rs
- compiler/noirc_evaluator/src/ssa/parser/tests.rs
> fix: let SSA parser parse calls to print

- compiler/noirc_evaluator/src/acir/arrays.rs
- compiler/noirc_evaluator/src/acir/mod.rs
Resolves 
This is mostly me just improving code readability so that we can optimize this without needing to worry about causing bugs.
I've added comments to call out various changes but it mostly boils down to finding cases where we're tackling the same problem in multiple ways and standardising on one method.
Check one:
> chore: refactor array handling in ACIRgen

- docs/docs/noir/modules_packages_crates/modules.md
Thanks ciaranightingale for https://github.com/noir-lang/noir/pull/8289. Our policy is to redo typo changes to dissuade metric farming. This is an automated script.
> chore: redo typo PR by ciaranightingale

- docs/versioned_docs/version-v1.0.0-beta.3/tutorials/noirjs_app.md
Thanks jennyg0 for https://github.com/noir-lang/noir/pull/8346. Our policy is to redo typo changes to dissuade metric farming. This is an automated script.
> chore: redo typo PR by jennyg0

- compiler/noirc_driver/src/lib.rs
- compiler/noirc_errors/src/position.rs
- compiler/noirc_evaluator/src/errors.rs
- compiler/noirc_frontend/src/ast/expression.rs
- compiler/noirc_frontend/src/ast/function.rs
- compiler/noirc_frontend/src/ast/statement.rs
- compiler/noirc_frontend/src/hir/comptime/errors.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- compiler/noirc_frontend/src/hir/def_collector/errors.rs
- compiler/noirc_frontend/src/hir/resolution/errors.rs
- compiler/noirc_frontend/src/hir/type_check/errors.rs
- compiler/noirc_frontend/src/parser/errors.rs
> chore: remove some unused enum variants and functions

- compiler/noirc_evaluator/src/brillig/brillig_gen/variable_liveness.rs
- compiler/noirc_evaluator/src/ssa/ir/dfg.rs
- compiler/noirc_evaluator/src/ssa/ir/instruction/binary.rs
- compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs
- compiler/noirc_evaluator/src/ssa/opt/inlining.rs
- compiler/noirc_evaluator/src/ssa/opt/unrolling.rs
> fix(SSA): disallow using `lt` with fields

- acvm-repo/blackbox_solver/src/ecdsa/secp256k1.rs
- acvm-repo/blackbox_solver/src/ecdsa/secp256r1.rs
Resolves 
This PR adds a few warnings to help debugging
Check one:
> chore: add logging for signature failure cases which break barretenberg

- .github/workflows/deny.yml
> chore: bump cargo deny

- compiler/noirc_evaluator/src/acir/acir_context/mod.rs
- tooling/ssa_executor/src/lib.rs
> fix: prevent `bound_constraint_with_offset` from panicking

- test_programs/benchmarks/semaphore_depth_10/Nargo.toml
Resolves 
Addresses a visibility issue.
Check one:
> chore: bump noir-edwards dep

- .github/critical_libraries_status/noir-lang/noir_bigcurve/.failures.jsonl
- EXTERNAL_NOIR_LIBRARIES.yml
> chore: mark bignum as expected to pass

- .config/nextest.toml
- .github/workflows/test-rust-workspace-arm64.yml
- .github/workflows/test-rust-workspace-msrv.yml
- .github/workflows/test-rust-workspace.yml
> chore: skip `ram_blowup_regression` on PRs

- compiler/noirc_evaluator/src/ssa/opt/assert_constant.rs
Resolves #9407
Also updates a comment to be more accurate.
Check one:
> chore: add some `assert_constant` tests

- .github/benchmark_projects.yml
- .github/workflows/test-js-packages.yml
- EXTERNAL_NOIR_LIBRARIES.yml
Automated update of the pinned commit of [aztec-packages](https://github.com/AztecProtocol/aztec-packages) repository against which we run benchmarks.
> chore: bump external pinned commits

- compiler/noirc_evaluator/src/ssa/opt/remove_bit_shifts.rs
> chore: Revert "chore: remove redundant `enforce_bitshift_rhs_lt_bit_size`"

- tooling/ssa_fuzzer/fuzzer/src/fuzz_lib/block_context.rs
- tooling/ssa_fuzzer/fuzzer/src/fuzz_lib/instruction.rs
- tooling/ssa_fuzzer/fuzzer/src/fuzz_lib/options.rs
- tooling/ssa_fuzzer/fuzzer/src/fuzz_lib/tests/embedded_curve_ops.rs
- tooling/ssa_fuzzer/fuzzer/src/fuzz_lib/tests/mod.rs
- tooling/ssa_fuzzer/fuzzer/src/fuzz_target.rs
- tooling/ssa_fuzzer/fuzzer/src/mutations/basic_types/mod.rs
- tooling/ssa_fuzzer/fuzzer/src/mutations/basic_types/point.rs
- tooling/ssa_fuzzer/fuzzer/src/mutations/basic_types/scalar.rs
- tooling/ssa_fuzzer/fuzzer/src/mutations/configuration.rs
- tooling/ssa_fuzzer/fuzzer/src/mutations/instructions/instruction_block_mutator.rs
- tooling/ssa_fuzzer/fuzzer/src/mutations/instructions/instruction_mutator.rs
- tooling/ssa_fuzzer/src/builder.rs
- tooling/ssa_fuzzer/src/typed_value.rs
Add intrinsic calls
+ embedded_curve_add
+ multi_scalar_mul
Resolves 
Check one:
> feat(ssa_fuzzer): embedded curve ops

- compiler/noirc_evaluator/src/ssa/opt/inlining.rs
> chore: remove redundant globals creation

- compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
No issue. 
I thought there was an issue here but in the end it was working well. Given that we don't have such tests it might be better to have them (especially considering the mem2reg complexity).
I wonder if for slice intrinsics like slice_push_back we can do better. I think right now we'll consider the returned slice as having unknown aliases, if the returned slice has references, but in fact the references will be the same as in the input slice. But it's maybe a not very good optimization.
Check one:
> chore: add two mem2reg regression tests where references are returned

- compiler/noirc_evaluator/src/ssa/validation/mod.rs
- tooling/ssa_fuzzer/fuzzer/src/fuzz_lib/block_context.rs
- tooling/ssa_fuzzer/fuzzer/src/fuzz_lib/instruction.rs
- tooling/ssa_fuzzer/fuzzer/src/fuzz_lib/tests/ecdsa.rs
- tooling/ssa_fuzzer/fuzzer/src/mutations/instructions/instruction_block_mutator.rs
- tooling/ssa_fuzzer/fuzzer/src/mutations/instructions/instruction_mutator.rs
- tooling/ssa_fuzzer/src/builder.rs
> chore: validate SSA blackbox function calls

- .github/workflows/nightly-fuzz-test.yml
> chore(ci): alert in slack if fuzzer fails

- docs/docs/noir/concepts/functions.md
- tooling/lsp/src/requests/completion.rs
- tooling/ssa_fuzzer/README.md
Thanks viktorking7 for https://github.com/noir-lang/noir/pull/9936. Our policy is to redo typo changes to dissuade metric farming. This is an automated script.
> chore: redo typo PR by viktorking7

- .github/workflows/nightly-fuzz-test.yml
> chore(ci): only send slack notifications during the week

- Cargo.lock
- deny.toml
- tooling/ssa_fuzzer/fuzzer/.gitignore
- tooling/ssa_fuzzer/fuzzer/Cargo.toml
- tooling/ssa_fuzzer/fuzzer/src/abstract_vm_integration.rs
- tooling/ssa_fuzzer/fuzzer/src/brillig.rs
> chore(ssa_fuzzer): add external coverage registration 

- compiler/noirc_evaluator/src/acir/mod.rs
No issue, just some duplication I noticed while reviewing ACIR-gen.
Check one:
> chore(ACIR): extract convert_constrain_error helper
