- .github/workflows/recrawler.yml
This PR adds a workflow to request a docs website recrawl
We kind of missed this when we merged docs to the monorepo, so search on the docs can be out of date sometimes. Manual triggering was needed
With this action, crawling will be triggered automatically
> chore: recrawl docs on merge

- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/def_collector/errors.rs
- compiler/noirc_frontend/src/hir/type_check/expr.rs
- compiler/noirc_frontend/src/hir/type_check/mod.rs
- compiler/noirc_frontend/src/hir_def/traits.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
- compiler/noirc_frontend/src/node_interner.rs
- compiler/noirc_frontend/src/tests.rs
- tooling/nargo_cli/tests/compile_failure/overlapping_generic_impls/Nargo.toml
- tooling/nargo_cli/tests/compile_failure/overlapping_generic_impls/src/main.nr
- tooling/nargo_cli/tests/compile_success_empty/trait_override_implementation/src/main.nr
- tooling/nargo_cli/tests/execution_success/trait_impl_base_type/src/main.nr
Resolves 
Adds a check for overlapping generic traits such as two `impl<T> Foo for T` impls. This PR also does some refactoring to slowly move impl selection into the name resolver / type checker. Notably, struct and primitive impls are treated more uniformly in that they both allow for multiple methods of the same name to be implemented on them. This is important not only for implementing the same trait e.g. `impl Foo for Bar<u32>` and `impl Foo for Bar<u64>`, but also for implementing multiple traits on the same type which happen to share method names.
This PR does not go all the way in the overlap checking. Notably the unification check needs to be changed to instantiate any named generics. I'll do this in a PR tomorrow. Once this is done we'll have overlap checking for generics in …
> feat: Add check for overlapping generic traits

- tooling/nargo_cli/tests/compile_success_empty/brillig_modulo/src/main.nr
Resolves #3275 
Activate the test with negative integers, the tests are working for me.
Check one:
> fix(3275): activate brillig modulo test with negative integers

- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- tooling/nargo_cli/tests/compile_success_empty/impl_with_where_clause/Nargo.toml
- tooling/nargo_cli/tests/compile_success_empty/impl_with_where_clause/src/main.nr
Resolves 
This was a smaller change than initially expected. Since functions already allow a `where` clause, I just copied the where clause constraints on the impl itself into the function's where clause.
Check one:
> feat: Implement where clauses on impls

- compiler/noirc_frontend/src/hir/def_collector/errors.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_frontend/src/node_interner.rs
- tooling/nargo_cli/tests/compile_failure/overlapping_generic_impls/src/main.nr
Fixes the final part of the overlap check from https://github.com/noir-lang/noir/pull/3307 to work for all generic types.
https://github.com/noir-lang/noir/pull/3307 implemented the overlap check for traits and most of the infrastructure required for it, but it was largely identical to the previous check we had which checked types via basic equality without handling type variables. So previously if you had an impl for `impl<T> Foo for T` and `impl Foo for u32`, they would not be caught as overlapping.
This PR implements the final key to the overlap check which is instantiating the generics in the type before trying to unify them. With this, the above error is caught.
Check one:
> feat: Expand trait impl overlap check to cover generic types

- .github/workflows/recrawler.yml
Once #3330 is merged, we won't have the recrawler. This PR adds it back.
Resolves 
Check one:
> chore: add back algolia recrawler

- docs/docs/getting_started/00_nargo_installation.md
- docs/versioned_docs/version-0.17.0/getting_started/00_nargo_installation.md
Remove Windows from binaries section and add a WSL section
Resolves https://github.com/noir-lang/noir/issues/3327#issue-1966578909
Remove Windows from binaries section and add a WSL section
Check one:
> chore(docs): Update Windows installation 

- noir_stdlib/src/hash.nr
- tooling/nargo_cli/tests/execution_success/hash_to_field/src/main.nr
I think we can merge this into #3338 
Resolves 
Check one:
> chore: add `hash_to_field_native` function

- Cargo.lock
- acvm-repo/acir/Cargo.toml
- acvm-repo/acir/src/circuit/mod.rs
- acvm-repo/acir/tests/test_program_serialization.rs
- acvm-repo/acvm_js/src/execute.rs
- acvm-repo/acvm_js/src/public_witness.rs
- compiler/noirc_driver/Cargo.toml
- compiler/noirc_driver/src/contract.rs
- compiler/noirc_driver/src/program.rs
- compiler/wasm/src/circuit.rs
- tooling/backend_interface/src/proof_system.rs
- tooling/backend_interface/src/smart_contract.rs
- tooling/nargo/Cargo.toml
- tooling/nargo/src/artifacts/contract.rs
- tooling/nargo/src/artifacts/mod.rs
- tooling/nargo/src/artifacts/program.rs
This removes the TODO which we had regarding moving serialization logic into ACIR. 
The read and write methods have been made private, so technically this a breaking change. They were only being used for the serialize and deserialize methods., but since its on the public API I've marked this PR as breaking.
Resolves 
Check one:
> chore!: Move circuit serialization circuit into acir

- noir_stdlib/src/field.nr
- noir_stdlib/src/hash.nr
- tooling/nargo_cli/tests/execution_success/hash_to_field/src/main.nr
Related to https://github.com/noir-lang/acvm/issues/358
This only adds a test to show that we can implement the hash_to_field blackbox function in Noir.
Since hash_to_field takes Field elements as parameters, the decomposition shown is needed to hash a ~254 bit element instead of a single u8.
Resolves 
Check one:
> chore: Add `hash_to_field` Noir alternative

- .github/workflows/publish-nargo.yml
Resolves 
Tom: This PR makes releases pre-releases by default. This fixes the issue where aztec releases are immediately set to be the latest release which breaks `noirup`.
Check one:
> chore: make releases pre-releases by default

- .github/workflows/auto-pr-rebuild-script.yml
- .github/workflows/formatting.yml
- .github/workflows/gates_report.yml
- .github/workflows/publish-acvm.yml
- .github/workflows/publish-nargo.yml
- .github/workflows/test-integration.yml
- .github/workflows/test-noir-js.yml
- .github/workflows/test-noir_wasm.yml
- .github/workflows/test-rust-workspace.yml
- README.md
- docs/docs/getting_started/00_nargo_installation.md
- flake.nix
- rust-toolchain.toml
- tooling/nargo/build.rs
- tooling/nargo_cli/build.rs
- tooling/nargo_fmt/src/utils.rs
Resolves 
This PR bumps us up to target an MSRV of 1.71.1
Check one:
> chore!: bump MSRV to 1.71.1

- compiler/noirc_frontend/src/lexer/lexer.rs
Using `Peekable` is not the most efficient choice because its "next" function is slower than the underlying iterator's "next," and calling it is a performance bottleneck.
Resolves #3334 
Check one:
> chore: correct handling of unicode in lexer

- compiler/noirc_frontend/src/ast/statement.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/parser/mod.rs
- compiler/noirc_frontend/src/parser/parser.rs
- tooling/nargo_fmt/src/visitor/stmt.rs
- tooling/nargo_fmt/tests/expected/for.nr
- tooling/nargo_fmt/tests/input/for.nr
> chore: format `for` stmt

- .github/workflows/test-abi_wasm.yml
- .github/workflows/test-acvm-js.yml
- .github/workflows/test-integration.yml
- .github/workflows/test-noir_wasm.yml
- cspell.json
Resolves 
This PR fixes a bunch of inconsistencies in the CI setup and standardises how we use nix.
Check one:
> chore: cleanup CI workflows to be more consistent

- .github/workflows/auto-pr-rebuild-script.yml
Resolves 
We're currently never publishing ACIR artifacts on master as seen in this CI run: https://github.com/noir-lang/noir/actions/runs/6699174556/job/18202815460
The issue seems to be a matter of quotation marks in the if statement so this PR removes them.
Check one:
> chore(ci): ensure that acir artifacts are published on master

- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/type_check/expr.rs
- compiler/noirc_frontend/src/hir_def/traits.rs
- compiler/noirc_frontend/src/node_interner.rs
- tooling/nargo_cli/tests/compile_success_empty/trait_generics/src/main.nr
Resolves 
Allows traits to define generic functions such as:
```rs
trait Foo {
fn foo<T>(self, x: T) -> T;
}
```
Impls can implement these functions as well, although there is no check that the impl has the same number of generics as the original trait function was. This turned out to be a bit more work so I'll include this in a separate PR.
Check one:
> feat: Allow traits to have generic functions

- .github/workflows/auto-pr-rebuild-script.yml
Resolves 
Followup to #3367 which replaces bash with the `@actions/github-script. This is also more consistent with how we handle checking for labels when dealing with the docs.
Check one:
> chore: replace bash with `@actions/github-script`

- .github/workflows/test-integration.yml
Resolves 
This PR builds the acvm_js package in parallel to the other nix packages in the integration test workflow. This should save a few minutes from CI time.
Check one:
> chore: build acvm_js for integration tests in parallel

- compiler/noirc_driver/src/lib.rs
- tooling/nargo_toml/src/semver.rs
Resolves 
Splitting off some small refactorings to `noirc_driver` from another PR.
Check one:
> chore: small driver refactors

- compiler/noirc_frontend/src/hir/aztec_library.rs
For loops were changed and this was not updated.
Resolves 
Check one:
> chore: fix for-loop in aztec-library

- .github/workflows/build-aztec-feature-flag.yml
Since the feature flag is not on by default, there are cases where we make compiler changes and forget to update the code under the feature flag. These are cosmetic changes, like changing the for-loop structure. This just adds a build step.  
Resolves 
Check one:
> chore: Add a workflow to build with feature flag

- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/def_collector/errors.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- tooling/nargo_cli/tests/compile_failure/trait_incorrect_generic_count/Nargo.toml
- tooling/nargo_cli/tests/compile_failure/trait_incorrect_generic_count/src/main.nr
Adds a check that trait impl methods have the same number of generics as the trait they implement.
Note that in the corner case of:
```rs
trait Trait {
fn trait_fn<T>(x: T) -> T;
}
impl<T> Trait for T {
fn trait_fn(x: T) -> T { x }
}
```
We match rust's behavior in disallowing this. 
Check one:
> feat: Add generic count check for trait methods

- Cargo.lock
- acvm-repo/barretenberg_blackbox_solver/Cargo.toml
- deny.toml
Resolves https://github.com/noir-lang/acvm/issues/521
This bumps wasmer to 4.2.3 to avoid the potential issue that Kev reported on the old repository.
Check one:
> chore: bump wasmer version to 4.2.3

- .github/workflows/publish-es-packages.yml
- .github/workflows/test-abi_wasm.yml
- .github/workflows/test-acvm-js.yml
- .github/workflows/test-integration.yml
- .github/workflows/test-noir_wasm.yml
Replace NIX_CACHE_NAME with "noir" in CI to resolve the accessibility issue for forked repositories.
The problem is that the `vars.NIX_CACHE_NAME` variable is not accessible to forks of the repository, leading to inconsistency and potential workflow failures for those who depend on this variable. 
Check one:
> chore: update nix cache name in workflows

- compiler/noirc_frontend/src/hir/aztec_library.rs
fixes: https://github.com/AztecProtocol/aztec-packages/issues/3193
locally:
- recompiled, rebased onto head of kevs hack branch, ran local aztec tests and they passed, so this does not break existing behaviour.
Aztec macros did not gracefully handle arrays of structs yet, this pr adds that functionality
Check one:
> fix(aztec_nr): serialise arrays of structs

- Cargo.lock
Resolves 
This PR removes a bunch of unnecessarily duplicated dependencies, updates us to move off of yanked versions and updates clap which has had a bunch of compilation speed improvements recently.
Check one:
> chore: bump cargo dependencies

- compiler/noirc_frontend/src/lexer/lexer.rs
- compiler/noirc_frontend/src/lexer/token.rs
> chore: Allow apostrophes in attributes

- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/hir/type_check/errors.rs
- compiler/noirc_frontend/src/hir/type_check/expr.rs
- compiler/noirc_frontend/src/hir/type_check/mod.rs
- compiler/noirc_frontend/src/hir_def/function.rs
- compiler/noirc_frontend/src/hir_def/traits.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
- compiler/noirc_frontend/src/node_interner.rs
- tooling/nargo_cli/tests/compile_failure/no_nested_impl/Nargo.toml
- tooling/nargo_cli/tests/compile_failure/no_nested_impl/src/main.nr
- tooling/nargo_cli/tests/compile_success_empty/impl_with_where_clause/src/main.nr
- tooling/nargo_cli/tests/compile_success_empty/trait_where_clause/src/main.nr
Previously when searching for a trait impl for a type such as `[A]`, an impl such as `impl Foo for [T] where T: Eq` would be selected without verifying whether `A` implemented `Eq` at all. This would later cause a panic during monomorphization if there was no such impl. For this PR, I've added a check to recursively verify all trait constraints have impls.
The error that is issued in the example program is:
```
error: No matching impl found for `Field: Eq`
┌─ /../program/src/main.nr:4:12
│
4 │     assert(a.eq(a));
│            ------- No impl for `Field: Eq`
│
= Required by `[Field; 2]: Eq`
= Required by `[[Field; 2]; 2]: Eq`
= Required by `[[[Field; 2]; 2]; 2]: Eq`
= Required by `[[[[Field; 2]; 2]; 2]; 2]: Eq`
```
Note the "Required by" clauses which are helpful in tracking down where …
> feat: Check where clauses when searching for trait impls

- docs/docs/language_concepts/data_types/01_integers.md
Document https://github.com/noir-lang/noir/pull/2748 and resolves https://github.com/noir-lang/noir/issues/3381 respectively.
- Document signed integers
- Document overflow behaviors of both unsigned and signed integers
- Update existing unsigned integer description and examples
Drafting this so that we could get v0.19.0 out sooner before Devconnect.
@guipublic would appreciate for your quick review.
Check one:
> chore(docs): Document signed integers and integer overflow behavior

- .github/workflows/auto-pr-rebuild-script.yml
Resolves 
We currently don't run the `auto-pr-rebuild-script` job on master for reason connected to how github actions handles conditions. This PR moves this condition to only cover the artifact upload so I can debug it more easily.
Check one:
> chore(ci): fix rebuild acir artifacts workflow

- .github/workflows/build-docs.yml
Further to https://github.com/noir-lang/noir/pull/3349, part of our docs are now automatically generated instead of manually written.
At times we might want the flexibility to trigger a doc build manually to e.g. gather such generated docs (in addition to building docs along Noir pre-releases), but we currently don't have the option.
This PR adds the ability to manually run the "Build docs" action.
Reference: [Manually running a workflow | GitHub Docs](https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow)
Demo: https://github.com/noir-lang-test/noir/actions/workflows/build-docs.yml
The demo workflow failed as actions are not properly set up in the test repo, but with this PR merged we will get the same "Run workflow" button.
Check one:
> chore(github): Add manual trigger for building docs

- .github/workflows/build-docs.yml
Reverts noir-lang/noir#3439.
[Publish Docs](https://github.com/noir-lang/noir/actions/workflows/publish-docs.yml) rather than Build docs should actually be used for manually publishing new docs.
> chore(github): Revert "Add manual trigger for building docs"

- .github/workflows/publish-docs.yml
This PR fixes the publish-docs workflow to fit the autogeneration of noirjs docs
Publish-docs fails
For the autogeneration, a build must be present. That wasn't required previously, so this PR adds it
> chore: fixing autogenned docs for publish-docs

- .github/workflows/docs-new-version.yml
- .github/workflows/docs-pr.yml
- .github/workflows/docs-release.yml
- .github/workflows/release.yml
This adds a new workflow to run on the "release" event.
When we make a release "stable", no event runs (except release-please, which is ignored). So the docs are not rebuilt with the latest stable.
> chore: creating a workflow for the release trigger

- compiler/noirc_driver/build.rs
It seems that because the 'tests' folder doesn't exist, it forces Cargo to recompile every time.
Root cause: https://github.com/rust-lang/cargo/issues/4213
Check one:
> chore: remove `cargo:rerun-if-changed=tests` in noirc_driver

- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
Resolves 
This PR allows us to handle constant array indices on flat slices. We previously disabled constant index handling due to potential index-out-of-bounds errors but this is not a concern on flat slices.
This means that we can optimize out these array reads without the associated risk of errors from nested slices.
Check one:
> feat: handle constant index operations on simple slices

- compiler/noirc_frontend/src/hir/type_check/expr.rs
- compiler/noirc_frontend/src/parser/errors.rs
- compiler/noirc_frontend/src/parser/parser.rs
Resolves 
1. Allow `where` clauses even if a function has no generics. This is because the impl it is a part of may have generics.
2. Add TypeAnnotationsNeeded when calling a method on an unbound type variable. Without this we can get a confusing message like "method foo is not available for type Foo"  since the type variable may be bound before the error is issued, changing the message.
Check one:
> fix: Allow `where` clause on all functions and improve error message

- tooling/nargo_fmt/src/visitor.rs
- tooling/nargo_fmt/src/visitor/item.rs
- tooling/nargo_fmt/tests/expected/ignore.nr
- tooling/nargo_fmt/tests/input/ignore.nr
> chore: support directives to control whether noirfmt runs on a section of code 

- tooling/nargo_fmt/src/utils.rs
- tooling/nargo_fmt/src/visitor/item.rs
- tooling/nargo_fmt/tests/expected/fn.nr
- tooling/nargo_fmt/tests/input/fn.nr
Fix undesirable line break before '{' in function signature with comments
Resolves #3310 
Check one:
> chore: Fix undesirable line break before '{' in function signature with comments

- Cargo.lock
Resolves 
This PR fixes cargo deny CI due to a new advisory error.
Check one:
> chore: update `self_cell` to v1.0.2

- compiler/noirc_frontend/src/parser/parser.rs
The tests that I added to `parser` are quite unreadable.
Uses `concat!` macro to make multiline pieces of code. Adds a helper function to test mutiple cases and check their errors given a parser function.
Check one:
> chore: Refactor parser tests (with concat!())

- tooling/nargo_cli/tests/execution_success/conditional_regression_underflow/Nargo.toml
The project name needs to match the directory name for the rebuild script to work properly.
Resolves 
Check one:
> chore: fix project name in integration test

- tooling/bb_abstraction_leaks/build.rs
With the addition of #3437 -- we can compile without a backend. If one is on an arm64 linux build, they will get a compile time panic. This PR changes it to a warning and just doesn't set the environment variables for the bb binary.
Resolves 
Check one:
> chore: Remove panic on arm64 linux builds for bb binary at compile time

- tooling/bb_abstraction_leaks/build.rs
Unfortunately, we cannot test ARM64 in CI right now. Instead of using option_env due to us early returning in build.rs, I've opted to having it set an x86_64 url. on arm64 machines it should give an error and then default to the no backend context.
I tested this on my machine by manually setting the backend to download to one that is unsupported on my machine 
Resolves 
Check one:
> chore: remove early return from build.rs

- Cargo.toml
This PR adds two size profiles to compilation, `size` and `size-aggressive`.
If you want to use them you can do : `cargo build --profile size` or `cargo build --profile size-aggressive`
Resolves 
Check one:
> chore: Add build profiles that optimize for size

- Cargo.lock
- Cargo.toml
- tooling/nargo_cli/Cargo.toml
- tooling/nargo_cli/src/cli/fmt_cmd.rs
- tooling/nargo_fmt/Cargo.toml
```bash
❯ cargo r -- fmt --check
Differences (-original|+formatted):
fn main() {
let _callStackItem3 = context.call_private_function(
-        
inputs.call_context.storage_contract_address,
get_note_zero_fn_selector,
[owner]
);
❯ echo $?
1
```
```bash
❯ cargo r -- fmt --check
No formatting changes were detected
❯ echo $?
0
```
Resolves #3520 
Check one:
> feat: add --check option to nargo fmt for dry-run formatting verification

- docs/docusaurus.config.js
As the docs repo is now migrated into this noir repo, this PR updates the link in the docs from pointing to https://github.com/noir-lang/docs to https://github.com/noir-lang/noir/tree/master/docs.
Check one:
> chore(docs): Update link to docs' GitHub

- tooling/nargo_toml/src/errors.rs
When a package has a compiler version requirement incompatible with the current version, an error message is produced that contains the wrong suggested versions.
The current version reads:
```
Incompatible compiler version in package ecrecover. Required compiler version is 0.10.1 but the compiler version is 0.19.2.
Update the compiler_version field in Nargo.toml to >=0.19.2 or compile this project with version 0.19.2
```
While this isn't strictly wrong, it's an unintuitive suggestion versus one that refers to the package required versions like this:
```
Update the compiler_version field in Nargo.toml to >=0.10.1 or compile this project with version 0.10.1
```
This suggests the user to either update the package to accept later compiler version that's currently active (`>=0.10.1`) or to …
> fix: Compiler version error message

- .github/workflows/docs-pr.yml
- docs/package.json
- tooling/noir_js_types/package.json
- yarn.lock
Resolves 
The docs package requires noir_js build artifacts in order to codegen the docs but it doesn't have a dependency set up which causes a `yarn build` from a fresh repo to fail.
I've thrown in a refactor of the docs PR workflow to build the docs's dependencies automatically.
Check one:
> chore: add dependency on noir_js from docs package

- tooling/nargo_cli/tests/execution_success/array_dynamic/src/main.nr
- tooling/nargo_cli/tests/execution_success/brillig_scalar_mul/src/main.nr
- tooling/nargo_cli/tests/execution_success/brillig_schnorr/src/main.nr
- tooling/nargo_cli/tests/execution_success/schnorr/src/main.nr
> chore: nargo fmt

- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
The number 2 doesn't seem to have any weighting here and generally this naming scheme is discouraged as it provides any useful information
Resolves 
Check one:
> chore: Rename error2 variable

- compiler/noirc_evaluator/src/ssa/opt/mem2reg/block.rs
Working towards https://github.com/noir-lang/noir/issues/3380
Somewhat reduces the amount of memory used by the mem2reg pass by using shared immutable maps. With this PR, the mem2reg pass is able to analyze up to roughly 70k blocks (up from 20k) of the `test-bls-proving-time` crate in the issue above. Since the full program has 865k blocks, it still isn't close to running successfully with this PR.
I went through a lot of different tests in reducing memory usage in getting this PR up. This includes pruning old blocks, instructions, and values from the DataFlowGraph, pruning old blocks from the mem2reg's `blocks` field once there are no more successors, truncating the maximum length of the `CallStack` stored for each instruction or removing it entirely, etc. None of these changes made a …
> fix: Somewhat reduce mem2reg memory usage

- tooling/bb_abstraction_leaks/build.rs
- tooling/noir_js_backend_barretenberg/package.json
- yarn.lock
> chore: update barretenberg to 0.16.0

- tooling/nargo_fmt/src/rewrite/array.rs
- tooling/nargo_fmt/src/rewrite/expr.rs
- tooling/nargo_fmt/src/utils.rs
- tooling/nargo_fmt/src/visitor/expr.rs
- tooling/nargo_fmt/src/visitor/item.rs
- tooling/nargo_fmt/src/visitor/stmt.rs
- tooling/nargo_fmt/tests/expected/fn.nr
- tooling/nargo_fmt/tests/input/fn.nr
launch on our code base: #3587
Resolves https://github.com/noir-lang/noir/pull/3549#discussion_r1404263413
Check one:
> chore: update code formatting to prevent parameter line wrapping

- .github/workflows/test-js-packages.yml
- tooling/noir_js_backend_barretenberg/.mocharc.json
- tooling/noir_js_backend_barretenberg/package.json
- tooling/noir_js_backend_barretenberg/src/public_inputs.ts
- tooling/noir_js_backend_barretenberg/test/public_input_deflattening.test.ts
- yarn.lock
Resolves 
We're currently sorting the witness indices according to their ascii ordering rather than their numerial ordering despite the fact we're sorting a `number[]`. This means that 10 comes before 2 and so the public inputs get flattened/deflattened incorrectly.
Draft while I add some tests for this.
Isn't javascript a wonderful language?
Check one:
> fix: Flatten public inputs according to their index in numerial rather than ascii order

- test_programs/execution_success/brillig_oracle/src/main.nr
- tooling/nargo/src/ops/foreign_calls.rs
Resolves #1911 
This PR removes the `get_number_sequence` and `get_reverse_number_sequence` foreign calls and replaces their usage in tests with a mocked foreign call.
I'm leaving this as non-breaking as we make no guarantees about these functions and anyone relying on a foreign call to create an array of increasing numbers... shouldn't.
Check one:
> chore: remove `get_number_sequence` foreign calls

- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
Resolves 
This PR adds the boolean special case to `and_var` so that we can AND together variables without having to perform the multiplication optimization manually.
Check one:
> feat: add special case for boolean AND in acir-gen

- compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
- compiler/noirc_evaluator/src/ssa/function_builder/mod.rs
- compiler/noirc_evaluator/src/ssa/ir/instruction.rs
- compiler/noirc_evaluator/src/ssa/opt/die.rs
- compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs
- tooling/nargo_cli/tests/execution_success/brillig_cow/Nargo.toml
- tooling/nargo_cli/tests/execution_success/brillig_cow/Prover.toml
- tooling/nargo_cli/tests/execution_success/brillig_cow/src/main.nr
Fixes remaining `todo` and some panics in https://github.com/noir-lang/noir/pull/3522
I'm not sure if unpacking the entire slice recursively to complete the `todo!()` is even possible so I tried a different (hopefully sound) approach of incrementing the Rc for sub-arrays on each `ArrayGet` and when constructing the array. I've also disabled the `IncrementRc` instruction when not in Brillig code since it is unneeded.
I'm targetting @sirasistant's PR so that it is easier to see the changes I made to it. If all is well, we can merge this PR and then his afterward to get the feature in.
Check one:
> fix: Fix remaining issues in Brillig's copy on write arrays

- scripts/bootstrap_native.sh
- scripts/bootstrap_packages.sh
Fixing docker builds
Currently Docker does not build correctly due to .gitrepo not being present in a standalone context, thus leaving necessary env vars unset
This change fixes the issue above, and keeps functionality for building from a subrepo
Check one:
> fix: docker builds

- compiler/noirc_evaluator/src/errors.rs
corrected the formatting of error message parameters in index out of bounds error
Resolves #3629 
Check one:
> fix: corrected the formatting of error message parameters in index out of bounds error

- compiler/noirc_errors/src/position.rs
- compiler/noirc_frontend/src/ast/mod.rs
- compiler/noirc_frontend/src/ast/statement.rs
- compiler/noirc_frontend/src/hir/resolution/import.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/parser/parser.rs
- tooling/nargo_fmt/build.rs
- tooling/nargo_fmt/src/rewrite.rs
- tooling/nargo_fmt/src/rewrite/typ.rs
- tooling/nargo_fmt/src/utils.rs
- tooling/nargo_fmt/src/visitor/item.rs
- tooling/nargo_fmt/tests/expected/fn.nr
- tooling/nargo_fmt/tests/input/fn.nr
> chore: type formatting

- docs/docs/language_concepts/01_functions.md
- docs/docs/language_concepts/07_mutability.md
- docs/versioned_docs/version-v0.10.5/language_concepts/01_functions.md
- docs/versioned_docs/version-v0.10.5/language_concepts/07_mutability.md
- docs/versioned_docs/version-v0.17.0/language_concepts/01_functions.md
- docs/versioned_docs/version-v0.17.0/language_concepts/07_mutability.md
- docs/versioned_docs/version-v0.19.0/language_concepts/01_functions.md
- docs/versioned_docs/version-v0.19.0/language_concepts/07_mutability.md
- docs/versioned_docs/version-v0.19.1/language_concepts/01_functions.md
- docs/versioned_docs/version-v0.19.1/language_concepts/07_mutability.md
- docs/versioned_docs/version-v0.19.2/language_concepts/01_functions.md
- docs/versioned_docs/version-v0.19.2/language_concepts/07_mutability.md
- docs/versioned_docs/version-v0.19.3/language_concepts/01_functions.md
- docs/versioned_docs/version-v0.19.3/language_concepts/07_mutability.md
- docs/versioned_docs/version-v0.19.4/language_concepts/01_functions.md
- docs/versioned_docs/version-v0.19.4/language_concepts/07_mutability.md
- docs/versioned_docs/version-v0.6.0/language_concepts/01_functions.md
- docs/versioned_docs/version-v0.6.0/language_concepts/07_mutability.md
- docs/versioned_docs/version-v0.7.1/language_concepts/01_functions.md
- docs/versioned_docs/version-v0.7.1/language_concepts/07_mutability.md
- docs/versioned_docs/version-v0.9.0/language_concepts/01_functions.md
- docs/versioned_docs/version-v0.9.0/language_concepts/07_mutability.md
Resolves #3452
This PR makes two changes in the docs:
1. I've removed the visibility modifier on an argument to the non-entrypoint function `foo`. This code would compile but would also raise a warning on `pub` being unnecessary and misleading so we should just remove it.
2. `pub` was missing on a `main` function return value in `7_mutability.md`.
Check one:
> chore(docs): address visibility issues in docs

- Cargo.toml
- release-please-config.json
Resolves 
This PR does an "I reckon" fix to publishing ACVM crates.
I've added a version number to the workspace `Cargo.toml` so that these crates can be pushed to crates.io. The issue then is that we require these to be bumped appropriately by the release-please PR.
I imagine the reason why this wasn't done originally is that it requires the `acvm-repo` release-please package to change files outside of its directory. I've given this a go however and we can check whether the PR gets updated correctly after this is merged.
cc @kevaundray as he set up the original release please setup for ACVM.
Check one:
> chore(ci): Fix publishing of ACVM crates

- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
Resolves 
This PR updates new code from #3617 to use the new form of `add_constant` added in #3647.
Check one:
> chore: remove unnecessary conversions from `add_constant`

- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
Resolves 
This PR adds more checks to see if we have an existing witness with the same value before we add a new one.
Check one:
> feat: reuse witnesses more when interacting with memory

- .github/workflows/release.yml
This changes it so that there is one consistent git credential that we use in CI. Theres no way to enforce this however if we have a bot account, we can then just use that one account consistently.
Resolves 
Check one:
> chore: use the same git credentials everywhere in CI

- Cargo.toml
This reverts the versioning done in the root Cargo.toml [here](https://github.com/noir-lang/noir/pull/3645) 
CI is currently complaining about this
Resolves 
Check one:
> chore: remove version key for ACVM crates from root cargo.toml

- .github/workflows/publish-acvm.yml
- .github/workflows/release.yml
Without this, release-please does not publish the ACVM packages
Resolves 
Check one:
> chore: add publish-acvm to release workflow

- release-please-config.json
This reverts the change done in #3645 and removes the extraneous flake.nix file
Resolves 
Check one:
> fix: revert chnage to modify version in workspace file for acvm dependencies

- .github/workflows/release.yml
> chore: empty commit to trigger update-docs workflow

- .github/workflows/release.yml
- Cargo.toml
- scripts/update-acvm-workspace-versions.sh
There doesn't seem to be a way to do this, given that a Cargo workspace is meant to have a single version assosciated with it. So the acvm version needs to be modified similar to the Cargo.toml
Resolves 
Check one:
> chore: update acvm workspace root versions in release-please

- .github/workflows/release.yml
This just ensures that the lockfile is updated after the ACVM versions in the root file have been modified
Resolves 
Check one:
> fix: sequence update-lockfile workflow so it gets modified after the ACVM version in the root has been changed

- .github/workflows/release.yml
Currently we are triggering the update-docs workflow when there is a change on the release-please PR branch, this is okay for workflows like update-lockfile. However, it doesn't work for update-docs because it uses `needs.release-please.outputs.release-tag-name` which depends on the release-please tag which we get after we have merged the release-please PR into master.
See [here](https://github.com/noir-lang/noir/actions/runs/7024781896/job/19114307821) for example where update lockfile is ran on master.
Resolves 
Check one:
> fix(docs): trigger `update-docs` workflow when the `release-please` PR gets merged and not on every merge to master

- docs/docs/nargo/01_commands.md
- tooling/nargo_cli/src/cli/compile_cmd.rs
Resolves #3488 
Keys have been removed from the artefacts, so we need to remove the option to add them as well.
Check one:
> fix: remove include-keys option

- compiler/noirc_frontend/src/monomorphization/mod.rs
- docs/docs/standard_library/logging.md
- docs/versioned_docs/version-v0.19.4/language_concepts/data_types/03_strings.md
- noir_stdlib/src/lib.nr
- test_programs/execution_success/strings/src/main.nr
- tooling/nargo/src/ops/foreign_calls.rs
- tooling/nargo_fmt/tests/expected/print.nr
- tooling/nargo_fmt/tests/expected/print2.nr
- tooling/nargo_fmt/tests/input/print.nr
- tooling/nargo_fmt/tests/input/print2.nr
Resolves  **https://github.com/noir-lang/noir/issues/3575**
Resolves **https://github.com/noir-lang/noir/issues/2912** (duplicate)
Continuation of https://github.com/noir-lang/noir/pull/3576
Refactors `println_oracle` method into `print` with boolean indicator, allowing `print` to coexist with `println` under the same `ForeignCall` string symbol.
Updates appropriate tests, and logging.md documentation.
Add a subchapter to `03_string.md` documentation for the `fmtstr` type
Check one:
> feat: Implement print without newline

- compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs
- test_programs/execution_success/regression_3635/Nargo.toml
- test_programs/execution_success/regression_3635/src/main.nr
Resolves #3635 
String literals were initialised as field array instead of array of u8.
Check one:
> fix: initialise strings as u8 array

- tooling/nargo_cli/src/cli/test_cmd.rs
Resolves https://github.com/noir-lang/noir/issues/3686
Improved the output of tests by including passed/failed count in the last line print.
Check one:
> feat: Enhance test information output

- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/hir/resolution/traits.rs
- compiler/noirc_frontend/src/hir/type_check/mod.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_frontend/src/node_interner.rs
Resolves 
feat(lsp): add goto definition for locals #3706
LSP server now understands goto definition command issued by Client (ie. vscode). In case of local symbol it will jump to it's definition.
Check one:
> feat(lsp): add goto definition for locals

- README.md
was onboarding this morning to tackle [a quick issue over here](https://github.com/noir-lang/noir/issues/3372)
and noticed this link broke in the top level README
https://github.com/noir-lang/noir?tab=readme-ov-file#working-on-this-project
Check one:
> chore: fix broken onboarding link in README

- compiler/noirc_frontend/src/lexer/lexer.rs
- compiler/noirc_frontend/src/lexer/token.rs
spotted an issue with punctuation inside a `#[test(should_fail_with = "")]` block ([comment on original issue](https://github.com/noir-lang/noir/issues/3372#issuecomment-1845660516))
Resolves #3372 (an extension of this original issue)
I built off of the original work done over here #3374 but simplified things down to just cover all common punctuation
Check one:
> chore: allow common ascii punctuation in attributes

- .github/workflows/test-js-packages.yml
Resolves 
It seems like despite the `tests-end` job not running and being skipped if any of the dependants fail, this is enough to satisfy the required check status. This PR changes it so that this job explicitly fails if any of the dependants failed or were skipped.
Check one:
> chore(ci): fail `tests-end` job if any dependants failed

- tooling/noir_js/.mocharc.json
- tooling/noir_js/package.json
- yarn.lock
This gets rid of the experimental loader warning, as tsx does not require it. 
This experimental loader feature is unstable and just to rule it out, could be one of the reasons why tests have become a bit flaky.
Resolves 
Check one:
> chore: use `tsx` instead of `ts-node` for `noir_js`

- acvm-repo/acir_field/src/generic_ark.rs
- test_programs/execution_success/strings/src/main.nr
single digit (or generally, odd length) hex literals such as `0x4` result in an `InvalidIntegerLiteral` error
Resolves #3235
i just prefixed all odd-length hex literals with another `0`, happy to change course if there's a better/more efficient way here (i'm kinda rust noob)
Check one:
> fix: deserialize odd length hex literals

- compiler/noirc_frontend/src/lexer/lexer.rs
Resolves #3283 
This PR adds support for underscores in numeric literals. This is restricted to not allow multiple underscores in a row and a literal cannot start or end with an underscore.
Check one:
> feat: allow underscores in integer literals

- compiler/fm/src/lib.rs
Since we already import FileMap with the usepath, using fm::FileMap is redundant
Resolves 
Check one:
> chore: fix un-needed fully qualified path

- compiler/noirc_frontend/src/hir/resolution/resolver.rs
This removes an extraneous debug statement that was likely missed when the corresponding PR got merged.
Resolves 
Check one:
> chore: remove extraneous dbg statement

- tooling/nargo/src/ops/compile.rs
- tooling/nargo_cli/src/cli/compile_cmd.rs
Resolves #3370 
This PR removes the special case which says all backends support the pedersen hash black box function.
Check one:
> chore: remove special casing for `pedersen_hash` black box function

- Cargo.lock
- compiler/fm/src/lib.rs
- tooling/lsp/Cargo.toml
- tooling/lsp/src/lib.rs
- tooling/lsp/src/requests/goto_definition.rs
This is a small change to control the scope of what the lsp touches and to see what the fm crate is offering to other crates in this workspace.
codespan_reporting is needed because the fm crate is using codespan
Resolves 
Check one:
> chore: re-export the items needed for the lsp from the fm crate instead of importing codespan_reporting

- compiler/fm/src/lib.rs
- compiler/noirc_driver/src/lib.rs
- compiler/wasm/src/compile.rs
> chore: try using two methods for adding files; one which assumes the path is canonical and the other which adds the root and canonicalizes

- tooling/noirc_abi/src/input_parser/mod.rs
The test should be asserting that the parse method returns an error
Resolves 
Check one:
> fix: add missing assertion to test

- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/hir/resolution/traits.rs
- compiler/noirc_frontend/src/hir/type_check/expr.rs
- compiler/noirc_frontend/src/hir/type_check/mod.rs
- compiler/noirc_frontend/src/hir_def/traits.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
- compiler/noirc_frontend/src/node_interner.rs
- tooling/noirc_abi/src/lib.rs
The `Trait` struct is quite large and was being cloned every time `get_trait` was called in the NodeResolver, which was somewhat often.
Stops the cloning of traits! The `Clone` derive is removed entirely and when needed for ownership reasons we either re-retrieve the trait by calling `get_trait` again (which now returns a reference), or we temporarily take ownership of the trait's methods.
Check one:
> fix: Stop cloning Traits!

- tooling/nargo_cli/build.rs
@jfecher noted that occassionally the JSON conversion method would fail. This changes `expect` to `unwrap_or_else` so that we know exactly what stdout input the error is failing on. 
Resolves 
Check one:
> chore: Improve error message in tests

- Cargo.lock
- Cargo.toml
- acvm-repo/acvm_js/Cargo.toml
- compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs
- compiler/wasm/Cargo.toml
- tooling/backend_interface/Cargo.toml
- tooling/backend_interface/src/lib.rs
- tooling/backend_interface/src/proof_system.rs
- tooling/nargo_cli/Cargo.toml
- tooling/nargo_cli/src/main.rs
If you want to see info level logs, you can do `NOIR_LOG=info nargo compile` by default if that environment variable is not set, then it will only print out error level logs
Resolves 
Check one:
> chore: conservatively use log::info instead of println for some expressions

- compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs
Currently multiplication of booleans adds in a range check which is unnecessary as the result cannot be larger than the inputs.
Check one:
> feat: avoid overflow checks on boolean multiplication

- .github/workflows/test-cargo.yml
- .github/workflows/test-js.yml
- scripts/bootstrap_native.sh
- scripts/bootstrap_packages.sh
- scripts/test_js_packages.sh
This was not caught because the docker tests are not required checks and it was only being ran on master. 
They are not required because they need to be optimized a bit more with caching. I don't expect them to fail often, so in the interim, its okay to not have these as required (If this happens again and we have not migrated, then we can revisit)
Resolves 
Check one:
> fix: remove `noirc_driver/aztec` feature flag in docker

- tooling/lsp/src/notifications/mod.rs
- tooling/nargo_toml/src/lib.rs
While saving file - procedure of compiling package should be applied to single package rather than all packages available in workspace.
Check one:
> fix(lsp): package resolution on save

- docs/docs/explanations/standard_library/traits.md
- noir_stdlib/src/default.nr
- noir_stdlib/src/lib.nr
- noir_stdlib/src/ops.nr
- test_programs/compile_failure/no_nested_impl/src/main.nr
Adds traits for `Default`, `Add`, `Sub`, `Mul`, `Div`, and `Eq` to the stdlib.
Note that this does not implement operator overloading so the operator traits must be called by name. We also have no way currently of implementing a trait for all integer sizes so I've manually implemented only some common ones. Let me know if there are other impls I should add.
Check one:
> feat: Add some traits to the stdlib

- .github/workflows/publish-nargo.yml
- .github/workflows/test-js-packages.yml
Resolves 
This PR adds a timeout to all of the jobs which are likely to spin out for a long time.
Check one:
> chore(ci): enforce timeouts on build and test workflows

- compiler/noirc_frontend/src/parser/parser.rs
Resolves 
Removes the experimental feature warning for signed integers. Bit shifting is the only task that remains for signed integers and this already has a separate error message.
Check one:
> chore: Remove signed integer warning

- Cargo.lock
- Cargo.toml
- compiler/fm/Cargo.toml
- compiler/fm/src/lib.rs
- compiler/noirc_frontend/Cargo.toml
- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- tooling/backend_interface/Cargo.toml
- tooling/nargo/Cargo.toml
- tooling/nargo_cli/Cargo.toml
Resolves #3799 
This is a relatively quick and dirty resolution to #3799. We may want to integrate these functions into `ModCollector` as methods but I think they also work standalone plus it means that we can transfer the tests across without needing to create a `ModCollector` instance.
Check one:
> chore: move module related code from `fm` to `noirc-frontend`

- docs/docs/explanations/noir/traits.md
Resolves 
Fixes an issue with the trait documentation where two methods were missing the brackets to introduce their generic parameters. I also renamed the generic `S` to `T` to match the paragraph above it talking about "all types `T` that implement `Area`"
Check one:
> chore: Add missing generics to trait docs

- acvm-repo/acvm/src/compiler/mod.rs
- acvm-repo/acvm/src/compiler/optimizers/mod.rs
- acvm-repo/acvm/src/compiler/transformers/mod.rs
Same as https://github.com/noir-lang/noir/pull/3814 but with a different approach, by building the map of old to new inside AcirTransformationMap
Resolves https://github.com/noir-lang/noir/issues/3809
Check one:
> feat: speed up transformation of debug messages

- release-please-config.json
Resolves 
This PR adds a bootstrap sha which corresponds to the failed 0.19.5 release.
Check one:
> chore: add bootstrap sha for release-please

- .github/workflows/release.yml
Resolves 
This PR moves the cutting of a new docs version to happen within the release-please PR.
Check one:
> chore(ci): correct how docs are build for releases

- compiler/wasm/test/browser/index.test.ts
- compiler/wasm/test/node/index.test.ts
Since we don't want these checked in and these are compiled manually, they can get out of sync if you build the wasm and do not do `noirup -p .` and then recompile the example programs.
The error message will say that the bytecodes produced are different, with this change the test will first tell you that the versions are different. 
Resolves 
Check one:
> chore: Compare noir versions when testing that the wasm compiled artefact is equal to the natively compiled artefact

- compiler/noirc_frontend/src/hir/mod.rs
- compiler/noirc_frontend/src/tests.rs
- compiler/wasm/src/compile.rs
- compiler/wasm/src/compile_new.rs
- tooling/nargo/src/lib.rs
This is a minor cleanup task. Everywhere we created a CompilerContext, we were passing in a default CrateGraph. 
This PR just creates the default CrateGraph internally, so that the caller does not need to. If in the future, we decide to want to pass a populated CrateGraph, we can create a `with_crate_graph` method to account for the edge case.
Resolves 
Check one:
> chore: Compiler `Context` instantiates a new `CrateGraph` internally

- .github/workflows/release.yml
Resolves 
Fixes the issue in #3828 where we're trying to read from the release-please job as if it were the release-please action.
Check one:
> chore(ci): fix versioning of docs in release PR

- compiler/fm/src/lib.rs
- compiler/noirc_driver/src/debug.rs
- compiler/noirc_frontend/src/hir/def_map/mod.rs
- tooling/nargo/src/artifacts/debug.rs
- tooling/nargo_cli/src/cli/fmt_cmd.rs
This makes the API more uniform because to add a file, we call:
```
pub fn add_file_with_source(&mut self, file_name: &Path, source: String) -> Option<FileId> {
```
and now to fetch a file we call:
```
pub fn fetch_file(&self, file_id: FileId) -> &str;
```
Instead of returning a `File` which was not present when we were adding a File
Resolves 
Check one:
> chore: `fetch_file` now returns ` &str` instead of a `File`

- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
> fix: Prevent panic on unsupported BB function in ACIR gen

- tooling/nargo_cli/src/cli/test_cmd.rs
Workspaces typically contain some crates with no tests (especially binary crates that are only entry points). Running tests without specifying a test name on a crate won't fail with this PR if that crate has no tests. 
Possible approach to #3863
Check one:
> fix: Don't fail if no tests and the user didn't provide a pattern

- tooling/nargo_cli/src/cli/lsp_cmd.rs
Resolves 
This PR re-adds a change which was removed from #3875 which is required for the LSP to run inside of a docker container.
Check one:
> fix: allow lsp to run inside of a docker container

- .github/workflows/publish-docs.yml
- .github/workflows/release.yml
This PR makes docs deploy on every merge to master.
Right now docs are only deployed when the "Publish Docs" workflow runs, which is everytime a release PR is merged. There's a workflow dispatch so we can go and manually deploy it (like @kevaundray is doing here](https://github.com/noir-lang/noir/actions/runs/7251799715)
We don't like manual so we're deploying it every merge to master 😄
- Makes `publish_docs` run on every merge
- Removes `publish_docs` from the release-please workflow
This doesn't touch the new versioning system @TomAFrench cleverly put together. Versions are still generated each time release-please adds a new commit to its PR (I think).
This is mostly _when_ to deploy
> chore: making docs always deploy on master

- acvm-repo/acir/acir_docs.md
- cspell.json
Resolves 
Fixes a bunch of spelling issues that github keeps complaining about.
Check one:
> chore: fix spelling issues

- docs/docusaurus.config.ts
- docs/src/css/custom.css
As usual I got a little bit carried away, but the whole point was to just remove the white background in the CTA box with dark mode.
Ended up making some other color changes.
A picture worth a thousand words:
- Fixes the CTA box
- Changes primary colors to match Aztec's color sheet, not much since we're gonna have a restyling later on anyway
- Makes docs respect system theme instead of defaulting to white
> fix: fixing dark mode background on the CTA button

- acvm-repo/acvm_js/package.json
- compiler/wasm/package.json
- tooling/noir_codegen/package.json
- tooling/noir_js/package.json
- tooling/noir_js_backend_barretenberg/package.json
- tooling/noir_js_types/package.json
- tooling/noirc_abi_wasm/package.json
Resolves 
Socket is complaining about our releases: https://socket.dev/npm/package/@noir-lang/noir_js/issues/0.22.0-d025731.nightly
This PR adds various metadata to improve out package quality score.
Check one:
> chore: improve package.json metadata

- docs/docs/explainers/explainer-recursion.md
Made some simple readability changes
Resolves 
Check one:
> chore: Update explainer-recursion.md

- Cargo.lock
- Cargo.toml
- acvm-repo/acir_field/src/generic_ark.rs
- compiler/noirc_printable_type/Cargo.toml
- compiler/noirc_printable_type/src/lib.rs
- deny.toml
- tooling/debugger/src/context.rs
- tooling/debugger/src/dap.rs
- tooling/debugger/src/repl.rs
- tooling/lsp/src/requests/test_run.rs
- tooling/nargo/Cargo.toml
- tooling/nargo/src/ops/foreign_calls.rs
- tooling/nargo/src/ops/test.rs
- tooling/nargo_cli/src/cli/execute_cmd.rs
- tooling/nargo_cli/src/cli/prove_cmd.rs
- tooling/nargo_cli/src/cli/test_cmd.rs
This adds a JSON-RPC client to the DefaultForeignCallExecutor. This allows it to solve unknown oracle calls. The URL to the foreign call executor is an optional argument to nargo execute, nargo test and nargo prove.
Resolves #1052
An example echo server in typescript
```typescript
import {
JSONRPCServer,
TypedJSONRPCServer,
} from "json-rpc-2.0";
import express from "express";
import bodyParser from "body-parser";
type Methods = {
echo(params: ForeignCallParam[]): ForeignCallResult;
};
const server: TypedJSONRPCServer<Methods> = new JSONRPCServer(/* ... */);
interface Value {
inner: string,
}
interface SingleForeignCallParam {
Single: Value,
}
interface ArrayForeignCallParam {
Array: Value[],
}
type ForeignCallParam = SingleForeignCallParam | ArrayForeignCallParam;
interface …
```
> feat: Resolve oracle calls via JSON-RPC

- docs/docs/how_to/how-to-recursion.md
Last typo changes
Resolves 
Check one:
> chore: Update how-to-recursion.md

- docs/docs/index.md
> chore: Update index.md

- tooling/lsp/src/requests/goto_definition.rs
Resolves 
Slow performance on bigger workspace with goto-definitions #3915
Optimises performance of a request from ~16 seconds to ~1s on sample workspace [noir-protocol-circuits](https://github.com/AztecProtocol/aztec-packages/tree/master/yarn-project/noir-protocol-circuits)
Check one:
> chore: Optimize goto_definitions for workspace case

- Cargo.lock
Resolves 
This pr bumps a few versions of deps to reduce dependency tree.
Check one:
> chore: bump dependency versions

- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
Resolves 
This PR avoids churn on `AcirVar`s when we perform trivial multiplications. This avoids some situations where we were codegenning expressions with zero-coefficient terms.
Check one:
> feat: simplify multiplications by `0` or `1` in ACIR gen

- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
Resolves 
This PR removes the predicate from the ACIR codegened from `Instruction::Lt`.
I think this predicate got added as a knee-jerk reaction to there being divisions involved however all these divisions are done with a known non-zero constant divisor so we can always perform the division safely.
This fixes a discrepancy as we're applying `current_side_effects_enabled_var` despite https://github.com/noir-lang/noir/blob/aabe5c15bc9d509e6953e689a5f479b26b972384/compiler/noirc_evaluator/src/ssa/ir/instruction.rs#L263-L273 stating that `Lt` not having side effects. As a bonus we can benefit from optimisations in acir gen.
Check one:
- [x ] I have tested the changes locally.
> feat: remove unnecessary predicate from `Lt` instruction

- compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs
- compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs
Followup to #3740
#3740 fixed an issue where array equalities were making their way into SSA and not having side effect predicates applied correctly by applying the predicate to each of the array elements. We actually state that we do not want array equalities in SSA (in `insert_array_equality`) so the fundamental issue of array equalities in SSA still exists.
We were allowing an implicit array equality to sneak into SSA by performing an optimization of `Constrain(Eq(x, y), 1)` into `Constrain(x, y)` during codegen. This meant that if `x` and `y` were arrays then we bypass the `insert_array_equality` function which the `Eq` instruction would call, which would have calculated a primitive predicate value for the constrain statement to act on.
This PR removes the extra logic from the …
> fix: prevent `Instruction::Constrain`s for non-primitive types

- test_programs/noir_test_failure/should_fail_mismatch/src/main.nr
Resolves 
This PR updates the `should_fail_mismatch` test to use the correct return type from the `pedersen_commitment` function. Previously the test was failing due to this type error and not from the fact that the assertion was failing.
Check one:
> chore: fix `should_fail_mismatch` test to use correct pedersen return type

- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
Resolves 
This is just a small cleanup so that we can think in terms of logic operators rather than subtractions here.
Check one:
> chore: abstract away subtractions from `OR` implementation

- Cargo.lock
- tooling/debugger/Cargo.toml
- tooling/debugger/src/lib.rs
- tooling/debugger/src/repl.rs
- tooling/debugger/src/source_code_printer.rs
- tooling/nargo/src/artifacts/debug.rs
The debugger REPL was failing under certain scenarios when a stepped location spanned multiple lines. We tracked down the failure to a missing bounds check. 
This PR fixes the issue, introduces a refactor to make the relevant code testable, and adds regression tests to prevent reoccurrence.
This PR is best reviewed as a whole instead of commit-by-commit.
- Moves source code printing logic from the main debugger REPL module, to a new source_code_printer module.
- Decouples actual printing from rendering logic to improve testability.
- Adds regression tests
Check one:
> fix(debugger): crash when stepping through locations spanning multiple lines

- compiler/noirc_evaluator/src/errors.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
Resolves 
Unexpected is one word so we shouldn't have a capitial here.
Check one:
> chore: fix casing on `InternalError::Unexpected`

- acvm-repo/acvm/src/compiler/optimizers/redundant_range.rs
Resolves 
A range constraint is a weaker constraint than directly asserting the witness to be equal to a value (as long as that value fits within the set number of bits). We can then remove range constraints from these witnesses.
I've made sure to keep any range constraints which would conflict with the constant witness assignment.
Check one:
> feat: remove range constraints from witnesses which are constrained to be constants

- noir_stdlib/src/ec/montcurve.nr
- noir_stdlib/src/ec/swcurve.nr
- noir_stdlib/src/ec/tecurve.nr
Resolves 
This PR just moves the `eq` methods on the ec point structs into `Eq` trait impls.
Check one:
> feat: implement `Eq` trait on curve points

- compiler/noirc_evaluator/src/ssa/function_builder/mod.rs
- compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs
Resolves 
This PR gives an `insert_range_check` method for consistency with the other `Instruction`s.
Check one:
> chore: add `insert_range_check` method to `FunctionBuilder`

- compiler/noirc_driver/src/abi_gen.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/mod.rs
- compiler/noirc_frontend/src/hir/type_check/expr.rs
- compiler/noirc_frontend/src/hir/type_check/mod.rs
- compiler/noirc_frontend/src/hir_def/function.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
- compiler/noirc_frontend/src/node_interner.rs
Resolves 
This PR frees us from the tyranny of cloning `FuncMeta` every time we want to access them via `NodeInterner::func_meta`. Now we will be graced with a very slight, likely imperceptible performance increase.
Check one:
> chore: Stop cloning `FuncMeta`

- tooling/nargo_cli/src/cli/test_cmd.rs
- Currently the `writeln!` macro is used before `writer.reset()` so the ANSI escape code to reset terminal colours to their default is printed on a new line that is left empty.
- This PR moves the ANSI colour reset code to the end of the last line of the test commands' output.
- Add `FAIL` to test result before messages from the compiler are inlined on the following line.
- Minor fix in code where mentions of printing to `stdout` are made when in-fact `writer` is outputting to `stderr`.
Currently Nargo's output with scripts breaks terminal colours under certain scenarios. Mostly in combination with tools that re-run commands on file change like `wgo`, `entr`, or `watchman` when used with shell scripts.
Special checks and logic (in said shell scripts) must be added to spawn the process in …
> fix: Improve `nargo test` output

- compiler/wasm/src/compile_new.rs
Resolves 
This PR bubbles up the error message for an invalid crate name rather than panicking.
Check one:
> fix: remove panic for adding an invalid crate name in wasm compiler

- docs/docs/noir/concepts/generics.md
Resolves 
Updates an outdated section of the docs which claims we don't have traits - when we do now.
I have a link to the traits page included here which I still need to test to see if it works
Check one:
> fix: Update generics docs to mention we have traits now

- acvm-repo/acir/src/circuit/mod.rs
- acvm-repo/brillig_vm/src/black_box.rs
- compiler/noirc_evaluator/src/ssa/function_builder/data_bus.rs
- compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs
- compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs
- compiler/noirc_frontend/src/ast/mod.rs
- compiler/noirc_frontend/src/hir/type_check/stmt.rs
- compiler/noirc_frontend/src/parser/parser.rs
- tooling/noirc_abi/src/lib.rs
Resolves 
This PR adds some strings to unreachable panics so that if they manage to get run then we get a usable error message.
This should be a noop.
Check one:
> chore: remove some empty `unreachable!`s

- docs/src/pages/index.jsx
> chore(docs): small grammar fix on the landing page

- compiler/noirc_frontend/src/hir/def_map/mod.rs
- test_programs/compile_success_empty/reexports/Nargo.toml
- test_programs/compile_success_empty/reexports/src/main.nr
- test_programs/test_libraries/exporting_lib/Nargo.toml
- test_programs/test_libraries/exporting_lib/src/lib.nr
- test_programs/test_libraries/reexporting_lib/Nargo.toml
- test_programs/test_libraries/reexporting_lib/src/lib.nr
Resolves 
This PR adds a test case to just show the current state of reexports across libraries.
Check one:
> chore: add test case showing reexports

- compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
- compiler/noirc_evaluator/src/brillig/brillig_ir.rs
- compiler/noirc_evaluator/src/brillig/brillig_ir/debug_show.rs
Resolves 
As part of #3984, I noticed that I forgot to remove the truncation behaviour from casts in brillig. This PR updates them to be a simple `mov` instruction.
In order to do this I've added a proper implementation of `Instruction::Truncate`.
Check one:
> feat: remove truncation from brillig casts

- .github/workflows/publish-docs.yml
Resolves 
These commit comments are spamming notifications and generally have a low signal-to-noise ratio. This PR turns them off.
Check one:
> chore(ci): disable commit comments on docs publishing

- .github/scripts/noir-wasm-build.sh
- .github/workflows/docker-test-flow.yml
- scripts/nargo_compile_wasm_fixtures.sh
Resolves #4009 
Aiming to be the dumbest way to get CI passing again.
Check one:
> chore(ci): fix docker CI

- .github/workflows/test-js-packages.yml
- compiler/wasm/.gitignore
- compiler/wasm/package.json
Resolves 
The ordering on `exports` is important plus we have `types` missing which was causing issues in `aztec-packages`.
Check one:
> fix: fixup exports from `noir_wasm`

- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
Omit the mapping of SSA indexes to flat indexes for arrays of structs.
The mapping of SSA indexes to flat indexes is only necessary when arrays contain arrays or slices. The SSA indexing is a flat indexing for arrays that do not contain arrays in them. This PR omits the mapping for arrays of structs (that do not contain arrays in them), that previously were generating an identity mapping, increasing the number of constraints.
This reduces significantly the constraint counts in aztec protocol circuits:
| Program | ACIR opcodes (+/-) | % | Circuit size (+/-) | % |
|:-|-:|-:|-:|-:|
| **private_kernel_init** | -11,663 ✅ | **-24.27%** | -45,467 ✅ | **-11.89%** |
| **rollup_base** | -55,441 ✅ | **-18.84%** | -221,585 ✅ | **-13.26%** |
| **private_kernel_inner** | -58,582 ✅ | **-38.79%** | …
> feat: Optimize array ops for arrays of structs

- noir_stdlib/src/uint128.nr
Resolves 
This PR adds a range check to `U128::from_integer` as this method accepts an arbitrary field and so is unsafe.
Check one:
> feat: assert maximum bit size when creating a U128 from an integer

- docs/package.json
- yarn.lock
This PR bumps the playground version to 0.7.0 which uses Noir 0.22.0
Resolves #3993
> chore(docs): bumping playground version

- tooling/noir_js/src/witness_generation.ts
Resolves 
This PR stores a `WasmBlackboxFunctionSolver` in a global variable so that we can avoid reinitialisation on subsequent exections.
This takes a trick from `aztec-packages` but I haven't validated that it actually causes a speedup
Check one:
> feat: use singleton `WasmBlackBoxFunctionSolver` in `noir_js`

- compiler/noirc_driver/tests/stdlib_warnings.rs
Resolves 
We've had a number of occasions where a feature is added which causes the stdlib to produce warnings on every compilation. This isn't great so we should catch and fix those warnings as we create them.
This PR adds a test which compiles a very simple program and asserts that no warnings are omitted.
Check one:
> chore: add test to disallow stdlib producing warnings

- compiler/noirc_evaluator/src/ssa/function_builder/mod.rs
- compiler/noirc_evaluator/src/ssa/ir/dfg.rs
- compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs
…
Resolves 
This PR removes unnecessary overflow checks in more scenarios than previously. We do this by inspecting whether the inputs are `Instruction::Cast`s which allows us to determine an more restrictive upper bound on the value and reason about how this affects the result.
Check one:
> feat: Avoid unnecessary range checks by inspecting instructions for casts

- compiler/noirc_driver/src/lib.rs
- compiler/wasm/src/compile.rs
- compiler/wasm/src/compile_new.rs
- tooling/nargo/src/ops/compile.rs
- tooling/nargo_cli/src/cli/compile_cmd.rs
Resolves #2798 
This PR adds ` --force` flag which will ignore any existing build artifacts when compiling a circuit.
Check one:
> feat: add a `--force` flag to force a full recompile

- acvm-repo/acvm/tests/solver.rs
Resolves #3802
This PR enables these ignored tests.
Check one:
> chore: reenable integration tests in ACVM

- compiler/noirc_evaluator/src/ssa/ir/instruction/call.rs
The compiler optimizes uses of the `ToRadix` intrinsic applied to constants by precomputing the results.
Resolves #4048
The optimization produces a fixed sized array instead of a slice.
The PR changes the `constant_to_radix` function to produce a slice and generates a tuple with the length and the slice itself, which fits the internal representation of slices in SSA. 
This was found and fixed during the implementation of the debugger (see #3015).
Check one:
> fix: Make `constant_to_radix` emit a slice instead of an array

- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/hir/resolution/traits.rs
- compiler/noirc_frontend/src/hir/type_check/expr.rs
- compiler/noirc_frontend/src/hir_def/traits.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
- compiler/noirc_frontend/src/node_interner.rs
Resolves #4058 
Small cleanup from the trait generics PR. Since `TypeVariableId`s are no longer needed in `Generics`, this removes them.
Check one:
> chore: Remove TypeVariableId from Generics

- .github/workflows/docs-dead-links.yml
Resolves 
As @critesjosh mentioned in #3999, this link currently 404s because github doesn't allow getting the job id necessary to construct this URL using the context api.
Check one:
> chore(ci): link to workflow run in `docs-dead-links.yml`

- Cargo.lock
Resolves 
This PR updates `h2` to address the vulnerability which is causing cargo-deny to error.
Check one:
> fix: fix advisory issue in cargo-deny

- aztec_macros/src/lib.rs
Resolves 
Having an unsupported type in the interface of an Aztec contract currently causes the compile to panic. This PR replaces this with a proper error.
Check one:
> chore: remove panic for unsupported types in aztec contract interface

- tooling/nargo_cli/build.rs
Resolves 
It's currently possible for an integration test to report true due to the integration test using a cached artifact. This isn't an issue in CI as no cached artifacts exist there but it can results in strange behaviour locally.
This PR addresses this issue by forcing a full recompile.
Check one:
> chore: force programs to be fully rebuilt in integration tests

- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
Followup to #3916
`Instruction::Constrain` is now only defined for primitive types so we don't require handling for array equalities in ACIR-gen as this should be decomposed in SSA.
Check one:
> chore: remove concept of constraining non-primitive types from acir-gen

- .github/workflows/release.yml
Resolves 
This PR should resolve the CI failures on the release-please PR. This is because the Noir playground uses a fixed version of noir packages and so results in new entries in the yarn.lock file as we update everything else.
The Noir playground should be updated so that it doesn't bring in its own dependencies to fix this properly.
Check one:
> chore(ci): update `yarn.lock` on release PRs

- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
- compiler/noirc_printable_type/src/lib.rs
- test_programs/execution_success/debug_logs/src/main.nr
As part of our debugger implementation (see #3015) we need to extend the supported types that can be printed. We are using `noirc_printable_type` to keep values of variables at runtime for debug inspection.
Also resolves #4073
This PR adds support for converting these new types:
- Tuples
- Slices: lift the restriction to print them and handle arrays with dynamic size (flagging them with a `None` length in the type)
- Functions: printed as an opaque `<<function>>` tag for now
- Mutable references: printed as an opaque `<<mutable ref>>` tag for now
- Unit: this is actually required to fully support function type conversion, for non-closured function references (ie. the environment is `()` in that case)
The PR also fixes a preexisting bug when printing multiple values using formatted strings …
> feat: Support printing more types

- .github/actions/setup/action.yml
- .github/workflows/docs-pr.yml
- .github/workflows/publish-docs.yml
- .github/workflows/release.yml
Resolves 
This PR splits building and deploying a preview of the docs. This should enforce that docs are always ready to be published without generating a large number of unnecessary deploys.
Check one:
> chore(ci): always build docs

- Cargo.lock
- tooling/backend_interface/test-binaries/mock_backend/Cargo.lock
- tooling/lsp/src/requests/profile_run.rs
- tooling/nargo/src/ops/compile.rs
- tooling/nargo/src/ops/mod.rs
- tooling/nargo_cli/Cargo.toml
- tooling/nargo_cli/build.rs
- tooling/nargo_cli/src/cli/codegen_verifier_cmd.rs
- tooling/nargo_cli/src/cli/compile_cmd.rs
- tooling/nargo_cli/src/cli/dap_cmd.rs
- tooling/nargo_cli/src/cli/debug_cmd.rs
- tooling/nargo_cli/src/cli/execute_cmd.rs
- tooling/nargo_cli/src/cli/info_cmd.rs
- tooling/nargo_cli/src/cli/prove_cmd.rs
- tooling/nargo_cli/src/cli/verify_cmd.rs
Resolves partially #3503
This PR removes some duplication on the compilation methods
Check one:
> feat: deduplicate `compile_program` and `compile_contract` methods

- compiler/noirc_evaluator/src/ssa/function_builder/mod.rs
- compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs
Resolves 
Small PR to replace usage of `(1-x)` instead of `not(x)` for boolean `x`. This improves readability of the codegen imo.
Check one:
> chore: replace explicit subtractions with nots

- compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs
- test_programs/execution_success/databus/src/main.nr
Resolves #4046 
This PR changes saves the data bus configuration before processing the other queued functions during SSA gen phase.
With the current implementation the databus will be incorrectly saved to the last generated function instead of the main function, causing a panic in a later optimization phase.
Check one:
> fix: save the data bus to the current function before generating others

- aztec_macros/src/lib.rs
Resolves 
This enum is dangerously close to triggering https://rust-lang.github.io/rust-clippy/master/#/clippy::enum_variant_names so I've renamed some things.  I've also delayed where we convert from an `AztecMacroError` to a `MacroError` to avoid a number of `into()`s
Check one:
> chore: rename aztec macro errors

- tooling/noir_js_backend_barretenberg/src/index.ts
Resolves 
We've got documentation in this package which should probably be in the jsdoc but isn't. I've then moved it across into there so it becomes part of the autogenerated docs.
Check one:
> chore: move comments into doc comments in `noir_js_backend_barretenberg`

- tooling/noir_js_backend_barretenberg/src/index.ts
Resolves 
This PR stops `api` from being the `any` type so we get type safety when calling methods on it.
This doesn't affect the lazy loading of bb.js as we're only importing types which get stripped out by typescript.
Check one:
> chore: add better type safety in `noir_js_backend_barretenberg`

- compiler/noirc_driver/src/contract.rs
- compiler/noirc_driver/tests/contracts.rs
- test_programs/compile_failure/multiple_contracts/Nargo.toml
- test_programs/compile_failure/multiple_contracts/src/main.nr
- tooling/nargo_cli/build.rs
- tooling/nargo_cli/src/cli/codegen_verifier_cmd.rs
- tooling/nargo_cli/src/cli/compile_cmd.rs
- tooling/nargo_cli/src/cli/dap_cmd.rs
- tooling/nargo_cli/src/cli/debug_cmd.rs
- tooling/nargo_cli/src/cli/execute_cmd.rs
- tooling/nargo_cli/src/cli/prove_cmd.rs
- tooling/nargo_cli/src/cli/verify_cmd.rs
Resolves https://github.com/noir-lang/noir/issues/2608
This PR removes the `compile_bin_package` function as it's pretty unnecessary. At the same time I've added filters to other commands which only make sense on binary packages to avoid #2608 
Check one:
> chore: remove `compile_bin_package`

- compiler/noirc_evaluator/src/errors.rs
Resolves 
This message is a bit strong for a warning (constant return values are technically allowed, there's just generally not much reason for them). It also doesn't give much information on why they may not be a good idea.
I've updated the warning to something which I think is more useful. Happy to take feedback on this however.
Check one:
> chore: improve warning message for returning a constant value

- tooling/nargo_cli/src/cli/test_cmd.rs
Resolves 
Currently if you're running tests in a workspace and are filtering them by name, if any of the packages doesn't contain a matching test then we will immediately return an error. This PR fixes this so that we wait until we have checked the entire workspace, should there still be no matching tests then we throw an error but otherwise pass.
Check one:
> fix: check for tests in all packages before failing due to an unsatisfied test filter

- compiler/noirc_driver/src/lib.rs
Debugging optimizations often requires inspecting the monomorphized program. This adds an option to enable this.
https://github.com/noir-lang/noir/issues/4067
Example usage:
```bash
❯ (cd test_programs/compile_success_contract/simple_contract && cargo run compile --show-monomorphized)
Compiling nargo_cli v0.23.0 (/Users/michaelklein/Coding/rust/noir/tooling/nargo_cli)
Finished dev [optimized + debuginfo] target(s) in 1.79s
Running `/Users/michaelklein/Coding/rust/noir/target/debug/nargo compile --show-monomorphized`
Monomorphized AST for program with hash: 18020856208726922572
fn triple$f0(x$l0: Field) -> Field {
(x$l0 * 3)
}
Monomorphized AST for program with hash: 9305131916264092540
fn skibbidy$f0(x$l0: Field) -> Field {
(x$l0 * 5)
}
Monomorphized AST for program with hash: …
```
> feat: add option to print monomorphized program

- compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
- test_programs/noir_test_success/out_of_bounds_alignment/Nargo.toml
- test_programs/noir_test_success/out_of_bounds_alignment/src/main.nr
Adds a runtime length check to avoid out of bounds accesses, to emulate the behavior with ACIR dynamic array accesses.
Check one:
> feat: Add brillig array index check

- compiler/noirc_driver/src/contract.rs
- compiler/wasm/src/compile.rs
- compiler/wasm/src/compile_new.rs
- tooling/lsp/src/requests/profile_run.rs
- tooling/nargo/src/artifacts/debug.rs
- tooling/nargo/src/ops/compile.rs
- tooling/nargo/src/ops/mod.rs
- tooling/nargo/src/ops/optimize.rs
- tooling/nargo/src/ops/transform.rs
- tooling/nargo_cli/src/cli/codegen_verifier_cmd.rs
- tooling/nargo_cli/src/cli/compile_cmd.rs
- tooling/nargo_cli/src/cli/dap_cmd.rs
- tooling/nargo_cli/src/cli/debug_cmd.rs
- tooling/nargo_cli/src/cli/execute_cmd.rs
- tooling/nargo_cli/src/cli/info_cmd.rs
- tooling/nargo_cli/src/cli/prove_cmd.rs
- tooling/nargo_cli/src/cli/verify_cmd.rs
- tooling/noirc_abi/src/lib.rs
This PR moves the responsibility for transforming a circuit into a certain expression width into `nargo_cli`. This gives us better separation of concerns where we no longer need to know the target backend before we compile a circuit (i.e. we can save a generic artifact and then target multiple backends using this)
Check one:
> feat: Separate compilation and expression narrowing in `nargo` interface

- .github/scripts/wasm-bindgen-install.sh
- scripts/install_wasm-bindgen.sh
This uses a preinstalled version of wasmbindgen-cli install of recompiling each time
Resolves 
Check one:
> chore: install wasm-bindgen using binstall

- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/hir/type_check/expr.rs
- test_programs/execution_success/regression_4088/Nargo.toml
- test_programs/execution_success/regression_4088/Prover.toml
- test_programs/execution_success/regression_4088/src/main.nr
Resolves #4088
We were calling `instantiate` on identifiers before applying any trait constraints. So if we have a constraint like `Foo<Field>` (referring to the trait `trait Foo<T> { ... }`, and an identifier `foo : forall T. fn(T)`, we need to apply the `T = Field` constraint before instantiating `foo` to replace `T` with a fresh type variable.
Check one:
> fix: apply generic arguments from trait constraints before instantiating identifiers

- acvm-repo/brillig_vm/src/lib.rs
- acvm-repo/brillig_vm/src/memory.rs
- compiler/noirc_driver/src/abi_gen.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
- compiler/noirc_frontend/src/ast/function.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/type_check/expr.rs
- tooling/nargo/src/ops/foreign_calls.rs
Converts usages of `&Vec<T>` to `&[T]`
Resolves https://github.com/noir-lang/noir/issues/679 
`&Vec` can be dereferenced into `&[T]` whereas `&[T]` is more general.
In all but the following two cases, the type can simply be changed:
1. Both `clone` and `to_vec` perform a copy:
```rust
VMStatus::Finished => Some((vm.get_registers().clone(), vm.get_memory().clone())),
VMStatus::Finished => Some((vm.get_registers().clone(), vm.get_memory().to_vec())),
```
2. Both perform a match on the `Option`:
```rust
self.name == name && (self.params.is_none() || self.params.as_ref() == Some(params))
self.name == name && (self.params.is_none() || self.params.as_deref() == Some(params))
```
Check one:
> chore: convert vec references to slices

- tooling/debugger/src/repl.rs
Reduces the amount of information printed to the console after each step, when execution pauses at an ACIR BRILLIG opcode.
Part of #3015. 
Before this change:
```
[1327_concrete_in_generic] Starting debugger
At opcode 0: BRILLIG: inputs: [Single(Expression { mul_terms: [], linear_combinations: [], q_c: 0 }), Single(Expression { mul_terms: [], linear_combinations: [(1, Witness(0))], q_c: 0 })]
outputs: []
[Mov { destination: RegisterIndex(2), source: RegisterIndex(0) }, Mov { destination: RegisterIndex(3), source: RegisterIndex(1) }, Const { destination: RegisterIndex(0), value: Value { inner: 0 } }, Const { destination: RegisterIndex(1), value: Value { inner: 0 } }, Mov { destination: RegisterIndex(2), source: RegisterIndex(2) }, Mov { destination: RegisterIndex(3), source: …
```
> chore(debugger): Limit printed BRILLIG opcode info while stepping in REPL debugger

- tooling/lsp/src/lib.rs
- tooling/nargo/src/workspace.rs
- tooling/nargo_toml/src/lib.rs
Resolves 
LSP crash when source file not in workspace #4143
Check one:
> fix(lsp): crash when file not in workspace

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
The move towards using GitHub Discussions to suggest ideas was found premature following https://github.com/noir-lang/noir/pull/2672, as it introduced additional frictions in:
- Requiring the need to switch between Issues / Discussions to distill ideas raised
- Discussions are not manageable on GitHub's Project Board
Until we can formally define how the Ideas section in GitHub Discussions should be used, this PR reverts the repo back to using GitHub Issues for feature requests for us to move faster in the meantime.
Check one:
> chore(github): Suspend GitHub Discussions Ideas and revert to feature request issues

- compiler/noirc_frontend/src/hir_def/types.rs
Resolves #4151
Adds a manual `Type: Debug` impl for displaying all the information in types a bit more succinctly. This is helpful while debugging generic code for following type variable links which are otherwise excluded from the `Type: Display` impl.
Check one:
> chore: Add Type: Debug impl

- .github/workflows/publish-es-packages.yml
Resolves https://github.com/noir-lang/noir/issues/4157
https://github.com/noir-lang/noir/pull/3891 didn't update release flow so it's still trying to build `noir_wasm` using nix. This PR updates to use the new build process.
Check one:
> chore(ci): fix publishing of `noir_wasm`

- .github/workflows/publish-es-packages.yml
Resolves 
This PR fixes an issue in #4163  where the job dependency was mistyped.
Check one:
> chore: fix js package publishing workflow

- noir_stdlib/src/convert.nr
- noir_stdlib/src/lib.nr
- noir_stdlib/src/prelude.nr
- test_programs/compile_success_empty/trait_generics/src/main.nr
Supercedes #4148 
This PR adds a definition of `From` and `Into` traits into the Noir prelude. I've provided implementations for the primitive types along with the trivial general implementations of the traits.
Check one:
Will document once codegen is up.
> feat: add definitions for From and Into traits to Noir prelude

- docs/docs/noir/concepts/data_types/arrays.md
> fix: Update array method type signatures in the docs

- docs/docs/noir/standard_library/traits.md
- noir_stdlib/src/default.nr
> chore: pull in `Default` trait definition through a snippet

- docs/docs/noir/standard_library/black_box_fns.md
- docs/docs/noir/standard_library/cryptographic_primitives/ecdsa_sig_verification.mdx
- docs/docs/noir/standard_library/cryptographic_primitives/hashes.mdx
- docs/docs/noir/standard_library/cryptographic_primitives/scalar.mdx
- docs/docs/noir/standard_library/cryptographic_primitives/schnorr.mdx
- noir_stdlib/src/ecdsa_secp256k1.nr
- noir_stdlib/src/ecdsa_secp256r1.nr
- noir_stdlib/src/hash.nr
- noir_stdlib/src/scalar_mul.nr
- noir_stdlib/src/schnorr.nr
Resolves https://github.com/noir-lang/noir/issues/4176
Check one:
> chore(docs): update hashes page to pull in code

- .github/workflows/release.yml
- docs/package.json
Resolves 
Currently when cutting a release in CI, docusaurus is looking for `processed-docs` however this hasn't been generated.
This PR then ensures this is up to date when generating a release by running `preprocess` before doing so.
Check one:
> fix(docs): codegen docs before cutting a new version

- acvm-repo/acvm_js/src/logging.rs
Resolves 
Looking at the [CI logs](https://github.com/noir-lang/noir/actions/runs/7698147053/job/20976987617?pr=4194#step:6:16), the ACVM JS failures seem to be happening inside the `init_log_lebel` function. I'm not sure how this panic would be triggered intermittently but this PR removes it in favour of returning a JS error as we shouldn't assume that user inputted log levels are valid.
Check one:
> fix: remove panic from `init_log_level` in `acvm_js`

- acvm-repo/acvm/src/compiler/transformers/mod.rs
Resolves 
smol refactor I noticed.
Check one:
> chore: simplify marking black box function outputs as solvable

- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
Resolves 
I noticed that we were getting suboptimal acir generation when using `.any()` on `BoundedVec` where the `exceededLen` check would get more expensive the longer the `BoundedVec` was.
The issue turned out to be that because we we would sum before multiplying when performing the ORs on the length check, we weren't taking advantage of the fact that multiplication can result in one of its inputs being replaced with a single witness if the result would have been degree 3 or more.
This meant that rather than having a simple `a + b - 2ab` for each OR with `a` and `b` being witnesses , `a` would consist of a quadratic and 2 linear terms. We'd then continue to pick up extra terms for each element in the `BoundedVec`.
The simple fix is then whenever we are performing operations on two …
> feat: multiply first to allow more ACIR gen optimizations

- acvm-repo/acvm/src/compiler/optimizers/redundant_range.rs
…
Complement to https://github.com/AztecProtocol/aztec-packages/pull/4164. I'm going to leave this in draft until we've pushed out a release of `bb` containing the optimisation.
This optimisation is being moved to be a responsibility of the backend so we shouldn't do it here.
Check one:
> feat: remove replacement of boolean range opcodes with `AssertZero` opcodes

- scripts/bootstrap_native.sh
This pull request introduces an improvement to the `bootstrap_native.sh` script. It adds a preliminary check to verify whether Cargo, the Rust package manager, is installed in the environment. This enhancement is aimed at providing clearer error messages to developers setting up the project.
- Added a check in `bootstrap_native.sh` to determine if the `cargo` command is available in the system.
- If Cargo is not found, the script now outputs a user-friendly error message: `Cargo is not installed. Please install Cargo and the Rust toolchain.`
During the setup process, particularly for new contributors or in environments where Rust is not yet installed, the absence of Cargo could lead to a cryptic error message. By explicitly checking for Cargo and providing a clear error message, we make …
> feat: Improve Error Handling for Cargo in Bootstrap Script

- docs/docs/noir/concepts/unconstrained.md
> chore(docs): XOR typo in docs

- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
Resolves 
This PR removes the predicate from `AcirContext.sort()`. I'm not sure why this exists as we should always be able to perform a sorting on an array of values. We also list `Intrinsic::Sort` as having no side effects so it doesn't make sense for us to be using the side effects predicate here.
Check one:
> feat: remove predicate from `sort` intrinsic function

- compiler/noirc_frontend/src/parser/errors.rs
- compiler/noirc_frontend/src/parser/parser.rs
- noir_stdlib/src/cmp.nr
- noir_stdlib/src/convert.nr
- noir_stdlib/src/default.nr
- noir_stdlib/src/ops.nr
- test_programs/compile_success_empty/brillig_cast/src/main.nr
- test_programs/compile_success_empty/brillig_modulo/src/main.nr
- test_programs/execution_success/5_over/src/main.nr
- test_programs/execution_success/bit_shifts_comptime/src/main.nr
- test_programs/execution_success/conditional_regression_underflow/src/main.nr
- test_programs/execution_success/regression/src/main.nr
Breaking change warning for [#4162](https://github.com/noir-lang/noir/issues/4162)
Check one:
> feat: Add warnings for usage of restricted bit sizes

- compiler/noirc_evaluator/src/ssa/ir/instruction.rs
- test_programs/compile_success_empty/literal_not_simplification/Nargo.toml
- test_programs/compile_success_empty/literal_not_simplification/src/main.nr
Resolves 
This PR expands the existing simplification of constant NOT instructions to cover all unsigned integers.
Check one:
> feat: simplify all unsigned constant NOT instructions

- deny.toml
Related to https://github.com/noir-lang/noir/issues/4247
This PR adds a big nasty warning for adding new git dependencies as part of avoiding #4247 happening again.
Check one:
> chore: add warning for adding new git dependencies in `deny.toml`

- Cargo.lock
- acvm-repo/bn254_blackbox_solver/Cargo.toml
- deny.toml
Related to #4247 @TomAFrench has identified that since we are using git dependencies, we are not able to publish acv to crates.io. This uses a published version of grumpkin instead of the git dependency version.
Resolves 
Check one:
> chore: use published noir grumpkin package

- compiler/noirc_evaluator/src/ssa/function_builder/mod.rs
- compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs
A followup to https://github.com/noir-lang/noir/pull/4210
Check one:
> fix: Remove hack in increment_array_reference_count

- compiler/noirc_evaluator/src/errors.rs
Resolves #3687 
This simply adds a secondary message to clarify that using a slice length will lead to the `Could not determine loop bound at compile-time` error. 
I was thinking of disabling this earlier during type check but we don't necessarily know that we will have a slice until codegen as arrays and slices are polymorphic with one another. I also thought about making a separate runtime error to check during loop unrolling but we are not necessarily going to still have the `ArrayLen` call codegen'd in SSA and will instead have the call's results for the loop condition, so this isn't a basic check and some more logic would be needed.
The best option for a specific error check seems to be during `codegen_for` before we codegen the end range. We can check whether we are making a slice …
> chore: Add secondary message for UnknownLoopBound error

- compiler/noirc_evaluator/src/errors.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
- test_programs/compile_failure/brillig_slice_to_acir/Nargo.toml
- test_programs/compile_failure/brillig_slice_to_acir/src/main.nr
- test_programs/compile_failure/brillig_vec_to_acir/Nargo.toml
- test_programs/compile_failure/brillig_vec_to_acir/src/main.nr
Resolves #2535 
We currently panic when attempting to return a slice from an unconstrained runtime to an ACIR runtime. In some cases such as in the linked issue the panic is not very clear at all. 
New error:
Check one:
> fix: Clean error when attemping to return a slice from Brillig to ACIR

- tooling/debugger/src/dap.rs
- tooling/debugger/src/repl.rs
Resolves #4231
The REPL debugger is not handling the case when the compiled circuit has no opcodes and since it assumes there will be some opcodes, it panics on continue.
With this PR, the REPL debugger will start in a "finished" stated in those cases and the DAP will not start the main loop.
This edge case is very unlikely to happen, especially after applying #4185 which changes the default mode for the debugger to Brillig (seems to generate at least a trampoline-like fragment even for empty programs) and after the introduction of debugging instrumentation. Nevertheless it will still be possible (eg. empty program and passing `--acir-mode` option).
Check one:
> fix: Prevent debugger crashing on circuits with no opcodes

- compiler/noirc_frontend/src/hir/type_check/errors.rs
- compiler/noirc_frontend/src/hir/type_check/expr.rs
- test_programs/compile_failure/brillig_mut_ref_from_acir/Nargo.toml
- test_programs/compile_failure/brillig_mut_ref_from_acir/src/main.nr
Resolves #4245 
This adds a type check for call expressions to check the arguments of a call to an unconstrained function from a constrained function. As we have two different runtime environments this makes type checking a bit more complicated. As a followup to this PR we could try and catch the error added here (https://github.com/noir-lang/noir/pull/4280) sooner. However, if the unconstrained function uses generics we must still fall back to the "type check" in SSA/ACIR gen from PR #4280.
This PR now errors for the snippet in issue with the below using `nargo check`:
Check one:
> fix: Type check ACIR mutable reference passed to brillig

- compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs
- compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs
Partial work towards https://github.com/noir-lang/noir/issues/4275
We were mixing Field and u64 types when accessing arrays. Since we index arrays by u64s, always cast array/slice addressing values to u64.
Check one:
> fix: Ssa typing for array & slice indexes

- compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs
Partial work towards https://github.com/noir-lang/noir/issues/4275
Also use the array index type (u64) for assign_lvalue_index.
Check one:
> fix: Ssa typing for assign_lvalue_index

- compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- tooling/debugger/src/context.rs
Resolves 
This PR removes the unnecessary foreign call we're performing for static error messages.
Check one:
> fix: simplify constant assert messages into `ConstrainError::Static`

- compiler/noirc_evaluator/src/ssa.rs
- compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs
Resolves #4070
This PR uses `Instruction::Constrain` to perform simplifications in SSA where one value is swapped for another simpler value due to the fact that the circuit will be unsatisfiable should the two values not be equivalent (because of the `Instruction::Constrain`.
A previous implementation of this resulted in the bug https://github.com/noir-lang/noir/issues/2645. This was because constraints which were only active in certain areas of the code were applied across all of the SSA. This implementation avoids this by using a separate cache for the constrained values for each value of `side_effects_enabled_var`. This means that passing a `Instruction::EnableSideEffects` instruction will "forget" any constraints which aren't currently active.
One trouble from this PR is that we now …
> feat: use constraint information to perform constant folding

- docs/docs/noir/concepts/data_types/integers.md
This pull request addresses an issue identified in the [integers tutorial](https://noir-lang.org/docs/noir/syntax/data_types/integers/), where the `wrapping_add` function was incorrectly called with a single argument `(x + y)` instead of the correct form with two separate arguments `(x, y)`.
The documentation has been updated to reflect the correct usage:
```diff
- std::wrapping_add(x + y)
+ std::wrapping_add(x, y)
```
Special thanks to @Complexlity for identifying this issue and bringing it to attention through issue #4272.
> chore: Fix Incorrect `wrapping_add` Usage in Integers Tutorial

- docs/docs/noir/concepts/mutability.md
Resolves 
While working on  #4293 I noticed our mutability docs were quite outdated, so I updated them.
Check one:
> chore: Update mutability docs

- tooling/nargo_fmt/src/visitor/stmt.rs
- tooling/nargo_fmt/tests/expected/assert.nr
- tooling/nargo_fmt/tests/input/assert.nr
Resolves 
This PR adds a test for how as format `assert` calls along with removal of handling for the `constrain` keyword. We'll now rewrite them to be `assert` although in reality we error out of the formatter before we reach this.
Check one:
> chore: add test for formatting assertions

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Bug Report & Feature Request templates
- Add "Project Impact" and "Workaround" sections
- Minor updates
Bug Report template
- Add NoirJS in the "Environment" section
Preview:
- Bug Report: https://github.com/Savio-Sou/noir/issues/new?template=bug_report.yml
- Feature Request: https://github.com/Savio-Sou/noir/issues/new?template=feature_request.yml
Check one:
> chore(github): Update Issue templates

- .github/actions/install-playwright/action.yml
- .github/scripts/integration-test-browser.sh
- .github/scripts/integration-test-node.sh
- .github/workflows/docker-test-flow.yml
- .github/workflows/docs-pr.yml
- .github/workflows/gates_report.yml
- .github/workflows/publish-es-packages.yml
- .github/workflows/publish-nargo.yml
- .github/workflows/test-js-packages.yml
- compiler/integration-tests/package.json
Resolves 
This should help cut CI times to remove the new bottleneck after #4305 
Check one:
> chore: split node and browser integration tests to run in parallel

- .github/workflows/publish-es-packages.yml
- .github/workflows/test-js-packages.yml
- compiler/wasm/package.json
- compiler/wasm/src/types/noir_artifact.ts
- tooling/noir_js_types/package.json
- tooling/noir_js_types/src/types.ts
- tooling/noirc_abi_wasm/package.json
- tooling/noirc_abi_wasm/src/js_witness_map.rs
- tooling/noirc_abi_wasm/src/lib.rs
- yarn.lock
Resolves 
`noir_wasm`s dependency on `noirc_abi_wasm` is preventing us from building it in parallel. It only relies on types so I've moved those to `noir_js_types` and both of those packages pull these types in.
Check one:
> chore: remove `noir_wasm` dependency on `noirc_abi_wasm`

- compiler/noirc_evaluator/src/brillig/brillig_ir.rs
- tooling/debugger/ignored-tests.txt
Resolves https://github.com/AztecProtocol/aztec-packages/issues/4513
Move registers to registers wasn't ensuring that the destinations were allocated so it was possible to codegen a case where move registers to registers was squashing values
Check one:
> fix: Ensure that destination register is allocated when moving between registers in brillig gen

- compiler/noirc_frontend/src/hir/type_check/expr.rs
- test_programs/execution_success/global_consts/src/main.nr
Resolves #4318 
I've added the necessary `Option` handling for us to make calls from the global context.
Check one:
> fix: allow function calls in global definitions

- tooling/nargo_fmt/src/visitor/stmt.rs
- tooling/nargo_fmt/tests/expected/assert.nr
- tooling/nargo_fmt/tests/input/assert.nr
Due to our use of Display for message formatting, we were generating invalid code.
Output before the PR:
```rust
assert(x, plain::message);
```
Output after the PR:
```rust
assert(x, message);
```
Check one:
> fix: message formatting for assert statement

- docs/docs/noir/standard_library/black_box_fns.md
- docs/docs/tutorials/noirjs_app.md
- docs/versioned_docs/version-v0.23.0/noir/concepts/data_types/fields.md
- docs/versioned_docs/version-v0.23.0/noir/concepts/data_types/integers.md
- docs/versioned_docs/version-v0.23.0/noir/standard_library/black_box_fns.md
- docs/versioned_docs/version-v0.23.0/noir/standard_library/bn254.md
- docs/versioned_docs/version-v0.23.0/noir/standard_library/cryptographic_primitives/ecdsa_sig_verification.mdx
- docs/versioned_docs/version-v0.23.0/noir/standard_library/cryptographic_primitives/hashes.mdx
- docs/versioned_docs/version-v0.23.0/noir/standard_library/cryptographic_primitives/scalar.mdx
- docs/versioned_docs/version-v0.23.0/noir/standard_library/cryptographic_primitives/schnorr.mdx
- docs/versioned_docs/version-v0.23.0/reference/NoirJS/noir_wasm/.nojekyll
- docs/versioned_docs/version-v0.23.0/reference/NoirJS/noir_wasm/functions/compile.md
- docs/versioned_docs/version-v0.23.0/reference/NoirJS/noir_wasm/functions/createFileManager.md
- docs/versioned_docs/version-v0.23.0/reference/NoirJS/noir_wasm/functions/inflateDebugSymbols.md
- docs/versioned_docs/version-v0.23.0/reference/NoirJS/noir_wasm/index.md
- docs/versioned_docs/version-v0.23.0/reference/NoirJS/noir_wasm/type-aliases/CompilationResult.md
- docs/versioned_docs/version-v0.23.0/reference/NoirJS/noir_wasm/typedoc-sidebar.cjs
- docs/versioned_docs/version-v0.23.0/tutorials/noirjs_app.md
Resolves https://github.com/noir-lang/noir/issues/4200.
Copy updates introduced by the PRs listed in the Issue linked into the versioned v0.23.0 doc folder.
Majority of the changes in this PR are merely direct copy-paste of updates from the individual PRs. Exception being minor path fixes.
Check one:
> chore(docs): Update v0.23.0 docs with retroactive doc updates

- .github/workflows/publish-docs.yml
Our docs are currently published when and only when there is a doc change merged to master.
We at times might need more flexibility for publishing docs though (e.g. when a release is flipped stable).
This PR adds a manual trigger for publishing docs.
We attempted automated triggers by release status change (e.g. when a release is flipped from pre-release to stable) some while ago, but that approach would only build and publish docs from the release commit instead of from master (that contains post-release doc patches).
We used to have a manual trigger, which was removed in https://github.com/noir-lang/noir/pull/3877.
Check one:
YOLO
> chore(docs): Add manual trigger for publishing docs

- compiler/noirc_evaluator/src/ssa/ir/instruction/binary.rs
Resolves 
In the vein of #4327. We now replace modulo operations with a power of two with the more specific `Instruction::Truncate`.
Check one:
> feat: replace modulo operations with truncations where possible

- compiler/wasm/package.json
- yarn.lock
Resolves 
`noir_wasm` doesn't use `noirc_abi` so we can remove this dependency.
Check one:
> chore: remove unnecessary dev dependency from `noir_wasm`

- compiler/wasm/scripts/install_wasm-pack.sh
> chore(ci): force the install of wasm-pack when building noir_wasm

- cspell.json
Resolves 
This fixes an issue where some codegened docs has an unrecognised word in it.
Check one:
> chore: add `memfs` to cspell

- .github/actions/setup/action.yml
- .github/workflows/release.yml
Resolves 
Bumps the node version used in CI to the latest v18 version.
Check one:
> chore(ci): bump node to 18.19.0

- .github/workflows/publish-es-packages.yml
Resolves 
Publishing of Noir packages is currently failing due to a `_` being used in place of a `-`.
Check one:
> chore: fix JS package publishing

- compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_black_box.rs
- compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
- compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block_variables.rs
- compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_fn.rs
- compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_slice_ops.rs
- compiler/noirc_evaluator/src/brillig/brillig_ir.rs
- compiler/noirc_evaluator/src/brillig/brillig_ir/artifact.rs
- compiler/noirc_evaluator/src/brillig/brillig_ir/brillig_variable.rs
- compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs
Work towards #4369
Uses consistent bit sizes for truncate and starts a refactor where we start to track bit sizes for values in brillig IR
Check one:
> fix: Consistent bit size for truncate

- .github/EXTERNAL_CONTRIBUTOR_PR_COMMENT.md
- .github/workflows/pull-request-title.yml
Resolves 
This PR adds a sticky comment to any PRs which are opened from another repository which warns against force pushing once we've started reviewing the PR.
Check one:
> chore(ci): add warning for external contributors force pushing

- .github/workflows/pull-request-title.yml
Resolves 
#4373 isn't being triggered properly currently.
Check one:
> chore: fix trigger for force-push sticky comment

- tooling/nargo/src/lib.rs
Resolves https://github.com/noir-lang/noir/issues/4379
This PR adds a filter so we only add files with a `.nr` extension to the file manager.
Check one:
> fix: only add `.nr` files to file manager

- compiler/noirc_frontend/src/monomorphization/mod.rs
Resolves #4290 
Previously, the monomorphizer would assume all numeric generics were Fields, but this was not necessarily true.
Check one:
> fix: Use correct type for numeric generics

- test_programs/execution_success/debug_logs/src/main.nr
Resolves #2903 
I added a function `regression_2903` to the `debug_logs` test that shows we can now accurately print arrays of strings. This was fixed in previous formatting work. I also removed `std::` prefixes from `println` now that we have a prelude.
Check one:
> chore: Test for printing array of strings

- .github/CRATES_IO_PUBLISH_FAILED.md
- .github/JS_PUBLISH_FAILED.md
- .github/workflows/publish-acvm.yml
- .github/workflows/publish-es-packages.yml
Resolves 
This PR adds an action to open an issue if either the ACVM crates or JS packages fail to publish.
Check one:
> chore(ci): add alerts for failed publishes

- docs/versioned_docs/version-v0.23.0/tutorials/noirjs_app.md
Updates the tutorial to work with v 0.23.0
Resolves 
Check one:
> fix(docs): Update noirjs_app for 0.23

- compiler/noirc_evaluator/src/ssa/function_builder/mod.rs
Resolves https://github.com/noir-lang/noir/issues/4275
Adds a check in insert_binary to make sure we don't start codegening non-matching binary ops again.
Check one:
> fix: Enforce matching types of binary ops in SSA

- aztec_macros/src/lib.rs
- compiler/noirc_frontend/src/hir/def_map/mod.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/hir/type_check/expr.rs
- compiler/noirc_frontend/src/hir/type_check/mod.rs
- compiler/noirc_frontend/src/hir/type_check/stmt.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_frontend/src/monomorphization/debug.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
- compiler/noirc_frontend/src/node_interner.rs
- compiler/utils/arena/src/lib.rs
Resolves the underlying issue with #4207 where definition/expr types are being overwritten by other exprs/definitions because DefinitionIds are converted into Indexes which may clash with those from expressions.
Separates out `id_to_type` into another map for only definitions: `definition_to_type` to resolve the clash. I've also removed the `impl From<DefinitionId> for Index` to prevent this issue in the future.
Check one:
> fix: DefinitionIds should not be stored in id_to_type

- noir_stdlib/src/scalar_mul.nr
- test_programs/execution_success/brillig_scalar_mul/src/main.nr
Resolves  https://github.com/noir-lang/noir/issues/4260
The error is explained in the comment I've added to the stdlib. This is a quick fix and we can clean it up once we're making serialisation changes in `aztec-packages` again.
Check one:
> fix: correct invalid brillig codegen for `EmbeddedCurvePoint.add`

- compiler/wasm/package.json
- compiler/wasm/webpack.config.ts
- yarn.lock
Resolves 
Bumping all the webpack dependencies to see if that helps with build stability.
Check one:
> chore: bump webpack dependencies

- tooling/nargo_toml/src/errors.rs
Resolves 
This addresses an issue that a user in the discord is running into where they're trying to load a workspace as a dependency and can't figure out how to fix their Nargo.toml.
We should probably be embedding links to the docs but that would require some setup so that we point to the correct version, etc.
Check one:
> feat: update error message when trying to load workspace as dependency

- docs/docs/noir/standard_library/containers/vec.mdx
Working towards #4348
We'll soon have bounded vec and hashmap types documented so I thought I'd create a new `containers` folder for documentation of the `std::containers` module.
Minor updates in the Vec docs:
- Removed implementation details from methods
- Reordered `Vec::len` up to the top since it is important
- Minor grammar fixes
Check one:
> chore: Update Vec docs

- .github/workflows/docs-pr.yml
- .github/workflows/formatting.yml
- .github/workflows/gates_report.yml
- .github/workflows/publish-acvm.yml
- .github/workflows/publish-es-packages.yml
- .github/workflows/publish-nargo.yml
- .github/workflows/test-js-packages.yml
- .github/workflows/test-rust-workspace-msrv.yml
- .github/workflows/test-rust-workspace.yml
- Cargo.toml
- Dockerfile.ci
- README.md
- docs/docs/getting_started/installation/other_install_methods.md
- flake.nix
- rust-toolchain.toml
- tooling/nargo/build.rs
- tooling/nargo_cli/build.rs
Resolves 
Bumpalo bumped their MSRV in a [patch/minor release](https://github.com/fitzgen/bumpalo/commit/f8597ceb3600807a902fa9692fb43c49e7b63b27) and wasmer is using an unlocked dependency so we need to bump to match.
Check one:
> chore!: bump msrv to 1.73.0

- .github/scripts/wasm-opt-install.sh
- .github/workflows/publish-es-packages.yml
- .github/workflows/test-js-packages.yml
Resolves 
We're currently building unoptimised wasm binaries in CI as wasm-opt isn't installed. This PR installs wasm-opt to perform these optimisations.
Check one:
> feat(ci): Use wasm-opt when compiling wasm packages

- noir_stdlib/src/collections.nr
- noir_stdlib/src/collections/map.nr
- noir_stdlib/src/hash.nr
- noir_stdlib/src/hash/pedersen.nr
- test_programs/compile_failure/hashmap_load_factor/Nargo.toml
- test_programs/compile_failure/hashmap_load_factor/Prover.toml
- test_programs/compile_failure/hashmap_load_factor/src/main.nr
- test_programs/execution_success/hashmap/Nargo.toml
- test_programs/execution_success/hashmap/Prover.toml
- test_programs/execution_success/hashmap/src/main.nr
- test_programs/execution_success/hashmap/src/utils.nr
This PR shall bring HashMap into the `stdlib` of Noir.
Resolves #4241
Implementation of `HashMap` with open addressing and quadratic probing scheme. Since Noir requires knowing loop bounds (and recursive calls) at compile time, `HashMap` is of fixed capacity and **no** dynamic resize is accomplished with regard to load factor. 
Furthermore, contribution includes implementation of `PedersenHasher` to be used for now. One can examine potentially better and less heavy prehash functions. 
I tried to conform with best practices of engineering, however since Noir is in rapid development, there are certain things which may be optimized in future, both from the code style and performance point of view.
I put the `PedersenHasher` among the `poseidon.nr` and `mimc.nr`, so one can consider moving …
> feat: Add HashMap to the stdlib

- compiler/noirc_evaluator/src/ssa.rs
Before https://github.com/noir-lang/noir/pull/4240 we needed mem2reg to be run as to not panic when fetching slice lengths.
After the linked PR we have an improved startegy for tracking slice capacities by generating a slice capacities map before merging of values. This should enable us to remove a mem2reg pass that is run before flattening. 
Check one:
> chore(ssa): Remove mem2reg run before flattening

- compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs
Resolves 
We're currently printing out every expression we're monomorphising.
Check one:
> fix: remove print from monomorphization pass

- acvm-repo/brillig_vm/src/arithmetic.rs
Resolves #2480
In BrilligVM, we have now the same behaviour regarding division by 0. Whether it is a field or integer division, we return 0 when dividing by zero. Since we have a constraint which checks that the inverse times itself is 1, this constraint will always fail if we divide by zero (instead of panic or returning an error).
Check one:
> chore: do not panic when dividing by zero

- compiler/wasm/src/compile.rs
- compiler/wasm/src/compile_new.rs
- compiler/wasm/src/index.cts
- compiler/wasm/src/index.mts
- compiler/wasm/src/lib.rs
- compiler/wasm/src/noir/noir-wasm-compiler.ts
- compiler/wasm/src/types/noir_artifact.ts
- compiler/wasm/test/compiler/browser/compile.test.ts
- compiler/wasm/test/compiler/node/compile.test.ts
- compiler/wasm/test/compiler/shared/compile.test.ts
- compiler/wasm/test/wasm/browser/index.test.ts
- compiler/wasm/test/wasm/node/index.test.ts
Resolves 
This PR exposes separate functions to compile contracts vs programs in the wasm compiler. This allows us to simplify various code paths as we don't need to deal with the potential for the two artifact types as this just leads to us asserting types and breaking type safety.
Check one:
> feat: expose separate functions to compile programs vs contracts in `noir_wasm`

- .github/ACVM_NOT_PUBLISHABLE.md
- .github/workflows/test-rust-workspace-msrv.yml
- .github/workflows/test-rust-workspace.yml
- cspell.json
Resolves 
Current the MSRV check CI runs on every PR so if one of our dependencies breaks us, all merges halt until we fix this. This is unnecessary as we only need to stop publishing releases and normal development work can continue.
This PR switches this workflow to instead run only on master and on a nightly schedule. If the workflow fails then an issue will be raised.
Check one:
> chore(ci): prevent msrv checks from blocking PRs

- tooling/nargo_fmt/src/utils.rs
- tooling/nargo_fmt/src/visitor/item.rs
- tooling/nargo_fmt/tests/expected/databus.nr
- tooling/nargo_fmt/tests/input/databus.nr
Resolves 
This PR fixes an issue uncovered by #4422 where we're not properly formatting databus visibility modifiers. I've fixed this and added a new test case for regressions.
Check one:
> fix: correct formatting for databus visibility types

- Cargo.lock
- compiler/noirc_driver/Cargo.toml
- compiler/noirc_driver/src/lib.rs
- compiler/noirc_evaluator/src/errors.rs
- compiler/noirc_frontend/src/monomorphization/debug.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
- compiler/noirc_frontend/src/tests.rs
- tooling/nargo/src/ops/test.rs
Resolves #4407 
We currently have no way to gracefully error during monomorphization and so must panic if we run into any errors.
This PR then adds the `MonomorphizationError` enum with an example error type. We've also added a `CompileError` which unifies `RuntimeError` and `MonomorphizationError` so they can be converted into `FileDiagnostic`s
Check one:
> fix: remove panic when generic array length is not resolvable

- noir_stdlib/src/collections/bounded_vec.nr
- noir_stdlib/src/hash/poseidon2.nr
- test_programs/noir_test_success/bounded_vec/src/main.nr
Removes the `empty_value` field from the bounded vec. This muddies the API and shouldn't be needed since we have `crate::unsafe::zeroed()` instead.
Check one:
- Included in https://github.com/noir-lang/noir/pull/4430
> chore!: Remove empty value from bounded vec

- .github/EXTERNAL_CONTRIBUTOR_PR_COMMENT.md
- .github/workflows/pull-request-title.yml
Resolves #
This workflow was failing due to the fact that we're storing the message in a file but not checking out the repository.
While checking out would be safe in this case, I've just moved the comment into the workflow for paranoia reasons.
Check one:
> chore(docs): fix external contributor force push workflow

- docs/docusaurus.config.ts
The "Edit this page" button in the generated documentation for the `noir-lang` project leads to a 404 - Page Not Found error for documents in the development version. This issue is due to the button's link containing `/processed-docs` in the path instead of `/docs`. The problem affects the development version of the documentation, whereas versioned documentation (e.g., v0.23.0) correctly links to editable markdown files on GitHub.
| Before                                                                                             | After                                                                                              |
| -------------------------------------------------------------------------------------------------- | …
> chore(docs): correct 'Edit this page' URL for dev docs

- compiler/noirc_frontend/src/parser/parser/function.rs
Resolves 
This PR creates a parser for `'pub(crate)'|'pub'|''` which returns the `FunctionVisibility`. This allows parsing visibility more reusable for when we add visibility for imports, structs, etc.
Check one:
> chore: create parser specifically for function visibility

- package.json
Resolves #4446 
We're currently not building `noir_codegen` before we publish so I've updated the build script.
Check one:
> fix: build noir_codegen when publishing

- compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
Avoid codegening overhead for no-op range checks generated by https://github.com/noir-lang/noir/issues/4456
Check one:
> feat: skip redundant range checks in brillig

- compiler/integration-tests/package.json
- compiler/integration-tests/test/mocks/os.js
- compiler/integration-tests/web-test-runner.config.mjs
- tooling/noir_js_backend_barretenberg/src/index.ts
- tooling/noir_js_backend_barretenberg/src/types.ts
- yarn.lock
Makes `BackendBarretenberg` pass all the options to the `bb.js` instance.
Makes `BackendBarretenberg` pass all the options to the `bb.js` instance, namely min and max memory. Manually setting max memory makes iOS not immediately kill workers on the browser.
This is already implemented in BB as per [this PR](https://github.com/AztecProtocol/aztec-packages/pull/3265)
Replicates the change I made in a pinch for `progrcrypto` Istanbul. [Example usage here](https://github.com/signorecello/progcrypto23-act/blob/f95f267f2460a423f99865ca30e29f89e8104bc5/packages/user/pages/index.tsx#L31)
> feat: add option to set max memory for bb.js

- tooling/lsp/src/requests/profile_run.rs
- tooling/nargo/src/ops/compile.rs
- tooling/nargo/src/ops/mod.rs
- tooling/nargo_cli/src/cli/check_cmd.rs
- tooling/nargo_cli/src/cli/codegen_verifier_cmd.rs
- tooling/nargo_cli/src/cli/compile_cmd.rs
- tooling/nargo_cli/src/cli/debug_cmd.rs
- tooling/nargo_cli/src/cli/execute_cmd.rs
- tooling/nargo_cli/src/cli/export_cmd.rs
- tooling/nargo_cli/src/cli/fmt_cmd.rs
- tooling/nargo_cli/src/cli/info_cmd.rs
- tooling/nargo_cli/src/cli/prove_cmd.rs
- tooling/nargo_cli/src/cli/verify_cmd.rs
Related to #3503 
This PR removes the extra copy of the `report_errors` function.
Check one:
> chore: export `report_errors` from `nargo`

- docs/docs/noir/standard_library/containers/index.md
The "containers" section of noir's docs was the only section not capitalized previously
I checked "Documentation included in this PR." so that docs can be regenerated for this PR and we can see the section is capitalized.
Check one:
> chore: Capitalize containers section in docs

- docs/docs/noir/standard_library/cryptographic_primitives/eddsa.mdx
- noir_stdlib/src/eddsa.nr
- test_programs/execution_success/eddsa/src/main.nr
Gives a source of truth for deriving public keys for EdDSA signatures, e.g. for testing.
Adds this function:
```rust
fn eddsa_poseidon_to_pub(secret: Field) -> (Field, Field)
```
Check one:
> feat: Add eddsa_poseidon_to_pub function to stdlib with test + docs

- tooling/lsp/src/requests/test_run.rs
- tooling/nargo/src/ops/test.rs
- tooling/nargo_cli/src/cli/test_cmd.rs
Resolves 
This is a dirty hack to get tests running in parallel. To do this, we've given up printing the test results in a stream as they're run but we instead wait for all tests in a package to be run before we print them out in one go.
This takes the noir-protocol-circuits test suite from taking 1:46s to 27s.
Check one:
> feat: run tests in parallel in `nargo test` 

- deny.toml
Resolves 
cargo deny is deprecating a bunch of its config file so this PR updates to the new format.
Check one:
> chore: update cargo deny config

- compiler/wasm/src/noir/package.ts
Github deps are directly added to the file manager, which causes them to be missing the absolute path to the source file and only include the extraction directory relative to the fm root directory. This caused the path to the file to be formatted in an unexpected way and the compiler to panic.
Resolves: https://github.com/noir-lang/noir/issues/4355
Check one:
> fix: handling of gh deps in noir_wasm

- compiler/noirc_driver/src/lib.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/def_map/mod.rs
- compiler/noirc_frontend/src/tests.rs
Resolves 
We're cloning unnecessarily here as we can just pass the processors by reference.
Check one:
> chore: pass macro processors by reference

- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/resolution/import.rs
Resolves 
We don't need to pass by value here so we can just pass by reference instead.
Check one:
> chore: pass `import_directive` by reference

- compiler/noirc_frontend/src/hir/type_check/expr.rs
- compiler/noirc_frontend/src/tests.rs
- test_programs/execution_success/slices/src/main.nr
Resolves #4506
`==` on slices previously tried to use the built-in impl we have but this leads to a panic when evaluating binary operators in SSA. We expect both sides of the binary to be non-tuples but this isn't true for slice values. Instead of making this work for tuples I changed the type checker to force slices to use the stdlib impl we have for `==` rather than the built in one.
Check one:
> fix: Force src impl for == on slices

- compiler/noirc_frontend/src/ast/statement.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- compiler/noirc_frontend/src/parser/mod.rs
- compiler/noirc_frontend/src/parser/parser.rs
Resolves 
This is some groundwork pulled out from https://github.com/noir-lang/noir/pull/4491
We're going to want to apply visibility modifiers to module declarations so this PR creates a proper struct for these so it's easier for us to add an extra field to hold the visibility.
Check one:
> chore: add `ModuleDeclaration` struct

- compiler/noirc_frontend/src/hir/resolution/errors.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/hir/type_check/errors.rs
- compiler/noirc_frontend/src/hir/type_check/mod.rs
- compiler/noirc_frontend/src/hir_def/function.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_frontend/src/tests.rs
Resolves #4500
This was due to this check https://github.com/noir-lang/noir/blob/master/compiler/noirc_frontend/src/hir_def/types.rs#L706-L709 which was needed since we checked if types were valid for main during name resolution - which is before we know type aliases are not cyclic. I've moved this check to type checking instead.
Check one:
> fix: Allow type aliases in main

- .github/JS_PUBLISH_FAILED.md
- .github/workflows/publish-es-packages.yml
Resolves #
The 0.24.0 publish failed and was rerun after some more commits were merged into master. This caused an issue as some of the jobs weren't properly pulling the historical commit to build from and instead built from master. This caused inconsistent serialisation formats as there was likely a serialisation between those two commits.
This PR ensures that all packages are built from the same commit and also fixes a broken reporting mechanism.
Check one:
> chore(ci): fix JS publishing workflow checking out inconsistent commits

- compiler/noirc_frontend/src/monomorphization/mod.rs
Resolves https://github.com/noir-lang/noir/issues/4518
A match case for `Type::Alias` was forgotten when that was initially added.
Check one:
> fix: Add `follow_bindings` to follow `Type::Alias` links

- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
Resolves 
The `array_typ.contains_slice_element()` check in `can_omit_element_sizes_array` is incorrect.
This should have been `is_nested_slice()` but we already banned nested slices so I just removed it. This leads to improvements for slices in general so I have made it a separate PR.
This was also a blocker for https://github.com/noir-lang/noir/pull/4523. When working with `AsSlice` we would omit the element sizes array. When it came time to access a slice created with `as_slice()` we would attempt to use the element sizes array which was never initialized correctly and we would go out of bounds.
Check one:
> fix(acir_gen): More granular element sizes array check

- compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
Temporary regisers are not conserved when calling and returning from another function, only alive variables are conserved. The condition in an assert was computed before the call to the dynamic message handler so it could be overwritten by the callee. I just compute the condition after the potential call.
Check one:
> fix: Dynamic assert messages in brillig

- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- test_programs/execution_success/global_consts/src/main.nr
Resolves #1440
This was a fairly simple change - non-integer globals used to be resolved before struct methods were even collected. I've moved this to after methods are collected. Now global resolution is the first step of resolving in general.
Integer globals are still resolved early since structs may refer to them in numeric generics.
Check one:
> fix: Allow non-integer globals to reference struct methods

- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_frontend/src/tests.rs
Resolves #4545
A prior assumption we had where we didn't need to bind generics just to check how many fields a type can have turned out not to be true. Binding generics is important for cases such as the new test case where generic lengths are used.
Check one:
> fix: Substitute generics when checking the field count of a type

- noir_stdlib/src/hash.nr
Resolves a TODO in #4241 
Adds the remaining Hash impls for primitive types in the stdlib
I've marked this as "no documentation needed" but we should probably document somewhere that these types are hashable. Where should this go? The existing "hash methods" page doesn't seem to fit.
Check one:
> chore: Add more `Hash` impls to stdlib

- tooling/nargo_cli/Cargo.toml
The acvm binary was added recently which prevents developers from using `cargo run` without an additional `--bin nargo` to specify the nargo binary
Sets the default binary to run to `nargo` for `cargo run`.
Check one:
> fix: Make `nargo` the default binary for cargo run

- .github/scripts/noir-wasm-build.sh
Resolves 
Docker tests have been broken for a while. This PR builds the types package so that the `noir_wasm` package can build.
Check one:
> chore: fix docker test workflows

- docs/package.json
Followup to https://github.com/noir-lang/noir/pull/4568
Fixes https://github.com/noir-lang/noir/actions/runs/8347752784/job/22848198145#step:5:1324
Looks like the typedoc plugin doesn't build transitive dependencies if they're reexported so we need to ensure that the ACVM crate is built and available.
Check one:
> chore: fix docs builds on master

- tooling/debugger/tests/debug.rs
Resolves 
We're currently not closing the spawned bash process so we have to wait for the full timeout duration before the test registers as successful. This PR then adds an explicit call to `exit` to finish the test early.
I've also shortened the timeout as 2 minutes seems excessive.
Check one:
> chore(ci): fix long debugger test times

- tooling/nargo_cli/benches/criterion.rs
- tooling/nargo_cli/benches/utils.rs
Resolves 
This PR gets our criterion benchmarks working again after we made various changes to the repo structure. I've also changed it to bench proving times.
I'm going to follow up with changes to run this in CI.
Check one:
> chore: fix up benchmarking scripts

- compiler/noirc_frontend/src/hir/type_check/errors.rs
- compiler/noirc_frontend/src/hir/type_check/stmt.rs
Resolves https://github.com/noir-lang/noir/issues/4267
New error:
```bash
error: Strings do not support indexed assignment
┌─ /Users/michaelklein/Coding/rust/noir/test_programs/compile_failure/mutable_str_index/src/main.nr:3:5
│
3 │     example[0] = "?";
│     -------
│
Aborting due to 1 previous error
```
Check one:
> feat: add specific error for attempting `string[x] = ".."`

- aztec_macros/src/transforms/events.rs
- aztec_macros/src/transforms/functions.rs
- aztec_macros/src/transforms/storage.rs
- compiler/noirc_frontend/src/ast/expression.rs
- compiler/noirc_frontend/src/ast/function.rs
- compiler/noirc_frontend/src/ast/statement.rs
- compiler/noirc_frontend/src/debug/mod.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/hir/type_check/mod.rs
- compiler/noirc_frontend/src/hir_def/expr.rs
- compiler/noirc_frontend/src/lexer/token.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
- compiler/noirc_frontend/src/parser/parser.rs
- tooling/nargo_fmt/src/visitor/expr.rs
Resolves 
This PR splits out some more mundane changes from #4429. `BlockExpression` is now a standard rather than tuple struct to make it easier for us to add an `unsafe` property (and potentially `unchecked` in future)
Check one:
> chore: convert `BlockExpression` into a standard struct

- .github/ACVM_PUBLISH_FAILED.md
- .github/workflows/publish-acvm.yml
Addresses incorrect content of #4634
We were raising an alert for a bad publish of the ACVM crates as if they were the JS packages so this PR updates the alert to be consistent.
Check one:
> chore: fix acvm crates reporting errors as JS packages

- Cargo.lock
- Cargo.toml
- acvm-repo/bn254_blackbox_solver/Cargo.toml
- release-please-config.json
Resolves #4634 
The ACVM crate publishing steps are failing because when `barretenberg_blackbox_solver` was renamed to `bn254_blackbox_solver` the release please config wasn't updated to match, resulting in the version not being incremented on releases.
Check one:
> chore: fix versioning of `bn254_blackbox_solver` crate

- .github/workflows/release.yml
Resolves 
We currently don't have any feedback for when the release workflow doesn't fully complete to signal that releases shouldn't be made. I've updated the workflow so that we post a sticky comment in this situation.
Check one:
> chore(ci): add warning sticky comment

- .github/workflows/release.yml
Resolves 
Followup to #4647 
The previous PR has a missing brace which invalidates the workflow. This PR adds this.
Check one:
> chore: add missing brace to workflow

- .github/workflows/release.yml
Resolves 
See comment
Check one:
> chore: pass release PR number to sticky comment action

- tooling/nargo_cli/src/main.rs
Resolves 
This PR updates the filter on span events so that we get the duration of the span being printed.
Example output:
```
2024-03-27T17:18:17.207634Z TRACE check_crate{crate_id=Root(1) deny_warnings=false disable_macros=false}: noirc_driver: new
2024-03-27T17:18:17.238046Z TRACE check_crate{crate_id=Root(1) deny_warnings=false disable_macros=false}: noirc_driver: close time.busy=30.4ms time.idle=39.3µs
2024-03-27T17:18:17.238075Z TRACE compile_no_check{function_name="main"}: noirc_driver: new
2024-03-27T17:18:17.238081Z TRACE compile_no_check{function_name="main"}:monomorphize: noirc_frontend::monomorphization: new
2024-03-27T17:18:17.238180Z TRACE compile_no_check{function_name="main"}:monomorphize: noirc_frontend::monomorphization: close time.busy=95.5µs time.idle=3.56µs …
```
> chore: include durations of tracing spans in log output

- compiler/noirc_driver/src/lib.rs
- compiler/noirc_frontend/src/ast/statement.rs
- compiler/noirc_frontend/src/debug/mod.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/hir/type_check/stmt.rs
- compiler/noirc_frontend/src/hir_def/stmt.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_frontend/src/monomorphization/errors.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
- compiler/noirc_frontend/src/parser/parser.rs
- test_programs/compile_failure/array_length_defaulting/Nargo.toml
- test_programs/compile_failure/array_length_defaulting/src/main.nr
- test_programs/compile_failure/typevar_default/Nargo.toml
- test_programs/compile_failure/typevar_default/src/main.nr
- test_programs/compile_success_empty/option/src/main.nr
- test_programs/execution_success/prelude/src/main.nr
- tooling/noirc_abi/src/lib.rs
Resolves 
Adds an error when encountering an unbound `TypeVariableKind::Normal` instead of defaulting it to a Field.
Check one:
> fix: Error when a type variable is unbound during monomorphization instead of defaulting to Field

- compiler/noirc_evaluator/src/ssa.rs
- compiler/noirc_evaluator/src/ssa/opt/inlining.rs
…y clones
Resolves 
I just noticed a spot that was missed in inlining where `RuntimeType::is_entry_point` could be used rather than matching on `RuntimeType`. This is also better cause it stays in line with the filter for `get_entry_point_functions`. 
Check one:
> chore: Use is_entry_point helper on RuntimeType

- compiler/noirc_evaluator/src/ssa/ir/instruction.rs
- compiler/noirc_evaluator/src/ssa/ir/instruction/call.rs
Resolves 
We're currently not making full use of type information when optimizing out range constraints in SSA. I don't think makes a huge difference as they should be removed in ACIR gen but it's good to catch these early.
Check one:
> feat: improve optimisations on range constraints

- compiler/noirc_evaluator/src/ssa/ir/instruction/binary.rs
Resolves 
This PR adds some improvements for SSA generation for programs such as in #4688 where we now make more use of information on casted values.
Check one:
> feat: improve SSA type-awareness in EQ and MUL instructions

- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/resolution/errors.rs
- compiler/noirc_frontend/src/hir/resolution/import.rs
- compiler/noirc_frontend/src/hir/resolution/path_resolver.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/hir/resolution/traits.rs
- compiler/noirc_frontend/src/hir/type_check/mod.rs
Resolves 
This PR pulls out the actual changes to path resolution from #4491, omitting the changes which add visibility modifiers to modules.
We now determine whether a function is private (and so a warning or error should be emitted) during def collection. This is necessary as to properly determine whether a function is public or private we need information on whether all the modules in the function's path relative to where it's being used allow its contents to be used from this module - information which doesn't exist in the typechecking pass.
Check one:
> chore: check for references to private functions during path resolution

- compiler/noirc_evaluator/src/ssa/ir/instruction/binary.rs
No issue as this was found by @jfecher while testing in debug mode where we get overflow errors after https://github.com/noir-lang/noir/pull/4691
Resolves https://github.com/noir-lang/noir/pull/4699#discussion_r1548634192
Check one:
> fix(ssa): Do not use get_value_max_num_bits when we want pure type information

- noir_stdlib/src/field/bn254.nr
Field comparisons could be tricked by a malicious prover by decomposing 0 as either (PLO,PHI) o (0,0). Now we reuse instead the assert_gt code by extracting it to an assert_gt_limbs that is shared among decompose (to check that the decomposition of x is less than the decomposition of the field modulus, that is, that the decomposition of the field modulus is greater than the decomposition of x) and assert_gt (to check that the decomposition of a is greater than the decomposition of b)
Check one:
> fix: Field comparisons

- compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_fn.rs
- compiler/noirc_evaluator/src/brillig/brillig_ir/artifact.rs
- compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
- test_programs/execution_success/brillig_slice_input/Nargo.toml
- test_programs/execution_success/brillig_slice_input/src/main.nr
Allows passing slices to brillig entry points, since ACIR knows the initial length of the slice and is fixed at compile time.
Check one:
> feat: Allow slices to brillig entry points

- .github/workflows/docs-pr.yml
- .github/workflows/publish-docs.yml
- docs/package.json
Resolves 
When cutting a new version of the docs in release PRs we're querying the list of released noir versions from github and updating `versions.json` before we cut the new version. This results in docusaurus thinking that it should already have content for that version.
We can then no longer build the docs site in order to do all of the necessary preprocessing before creating the new versioned docs folder.
This PR stops the automated polling of github on every build to prevent this issue.
Check one:
> chore(ci): stop updating version list before cutting new docs version

- Cargo.lock
Resolves 
This fixes a vulnerability notice in cargo-deny.
Check one:
> chore: update from vulnerable version of h2

- package.json
Resolves 
This was removed in #4681 however it is required by the publish workflow for js packages. I've modified it to exclude the wasm based packages rather than being an explicit whitelist to avoid it missing off any new JS packages in future.
Check one:
> chore(ci): replace `yarn build:js:only` script

- docs/package.json
- docs/scripts/cut_version.sh
Resolves 
Followup to https://github.com/noir-lang/noir/pull/4726. The previous PR was slightly too blunt, we still need to generate `versions.json` but we need to filter out the new version before we build the docs as we're trying to build a new version of the docs before we've fully generated the dev version of the docs from which it is to be made.
We now generate `versions.json` as before but filter out the version of the docs which we are making before we build so that the build can complete.
Check one:
> chore(ci): fix cutting new versions of the docs

- docs/docs/how_to/how-to-oracles.md
We removed the old Value struct that added the objects with "inner" on the JS side for oracles.
Check one:
> chore: Remove the old Value struct from the oracle docs

- compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs
- compiler/noirc_frontend/src/monomorphization/ast.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
- compiler/noirc_frontend/src/monomorphization/printer.rs
- test_programs/execution_success/unit_value/Nargo.toml
- test_programs/execution_success/unit_value/src/main.nr
Resolves #4791
Zeroed used boolean values since we didn't have true unit values before. These were meant to be filtered out by the type but as shown in the issue, they'd still be used if they were directly returned.
Check one:
> fix: Fix panic when returning a zeroed unit value

- compiler/noirc_frontend/src/monomorphization/mod.rs
Resolves 
The original intention of this was to store functions and globals but after globals were implemented, only functions ended up being used in the `globals` hashmap. We also probably don't want to monomorphize globals into different copies going forward so I renamed the map to `functions` and clarified references to it to avoid confusion.
Check one:
> chore: Rename 'global' to 'function' in the monomorphization pass

- tooling/noirc_abi/src/errors.rs
- tooling/noirc_abi/src/input_parser/mod.rs
- tooling/noirc_abi/src/lib.rs
- tooling/noirc_abi_wasm/test/browser/errors.test.ts
- tooling/noirc_abi_wasm/test/node/errors.test.ts
Resolves #3560 
Resolves #4778 
This PR updates `InputValue.matches_abi` to `InputValue.find_type_mismatch` which returns an error related to the type which is failing to be abi encoded.
This should help @alexghr with debugging #4778 
Check one:
> feat: narrow ABI encoding errors down to target problem argument/field

- docs/docs/noir/concepts/oracles.md
- tooling/nargo/src/ops/foreign_calls.rs
Resolves #4772
This PR adds the `NARGO_FOREIGN_CALL_TIMEOUT` environment variable which allows setting the number of milliseconds which external foreign call resolvers can take to return a result.
Check one:
> feat: add `NARGO_FOREIGN_CALL_TIMEOUT` environment variable

- acvm-repo/acvm/src/pwg/blackbox/bigint.rs
- test_programs/execution_success/bigint/src/main.nr
Resolves #4578. The fix for issue #4530 has also being merged back so I also activate the related test case.
Field inversion for bigints had a typo.
I did not consider biguint256 since it was decided not to merge the PR.
Check one:
> fix: proper field inversion for bigints

- compiler/noirc_frontend/src/parser/mod.rs
- compiler/noirc_frontend/src/parser/parser.rs
- tooling/noirc_abi/src/input_parser/mod.rs
Resolves 
I'm fixing some clippy warnings which are popping up in my IDE.
This PR also runs the nightly version of clippy and fixes some of the issues where appropriate.
Check one:
> chore: run clippy

- .github/workflows/test-rust-workspace-msrv.yml
Resolves 
We weren't checking out the repo and had the wrong filename so the github action couldn't open an issue properly when the CI started failing.
Check one:
> chore(ci): fix alerts on msrv issues

- docs/docs/noir/modules_packages_crates/workspaces.md
- docs/versioned_docs/version-v0.17.0/modules_packages_crates/workspaces.md
- docs/versioned_docs/version-v0.19.0/modules_packages_crates/workspaces.md
- docs/versioned_docs/version-v0.19.1/modules_packages_crates/workspaces.md
- docs/versioned_docs/version-v0.19.2/modules_packages_crates/workspaces.md
- docs/versioned_docs/version-v0.19.3/modules_packages_crates/workspaces.md
- docs/versioned_docs/version-v0.19.4/modules_packages_crates/workspaces.md
- docs/versioned_docs/version-v0.22.0/noir/modules_packages_crates/workspaces.md
- docs/versioned_docs/version-v0.23.0/noir/modules_packages_crates/workspaces.md
- docs/versioned_docs/version-v0.24.0/noir/modules_packages_crates/workspaces.md
- docs/versioned_docs/version-v0.25.0/noir/modules_packages_crates/workspaces.md
- docs/versioned_docs/version-v0.26.0/noir/modules_packages_crates/workspaces.md
- docs/versioned_docs/version-v0.27.0/noir/modules_packages_crates/workspaces.md
Resolves #4805
This PR fixes the issue found by @iAmMichaelConnor in #4805, where the example Nargo.toml content for [workspace] has 
members with wrong paths. 
Since the structure has Nargo.toml inside the `crates` folder, then `members` should direct to folders inside `crates`.
``` file structure
├── crates
│   ├── a
│   │   ├── Nargo.toml
│   │   └── src
│   │       └── main.nr
│   └── b
│       ├── Nargo.toml
│       └── src
│           └── main.nr
├── Nargo.toml
└── Prover.toml
```
All nargo versions I've tested with, from v0.19.0 to v0.27.0, return `Cannot read file /home/sihanouk/crates/crates/a/Nargo.toml - does it exist?` without the fix.
Check one:
> chore(docs): fix wrong Nargo.toml workspace examples

- noir_stdlib/src/collections/bounded_vec.nr
Resolves 
We've got some leftovers from when arrays were indexed with `Field`s here which we can remove.
Check one:
> chore: remove unnecessary casts in `BoundedVec`

- noir_stdlib/src/collections/bounded_vec.nr
Resolves #4827 
We're currently not implementing the `Eq` trait on `BoundedVec`, which is added in this PR.
I've opted for ignoring differences in the storage array past `len` as while it's not possible to have non-zeroed entries past this index if you use the proper interface, it's possible to construct `BoundedVec`s for which this is not the case. Once we allow proper encapsulation of the internal state then we could simply check that the underlying storage is equal.
Check one:
> feat: implement `Eq` trait on `BoundedVec`

- noir_stdlib/src/collections/bounded_vec.nr
Resolves 
This PR follows up on #4830 to simplify the implementation based on discussion in that PR.
Check one:
> feat: simplify `BoundedVec::eq`

- docs/docs/noir/standard_library/traits.md
- noir_stdlib/src/cmp.nr
Resolves https://github.com/noir-lang/noir/issues/4781
This PR adds an equivalent to Rust's `std::cmp:max` and `std::cmp::min` https://doc.rust-lang.org/src/core/cmp.rs.html#1209
Check one:
> feat: add `min` and `max` functions to the stdlib

- acvm-repo/acvm_js/test/browser/black_box_solvers.test.ts
We're intermittently failing in CI due to #4849 however this initialisation is not strictly necessary. I'm then disabling it until a permanent fix is in place.
Check one:
> chore: remove initialisation of logger in `acvm_js` tests

- noir_stdlib/src/convert.nr
Resolves 
This PR just updates the `Into` trait definition to use a more explicit `self` parameter.
Check one:
> chore: more explicit `self` parameter in `Into` trait

- compiler/noirc_frontend/src/lexer/token.rs
Resolves 
This attribute is now no longer used internally by the compiler so we can just remove it.
Check one:
> chore: remove `SecondaryAttribute::Event`

- compiler/noirc_frontend/src/hir/comptime/scan.rs
Resolves https://github.com/noir-lang/noir/issues/4892
Check one:
> fix(experimental): Skip over comptime functions in scan pass

- .github/actions/install-playwright/action.yml
- .github/workflows/test-js-packages.yml
- Cargo.lock
Copy of https://github.com/noir-lang/noir/pull/4854 but without dependabot.
> chore: bump `rustls` to v0.21.11

- noir_stdlib/src/bigint.nr
- test_programs/execution_success/bigint/src/main.nr
Resolves #4882 
There were typos in bigint templates and also in curve modulus definitions
I don't understand how there could be so many typos, I thought I was being cautious... I triple checked all the parameters this time!
Check one:
> fix: fix curve parameters for bigints

- acvm-repo/acvm/src/pwg/brillig.rs
- acvm-repo/acvm/src/pwg/mod.rs
- tooling/debugger/src/context.rs
- tooling/debugger/src/repl.rs
Resolves #4823 
With the introduction of the `BrilligCall` opcode to deduplicate the Brillig bytecode instead of inlining it into `Brillig` opcodes, the debugger was not being able to correctly step into the execution of unconstrained functions.
This PR adds support to the Noir debugger to handle the new `BrilligCall` opcodes and allows stepping into unconstrained functions by retrieving the opcodes from the deduplicated Brillig functions. The changes impact both the REPL and the DAP debuggers.
In DAP mode, the disassembly request is still not working properly. It seems that we are not responding to the command in an appropriate manner. We will tackle that problem separately.
Check one:
> feat: Handle `BrilligCall` opcodes in the debugger

- compiler/noirc_evaluator/src/ssa.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/generated_acir.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
- compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs
Resolves 
This PR deletes a bunch of dead code from `noirc_evaluator`
Check one:
> chore: delete dead code

- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
> chore: Remove unnecessary `pub(super)` in interpreter

- compiler/noirc_frontend/src/hir/resolution/errors.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
Resolves 
Fixes a typo in an error variant.
Check one:
> chore: fix typo in `ResolverError::AbiAttributeOutsideContract`

- test_programs/noir_test_success/ignored_oracle/Nargo.toml
- test_programs/noir_test_success/ignored_oracle/src/main.nr
- tooling/nargo/src/ops/foreign_calls.rs
Resolves 
I've modified the `DefaultForeignCallExecutor` so that rather than panicking on an unrecognised foreign call we return an empty response.
This solves an issue experienced by @spalladino where `nargo test` was failing due to the use of a custom debugging oracle which doesn't return any values to the circuit. The only situation where these oracle calls not being handled would change the outcome of the test would be if they modify state in an external resolver such as to modify the response of a different oracle call (and so we'd still fail on those anyway).
I've cleared up some empty `Prover.toml` files as well.
Check one:
> feat: handle empty response foreign calls without an external resolver

- compiler/noirc_frontend/src/hir/type_check/stmt.rs
- test_programs/execution_success/slice_init_with_complex_type/Nargo.toml
- test_programs/execution_success/slice_init_with_complex_type/src/main.nr
- tooling/debugger/ignored-tests.txt
Resolves https://github.com/noir-lang/noir/issues/4742
Check one:
> fix: Use annotated type when checking declaration

- docs/docs/noir/standard_library/traits.md
- noir_stdlib/src/ops.nr
- noir_stdlib/src/scalar_mul.nr
Resolves 
This PR implements the `std::op::Neg` trait so that we can implement `Sub` on `EmbeddedCurvePoint`
Check one:
BEGIN_COMMIT_OVERRIDE
feat: add `std::ops::Neg` trait to stdlib
feat: implement `std::ops::Sub` on `EmbeddedCurvePoint`
END_COMMIT_OVERRIDE
> feat: add `Neg` trait to stdlib

- compiler/noirc_evaluator/src/ssa/ir/instruction/call.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_printable_type/src/lib.rs
- test_programs/execution_success/debug_logs/src/main.nr
- test_programs/execution_success/slice_coercion/src/main.nr
- tooling/nargo/src/artifacts/debug_vars.rs
Resolves #4967
There is a problem in the [array to slice coercion](https://github.com/noir-lang/noir/blob/07930d4373a393146210efae69e6ec40171f047b/compiler/noirc_evaluator/src/ssa/ir/instruction/call.rs#L87) code. When evaluating the coercion, it does not take into account that for SSA, complex types such as tuples and structs are flattened, resulting in an array representation with length of elements times the size of the complex type (as a result of the flattening). This results in the replacement slice having an incorrect size.
Then, because the slice has an inflated size, the code which decodes the elements of the slice for printing or tracking (in the debugger) crashes when it attempts to decode beyond the values that it has available.
There are two additional minor changes …
> fix: Compute the correct slice length when coercing from a literal array of complex types

- .github/workflows/gates_report.yml
> chore: disable `gates_report.yml`

- noir_stdlib/src/ops/arith.nr
- noir_stdlib/src/ops/bit.nr
Followup to #4985 
This PR adds implementations for the `std::ops` traits for the new 16 bit traits.
Check one:
> feat: implement `ops` traits on `u16`/`i16`

- acvm-repo/acir/benches/serialization.rs
- acvm-repo/acvm/src/compiler/optimizers/constant_backpropagation.rs
- acvm-repo/acvm/src/compiler/optimizers/redundant_range.rs
- compiler/noirc_driver/src/lib.rs
- compiler/wasm/src/compile.rs
- compiler/wasm/src/compile_new.rs
- tooling/nargo_cli/src/cli/dap_cmd.rs
Resolves 
The new version of `bb` can use an expression width of 4 so we update to make use of this.
Check one:
> feat: increase default expression width to 4

- docs/docs/noir/standard_library/traits.md
- noir_stdlib/src/ops.nr
- noir_stdlib/src/ops/bit.nr
- noir_stdlib/src/uint128.nr
Resolves 
This PR adds a `Not` trait which is an equivalent of Rust's `std::ops::Not` trait which represents a bitwise NOT.
Check one:
> feat: add `Not` trait to stdlib

- compiler/noirc_evaluator/src/ssa/opt/inlining.rs
- test_programs/execution_success/no_predicates_brillig/src/main.nr
Fixes https://github.com/noir-lang/noir/pull/5012 using the entry point instead of the source function, to consider intermediate functions.
Check one:
> fix: Fix no predicates for brillig with intermediate functions

- acvm-repo/bn254_blackbox_solver/benches/criterion.rs
Resolves 
This PR adds benchmarks for pedersen commitments/hashes as well as schnorr signature verification.
```
pedersen_commitment     time:   [542.17 µs 543.27 µs 544.40 µs]
pedersen_hash           time:   [850.69 µs 852.11 µs 853.68 µs]
schnorr_verify          time:   [1.5978 ms 1.5997 ms 1.6018 ms]
```
Check one:
> chore: add benchmarks for pedersen and schnorr verification

- docs/versioned_docs/version-v0.29.0/how_to/how-to-solidity-verifier.md
Since its latest v24 upgrade, zkSync supports ecMul, ecAdd, and ecPairing. 
The verifier compiles and deploys on zkSync Sepolia Testnet
Resolves 
Check one:
> chore: update docs to represent zksync supporting necessary precompiles

- .github/workflows/test-js-packages.yml
- cspell.json
- docs/docs/getting_started/barretenberg/index.md
- scripts/install_bb.sh
Resolves 
`bbup` is now in master so we can use it to install `bb`
Check one:
> chore: use `bbup` to install `bb`

- acvm-repo/acir/src/circuit/opcodes.rs
- acvm-repo/acvm/src/compiler/optimizers/unused_memory.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
Related to #4974
This PR mark return data array with return_data block type, and disable the unused arrays optimisation for databus.
This is required because the return_data is not returned from main although similar constraints will be generated on the backend side.
This should be the last piece for this databus iteration from issue #4974, and it will allow to generate an end-to-end test with the databus to check if we get what is expected.
Check one:
> feat: Activate return_data in ACIR opcodes

- test_programs/rebuild.sh
- tooling/nargo_cli/src/cli/info_cmd.rs
Closes #5035
Alternative to #5035 which just deletes any test programs which don't have a Nargo.toml file.
Check one:
> chore: automatically clear any unwanted directories in `test_programs`

- compiler/noirc_frontend/src/hir/type_check/expr.rs
- compiler/noirc_frontend/src/tests.rs
- noir_stdlib/src/eddsa.nr
- test_programs/execution_success/turbofish_call_func_diff_types/src/main.nr
- tooling/nargo_cli/src/cli/info_cmd.rs
Resolves #5063 
After the turbofish PRs we want the ability to instantiate a variable from a generic trait. This was possible but it required a redundant type annotiation like such (assume `H` has been specified with a `where` clause):
```rust
let hasher: H = H::default()
```
Similarly to trait generics, we now add type bindings from a trait constraint if the trait impl is assumed to exist. 
We now can just do:
```rust
let hasher = H::default()
```
Check one:
- [] **[For Experimental Features]** Documentation to be submitted in a separate PR.
> fix: Apply self type from generic trait constraint before instantiating identifiers

- compiler/noirc_frontend/src/elaborator/expressions.rs
- compiler/noirc_frontend/src/elaborator/patterns.rs
- compiler/noirc_frontend/src/hir/type_check/expr.rs
Resolves 
Moving https://github.com/noir-lang/noir/pull/3542, https://github.com/noir-lang/noir/pull/5041, and https://github.com/noir-lang/noir/pull/5087 to the elaborator 
Check one:
> chore: Move turbofish changes to the elaborator

- acvm-repo/acvm/src/compiler/transformers/csat.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
Related to  #4629
Do not create a witness when multiplying a witness (or an affine transformation of a witness) with an expression of degree 1.
This PR does NOT fix the issue #4629, but it should help reducing the overall gates number.
The arithmetic expressions resulting from the multiplication should not explode in width since I only consider multiplication with a witness (or 'affine witness').
Check one:
> chore: Avoid creating witness for simple multiplications

- docs/docs/how_to/how-to-solidity-verifier.md
Links to evmdiff.com to show which EVM chains have the required precompiles
related to #4964 
Check one:
> chore(docs): Link to evmdiff for supported EVM chains

- compiler/noirc_frontend/src/elaborator/mod.rs
Follow-up to https://github.com/noir-lang/noir/pull/5094
This was missed when moving over changes due to the turbofish operator over to the elaborato.r
Check one:
> fix: Auto dereference trait methods in the elaborator

- Cargo.lock
- tooling/debugger/src/context.rs
- tooling/debugger/src/dap.rs
- tooling/nargo/Cargo.toml
- tooling/nargo/src/artifacts/debug.rs
- tooling/nargo_cli/src/cli/debug_cmd.rs
- tooling/nargo_cli/src/cli/execute_cmd.rs
Resolves 
I'm not sure why the SSA warnings were ever added onto the `DebugArtifact` but we don't use it at all so we can just remove them (which avoids a dependency on `noirc_evaluator`)
Check one:
> chore: remove warnings field from `DebugArtifact`

- compiler/noirc_frontend/src/elaborator/expressions.rs
- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/scope.rs
- compiler/noirc_frontend/src/elaborator/traits.rs
- compiler/noirc_frontend/src/elaborator/types.rs
Removes the `#![allow_unused]` now that the elaborator is reachable in the code base. Also removes some unused import and code found by new warnings afterward.
Check one:
> chore(elaborator): Remove unused imports & code

- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
Resolves 
This PR inlines `flatten_value_list` into `define_result_var` and deduplicates any `InternalWarning::ReturnConstant` warnings
Check one:
> chore: deduplicate `ReturnConstant` warning

- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/traits.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/hir/type_check/mod.rs
- compiler/noirc_frontend/src/hir_def/function.rs
Resolves some errors in the elaborator from checking a trait method's empty body against the expected type that was declared.
Adds whether or not a function is a trait method (not a trait impl method) to the `is_stub` method which is just a renamed `can_ignore_return_type`.
Down to 203 errors in the stdlib.
This also fixes unused variable warnings that were present before but not shown in the error count.
Check one:
> fix(experimental elaborator): Don't check return type for trait methods

- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/traits.rs
Fixes the "Duplicate definitions of <global> found" error by removing `resolve_local_globals`.
We don't need to re-add globals to scope anymore via `resolve_local_globals` since we're not creating a new Elaborator for each function like we do for NameResolvers. The flip side of this is that I think we'll need to change how globals are stored eventually so that they're not all always visible. I think how it is now may violate imports but I'll leave that for a later fix to keep these PRs small. (and wait until I have a test case that shows it).
Down to 61 errors after this PR. The errors are:
- "Duplicate definitions of \<generic> found" - looks to be only one case where there is a generic directly on a trait method. `fn hash<H>(self, state: &mut H) where H: Hasher;`
- "Expression type is …
> fix(experimental elaborator): Avoid defining globals twice

- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/patterns.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/hir/type_check/mod.rs
- compiler/noirc_frontend/src/hir_def/function.rs
Resolves a panic in the elaborator during monomorphization related to parameters being resolved twice and having a different DefinitionId the second time.
I've stored the original ids from the first resolution and switched to using only those.
Check one:
> fix(experimental elaborator): Fix panic during monomorphization

- tooling/lsp/src/requests/goto_declaration.rs
- tooling/lsp/src/requests/goto_definition.rs
- tooling/lsp/src/requests/mod.rs
Resolves 
We've got some copy pasted code here so I've added a helper function for converting a "position" to a "location".
Check one:
> chore: remove duplicated code from LSP

- compiler/noirc_frontend/src/elaborator/mod.rs
Adds a missed call to `generics.clear()`
Check one:
> fix(experimental elaborator): Clear generics after elaborating type aliases

- compiler/noirc_frontend/src/elaborator/expressions.rs
- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/statements.rs
- tooling/nargo_cli/tests/stdlib-tests.rs
Resolves an issue where globals would not have their type set correctly in the elaborator. This is because `elaborate_let` was called which creates a fresh DefinitionId rather than the one already defined by the global, and pushes the type to that fresh id.
Adds a `elaborate_global_let` function which copies over the new type to the original DefinitionId defined by the global.
This PR also adds a call to `self.type_variables.clear()` after a global is resolved so that its type is not defaulted too early.
Check one:
> fix(experimental elaborator): Fix global values used in the elaborator

- .github/workflows/test-rust-workspace-msrv.yml
Resolves 
We're currently getting a large number of false positive alerts such as https://github.com/noir-lang/noir/issues/5137 due to the workflow being cancelled when multiple PRs are merged in quick succession.
This PR changes the workflow to treat cancellation as a success rather than a failure to avoid this.
Check one:
> chore(ci): don't raise MSRV issue if workflow cancelled

- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
- test_programs/execution_success/signed_div/src/main.nr
Resolves #5129
A negative and null quotient was computed as -0=2^{bit_size}, which wraps over the bit size.
Check one:
> fix: wrapping in signed division

- compiler/noirc_frontend/src/elaborator/mod.rs
Resolves errors when using `impl Trait` in the elaborator
Desugaring impl args was happening when elaborating the function when it should have been when defining the FuncMeta beforehand. Additionally, I've taken advantage of the fact that the elaborator also combines the type checking step and have shortened the `desugar_impl_args` function significantly by converting to resolved types instead and pushing to the function's resolved traits. This way there's no danger of users accidentally using the name generated for the implicit generic since it was never introduced into scope.
After this PR only the following two test_programs are still failing:
tests::execution_success_global_consts
tests::execution_success_hashmap
I've yet to test to see if any of the frontend tests fail for the …
> fix(experimental elaborator): Fix `impl Trait` when `--use-elaborator` is selected

- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
Resolves 
This PR sets `noirc_frontend` to default to bn254 if no feature flag is set.
Check one:
> chore: default to using bn254 in `noirc_frontend`

- compiler/noirc_frontend/src/elaborator/patterns.rs
- compiler/noirc_frontend/src/elaborator/statements.rs
Resolves two issues:
1. A type error on some tuple patterns because a `follow_bindings` call was missing
2. When elaborating global lets we were setting the existing definition id to a DefinitionKind::Global, but it already was one. The fresh ID created by the let should have been marked global instead.
After this PR and https://github.com/noir-lang/noir/pull/5138 all test_programs are expected to work in the elaborator.
Check one:
> fix(experimental elaborator): Fix definition kind of globals and tuple patterns with `--use-elaborator` flag

- compiler/noirc_frontend/src/ast/mod.rs
- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/types.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/parser/parser.rs
This argument was previously used to add a fresh generic to a function's signature when we found a slice type back when those used a generic for the length. Since Slice types are now their own type this code path isn't accessible anymore (*).
(\*) The codepath is technically accessible by trying to use a string slice type but we don't support these yet anyway so I've removed them.
Check one:
> chore: Remove unused `new_variables` argument from `resolve_type_inner`

- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/hir/type_check/mod.rs
- compiler/noirc_frontend/src/node_interner.rs
- compiler/noirc_frontend/src/tests.rs
Resolves https://github.com/noir-lang/noir/issues/5146
Fixes all failing frontend tests with the elaborator
This PR includes a few fixes:
- Use `check_trait_impl_method_matches_declaration` to issue errors when a trait impl method is declared with an incorrect signature.
- `define_function_meta` for default trait functions on impls when they're copied over. Also make sure to set `self.current_trait_impl` and `self.self_type` for them as well.
- Use `try_get_trait_implementation` when getting a trait impl may fail (which may happen if there was a previous error resolving the trait for that impl). This was triggering on the test where we tried to declare a trait impl implementing a struct  rather than a trait.
- `check_trait_wrong_parameter_type` has a duplicate error on master but not in …
> fix(experimental elaborator): Fix frontend tests when `--use-elaborator` flag is specified

- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/generated_acir.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
Resolves #5104 
This PR preallocates some witnesses to hold the return values at the beginning of ACIR gen and then adds assertions to fill these witnesses with the return values. This ensures that the return values will be placed in the witness map directly after any function inputs (reasons for this being desirable are laid out in #5104)
Check one:
> feat: place return value witnesses directly after function arguments

- compiler/noirc_frontend/src/elaborator/types.rs
- compiler/noirc_frontend/src/hir/comptime/errors.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/hir/comptime/value.rs
- compiler/noirc_frontend/src/hir/resolution/errors.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/hir/type_check/errors.rs
- test_programs/execution_success/cast_and_shift_global/Nargo.toml
- test_programs/execution_success/cast_and_shift_global/src/main.nr
Resolves https://github.com/noir-lang/noir/issues/5160
Adds a case for casts in comptime globals
Check one:
> feat: support casting in globals

- compiler/noirc_frontend/src/elaborator/lints.rs
A check from https://github.com/noir-lang/noir/pull/5165 was inverted leading to CI issues in https://github.com/noir-lang/noir/pull/5172
Fixed an accidentally inverted check for checking if a function is unconstrained
Check one:
> fix(elaborator): Invert unconstrained check

- compiler/noirc_frontend/src/node_interner.rs
> fix: Fix panic in `get_global_let_statement`

- acvm-repo/brillig_vm/src/lib.rs
Resolves 
This PR breaks out helper functions for writing values into memory to aid reviewing #4053 
Check one:
> chore: break out helper methods for writing foreign call results

- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/patterns.rs
- compiler/noirc_frontend/src/elaborator/types.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/node_interner.rs
Resolves some issues with resolving globals in a type position in certain Noir repositories.
These were an issue before because `non_literal_globals` were resolved after `func_metas` were defined, but `func_metas` may refer to them in their type signature.
Keeps a list of any unresolved globals and resolve them on demand if needed.
Check one:
> fix(elaborator): Lazily elaborate globals

- noir_stdlib/src/hash.nr
- test_programs/execution_success/pedersen_commitment/Prover.toml
- test_programs/execution_success/pedersen_commitment/src/main.nr
- test_programs/execution_success/schnorr/src/main.nr
- test_programs/noir_test_success/should_fail_with_matches/src/main.nr
Related to #4931 
Replace PedersenPoint in the std lib with EmbeddedPoint
Check one:
- [X ] No documentation needed.
> feat: standardize pedersen functions to return `EmbeddedCurvePoint`

- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
- compiler/noirc_frontend/src/elaborator/lints.rs
- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/types.rs
- compiler/noirc_frontend/src/hir/resolution/errors.rs
- compiler/noirc_frontend/src/node_interner.rs
- test_programs/execution_success/schnorr/src/main.nr
Resolves 
This PR adds a new lint inspired by the review of https://github.com/AztecProtocol/aztec-packages/pull/6751 which enforces that oracle functions must be marked as unconstrained.
I've also moved the error for calling an oracle function from a constrained function into the frontend rather than waiting until ACIR gen.
Check one:
> chore: add more lints related to oracle calls

- docs/docs/index.mdx
Description of Noir on the page is outdated and not fully accurate:
- Implies support for SNARK proving systems only
- Defines ZKP as Zero-Knowledge _Programs_
This PR updates the descriptions accordingly.
Check one:
> chore(docs): Update docs homepage

- docs/docs/tooling/debugger.md
- docs/versioned_docs/version-v0.28.0/tooling/debugger.md
- docs/versioned_docs/version-v0.29.0/tooling/debugger.md
- docs/versioned_docs/version-v0.30.0/tooling/debugger.md
Dependency versions of Noir / Nargo / vscode-noir for using the Noir Debugger are currently listed as "0.xx" in the docs.
This PR updates to docs to specify the actual versions required:
- Noir & Nargo ≥0.28.0
- Noir's VS Code extension ≥0.0.11
Check one:
> chore(docs): Supplement Noir Debugger's dependency versions

- compiler/noirc_frontend/src/ast/expression.rs
- compiler/noirc_frontend/src/elaborator/expressions.rs
- compiler/noirc_frontend/src/hir/comptime/errors.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/hir/comptime/value.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/lexer/token.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
- compiler/noirc_frontend/src/parser/parser.rs
- test_programs/execution_success/comptime_println/Nargo.toml
- test_programs/execution_success/comptime_println/src/main.nr
- tooling/nargo_fmt/src/rewrite/expr.rs
> feat: Implement println in the comptime interpreter

- docs/docusaurus.config.ts
This PR solves a broken link in the project documentation that incorrectly points users to an obsolete GitHub repository URL.
This change corrects the 'Docs GitHub' hyperlink in the footer of the documentation to direct users to the new correct repository path. Before, the link directed users to [https://github.com/noir-lang/docs](https://github.com/noir-lang/docs), which has been archived. The updated link now correctly points to [https://github.com/noir-lang/noir/tree/master/docs](https://github.com/noir-lang/noir/tree/master/docs).
Check one:
> chore(docs): fix incorrect docs github link in footer

- acvm-repo/acir_field/src/field_element.rs
- acvm-repo/acir_field/src/generic_ark.rs
- acvm-repo/acvm/src/pwg/blackbox/logic.rs
- acvm-repo/acvm_js/src/black_box_solvers.rs
- acvm-repo/blackbox_solver/src/lib.rs
- acvm-repo/blackbox_solver/src/logic.rs
Related to #5055 
We don't need the field element to know about AND and XOR as we just need to be able to convert into byte arrays and back. I've then moved this into the blackbox solver crate (the only place we were actually using this) to simplify the `AcirField` trait.
Check one:
> chore: move implementation of bitwise operations into `blackbox_solver`

- acvm-repo/acir_field/src/field_element.rs
Resolves https://github.com/noir-lang/noir/issues/5174
This PR inlines `FieldElement.is_negative` into `FieldElement.to_i128` so it can't be misused elsewhere while documenting the reasoning behind it.
Check one:
> chore: inline `FieldElement.is_negative` and document

- Cargo.lock
- Cargo.toml
- acvm-repo/acir_field/Cargo.toml
- acvm-repo/acir_field/proptest-regressions/field_element.txt
- acvm-repo/acir_field/src/field_element.rs
- acvm-repo/acvm/Cargo.toml
- acvm-repo/blackbox_solver/Cargo.toml
- acvm-repo/blackbox_solver/src/logic.rs
- cspell.json
Related to #5173 
This PR adds some usage of the `proptest` crate into ACVM crates to replace some smoke-tests which use hardcoded values.
Check one:
> chore: add some property tests to ACVM crates

- Cargo.lock
- Cargo.toml
- acvm-repo/acir_field/Cargo.toml
- acvm-repo/bn254_blackbox_solver/Cargo.toml
- acvm-repo/bn254_blackbox_solver/src/embedded_curve_ops.rs
- acvm-repo/bn254_blackbox_solver/src/lib.rs
- acvm-repo/bn254_blackbox_solver/src/pedersen/commitment.rs
- acvm-repo/bn254_blackbox_solver/src/pedersen/hash.rs
- acvm-repo/bn254_blackbox_solver/src/poseidon2.rs
- acvm-repo/bn254_blackbox_solver/src/schnorr/mod.rs
Resolves 
Depending on `bn254_blackbox_solver` results in the `bn254` feature flag being applied to the `acir` crate. This is unnecessary as we can just have this crate use a `GenericFieldElement` and construct it as a BN254 field.
This simplifies the lives of people attempting to use Noir with an alternative field choice.
Check one:
> chore: avoid `bn254_blackbox_solver` polluting feature flags

- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/node_interner.rs
- test_programs/compile_success_empty/no_duplicate_methods/Nargo.toml
- test_programs/compile_success_empty/no_duplicate_methods/src/main.nr
Resolves "duplicate method" error when declaring trait methods on different traits with the same method name in the elaborator.
This was the last error type in aztec packages for the elaborator. ~~After this, there are still some extra unused variable warnings I will fix but the entire crate tests successfully.~~ Nevermind, looks like aztec-nr just naturally has many unused variables
Check one:
> fix(elaborator): Fix duplicate methods error

- compiler/noirc_frontend/src/elaborator/mod.rs
Resolves https://github.com/noir-lang/noir/issues/5194
Fixes a performance issue where the elaborator was ~2x as slow running `nargo t --use-elaborator` on aztec-nr versus the same tests without the elaborator  (4s versus 2s).
Found via flamegraph - `self.type_variables` wasn't cleared after each function was elaborated. This Vec is meant to just store type variables local to a function so that we can check if any need type hints after it is done but since it wasn't cleared out, we'd be checking an increasingly large Vec for each function.
With this change the elaborator is slightly faster (but not noticeably) than our current code. 1.9 versus 2.0s average across 10 runs for `nargo t` (with lower std. deviation than our current code as well).
Check one:
> chore: Optimize the elaborator

- aztec_macros/src/utils/ast_utils.rs
- compiler/noirc_frontend/src/ast/expression.rs
- compiler/noirc_frontend/src/ast/mod.rs
- compiler/noirc_frontend/src/ast/statement.rs
- compiler/noirc_frontend/src/debug/mod.rs
- compiler/noirc_frontend/src/elaborator/expressions.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/lexer/lexer.rs
- compiler/noirc_frontend/src/lexer/token.rs
- compiler/noirc_frontend/src/parser/parser.rs
- compiler/noirc_frontend/src/parser/parser/types.rs
- tooling/nargo_fmt/src/rewrite/expr.rs
- tooling/nargo_fmt/tests/expected/let.nr
- tooling/nargo_fmt/tests/input/let.nr
To try to make it easier to review I'm breaking the parser related changes here out #5203.
It turns out `parser/types.rs` was never in our module tree. I've added it and removed the duplicate parsers for parsing types that were in `parser/parser.rs`. They've had some changes since the copies in `parser/types.rs` were first changed so I've updated those as well.
Check one:
> chore: Parse macros

- scripts/redo-typo-pr.sh
Resolves 
This PR pulls across the typo PR script from aztec-packages so we can use it here as well.
Check one:
> chore: copy across typo PR script from aztec-packages

- compiler/noirc_evaluator/src/ssa.rs
- compiler/noirc_evaluator/src/ssa/opt/flatten_cfg/value_merger.rs
- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/lexer/token.rs
- docs/versioned_docs/version-v0.28.0/tutorials/noirjs_app.md
- docs/versioned_docs/version-v0.29.0/tutorials/noirjs_app.md
Thanks dropbigfish for https://github.com/noir-lang/noir/pull/5232. Our policy is to redo typo changes to dissuade metric farming. This is an automated script.
> chore: redo typo PR by dropbigfish

- compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs
- test_programs/execution_success/regression_5202/Nargo.toml
- test_programs/execution_success/regression_5202/fraction/LICENSE
- test_programs/execution_success/regression_5202/fraction/Nargo.toml
- test_programs/execution_success/regression_5202/fraction/README.md
- test_programs/execution_success/regression_5202/fraction/src/lib.nr
- test_programs/execution_success/regression_5202/src/main.nr
Resolves #5202 
The linked issue was coming from our if condition optimization where we assume the value of an if's condition to be true within the then branch and false within the else branch. It seems the `map_value` calls from this weren't being reset properly since the nested `if f1.sign { .. } { .. }`'s else branch assumed `f1.sign` to be false, which was not reset properly after the `if`.  I've temporarily disabled the optimization until we can add it back without breaking this test.
Check one:
> fix: Disable `if` optimization

- docs/docs/noir/standard_library/containers/boundedvec.md
- docs/docs/noir/standard_library/containers/vec.mdx
- noir_stdlib/src/collections/bounded_vec.nr
- noir_stdlib/src/collections/vec.nr
- test_programs/noir_test_success/bounded_vec/src/main.nr
- tooling/nargo_cli/tests/stdlib-tests.rs
Resolves 
This PR exposes `set` and `set_unchecked` methods to `BoundedVec` which allow writing to individual indices in the array without having to access `self.storage` directly.
I've also documented the expected behaviour for the get and set operations.
Check one:
> feat: add `set` and `set_unchecked` methods to `Vec` and `BoundedVec`

- noir_stdlib/src/hash/poseidon2.nr
Resolves #4688 
Adding the no_predicates attribute to poseidon2 because hashing operations have no side-effect.
Check one:
> chore: add no predicate to poseidon2

- docs/docs/noir/standard_library/containers/boundedvec.md
- noir_stdlib/src/collections/bounded_vec.nr
This adds a `map` function to `BoundedMap`, which I've found to be a relatively common need, and quite annoying to implement outside of the stdlib as it requires raw access to the internals of the data structure.
Check one:
> feat: add BoundedVec::map

- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- test_programs/compile_success_empty/comptime_array_len/Nargo.toml
- test_programs/compile_success_empty/comptime_array_len/src/main.nr
- test_programs/execution_success/array_len/src/main.nr
Resolves 
This PR implements support for the `array_len` builtin so we can query the length of arrays in `comptime` blocks. Ideally we'd tie this closer to the `Intrinsics` struct in `noirc_evaluator` but we can handle this morn cleanly later.
Check one:
> feat: implement comptime support for `array_len` builtin

- compiler/noirc_driver/src/abi_gen.rs
Resolves slack issue https://aztecprotocol.slack.com/archives/C02M7VC7TN0/p1718697469796579?thread_ts=1718697265.759469&cid=C02M7VC7TN0
Looks like when this was added the author used the display method rather than one for serialization.
Check one:
> fix: use proper serialization in `AbiValue`

- acvm-repo/acvm/src/compiler/transformers/csat.rs
Resolves 
This PR addresses an issue where we were unnecessarily splitting an expression based on an example which Zac found while working on `noir-edwards`. We were being overly restrictive and only accepting the case where both witnesses in the multiplication are shared with other terms
Check one:
> fix: avoid unnecessarily splitting expressions with multiplication terms with a shared term

- compiler/noirc_frontend/src/elaborator/patterns.rs
Resolves https://github.com/noir-lang/noir/issues/5271
Lazily elaborating functions wasn't correct since the FuncMeta object never stored the LocalModuleId carried by the set of unresolved functions. This lead to lazily elaborated functions be elaborated in a different module than intended.
Lazily elaborated functions seem to no longer be necessary to run our tests, nor to run the tests in aztec-nr so I've just removed them rather than adding the additional fields to FuncMeta. 
Check one:
> fix: Don't lazily elaborate functions

- compiler/noirc_frontend/src/monomorphization/mod.rs
- test_programs/execution_success/modulus/src/main.nr
Resolves 
We're currently returning an array literal for these methods in the stdlib whereas the Noir code states that it should return a slice. This results in issues when passing these "slices" into other functions such that it causes the inlining pass to panic.
I've fixed this by replacing the array literal with a slice literal.
Check one:
> fix: fix incorrect return type being applied to stdlib functions `modulus_be_bytes()`, `modulus_be_bits()`, etc.

- compiler/noirc_frontend/src/elaborator/mod.rs
- test_programs/compile_success_contract/recursive_method/Nargo.toml
- test_programs/compile_success_contract/recursive_method/src/main.nr
…
Resolves #5288 
This PR fixes #5288 by updating `self.in_contract` before we define function metadata to match `self.local_module`. This is mildly hacky and we may want to have a nicer "switch modules and update everything which depends on it" helper function in future.
Check one:
> fix: update `in_contract` flag before handling function metadata in elaborator

- tooling/nargo_fmt/src/visitor/item.rs
- tooling/nargo_fmt/tests/expected/fn.nr
- tooling/nargo_fmt/tests/input/fn.nr
Resolves #5300 
Previously the formatter was inserting an extra `<` when formatting functions with a space before `<` when specifying generics. We currently mark the starting span for a list of generics as the end of the function name. Having this be the starting span would cause the first generic of the sequence to have `<` marked as a leading string when it should not have been. We now start the span for a function's generics by looking for `<` rather than starting the span at the end of the function name. 
Check one:
> fix(nargo_fmt): Account for spaces before the generic list of a function

- compiler/noirc_frontend/src/monomorphization/errors.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
Replaces an `unwrap` and panic in the monomorphizer with an ICE issued to the user instead. This isn't expected to be issued normally, but is being issued currently when a `comptime let` variable is used in runtime code since `comptime let` is still unimplemented in the evaluator.
This does not fix the underlying `comptime let` error, only the resulting panic.
Check one:
> fix: Replace panic in monomorphization with an error

- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- test_programs/compile_success_empty/derive_impl/Nargo.toml
- test_programs/compile_success_empty/derive_impl/src/main.nr
Implements `slice_push_back` in the comptime interpreter. This was needed in the vertical slice example to build a slice of quoted fields for the type in the impl.
With this a slightly modified version of the vertical slice code now runs. Notably:
- Generic functions do not work, so a `map` function like in the original cannot be used
- An annotation function can return a quoted impl, but the impl isn't actually inserted into the program yet. So the derived impl does nothing currently.
Check one:
> feat: Implement `slice_push_back` in the comptime interpreter

- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- test_programs/compile_success_empty/derive_impl/Nargo.toml
- test_programs/compile_success_empty/derive_impl/src/main.nr
Resolves 
Fixes an issue in the interpreter where the interpreter would error for member access expressions on tuples. This prevented e.g. `my_tuple.0`.
Check one:
> fix: Implement interpretation of member access on tuples

- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir/comptime/value.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- noir_stdlib/src/lib.nr
- noir_stdlib/src/meta.nr
- noir_stdlib/src/meta/type_def.nr
- test_programs/compile_success_empty/comptime_type_definition/Nargo.toml
- test_programs/compile_success_empty/comptime_type_definition/src/main.nr
- test_programs/compile_success_empty/derive_impl/Nargo.toml
- test_programs/compile_success_empty/derive_impl/src/main.nr
Resolves #5285 
Implements `as_type`, `generics`, and `fields` on the `TypeDefinition` type.
The `Type` type isn't really supported yet so `as_type` and `fields` return `Quoted` token streams instead of `Type`s for now.
A few bugs still need to be fixed after this PR for the vertical slice to work.
Check one:
> feat: Add some metaprogramming methods on `TypeDefinition`

- compiler/noirc_driver/src/lib.rs
- compiler/noirc_evaluator/src/ssa.rs
Better reviewed with "Diff -> Hide whitespace".
Resolves #4667
Introduces an `SsaEvaluatorOptions` struct that bundles a bunch of booleans that are passed down several functions.
None
Check one:
> chore: Bundle SSA Evaluator Options

- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/generated_acir.rs
Pulls across fix made in sync PR at https://github.com/AztecProtocol/aztec-packages/pull/7134/commits/e39be3dc0ee89d9a246366a1f88eb36b26f25751
For some reason in the `noir-contracts` workspace, we're emitting a _lot_  (100+ MB worth) of brillig call opcodes which have their predicate hardcoded to zero (i.e. they will never actually be executed).
This PR adds a check before we emit a brillig call opcode to see if the predicate is zero and, if so,  we skip it and zero out all the outputs at compile time.
Check one:
> fix: skip emission of brillig calls which will never be executed

- acvm-repo/acir/src/circuit/black_box_functions.rs
- acvm-repo/acir/src/circuit/opcodes/black_box_function_call.rs
- acvm-repo/acvm/src/pwg/blackbox/mod.rs
- acvm-repo/acvm/src/pwg/blackbox/pedersen.rs
- acvm-repo/blackbox_solver/src/curve_specific_solver.rs
- acvm-repo/bn254_blackbox_solver/src/lib.rs
- acvm-repo/brillig/src/black_box.rs
- acvm-repo/brillig_vm/src/black_box.rs
- compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_black_box.rs
- compiler/noirc_evaluator/src/brillig/brillig_ir.rs
- compiler/noirc_evaluator/src/brillig/brillig_ir/debug_show.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/generated_acir.rs
- compiler/noirc_evaluator/src/ssa/ir/instruction/call.rs
- noir_stdlib/src/hash.nr
- tooling/lsp/src/solver.rs
- tooling/nargo_cli/tests/stdlib-tests.rs
This PR adds (back) the blackbox functions for Pedersen hash/commitment, until we get a similar circuit (in term of number of gates) with the Noir implementation.
The Noir version is kept and assert to ouput the same value in a test.
This PR reverts the PR #5221
Check one:
> chore: add back Pedersen blackbox functions (revert PR 5221)

- scripts/install_bb.sh
- tooling/noir_js_backend_barretenberg/package.json
- tooling/noir_js_backend_barretenberg/src/backend.ts
- yarn.lock
Resolves 
This PR bumps the bb version to avoid stuff breaking on syncs
Check one:
> chore: bump `bb` to 0.43.0

- docs/docs/tooling/testing.md
- test_programs/noir_test_failure/should_fail_mismatch/src/main.nr
- test_programs/noir_test_success/should_fail_with_matches/src/main.nr
- tooling/nargo/src/ops/test.rs
Resolves #4786
`#[test(should_fail_with = "message")]` will now check that "message" is a substring of the failure reason. I _think_ this is a backwards-compatible change.
I thought about supporting regular expressions, as suggested in the related issue, but I didn't know how to signal that it's a regex or just "contains". I guess that could be done with another name, something like `should_with_with_regexp` 🤔 (in a separate PR, if really needed/wanted)
None
Check one:
> feat: let `should_fail_with` check that the failure reason contains the expected message

- compiler/noirc_frontend/src/elaborator/mod.rs
- test_programs/compile_success_contract/abi_attribute/Nargo.toml
- test_programs/compile_success_contract/abi_attribute/src/main.nr
Resolves 
Followup to #5292 to handle globals as well
Check one:
> fix: fix usage of `#[abi(tag)]` attribute with elaborator

- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/types.rs
Resolves https://github.com/noir-lang/noir/pull/5298#discussion_r1648054135
This PR replaces the `in_contract` field with a `in_contract` function. This does expand the `self_type.is_some()` override to a couple of locations however which I need to check whether it's going to cause issues.
Check one:
> chore: replace cached `in_contract` with `in_contract()` method

- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
This PR replaces a panic with a nicer error plus a link to the relevant issue: https://github.com/noir-lang/noir/issues/4925
Check one:
> chore: remove panic for unimplemented trait dispatch

- docs/docs/noir/concepts/data_types/arrays.md
- docs/docs/noir/concepts/data_types/slices.mdx
- noir_stdlib/src/slice.nr
- test_programs/execution_success/slices/src/main.nr
Looks like these were removed back when we split arrays from slices since they no longer shared the array implementation. I've added them back.
Currently requires https://github.com/noir-lang/noir/pull/5332 to work due to a panic in the type system found while adding to the slices test.
Check one:
> feat: Add `map`, `fold`, `reduce`, `any`, and `all` for slices

- compiler/noirc_frontend/src/elaborator/expressions.rs
- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/statements.rs
- compiler/noirc_frontend/src/hir/comptime/errors.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/hir/comptime/tests.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/hir/type_check/mod.rs
- compiler/noirc_frontend/src/hir_def/function.rs
- test_programs/compile_failure/non_comptime_local_fn_call/Nargo.toml
- test_programs/compile_failure/non_comptime_local_fn_call/src/main.nr
- test_programs/noir_test_success/comptime_globals/src/main.nr
Resolves https://github.com/noir-lang/noir/issues/5333
Issues an error when a non-comptime function in the same crate is called from a comptime context:
```
error: `id` cannot be called in a `comptime` context here
┌─ /.../non_comptime_local_fn_call/src/main.nr:3:18
│
3 │         let _a = id(3);
│                  ----- This function must be `comptime` or in a separate crate to be called
│
```
This limitation is because all comptime items are elaborated before non-comptime items within a crate.
Check one:
> fix: Error when a local function is called in a comptime context

- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/statements.rs
Resolves 
In the vein of #5324, we now just look up whether the `current_function` is unconstrained rather than tracking this on the elaborator.
This does come with a little bit of a perf degradation as we need to look up the function on each jump but that should be pretty negligible.
Check one:
> chore: remove `is_unconstrained_fn` field from elaborator

- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/types.rs
Resolves 
Quick PR to make more use of the `push_err` helper when creating errors in the elaborator.
Check one:
> chore: use `push_err` more in elaborator

- compiler/noirc_errors/src/reporter.rs
This will also honor `TERM=dumb` and the `NO_COLOR` env vars.
Resolves #5074
`nargo` errors are written to stderr. These were always using colors. In this PR we check if stderr is a terminal and just then use colors, otherwise we don't. Actually, if is a terminal we don't always output colors: we use `[ColorChoice::Auto](https://docs.rs/termcolor/latest/termcolor/enum.ColorChoice.html#variant.Auto)` which will honor some standard env vars like `TERM=dumb` or `NO_COLOR`.
This change will also improve error messages outputted in `cargo test` inside `nargo_cli` when something is supposed to compile but doesn't.
Note that this does just one alternative proposed in #5074. Another thing is adding a `--color` option. I think that could be done in a separate PR (if really wanted/needed).
None. …
> feat: disable nargo color output if stderr is tty

- compiler/noirc_driver/tests/stdlib_warnings.rs
- noir_stdlib/src/lib.nr
Resolves 
This PR turns back on the test that the stdlib shouldn't produce compiler warnings.
Check one:
> fix: address compiler warnings coming from stdlib

- compiler/noirc_evaluator/src/errors.rs
- compiler/noirc_evaluator/src/ssa/opt/assert_constant.rs
Fix `static_assert` error message
Error message for `static_assert` was ~"Argument to static_assert is false or dynamic" at some point, but currently is copy/pasted from the nested slices error
Check one:
> chore: `static_assert` error message fix and split into is-dynamic and is-false

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
Resolves comment: https://github.com/noir-lang/noir/pull/5341#pullrequestreview-2142302988
Before this PR, we could panic if a builtin within a comptime block fails to type check, and is later executed by the interpreter.
Check one:
> fix: Remove panics in the interpreter when a builtin fails to type check

- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- compiler/noirc_frontend/src/hir_def/traits.rs
Resolves frontend indeterminism
Check one:
> fix: Replace std::HashMap with FxHashMap to fix frontend indeterminism

- compiler/noirc_frontend/src/elaborator/expressions.rs
- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/patterns.rs
- compiler/noirc_frontend/src/elaborator/statements.rs
- compiler/noirc_frontend/src/elaborator/types.rs
- compiler/noirc_frontend/src/hir/comptime/errors.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/hir/type_check/errors.rs
- compiler/noirc_frontend/src/hir/type_check/expr.rs
- compiler/noirc_frontend/src/hir/type_check/mod.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
- compiler/noirc_frontend/src/node_interner.rs
- test_programs/compile_success_empty/comptime_traits/Nargo.toml
- test_programs/compile_success_empty/comptime_traits/src/main.nr
- tooling/nargo_cli/build.rs
Resolves https://github.com/noir-lang/noir/issues/4925
Implements trait dispatch in the interpreter - which includes operator overloading.
I've tried to share as much code as I can between the interpreter and monomorphization.
Most of this PR is rather straightforward adapting code in the monomorphizer to use in the interpreter. The main new bit of code is a stack of `FunctionContext`s in the elaborator. I found at that when having a comptime block in the middle of a function, even a known trait would panic that it had no impl. This was because we previously delayed solving impls to the very end of a function when types were known. I've had to change this into a stack instead so that we can solve impls that were done within a comptime block at the end of that comptime block, just before …
> feat: Implement trait dispatch in the comptime interpreter

- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/locations.rs
- compiler/noirc_frontend/src/node_interner.rs
- compiler/noirc_frontend/src/resolve_locations.rs
- tooling/lsp/src/requests/goto_declaration.rs
- tooling/lsp/src/requests/goto_definition.rs
- tooling/lsp/src/requests/mod.rs
- tooling/lsp/src/requests/rename.rs
- tooling/lsp/src/test_utils.rs
- tooling/lsp/test_programs/go_to_definition/src/main.nr
Resolves #5389
"Go to definition" works by scanning some `id_to_location` hash map where all expressions and statements locations are stored. However, "use" statement locations aren't captured there.
Then, we recently implemented rename functionality which works by building a graph that connects references to referenced nodes. This same graph can be used for "go to definition"! So that's what this PR does. However, it will first check the graph, then try the other approach because I think that other approach works for trait impls and other things which aren't captured in the reference graph. I'm still trying to understand that part and to avoid breaking things I left it as is (there are also no tests for those things so it's hard to know if we break something... but I plan to add more …
> fix: go to definition from `use` statement

- .github/workflows/publish-nargo.yml
Resolves #5283 
This PR adds `aarch64-unknown-linux-gnu` to the list of targets we build for so `noirup` can serve it.
Check one:
> feat: build releases for `aarch64-unknown-linux-gnu` target

- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- tooling/lsp/src/requests/goto_definition.rs
- tooling/lsp/test_programs/go_to_definition/src/main.nr
Resolves https://github.com/noir-lang/noir/pull/5390#issuecomment-2205880047
Go to definition didn't work in this case:
```rust
use some::name as aliased_name;
//        ~~~~ click here
```
https://github.com/noir-lang/noir/assets/209371/e35ca028-69e0-4e74-8fce-9c63a1376232
Also adds a test that clicking "aliased_name" also works the same way.
Check one:
> fix: go to definition from aliased use

- Cargo.lock
- compiler/noirc_evaluator/Cargo.toml
- compiler/noirc_evaluator/src/ssa/ir/instruction/binary.rs
Resolves 
This PR adds some helper functions for converting between `FieldElement` and signed integers.
Check one:
> chore: refactor conversion between `FieldElement` and signed integers

- docs/src/pages/index.jsx
Resolves #4982
These persona boxes were a rudimentary way to get some info about who was coming to the docs. We have proper analytics now, so we can remove them.
Check one:
> chore(docs): Remove persona boxes from the landing page

- docs/docs/noir/standard_library/cryptographic_primitives/ec_primitives.md
- docs/versioned_docs/version-v0.17.0/standard_library/cryptographic_primitives/04_ec_primitives.md
- docs/versioned_docs/version-v0.19.0/standard_library/cryptographic_primitives/04_ec_primitives.md
- docs/versioned_docs/version-v0.19.1/standard_library/cryptographic_primitives/04_ec_primitives.md
- docs/versioned_docs/version-v0.19.2/standard_library/cryptographic_primitives/04_ec_primitives.md
- docs/versioned_docs/version-v0.19.3/standard_library/cryptographic_primitives/04_ec_primitives.md
- docs/versioned_docs/version-v0.19.4/standard_library/cryptographic_primitives/04_ec_primitives.md
- docs/versioned_docs/version-v0.22.0/noir/standard_library/cryptographic_primitives/ec_primitives.md
- docs/versioned_docs/version-v0.23.0/noir/standard_library/cryptographic_primitives/ec_primitives.md
- docs/versioned_docs/version-v0.24.0/noir/standard_library/cryptographic_primitives/ec_primitives.md
- docs/versioned_docs/version-v0.25.0/noir/standard_library/cryptographic_primitives/ec_primitives.md
- docs/versioned_docs/version-v0.26.0/noir/standard_library/cryptographic_primitives/ec_primitives.md
- docs/versioned_docs/version-v0.27.0/noir/standard_library/cryptographic_primitives/ec_primitives.md
- docs/versioned_docs/version-v0.28.0/noir/standard_library/cryptographic_primitives/ec_primitives.md
- docs/versioned_docs/version-v0.29.0/noir/standard_library/cryptographic_primitives/ec_primitives.md
- docs/versioned_docs/version-v0.30.0/noir/standard_library/cryptographic_primitives/ec_primitives.md
Resolves #5392
Updates the links to github to not be broken
Check one:
> fix(docs): Fix broken docs link to gihtub

- compiler/noirc_frontend/src/elaborator/expressions.rs
- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/patterns.rs
- compiler/noirc_frontend/src/elaborator/scope.rs
- compiler/noirc_frontend/src/elaborator/types.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- compiler/noirc_frontend/src/hir/resolution/import.rs
- compiler/noirc_frontend/src/hir/resolution/path_resolver.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/hir/resolution/traits.rs
- compiler/noirc_frontend/src/hir/type_check/mod.rs
- compiler/noirc_frontend/src/locations.rs
- compiler/noirc_frontend/src/node_interner.rs
- tooling/lsp/src/requests/rename.rs
- tooling/lsp/src/test_utils.rs
- tooling/lsp/test_programs/rename_struct/src/main.nr
Resolves #5394
Finds struct locations in return types and inside paths.
Making it work for the return type was simple: the code to register it is now done a bit earlier so it works in all cases where a type is referred as the last segment in a Path.
Making it work when the type is in the middle of a Path (like in `foo::Foo::new`) was a bit trickier: the existing Path lookup only cared about (and registered) the result of the last segment. So now there's code to register each segment in turn... but this is only done if running in LSP mode. So in `foo::Foo::new`, `foo` is linked to a module and `Foo` is linked to a struct. The existing code relied on the `DependencyId` for this, but a "module" dependency didn't exist... to avoid introducing new variants that are only used in this reference …
> fix: lsp find struct reference in return locations and paths

- compiler/noirc_evaluator/src/ssa/opt/inlining.rs
Consider the following code:
```rust
fn inner<N>(input: Field) {
assert_eq(input, 27);
}
#[no_predicates]
fn no_predicates(input: Field) {
inner(input)
}
fn outer_pass_through(input: Field) {
no_predicates(input)
}
fn main(input: Field) {
outer_pass_through(input)
}
```
This is the call stack with `#[no_predicates]`:
```
┌─ /mnt/user-data/alvaro/constructor/src/main.nr:23:5
│
23 │     assert_eq(input, 27);
│     --------------------
│
= Call stack:
1. /mnt/user-data/alvaro/constructor/src/main.nr:32:5
2. /mnt/user-data/alvaro/constructor/src/main.nr:28:5
3. /mnt/user-data/alvaro/constructor/src/main.nr:23:5
```
This is the call stack without  `#[no_predicates]`:
```
error: Failed constraint
┌─ /mnt/user-data/alvaro/constructor/src/main.nr:23:5
│
23 │     assert_eq(input, 27);
│ …
```
> fix: Complete call stacks with no_predicates

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- docs/docs/noir/standard_library/is_unconstrained.md
- test_programs/compile_success_empty/comptime_slice_methods/Nargo.toml
- test_programs/compile_success_empty/comptime_slice_methods/src/main.nr
- tooling/nargo_cli/build.rs
Adds the remaining builtin slice methods to the interpreter.
Also adds `is_unconstrained` which always returns true. This way `comptime` can also take advantage of any `if is_unconstrained()` optimizations (like `break`) used in unconstrained code in called functions.
Check one:
> chore: Add remaining slice methods to the interpreter

- compiler/noirc_evaluator/src/errors.rs
- compiler/noirc_evaluator/src/ssa/ir/types.rs
- compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs
- compiler/noirc_frontend/src/elaborator/lints.rs
- compiler/noirc_frontend/src/elaborator/statements.rs
- compiler/noirc_frontend/src/hir/type_check/errors.rs
- compiler/noirc_frontend/src/hir/type_check/stmt.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_frontend/src/tests.rs
- cspell.json
- test_programs/compile_failure/overflowing_assignment/Nargo.toml
- test_programs/compile_failure/overflowing_assignment/src/main.nr
Resolves #5419
This is similar to #5372, except that here the compiler does an early check with explicitly annotated types, and in the related issue the check is done later on, once unknown types are resolved.
Also in this PR:
- a test was moved from `test_programs` to `noirc_frontend/src/tests.rs` because the error produced here can be caught there
- the error message produced in both places is now exactly the same (showing the possible range of values, which helps to know why you exceeded the min/max)
None
Check one:
> fix: correct range for overlfowing/underflowing integer assignment

- tooling/noir_js_backend_barretenberg/src/backend.ts
- tooling/noir_js_backend_barretenberg/src/verifier.ts
Resolves 
As pointed out by Palla in the bb.js doc, we're exporting two different verifiers here. I'm not sure why this is the case so I've folded `BarretenbergVerifierBackend` into `BarretenbergBackend` so `BarretenbergVerifier` is the only `VerifierBackend` that doesn't also implement `Backend`.
Check one:
> chore: merge `BarretenbergVerifierBackend` and `BarretenbergBackend`

- acvm-repo/acvm/src/pwg/brillig.rs
Resolves 
This PR pulls out a modified version of @anaPerezGhiglia's refactoring to how we extract error payloads from the brillig VM's memory from #5403 to separate it from the creation of the new error variant.
Check one:
> chore: extracts refactoring of reading error payloads from #5403

- compiler/noirc_evaluator/src/ssa/opt/inlining.rs
Resolves 
I found the way we were handling `no_predicates` function a little indirect here so I've changed these booleans to literally be "do we want to inline no_predicates functions" rather than whether we should treat them as entrypoints.
Check one:
> chore: refactor logic around inlining `no_predicates` functions

- .github/workflows/mirror-external_libs.yml
Adds a dummy workflow for the PR #5417
This will allow the workflow to be run, so that it can be run from the #5417 PR once the dummy version is merged and ran once.
Check one:
> chore: dummy workflow

- compiler/noirc_frontend/src/hir/comptime/errors.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
Working towards https://github.com/noir-lang/noir/issues/5428
Changes the panic in https://github.com/noir-lang/noir/issues/5428 to an error instead. The original error message was no longer appropriate either since this was occurring in the interpreter rather than the monomorphizer.
This doesn't fix the issue, I just thought it'd be slightly nicer UX going forward if we didn't panic here.
Check one:
> fix: Change panic to error in interpreter

- compiler/noirc_evaluator/src/ssa/opt/remove_enable_side_effects.rs
Resolves 
We currently pick up quite a lot of duplicated `EnableSideEffects` instructions as we perform optimizations on the SSA which tends to clutter up the output. This PR adds a small change to remember the currently active predicate condition and skips any instructions which will just will just reactivate the current predicate.
I've added a test case which shows the sort of SSA which we want to avoid.
Check one:
> feat: remove redundant `EnableSideEffects` instructions

- compiler/noirc_evaluator/src/ssa/checks/check_for_underconstrained_values.rs
check_for_underconstrained_values pass was producing false positives because the value ids of results in the function were different from the value ids used in other constraints and had to be resolved.
Added checks to ensure we also resolve all values before using
Check one:
> fix: Fix issue with unresolved results

- compiler/noirc_evaluator/src/errors.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
- noir_stdlib/src/collections/bounded_vec.nr
Resolves #5464 
Similarly to how we removed compile-time assertion failures in order to have correct test error messages, we must do the same for invalid indices.
Check one:
> fix: remove compile-time error for invalid indices

- compiler/noirc_evaluator/src/ssa/ir/instruction.rs
- compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs
@TomAFrench's recent SSA changes got me thinking more about the passes and I was looking at how we deduplicated instructions. We never deduplicated instructions which can require a predicate so I've added the ability to do so here.
We only deduplicate these instructions after flattening and to do so we cache the SideEffectsEnabled var in addition to the instruction - and only if the instruction actually relies on the variable.
Check one:
> feat(optimization): Deduplicate more instructions

- noir_stdlib/src/embedded_curve_ops.nr
Resolves #4206 
Add documentation to EmbeddedCurvePoint
Check one:
> chore: document EmbeddedCurvePoint

- scripts/bump-bb.sh
- scripts/install_bb.sh
- test_programs/gates_report.sh
- tooling/noir_js_backend_barretenberg/package.json
- yarn.lock
Resolves 
This PR bumps bb to the latest version before the recent serialization change.
Check one:
> chore: bump bb to 0.45.1

- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- cspell.json
- test_programs/compile_success_empty/attribute_args/Nargo.toml
- test_programs/compile_success_empty/attribute_args/src/main.nr
Resolves https://github.com/noir-lang/noir/issues/5473
Resolves https://github.com/noir-lang/noir/issues/5476
Allows arguments to attribute functions.
- These arguments are all quoted by default. This is to replicate something like Rust's `#[derive(Foo, Bar)]` where  `Foo` and `Bar` are meant to be traits rather than values in scope.
- Varargs is also possible if the attribute accepts a slice of Quoted values rather than individual Quoted arguments.
Check one:
> feat: Allow arguments to attribute functions

- compiler/noirc_frontend/src/parser/parser/types.rs
- noir_stdlib/src/meta/mod.nr
- test_programs/compile_success_empty/unquote/Nargo.toml
- test_programs/compile_success_empty/unquote/src/main.nr
- tooling/nargo_cli/build.rs
Resolves https://github.com/noir-lang/noir/issues/5478
Check one:
> feat: Add unquote function

- scripts/redo-typo-pr.sh
Resolves 
This PR updates the typo PR script to squash the commits as multi-commit PRs weren't being processed properly.
Check one:
> chore: update typo PR script

- compiler/noirc_frontend/src/elaborator/expressions.rs
- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/scope.rs
- compiler/noirc_frontend/src/elaborator/types.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- compiler/noirc_frontend/src/hir/resolution/import.rs
- compiler/noirc_frontend/src/hir/resolution/path_resolver.rs
- compiler/noirc_frontend/src/hir/resolution/resolver.rs
- compiler/noirc_frontend/src/hir/type_check/mod.rs
- compiler/noirc_frontend/src/hir_def/function.rs
- compiler/noirc_frontend/src/locations.rs
- compiler/noirc_frontend/src/node_interner.rs
- tooling/lsp/src/lib.rs
- tooling/lsp/src/requests/goto_declaration.rs
- tooling/lsp/src/requests/goto_definition.rs
- tooling/lsp/src/requests/hover.rs
- tooling/lsp/src/requests/mod.rs
- tooling/lsp/src/requests/references.rs
- tooling/lsp/src/requests/rename.rs
- tooling/lsp/src/types.rs
- tooling/lsp/test_programs/rename_function/src/main.nr
- tooling/lsp/test_programs/workspace/one/src/lib.nr
- tooling/lsp/test_programs/workspace/two/src/lib.nr
- tooling/lsp/test_programs/workspace/two/src/other.nr
Resolves #1575
Implements LSP hover for:
- modules
- structs
- struct members
- traits
- global variables
- functions
- aliases
- local variables
The popup content is similar to that of Rust Analyzer except that there's no link to go to that reference. The reason is that it seems the LSP type to do that has an "actions" property but I can't find that in the lsp-types library we are using. That said, once this PR is merged doing that should be relatively easy, and it might be better to keep PRs smaller.
There's one case where the hover doesn't work: if you have `let x: i32 = Default::default();`, hovering over `default` won't show the impl function. It's doable, but doing it requires more changes in this PR and at one point I wanted to stop :-)
This PR also includes several fixes that I …
> feat: LSP hover

- tooling/lsp/src/requests/code_lens_request.rs
- tooling/nargo_cli/src/cli/mod.rs
Give more visibility to debugger
- Add a new `Debug` codelens action to main functions
- Unhid the `debug` command from nargo_cli
https://github.com/noir-lang/vscode-noir/assets/13237343/6e83d28c-126a-41ff-a23b-bc7ce9a50ccb
This PR has its sibling in vscode-noir repo noir-lang/vscode-noir#85
Check one:
> feat: add debug codelens action

- compiler/integration-tests/package.json
- yarn.lock
Resolves 
This PR bumps the version of hardhat we use for integration tests.
Check one:
> chore: bump hardhat version to `2.22.6`

- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/hir/comptime/tests.rs
- compiler/noirc_frontend/src/hir/comptime/value.rs
- compiler/noirc_frontend/src/parser/parser/structs.rs
Resolves https://github.com/noir-lang/noir/issues/5504
Mutable variables weren't wrapped in a mutable reference before like they are in SSA - they are now.
This is an alternate version from the last PR - I've cherry-picked the last PR so this can be merged into master instead of another branch.
Check one:
> fix: Mutability in the comptime interpreter

- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- compiler/noirc_frontend/src/node_interner.rs
- tooling/lsp/src/requests/hover.rs
- tooling/lsp/src/requests/mod.rs
Resolves #5516
It seems hover broke in 70dabfa454516b839b57554fb2e2574a84748d66 . However, our tests still pass. I still don't understand why it only breaks when the request comes from an actual VS Code instance and not in tests... but for now I'd rather revert the commit that broke it and eventually try to do the refactor again, because having hover is pretty nice :-)
None.
Check one:
> fix: lsp hover wasn't always working

- docs/docs/noir/concepts/data_bus.mdx
- docs/docs/noir/concepts/oracles.mdx
- docs/src/components/Notes/_experimental.mdx
Resolves #4935
This pull request makes the experimental feature warnings the same across different parts of the documentation. I've created one warning message that all pages can show. This helps in keeping the docs consistent and easy to update.
The new disclaimer meets all the requirements set out in issue #4935 by:
- Clearly stating that the feature is experimental;
- Noting that the documentation may be incomplete or out of date, and thus subject to changes that could impact its behavior or functionality;
- Encouraging contributions and providing a direct link to the project's GitHub repository.
Check one:
> chore: standardize experimental feature disclaimer across documentation

- aztec_macros/src/transforms/note_interface.rs
- aztec_macros/src/transforms/storage.rs
- compiler/noirc_frontend/src/ast/structure.rs
- compiler/noirc_frontend/src/ast/traits.rs
- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- compiler/noirc_frontend/src/hir/def_map/mod.rs
- compiler/noirc_frontend/src/parser/mod.rs
- compiler/noirc_frontend/src/parser/parser.rs
- compiler/noirc_frontend/src/parser/parser/structs.rs
- compiler/noirc_frontend/src/parser/parser/traits.rs
- compiler/noirc_frontend/src/tests.rs
- noir_stdlib/src/meta/trait_constraint.nr
- test_programs/compile_success_empty/comptime_trait_constraint/src/main.nr
Resolves 
This is somewhat of a quick fix to the issue in the trait constraint PR and in @asterite's comptime prefix operator PR.
The issue was that the comptime functions/blocks were using other functions which weren't elaborated yet. So they saw an empty function body. Just adding `comptime` to a function in an impl wasn't sufficient since the compiler didn't look in every function within an impl to know whether to add the impl to the list of comptime items. Moreover, it wouldn't be possible to only add this `comptime` to a subset of functions within an impl so I decided to allow `comptime` as a keyword on an entire impl as well - and this is what decides whether or not to add it to the comptime items.
I'm not really satisfied with this solution since it overloads `comptime` to mean …
> fix: Add `comptime` to trait impls and structs

- compiler/noirc_frontend/src/hir/def_map/module_data.rs
Resolves 
Looks like we missed a dbg in one of the recent PRs. This was causing a lot of unnecessary dbg output.
Check one:
> chore: Remove dbg on find_func_with_name

- compiler/noirc_frontend/src/elaborator/mod.rs
Resolves 
Removes the "Unknown attribute warning" since it is now spamming aztec-nr use cases.
We'll want to re-add this warning eventually but we'd need some way to known when users want to call attributes as a function versus when they are just annotations picked up from elsewhere. It's possible this later use case may disappear once `macro_processors` is removed though.
Check one:
> chore: Remove unknown annotation warning

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir/comptime/value.rs
- noir_stdlib/src/compat.nr
- noir_stdlib/src/field/mod.nr
- test_programs/execution_success/comptime_slice_equality/Nargo.toml
- test_programs/execution_success/comptime_slice_equality/src/main.nr
Resolves 
This PR changes the function `std::compat::is_bn254` to run in a `comptime` context. To do this I've had to implement a few compiler builtins within the interpreter.
I've had to mangle `std::compat::is_bn254` a bit to get around restrictions on when a function can be called in a `comptime` context however.
This works around around the loop unrolling issue experienced in #4535.
Check one:
> feat: add comptime support for `modulus_*` compiler builtins

- compiler/noirc_frontend/src/ast/expression.rs
- tooling/lsp/src/lib.rs
- tooling/lsp/src/requests/document_symbol.rs
- tooling/lsp/src/requests/mod.rs
- tooling/lsp/src/types.rs
- tooling/lsp/test_programs/document_symbol/Nargo.toml
- tooling/lsp/test_programs/document_symbol/src/main.nr
Resolves #5533
With this you can see where you are at any time, and jump to any symbol in the document.
https://github.com/user-attachments/assets/74ebdb36-cd51-4afc-a33e-775156c1317b
None
Check one:
> feat: LSP document symbol

- Cargo.lock
- tooling/lsp/Cargo.toml
- tooling/lsp/src/requests/inlay_hint.rs
I noticed that the inlay hint request would sometimes panic. This happens if the request happens when a source file is being edited but its cached version (in a FileMap) is not yet updated. Then, the editor might pass a line range that's bigger than what's cached... producing a panic.
In reality, the panic comes from the `codespan_lsp` crate: a function we call returns `Result`, but there's an `unwrap()` inside it making it panic instead of returning a Result.
Here we don't depend on `codespan_lsp` for doing that, and instead copy the logic but never panic.
None.
Check one:
> fix: never panic in LSP inlay hints

- compiler/noirc_evaluator/src/ssa/ir/instruction.rs
PR #5449 introduces a new issue in aztec protocol circuits
Revert the PR
The test 'sort_get_split_order_hints_desc_non_zero_split_counter_empty' is failing with the PR.
It is not clear to me why the PR is making this to fail.
One corner case that we could have when you replace a load with the stored value is:
- loose the index bound check (i.e `A[i]=y; x=A[i] +5; `becomes `x=y+5`, whether or not i is out-of-bounds.
- loose the side-effect; if the store is under a side-effect, replacing it uses by the stored value is not conditional to the enable-side-effect value anymore.
Check one:
> fix: revert PR #5449

- compiler/noirc_frontend/src/hir/comptime/value.rs
Resolves 
With the mutability change in the interpreter we now use `Type::Pointer` for non-`&mut` types. If `auto_deref` is type it signals the variable is mutable, but not an actual mutable reference type.
Check one:
> fix: type_of for pointer types

- compiler/noirc_frontend/src/hir_def/types.rs
Fixes two issues:
1. Our `occurs` check did not check the type variable ids at each step. So if the same type variable is in the middle of several bindings, we could miss it and bind anyway, creating a cycle.
2. `force_bind` should still do an `occurs` check
Check one:
> fix: Fix occurs check

- aztec_macros/src/utils/hir_utils.rs
Do not report the warnings as error during Aztec Macro compilation
When Aztec Macro is calling the elaborator, warnings are not discriminated from errors, so they break contract compilation.
Check one:
> chore: filter warnings from elaborator in Aztec Macros

- docs/docs/noir/concepts/generics.md
> chore(docs): Docs for turbofish operator

- test_programs/execution_success/uhashmap/Nargo.toml
Resolves 
The wrong test name here is causing CI on other PRs to fail (namely https://github.com/noir-lang/noir/pull/5540) - not sure how the original PR passed checks with this.
Check one:
> fix: Fix `uhashmap` test name

- compiler/noirc_frontend/src/ast/mod.rs
- compiler/noirc_frontend/src/parser/errors.rs
- compiler/noirc_frontend/src/parser/parser/function.rs
- compiler/noirc_frontend/src/tests.rs
Resolves #5552
This temporarily disallows signed numeric generics as to prevent the panic in the issue until they are fully supported. In general type-level integers need to be updated to support numeric generics. It is deceiving to not ban them until type-level integers are updated as otherwise users can declare signed numeric generics but not actually use them as per the linked issue.
For the code in the issue we now get this error:
Check one:
- [] No documentation needed.
> fix(frontend): Disallow signed numeric generics

- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/trait_impls.rs
- compiler/noirc_frontend/src/elaborator/traits.rs
- compiler/noirc_frontend/src/elaborator/types.rs
- compiler/noirc_frontend/src/hir_def/function.rs
- test_programs/compile_success_empty/trait_call_full_path/Nargo.toml
- test_programs/compile_success_empty/trait_call_full_path/src/main.nr
Resolves #5557
For something like `Add::add` the logic was checking if `Add` was a trait, then looking for a method `add` in it. It only worked if the path had exactly two segments.
I initially thought the fix was simple: also make it work if there are more segments. However, it got tricky if there's just one segment: we need to find out the trait associated with the found function. This wasn't tracked in `FuncMeta` (well, there was a boolean for it but not the optional `TraitId`) so in this PR this information is now tracked, and the lookup works in all cases.
None.
Check one:
> fix: allow calling a trait method with paths that don't consist of exactly two segments

- compiler/noirc_frontend/src/ast/mod.rs
- compiler/noirc_frontend/src/parser/errors.rs
- compiler/noirc_frontend/src/parser/parser/function.rs
- compiler/noirc_frontend/src/parser/parser/types.rs
- compiler/noirc_frontend/src/tests.rs
Resolves #5571 
The issue references expanding the supported type-level integers, however, after a team discussion we decided to simply restrict the supported numeric generics. If other kinds of numeric generics become highly requested we can then re-assess whether we want to expand support for type level constants.
A new parser combinator for numeric generics was introduced to differentiate with the existing `type_expression` combinator. This is due to usage of `or_not` in the `generic_type_args` parser. Due to the `or_not` combinator the expression error was being ignored. Thus, the new numeric generic expression combinator returns an optional expression along with its parsed type.
This program:
```rust
fn big<let N: u64>() -> u64 {
N
}
fn main() {
let _ = big::<18446744073709551615>(); …
```
> fix(frontend)!: Restrict numeric generic types to unsigned ints up to `u32`

- Cargo.lock
- compiler/noirc_frontend/Cargo.toml
- compiler/noirc_frontend/src/hir/comptime/errors.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/foreign.rs
Resolves another of the many builtin/foreign functions that still need to be implemented in the interpreter
Check one:
> feat: Implement `poseidon2_permutation` in comptime interpreter

- compiler/noirc_frontend/src/monomorphization/mod.rs
- test_programs/compile_success_empty/zeroed_slice/Nargo.toml
- test_programs/compile_success_empty/zeroed_slice/src/main.nr
Resolves #5429
An incorrect type literal type was being passed.
None.
Check one:
> fix: let std::unsafe::zeroed() work for slices

- compiler/noirc_frontend/src/parser/parser.rs
- compiler/noirc_frontend/src/parser/parser/traits.rs
Resolves #4809
Also removes some duplicated parsing functions (I checked and their code was exactly the same).
None.
Check one:
> fix: allow trailing comma when parsing where clauses

- compiler/noirc_frontend/src/elaborator/types.rs
- compiler/noirc_frontend/src/tests.rs
Resolves #5186
Looking for methods that are bound to trait constraints was already working for `NamedGeneric`, but when the trait is on a composite type, like `(T, U)` or even `(T, i32)` methods weren't lookup up in constraints bound to those types.
We only lookup this in case the regular (`lookup_primitive_method`) lookup fails to find something.
None.
Check one:
> fix: lookup trait constraints methods in composite types

- compiler/noirc_frontend/src/elaborator/mod.rs
- test_programs/compile_success_empty/trait_call_in_global/Nargo.toml
- test_programs/compile_success_empty/trait_call_in_global/src/main.nr
Resolves #5029
Trait constraints weren't checked after elaborating a global.
I couldn't just call `check_and_pop_function_context()` because that also defaults type variables... and if we do that the usage of a global will not have an effect on its type. I guess this is one scenario:
```rust
global x = 1; // What's the type of x?
```
We don't know. I guess it ends up being `Field` later on (where?) But if we have this:
```rust
global x = 1;
fn main() {
let y: i32 = 0;
assert_eq(x, y);
}
```
now x's type will be `i32` because of that comparison. So if we eagerly bind `1` to its default type, this will break.
All of this to say: in Rust a global's type (well, for a `const`) must be explicitly specified. I guess that if we also did that in Noir then this wouldn't be a problem. And given that …
> fix: let trait calls work in globals

- compiler/noirc_frontend/src/elaborator/comptime.rs
- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/types.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/hir/def_map/mod.rs
- compiler/noirc_frontend/src/hir_def/function.rs
Resolves https://github.com/noir-lang/noir/pull/5538#issuecomment-2237533285
If a function with an empty body is found within the comptime interpreter we now lazily elaborate it instead of failing with an error.
The test for this is `noir_test_success_comptime_globals` which after #5538 requires lazy elaboration due to comptime globals themselves now being elaborated before functions.
This PR opens the way to be more lax about marking functions `comptime` and potentially lets us remove the restriction that you can only call non-comptime functions in separate modules.
Check one:
> fix: Lazily elaborate functions in comptime interpreter

- aztec_macros/src/transforms/functions.rs
- aztec_macros/src/transforms/note_interface.rs
- aztec_macros/src/transforms/storage.rs
- aztec_macros/src/utils/ast_utils.rs
- compiler/noirc_frontend/src/ast/expression.rs
- compiler/noirc_frontend/src/ast/mod.rs
- compiler/noirc_frontend/src/ast/statement.rs
- compiler/noirc_frontend/src/debug/mod.rs
- compiler/noirc_frontend/src/elaborator/expressions.rs
- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/patterns.rs
- compiler/noirc_frontend/src/elaborator/scope.rs
- compiler/noirc_frontend/src/elaborator/types.rs
- compiler/noirc_frontend/src/elaborator/unquote.rs
- compiler/noirc_frontend/src/hir/comptime/hir_to_display_ast.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/resolution/import.rs
- compiler/noirc_frontend/src/hir/type_check/errors.rs
- compiler/noirc_frontend/src/noir_parser.lalrpop
- compiler/noirc_frontend/src/parser/parser.rs
- compiler/noirc_frontend/src/parser/parser/path.rs
- compiler/noirc_frontend/src/parser/parser/primitives.rs
- compiler/noirc_frontend/src/parser/parser/traits.rs
- compiler/noirc_frontend/src/parser/parser/types.rs
- compiler/noirc_frontend/src/tests.rs
- tooling/lsp/src/requests/document_symbol.rs
- tooling/lsp/src/requests/inlay_hint.rs
- tooling/nargo_fmt/src/rewrite/expr.rs
Part of #5584
This PR adds support for parsing turbofishes in any path segments. Turbofish is only still checked when elaborating variables, but only for the last turbofish (like before). For now any other placement of a turbofish will give a type error, but at least they can be parsed now. In later PRs we can make them work in the middle of variables, in constructors, etc.
Right now turbofishes aren't parsed in named typed (for example in a struct pattern). The reason is that if I use `path()` instead of `path_no_turbofish()` then the parser gives a stack overflow and I'm not sure why. Maybe it's because `parse_type()` is used recursively, I'm not sure... but these stack overflow errors are kind of hard to diagnose. In any case we can parse those later on once we decide to support …
> feat: turbofish operator on path segments

- compiler/noirc_frontend/src/elaborator/expressions.rs
Resolves #5523
The span of a Prefix expression was taken from its prefixed expression instead of from the entire expression.
I'm not sure how to test this 🤔 
Check one:
> fix: correct span for prefix operator

- compiler/noirc_frontend/src/ast/statement.rs
- compiler/noirc_frontend/src/elaborator/expressions.rs
- compiler/noirc_frontend/src/elaborator/patterns.rs
- compiler/noirc_frontend/src/elaborator/types.rs
- compiler/noirc_frontend/src/parser/parser.rs
- compiler/noirc_frontend/src/parser/parser/path.rs
- compiler/noirc_frontend/src/parser/parser/primitives.rs
- compiler/noirc_frontend/src/parser/parser/types.rs
- compiler/noirc_frontend/src/tests.rs
Part of https://github.com/noir-lang/noir/issues/5584
Allows parsing turbofish in a struct pattern path segments, then uses those turbofish generics for type binding/inference.
None.
Check one:
> feat: turbofish in struct pattern

- tooling/lsp/src/requests/inlay_hint.rs
- tooling/lsp/test_programs/inlay_hints/src/main.nr
Resolves #5527
Makes type hints insertable, though not all of them can be inserted. For example a for variable can't have a type annotation, and a struct member pattern can't either.
I also added a test for when the type hint is shown for a struct member pattern, which was missing (mainly to assert that the type there isn't insertable).
https://github.com/user-attachments/assets/b3a02f2b-be82-49b5-9ac5-cebf8cb83214
None.
Check one:
> feat: allow inserting LSP inlay type hints

- compiler/noirc_frontend/src/elaborator/types.rs
- compiler/noirc_frontend/src/tests.rs
Resolves #5583
There's a call, `verify_generics_count`, that's supposed to do this check. The problem is that the `args` given to it are the results of zipping the struct's generics with the given generics. That will always produce an `args` the size of the smallest of the two. So, if a struct doesn't have generics, `args` will end up empty and no error is produced. However, if a struct has more generics than given, an error was correctly produced. The solution is to get the actual and expected numbers before shadowing `args`.
In Rust this program gives two errors:
```rust
struct Foo {}
impl Foo<T> {}
fn main() { }
```
1. cannot find T in this scope
2. struct takes 0 generic arguments but 1 generic argument was supplied
With this PR, in Noir we'll be just giving one error (the second …
> fix: error on incorrect generic count for impl and type alias

- tooling/lsp/src/requests/inlay_hint.rs
- tooling/lsp/test_programs/inlay_hints/src/main.nr
Resolves #5640
None.
Check one:
> feat: LSP inlay type hints on lambda parameters

- compiler/fm/src/file_map.rs
- tooling/lsp/src/requests/mod.rs
Resolves #5641
It seems `FileMap`'s `name` function was the one that needed that change.
To avoid doing a syscall to get the current directory every time a name is needed, `FileMap` gets it at the beginning of the program. I think this is fine as the current directory can't change while the compilation is happening.
None.
Check one:
> feat: let filenames in errors be relative to the current dir if possible

- compiler/noirc_frontend/src/elaborator/scope.rs
- compiler/noirc_frontend/src/tests.rs
Resolves #1791
When resolving a path (any path), we now check if the first segment is `Self` (a similar check is done in another places of our codebase). If so, resolve the next path segments relative to that type. Only struct types are supported here... in theory a trait type can also show up, but that case is handled as a special case in the compiler. I'll create a follow-up PR removing that special case and seeing if it works.
None.
Check one:
> fix: allow using Self for function calls

- compiler/noirc_frontend/src/monomorphization/mod.rs
- test_programs/compile_failure/type_annotation_needed_on_struct_constructor/Nargo.toml
- test_programs/compile_failure/type_annotation_needed_on_struct_constructor/src/main.nr
- test_programs/compile_failure/type_annotation_needed_on_struct_new/Nargo.toml
- test_programs/compile_failure/type_annotation_needed_on_struct_new/src/main.nr
Resolves #5436
The monomorphizer checks that no types exist that aren't unbound and can't have a default type. This is also the case for structs, but this check is done on field types after they are paired with generics. For example:
```rust
struct Foo<T> {
x: T
}
fn main() {
let _ = Foo { x: 1 };
}
```
Here we pair `T` with the generic type of 1, then it's defaulted to `Field`, no error.
However, it can happen that a generic parameter isn't mentioned at all in a struct field. For example:
```rust
struct Foo<T> {
}
fn main() {
let _ = Foo {};
}
```
Here `T` isn't paired with anything, so it's left unbound. However, because we only check that the resulting field types aren't unbound, no error happens.
The solution in this PR is to check that generic parameters aren't unbound. This required …
> fix: error on unbound generics in structs

- tooling/lsp/src/lib.rs
- tooling/lsp/src/notifications/mod.rs
- tooling/lsp/src/requests/code_lens_request.rs
- tooling/lsp/src/requests/hover.rs
- tooling/lsp/src/requests/inlay_hint.rs
- tooling/lsp/src/requests/mod.rs
- tooling/lsp/src/requests/references.rs
The LSP server recently became very slow. The main culprits are these two PRs:
- https://github.com/noir-lang/noir/pull/5461
- https://github.com/noir-lang/noir/pull/5561
Those PRs made it so that when a file is opened, changed or saved, we re-analyze the entire workspace. It turns out that's too slow (I tried it on a few big projects and it wasn't slow, but it is slow in one of our projects). The old behavior was to only check the package where the file is, not the entire workspace.
Another issue is that inlay hints don't work well inside contracts because they have generated code that ends up overlapping the real code.
This is what this PR does: it only checks the enclosing package when opening or saving a document (essentially reverting #5461). There's also a speed-up here because …
> fix: speed up LSP

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- noir_stdlib/src/meta/mod.nr
- noir_stdlib/src/meta/typ.nr
- test_programs/compile_success_empty/comptime_type/Nargo.toml
- test_programs/compile_success_empty/comptime_type/src/main.nr
Part of #5668
I originally wanted to just add `type_of`, but in order to test it in some way I thought of comparing two types and checking whether they are equal or not... which required implementing `Eq` for `Type`, which I guess is useful any way.
Another way could have been to be able to turn a `Type` into a string and check that, but there's no unbounded `String` type at comptime... Another way would be to `println` the type and check the program's output, but there's no quick way to do it right now... but I think asserting on equality is fine too, especially because the implementation of `type_of` is very simple.
Check one:
> feat: add `std::meta::type_of` and `impl Eq for Type`

- compiler/noirc_frontend/src/node_interner.rs
- compiler/noirc_frontend/src/tests.rs
Resolves #5195
If I'm understanding the code correctly, when you have code like this:
```rust
trait Trait {
fn trait_func(self);
}
fn foo<T>(t: T) {
Trait::trait_func(t);
}
```
the compiler will search in all impls of `Trait` for a matching one. Then:
- if it only finds one, it succeeds
- otherwise it's an error (no matching impl found, or too many found)
If an impl has a where clause, the compiler checks if that where clause matches. For example:
```rust
trait One {
}
impl Trait for T where T: One {
// ...
}
```
So here there's an impl for `Trait`, it has a where clause, so the compiler checks if that `T` is `One`. And here's the thing: if there's no match, it would immediately error. I think that was the bug.
In this PR, we capture that error but continue seeing if we can find a …
> fix: let a trait impl that relies on another trait work

- compiler/integration-tests/circuits/recursion/src/main.nr
- docs/docs/noir/standard_library/recursion.md
- examples/recursion/recurse_leaf/src/main.nr
- examples/recursion/recurse_node/src/main.nr
- noir_stdlib/src/lib.nr
- test_programs/execution_success/double_verify_nested_proof/src/main.nr
- test_programs/execution_success/double_verify_proof/src/main.nr
- test_programs/execution_success/double_verify_proof_recursive/src/main.nr
Resolves https://github.com/noir-lang/noir/issues/5660
Switches verify proof to arrays
Check one:
> fix: Switch verify proof to arrays

- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- test_programs/compile_success_empty/regression_5671/Nargo.toml
- test_programs/compile_success_empty/regression_5671/src/main.nr
Resolves #5671
The issue was that we were adding trait constraints to the methods themselves in `dc_mod` but this code isn't run for items generated from attributes which only go through the elaborator. I've just moved this code to the elaborator instead.
Check one:
> fix: Fix where clause issue in items generated from attributes

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- noir_stdlib/src/meta/typ.nr
- test_programs/compile_success_empty/comptime_type/src/main.nr
Part of #5668
I'm leaving `as_struct` for a next PR.
None.
Check one:
> feat: add `Type` methods: `as_tuple`, `as_slice`, `as_array`, `as_constant`, `is_bool`

- tooling/lsp/src/requests/hover.rs
In Rust LSP, when you hover over a variable you get to see its type, but you also get links to every reachable type. I wanted to do that when implementing hover but I didn't know how. Now I figured it out :-)
This is what this PR does:
https://github.com/user-attachments/assets/7362d51d-c836-4ab1-b840-d2e7f3fb38d4
None.
Check one:
> feat: LSP hover now includes "Go to" links

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- noir_stdlib/src/meta/typ.nr
- test_programs/compile_success_empty/comptime_type/src/main.nr
Part of #5668
None.
Check one:
> feat: add `Type::as_struct`

- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- test_programs/compile_success_empty/comptime_closures/Nargo.toml
- test_programs/compile_success_empty/comptime_closures/src/main.nr
Resolves https://github.com/noir-lang/noir/issues/4879
Implements closures in the comptime interpreter.
This ended up being much easier than expected. Almost makes me suspicious.
Check one:
> feat: Implement closures in the comptime interpreter

- tooling/lsp/src/requests/inlay_hint.rs
- tooling/lsp/src/requests/mod.rs
- tooling/lsp/test_programs/inlay_hints/src/main.nr
I had this code back when I was playing with inlay hints. I originally implemented all inlay hints types but then I split them into smaller PRs. This is the last one of those PRs.
https://github.com/user-attachments/assets/6b3cf946-cbac-496f-befd-eba394cd8460
Check one:
> feat: LSP closing brace hints

- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
- compiler/noirc_frontend/src/parser/mod.rs
- compiler/noirc_frontend/src/parser/parser.rs
- compiler/noirc_frontend/src/parser/parser/path.rs
- compiler/noirc_frontend/src/parser/parser/traits.rs
- noir_stdlib/src/meta/function_def.nr
- noir_stdlib/src/meta/mod.nr
- noir_stdlib/src/meta/module.nr
- noir_stdlib/src/meta/quoted.nr
- test_programs/compile_success_empty/comptime_function_definition/src/main.nr
- test_programs/compile_success_empty/comptime_module/Nargo.toml
- test_programs/compile_success_empty/comptime_module/src/main.nr
Part of #5668
Adds these comptime functions:
- `Quoted::as_module`
- `Module::name`
- `Module::is_contract`
- `Module::functions`
- `FunctionDefinition::name`
Some notes:
- I made `Quoted::as_module` return `Option<ModuleId>`, while other `Quoted::as_...` methods currently return a non-Option instead. Eventually it would be nice to unify these but doing that in this PR would have made it much bigger and complex, mainly because those methods rely on methods that are used in many places in the compiler.
- For now I made `Module::name` and `FunctionDefinition::name` return `Quoted`. Once we have a `String` type we could change them to `String`, and the logic from going to Quoted -> String is very simple.
I was wondering... would a `String` type be what a Slice is for Arrays?
One more …
> feat: add some `Module` comptime functions

- compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
- compiler/noirc_evaluator/src/ssa/function_builder/mod.rs
- compiler/noirc_evaluator/src/ssa/ir/cfg.rs
- compiler/noirc_evaluator/src/ssa/ir/instruction.rs
- compiler/noirc_evaluator/src/ssa/ir/instruction/call.rs
- compiler/noirc_evaluator/src/ssa/ir/printer.rs
- compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs
- compiler/noirc_evaluator/src/ssa/opt/flatten_cfg/value_merger.rs
- compiler/noirc_evaluator/src/ssa/opt/inlining.rs
- compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs
- compiler/noirc_evaluator/src/ssa/opt/simplify_cfg.rs
- compiler/noirc_evaluator/src/ssa/opt/unrolling.rs
Resolves https://github.com/noir-lang/noir/issues/5322
Previously we added call stacks as a way to give better error reporting on SSA instructions. Since these were just for errors, they only needed to be on instructions which could emit errors. Since then, these call stacks have also been used for profiling Noir code which revealed many instructions without locations - many of them being instructions inserted by the compiler rather than the user during intermediate compiler passes like flatten_cfg.
I've went through and gotten rid of each case of `CallStack::new()`. As far as I can tell all the remaining locations are either the intended use case of an initial, empty value, or are used in some error messages where the location is unknown.
Anyways - because many of the instructions …
> fix: Add locations to most SSA instructions

- docs/docs/getting_started/hello_noir/index.md
Since nargo/bb split, a few people accidentally mix up filenames used between the commands (compile, witness, prove, verify)
Check one:
> chore: Add docs tip about filenames between commands

- compiler/noirc_frontend/src/elaborator/patterns.rs
- compiler/noirc_frontend/src/hir/comptime/errors.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/foreign.rs
- compiler/noirc_frontend/src/node_interner.rs
- compiler/noirc_frontend/src/parser/mod.rs
- compiler/noirc_frontend/src/parser/parser.rs
- noir_stdlib/src/meta/function_def.nr
- test_programs/compile_success_empty/comptime_function_definition/src/main.nr
- tooling/nargo_fmt/src/items.rs
Part of #5668
I think we are missing a `FunctionDefinition::body`, but that could come later.
I had to get a `FuncMeta` many times in some functions because Rust wouldn't let me get two mutable borrows of interner.
Generics handling is missing... but I think right now generics can't appear in these functions, as attributes only run on top-level functions, not on impl or trait impl functions, but let me know if this is not the case.
Check one:
> feat: add mutating FunctionDefinition functions

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- noir_stdlib/src/meta/typ.nr
- test_programs/compile_success_empty/comptime_type/src/main.nr
> feat: add `Type::implements`

- compiler/noirc_frontend/src/hir/def_map/module_data.rs
- compiler/noirc_frontend/src/lib.rs
- compiler/noirc_frontend/src/parser/errors.rs
- compiler/noirc_frontend/src/parser/parser/path.rs
- tooling/lsp/src/lib.rs
- tooling/lsp/src/notifications/mod.rs
- tooling/lsp/src/requests/completion.rs
- tooling/lsp/src/requests/hover.rs
- tooling/lsp/src/requests/inlay_hint.rs
- tooling/lsp/src/requests/mod.rs
- tooling/lsp/src/types.rs
- tooling/lsp/src/utils.rs
Part of #1577
Implements autocompletion for use statements, so typing anything after `use`.
https://github.com/user-attachments/assets/a9ecd738-30c2-41fc-8ea0-3ea93d5d99ab
Note: the gray hints are probably coming from copilot, I should have turned it off before recording 😅 
To begin implementing autocompletion I thought starting with `use` would be the easiest thing, but also not having to look up the std (or your project) module hierarchy could be useful.
To implement this I had to allow parsing `use foo::`, that is, allowing trailing colons, because otherwise that wouldn't parse to a use statement and we wouldn't have any information to do the autocompletion.
There are still some cases that don't work. For example if you write `use ` and explicitly ask for autocompletion, you don't get …
> feat: LSP autocompletion for use statement

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
- compiler/noirc_frontend/src/hir/comptime/value.rs
- noir_stdlib/src/meta/expr.nr
- noir_stdlib/src/meta/mod.nr
- noir_stdlib/src/meta/quoted.nr
- test_programs/compile_success_empty/comptime_exp/Nargo.toml
- test_programs/compile_success_empty/comptime_exp/src/main.nr
Part of #5668
What the title says.
I didn't know how to test the exprs. I tried implementing `impl Eq for Expr` but even though two exprs looked the same (same tokens) they weren't equal... but I didn't dig deeper into why that is (I didn't know if `Eq` was desired in this case)
Check one:
> feat: add `Quoted::as_expr` and `Expr::as_function_call`

- Cargo.lock
- compiler/noirc_frontend/Cargo.toml
- compiler/noirc_frontend/src/hir/def_map/module_data.rs
- compiler/noirc_frontend/src/lexer/token.rs
- tooling/lsp/Cargo.toml
- tooling/lsp/src/requests/completion.rs
- tooling/lsp/src/requests/completion/builtins.rs
Part of #1577
LSP will now suggest completions anywhere there's a Path. Here are some scenarios:
Sorry for the large diff, the bulk of it is traversing the AST. I thought about using something like the Visitor pattern, but I'm not exactly sure how it would look in Rust and whether it would greatly reduce the amount of code. It could be a separate refactor, though! (and we have tons of tests now, so it should be safe to do too).
Another big chunk of code is tests... So the actual logic isn't that large. 
Some more things could be done on top of this, like suggesting `Self` if it's available, but I wanted to stop making this PR bigger 😊 
Check one:
> feat: LSP path completion

- aztec_macros/src/transforms/contract_interface.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_frontend/src/node_interner.rs
- compiler/noirc_frontend/src/parser/errors.rs
- compiler/noirc_frontend/src/parser/parser.rs
- compiler/noirc_frontend/src/resolve_locations.rs
- tooling/lsp/src/requests/completion.rs
- tooling/lsp/src/requests/mod.rs
Suggest struct fields and methods after you type "." or "::". 
Here it's working in a project inside Aztec-Packages:
Some things don't work well yet. For example if you chain some calls, like `[1, 2, 3].as_slice().` nothing is offered there. It has to do with how things are stored in `id_to_location`. Or if you type `if something.` then nothing gets offered because that doesn't parse right.
We could improve those things on later PRs, though, but at least autocompletion now is much better than before.
Check one:
> feat: LSP fields, functions and methods completion after "." and "::"

- compiler/noirc_frontend/src/elaborator/expressions.rs
- compiler/noirc_frontend/src/parser/errors.rs
- compiler/noirc_frontend/src/parser/parser.rs
- tooling/lsp/src/requests/completion.rs
There were a couple of contexts where autocompletion wouldn't trigger. This PR fixes some of these.
Before:
After:
Before:
The reason is that is was autocompleting for the type of `foo.bar & foo` instead of just `foo`.
After:
Before:
After:
Before:
After:
I might send a follow-up PR to split `completion.rs` into several files because it's getting pretty big. For example tests could go in a separate file.
Check one:
> fix: let LSP autocompletion work in more contexts

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
- noir_stdlib/src/meta/mod.nr
- noir_stdlib/src/meta/trait_impl.nr
- test_programs/compile_success_empty/comptime_trait_impl/Nargo.toml
- test_programs/compile_success_empty/comptime_trait_impl/src/main.nr
> feat: add `TraitImpl::trait_generic_args` and `TraitImpl::methods`

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- noir_stdlib/src/meta/expr.nr
- test_programs/compile_success_empty/comptime_exp/src/main.nr
Part of #5668
Just four, to keep PRs small.
Check one:
> feat: add `Expr` methods: `as_tuple`, `as_parenthesized`, `as_index`, `as_if`

- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- noir_stdlib/src/meta/expr.nr
- test_programs/compile_success_empty/comptime_exp/src/main.nr
Part of #5668
Just one method because while doing it I got an error trying to compare two bools at comptime, and I found that that case was missing.
Check one:
> feat: add `Expr::as_bool`

- tooling/lsp/src/requests/completion.rs
- tooling/lsp/src/requests/completion/completion_items.rs
- tooling/lsp/src/requests/completion/tests.rs
- tooling/lsp/src/requests/completion/traversal.rs
- tooling/lsp/src/requests/signature_help/traversal.rs
Part of #1577
(there are many more completions we could support and it's hard to list all of them upfront, so I'll just link to that issue from now on)
Suggest tuple fields (0, 1) in autocompletion, which is useful if you don't know the type you are handling with (maybe it's a result of another expression that's not in a variable).
Also I noticed tuple methods showed up duplicate, so that's fixed too.
Before:
After:
The two first commits are just refactors, so I'd suggest going commit by commit.
Check one:
> feat: suggest tuple fields in LSP completion

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- noir_stdlib/src/meta/expr.nr
- noir_stdlib/src/meta/mod.nr
- noir_stdlib/src/meta/op.nr
- test_programs/compile_success_empty/comptime_exp/src/main.nr
Part of #5668
Adds `UnaryOp` as the type to hold the operator.
I plan to tackle `as_binary_op` next, and use the same `op.nr` file for it with a `BinaryOp` type.
Check one:
> feat: add `Expr::as_unary`

- tooling/lsp/src/requests/completion.rs
- tooling/lsp/src/requests/completion/completion_items.rs
- tooling/lsp/src/requests/completion/tests.rs
^ The above is just an example of it working, I'm not encouraging using constructors of std types 😄 
This is the last autocompletion I had in mind while implementing autocompletion, so I'll likely won't send any other LSP PRs for a while...
That said, if you think of other autocompletions (that don't involve auto-importing, because that's a big thing) let me know (or capture an issue) and we can work on it.
Check one:
> feat: LSP autocomplete constructor fields

- tooling/lsp/src/requests/completion.rs
- tooling/lsp/src/requests/completion/completion_items.rs
- tooling/lsp/src/requests/completion/tests.rs
Also includes a couple of refactors to further simplify things.
Check one:
> feat: suggest trait methods in LSP completion

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- noir_stdlib/src/meta/expr.nr
- noir_stdlib/src/meta/op.nr
- test_programs/compile_success_empty/comptime_exp/src/main.nr
> feat: add `Expr::as_binary_op`

- docs/docs/explainers/explainer-writing-noir.md
Clarify use of Field type
Check one:
> chore: clarify Field use

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- noir_stdlib/src/meta/expr.nr
- test_programs/compile_success_empty/comptime_exp/src/main.nr
> feat: add `Expr::as_any_integer` and `Expr::as_member_access`

- compiler/noirc_frontend/src/elaborator/mod.rs
- noir_stdlib/src/meta/mod.nr
- test_programs/compile_success_empty/macros_in_comptime/src/main.nr
Resolves 
Allows `comptime` code to use `break` and `continue` without also marking the functions `unconstrained`. This is more important with the `unsafe { }` change since we don't want to have to wrap comptime code in unsafe blocks, nor do we want to mark unconstrained functions used in a comptime block as requiring `unsafe { }`.
Check one:
> fix: Allow comptime code to use break without also being `unconstrained`

- compiler/noirc_frontend/src/ast/expression.rs
- compiler/noirc_frontend/src/elaborator/comptime.rs
- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- compiler/noirc_frontend/src/hir/def_map/module_def.rs
- compiler/noirc_frontend/src/locations.rs
- compiler/noirc_frontend/src/node_interner.rs
- tooling/lsp/src/requests/completion.rs
- tooling/lsp/src/requests/completion/auto_import.rs
- tooling/lsp/src/requests/completion/autoimport.rs
- tooling/lsp/src/requests/completion/sort_text.rs
- tooling/lsp/src/requests/completion/tests.rs
I said I wasn't going to send any more LSP features, but I had this one in the back of my head since I started working on autocompletion. I had the idea of how to do it in my head, but I wanted to first work on the easier stuff (regular autocompletion). It turns out auto-import wasn't that hard to implement after all!
In this PR every new imported item is added as a full path. Ideally, like in Rust Analyzer, we'd group common use prefixes, add to existing ones, etc. We can do that! But maybe it could be part of a follow-up PR, or maybe we could do it much later. Or maybe `nargo fmt` could handle this, so the auto-import doesn't do it, but once you save the file it's done. That's why I didn't spend time on that in this PR.
There's …
> feat: LSP auto-import completion

- Cargo.lock
- tooling/lsp/Cargo.toml
- tooling/lsp/src/requests/completion.rs
- tooling/lsp/src/requests/completion/completion_items.rs
- tooling/lsp/src/requests/completion/sort_text.rs
- tooling/lsp/src/requests/completion/tests.rs
As I mentioned in #5741, I noticed Rust Analyzer will suggests methods and names where the prefix you are writing matches any part of the name. Well, kind of, the logic is not exactly that, but that's what's implemented in this PR. It should make finding things much easier (if you are looking for stuff related to "merkle" or "hasher" you just need to type that).
It works in any context, for example struct fields:
None.
Check one:
> feat: (LSP) suggest names that match any part of the current prefix

- noir_stdlib/src/cmp.nr
- noir_stdlib/src/default.nr
- noir_stdlib/src/hash/mod.nr
- noir_stdlib/src/ops/arith.nr
- noir_stdlib/src/ops/bit.nr
Resolves #5733 
This PR implements some missing trait implementations for numeric types. This covers `u16` as mentioned in the issue but also `u1`s
Check one:
> fix: add missing trait impls for integer types to stdlib

- compiler/noirc_frontend/src/parser/errors.rs
- compiler/noirc_frontend/src/parser/parser.rs
- compiler/noirc_frontend/src/parser/parser/function.rs
- compiler/noirc_frontend/src/parser/parser/traits.rs
- tooling/lsp/src/requests/completion.rs
- tooling/lsp/src/requests/completion/tests.rs
Autocompletion wasn't triggering in function parameter types, or in impl names. The reason is that when you start writing them the body will still be missing, and that discarded the entire fn or impl. In this PR we make that parse well, but produce an error (and create a fake empty body).
Now autocompletion works fine in these scenarios:
I'm not sure about the many new "parser error" introduced, maybe there should be a generic "expected these tokens"? I think chumsky has one of those errors but it's kind of tied to the parsing logic. On the other hand adding new errors is simple, so maybe it's fine.
Check one:
> feat: fault-tolerant parsing of `fn` and `impl`

- compiler/noirc_frontend/src/elaborator/expressions.rs
- compiler/noirc_frontend/src/elaborator/statements.rs
- compiler/noirc_frontend/src/elaborator/types.rs
- compiler/noirc_frontend/src/hir/type_check/errors.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_frontend/src/tests.rs
Resolves #5763
This code is handled differently than the other `unsafe` checks, and I forgot about that.
This issue is preventing noir syncs on Aztec Packages.
Check one:
> fix: unconstrained fn mismatch is now a warning

- tooling/lsp/src/requests/completion.rs
- tooling/lsp/src/requests/completion/auto_import.rs
- tooling/lsp/src/requests/completion/tests.rs
- tooling/lsp/src/requests/hover.rs
Part of #1577
We recently added `super::` to `use` so I thought it would be nice if the auto-importer used that if possible.
This PR also includes a small refactor in the hover code because the code to format a module path exists there too (but the two are different enough that I didn't reuse them).
Check one:
> feat: user `super::` in LSP autocompletion if possible

- compiler/noirc_evaluator/src/ssa/ir/instruction.rs
Resolves https://github.com/noir-lang/noir/issues/5767
Instead of checking if an array_get is from a constant array, we can follow array_sets to find a previous constant array. If the index was ever unknown we fail to optimize. If the index is known but changed by an array set we fail as well instead of optimizing to the set value. This is in case the side effect variables are different for the get & set.
I set an arbitrary maximum of 5 array_sets to check before giving up and failing to find a constant array.
Check one:
> feat(optimization): Follow past `array_set`s when optimizing `array_get`s

- tooling/lsp/src/lib.rs
- tooling/nargo/src/lib.rs
Resolves #5774
LSP caches open files so that features work relative to open, potentially unsaved, file buffers. Before analyzing a crate or processing a package, we add these open files to a FileManager. The problem was that we were adding all open files, regardless of whether they belonged to a package. Because we don't always call `check_crate` on LSP features (for example when you hover we collect a packages files but don't call `check_crate`) a packages file FileIDs would change if we added new files that didn't exist before in that package.
It's... kind of hard to explain. But it also makes sense to not add files that are not relevant to the package. I debugged it for hours until I found the reason. With this fix LSP should work really well now (it wasn't working that well in …
> fix: (LSP) only add cached files relevant to workspace

- test_programs/execution_failure/fold_nested_brillig_assert_fail/src/main.nr
- tooling/nargo/src/ops/execute.rs
Resolves 
No issue as small issue found while working on bug related to brillig.
Changing `fold_nested_brillig_assert_fail` to the following main (where we expect the second call to fail):
```rust
fn main(x: Field) {
assert(1 == fold_conditional_wrapper(!x as bool));
assert(1 == fold_conditional_wrapper(x as bool));
}
```
would lead to this call stack:
```
error: Failed to solve program: 'Failed to solve brillig function'
┌─ /mnt/user-data/maxim/noir/test_programs/execution_failure/fold_nested_brillig_assert_fail/src/main.nr:27:12
│
27 │     assert(x);
│            -
│
= Call stack:
1. /mnt/user-data/maxim/noir/test_programs/execution_failure/fold_nested_brillig_assert_fail/src/main.nr:6:17
2. /mnt/user-data/maxim/noir/test_programs/execution_failure/fold_nested_brillig_assert_fail/src/mai …
```
> fix(acvm): Clear ACIR call stack after successful circuit execution

- compiler/noirc_frontend/src/elaborator/scope.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- compiler/noirc_frontend/src/hir/resolution/import.rs
- compiler/noirc_frontend/src/hir/resolution/path_resolver.rs
- compiler/noirc_frontend/src/node_interner.rs
- tooling/lsp/src/requests/completion/auto_import.rs
- tooling/lsp/src/requests/completion/tests.rs
- tooling/lsp/src/requests/goto_definition.rs
- tooling/lsp/src/requests/hover.rs
- tooling/lsp/test_programs/go_to_definition/Nargo.toml
- tooling/lsp/test_programs/go_to_definition/dependency/Nargo.toml
- tooling/lsp/test_programs/go_to_definition/dependency/src/lib.nr
- tooling/lsp/test_programs/go_to_definition/src/main.nr
Resolves #5787
This is a minor thing, but hover and go-to-definition didn't work in path segments that referred to crates. For completeness, and for features we could build later on (for example making auto-import insert new stuff inside existing paths if possible) I thought it would be nice to have this working.
While doing it some code got simplified: the part of a path that referred to a crate didn't refer to anything (None) and that was the only case where an Option was needed. Now that we capture all references that None is gone.
I know we are kind of capturing module attributes twice, one in the def maps and another in NodeInterner, but otherwise getting a Location from a ReferenceId would also need def maps to be passed to NodeInterner, which is a bit less convenient. In any case …
> feat: LSP hover and go-to-definition for crates

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
- compiler/noirc_frontend/src/hir/comptime/value.rs
- noir_stdlib/src/meta/expr.nr
Part of #5668
Both ExpressionKind and StatementKind will be exposed as `Expr` (as discussed with Jake). So `Expr::as_block` will return the block statements as a list of expressions. There's also the thing that some of these statements might be `Semi` (well, all except maybe the last one) and having to explicitly unwrap that with `as_semi` might be tedious or bug-prone, so instead that's unwrapped automatically when you call any of the `as_...` methods, but then there's an `has_semicolon` on `Expr` to know if it has a semicolon.
There's just those two methods in this PR because I wanted to validate this approach. Next I'll add more `as_...` methods but for StatementKind.
Check one:
> feat: Add `Expr::as_block` and `Expr::has_semicolon`

- compiler/noirc_driver/src/lib.rs
- compiler/noirc_evaluator/src/ssa.rs
- cspell.json
Resolves 
No issue as discovered when experimenting with https://github.com/iAmMichaelConnor/blob-lib/tree/domain-size-4096. 
When compiling the circuit on the branch linked above using Noir master this was the result of timing `nargo compile`:
```
nargo compile --force --benchmark-codegen --silence-warnings  383.30s user 148.34s system 131% cpu 6:44.03 total
```
with under constrained check taking 200ms (about half the compilation time). 
The check returned no bugs. If the developer wants to iterate more quickly and knows they are not changing unconstrained code or simply wishes to check for under constrained bugs later they should have the ability.
This PR simply adds a flag `--skip-underconstrained-check` that skips calling `ssa.check_for_underconstrained_values()`.
The blob-lib linked …
> chore: Toggle underconstrained check

- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
- compiler/noirc_evaluator/src/ssa/ir/dfg.rs
- compiler/noirc_evaluator/src/ssa/ir/instruction.rs
- test_programs/execution_success/sha256/Prover.toml
- test_programs/execution_success/sha256/src/main.nr
Resolves #5761
For array operation, we keep the index when it is safe, instead of using the predicate.
Check one:
> fix: do not use predicate for index in array operation, when the index is safe

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
- noir_stdlib/src/meta/expr.nr
Part of #5668
Continuing with the least hardest ones...
Check one:
> feat: add `Expr` methods: as_comptime, as_unsafe, is_break, is_continue

- compiler/noirc_frontend/src/hir/resolution/import.rs
- tooling/lsp/src/requests/completion.rs
- tooling/lsp/src/requests/completion/tests.rs
Resolves #5808
Reuses the same logic done when resolving a `use` or `Path` in the compiler.
It's debatable whether this functionality is desired, because sometimes you add a function, want to use it and autocompletion doesn't suggest it, and it takes a while for you to realize that you forgot to add `pub`. However, a lot of the suggested functions come from the std or external crates, and it doesn't make sense to reveal these private functions. This is also how Rust Analyzer works too.
Check one:
> fix: honor function visibility in LSP completion

- docs/docs/noir/concepts/comptime.md
Resolves 
Cmp is not a trait, it should be Ord.
Check one:
> chore: Fix docs typo

- compiler/noirc_frontend/src/elaborator/types.rs
- test_programs/compile_success_empty/regression_5823/Nargo.toml
- test_programs/compile_success_empty/regression_5823/src/main.nr
Resolves https://github.com/noir-lang/noir/issues/5823
We check `rhs` differently than `lhs` in left and right bit shifts in a series of hacky checks.
In the case of type variables, `lhs` and `rhs` may be swapped causing the unification to be placed on lhs instead of rhs. I've reordered the cases to prevent this.
Check one:
> fix: bit shifting type checking

- docs/docs/noir/standard_library/meta/quoted.md
Resolves 
All PRs are failing the "Deploy preview for PR" CI job. This is causing a big red X on all passing PRs.
Check one:
> fix(docs): Fix file paths for metaprogramming docs

- noir_stdlib/src/hash/keccak.nr
Resolves 
We can reduce the size of our keccak stdlib method in Brillig. There are operations that are repeated across multiple places, different operations we can perform depending on whether we are in an unconstrained or constrained runtime, and we had an extra unnecessary loop for building our `sliced_buffer` variable. 
Check one:
> chore(perf): Update to stdlib keccak for reduced Brillig code size

- docs/docs/noir/concepts/data_types/slices.mdx
Thanks nnsW3 for https://github.com/noir-lang/noir/pull/5833. Our policy is to redo typo changes to dissuade metric farming. This is an automated script.
> chore: redo typo PR by nnsW3

- compiler/noirc_frontend/src/monomorphization/mod.rs
- compiler/noirc_frontend/src/node_interner.rs
- noir_stdlib/src/collections/map.nr
- noir_stdlib/src/collections/umap.nr
- noir_stdlib/src/hash/sha256.nr
- noir_stdlib/src/option.nr
- test_programs/compile_failure/unspecified_generic/Nargo.toml
- test_programs/compile_failure/unspecified_generic/src/main.nr
- test_programs/compile_success_empty/method_call_regression/src/main.nr
- test_programs/compile_success_empty/option/src/main.nr
Ran into this while working on arithmetic generics. It's possible to have cases like:
```rs
fn foo<let N: u32>() {}
fn main() {
foo();
}
```
For which `N` is unused but we don't issue a "type annotations needed" error for it currently because it isn't present in the instantiated function type of `foo`. This PR fixes this and issues the error.
Check one:
> fix!: Check unused generics are bound

- tooling/nargo_cli/src/cli/fs/inputs.rs
…ents but a return value
Resolves 
This is a small QOL change but we don't need to have a `Prover.toml` file in the case where the circuit has no inputs but potential return values. In this case we can tolerate a missing `Prover.toml` file.
Check one:
> chore: don't require empty `Prover.toml` for programs with zero arguments but a return value

- noir_stdlib/src/array.nr
- noir_stdlib/src/field/mod.nr
- noir_stdlib/src/slice.nr
Resolves 
This PR adds some proper documentation to `to_be_bytes` and similar functions. This flags up the potential security concern and failure cases.
Check one:
> chore: add documentation to `to_be_bytes`, etc.

- compiler/noirc_frontend/src/elaborator/types.rs
- compiler/noirc_frontend/src/hir/resolution/errors.rs
- compiler/noirc_frontend/src/hir/type_check/generics.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_frontend/src/hir_def/types/arithmetic.rs
- compiler/noirc_frontend/src/monomorphization/errors.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
- test_programs/compile_success_empty/arithmetic_generics/src/main.nr
In the initial arithmetic generics PR we only added the one specific case for simplifying `(N + C1) - C2`.
Later in the associated types PR we added another case to simplify the non-constant `(N + M) - M`
This PR fills in the missing cases for each other operator. It also has somewhat better overflow handling by returning an `Option` in the operator function and removing the wrapping operations.
Check one:
> chore: Add missing cases to arithmetic generics

- compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_memory.rs
Resolves 
In order to calculate `vector_size - 1 - iterator`, rather than initialising a register to `vector_size` and then decrementing it on each loop iteration, we're currently recalculating it from scratch on each iteration. I've modified this so that we can avoid these extra ops
Check one:
> feat: remove unnecessary copying of vector size during reversal

- compiler/noirc_evaluator/src/ssa/ir/instruction.rs
- compiler/noirc_evaluator/src/ssa/opt/flatten_cfg/value_merger.rs
Resolves 
Found while I was working on Jan's bug. There were a number of arrays we merged where we'd get `vN = if ... then vM else vM` which we had to go through the long merge for without this.
Check one:
> feat(optimization): Avoid merging identical (by ID) arrays

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- docs/docs/noir/standard_library/meta/expr.md
- noir_stdlib/src/meta/expr.nr
- test_programs/compile_success_empty/inject_context_attribute/src/main.nr
- test_programs/noir_test_success/comptime_expr/src/main.nr
Part of #5668
Adds `Expr::as_assert` and handles it in `Expr::mutate`.
None.
Check one:
> feat: add `Expr::as_assert`

- tooling/lsp/src/requests/completion/builtins.rs
- tooling/lsp/src/requests/completion/tests.rs
- tooling/lsp/src/requests/signature_help.rs
- tooling/lsp/src/requests/signature_help/tests.rs
- tooling/lsp/src/requests/signature_help/traversal.rs
This is something minor, but it's good for completeness and also for users to easily learn that there's an optional failure message you can use in these built-in functions.
I don't know if the syntax is clear for showing that the last argument is optional, so if you have another syntax in mind let me know!
Check one:
> feat: LSP signature help for assert and assert_eq

- tooling/nargo/src/errors.rs
- tooling/nargo/src/ops/execute.rs
Resolves 
Bug found while doing other work
With the move to Brillig locations we fetch the brillig function id separately when resolving errors. We were not appropriately attaching a BrilligFunctionId when we had an `ExecutionError::AssertionFailed`. We now attach an `Option<BrilligFunctionId>` to an `ExecutionError::AssertionFailed` that allows us to resolve the Brillig metadata.
Testing on `execution_failure/option_expect`:
Before this PR:
After this PR:
Check one:
> fix(nargo): Resolve Brillig assertion payloads

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- docs/docs/noir/standard_library/meta/typ.md
- noir_stdlib/src/meta/typ.nr
- test_programs/compile_success_empty/comptime_type/src/main.nr
> feat: add `Type::as_string`

- compiler/noirc_frontend/src/resolve_locations.rs
- tooling/lsp/src/lib.rs
- tooling/lsp/src/modules.rs
- tooling/lsp/src/requests/code_action.rs
- tooling/lsp/src/requests/code_action/tests.rs
- tooling/lsp/src/requests/completion/auto_import.rs
- tooling/lsp/src/requests/mod.rs
- tooling/lsp/src/types.rs
- tooling/lsp/src/visibility.rs
Part of #1579
There are many code actions we could support, but the most useful ones are importing unknown identifiers or fully-qualifying them. This is what this PR is about.
Also thanks to VS Code that it notices that if you request code action on an error, it actually requests code actions for that error span... so it seems like the two are connected, but they are not! And it works just fine :-)
Also fixes a bug I found in "go to definition" when there was no definition to resolve to (precisely the case this code action works on).
Note that in Rust Analyzer it shows as "Qualify [name]" or "Import [name]" and if there are multiple possibilities, a popup shows up letting you choose which one. I wanted to do the same, but looking at the server trace for Rust Analyzer I see each code …
> feat: LSP code actions to import or qualify unresolved paths

- compiler/noirc_errors/src/reporter.rs
- compiler/noirc_frontend/src/hir/resolution/errors.rs
- compiler/noirc_frontend/src/hir/type_check/errors.rs
- compiler/noirc_frontend/src/parser/errors.rs
- tooling/lsp/src/notifications/mod.rs
Browsing the LSP docs I found out that diagnostics can have tags, like "unnecessary" or "deprecated". I thought it would be nice to use those.
Before:
After:
None
Check one:
> feat: LSP diagnostics now have "unnecessary" and "deprecated" tags

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- docs/docs/noir/standard_library/meta/expr.md
- noir_stdlib/src/meta/expr.nr
- test_programs/noir_test_success/comptime_expr/src/main.nr
> feat: add `Expr::as_assert_eq`

- compiler/noirc_evaluator/src/brillig/mod.rs
- compiler/noirc_evaluator/src/ssa.rs
Resolves 
Small change which adds tracking for how long brillig gen takes to the debug logs.
Check one:
> chore: add a span to track timing of brillig gen

- aztec_macros/src/utils/ast_utils.rs
- compiler/noirc_frontend/src/ast/statement.rs
- compiler/noirc_frontend/src/debug/mod.rs
- compiler/noirc_frontend/src/hir/comptime/hir_to_display_ast.rs
- compiler/noirc_frontend/src/parser/parser.rs
Resolves 
We have this nice helper function to construct `StatementKind:Let`s in the parser but we don't use it anywhere else. This PR reworks this helper function so we can use it in more places.
Check one:
> chore: use `new_let` more widely

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- test_programs/compile_success_empty/comptime_str_as_bytes/Nargo.toml
- test_programs/compile_success_empty/comptime_str_as_bytes/src/main.nr
Resolves 
This PR implements converting a string to a byte array in comptime, something very useful for function signatures in aztec-nr
Check one:
> feat: implement `str_as_bytes` in the `comptime` interpreter

- .github/workflows/release.yml
Resolves 
I noticed that the commits for the release PR is still set up to be authored by Kev. I've replaced this with the noirwhal account.
Check one:
> chore: update git user for release PRs

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
Resolves 
Applies some suggestions from the PR review for `str_as_bytes` in the comptime interpreter
Check one:
> chore: Cleanup str_as_bytes

- tooling/lsp/src/lib.rs
- tooling/lsp/src/notifications/mod.rs
- tooling/lsp/src/requests/mod.rs
I noticed that currently LSP will only produce diagnostics for the file you save. That's not very convenient, as if for example you make a change to a function signature that breaks someone using it, you won't find out unless you go to that other file and save it (but how do you know which file is it?) My guess is that you'd use `nargo` on the command line to find out.
Now when a package is type-checked, all errors are reported, regardless of whether they match the file that was saved. I believe this will speed up developing with Nargo! (it was also slowing me down when trying out new warnings or errors)
I thought implementing this was going to be straight-forward (just start reporting errors in all files) but there's a catch: if a file had errors but doesn't have errors anymore, we still …
> feat: LSP diagnostics for all package files

- compiler/noirc_frontend/src/hir/comptime/value.rs
Resolves #5899
For debugging purposes, when you `println` a quoted value, some token values aren't expanded, making it a bit harder to understand what's going on.
Now interned expressions are shown in `Quoted` values.
This program:
```rust
fn main() {
comptime
{
let n = quote { [1, 2, 3] }.as_expr().unwrap();
let q = quote { $n };
println(q);
}
}
```
Used to print:
```
quote { (expr) }
```
Now it prints: 
```
quote { [1, 2, 3] }
```
None.
Check one:
> feat: better println for Quoted

- compiler/noirc_evaluator/src/errors.rs
- compiler/noirc_frontend/src/hir/resolution/errors.rs
The `NestedSlice` error is unclear when there is only one slice:
```bash
error: Nested slices are not supported
┌─ /Users/michaelklein/Coding/noir/two_tag/src/main.nr:31:12
│
31 │     rules: [[Field]; N],
│            ------------ Try to use a constant sized array instead
```
Rephrases the `NestedSlice` error message to make it more clear that slices within arrays or other slices are disallowed.
Check one:
> chore: make nested slice error more clear for `[[T]; N]` case

- compiler/noirc_evaluator/src/ssa.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
- compiler/noirc_evaluator/src/ssa/checks/check_for_underconstrained_values.rs
- compiler/noirc_evaluator/src/ssa/ir/function.rs
- compiler/noirc_evaluator/src/ssa/ir/map.rs
- compiler/noirc_evaluator/src/ssa/opt/inlining.rs
- compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
- compiler/noirc_evaluator/src/ssa/opt/mod.rs
- compiler/noirc_evaluator/src/ssa/opt/normalize_value_ids.rs
SSA can be difficult to debug manually, particularly for very large files. Even when comparing two sources side by side it can be hard to find exactly where they differ since one optimization difference earlier on can affect where ValueIds start in every function afterward.
This PR adds a pass to normalize ids in an SSA program - restarting from v0 after every SSA pass instead of continuing from the previous end. The goal of this is to be able to take two SSA programs and easily diff them to find out where they start differing.
E.g. using this on two files containing the final SSA from https://github.com/noir-lang/noir/issues/5771 in both failing and passing versions, it is clear that they differ in exactly one ValueId in one instruction.
This new pass is only run when `--show-ssa` is …
> chore: Add pass to normalize Ids in SSA

- compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
Working towards #4535 
Small optimization found while working in mem2reg. Now that we have a small per function state we can see which stores/loads that are leftover can be removed. 
A place we are potentially missing stores that can be removed is in return blocks. If we have a store inside of a return block that is not loaded from inside that block, we can safely remove that store (given it is not a reference param). 
Check one:
> feat(perf): Remove last store in return block if last load is before that store

- compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
…
Resolves 
We're currently performing a `x == 1` equality and then constraining the result to be `1` when dealing with boolean values in brillig. This PR updates the codegen to just act on `x` directly.
Check one:
> feat: remove equality operation on boolean constraints against constants

- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- tooling/nargo_cli/src/cli/lsp_cmd.rs
Resolves #5904
I found out that writing to the error stream when connected to the LSP client actually sends that output to the LSP output window ("Noir Language Server") in our case so I chose to do that for comptime println/print. Advantages:
- No more crashing of the LSP server on comptime println
- If you know it goes to that output you can actually see the output without having to go to a terminal to run that code, so debugging comptime will be pretty fast now
- (if you don't know the output goes there, it's fine too: at least the LSP server doesn't crash 😄)
Though the original issue was about using sockets to communicate with the LSP client, I think we won't need that after all if comptime println was the only issue (and I think most LSP servers use stdin/stdout for communication …
> fix: prevent comptime println from crashing LSP

- compiler/noirc_frontend/src/elaborator/comptime.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- tooling/lsp/src/modules.rs
- tooling/lsp/src/requests/code_action/import_or_qualify.rs
- tooling/lsp/src/requests/completion.rs
- tooling/lsp/src/requests/completion/auto_import.rs
- tooling/lsp/src/requests/completion/tests.rs
- tooling/lsp/src/visibility.rs
Resolves #5879
Uses the existing visibility check instead of just considering private items to never be visible.
None.
Check one:
> feat: LSP will now suggest private items if they are visible

- aztec_macros/src/utils/ast_utils.rs
- compiler/noirc_driver/src/lib.rs
- compiler/noirc_errors/src/position.rs
- compiler/noirc_frontend/src/elaborator/comptime.rs
- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/types.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir_def/function.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_frontend/src/lexer/lexer.rs
- compiler/noirc_frontend/src/lexer/token.rs
Resolves #5903
Now the compiler will check that attribute function callbacks have at least one argument, that that argument's type matches the corresponding type, and that remaining arguments also match the types given.
Also previously errors on these callbacks were shown on the function that had the attribute, instead of on the attribute, likely because attributes didn't have a Span attached to them: this PR adds that too.
The error message is still a bit strange because if you have code like this:
```rust
#[attr]
fn foo() {}
fn attr() {}
fn main() {}
```
You get this:
```
error: Expected 0 arguments, but 1 was provided
┌─ src/main.nr:1:3
│
1 │ #[attr]
│   ---- Too many arguments
```
which kind of makes sense, because 1 implicit argument was provided but 0 are expected in the callback, …
> feat: check argument count and types on attribute function callback

- compiler/noirc_frontend/src/hir/comptime/value.rs
- compiler/noirc_frontend/src/tests.rs
Resolves #5916
I think there might be other `Value`s that we could convert into tokens, like `String`, but I didn't want to handle those in this PR (should it be `Str` or `RawStr`? etc.). And it's possible that we only need this special logic for integers anyway.
Check one:
> feat: unquote some value as tokens, not as unquote markers

- compiler/noirc_frontend/src/elaborator/comptime.rs
- compiler/noirc_frontend/src/hir/comptime/errors.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- compiler/noirc_frontend/src/hir/mod.rs
- compiler/noirc_frontend/src/tests.rs
- docs/docs/noir/concepts/comptime.md
- test_programs/compile_success_empty/unquote_struct/Nargo.toml
- test_programs/compile_success_empty/unquote_struct/src/main.nr
Resolves https://github.com/noir-lang/noir/issues/5913
Allows inserting new structs and impls into the program from comptime attributes.
Inserting new structs wasn't allowed originally since functions wouldn't be able to refer to them in their signature. This use case isn't needed for aztec currently so I'm adding this feature now and we can look into expanding it later. See https://github.com/noir-lang/noir/issues/5926
Check one:
> feat: Allow inserting new structs and into programs from attributes

- compiler/noirc_frontend/src/elaborator/comptime.rs
Resolves https://github.com/noir-lang/noir/issues/5915
We were just missing a quick check after running attributes. Now their output will be shown when the `--debug-comptime-in-file` flag is used
Check one:
> fix: Support debug comptime flag for attributes

- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
- compiler/noirc_frontend/src/hir/comptime/value.rs
- docs/docs/noir/standard_library/fmtstr.md
- docs/docs/noir/standard_library/meta/fmtstr.md
- noir_stdlib/src/meta/format_string.nr
- noir_stdlib/src/meta/mod.nr
- test_programs/compile_success_empty/comptime_fmt_strings/src/main.nr
- test_programs/compile_success_empty/unquote_struct/src/main.nr
- tooling/lsp/src/requests/completion/tests.rs
Resolves #5899
Resolves #5914
Two things here:
1. When interpolating quotes values inside a format string, we do that without producing the `quote {` and `}` parts, which is likely what a user would expect (similar to unquoting those values).
2. In order to create identifiers (or any piece of code in general) by joining severa quoted values you can use format strings together with the new `fmtstr::contents` method, which returns a `Quoted` value with the string contents (that is, without the leading and trailing double quotes).
I originally thought about a method like `fmtstr::as_identifier` that would try to parse the string contents as an identifier (maybe an `Ident`, or maybe a `Path`), returning `Option<Quoted>` and `None` in case it couldn't be parsed to that. But I think in general …
> feat: add `fmtstr::contents`

- compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
Optimizes bounds checks
Check one:
> feat: Only check array bounds in brillig if index is unsafe

- compiler/noirc_frontend/src/hir/comptime/errors.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- docs/docs/noir/standard_library/meta/struct_def.md
- noir_stdlib/src/meta/struct_def.nr
- test_programs/compile_success_empty/comptime_type_definition/src/main.nr
Resolves https://github.com/noir-lang/noir/issues/5911
Adds a function to set the fields on a struct type
Hyper-specific error messages can be fun. Here's the error issued when one of the field names isn't a valid identifier:
```
error: Quoted value in index 1 of this slice is not a valid field name
┌─ src/main.nr:25:18
│
25 │     s.set_fields(fields);
│                  ------ `quote { foo bar }` is not a valid field name for `set_fields`
│
```
Check one:
> feat: Add `StructDefinition::set_fields`

- compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
Partially resolves #4535 
Replaces https://github.com/noir-lang/noir/pull/5865
When we see a load we mark the address of that load as being a known value of the load result. When we reach a store instuction, if that store value has a known value which is equal to the address of the store we can remove that store. 
We also check whether the last instruction was an `inc_rc` or a `dec_rc`. If it was we do not remove the store.
Check one:
> feat(perf): Remove known store values that equal the store address in mem2reg

- compiler/noirc_frontend/src/elaborator/comptime.rs
- test_programs/compile_success_empty/comptime_module/src/main.nr
- tooling/lsp/src/requests/completion/builtins.rs
Resolves https://github.com/noir-lang/noir/issues/5875#issuecomment-2331698684
Check one:
> fix: always place module attribute generated items inside module

- compiler/noirc_frontend/src/hir/comptime/errors.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- docs/docs/noir/standard_library/meta/function_def.md
- noir_stdlib/src/meta/function_def.nr
Part of #5874
This is fun 😄 
I'll add similar methods to `StructDefinition` and `Module` in follow-up PRs.
Check one:
> feat: add `FunctionDefinition::add_attribute`

- compiler/noirc_frontend/src/elaborator/lints.rs
- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
- compiler/noirc_frontend/src/parser/mod.rs
- compiler/noirc_frontend/src/parser/parser.rs
- compiler/noirc_frontend/src/parser/parser/function.rs
- compiler/noirc_frontend/src/parser/parser/visibility.rs
- docs/docs/noir/standard_library/meta/function_def.md
- noir_stdlib/src/meta/function_def.nr
- test_programs/compile_success_empty/comptime_function_definition/src/main.nr
Resolves #5902
There's a catch: if you pass `quote { hello world }` to the method, it doesn't crash. The reason is that when we parse the visibility, if it's not `pub` or one of the other non-private visibilities, we simply assume it's private (in regular code then would come a type or `{` and that's where it would fail to parse). I wanted to error in this case but couldn't:
1. One idea I had was to check if we get a non-empty tokens stream. If that's the case and we don't get a private visibility, it's an error. Well, that worked, but I didn't know how to easily create a `ParserError` for that.
2. Another idea is to have a specific parser to parse this or EOF... but I tried a choice with `TokenKind::Token(Token::EOF)` and when it was EOF, it said it was expecting EOF (kind of confusing). …
> feat: add `FunctionDef::set_return_visibility`

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
- docs/docs/noir/standard_library/meta/struct_def.md
- noir_stdlib/src/meta/struct_def.nr
- test_programs/compile_success_empty/attributes_struct/src/main.nr
Resolves #5874
I originally wanted to test this by adding `abi(...)` to a struct and seeing that it errors if that struct appears in a signature but is outside of a contract, but... function parameters are type-checked before that (I think). So another way to test this is to also have `has_named_attribute`, so I added that too.
Side note: maybe adding an attribute to a function/struct should eventually invoke the associated function, if there's any, but we can probably try to do that in a separate PR, and only if really needed.
Check one:
> feat: add `StructDefinition::add_attribute` and `has_named_attribute`

- .gitattributes
Resolves 
Once https://github.com/github-linguist/linguist/pull/7021 has been deployed to github's internal systems we should have the Noir code in this repository highlighted with our own grammar so this override will be unnecessary.
Check one:
> chore: remove override to use rust syntax highlighting

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir/comptime/value.rs
- docs/docs/noir/standard_library/meta/typ.md
- noir_stdlib/src/meta/typ.nr
- test_programs/compile_success_empty/comptime_type/src/main.nr
Resolves https://github.com/noir-lang/noir/issues/5873
Adds a metaprogramming function to create new type variables. Vaguely useful sometimes for impl searches to get the value of other types used in the impl search.
Check one:
> feat: Add `std::meta::typ::fresh_type_variable`

- tooling/lsp/src/requests/completion.rs
- tooling/lsp/src/requests/completion/completion_items.rs
- tooling/lsp/src/requests/completion/tests.rs
While working with Rust I noticed that if you type a field name or a method name and there's a `self` variable, those fields and methods are suggested without you having to explicitly write `self`. I think that's useful as you sometimes forget about the self prefix, or just because you end up typing less.
This PR implements that.
Check one:
> feat: LSP now suggests self fields and methods

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- docs/docs/noir/standard_library/meta/struct_def.md
- noir_stdlib/src/meta/struct_def.nr
- test_programs/compile_success_empty/comptime_struct_definition/src/main.nr
Resolves https://github.com/noir-lang/noir/issues/5958
Adds `StructDefinition::name`
Check one:
> feat: Add `StructDefinition::name`

- compiler/noirc_frontend/src/hir/comptime/errors.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- docs/docs/noir/standard_library/meta/struct_def.md
- noir_stdlib/src/meta/struct_def.nr
- test_programs/compile_success_empty/comptime_struct_definition/src/main.nr
Resolves https://github.com/noir-lang/noir/issues/5957
Adds a generic to an existing struct.
Due to the same reasoning in https://github.com/noir-lang/noir/issues/5926, existing code referring to these structs won't see the generics on them. For now I've documented to try to avoid this use case.
Check one:
> feat: Add `StructDefinition::add_generic`

- compiler/noirc_frontend/src/ast/mod.rs
- compiler/noirc_frontend/src/ast/visitor.rs
- tooling/lsp/src/requests/completion.rs
- tooling/lsp/src/requests/completion/builtins.rs
- tooling/lsp/src/requests/completion/completion_items.rs
- tooling/lsp/src/requests/completion/kinds.rs
- tooling/lsp/src/requests/completion/tests.rs
While working a lot with attributes lately I thought it would be nice if we had autocompletion there too.
Built-in attributes are suggested (I don't know if I got them all right, I don't know which attributes are allowed on structs) and also "function attributes" (we need to give this a name) are suggested if their first argument type matches that of the item the annotation is on (and with auto-import, we effectively get all annotations available to be placed on a function/struct/module).
If we add new attributes we'll have to remember to update the LSP code. But... I think this might be rare, so it might be fine to have to remember this. Also eventually if would be nice if all attributes had an associated function (even if it's a built-in one) and then we wouldn't need special code for …
> feat: LSP autocompletion for attributes

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- docs/docs/noir/standard_library/meta/function_def.md
- noir_stdlib/src/meta/function_def.nr
- test_programs/compile_success_empty/comptime_function_definition/src/main.nr
…constrained`
Resolves #5954
Check one:
> feat: add `FunctionDefinition` methods `is_unconstrained` and `set_unconstrained`

- noir_stdlib/src/cmp.nr
- test_programs/execution_success/derive/src/main.nr
While playing around with the derive attribute I noticed `derive(Eq)` fails to compile for an empty struct.
Fixes the above.
Check one:
> fix: let `derive(Eq)` work for empty structs

- compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
- test_programs/compile_success_empty/references_aliasing/src/main.nr
Partially https://github.com/noir-lang/noir/pull/5925#issuecomment-2332383904 and benefits other post mem2reg function cleanup work https://github.com/noir-lang/noir/pull/5925. Want to add some more aliasing cases.
Works towards making the alias testing surrounding mem2reg more robust.
I have added a mem2reg unit test where the code is storing to an alias inside of a loop. This triggered a failure that has been fixed in this PR. I also confirmed that this unit test would have caught the error triggered by #5935 in https://github.com/AztecProtocol/aztec-packages/pull/8378. 
We have a simple post-mem2reg process that operates over the final mem2reg state to determine if there are any stores that were missed that can be removed. The check currently does not look at whether the store we are …
> fix(mem2reg): Handle aliases in function last store cleanup and additional alias unit test

- noir_stdlib/src/lib.nr
- noir_stdlib/src/meta/op.nr
- noir_stdlib/src/panic.nr
- noir_stdlib/src/prelude.nr
Resolves #5849
Adds a `panic` method exactly as proposed in #5849 , and uses it in a couple of places where `panic` would have been useful to have.
Is it okay in `std::panic::panic`? Where should we document this? (maybe in a new `panic.md` file, or somewhere else?)
Check one:
> feat: add a `panic` method to the stdlib

- tooling/lsp/src/requests/document_symbol.rs
- tooling/lsp/test_programs/document_symbol/src/main.nr
While working with the standard library I noticed Document Symbol didn't work with primitive impls.
If you have this:
```rust
impl i32 {
fn foo() {}
}
```
then pressing command+shift+o on VS Code didn't show `impl i32` nor `foo()`. I think when I coded this logic I didn't know you could have impls for non-named types. This PR fixes that.
Check one:
> fix: LSP document symbol didn't work for primitive impls

- compiler/noirc_driver/src/lib.rs
- compiler/noirc_frontend/src/graph/mod.rs
- tooling/lsp/src/modules.rs
- tooling/lsp/src/notifications/mod.rs
- tooling/lsp/src/requests/hover.rs
- tooling/lsp/src/requests/mod.rs
- tooling/lsp/src/requests/profile_run.rs
- tooling/lsp/src/requests/test_run.rs
- tooling/lsp/src/requests/tests.rs
- tooling/nargo/src/workspace.rs
- tooling/nargo_cli/src/cli/check_cmd.rs
- tooling/nargo_cli/src/cli/compile_cmd.rs
- tooling/nargo_cli/src/cli/export_cmd.rs
- tooling/nargo_cli/src/cli/fmt_cmd.rs
- tooling/nargo_cli/src/cli/test_cmd.rs
`nargo test` doesn't work in the standard library, and LSP gives lots of (incorrect) errors when opening the standard library.
The main issue is that when you run `nargo` against the standard library, a copy of it is also loaded as the standard library. Then we get duplicate definitions, etc.
I tried several things to solve this and one that worked and ended up making a bit of sense is having a crate be the root and the standard library at the same time.
Now with this PR we can run `nargo test`, LSP works well, and you can even run tests directly from the editor, which could speed up the stdlib development.
1. 7 warnings still remain in the standard library (all unused functions) but I'd like to solve that in a separate PR.
2. If this gets merged we could eventually change CI to compile …
> feat: let `nargo` and LSP work well in the stdlib

- noir_stdlib/src/hash/poseidon/bn254/consts.nr
- noir_stdlib/src/hash/poseidon/mod.nr
- noir_stdlib/src/meta/mod.nr
Two functions were unused, another one two but it was kind of a test so I marked it as such.
After this 4 "unused" functions remain, but solving those is a bit more challenging so I'm leaving that for a separate PR.
Check one:
> chore: remove 3 unused functions warnings in the stdlib

- noir_stdlib/src/collections/bounded_vec.nr
- test_programs/noir_test_success/bounded_vec/src/main.nr
Part of #5797
This PR copies the docs from the `.md` file to the `.nr` file.
I'll be sending one PR per `.md` file. It looks like they are 36 in total so it will take some time to port all the docs, but not that much. And this way reviewing these PRs will be more manageable.
For now examples are copied inline into the `.nr` file. Eventually we could maybe have `nargo test` run or at least type-check these example
Check one:
> chore: document BoundedVec

- compiler/noirc_frontend/src/monomorphization/errors.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
Resolves 
Adds an error during monomorphization if any comptime functions fall through the cracks and aren't executed at compile-time.
Check one:
> fix: Error when comptime functions are used in runtime code

- acvm-repo/acvm/tests/solver.rs
Resolves the keccak256_injective test being flakey
Makes the keccak256_injective test not flakey.
Check one:
> fix: Restrict keccak256_injective test input to 8 bits

- compiler/noirc_frontend/src/elaborator/comptime.rs
- compiler/noirc_frontend/src/elaborator/expressions.rs
- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/elaborator/statements.rs
- compiler/noirc_frontend/src/hir/resolution/errors.rs
- compiler/noirc_frontend/src/tests.rs
- noir_stdlib/src/append.nr
- noir_stdlib/src/meta/expr.nr
- noir_stdlib/src/meta/op.nr
- test_programs/compile_failure/quote_at_runtime/Nargo.toml
- test_programs/compile_failure/quote_at_runtime/src/main.nr
- test_programs/compile_success_empty/attributes_struct/src/main.nr
- test_programs/compile_success_empty/comptime_function_definition/src/main.nr
- test_programs/compile_success_empty/comptime_global_using_trait/Nargo.toml
- test_programs/compile_success_empty/comptime_global_using_trait/src/main.nr
- test_programs/compile_success_empty/comptime_module/src/main.nr
- test_programs/compile_success_empty/comptime_module/src/separate_module.nr
- test_programs/compile_success_empty/inject_context_attribute/src/main.nr
Resolves 
Fixes a few small issues:
- Error when `quote` is used in runtime code
- Had to update some stdlib code for this
- This could maybe be an issue in the future for something like `impl Append for Quoted` which relies on this. These impl methods have to be comptime now which we currently allow even though the parent trait says nothing about it. At least with https://github.com/noir-lang/noir/pull/5976 we'd get an error if one of these accidentally sneaks into runtime code.
- `self.in_comptime_context()` wasn't being tracked accurately in the case of attributes and globals where the function context would only be of length 2 due to there being no outer function. I changed the check to make it more direct instead of relying on indirect changes.
- Comptime globals weren't evaluated in …
> fix: Error when `quote` is used in runtime code

- compiler/noirc_frontend/src/ast/visitor.rs
- tooling/lsp/src/requests/completion/builtins.rs
- tooling/lsp/src/requests/completion/completion_items.rs
- tooling/lsp/src/requests/completion/tests.rs
I noticed LSP didn't suggest trait attributes... because these weren't visited. I also noticed when an attribute related to a function was suggested, but the function only had one argument, the parentheses were included in the suggestion but they aren't needed.
Fixes the above problems.
Check one:
> fix: suggest trait attributes in LSP

- compiler/noirc_frontend/src/elaborator/types.rs
- compiler/noirc_frontend/src/hir/resolution/errors.rs
- compiler/noirc_frontend/src/monomorphization/errors.rs
- compiler/noirc_frontend/src/monomorphization/mod.rs
- compiler/noirc_frontend/src/tests.rs
- noir_stdlib/src/meta/expr.nr
- noir_stdlib/src/meta/format_string.nr
- noir_stdlib/src/meta/function_def.nr
- noir_stdlib/src/meta/module.nr
- noir_stdlib/src/meta/quoted.nr
- noir_stdlib/src/meta/struct_def.nr
- noir_stdlib/src/meta/trait_constraint.nr
- noir_stdlib/src/meta/trait_def.nr
- noir_stdlib/src/meta/trait_impl.nr
- noir_stdlib/src/meta/typ.nr
- noir_stdlib/src/meta/typed_expr.nr
- noir_stdlib/src/meta/unresolved_type.nr
- test_programs/compile_success_empty/comptime_fmt_strings/src/main.nr
- test_programs/compile_success_empty/comptime_function_definition/src/main.nr
Resolves https://github.com/noir-lang/noir/issues/5983
Errors when a comptime-only type is used in runtime code.
Currently this is just the various quoted types but in the future would also include user-defined `comptime` structs.
Check one:
> fix: Error when comptime types are used in runtime code

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- docs/docs/noir/standard_library/meta/typed_expr.md
- noir_stdlib/src/meta/typed_expr.nr
- test_programs/compile_success_empty/comptime_typed_expr/Nargo.toml
- test_programs/compile_success_empty/comptime_typed_expr/src/main.nr
> feat: add `TypedExpr::get_type`

- tooling/lsp/src/requests/completion/completion_items.rs
- tooling/lsp/src/requests/completion/tests.rs
Just a tiny thing: when functions are suggested, Rust Analyzer shows the full function signature above the documentation (this is a completion item's `detail` property). It's useful because in the list the signature is usually trimmed.
Before:
After:
Also includes a bunch of small refactors to make it easier to test that something is a function completion item regardless of whether it ends up being a snippet completion or not, whether it triggers a command, etc.
Check one:
> feat: LSP completion function detail

- compiler/noirc_frontend/src/elaborator/patterns.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/hir/comptime/value.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- test_programs/compile_success_empty/comptime_globals_regression/Nargo.toml
- test_programs/compile_success_empty/comptime_globals_regression/src/main.nr
Resolves https://github.com/noir-lang/noir/issues/5991
Fixes two issues:
1. The original linked issue where elaborating a function early would cause any globals to be "locked in" in a sense.
2. The fact that we were never actually mutating underlying values in the interpreter.
Check one:
> fix: Fix using lazily elaborated comptime globals

- compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_slice_ops.rs
- compiler/noirc_evaluator/src/brillig/brillig_ir.rs
- compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs
- compiler/noirc_evaluator/src/brillig/brillig_ir/procedures/mod.rs
- compiler/noirc_evaluator/src/brillig/brillig_ir/procedures/prepare_vector_insert.rs
- compiler/noirc_evaluator/src/brillig/brillig_ir/procedures/prepare_vector_push.rs
- compiler/noirc_evaluator/src/brillig/brillig_ir/procedures/vector_pop.rs
- compiler/noirc_evaluator/src/brillig/brillig_ir/procedures/vector_remove.rs
- compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
Calling the same slice operation more than once won't duplicate the bytecode anymore, will just jump to it.
Check one:
> feat: Extract brillig slice ops to reusable procedures

- aztec_macros/src/utils/errors.rs
I wrote `contract { ... }` in a file and it told me to go somewhere that doesn't exist (it redirects me to the main docs page).
Updates the link to one that I think is correct.
Check one:
> fix: help link was outdated

- compiler/noirc_frontend/src/elaborator/statements.rs
- compiler/noirc_frontend/src/hir/resolution/errors.rs
Resolves https://github.com/noir-lang/noir/issues/5982
Issues an error when mutating comptime globals in a non-comptime context. Previously we either allowed the code if the method is unused, or panicked during monomorphization.
Check one:
> fix: Error when mutating comptime variables in non-comptime code

- .github/scripts/cargo-binstall-install.sh
- .github/scripts/command-check.sh
- compiler/wasm/scripts/install_wasm-pack.sh
Resolves 
This PR just avoids us having multiple ways to install `cargo-binstall` so everything goes through `cargo-binstall-install.sh`
Check one:
> chore: single install script for cargo-binstall

- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_frontend/src/hir_def/types/arithmetic.rs
- test_programs/compile_success_empty/arithmetic_generics_move_constant_terms/Nargo.toml
- test_programs/compile_success_empty/arithmetic_generics_move_constant_terms/src/main.nr
Resolves https://github.com/noir-lang/noir/issues/6006
Previously we were failing for constraints like `a + 3 = b + 1` when we could instead move the constant terms to one side: `a + 2 = b` then solve with `b := a + 2`.
Check one:
> fix: Try to move constant terms to one side for arithmetic generics

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- docs/docs/noir/standard_library/meta/module.md
- noir_stdlib/src/meta/module.nr
- test_programs/compile_success_empty/comptime_module/src/main.nr
Resolves https://github.com/noir-lang/noir/issues/6015
Adds a method to `Module` to retrieve each struct defined in the module
Check one:
> feat: Add `Module::structs`

- compiler/noirc_frontend/src/lexer/token.rs
Fixes an issue with how string tokens are displayed. Previously they wouldn't include the double quotes, and special characters weren't escaped.
Check one:
> fix: Correctly print string tokens

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
- docs/docs/noir/standard_library/meta/function_def.md
- docs/docs/noir/standard_library/meta/module.md
- docs/docs/noir/standard_library/meta/op.md
- docs/docs/noir/standard_library/meta/quoted.md
- docs/docs/noir/standard_library/meta/struct_def.md
- docs/docs/noir/standard_library/meta/typ.md
- noir_stdlib/src/meta/function_def.nr
- noir_stdlib/src/meta/module.nr
- noir_stdlib/src/meta/op.nr
- noir_stdlib/src/meta/quoted.nr
- noir_stdlib/src/meta/struct_def.nr
- noir_stdlib/src/meta/typ.nr
Resolves https://github.com/noir-lang/noir/issues/6012
Implements Hash and Eq for a number of comptime types, including a few that had Eq but not Hash.
Check one:
> feat: impl Hash and Eq on more comptime types

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
- compiler/noirc_frontend/src/hir/def_map/module_data.rs
- compiler/noirc_frontend/src/lexer/token.rs
- noir_stdlib/src/meta/function_def.nr
- noir_stdlib/src/meta/module.nr
- noir_stdlib/src/meta/struct_def.nr
- test_programs/compile_success_empty/attributes_struct/src/main.nr
- test_programs/compile_success_empty/comptime_function_definition/src/main.nr
- test_programs/compile_success_empty/comptime_module/src/main.nr
- test_programs/compile_success_empty/inject_context_attribute/src/main.nr
Resolves #6009
Also made it a bit more efficient.
Check one:
> feat: let `has_named_attribute` work for built-in attributes

- tooling/lsp/src/requests/completion.rs
- tooling/lsp/src/requests/completion/tests.rs
While working with attributes I found that auto-import didn't work well if a module has an attribute on it.
Before:
After:
Check one:
> fix: use module name as line after which we'll insert auto-import

- tooling/nargo_cli/src/cli/execute_cmd.rs
Resolves 
This PR updates `nargo execute` so that if no name is specified then the witness is written to a file named after the noir package.
Check one:
> feat: default to outputting witness with file named after package

- docs/docs/noir/concepts/data_types/arrays.md
- noir_stdlib/src/array/mod.nr
> chore: document array methods

- compiler/noirc_frontend/src/elaborator/expressions.rs
- compiler/noirc_frontend/src/hir/type_check/errors.rs
- compiler/noirc_frontend/src/tests.rs
Resolves #5721
Today I bumped into this bug so I thought about trying to fix it.
Check one:
> fix: error on `&mut x` when `x` is not mutable

- compiler/noirc_frontend/src/ast/visitor.rs
- compiler/noirc_frontend/src/elaborator/mod.rs
- compiler/noirc_frontend/src/hir_def/function.rs
- compiler/noirc_frontend/src/lexer/lexer.rs
- compiler/noirc_frontend/src/lexer/token.rs
- tooling/lsp/src/requests/completion.rs
I saw spellcheck complain about this. Until that I didn't realize there was a typo 😄 
Check one:
> chore: rename CustomAtrribute to CustomAttribute

- aztec_macros/src/utils/parse_utils.rs
- compiler/noirc_frontend/src/ast/expression.rs
- compiler/noirc_frontend/src/ast/visitor.rs
- compiler/noirc_frontend/src/elaborator/expressions.rs
- compiler/noirc_frontend/src/hir/comptime/value.rs
- compiler/noirc_frontend/src/hir/resolution/errors.rs
- compiler/noirc_frontend/src/parser/parser.rs
- compiler/noirc_frontend/src/parser/parser/primitives.rs
- test_programs/compile_success_empty/comptime_parse_statement_as_expression/'
- test_programs/compile_success_empty/comptime_parse_statement_as_expression/Nargo.toml
- test_programs/compile_success_empty/comptime_parse_statement_as_expression/src/main.nr
- tooling/lsp/src/requests/inlay_hint.rs
- tooling/nargo_fmt/src/rewrite/expr.rs
Resolves https://github.com/noir-lang/noir/issues/6036
Grego was having an issue from some macros where some code was taken from a block and later put in the rhs of a `let` statement: `let _ = $former_block_statement`. Since this expression originated from a block statement though, it is a `Token::InternedStatement` and not a valid expression.
I've updated the parser to accept interned statements in an expression position, and we just later validate that they're either `StatementKind::Expression` or `StatementKind::Semi` nodes.
Check one:
> fix: Parse a statement as an expression

- compiler/noirc_frontend/src/elaborator/expressions.rs
- compiler/noirc_frontend/src/tests.rs
I noticed that after #6037 got merged, doing `foo(&mut undefined)` when `undefined` isn't declared crashes the compiler.
I wonder if instead of using a dummy ID we should use `Option` to represent undefined variables (not for this PR, just for a later larger refactor).
Check one:
> fix: prevent check_can_mutate crashing on undefined variable

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- test_programs/compile_success_empty/comptime_to_radix/Nargo.toml
- test_programs/compile_success_empty/comptime_to_radix/src/main.nr
Resolves #6042
This PR implements `to_be_radix` in the comptime interpreter by reusing our impl for `to_le_radix`.
Check one:
> feat: implement `to_be_radix` in the comptime interpreter

- tooling/lsp/src/lib.rs
- tooling/lsp/src/notifications/mod.rs
- tooling/lsp/src/requests/mod.rs
- tooling/lsp/src/requests/references.rs
- tooling/lsp/src/requests/rename.rs
LSP is still relatively slow and there are many optimization opportunities we can use.
This is just the second commit of #6045
Check one:
> feat: faster LSP by caching file managers

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- docs/docs/noir/standard_library/meta/expr.md
- noir_stdlib/src/meta/expr.nr
- test_programs/noir_test_success/comptime_expr/src/main.nr
> feat: add `Expr::as_lambda`

- compiler/noirc_frontend/src/elaborator/comptime.rs
- compiler/noirc_frontend/src/elaborator/scope.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter.rs
- compiler/noirc_frontend/src/hir/comptime/value.rs
- compiler/noirc_frontend/src/lexer/token.rs
- docs/docs/noir/concepts/comptime.md
- test_programs/compile_success_empty/use_callers_scope/Nargo.toml
- test_programs/compile_success_empty/use_callers_scope/src/main.nr
We have many methods now such as `Quoted::as_type` or `Quoted::as_trait_constraint` which resolve items in the current scope. It is useful to change the scope these are resolved in but somewhat impractical to do what we did with `Expression::resolve` and have them all take module parameters.
I've added `#[use_callers_scope]` which can be added to a comptime function to change the scope any builtins resolve in to that of the caller. This also works in helper functions and closures.
Check one:
> feat(metaprogramming): Add `#[use_callers_scope]`

- tooling/lsp/src/requests/completion.rs
- tooling/lsp/src/requests/completion/tests.rs
LSP autocompletion didn't trigger in some cases.
Makes LSP autocompletion work when typing a dot but in the next line an l-value assignment follows. In that case the current line and the line that follows are parsed as a single assignment to an l-value and we must complete in the middle of that entire expression.
Also adds a missing `follow_bindings()` that caused some of these cases to not work.
Check one:
> fix: let LSP suggest fields and methods in LValue chains

- compiler/noirc_frontend/src/ast/structure.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- compiler/noirc_frontend/src/hir/def_map/module_data.rs
- compiler/noirc_frontend/src/locations.rs
- compiler/noirc_frontend/src/parser/parser/structs.rs
- compiler/noirc_frontend/src/tests.rs
- compiler/noirc_frontend/src/usage_tracker.rs
- docs/docs/noir/concepts/data_types/structs.md
- noir_stdlib/src/bigint.nr
- noir_stdlib/src/cmp.nr
- noir_stdlib/src/collections/bounded_vec.nr
- noir_stdlib/src/collections/map.nr
- noir_stdlib/src/collections/umap.nr
- noir_stdlib/src/collections/vec.nr
- noir_stdlib/src/ec/consts/te.nr
- noir_stdlib/src/ec/montcurve.nr
- noir_stdlib/src/ec/swcurve.nr
- noir_stdlib/src/ec/tecurve.nr
- noir_stdlib/src/embedded_curve_ops.nr
- noir_stdlib/src/hash/mimc.nr
- noir_stdlib/src/hash/mod.nr
- noir_stdlib/src/hash/poseidon/mod.nr
- noir_stdlib/src/hash/poseidon2.nr
- noir_stdlib/src/meta/mod.nr
- noir_stdlib/src/meta/op.nr
- noir_stdlib/src/option.nr
- noir_stdlib/src/test.nr
- noir_stdlib/src/uint128.nr
- tooling/lsp/src/requests/code_action/import_or_qualify.rs
- tooling/lsp/src/requests/completion/tests.rs
Part of #4515
Part of #4775
Allows marking structs as pub or pub(crate). Also will now report unused structs.
Let me know if some of the structs I marked as `pub` shouldn't actually be `pub`. I didn't mark some as pub, I think only the ones used for tests.
Check one:
> feat: allow visibility modifiers in struct definitions

- compiler/noirc_frontend/src/ast/traits.rs
- compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
- compiler/noirc_frontend/src/hir/def_map/module_data.rs
- compiler/noirc_frontend/src/parser/parser/traits.rs
- compiler/noirc_frontend/src/tests.rs
- compiler/noirc_frontend/src/usage_tracker.rs
- docs/docs/noir/concepts/traits.md
- noir_stdlib/src/append.nr
- noir_stdlib/src/bigint.nr
- noir_stdlib/src/cmp.nr
- noir_stdlib/src/convert.nr
- noir_stdlib/src/default.nr
- noir_stdlib/src/hash/mod.nr
- noir_stdlib/src/meta/ctstring.nr
- noir_stdlib/src/ops/arith.nr
- noir_stdlib/src/ops/bit.nr
Part of #4515
Fixes #4775
Traits can now be marked as `pub` or `pub(crate)`, and a warning will happen if a trait is unused.
Check one:
> feat: visibility for traits

- compiler/noirc_frontend/src/hir/comptime/hir_to_display_ast.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- tooling/lsp/src/requests/inlay_hint.rs
Resolves https://github.com/noir-lang/noir/issues/6052
Check one:
> chore: remove unused TypeVariableKind::Constant

- compiler/noirc_frontend/src/elaborator/traits.rs
- compiler/noirc_frontend/src/hir/type_check/errors.rs
- compiler/noirc_frontend/src/parser/errors.rs
- compiler/noirc_frontend/src/parser/parser/traits.rs
- tooling/lsp/src/requests/code_action/implement_missing_members.rs
- tooling/lsp/src/requests/completion.rs
- tooling/lsp/src/trait_impl_method_stub_generator.rs
Fixes #5717
In a previous PR we started allowing `unconstrained` and `comptime` in trait impls. But two things remained:
1. Defining an `unconstrained` trait impl method would produce a warning.
2. We should error if a trait method is unconstrained but the trait impl method is not, or the other way around.
This PR will also include "unconstrained" in trait imp method stubs in LSP.
I initially also errored if there's a mismatch in `comptime`, but that's probably not good as we have some implementation of `Append` be comptime and some not. This made me wonder what's the purpose of `comptime` in functions, if non-comptime functions can also be interpreted.
Check one:
> feat: check unconstrained trait impl method matches

- compiler/noirc_frontend/src/ast/statement.rs
- compiler/noirc_frontend/src/parser/parser.rs
Resolves https://github.com/noir-lang/noir/issues/6060
We had `ExpressionKind::Interned` as always requiring a semicolon to separate two expressions, but this isn't true for all expression types (blocks, if). We can't check what is interned so I just always made the semicolon optional.
Check one:
> fix: Be more lenient with semicolons on interned expressions

- compiler/noirc_evaluator/src/ssa/ir/function_inserter.rs
- compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs
- compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
- test_programs/compile_success_no_bug/databus_mapping_regression/Nargo.toml
- test_programs/compile_success_no_bug/databus_mapping_regression/src/main.nr
Resolves #5705
We were using an inserter in flattening but forgot to update the databus
Check one:
> fix: Update databus in flattening

- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
- compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
- compiler/noirc_frontend/src/hir/comptime/value.rs
- test_programs/compile_failure/comptime_parse_all_tokens/Nargo.toml
- test_programs/compile_failure/comptime_parse_all_tokens/src/main.nr
Resolves https://github.com/noir-lang/noir/issues/5803
Resolves https://github.com/noir-lang/noir/issues/6059
If we ever had a token stream with a subset of valid input we'd parse just that subset instead of erroring that the full input doesn't parse.
We don't have EOF tokens in token streams so I used the `end()` primitive instead.
Check one:
> fix: Always parse all tokens from quoted token streams

- compiler/noirc_errors/src/lib.rs
- compiler/noirc_errors/src/reporter.rs
- compiler/noirc_evaluator/src/errors.rs
- compiler/noirc_frontend/src/hir/comptime/errors.rs
- compiler/noirc_frontend/src/monomorphization/errors.rs
- tooling/nargo/src/errors.rs
Resolves https://github.com/noir-lang/noir/issues/6065
Ensures the stack trace used in assertion failure messages at comptime have the correct ordering. The old scheme was grouping together each location by file and ordering by line number so I changed it to just show filenames like we do in SSA when there's a failing assert.
Check one:
> fix: Correct stack trace order in comptime assertion failures

- compiler/noirc_frontend/src/elaborator/types.rs
- test_programs/compile_failure/global_without_a_type_used_as_array_length/Nargo.toml
- test_programs/compile_failure/global_without_a_type_used_as_array_length/src/main.nr
Resolves #6046
Another case of an unhandled`DefinitionId::dummy()`.
Check one:
> fix: don't crash on untyped global used as array length

- compiler/noirc_frontend/src/elaborator/expressions.rs
- compiler/noirc_frontend/src/elaborator/types.rs
- compiler/noirc_frontend/src/hir_def/types.rs
- compiler/noirc_frontend/src/tests.rs
- test_programs/compile_success_empty/numeric_generics_explicit/src/main.nr
Resolves https://github.com/noir-lang/noir/issues/6081
Resolves https://github.com/noir-lang/noir/issues/6082
Now that we check kinds explicitly we were erroring if globals weren't already `u32` yet leading to a lot of existing code needing to be changed.
If we change the exact equality to a unification check we can instead infer the globals need to be a `u32` without requiring user code to be changed.
This PR is still breaking since there were causes we didn't catch before of invalid kinds being used in array lengths, e.g. `fn foo<let N: u8>(a: [Field; N])` in one of our unit tests.
Check one:
> fix!: Infer globals to be u32 when used in a type
