noir-lang/noir

compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/hir/comptime/interpreter.rs
noir_stdlib/src/meta/mod.nr
test_programs/compile_success_empty/macro_result_type/Nargo.toml
test_programs/compile_success_empty/macro_result_type/src/main.nr
test_programs/compile_success_empty/macro_result_type/t.rs

Resolves an issue from @asterite on slack
When we type check a macro call we don't know the actual type so we return a fresh type variable.
When we later execute this code at comptime we do know the type, so we should unify the type variable then, potentially catching any inconsistencies. This also makes the value of the type variable known (during evaluation, not type checking!) as in the new test case.
Also fixed an issue where you couldn't call a method as a macro directly and needed an extra `unquote!` call.
Check one:

fix: Unify macro result type with actual type

---

tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/auto_import.rs
tooling/lsp/src/requests/completion/completion_items.rs
tooling/lsp/src/requests/completion/tests.rs

There was no way to get completions for macro calls, so the user had to complete, go back and add the `!`. 
Now if something can be a macro call it's suggested too.
A special case is done for `unquote!`: it's only suggested as a macro call, never as a function call.
Check one:

feat: let LSP suggest macro calls too

---

aztec_macros/src/transforms/note_interface.rs
aztec_macros/src/transforms/storage.rs
aztec_macros/src/utils/parse_utils.rs
compiler/noirc_frontend/src/ast/expression.rs
compiler/noirc_frontend/src/ast/statement.rs
compiler/noirc_frontend/src/ast/visitor.rs
compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/elaborator/patterns.rs
compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/hir/comptime/interpreter.rs
compiler/noirc_frontend/src/hir/comptime/value.rs
compiler/noirc_frontend/src/hir/type_check/generics.rs
compiler/noirc_frontend/src/hir_def/expr.rs
compiler/noirc_frontend/src/hir_def/types.rs
compiler/noirc_frontend/src/node_interner.rs
compiler/noirc_frontend/src/parser/parser.rs
compiler/noirc_frontend/src/parser/parser/path.rs
compiler/noirc_frontend/src/parser/parser/types.rs
test_programs/compile_success_empty/type_path/Nargo.toml
test_programs/compile_success_empty/type_path/src/main.nr
tooling/lsp/src/requests/inlay_hint.rs
tooling/nargo_fmt/src/rewrite/expr.rs

Resolves https://github.com/noir-lang/noir/issues/6078
Adds the ability to do `Type::method` where `Type` is a primitive type or interned type. Other named types should already be supported by existing paths.
I also made a small update to `lookup_method` to support looking up methods without a `self` parameter to allow for us to possibly have something like `Field::static_method()` in the future, although we have no functions like this in the stdlib currently.
Check one:

feat: Implement type paths

---

tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/completion_items.rs
tooling/lsp/src/requests/completion/tests.rs

When in non-comptime code, when suggesting a function that returns `Quoted` it should never be suggested as a non-macro call.
Check one:

feat: (LSP) if in runtime code, always suggest functions that return Quoted as macro calls

---

compiler/noirc_frontend/src/elaborator/types.rs
tooling/lsp/src/requests/hover.rs

I noticed Rust Analyzer shows a `const` value, so I figured we could do the same thing with simple globals.
This is only done for globals with "simple" types (bools, strings, integers, arrays, tuples). It can be useful to avoid having to go to the global definition to check the value, in case it's needed.
Check one:

feat: (LSP) show global value on hover

---

compiler/noirc_frontend/src/elaborator/traits.rs
compiler/noirc_frontend/src/tests.rs

Resolves #6100 
It seems that #5156 has resulted in problems in unifying numeric generics in trait impl methods.
Check one:

fix: preserve generic kind on trait methods

---

compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
tooling/noir_js/scripts/compile_test_programs.sh
tooling/noir_js/test/node/execute.test.ts
tooling/noir_js/test/noir_compiled_examples/databus/Nargo.toml
tooling/noir_js/test/noir_compiled_examples/databus/src/main.nr
tooling/noirc_abi/src/lib.rs

Resolves #5715
This PR picks up from @guipublic's work on #6074 to enable decoding databus return values in `noirc_abi`. I've added a test to show this working
Check one:

fix: decode databus return values

---

tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/tests.rs
tooling/lsp/src/requests/mod.rs

`$var` should be suggested inside `quote { ... }`: only local variables should be suggested.
Check one:

feat: (LSP) suggest $vars inside `quote { ... }`

---

tooling/noir_js/test/node/execute.test.ts

Resolves 
It looks like we picked up an extra copy of some tests in this file at some point (most likely a sync)
Check one:

chore: delete duplicated test

---

compiler/noirc_frontend/src/parser/parser/path.rs
tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/tests.rs

Autocompletion for `TypePath` didn't exist because it's a recently added feature.
Offers suggestions when you type, for example, `u32::`. For this I had to allow parsing a `TypePath` without any ident following it (like we do for paths), still producing a parsing error.
Also fixes the issue that built-in types weren't suggest in any position (only where types are expected, like function argument types, but now that you can call static methods on these types it makes sense to always offer them):
Check one:

feat: LSP autocompletion for `TypePath`

---

compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
compiler/noirc_evaluator/src/ssa/ir/function.rs
compiler/noirc_evaluator/src/ssa/opt/array_set.rs
compiler/noirc_evaluator/src/ssa/opt/rc.rs

Resolves 
Part of general effort to reduce Brillig bytecode sizes.
We currently only perform the array set last uses optimization on ACIR functions. This makes sense as the pass only looks only last uses in a single block. We can start to expand the last uses opt to encompass more than just ACIR functions and make it aware of the last array set of an array across blocks. This is quite complex though so this PR currently just attempts to look at the return block of Brillig functions and see the effects.
Check one:

feat(perf): Allow array set last uses optimization in return block of Brillig functions

---

compiler/noirc_evaluator/src/ssa/opt/die.rs
test_programs/execution_success/brillig_constant_reference_regression/Nargo.toml
test_programs/execution_success/brillig_constant_reference_regression/Prover.toml
test_programs/execution_success/brillig_constant_reference_regression/src/main.nr

Resolves #6121
Die was not considering constants as used. As a result, the reference counter operations on constants were removed.
This created a correctness issue.
Check one:

fix: Consider constants as used values to keep their rc ops

---

compiler/noirc_frontend/src/ast/mod.rs
test_programs/compile_success_empty/parenthesized_expression_in_array_length/Nargo.toml
test_programs/compile_success_empty/parenthesized_expression_in_array_length/src/main.nr

We were missing handling parenthesized expressions in `UnresolvedTypeExpression::from_expr_helper`
Fixes the above issue.
Check one:

fix: handle parenthesized expressions in array length

---

compiler/noirc_frontend/src/ast/statement.rs
compiler/noirc_frontend/src/ast/visitor.rs
compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
compiler/noirc_frontend/src/node_interner.rs
tooling/lsp/src/requests/code_action.rs
tooling/lsp/src/requests/code_action/remove_unused_import.rs
tooling/lsp/src/requests/code_action/tests.rs
tooling/lsp/src/requests/completion.rs

Part of #1579
This implements another commonly used feature: "remove unused import/s".
This is when the entire `use` item is removed:
This is when part of the `use` item is removed:
This is when "Remove all the unused imports" is chosen with a selection range:
It works exactly the same as Rust Analyzer:
1. You get a "Remove unused import", "Remove unused imports" or "Remove the entire `use` item" on each `use` item that has unused import(s)
2. You also get a "Remove all the unused imports" code action. This will remove all unused imports in the current selection.
I need to clarify 2 because it's something I learned while coding this: a code action is suggested in the selection you have (the selection is the cursor in case there's no selection, though VSCode would sometimes use the current …

feat: (LSP) remove unused imports

---

noir_stdlib/src/hash/keccak.nr

Resolves 
This PR removes the `temp` array created when swapping the endianness of the `block_bytes` array and just swaps the values in place. This removes some unnecessary reads/writes from brillig.
Check one:

feat: swap endianness in-place in keccak implementation

---

noir_stdlib/src/hash/keccak.nr

Resolves 
This PR simplifies the keccak256 implementation by removing a branch which we'll never actually go down.
When converting from bytes to u64 limbs we have an if statement with the condition `if (limb_start + WORD_SIZE > max_blocks_length)`.
We can show that the maximum value of the LHS is exactly `max_blocks_length` and so this branch will never trigger (however brillig cannot know that so it's preserved in the bytecode).
```
num_limbs * WORD_SIZE = max_blocks * LIMBS_PER_BLOCK * WORD_SIZE
= (max_blocks_length / BLOCK_SIZE_IN_BYTES) * LIMBS_PER_BLOCK * WORD_SIZE // using definition of `max_blocks`
= max_blocks_length  * (LIMBS_PER_BLOCK * WORD_SIZE / BLOCK_SIZE_IN_BYTES) 
= max_blocks_length  * (LIMBS_PER_BLOCK / LIMBS_PER_BLOCK) // using definition of `LIMBS_PER_BLOCK` 
= …
```

feat: remove unnecessary branching in keccak impl

---

compiler/noirc_frontend/src/hir/comptime/display.rs

Just a small thing: we have a token pretty printer and it was printing a sequence of tokens like `+ =` like "+ =" instead of not putting a space between them.
Fixes the above.
I'd add a test, but I get a linker error when trying to run tests on the frontend project since a few weeks/months (I think it's because of chumsky, not sure!). In any case this behavior is not critical, it's just helpful for outputting quoted values at compile-time.
Check one:

fix: let token pretty printer handle `+=` and similar token sequences

---

noir_stdlib/src/hash/sha256.nr

Resolves 
We can optimize the sha256 implementation rolling the if-statement condition into the values being constrained manually. This allows us to have a single constraint rather than 2 with opposite predicates.
Check one:

feat: optimize constraints in sha256

---

compiler/noirc_frontend/src/ast/statement.rs
compiler/noirc_frontend/src/ast/visitor.rs
compiler/noirc_frontend/src/debug/mod.rs
compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/elaborator/patterns.rs
compiler/noirc_frontend/src/elaborator/statements.rs
compiler/noirc_frontend/src/hir/comptime/hir_to_display_ast.rs
compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
compiler/noirc_frontend/src/lexer/token.rs
compiler/noirc_frontend/src/parser/parser.rs
compiler/noirc_frontend/src/parser/parser/traits.rs
compiler/noirc_frontend/src/tests/unused_items.rs
tooling/lsp/src/requests/completion/builtins.rs
tooling/lsp/src/requests/completion/completion_items.rs
tooling/lsp/src/requests/completion/tests.rs

Resolves #6148
This is only for `let`, which is what we currently need.
Should this be documented? I guess so, but I couldn't find where in our docs we explain `let`. (on the other hand we have `deprecated` but it seems to also be undocumented)
Check one:

feat: allow silencing an unused variable defined via `let`

---

compiler/noirc_evaluator/src/brillig/brillig_gen/constant_allocation.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/variable_liveness.rs

Avoids the runtime cost of reinitializing constants inside loops.
Check one:

feat: Hoist constant allocation outside of loops

---

noir_stdlib/src/ec/consts/te.nr
noir_stdlib/src/ec/tecurve.nr
noir_stdlib/src/hash/mimc.nr
noir_stdlib/src/hash/sha256.nr
noir_stdlib/src/schnorr.nr
noir_stdlib/src/sha256.nr
noir_stdlib/src/sha512.nr

Resolves 
This PR deprecates various items in the stdlib. Where an external library is fulfilling the role of a stdlib function we point off to that external lib.
Check one:

chore: deprecate various items in stdlib

---

compiler/noirc_frontend/src/ast/visitor.rs
compiler/noirc_frontend/src/elaborator/comptime.rs
compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
compiler/noirc_frontend/src/hir/def_map/module_data.rs
compiler/noirc_frontend/src/parser/mod.rs
compiler/noirc_frontend/src/parser/parser.rs
compiler/noirc_frontend/src/tests.rs
compiler/noirc_frontend/src/tests/unused_items.rs
compiler/noirc_frontend/src/usage_tracker.rs
docs/docs/noir/concepts/globals.md
noir_stdlib/src/field/bn254.nr
tooling/nargo_fmt/src/visitor/item.rs

Part of #4515
I left all of the stdlib globals as private except one which needed to be `pub(crate)` to avoid a warning. I don't know if some of these globals should actually be public.
Check one:

feat: visibility for globals

---

compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_intrinsic.rs

Avoids creating an extra constant for to radix when we already have a variable for it.
Check one:

fix: Pass radix directly to the blackbox

---

noir_stdlib/src/hash/mod.nr

These are functions that we need to import directly in `aztec-nr`, from discussion with @vezenovm there doesn't seem to be a good reason to not export them.

feat: expose `derived_generators` and `pedersen_commitment_with_separator` from the stdlib

---

compiler/noirc_evaluator/src/ssa/ir/instruction/cast.rs

Resolves 
Small optimization I noticed while working on other tasks.
We currently simplify when casting to a field or an unsigned type. We can also simplify when casting to a signed type. This is an initial version that is quite conservative in the simplification. If we we have a constant that is below `2^(bit_size-1)` when casting to a signed type we return the constant with the new signed type. I also added the case of signed -> field as this can be the same as going unsigned -> field. 
Check one:

feat(ssa): Simplify signed casts

---

compiler/noirc_frontend/src/hir/def_collector/errors.rs
compiler/noirc_frontend/src/lib.rs

Resolves 
This PR follows up on #6087 by removing the error variant which is provided for `aztec_macros` to return.
Check one:

chore: remove `DefCollectorErrorKind::MacroError`

---

compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
test_programs/compile_success_empty/comptime_module/src/main.nr

The above functions would return items in different order depending on the run.
Check one:

feat: let `Module::functions` and `Module::structs` return them in definition order

---

compiler/noirc_evaluator/src/ssa/ir/printer.rs
compiler/noirc_evaluator/src/ssa/opt/die.rs

Part of general effort to reduce Brillig bytecode sizes
An array can be borrowed without being mutated. We code gen inc_rc instructions quite pessimistically on every borrow or reassignment of an array. If we know that the array is never mutated, it should be safe to remove these inc_rc instructions. 
During DIE we now track all inc_rc instructions in a block and if that array is never used in an array set or a store, we mark its inc_rc instruction for removal.
Check one:

feat(perf): Remove inc_rc instructions for arrays which are never mutably borrowed

---

compiler/noirc_evaluator/src/ssa/opt/die.rs

Part of general effort to reduce Brillig bytecode sizes. 
We often have patterns like such (example from `brillig_rc_regression_6123`): 
```
brillig fn main f0 {
b0():
inc_rc [Field 0, Field 0]
inc_rc [Field 0, Field 0]
inc_rc [Field 0, Field 0]
inc_rc [Field 0, Field 0]
inc_rc [Field 0, Field 0]
v4 = allocate
store [Field 0, Field 0] at v4
v5 = allocate
store u32 0 at v5
inc_rc [Field 0, Field 0]
v7 = allocate
store [Field 0, Field 0] at v7
inc_rc [Field 0, Field 0]
inc_rc [Field 0, Field 0]
jmp b1(u32 0)
```
It is usually due to each impl method that mutably borrows self placing inc RCs on the internal arrays of the struct for which it is implementing the method. Without any instructions in between these `inc_rc` instructions, we can safely collapse the inc_rcs into a single one.
The …

feat(perf): Remove redundant inc rc without instructions between

---

compiler/noirc_evaluator/src/ssa.rs

Part of general effort to reduce Brillig bytecode sizes.
While working other SSA opts, I noticed in a couple tests we had simplified blocks down to only their terminator, but those empty blocks still existed in our final SSA. It looks to be due to previous passes, and specifically DIE simplifying down to an empty block which was not caught in the initial CFG simplification. 
I pushed this PR wanted to see how much of a benefit simplifying at the end would be across our tests. It is a whole extra SSA pass, however, of all our passes, simplify CFG shouldn't be very heavy and wouldn't be too bad to run again if it provides decent benefits. 
Check one:

feat(perf): Simplify the cfg after DIE

---

compiler/noirc_evaluator/src/ssa/opt/remove_enable_side_effects.rs

Resolves 
PR described in comment in code.
Check one:

feat: skip `remove_enable_side_effects` pass on brillig functions

---

compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs
compiler/noirc_evaluator/src/ssa/opt/array_set.rs

Resolves 
Fix for failure in the `test_barycentric` of the `blob` lib in `noir-protocol-circuits`. The test now passes when Brillig's `MAX_STACK_SIZE` is increased to 32k. 
I included an additional map to track whether an array set result was used as a value in another array set. We can not allow for inner nested array sets to be mutable across blocks as the full nested array may be used in another block. We could add additional logic to check whether the parent array set will be marked mutable, but this seems overly complex for little benefit at the moment as this fix showed a quite small size regression.
Check one:

fix(ssa): Check if result of array set is used in value of another array set

---

compiler/noirc_evaluator/src/ssa/ir/cfg.rs
compiler/noirc_evaluator/src/ssa/opt/simplify_cfg.rs

Resolves 
Inspired by https://github.com/noir-lang/noir/pull/6184, I noticed that after simplifying a constant jmpif we wouldn't inline the block following the inlined block into the first block, as an example consider the SSA
```
After Dead Instruction Elimination:
brillig fn main f0 {
b0(v0: Field, v1: Field):
constrain v0 == Field 1
constrain v1 == Field 0
jmpif u1 0 then: b2, else: b1
b2():
v8 = add v0, Field 1
jmp b3(v0, v8)
b3(v2: Field, v3: Field):
v9 = add v0, Field 1
constrain v2 == v9
constrain v3 == v0
constrain v0 == Field 1
constrain v1 == Field 0
return 
b1():
v7 = add v0, Field 1
jmp b3(v7, v0)
}
```
Here we can see that we never enter `b2`, instead going `b0 -> b1 -> b3`. However when the simplify_cfg pass looks at the predecessors of `b3` it sees both `b1` **and `b2`** …

feat: remove orphaned blocks from cfg to improve `simplify_cfg` pass.

---

compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs
compiler/noirc_evaluator/src/ssa/opt/array_set.rs

Resolves 
The `analyze_last_uses` method was starting to have multiple different state variables. This PR just creates a separate context struct for analyze the mutable array sets across a block in hopes of making it simpler to add future additions.
Check one:

chore(refactor): Array set optimization context struct for analysis

---

compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs
compiler/noirc_evaluator/src/ssa/ir/instruction.rs

Part of general effort to reduce Brillig bytecode sizes
We often times (usually when working with nested arrays) run into patterns where we fetch an inner nested array dynamically, array set a different array in the nested array, and the reset the other unchanged nested array at the same index. These array sets can be optimized out.
Here is an example of what happens on master in SSA. Looking at `nested_array_dynamic` with `--force-brillig`. Inside `b14` you will see the following:
```
v114 = array_get v110, index v113
v115 = add v113, u32 1
v116 = add v113, u32 2
v117 = array_get v110, index v116
v118 = array_set v110, index v113, value v114
```
After this PR `v118 = array_set v110, index v113, value v114` will simplify to `v110`. If `v114` is unused anywhere else in the function (which …

feat(perf): Optimize array set from get

---

compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs

chore: revert mistaken stack size change

---

compiler/noirc_frontend/src/elaborator/patterns.rs
compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/hir/comptime/interpreter.rs
compiler/noirc_frontend/src/hir_def/expr.rs
compiler/noirc_frontend/src/monomorphization/mod.rs
compiler/noirc_frontend/src/tests/imports.rs
compiler/noirc_frontend/src/tests/visibility.rs

We were producing "this item is private" errors twice.
The problem was that the code looked up a path twice, and errored each time it found an error in that lookup.
Now the code still looks up the path twice, but only errors once (if the first lookup succeeds, we report the optional error of that lookup, otherwise we do the same with the second one).
Also applied some refactors (made a tuple return value its own struct, and made an enum variant use a struct instead of a tuple too).
This fixes the issue but we are still doing two Path lookups here, which means there's an optimization opportunity to only do the lookup once. But this can be done in a separate PR.
Check one:

fix: don't warn twice when referring to private item

---

compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
compiler/noirc_frontend/src/locations.rs
tooling/lsp/src/requests/code_action/import_or_qualify.rs
tooling/lsp/src/requests/completion/tests.rs

Even though we started tracking visibility for many items, this visibility wasn't registered for auto-import.
I was thinking that maybe registering things for auto-import isn't necessary. We could traverse all types and all functions in all modules and check if they match... but maybe that'll be much slower (right now we group all items by name so maybe iterating that is faster). In any case we could explore that other option later on.
Check one:

fix: add missing visibility for auto-import names

---

compiler/noirc_frontend/src/parser/parser/expression.rs
compiler/noirc_frontend/src/parser/parser/pattern.rs

Resolves #6215
If we get '=' instead of ':' we error but continue parsing the field value.
None.
Check one:

feat: recover from '=' instead of ':' in struct constructor/pattern

---

compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/tests/unused_items.rs

No issue as found while working on other tasks.
Compile `nested_array_dynamic` and you will see a warning the `Bar` is never constructed. However, `Bar` is an internal field to the `Foo` struct which is provided as inputs and is thus constructed.
When marking a parameter type as used we also go over all of the struct fields to account for any nested structs.
Check one:

fix(frontend): Do not warn when a nested struct is provided as input to main

---

tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/tests.rs

Struct fields now have visibility, but LSP still suggests all fields regardless of their visibility.
Hides non-accessible struct fields using the same logic the compiler applies to check if a struct field is visible.
None.
Check one:

feat: don't suggest private struct fields in LSP

---

compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
compiler/noirc_frontend/src/tests/unused_items.rs

fix: don't warn on unuse global if it has an abi annotation

---

tooling/lsp/src/lib.rs

Before this PR, LSP would crash for assumed workspaces (when we can't find a Nargo.toml) or when there were errors in the Nargo.toml.
Now LSP doesn't crash in the above cases:
- for assumed workspaces we don't crash (we used to not crash but I made some changes in the past that broke this)
- for errors in Nargo.toml we now output to STDERR, so you can see the error in the output. This is what Rust Analyzer does, except that they also have a "rust-analyzer" thing at the bottom that becomes yellow when there's an error... I didn't implement this (it probably requires some code on the extension side) but I think if something doesn't work you'd check the logs or ask, and it's worse if it crashes.
Check one:

feat: don't crash LSP when there are errors resolving the workspace

---

compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/elaborator/statements.rs
compiler/noirc_frontend/src/hir/resolution/visibility.rs
compiler/noirc_frontend/src/hir_def/types.rs
compiler/noirc_frontend/src/tests/visibility.rs
noir_stdlib/src/ec/montcurve.nr
noir_stdlib/src/ec/swcurve.nr
noir_stdlib/src/ec/tecurve.nr
noir_stdlib/src/hash/sha256.nr
noir_stdlib/src/option.nr
tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/tests.rs

Part of #4515
Apparently in #6179 I only made it work for calls like `foo::Bar::baz()` but no checks were done for method calls (where `self` is involved).
This PR now warns when calling private or `pub(crate)` methods, either on structs or primitive types, when they are not accessible from the current module.
We also now don't suggest non-accessible methods from LSP.
I also removed an unused global that was introduced some time ago.
Check one:

fix: visibility for impl methods

---

acvm-repo/bn254_blackbox_solver/src/poseidon2.rs
tooling/nargo_cli/tests/stdlib-props.rs

Related to #6141 
Adds a fuzz test for `poseidon2.nr` comparing the results to [bn254_blackbox_solver::poseidon_hash](https://github.com/noir-lang/noir/blob/70cbeb4322a0b11c1c167ab27bf0408d04fe7b7d/acvm-repo/bn254_blackbox_solver/src/poseidon2.rs#L547), which says it's `"Performs a poseidon hash with a sponge construction equivalent to the one in poseidon2.nr"`
To pass the test the Rust implementation was given a new `is_variable_length` parameter to inform it whether it needs to append an extra 1 like Noir and Berratenberg do. 
The test initially failed:
```console
❯ cargo test -p nargo_cli --test stdlib-props poseidon
test fuzz_poseidon2_equivalence ... FAILED
---- fuzz_poseidon2_equivalence stdout ----
Test failed: assertion failed: `(left == right)` 
left: …
```

feat(test): Fuzz test poseidon2 hash equivalence

---

tooling/nargo_cli/tests/stdlib-props.rs

Related to #6141
Assert that the `PoseidonHasher` calculates the same hash on dynamic input as the `hash_<length>` function we know it has to call.
Check one:

feat(test): Include the PoseidonHasher in the fuzzing

---

acvm-repo/acvm_js/src/lib.rs
compiler/noirc_evaluator/src/ssa/ir/instruction.rs
compiler/noirc_evaluator/src/ssa/ir/instruction/call.rs
compiler/noirc_evaluator/src/ssa/opt/flatten_cfg/capacity_tracker.rs
compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs

Partial fix to https://github.com/noir-lang/noir/issues/5462
This PR doesn't fully fix https://github.com/noir-lang/noir/issues/5462 but allows full compilation of a program without panicking. The test program from #5462 now successfully compiles (due to us being able to remove the inactive branch during inlining)
We still fail to properly handle branches which are conditional on runtime values such as the below:
```
fn main(active: bool) {
let empty_slice: [u8] = &[];
if !active {
let _ = empty_slice.pop_front();
}
}
```
This compiles to the below program
```
Compiled ACIR for main (unoptimized):
func 0
current witness index : 2
private parameters indices : [0]
public parameters indices : []
return value indices : []
BLACKBOX::RANGE [(0)] [ ]
INIT (id: 0, len: 0) 
EXPR [ (-1, _1) 0 ]
MEM …
```

fix: prevent compiler panic when popping from empty slices

---

Cargo.lock
compiler/fm/src/lib.rs
tooling/nargo/Cargo.toml
tooling/nargo/src/lib.rs

Reading all workspace files is slow.
**TL;DR: reading all `.nr` files in the noir-circuits project now takes 10ms instead of 1.5 seconds.**
Using `flamegraph` I noticed reading a workspace files was slow. For example in `noir-contracts` it was taking 1.5 seconds to do that.
The first thing in this PR is using the `walkdir` crate which brings two benefits:
- It reduces the time to 1.3 seconds (not much, but it's something)
- It removes the need for us to reproduce that code and maintain it (we had tests for walking a dir)
Still, 1.3 seconds seemed like too slow. At first I searched if there was alternatives to `std::fs::read_string` but it seems that's the most efficient thing to use. So I created a separate project that essentially did `walkdir` on `noir-contracts`, reading all files and …

feat: optimize reading a workspace's files

---

compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/elaborator/patterns.rs
compiler/noirc_frontend/src/elaborator/statements.rs
compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs

Followup to https://github.com/noir-lang/noir/pull/6282
Some methods in the `Elaborator` received a `global_id: Option<GlobalId>` and a `definition: DefinitionKind` parameter. We found that `Elaborator::elaborate_let` actually created `definition` to carry the same global ID as it was given, so `global_id: Some(id)` and `definition: DefinitionKind::Global(id)` always carried the same value. We added an [assertion](https://github.com/noir-lang/noir/pull/6282/commits/1d2bd36ab5fb38ebab28b8262dbf13f8020ee461) that checked that they are never different.
The next logical step is to remove the possibility of confusion by only carrying the ID in the definition.
Check one:

chore(refactor): Remove optional global_id from methods that can get it from the definition

---

compiler/noirc_errors/src/reporter.rs
tooling/lsp/src/notifications/mod.rs

Errors shown in LSP didn't show the "secondaries" we capture, nor the notes.
Resolves #6272
Now secondaries and notes are shown as details to the primary error, like in Rust Analyzer:
Check one:

feat: show LSP diagnostic related information

---

acvm-repo/acvm/src/compiler/mod.rs
acvm-repo/acvm/src/compiler/transformers/csat.rs
acvm-repo/acvm/src/compiler/transformers/mod.rs
compiler/noirc_driver/src/lib.rs
tooling/nargo_cli/benches/criterion.rs
tooling/nargo_cli/src/cli/mod.rs

Resolves #5560
Rejects an invalid `--expression-value` in the CLI, which would later cause a panic in `acvm::compiler::transformers::csat`. 
An example error message looks like:
```text
error: invalid value '1' for '--expression-width <EXPRESSION_WIDTH>': minimum value is 3
```
The issue suggests that [CSatTransformer::new](https://github.com/noir-lang/noir/blob/ae87d287ab1fae0f999dfd0d1166fbddb927ba97/acvm-repo/acvm/src/compiler/transformers/csat.rs#L24-L27) should return a `Result` explaining the problem it has with `width`, rather than doing an `assert!` (without any message) and crashing the program. I agree, however looking at the chain of calls, none of the half-dozen functions we go through to reach this use `Result`, and the `CSatTransformer` is the only option we have. This …

fix: Reject invalid expression with in CLI parser

---

docs/docs/noir/concepts/data_types/arrays.md
noir_stdlib/src/array/mod.nr

Resolves a private issue sent to me on slack
Array map is a fairly old method written before we had `std::mem::zeroed`. Now that we have zeroed, we can allow mapping empty arrays since we can use `zeroed` to get the filler `U` value for the starting elements.
While I was at it I included a small clarification to `reduce`'s docs that it requires a non-empty array
Check one:

fix: Allow array map on empty arrays

---

compiler/noirc_evaluator/src/ssa/opt/unrolling.rs

Resolves #6192 
We're not actually calling `Function::unroll_loops_iteratively` so we can remove it.
Check one:

chore: remove dead function

---

.github/workflows/test-js-packages.yml

Resolves 
The old repository is no longer maintained so I've updated to point at the new one.
Check one:

chore: update `noir-edwards` repo to point at `noir-lang` org

---

compiler/noirc_frontend/src/parser/parser/global.rs

Without a span, LSP's document symbol crashed.
Replaces a default span with a correct one.
Check one:

fix: mutable global pattern didn't have a span

---

tooling/nargo_fmt/src/formatter/expression.rs

Resolves #4980
In reality the new formatter didn't crash anymore, it just formatted this:
```noir
fn foo() {
let x = 1 // one
+ 2 // two
+ 3; // three
}
```
like this:
```noir
fn foo() {
let x = 1 // one
+ 2 // two
+ 3; // three
}
```
but making it look like the first snippet was easy, so here's that PR :-)
Check one:

fix: (formatter) indent after infix lhs

---

tooling/nargo_fmt/src/formatter/statement.rs

Resolves https://github.com/noir-lang/noir_json_parser/pull/16#issuecomment-2435374508
I thought for "op assign" like `x += 1` there will always come one or two tokens, then `=`, but that's not the case for `>>=` (it's `> >=`).
Check one:

fix: formatter didn't format `>>=` well

---

compiler/noirc_frontend/src/tests.rs
compiler/noirc_frontend/src/tests/metaprogramming.rs

Resolves 
These tests weren't being run because of a missing `mod metaprogramming;`. I've also added a test for a requested feature from another team.
Check one:

chore: run tests in metaprogramming.rs

---

test_programs/compile_success_empty/arithmetic_generics/src/main.nr
test_programs/compile_success_empty/comptime_closures/src/main.nr
test_programs/compile_success_empty/inner_outer_cl/src/main.nr
test_programs/compile_success_empty/use_callers_scope/src/main.nr
test_programs/execution_success/higher_order_functions/src/main.nr
tooling/nargo_fmt/src/chunks.rs
tooling/nargo_fmt/src/formatter/expression.rs
tooling/nargo_fmt/tests/expected/contract.nr

…nt blocks
Not a problem, but rustfmt seems to do the same and it can help reduce some of the code noise.
Maybe this feature is controversial? I didn't find a way to turn it off in rustfmt.
Check one:

feat: let the formatter remove lambda block braces for single-statement blocks

---

compiler/noirc_frontend/src/tests/metaprogramming.rs

…
Resolves 
This PR adds a test to sanity check that we will throw an error on duplicate named functions being injected by macros as reported in https://aztecprotocol.slack.com/archives/C0183F0V42V/p1729855935233669
Check one:

chore: add test to check that duplicate definitions generated from macros throws error

---

noir_stdlib/src/hash/mod.nr

Resolves 
If I turn down the inliner aggressiveness I start getting failures here due to the need for `domain_generator_bytes` to be a constant. This PR adds an attribute to always inline this function.
Check one:

fix: always inline `derive_generators`

---

compiler/noirc_evaluator/src/ssa/opt/array_set.rs

Resolves #6349 
We check that we do not mark arrays mutable which comes from load instructions as that array may be used by multiple values. This is overridden by checking whether we are in the return block, in which case we do mark the array as mutable. This however breaks when we no longer inline everything. I switched the set of arrays from loads to a map of arrays from loads to whether they come from a block parameter.  
Check one:

fix(ssa): Do not mark an array from a parameter mutable

---

Cargo.lock
Cargo.toml
tooling/nargo_cli/Cargo.toml
tooling/nargo_cli/tests/stdlib-tests.rs

Resolves #6349
Added a `test_matrix` around `run_stdlib_tests` to call it with/without forcing Brillig and to try various inlining aggressiveness (min, 0, max).
The syntax to call a specific test still works, but now it runs with all compiler options combinations from the matrix:
```console
❯ cargo test -q -p nargo_cli --test stdlib-tests -- run_stdlib_tests trait_eq::inequality
running 6 tests
[stdlib] Testing collections::bounded_vec::bounded_vec_tests::trait_eq::inequality... ok
[stdlib] 1 test passed
[stdlib] Testing collections::bounded_vec::bounded_vec_tests::trait_eq::inequality... ok
[stdlib] 1 test passed
[stdlib] Testing collections::bounded_vec::bounded_vec_tests::trait_eq::inequality... FAIL
Failed to solve program: 'Failed to solve brillig function'
error: Failed to solve …
```

feat(test): Run test matrix on stdlib tests

---

compiler/noirc_frontend/src/elaborator/scope.rs
compiler/noirc_frontend/src/hir_def/types.rs
compiler/noirc_frontend/src/tests.rs
compiler/noirc_frontend/src/tests/aliases.rs

Resolves https://github.com/noir-lang/noir/issues/6347
We were calling `lookup` only expecting a StructId, so I added another case for a type alias in general.
If the type alias resolves to a non-struct type we still issue an error. E.g. if we had `type Bar = ();`
```
┌─ src/main.nr:8:9
│
8 │     let Bar { inner } = Foo { inner: 42 };
│         ------------- () has no fields to construct it with
│
```
Check one:

fix: allow type aliases in let patterns

---

compiler/noirc_frontend/src/ast/statement.rs
compiler/noirc_frontend/src/parser/parser/use_tree.rs
tooling/lsp/src/lib.rs
tooling/lsp/src/requests/code_action/remove_unused_import.rs
tooling/lsp/src/requests/code_action/tests.rs
tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/auto_import.rs
tooling/lsp/src/requests/completion/tests.rs
tooling/lsp/src/tests.rs

No problem, just makes it easier to avoid having to manually manage use statements.
LSP auto-import will now behave like Rust Analyzer, where if there's a single location we can add a new use statement too, we do it. That way if the user specified multiple use statements, that decision is respected.
There are two more things I'd like to eventually do, as follow-ups, when I have time in-between other tasks:
1. The code action that adds an import will still always insert a new use statement: we also have to teach it to try to insert into an existing use statement
2. To know where a new use statement should go to I made the code compute all segment positions. That should be fast, but of course it will take more time than no time. In LSP completion (and code action) you can tell the client …

feat: LSP auto-import will try to add to existing use statements

---

docs/docs/noir/concepts/comptime.md

Resolves https://github.com/AztecProtocol/dev-rel/issues/405
Check one:

chore: minor tweaks to comptime doc

---

tooling/lsp/src/lib.rs
tooling/lsp/src/requests/code_action.rs
tooling/lsp/src/requests/code_action/import_or_qualify.rs
tooling/lsp/src/requests/code_action/tests.rs
tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/auto_import.rs
tooling/lsp/src/requests/completion/tests.rs
tooling/lsp/src/requests/mod.rs
tooling/lsp/src/tests.rs
tooling/lsp/src/use_segment_positions.rs

Like #6354 but for the import code action.
Tries to extract and reuse all the logic that's used for this in autocompletion, and use it for this code action.
Check one:

feat: let the LSP import code action insert into existing use statements

---

compiler/noirc_frontend/src/hir/comptime/interpreter.rs

Resolves 
Fixes a panic that can occur in comptime code sometimes when calling a function which previously failed to completely resolve. Can't seem to repro it again though.
Check one:

fix: Fix panic in comptime code

---

tooling/nargo_fmt/src/chunks.rs
tooling/nargo_fmt/src/formatter/comments_and_whitespace.rs
tooling/nargo_fmt/src/formatter/expression.rs
tooling/nargo_fmt/src/formatter/module.rs

While coding in Noir I noticed this code:
```noir
mod foo {
mod bar {
}
}
```
ended up being formatted like this:
```noir
mod foo {
mod bar {
}
}
```
It wasn't working well because the code for submodules wasn't reusing a function to format empty blocks. The reason is that I implemented submodules first, then eventually came up with a function to format empty blocks but forgot to use it there.
I also found some other edge cases so I fixed them (an existing test got changed, its formatting is slightly better now).
(This is all minor, but it's nice if things are consistent)
I checked and with this nothing is reformatted in this repo or Aztec-Packages: there are no empty blocks with comments, because that usually happens as you are coding but not in the final state of the code.
Check one:

fix: slightly better formatting of empty blocks with comments

---

compiler/noirc_frontend/src/node_interner.rs
compiler/noirc_frontend/src/tests/traits.rs

Resolves https://github.com/AztecProtocol/aztec-packages/pull/9425#issuecomment-2438553794
When entering a function we were adding assumed traits, and also for parent traits, but we weren't removing parent traits.
I added a test that gives a warning saying "constraint T: Foo" is not needed without this PR (that's how I realized the bug was related to lingering assumed traits).
Check one:

fix: remove assumed parent traits

---

compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
compiler/noirc_frontend/src/node_interner.rs
tooling/lsp/src/modules.rs
tooling/lsp/src/requests/code_action/import_or_qualify.rs
tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/auto_import.rs
tooling/lsp/src/requests/completion/tests.rs
tooling/lsp/src/visibility.rs

While coding a bit in Noir I realized public items in private modules were incorrectly offered by LSP auto-import.
In addition to checking whether an item is accessible from the current module, we now check if that item's parent modules are accessible.
Check one:

fix: LSP auto-import would import public item inside private module

---

compiler/noirc_frontend/src/ast/visitor.rs
tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/completion_items.rs
tooling/lsp/src/requests/completion/kinds.rs
tooling/lsp/src/requests/completion/tests.rs

For some reason I forgot to handle traits in LSP completion.
Check one:

feat: let LSP suggest traits in trait bounds

---

tooling/lsp/src/requests/code_action/import_or_qualify.rs
tooling/lsp/src/requests/completion/auto_import.rs
tooling/lsp/src/requests/completion/tests.rs
tooling/lsp/src/visibility.rs

After #6366, and while working on #6370, I noticed the trait `Add` (and other ops) weren't suggested anymore. The reason is that they are re-exported from a different module, and private in their own module. #6366 didn't take that into account so this PR fixes that.
Check one:

fix: (LSP) check visibility of module that re-exports item, if any

---

tooling/nargo_fmt/src/formatter/expression.rs

fix: (formatter) correctly format quote delimiters

---

compiler/noirc_frontend/src/hir/resolution/errors.rs
compiler/noirc_frontend/src/hir/type_check/errors.rs
tooling/lsp/src/requests/code_action.rs
tooling/lsp/src/requests/code_action/remove_bang_from_call.rs

Resolves #6380 with the bonus
Check one:

feat: suggest removing `!` from macro call that doesn't return Quoted

---

compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_black_box.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_slice_ops.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_control_flow.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_memory.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/procedures/mod.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/procedures/prepare_vector_insert.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/procedures/prepare_vector_push.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/procedures/vector_copy.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/procedures/vector_pop.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/procedures/vector_pop_back.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/procedures/vector_pop_front.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/procedures/vector_remove.rs
tooling/debugger/src/repl.rs

Brillig vectors didn't have capacities, so all operations were O(N) since they required copying the vector.
This PR adds capacities to vectors and uses them in the slice operations to avoid copying when possible.
Unfortunately I can't make an e2e test showcasing a simple program where performance is good thanks to this due to reference counter weirdness:
```noir
unconstrained fn main() {
let mut slice = &[];
for i in 0..10000 {
slice = slice.push_back(i);
}
assert(slice.len() == 10000);
}
```
```
After Array Set Optimizations:
brillig(inline) fn main f0 {
b0():
v1 = allocate
store u32 0 at v1
inc_rc []
v4 = allocate
store [] at v4
jmp b1(u32 0)
b1(v0: u32):
v6 = lt v0, u32 2⁴×625
jmpif v6 then: b3, else: b2
b3():
v8 = load v1
v9 = load v4
v11, v12 = call slice_push_back(v8, v9, v0)
inc_rc …
```

feat: Add capacities to brillig vectors and use them in slice ops

---

tooling/lsp/src/requests/hover.rs
tooling/lsp/test_programs/workspace/two/src/lib.nr

Some things I noticed were missing when hovering over functions, compared to what Rust Analyzer does.
Hovering over a function will now show it's visibility, whether it's comptime/unconstrained, and also show the struct, trait or trait impl it belongs to. Also, numeric generic types previously showed up just as their name, but now they show up with the `let N: ...` syntax.
Check one:

feat: better LSP hover for functions

---

noir_stdlib/src/hash/keccak.nr

Follow-up to #6393
The length of `Vec` can be computed at compile-time, so we can use an array instead of a Vec.
Check one:

chore: use array instead of Vec in keccak256

---

compiler/noirc_frontend/src/tests/traits.rs

Resolves https://github.com/noir-lang/noir/issues/6314
#6314 appears to have been fixed in https://github.com/noir-lang/noir/pull/6325
Check one:

chore: add regression tests for #6314

---

compiler/noirc_frontend/src/hir_def/types.rs
test_programs/compile_failure/cannot_deduce_numeric_generic/Nargo.toml
test_programs/compile_failure/cannot_deduce_numeric_generic/src/main.nr

Resolves #6379
Even though `Kind::Numeric` holds a type, say, `u32`, that type is not the default value that should be used if we can't bind that var.
Check one:

fix: numeric generic doesn't have a default type

---

tooling/nargo_cli/src/cli/info_cmd.rs

Just something I noticed while working on `nargo info`. The `--profile-info` flag is hidden and I am willing to bet largely unused. We can move to the noir-profiler under `tooling/profiler` as it is much more informative and easier to navigate. 
I have removed `--profile-info` from `nargo info` and the subsequent methods related to it. 
I would also like to remove the "Profile" codelens @asterite @TomAFrench. I was trying to use it on `1_mul` and `sha256_regression` and nothing would happen while the other code lens commands worked. 
Check one:

chore(nargo): Remove old profile as part of info cmd

---

compiler/noirc_frontend/src/elaborator/comptime.rs
compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/elaborator/patterns.rs
compiler/noirc_frontend/src/elaborator/scope.rs
compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
compiler/noirc_frontend/src/hir/mod.rs
compiler/noirc_frontend/src/hir/resolution/import.rs
compiler/noirc_frontend/src/hir/resolution/path_resolver.rs
compiler/noirc_frontend/src/node_interner.rs
compiler/noirc_frontend/src/tests.rs
compiler/noirc_frontend/src/tests/turbofish.rs
compiler/noirc_frontend/src/usage_tracker.rs
tooling/lsp/src/attribute_reference_finder.rs
tooling/lsp/src/lib.rs
tooling/lsp/src/notifications/mod.rs
tooling/lsp/src/requests/code_action.rs
tooling/lsp/src/requests/code_action/remove_unused_import.rs
tooling/lsp/src/requests/goto_definition.rs
tooling/lsp/src/requests/hover.rs
tooling/lsp/src/requests/mod.rs

Resolves #4469
Resolves #6311
This PR enables two things:
1. Using type aliases in paths
2. Also allowing turbofish on those aliases
The caveat is that this only works (for now) for aliases that point to a struct (I captured a follow-up issue here: #6398). Making it work for other types is a bit tricky, and will likely require finally rewriting the path lookup logic (it should probably be embedded in `Elaborator`). But I'd like to do that as a separate PR.
Check one:

fix: aliases in path

---

compiler/noirc_frontend/src/lexer/errors.rs
compiler/noirc_frontend/src/lexer/lexer.rs
compiler/noirc_frontend/src/lexer/token.rs
tooling/lsp/src/requests/completion/builtins.rs

Resolves #4676
In reality we were producing an error message for this snippet:
```noir
#[test(should_fail_with("Arrays not equal"))]
fn foo() {}
```
though the error message said that it couldn't find a `test` function. The reason is that the lexer couldn't parse the attribute contents well: it split the attribute contents when `(` and `)` were found and tried to match that to some expected format, but because here we have nested parentheses it didn't work. What I did is try to parse that by checking the first and last parentheses.
I also didn't know you could write `#[test(should_fail)]` so I added that as an LSP autocompletion.
I'm thinking that maybe the attribute contents should be parsed by lexing its contents. With that, we could also keep a nesting counter when `[` and `]` are …

feat: improve malformed test attribute error

---

noir_stdlib/src/field/mod.nr

Resolves https://github.com/AztecProtocol/ab2/issues/11
A byte array is being referred to as `bits` due to some copy-pasting of code.
Check one:

chore: update variable names in stdlib tests to be more correct

---

compiler/noirc_frontend/src/tests/traits.rs

Resolves #6420 
This PR adds a regression test for the issue experienced in https://github.com/noir-lang/noir-edwards/pull/9
Check one:

chore: create a regression test for #6420

---

compiler/noirc_evaluator/src/ssa.rs
compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
test_programs/execution_success/references/src/main.nr

Resolves https://github.com/noir-lang/noir/issues/6443
The `mem2reg` SSA pass eliminates stores that have no use, but as testing with different inliner aggressiveness showed it also eliminated stores into mutable references passed to a function. This is an effect that is expected to be visible outside, after the call. It turns out that `PerFuncContext::is_store_alias_used` _does_ consider the input reference parameters of the function as stopping conditions for removing a store to an address, but it does so only if there is an alias for the address which appears in the input parameters. This wasn't the case, and the removal went ahead. 
I added a method that adds a self-alias to all block parameters if they are reference types and don't already have aliases from the merge of the …

fix(sea): mem2reg to treat block input references as alias

---

compiler/noirc_frontend/src/ast/statement.rs
compiler/noirc_frontend/src/elaborator/path_resolution.rs
compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/tests.rs
compiler/noirc_frontend/src/tests/traits.rs

Code like `struct Foo { x: <Y> }` would crash the compiler.
`<Y>` in a type position is parsed as an incomplete `AsTraitPath` with an empty Path. The reason for this is that it's useful for LSP: if typing inside `Y` we can complete that trait, even though the `as` and the path are missing. However, some code in the Elaborator checks if a path's first name is `Self` without checking first if the path is not empty, leading to a crash. This PR fixes that.
While typing in an editor, if you tried to rename the type `Foo<N>` by deleting "Foo" first, it would lead to crashing the LSP server.
Check one:

fix: don't crash on AsTraitPath with empty path

---

compiler/noirc_frontend/src/hir_def/types.rs
compiler/noirc_frontend/src/tests.rs

Resolves #6438
This doesn't fix the panic that's mentioned [here](https://github.com/zkpassport/noir_rsa/pull/2) though, I'll see if I can find out why that happens.
Check one:

fix: check infix expression is valid in program input

---

tooling/nargo_fmt/src/chunks.rs
tooling/nargo_fmt/src/formatter/buffer.rs
tooling/nargo_fmt/src/formatter/expression.rs
tooling/nargo_fmt/src/formatter/function.rs
tooling/nargo_fmt/src/formatter/statement.rs
tooling/nargo_fmt/tests/expected/parens.nr

While reducing some Noir code to find a bug I noticed that commenting some parts of the code would lead to some newlines being removed, shifting other lines and making debugging things a bit hard.
This PR makes sure that if there are multiple newlines before or after comments in statements, they are respected (well, a maximum of 2, like always).
This also fixes a potential bug where the current line width wasn't correctly adjusted after some trimming operations.
Check one:

fix: let formatter respect newlines between comments

---

examples/codegen_verifier/codegen_verifier.sh
examples/codegen_verifier/src/main.nr

Resolves 
I was debugging a user's issue with the smart contract verifier and needed to be able to run a program with multiple public inputs through this example. I've then modified it to properly split the public inputs string into multiple string to represent each `bytes32`.
Check one:

chore: update example to show how to split public inputs in bash

---

compiler/noirc_evaluator/src/ssa.rs
noir_stdlib/src/hash/poseidon/mod.nr
test_programs/execution_success/eddsa/src/main.nr
tooling/nargo_cli/build.rs

Addresses https://github.com/noir-lang/noir/issues/6441
Adds the `#[inline_always]` attribute to `PoseidonHasher::write`. This way at least we can pass the tests in https://github.com/noir-lang/noir/pull/6429 for `--inliner-aggressiveness 0`, which is what was supposed to be the default value in https://github.com/noir-lang/noir/pull/6378 We still have to exclude the `-Inf` option in the tests.
Looking behind the scenes, many of the functions in the test have inlining costs slightly less than zero, so with -Inf they don't get inlined, but with 0 they do, but that is not enough to make the test pass. An aggressiveness of 22 is enough; as it happens `write` has a cost of 21, and inlining this method does the trick. 
I don't know if it makes sense to add this attribute, but wanted to open a …

fix: Change PoseidonHasher::write to be inline_always

---

compiler/noirc_evaluator/src/ssa/ir/types.rs
compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
compiler/noirc_evaluator/src/ssa/opt/mem2reg/alias_set.rs

Resolves https://github.com/noir-lang/noir/issues/6474
We allow mutable aliasing so all parameters can potentially be mutably aliased. We were over-eager in an optimization previously where we assumed parameters weren't aliased, and thus optimized out loads that were needed in some cases.
I've tried to preserve the optimization while fixing the bug best I could. This check is now type-aware so we assume parameters are possibly aliased with any other parameter of the same type, but a `&mut i32` cannot alias a `&mut Field`. The only caveat is that we can't really handle arrays or reference types containing other references within so for these we revert to the pre-optimization behavior of assuming `AliasSet::unknown()` for all references since these nested references may also reference other …

fix: Treat all parameters as possible aliases of each other

---

docs/docs/how_to/how-to-oracles.md
docs/versioned_docs/version-v0.36.0/how_to/how-to-oracles.md
docs/versioned_docs/version-v0.37.0/how_to/how-to-oracles.md
docs/versioned_docs/version-v0.38.0/how_to/how-to-oracles.md

Fixes broken links
There were some lingering broken links that got merged.
Check one:

fix(docs): Fix broken links in oracles doc

---

compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs

Deduplicates instructions across multiple blocks, mostly for brillig improvements.
Uses a dominator tree to ensure the instruction we're replacing the current with dominates the current block.
This should resolve the duplicate `make_array` instructions in https://github.com/noir-lang/noir/pull/6071
Check one:

feat: Deduplicate instructions across blocks

---

compiler/noirc_evaluator/src/ssa/opt/as_slice_length.rs
compiler/noirc_evaluator/src/ssa/parser.rs
compiler/noirc_evaluator/src/ssa/parser/lexer.rs
compiler/noirc_evaluator/src/ssa/parser/tests.rs

I wanted to add a test for an existing optimization that is untested. While doing so I noticed the SSA parser can't parse slice types and also that some errors were incorrect (there's one `{token}` occurrence that should have been `{found}`).
I want to very slowly add tests for existing optimizations that don't have tests. This is just for one of them, but also includes a bunch of fixes.
Check one:

fix: parse Slice type in SSa

---

compiler/noirc_frontend/src/elaborator/traits.rs
compiler/noirc_frontend/src/tests/unused_items.rs

Resolves https://github.com/noir-lang/noir/issues/6479
This was actually more than just a visibility bug: it could happen that we just elaborated a trait in a nested module, and `local_module` ended up in that nested module; then finding types for where clauses would find them even if they were normally unreachable. For example this code compiled fine:
```noir
mod foo {
pub trait Foo {}
}
pub trait Bar<T>
where
T: Foo, // Here Foo was incorrectly found
{}
```
I wonder if directly setting `local_module` should be forbidden, and instead we should always use `replace_module`.
Check one:

fix: set local_module before elaborating each trait

---

compiler/noirc_evaluator/src/ssa/opt/unrolling.rs

Resolves 
I noticed that when we're unrolling loops we run 2 `mem2reg` passes and a `simplify_cfg` on all functions in the program after every failure. This means that we'll end up doing a lot of redundant work on all the other functions in the program as long as there's a single function which is still having loops unrolled.
This PR changes how we do loop unrolling so that we unroll a single function to completion before we start unrolling the next. This also opens up the opportunity to parallelize this work in future. 
Check one:

feat: avoid unnecessary ssa passes while loop unrolling

---

compiler/noirc_evaluator/src/ssa/parser.rs
compiler/noirc_evaluator/src/ssa/parser/lexer.rs
compiler/noirc_evaluator/src/ssa/parser/tests.rs
compiler/noirc_evaluator/src/ssa/parser/token.rs

SSA parser does not parse negative integer values currently
Found while updating https://github.com/noir-lang/noir/pull/6434
Check one:

chore: Parse negatives in SSA parser

---

compiler/noirc_evaluator/src/ssa/opt/mod.rs

The parser diff appears reversed when an SSA test is incorrect so I swapped the order so that it is more natural.
Before it resembled:
```
- actual line
+ expected line
```
This reverses it to be more like a git diff:
```
- expected line
+ actual line
```
Check one:

chore: Reverse ssa parser diff order

---

compiler/noirc_evaluator/src/ssa/opt/array_set.rs

Resolves #6486 
The PR changes the `array_set` pass to skip Brilling functions completely and remove all code related to `is_brillig_runtime` as well. 
This is undoing the changes made in https://github.com/noir-lang/noir/pull/6463 to fix a Brillig bug that made arrays shared via function parameters with the caller mutable. Apparently ACIR never had a problem with this, and not being able to do that optimisation makes it less efficient. 
I suppose we could make this conditional on the already present `is_brillig_runtime` flag, however it was decided that the `array_set` pass was only ever meant to be used by ACIR, and Brillig should use refcounts exclusively to decide whether to mutate or not. 
Check one:

chore(ssa): Skip array_set pass for Brillig functions

---

compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/hir_def/types.rs

No issue, minor chore for unused methods that I noticed while debugging my frontend stack overflow.
These methods are leftover from implicit numeric generics and can be deleted.
Check one:

chore: Remove unused methods from implicit numeric generics

---

acvm-repo/acvm/src/compiler/optimizers/merge_expressions.rs

…
Resolves https://github.com/noir-lang/noir/issues/6527
The `merge_expressions` optimization pass was not taking the outputs of blackbox functions into account so if the result was using in two AssertZero opcodes then we'd end up optimizing it out and orphaning the blackbox opcode.
Check one:

fix: take blackbox function outputs into account when merging expressions

---

compiler/noirc_frontend/src/hir_def/types.rs
compiler/noirc_frontend/src/monomorphization/mod.rs

Resolves https://github.com/noir-lang/noir/issues/6457
Finishes monomorphization in the program above in ~1.3s on my machine compared to master which stack overflows after 1min 12s.
Fixes the issue by performing a shallow follow bindings call before each unification. This follows immediate type variable links but stops once a non-type variable is reached. This prevents the issue in the program above because previously in unification we'd unify as soon as possible. If `self` is unbound but `other` is a bound type variable, we could be continuously adding another link to the chain. E.g. `tv3 -> tv2 -> tv1 -> Field` unified with `tv4` may become `tv4 -> tv3 -> tv2 -> tv1 -> Field`.
With this change we follow bindings beforehand so we'd unify `tv4` to `Field` and would never build up the …

fix: Do a shallow follow_bindings before unification

---

.github/workflows/release.yml
release-please-config.json

Resolves 
This PR switches release-please over to using `1.0.0-beta.0` versioning. The final digit will keep increasing until we switch back to the normal versioning strategy.
Before we merge this I need to do some thinking on what potential knock on effects there may be on npm/crates.io releases.
Check one:

chore: switch to 1.0.0-beta versioning

---

compiler/noirc_driver/src/lib.rs
cspell.json
tooling/nargo/src/ops/compile.rs

Resolves 
Currently we don't allow easy distinguishing between the output for different packages within a workspace. This PR adds a span for this which we label with the package name.
Check one:

chore: embed package name in logs

---

test_programs/execution_success/sha256_brillig_performance_regression/Nargo.toml
test_programs/execution_success/sha256_brillig_performance_regression/Prover.toml
test_programs/execution_success/sha256_brillig_performance_regression/src/main.nr

Showcases the blowup described in https://github.com/noir-lang/noir/issues/6565
This function went from 24k-27k opcodes executed to roughly 440k.
Check one:

chore: Added test showcasing performance regression

---

compiler/noirc_evaluator/src/ssa/ir/instruction/call.rs
compiler/noirc_evaluator/src/ssa/parser/mod.rs

Fixes a bug I found while working on #6548
Check one:

fix: correct type when simplifying `derive_pedersen_generators`

---

tooling/nargo_toml/src/errors.rs
tooling/nargo_toml/src/semver.rs

Resolves #6578 
This is a quick fix for #6578. We now treat prereleases as equivalent to the full releases for the purposes of `compiler_version` and can address this more permanently closer to the 1.0.0 release.
I've also disallowed placing requirements on compiler versions other than standard releases in order to simplify things.
Check one:

fix: consider prereleases to be compatible with pre-1.0.0 releases

---

tooling/nargo_cli/src/cli/init_cmd.rs

Resolves 
`nargo new` will create `Nargo.toml` file with an invalid `compiler_version` field after #6580 
Check one:

fix: remove `compiler_version` from new `Nargo.toml`

---

docs/docs/how_to/how-to-oracles.md

Resolves https://github.com/noir-lang/noir/pull/6597#discussion_r1853667699
Check one:

chore: Typo in oracles how to

---

tooling/nargo_fmt/src/formatter/expression.rs
tooling/nargo_fmt/src/formatter/function.rs

Just a small formatter issue I found while trying to reduce some code by commenting it.
Previously this code:
```noir
fn main() {
let a = 1;
// let x = 1;
// let y = 2;
}
```
was formatted to this one:
```noir
fn main() {
let a = 1;
// let x = 1;
// let y = 2;
}
```
With this PR the newline between comments is preserved.
Check one:

fix: preserve newlines between comments when formatting statements

---

acvm-repo/acir_field/src/field_element.rs

Closes #4759 
I found this due to #6550.
We make heavy use of the `num_bits` method during compilation but this is currently doing a lot of unnecessary allocations in order to perform a full bit decomposition of the field element. We can rework this to work on the byte decomposition which removes 96% of all the temporary allocations from compilation.
Check one:

chore: remove temporary allocations from `num_bits`

---

tooling/nargo_cli/build.rs

When running `nargo_cli` tests locally, it will fail if there are "almost empty" directories that remained from a previous git branch switch.
Check one:

chore: ignore almost-empty directories in nargo_cli tests

---

acvm-repo/acir_field/src/field_element.rs

`FieldElement::hash` and `FieldElement::eq` allocate by calling `to_be_bytes`. We can derive these traits by delegating to the internal `Fp` implementation.
I _think_ the internal `Fp` implementation holds a BigInt, which is a wrapper around `[u64; N]`, and that's what's hashed, so I guess hashing that involves no memory allocations. Same for equality comparison.
But maybe there's a reason these weren't derived in the first place...?
Check one:

chore: derive PartialEq and Hash for FieldElement

---

compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs
compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs

Resolves https://github.com/noir-lang/noir/pull/6434#discussion_r1828469417
When there is a duplicate store in the same block without a load or call in between we used to remove that store in mem2reg. After https://github.com/noir-lang/noir/pull/6434 reactivating the following snippet:
```
if let Some(last_store) = references.last_stores.get(&address) {
self.instructions_to_remove.insert(*last_store);
}
``` 
gives this error:
In https://github.com/noir-lang/noir/pull/6434, when handing side effects during flattening we switched to doing `prev_value = load foo; store (if c then 3 else prev_value) in foo`. However, the first store to an allocation has no previous value (`foo = allocate; store 3 in foo`). So if we replace the first store with a load, the load is not going to be removed by …

fix(ssa): Track all local allocations during flattening

---

docs/docs/noir/standard_library/mem.md
docs/docs/noir/standard_library/meta/index.md
docs/docs/noir/standard_library/meta/typ.md

Thanks donatik27 for https://github.com/noir-lang/noir/pull/6573. Our policy is to redo typo changes to dissuade metric farming. This is an automated script.

chore: redo typo PR by donatik27

---

compiler/noirc_frontend/src/node_interner.rs
tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/tests.rs

Resolves #6608
I didn't know about having to use `find_matching_method` when looking up methods, so back then I ended up doing some similar logic that wasn't quite right.
Check one:

fix(LSP): use generic self type to narrow down methods to complete

---

compiler/noirc_errors/src/position.rs
tooling/lsp/src/requests/code_action/import_or_qualify.rs

I noticed that LSP code actions weren't triggering when the cursor was right at the beginning (or end) of an identifier. This is a very common use case so this PR fixes that.
Check one:

fix: LSP code action wasn't triggering on beginning or end of identifier

---

compiler/noirc_frontend/src/parser/errors.rs
compiler/noirc_frontend/src/parser/parser.rs
compiler/noirc_frontend/src/parser/parser/types.rs

Resolves #4548
Even though the error message was already better than the chumsky parser (it said "expected a `mut`, found [another token]") now the error message also says that Noir doesn't have immutable references.
The original issue suggests linking to some docs explaining why that is but I don't know if such doc exists.
Check one:

chore: improve error message of `&T`

---

noir_stdlib/src/hash/poseidon2.nr

Resolves 
I'm not sure why this if-statement is here but it's a bit weird rather than just passing this condition as the argument directly.
Check one:

chore: refactor poseidon2

---

compiler/noirc_evaluator/src/ssa/ir/instruction/call.rs

Resolves #6662 
If someone attempts to do a decomposition into radices other than 2 or 256 then we'll end up returning the incorrect type. This PR solves this issue.
Check one:

fix: always return an array of `u8`s when simplifying `Intrinsic::ToRadix` calls

---

compiler/noirc_frontend/src/elaborator/comptime.rs
compiler/noirc_frontend/src/tests/metaprogramming.rs

Resolves #6373
By unifying before evaluating the argument we'll have the type bindings correctly set.
Check one:

fix: use correct type for attribute arguments

---

compiler/noirc_frontend/src/debug/mod.rs
compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/elaborator/patterns.rs
compiler/noirc_frontend/src/hir/resolution/errors.rs
compiler/noirc_frontend/src/tests.rs

I noticed you couldn't define a function like `fn foo(_: i32, _: Field)`, it errored saying that `_` is defined multiple times.
Then I noticed you can have code like `let _ = 1; let x = _;`.
Both things above are fixed with this PR (the first one doesn't error anymore, the second one errors with a message that's the same Rust produces).
Check one:

fix: allow multiple `_` parameters, and disallow `_` as an expression you can read from

---

compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/hir/type_check/errors.rs
compiler/noirc_frontend/src/hir_def/types.rs
compiler/noirc_frontend/src/tests.rs

Resolves #5651
Now the error shows up like this:
```
error: No method named 'wrapped' found for type 'Foo'
┌─ src/main.nr:7:9
│
7 │         self.wrapped(x)
│         --------------- to call the function stored in 'wrapped', surround the field access with parentheses: '(', ')'
```
Rust's error message is a bit better, but I think we can't do it like that with what we have right now:
Check one:

feat: better error message when trying to invoke struct function field

---

.github/workflows/memory_report.yml

Related to #6604
js scripts were not updated
Check one:

chore: update noir-bench-report version

---

Cargo.lock
acvm-repo/acir/src/circuit/brillig.rs
acvm-repo/acir/src/circuit/mod.rs
acvm-repo/acir/src/circuit/opcodes.rs
acvm-repo/acir/src/circuit/opcodes/black_box_function_call.rs
acvm-repo/acir/src/circuit/opcodes/memory_operation.rs
acvm-repo/brillig/src/black_box.rs
acvm-repo/brillig/src/opcodes.rs
compiler/noirc_driver/src/debug.rs
compiler/noirc_driver/src/lib.rs
compiler/noirc_driver/src/program.rs
compiler/noirc_errors/src/debug_info.rs
compiler/noirc_evaluator/src/errors.rs
compiler/noirc_evaluator/src/ssa.rs
tooling/nargo/src/ops/check.rs
tooling/nargo/src/ops/transform.rs
tooling/nargo_cli/Cargo.toml
tooling/nargo_cli/src/cli/compile_cmd.rs
tooling/nargo_cli/tests/stdlib-props.rs
tooling/noirc_abi/src/lib.rs

Resolves #6669 
`compile_cmd::compile_programs` now detects the case when `nargo::ops::compile::compile_program` has the compiled artefact loaded from cache, rather than recompiled from scratch. When it's loaded from cache, it is assumed to have already gone through the rest of what `compile_cmd::compile_programs` does, which is to apply `nargo::ops::transform_program` on it, which includes ACVM optimisations and setting the target expression width. If the current target expression width is the same as the one the package was compiled with, we can skip doing these steps again. 
That eliminates the risk of running an non-idempotent optimisation that changes our circuit from what has been persisted before. If somebody were to delete the artefacts and compile from scratch with the same nargo …

feat(tooling): Skip program transformation when loaded from cache

---

tooling/noirc_abi_wasm/test/browser/abi_encode.test.ts
tooling/noirc_abi_wasm/test/node/abi_encode.test.ts

Resolves 
This change made in #6637 has broken the sync PR as it's using improper types here. This PR is a quick fix for this issue.
Check one:

chore: fix tests in `noirc_abi_wasm`

---

docs/docs/noir/standard_library/containers/boundedvec.md
noir_stdlib/src/collections/bounded_vec.nr

Resolves a private issue in a slack conversation
Adds two functions:
- `BoundedVec::from_parts` to create a bounded vec from an array and a length
- `BoundedVec::from_parts_unchecked` to do the same, but this version does not check or zero out any elements past the given length. If arrays with non-zeroed elements past the given length are given then this can result in two otherwise equal bounded vecs returning false for `BoundedVec::eq`.
Check one:

feat: Add `BoundedVec::from_parts` and `BoundedVec::from_parts_unchecked`

---

compiler/noirc_evaluator/src/ssa/opt/die.rs
test_programs/execution_success/reference_counts/src/main.nr

This reverts commit 440d94d8149ede5f211437e9405f65b460cfcbf8.
Resolves 
This commit was failing the e2e tests
Check one:

chore: Revert "fix: Don't remove necessary RC instructions in DIE pass (#6585)"

---

tooling/lsp/src/requests/completion/tests.rs
tooling/lsp/src/use_segment_positions.rs

LSP auto-import was trying to insert `use ...;` at line N, character 4 if the import should go inside a `mod`. The problem is, if that line is empty inserting at character 4 doesn't work.
Instead of inserting at the desired indentation, we now insert the indentation. That is, instead of inserting `use ...;` at character 4, we insert `    use ...;`.
Originally we also inserted an indent in the line following the `use`, so if you had:
```noir
mod a {
use foo; // imagine the new import goes after this line
fn bar() {}
}
```
we inserted "use bar;\n    " so that `fn bar() {}` remains indented. However, we also have logic to insert a newline between the new import and whatever comes next, so we actually never need to put an indentation after the use (and it's wrong to do so because we'll end up …

fix: LSP auto-import text indent

---

compiler/noirc_frontend/src/parser/parser/expression.rs

feat: improve parser recovery of constructor field with '::' instead of ':'

---

compiler/noirc_evaluator/src/ssa/opt/die.rs

Resolves 
We're currently iterating through the whole of a block N times to remove each RC instruction one-by-one so removing these is ~N^2. I've modified this to instead build up a list of instructions to remove per block and then remove all of these in a single pass.
Testing in the protocol circuits has halved compilation times on `private_kernel_reset`
Check one:

feat: replace quadratic removal of `rc` instructions

---

Cargo.lock
Cargo.toml
acvm-repo/bn254_blackbox_solver/Cargo.toml

deny/deny (pull request) CI action started failing because of the advisories requiring pprof to be >= 0.14.
Fixing pprof version
Check one:

chore: Update pprof

---

compiler/noirc_evaluator/src/ssa/ir/instruction/call.rs
compiler/noirc_evaluator/src/ssa/ir/printer.rs
compiler/noirc_evaluator/src/ssa/parser/lexer.rs
compiler/noirc_evaluator/src/ssa/parser/mod.rs
compiler/noirc_evaluator/src/ssa/parser/tests.rs
compiler/noirc_evaluator/src/ssa/parser/token.rs

Doesn't resolve any issue, but might make debugging SSA a bit easier.
In Noir string literals are just arrays of bytes. When going from code to SSA we always get byte arrays and it's hard to relate those back to string literals.
In this PR, when printing a `make_array` instruction whose array (or slice) consists of all printable ascii bytes, we now show that as a byte string literal (`b"..."`). I know Noir doesn't have `b"..."` like in Rust, but I used the same notation to make it clear that it's really a byte array.
For example, for this Noir program:
```noir
fn main() {
let x = 1;
println(f"X is {x}");
}
```
The final SSA before this PR was:
```
acir(inline) fn main f0 {
b0():
v7 = make_array [u8 88, u8 32, u8 105, u8 115, u8 32, u8 123, u8 120, u8 125] : [u8; 8]
call f1(u1 1, v7, u32 …
```

feat: show printable byte arrays as byte strings in SSA

---

Cargo.lock
acvm-repo/acvm/Cargo.toml
acvm-repo/acvm/src/compiler/mod.rs
acvm-repo/acvm/src/compiler/optimizers/mod.rs
acvm-repo/acvm/src/compiler/transformers/mod.rs
tooling/nargo_cli/src/cli/compile_cmd.rs

Followup for https://github.com/noir-lang/noir/pull/6694 
Makes `nargo::ops::transform_program` idempotent by adding two loops, both up to 3 passes, exiting early if the opcode hash doesn't change:
* an outer loop in `acvm::compiler::compile` that includes `optimize_internal` and `transform_internal` 
* an inner loop in `acvm::compiler::transformers::transform_internal`
Here's the journey I went through investigating the source of changes across optimisation runs.
On the `slice_loop` example the `Circuit::current_witness_index` field increased by 2 after each pass. This seems to be because:
1. It is increased by the number of intermediate variables created [here](https://github.com/noir-lang/noir/blob/dc96de7c7a3d3c325b955edb277534653204cc5a/acvm-repo/acvm/src/compiler/transformers/mod.rs# …

fix: Make `nargo::ops::transform_program` idempotent

---

tooling/nargo_cli/build.rs

Resolves 
After https://github.com/noir-lang/noir/pull/6685, reference counts are the same inlined or not again
Check one:

chore: Remove inliner override for `reference_counts` test

---

compiler/noirc_evaluator/src/ssa/ir/function.rs
compiler/noirc_evaluator/src/ssa/ir/printer.rs
compiler/noirc_evaluator/src/ssa/opt/array_set.rs
compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs
compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs
compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
compiler/noirc_evaluator/src/ssa/opt/simplify_cfg.rs
compiler/noirc_evaluator/src/ssa/opt/unrolling.rs
compiler/noirc_evaluator/src/ssa/parser/tests.rs

Resolves #6520
Curiously, `--show-ssa` for `fold_2_to_17` now gives another error, but at least it's not the old stack overflow anymore.
Check one:

fix: print ssa blocks without recursion

---

Cargo.lock
tooling/nargo_toml/Cargo.toml
tooling/nargo_toml/src/git.rs

Resolves #6720
The location to store dependencies didn't handle the case where there _wasn't_ a trailing slash as expected, resulting in the dependencies with and without a trailing slash treated as different crates.
For example the crate in question was downloaded to two different locations:
* `~/nargo/github.com/noir-lang/noir-bignumv0.4.2/src/lib.nr`
* `~/nargo/github.com/noir-lang/noir-bignum/v0.4.2/src/lib.nr`
These got mapped to separate `CrateId` in [prepare_dependency](https://github.com/noir-lang/noir/blob/da9a74a2c70be8ba2a72b7dfb24393c029a27564/compiler/noirc_driver/src/lib.rs#L267-L272), which then caused [unification](https://github.com/noir-lang/noir/blob/da9a74a2c70be8ba2a72b7dfb24393c029a27564/compiler/noirc_frontend/src/hir_def/types.rs#L1639) to fail because the …

fix: git dependency trailing slash

---

Cargo.lock
Cargo.toml

deny/deny (pull request) CI action started failing because of the advisories requiring url to be >= 2.5.4.
Updating url module version
Check one:

chore: Update url to 2.5.4

---

compiler/noirc_evaluator/src/acir/mod.rs
compiler/noirc_evaluator/src/ssa.rs
compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs
compiler/noirc_evaluator/src/ssa/ssa_gen/program.rs

Resolves #6521
Defer the entry point indexes to be computed after all ssa passes.
Check one:

fix: map entry point indexes after all ssa passes

---

compiler/noirc_evaluator/src/ssa/opt/unrolling.rs

Minor code cleanup of some unrolling methods
Check one:

chore: Cleanup unrolling pass

---

compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/elaborator/statements.rs
compiler/noirc_frontend/src/hir/type_check/errors.rs

Resolves #5606
Improves the type error issued when an index lvalue is used `a[0] = rhs` where the type of `a` is unknown.
- Changes the error location from `rhs` to `a[0]`
- Clarifies the error that a type annotation is needed because `a` could be an array or a slice
Check one:

fix: Improve type error when indexing a variable of unknown type

---

compiler/noirc_driver/src/lib.rs

Resolves 
The protocol circuits currently print out 250k lines of warnings to the console which reminded me that we track all of the typechecking warnings through the full compilation flow even if we've decided to silence them (as they do in aztec-packages).
This PR updates `check_crate` to drop all these warnings before we start the SSA passes so that we can free up some memory.
Check one:

chore: free memory for silenced warnings early

---

.github/workflows/cache-cleanup.yml
.github/workflows/deny.yml
.github/workflows/docs-dead-links.yml
.github/workflows/docs-pr.yml
.github/workflows/formatting.yml
.github/workflows/publish-acvm.yml
.github/workflows/publish-docs.yml
.github/workflows/publish-es-packages.yml
.github/workflows/publish-nightly.yml
.github/workflows/pull-request-title.yml
.github/workflows/recrawler.yml
.github/workflows/release.yml
.github/workflows/reports.yml
.github/workflows/spellcheck.yml
.github/workflows/test-js-packages.yml
.github/workflows/test-rust-workspace-msrv.yml
.github/workflows/test-rust-workspace.yml

Resolves 
Simpler solution to https://github.com/noir-lang/noir/pull/6746 to just lock ourselves to the old runner image to buy more time.
Check one:

chore: lock CI to use ubuntu 22.04

---

compiler/noirc_frontend/src/parser/parser/types.rs

@nventuro Found that this snippet crashed VSCode:
```noir
impl<T, let MaxLen: u32> BoundedVec<T, MaxLen> {
fn for_each<U, Env>(self, f: fn[Env](value: T, index: u32)) {
for i in 0..MaxLen {
if i < self.len() {
f(self.get_unchecked(i), i);
}
}
}
}
```
It turns out that a function type like this: `fn(value: T)` crashed the compiler. The reason is that parsing an fn parameter called `parse_type_or_error` and considered that an error if it returned `UnresolvedTypeData::Error`. The problem is that that method returned `UnresolvedTypeData::Unspecified` in that case. I think at one point I accidentally changed it to return `Unspecified` in order to reuse a function. The name is `parse_type_or_error` so returning `Error` is the correct thing to do, and it also solves the issue.
Check one:

fix: parser would hand on function type with colon in it

---

compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs
test_programs/execution_success/reference_counts/src/main.nr

Resolves https://github.com/noir-lang/noir/issues/6763
Replaces https://github.com/noir-lang/noir/pull/6774
Always incrementing the rc of an array from a let binding fixes the issue in the test in https://github.com/noir-lang/noir/issues/6763. We can revert this one part of #6685 for now and hopefully re-add it later when we figure out why it breaks.
This means reference counts essentially start at 2 again so the first mutation of an array will always incur a copy.
Check one:

fix: Minimal change to avoid reverting entire PR #6685

---

docs/docs/getting_started/noir_installation.md

fix: use extension in docs link so it also works on GitHub

---

compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs

Part of general effort to optimize the compiler.
Loop invariant code motion most affects the Brillig runtime, as in that runtime we actually keep loops and may possibly re-execute unnecessary instructions. In ACIR all loops are unrolled so when the pass was introduced I was thinking that running it may be an unnecessary cost when compiling to ACIR. However, the pass should provide benefits to the compilation pipeline itself.
For ACIR programs with large upper loop bounds, unrolling is oftentimes the pass that takes up the most time. If we can reduce the number of opcodes inside of a loop, unrolling should take less time. This becomes most obvious when paired with https://github.com/noir-lang/noir/pull/6782, as a large constant array it most likely going to be one of the heavier …

chore(ssa): Activate loop invariant code motion on ACIR functions

---

.github/workflows/test-js-packages.yml
scripts/check-critical-libraries.sh
tooling/nargo_cli/src/cli/test_cmd.rs
tooling/nargo_cli/src/cli/test_cmd/formatters.rs

Made on top of #6728
Towards #6733
Eventually we'll have `nargo test --format json`, which is what #6733. As a first step I wanted to introduce the `format` flag and, to try that abstraction in code I introduced a terse formatter similar to Rust.
On failure we don't immediately print the error. Instead, it's printed at the end (like in Rust). I can imagine this could be used in CI to reduce the output verboseness, because I guess all that matters in CI is seeing which tests failed. NOTE: I already added this `-q` flag to our external checks, you can see how it looks, I think it's a bit better as it's less noisy.
Like in Rust, there are two ways to trigger this terse behavior: `-q` (or `--quiet`) or `--format terse`. We could just keep `--format terse` but I think `-q` is convenient (and …

feat: `nargo test -q` (or `nargo test --format terse`)

---

compiler/noirc_evaluator/src/ssa/ir/instruction/binary.rs
compiler/noirc_evaluator/src/ssa/ir/instruction/call.rs
compiler/noirc_evaluator/src/ssa/ir/instruction/call/blackbox.rs

Resolves an issue in a slack thread by @michaeljklein 
Breakout of a change in https://github.com/noir-lang/noir/pull/6771 where slice pop back seemed to be using all of its ctrl_typevars for a tuple instead of the one element that was actually being popped. This only affects the ArrayGet though which is subsequently optimized out.
Check one:

feat: add `(x | 1)` optimization for booleans

---

compiler/noirc_evaluator/src/acir/mod.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
compiler/noirc_evaluator/src/ssa/ir/map.rs
compiler/noirc_evaluator/src/ssa/opt/defunctionalize.rs
compiler/noirc_evaluator/src/ssa/opt/unrolling.rs
compiler/noirc_evaluator/src/ssa/parser/into_ssa.rs

Changes `Id` to be represented by a `u32` instead of a `usize` to save memory.
Unsure on performance implications since I also used `.try_into().unwrap()` to panic if the length is greater than a u32 over `as u32` which would be faster but silently wrap.
Check one:

chore: Change Id to use a u32

---

.github/workflows/reports.yml
test_programs/compilation_report.sh

Started as investigations into https://github.com/noir-lang/noir/pull/6750#discussion_r1878881848, but looks like the memory issues have been resolved by recent updates. Specifically this switch to `u32` for Id https://github.com/noir-lang/noir/pull/6807.
Simply activates the two commented out rollup circuits. 
Check one:

chore(ci): Active rollup circuits in compilation report

---

acvm-repo/acvm/src/compiler/optimizers/mod.rs
compiler/noirc_evaluator/src/ssa/checks/check_for_underconstrained_values.rs

I was running `NOIR_LOG=trace nargo` on some programs and my entire output was entirely filled with the SSA of my program. I was unsure where we were printing this SSA, but then I found that a couple trace macros are called in the under constrained values check where we state which function we are processing. We should print the ID, not the entire function.
I switched to using func IDs instead of the entire function. This makes the trace actually readable. I could turn off the underconstrained check, but I think we should switch this to use an ID either way. Someone attempting to use `trace` should not have to know that they need this flag in order to get some reasonable debug output.
Check one:

chore: Do not print entire functions when running debug trace

---

docs/docs/getting_started/quick_start.md
docs/versioned_docs/version-v0.36.0/getting_started/quick_start.md
docs/versioned_docs/version-v0.37.0/getting_started/quick_start.md
docs/versioned_docs/version-v0.38.0/getting_started/quick_start.md
docs/versioned_docs/version-v0.39.0/getting_started/quick_start.md
docs/versioned_docs/version-v1.0.0-beta.0/getting_started/quick_start.md

workaround until we fix the registrar stuff

chore(docs): workaround

---

.vscode/settings.json

Today when working inside of Noir I suddenly started getting red all over any functions or structures that used proc macros: 
This was littering my code base and was quite annoying as it made it harder to see legitimate errors.
According to https://rust-analyzer.github.io/manual.html#toolchain we can force rust-analyzer to use the stable toolchain via an environment variable. So even though our rust toolchain is set to `1.74.1` we should not be out of sync with rust-analyzer updates. 
My proc macros errors from rust-analyzer are all gone now.
Check one:

chore: Have rust-analyzer use the stable toolchain

---

compiler/noirc_evaluator/src/ssa/ir/dfg.rs

First step towards #6822 
This is a small refactor of the DFG to create functions which would be useful for #6822. I haven't pushed this change into the `FunctionBuilder` as this would be a larger change.
Check one:

chore: refactor `DataFlowGraph.insert_instruction_and_results`

---

compiler/noirc_frontend/src/hir/comptime/interpreter.rs
compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
test_programs/compile_success_empty/comptime_as_field/Nargo.toml
test_programs/compile_success_empty/comptime_as_field/src/main.nr
test_programs/compile_success_empty/comptime_from_field/Nargo.toml
test_programs/compile_success_empty/comptime_from_field/src/main.nr

fix: implement `as_field` and `from_field` in the interpreter

---

compiler/noirc_evaluator/src/ssa/opt/resolve_is_unconstrained.rs

Resolves 
Very minor optimization I noticed while doing something else. 
Check one:

chore: move constant creation out of loop

---

compiler/noirc_frontend/src/elaborator/path_resolution.rs
compiler/noirc_frontend/src/elaborator/patterns.rs
compiler/noirc_frontend/src/tests/aliases.rs
test_programs/compile_success_empty/double_generic_alias_in_path/Nargo.toml
test_programs/compile_success_empty/double_generic_alias_in_path/src/main.nr

fix: double alias in path

---

compiler/noirc_driver/src/lib.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/artifact.rs
compiler/noirc_evaluator/src/ssa/opt/unrolling.rs
compiler/noirc_frontend/src/ast/statement.rs

Resolves #2036 
The parent branch added a check for non-determinism in the compiler. This PR contains all fixes to get our tests passing that check. I separated them out from the check itself for ease of reviewing. This PR will go into #6847 once it is ready. 
Check one:

fix: Remove all non determinism

---

compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/hir/comptime/errors.rs
compiler/noirc_frontend/src/hir/comptime/interpreter.rs
compiler/noirc_frontend/src/monomorphization/mod.rs
compiler/noirc_frontend/src/node_interner.rs
compiler/noirc_frontend/src/tests.rs

Resolves #6780
This program:
```noir
comptime global A: u32 = B;
comptime global B: u32 = A;
fn main() { }
```
now gives these errors:
```
error: Variable not in scope
┌─ src/main.nr:2:26
│
2 │ comptime global B: u32 = A;
│                          - Could not find variable
│
error: This global recursively depends on itself
┌─ src/main.nr:1:26
│
1 │ comptime global A: u32 = B;
│                          -
│
error: Dependency cycle found
┌─ src/main.nr:1:17
│
1 │ comptime global A: u32 = B;
│                 - 'A' recursively depends on itself: A -> B -> A
│
Aborting due to 3 previous errors
```
Check one:

fix: detect cycles in globals

---

tooling/debugger/src/foreign_calls.rs
tooling/nargo/src/foreign_calls/layers.rs
tooling/nargo/src/foreign_calls/mocker.rs
tooling/nargo/src/foreign_calls/mod.rs
tooling/nargo/src/foreign_calls/print.rs
tooling/nargo/src/foreign_calls/rpc.rs
tooling/nargo/src/lib.rs
tooling/nargo/src/ops/test.rs

Followup for https://github.com/noir-lang/noir/pull/6849
Adds a `foreign_calls::layer::Layer` construct which is used to compose `ForeignCallExecutor` instances. `DefaultForeignCallExecutor`, `DebugForeignCallExecutor` and `TestForeignCallExecutor` are reimplemented with this layering. 
The `DefaultForeignCallExecutor` allows us to inject a base layer, which the `TestForeignCallExecutor` uses to change the behaviour when nothing handles the call; this way we can reuse the default composition without having to repeat the logic in the test, similar to how the `DefaultDebugForeignCallExecutor` did it earlier.
Follow up for this would be:
* Make the _mock_ layer in the `DefaultForeignCallExecutor` optional, so that during normal execution no contract can install a mock and then handle foreign …

feat!: Composable foreign call handlers

---

tooling/lsp/src/requests/test_run.rs
tooling/nargo/Cargo.toml
tooling/nargo/src/foreign_calls/default.rs
tooling/nargo/src/foreign_calls/mocker.rs
tooling/nargo/src/foreign_calls/mod.rs
tooling/nargo/src/lib.rs
tooling/nargo/src/ops/mod.rs
tooling/nargo/src/ops/test.rs
tooling/nargo_cli/src/cli/test_cmd.rs
tooling/nargo_cli/tests/stdlib-tests.rs

Follow up for https://github.com/noir-lang/noir/pull/6857
Fixes the Wasm compilation in https://github.com/noir-lang/noir/pull/6849
Changes `nargo::ops::test::run_test` to take a generic function to create a `ForeignCallExecutor`, rather than a URL which it used for now to create a HTTP client, which would not compile to wasm, clashing with the goals of https://github.com/noir-lang/noir/pull/6835
Refactored `nargo` to make it possible to import the `test` features without the `rpc` stuff. Changed the feature flags to only disable the `DefaultForeignCallExecutor` for Wasm.
Check one:

feat!: `nargo::ops::test::run_test` generic in `ForeignCallExecutor`

---

compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/hir/type_check/errors.rs
compiler/noirc_frontend/src/tests.rs
noir_stdlib/src/collections/map.nr
noir_stdlib/src/meta/mod.nr

Resolves #6866
1. I checked `Aztec-Packages` and there are some occurrences of this warning (and also in the bignum library)
2. I learned that using `unsafe` inside a comptime context isn't needed, so the compiler will automatically warn about this (this happened in one place in the stdlib)
Check one:

feat: warn on unnecessary unsafe blocks

---

.github/workflows/reports.yml
test_programs/compilation_report.sh
test_programs/execution_report.sh

No issue as just a small improvement on existing compiler reports
For very small programs (e.g. less than 2 seconds) the compilation and execution reports can be deceiving as they can vary greatly per run. This PR adds logic to take an average of certain small programs to get more accurate reports.
Check one:

chore(ci): Take averages for compilation and execution report of small programs

---

compiler/noirc_evaluator/src/ssa/ir/instruction.rs
compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs

Resolves #6786 
The new way of handling predicates on store instructions was resulting in us having a stack of `load->if-else ->store->load ->if-else->store` where the else value of each if-else was the previous if-else. This means we get a huge stack of nested if-else instructions which share the same `then_condition` so they can be squashed down to just have the top "then" and bottom "else".
I've solved this by having the `simplify` instruction inspect the `then_value` and `else_value` of any if-else instructions to see if we're building a nested structure and then flatten it automatically.
This PR drops the size of `stateful-test-contract` (after being reduced to just having the `create_note` function) from 31.2MB to 12.2MB.
Check one:

feat: flatten nested if-else statements with equivalent conditions

---

.github/workflows/reports.yml
test_programs/compilation_report.sh
test_programs/execution_report.sh

In https://github.com/noir-lang/noir/pull/6874 we moved to computing an average of multiple runs of `nargo compile` and `nargo execute`. The noir-bench-report still expects our time input to have the format of the output from the `time` command (e.g. `[0-9]+m[0-9]+.[0-9]+s`). In that PR we just prepended `0m` as to not to have to convert back to minutes. This suffix clutters the report output. 
In this PR I decided to just keep with total seconds rather than converting back to minutes and seconds. It is simpler to work with one unit in my opinion. If we have reports that really need to be represented in minutes, we can address that at the time (if we have reports of that size it most likely means we have larger issues than how we display our reports). 
Updates to the commit in this PR …

chore(ci): Display times in compilation and execution reports only with seconds

---

Cargo.lock
compiler/noirc_evaluator/Cargo.toml
compiler/noirc_evaluator/src/ssa/ir/dfg.rs

Resolves https://github.com/noir-lang/noir/issues/6830
Experimenting with a direct fix for https://github.com/noir-lang/noir/issues/6830 since https://github.com/noir-lang/noir/pull/6850 is a bit extreme.
Check one:

chore: Use smallvec for instruction results

---

compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs

Step towards https://github.com/noir-lang/noir/issues/6878
Check one:

chore: Avoid duplicate Not instructions during flattening

---

test_programs/gates_report.sh

Resolves 
This PR resolves us having a billion lines of output from `gates_per_opcode` which are irrelevant for us. 
Check one:

chore: clean up gates reports script

---

.github/workflows/reports.yml
test_programs/gates_report.sh
test_programs/gates_report_brillig.sh
test_programs/gates_report_brillig_execution.sh

Resolves 
Brillig reports cause issues with https://github.com/noir-lang/noir/pull/6851 where I'm being stricter about the data we're feeding into this action so I'm merging this separately so that we get a compatible artifact on master.
Check one:

chore: remove malformed functions from brillig reports

---

compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/hir_def/types.rs
compiler/noirc_frontend/src/node_interner.rs
compiler/noirc_frontend/src/tests.rs
compiler/noirc_frontend/src/tests/traits.rs
noir_stdlib/src/meta/ctstring.nr
noir_stdlib/src/meta/mod.nr
noir_stdlib/src/meta/op.nr
test_programs/compile_success_empty/comptime_change_type_each_iteration/src/main.nr
test_programs/compile_success_empty/comptime_trait_constraint/src/main.nr
test_programs/compile_success_empty/ctstring/src/main.nr
test_programs/compile_success_empty/regression_5428/src/main.nr

Based on top of #6895
Part of https://github.com/noir-lang/noir/issues/6864
Similar to the previous PRs but this time for primitive types.
I think what's missing now is to do the same for "generic" types, for example if there's a trait impl for every `(T)`, calling a method of that trait on a tuple might not currently require the trait to be in scope. But I'll do this in a follow-up PR.
Check one:

feat!: require trait primitive functions/calls to have their trait in scope

---

compiler/noirc_evaluator/src/ssa/opt/remove_bit_shifts.rs

Resolves #6788 
Since bit shift are now forced to be done with u8 rhs operand, we do not need to cast it to unsigned type anymore.
Check one:

fix: remove unnecessary cast in bit-shift

---

tooling/nargo/src/lib.rs

Resolves an issue where monomorphisation hash differ between compilations from different installation folders
The file id are given by iterating over Noir source folders, but the iteration may depend on the file system state.
To fix this, I simply enumerate files in file names order.
Check one:

fix: consistent file_id across installation paths

---

docs/docs/noir/concepts/data_types/strings.md
docs/versioned_docs/version-v1.0.0-beta.1/noir/concepts/data_types/strings.md

chore: document format strings

---

Cargo.lock
tooling/nargo_cli/Cargo.toml
tooling/nargo_cli/tests/execute.rs

Resolves 
We no longer use the `test-binary` package since removing any connection to backends in the noir codebase.
Check one:

chore: remove unused dependency

---

compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs

Resolves 
Looking at the flattening pass atm so doing some modernising of the tests first.
Check one:

chore: use ssa parser in flattening pass tests

---

tooling/noirc_artifacts/src/debug_vars.rs

Resolves 
quick fix for a clippy warning.
Check one:

chore: fix warning

---

compiler/noirc_evaluator/src/ssa/ir/instruction.rs
compiler/noirc_evaluator/src/ssa/ir/instruction/binary.rs
compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs

Followup to https://github.com/noir-lang/noir/pull/6848 whose largest regression was in brillig opcodes executed https://github.com/noir-lang/noir/pull/6848#issuecomment-2549554990. 
In #6848 we marked certain binary ops as not being able to be hoisted due to the overflow checks inside of ACIR gen and Brillig gen. However, if a binary operation has one variable that is from an outer loop's induction variable we can determine whether or not there would be an overflow. This re-uses logic introduced in https://github.com/noir-lang/noir/pull/6639.
This PR currently just tries to hoist add and mul instructions as they are simpler. For example, `Sub` overflows depends on if the induction variable is on the lhs or the rhs (e.g. if it is the rhs we should check the induction variable's upper …

feat(ssa): Hoist add and mul binary ops using known induction variables

---

tooling/nargo_cli/src/cli/compile_cmd.rs

Resolves https://github.com/noir-lang/noir/issues/6940
Using `par_iter` prevents cargo t from capturing each threads output apparently. Switching back to iter shows any output, including the failing assert.
Check one:

fix: Show output of `test_program_is_idempotent` on failure

---

.github/workflows/reports.yml

Resolves 
We weren't properly handling the action inputs so always were looking at the brillig diff.
Check one:

chore: bump `noir-gates-diff`

---

compiler/noirc_evaluator/src/ssa/checks/check_for_underconstrained_values.rs
tooling/nargo_cli/build.rs

In https://github.com/noir-lang/noir/pull/6847 the `--check-non-determinism` flag was only run when force compiling to Brillig. Not sure why I put the flag here in #6847, it looks to be a mistake. Running the non-determinism check for normal ACIR compilation revealed that the under constrained value checks were generating their warnings in a non-deterministic manner.  
The under constrained value checks iterate over a HashSet in many locations. I switched the sets which are iterated over to all be a BTreeSet rather than a HashSet.
Check one:

fix: Non-determinism from under constrained checks

---

.github/workflows/test-js-packages.yml

Resolves 
Nit but it would be nice to be able to see the results in the github UI as well.
Check one:

chore: also print test output to stdout in CI

---

compiler/noirc_evaluator/src/ssa/function_builder/mod.rs
compiler/noirc_evaluator/src/ssa/ir/instruction/call.rs
compiler/noirc_evaluator/src/ssa/ir/instruction/call/blackbox.rs
compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs
compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs
compiler/noirc_evaluator/src/ssa/opt/normalize_value_ids.rs
compiler/noirc_evaluator/src/ssa/parser/into_ssa.rs
compiler/noirc_evaluator/src/ssa/parser/mod.rs
compiler/noirc_evaluator/src/ssa/parser/tests.rs

Resolves #6822
In a couple of tests simplification is still done because those tests are testing the simplification.
In one test, though, a new instruction popped up. I noticed that `normalize_ids()` would previously simplify instructions so we would miss if a pass didn't correctly simplify things... so I think the flattening pass might be leaving some extra `enable_side_effects` instructions, though I don't know if later those are simplified anyway.
Check one:

feat: don't simplify SSA instructions when creating them from a string

---

compiler/noirc_frontend/src/hir/def_collector/errors.rs

feat!: turn CannotReexportItemWithLessVisibility into an error

---

compiler/noirc_frontend/src/elaborator/comptime.rs
compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/hir/comptime/interpreter.rs
compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
compiler/noirc_frontend/src/hir/comptime/value.rs
compiler/noirc_frontend/src/parser/parser.rs
compiler/noirc_frontend/src/tests/metaprogramming.rs

Resolves #6968
The issue was that parser warnings made macro parsing failed. Instead, in this PR we report those warnings and move on (only if all parser errors were warnings).
Check one:

fix: don't fail parsing macro if there are parser warnings

---

compiler/noirc_frontend/src/elaborator/path_resolution.rs
compiler/noirc_frontend/src/tests/traits.rs

Some warnings found in noir-bignum regarding traits.
When doing path lookup there's a concept of "importing module", which is the module the triggered the path lookup, and "starting module", which is where we start looking names. Most of the time these are the same, for example if we do `use foo::Bar` we start at the current module and also look up `foo` in the current module. But when doing `use crate::...` or `use super::..` the starting module changes.
The code was using "starting module" instead of "importing module" to find traits in scope. This PR fixes that to use "importing module".
Check one:

fix: wrong module to lookup trait when using crate or super

---

.github/workflows/reports.yml
compiler/noirc_evaluator/src/acir/acir_variable.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_black_box.rs
noir_stdlib/src/aes128.nr
test_programs/execution_success/aes128_encrypt/src/main.nr

Resolves 
This PR changes the signature of the `aes128_encrypt` blackbox function so that it returns an array rather than a slice.
Docs do not mention the return type of this function so no changes are necessary.
Check one:

feat!: update `aes128_encrypt` to return an array

---

acvm-repo/acvm/src/pwg/memory_op.rs
acvm-repo/acvm/src/pwg/mod.rs

Addresses the panic caused by #6950 
This PR prevents us from panicking in situations such as #6950. It remains to be see as to why this invalid index is created but I'm leaving that to another PR.
Check one:

fix: do not panic on indices which are not valid `u32`s

---

compiler/noirc_evaluator/src/ssa/ir/printer.rs

No issue just something I noticed while working on globals. I wanted to be able to re-use the SSA printer for globals but most printer function accepts a `Function` type as input. However, they all only use `function.dfg` in the function and none of the other fields from `Function`. I want to be able to re-use these printer functions if I have a `DataFlowGraph` but not a `Function`.
I updated most methods under `ir/printer.rs` to accept a `DataFlowGraph` and use it directly. 
Check one:

chore: Use DFG in SSA printer

---

compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/node_interner.rs
compiler/noirc_frontend/src/tests/traits.rs
tooling/lsp/src/requests/hover.rs

This code used to give an error saying multiple traits (`Convert` and `Convert`) were in scope:
```noir
struct Foo {
inner: Field,
}
trait Converter<N> {
fn convert(self) -> N;
}
impl Converter<Field> for Foo {
fn convert(self) -> Field {
self.inner
}
}
impl Converter<u32> for Foo {
fn convert(self) -> u32 {
self.inner as u32
}
}
fn main() {
let foo = Foo { inner: 42 };
let _: u32 = foo.convert();
}
```
Now the error is gone. We search if there's only one trait, not one trait method, in scope. In the snippet above there are two but they are for the same trait so it's fine. Later on the type-checker checks that it's only bound to the one for `u32`.
If we remove the `u32` type annotation, we get this error:
```
error: Multiple trait impls match the object type `Foo`
┌─ src/main.nr:25:13
│ …
```

fix: allow multiple trait impls for the same trait as long as one is in scope

---

.github/critical_libraries_status/noir-lang/ec/.actual.jsonl
.github/critical_libraries_status/noir-lang/ec/.actual.jsonl.jq
.github/scripts/check_test_results.sh
.github/workflows/test-js-packages.yml

Resolves 
We're not properly catching when we completely brick an external project as currently we see no difference between this and a project for which all tests are passing.
This PR fixes the CI so that we can distinguish between these two cases.
Check one:

chore(ci): fail properly in `external-repo-checks`

---

compiler/noirc_frontend/src/elaborator/types.rs

Workaround for this issue: https://github.com/noir-lang/noir/pull/6987#issuecomment-2578316933
I'm sure a similar issue can happen in other scenarios, though I don't know what code reproduces it. We can use this workaround until we bump into a new error and the fix it in a better way.
Alternatively, we could revert #6987
Check one:

fix: return trait impl method as FuncId if there's only one

---

compiler/noirc_evaluator/src/ssa.rs
compiler/noirc_evaluator/src/ssa/ir/instruction.rs

Resolves 
`Cast`s can always be deduplicated as they have no ACIRgen footprint anyway.
Check one:

chore: mark casts as able to be deduplicated

---

compiler/noirc_frontend/src/monomorphization/mod.rs

Small change noticed while working on globals
We should only allow accessing resolved globals in monomorphization after switching to computing all globals at compile time. 
Check one:

chore: Only resolved globals monomorphization

---

compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs

Resolves 
Follow-up for https://github.com/noir-lang/noir/pull/6999#issuecomment-2580342046
Check one:

chore: Add short circuit in ssa-gen for known if conditions

---

compiler/noirc_evaluator/src/acir/mod.rs
compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
compiler/noirc_frontend/src/hir/comptime/tests.rs
compiler/noirc_frontend/src/tests.rs
test_programs/noir_test_success/global_eval/Nargo.toml
test_programs/noir_test_success/global_eval/src/main.nr

Resolves #6691
Implements the `to_be_bits` and `to_le_bits` builtin functions in the interpreter to support `pow` and bit shifting in globals.
Check one:

feat(comptime): Implement to_be_bits and to_le_bits in the interpreter

---

tooling/lsp/Cargo.toml
tooling/lsp/src/requests/hover.rs
tooling/lsp/test_programs/workspace/two/src/lib.nr

Requested by Nico and it's something small so I decided to do it.
Similar to Rust Analyzer, when you hover over a trait impl method which doesn't have docs, show the docs of the trait method being implemented.
Check one:

feat(lsp): use trait method docs for trait impl method docs on hover

---

compiler/noirc_driver/src/lib.rs

Resolves having to hack around the code to restrict which contract function to show.
Adds a `--show-contract-fn` CLI option to restrict the effects of `--show-ssa`, `--show-ssa-pass` and `--print-acir` to a single function in a contract, ie. a single circuit. 
Example:
```
cargo run --release -p nargo_cli -- \
--program-dir $PROGRAM_DIR compile \
--package token_contract  \
--print-acir \
--show-ssa-pass "Remove IfElse" \
--show-contract-fn public_dispatch 
```
Note that `--show-ssa-pass-name` has been shortened to `--show-ssa-pass`.
Often when investigating the size increase of a contract circuit such as the `public_dispatch` function of the `Token` contract in https://github.com/AztecProtocol/aztec-packages/pull/11138#issuecomment-2582218784 I want to see the SSA, but currently running …

feat(cli): Add CLI option to filter by contract function name

---

compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs
compiler/noirc_frontend/src/elaborator/path_resolution.rs

No issue, but these produce some warnings for me locally.
It's probably because I have something wrong in my configured Rust version that I'm getting these warnings but, regardless, this code simplification is probably good.
Check one:

chore: simplify a couple of enum variants

---

compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs

Resolves 
In the vein of #7007, we can skip codegen for any for loops where we know that we're going to eventually simplify it out of the CFG. This helps mostly when numeric generics are used in for loop bounds.
Check one:

feat: skip codegen of zero iteration loops

---

compiler/noirc_evaluator/src/acir/generated_acir.rs

…sion is zero
Resolves 
We're currently creating a new witness when checking whether linear expressions are equal to zero. This is unnecessary as these will neatly fit into the following constraints (at least for direct scaling of a single witness)
Check one:

feat: avoid generating a new witness when checking if linear expression is zero

---

compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/elaborator/trait_impls.rs
compiler/noirc_frontend/src/elaborator/traits.rs
compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
compiler/noirc_frontend/src/hir_def/traits.rs
compiler/noirc_frontend/src/node_interner.rs
tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/tests.rs
tooling/lsp/src/requests/hover.rs

Towards #6956
I noticed a couple of issues in how we suggest trait methods in LSP:
1. We don't show all of the trait methods if more than one could be called (only one, the first one). That is, if there are multiple traits with the same method name and none is currently imported, all of those should be suggested.
2. Non-visible trait methods were suggested
Solving these two things required some changes on the compiler side, outside of just LSP, and to avoid eventually creating a giant PR that solves all of #6956 I decided to split just this into a smaller PR.
Check one:

fix(lsp): suggest all possible trait methods, but only visible ones

---

compiler/noirc_evaluator/src/ssa/ir/dfg.rs
compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs
compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs

Followup to #7017 
This PR removes the remaining locations where we push inc_rc instructions into ACIR. I've then made the compiler panic if it sees these being inserted again.
Check one:

feat: avoid inserting `inc_rc` instructions into ACIR

---

tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/completion_items.rs
tooling/lsp/src/requests/completion/tests.rs

Part of #6956
LSP will now auto-import a trait when completing trait methods:
There's a bug now, where if a trait is private but is exposed by a public import, the trait is imported but it leads to a "private" error:
Rust Analyzer, somehow, will suggest the first public `use` it finds for that alias... we could try to do the same thing (no idea how yet 😅) but I'd leave that to another PR.
Check one:

feat: auto-import traits when suggesting trait methods

---

noir_stdlib/src/collections/umap.nr
tooling/nargo_fmt/src/formatter/statement.rs

fix(nargo_fmt): let doc comment could come after regular comment

---

.github/workflows/reports.yml
test_programs/compilation_report.sh
test_programs/execution_report.sh

Resolves #7002
Both compilation and execution reports now accept the number of runs we should do for a command rather than depending on a boolean flag. I also unified the github jobs to pass this flag to the script rather than running a separate job depending on whether we want to take averages.
Check one:

chore(ci): Unify compilation/execution report jobs that take averages with single runs 

---

.github/critical_libraries_status/.gitignore
CRITICAL_NOIR_LIBRARIES

Resolves 
This is a dependency of the json parser library.
Check one:

chore: add `noir_check_shuffle` as a critical library

---

acvm-repo/acvm/src/compiler/mod.rs
acvm-repo/acvm/src/compiler/transformers/mod.rs

chore: reduce number of iterations of `acvm::compiler::compile`

---

Cargo.lock
compiler/noirc_evaluator/Cargo.toml
compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
compiler/noirc_evaluator/src/ssa/opt/mem2reg/alias_set.rs

Related to #7001
Alternative to #7057
Check one:

chore(perf): try using vec-collections's VecSet in AliasSet

---

.github/workflows/reports.yml
test_programs/compilation_report.sh
test_programs/memory_report.sh

chore: reenable reports on rollup root circuits

---

compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
docs/docs/noir/standard_library/meta/struct_def.md
noir_stdlib/src/cmp.nr
noir_stdlib/src/meta/mod.nr
noir_stdlib/src/meta/struct_def.nr
test_programs/compile_success_empty/comptime_struct_definition/src/main.nr
test_programs/compile_success_empty/comptime_type/src/main.nr
test_programs/compile_success_empty/derive_impl/src/main.nr

Resolves an issue from a private slack request. Needed for implementing `derive_serialize` recursively so that struct field types have their generics substituted correctly.
Adds a `generic_args` argument to `StructDefinition::fields` to instantiate the field types with. This means this PR is breaking since this method used to require only `self`.
Since the old functionality of not instantiating can still be useful, I have moved it to a new function `fields_as_written` but wanted to emphasize that if users did need field types, and they don't know what the difference is, that they should prefer to use `fields`.
Check one:

feat!: Handle generic fields in `StructDefinition::fields` and move old functionality to `StructDefinition::fields_as_written`

---

tooling/lsp/src/requests/code_action.rs
tooling/lsp/src/requests/code_action/import_trait.rs
tooling/lsp/src/requests/code_action/tests.rs

Part of #6956
This PR adds an LSP code action to import a trait, but for now only in method calls (`foo.bar()`):
In follow-up PRs I'll implement the same for function calls (`Foo::bar()`), and for `TypePath` (like `Field::foo()`)
Check one:

feat(LSP): code action to import trait in a method call

---

.github/workflows/formatting.yml
test_programs/compile_success_empty/comptime_struct_definition/src/main.nr

Resolves 
This PR adds an end step to the formatting workflow so that we can make it required.
Check one:

chore: add end step for formatting workflow

---

acvm-repo/acvm/src/compiler/optimizers/unused_memory.rs
test_programs/compile_success_no_bug/regression_7062/Nargo.toml
test_programs/compile_success_no_bug/regression_7062/src/main.nr

Resolves #7062 
The unused memory optimisation was not checking for brillig inputs
Check one:

fix: do not remove memory blocks used as brillig input

---

compiler/noirc_evaluator/src/ssa/ir/dfg.rs
compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs

Followup for https://github.com/noir-lang/noir/pull/7053
Adds a `Dfg::insert_instruction_and_results_if_simplified` method which receives the existing instruction ID from `constant_folding`, and if the instruction could not be simplified and it still matches the original value, then it's not re-inserted into the `DenseMap`, saving some memory.
In my reference test with `rollup-base-public` it reduced peak memory from 2.7GB to 2.1GB
I suppose a followup could be to try to _remove_ instructions which are no longer needed.
Noticed that `constant_folding` is involved in the peak memory usage. According to the stack trace it allocates a lot of that memory to make instructions (appears twice, with 32.1% and 13.2%):
Check one:

chore: Do not make new instruction if it hasn't changed

---

compiler/noirc_frontend/src/elaborator/mod.rs
test_programs/compile_success_empty/serialize/src/main.nr

Resolves https://github.com/noir-lang/noir/issues/7077
Fixes the kind of implicit associated types and improves their name in error messages to match the `<T as Trait>::Type` syntax a user would use.
Check one:

fix: Allow implicit associated types on integer type kinds

---

compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
compiler/noirc_frontend/src/node_interner.rs
tooling/lsp/src/requests/code_action/import_trait.rs
tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/completion_items.rs
tooling/lsp/src/requests/completion/tests.rs
tooling/lsp/src/requests/mod.rs

Part of #6956
A trait might be private in a module but publicly reexported from a parent module. That trait can be used but referring to it via the module it's in, rather than the module it's reexported from, is an error.
This PR makes LSP suggest a visible reexport if a trait is not visible where it's defined. For example, there's `std::ops::arith::Add` in the standard library, which is actually hidden but reexported as `std::ops::Add`. Here's how it works now when autocompleting `add`:
And the same thing is done in the code action that suggests importing a trait:
Rust Analyzer works the same way. I initially thought we could hardcode it just for the stdlib ops, but Rust Analyzer managed to do it with any traits I defined so I figured they track reexports and suggest those.
Check one:

feat(LSP): auto-import trait reexport if trait is not visible

---

compiler/noirc_evaluator/src/ssa/opt/inlining.rs

Resolves 
With a view to #7072, I've pulled the predicate function for whether or not to inline a call to a function so we can pass in custom logic depending on how we want to inline functions.
Check one:

chore: allow passing custom conditions to inlining pass

---

compiler/noirc_frontend/src/tests/traits.rs

Related to #7090
See https://github.com/noir-lang/noir/pull/7074#issuecomment-2595279614
Check one:

chore: add test for isuee #7090

---

compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
docs/docs/noir/standard_library/meta/struct_def.md
docs/docs/noir/standard_library/meta/trait_impl.md
docs/versioned_docs/version-v0.36.0/noir/standard_library/meta/struct_def.md
noir_stdlib/src/meta/mod.nr
noir_stdlib/src/meta/struct_def.nr
test_programs/compile_success_empty/comptime_struct_definition/src/main.nr
test_programs/compile_success_empty/eq_derivation_with_numeric_generics/Nargo.toml
test_programs/compile_success_empty/eq_derivation_with_numeric_generics/src/main.nr

Eq derivation didn't work in structs with numeric generics
This PR changes the implementation of `struct_def_generics` to return tuples of the type and the numeric type, if the type is of numeric kind.
Check one:

fix!: Include kind in `StructDefinition::generics` and fix derivation of Eq in structs with numeric generics

---

compiler/noirc_evaluator/src/ssa/ir/printer.rs

No issue just little thing I found that was bugging me. 
Printing global arrays currently looks like this:
```
g0 = Field 1
g1 = make_array [Field 1, Field 1] : [Field; 2]
g2 = Field 0
g3 = make_array [Field 0, Field 0] : [Field; 2]
g4 = make_array [v1, v3] : [[Field; 2]; 2]
```
However, the last line should look like this: `g4 = make_array [g1, g3] : [[Field; 2]; 2]`
I account for whether we are in the global space when printing elements from MakeArray. 
Check one:

chore(ssa): Use correct prefix when printing array values in global space

---

compiler/noirc_evaluator/src/ssa/opt/remove_unreachable.rs

Extracted from https://github.com/noir-lang/noir/pull/7072
Unused brillig functions were not removed by `remove_unreachable` pass because all brillig functions were considered entry points. Only subsequent Inline passes removed them, leaving extra functions to look at and process in interim passes.
Check one:

fix: Remove unused brillig functions

---

.github/workflows/reports.yml

Resolves 
This PR locks us to use ubuntu 22.04 across our CI for consistency.
Check one:

chore: lock to ubuntu 22.04

---

compiler/noirc_evaluator/src/ssa/opt/defunctionalize.rs

Extracted from https://github.com/noir-lang/noir/pull/7072
Depends on https://github.com/noir-lang/noir/pull/7100 to fix SSA parsing
Skips the creation of unnecessary blocks in the `apply` functions during `defunctionalize`, jumping straight to the return block.
At the time I thought it might play a role in the inlining cost calculation, although it might not do so, as the final jumps are not considered actual instructions I think. These blocks would be removed by a `simplify` pass, but I didn't see a reason they should be generated in the first place.
Check one:

fix: Simplify defunctionalize return

---

compiler/noirc_evaluator/src/ssa/ir/instruction.rs
compiler/noirc_evaluator/src/ssa/opt/die.rs
compiler/noirc_evaluator/src/ssa/opt/unrolling.rs

Resolves https://github.com/noir-lang/noir/issues/7104
Adds a `flattened` flag to `Function::dead_instruction_elimination` which is passed to `Instruction::can_eliminate_if_unused` to prevent [this assumption](https://github.com/noir-lang/noir/blob/a6685befe3b103b236997843f69afc07b6ea0a8c/compiler/noirc_evaluator/src/ssa/ir/instruction.rs#L534-L544) from removing the `store` instruction before the inlining, the flattening of the CFG, and mem2reg passes have happened. Thanks @vezenovm for the pointer!
Originally I thought I would have to track `&mut` block parameters as "use", but the assumptions listed in `can_eliminate_in_unused` suggested that `store` _must_ be removed from ACIR, and to stop that from happening it's enough to give it more information, so it doesn't infer whether other …

feat(ssa): Add flag to DIE pass to be able to keep `store` instructions

---

docs/docs/getting_started/quick_start.md
docs/docs/noir/concepts/data_types/slices.mdx
docs/docs/noir/concepts/generics.md

Suggestions of minor changes in docs
1. Some code section was not properly formatted due to missing ``` in quick start page
2. An extra word `for` in section of quick start page
3. `push_front` says to return an `array`
4. `pop_front` & `pop_back` say to return `array`s
5. Missing `}` in a code section in generics page
6. Calling functions with generic parameters is not executable and the comments doesn't match the code
7. Example in tubofish operator section doesn't match the comment
1. Added the missing ``` 
2. Removed the extra word
3. Changed to `slice`
4. Changed to `slice`
5. Added the `}` 
6. Added `MyStruct` implementation and changed `main` last assert to match the comment
7. Updated the code to match the comment
Check one:

chore: Formatting issues / minor errors in the docs

---

tooling/nargo_cli/src/cli/check_cmd.rs
tooling/nargo_cli/src/cli/mod.rs

fix: don't always use an exclusive lock in `nargo check`

---

.github/workflows/reports.yml

chore: remove comments for time/memory benchmarks

---

noir_stdlib/src/collections/bounded_vec.nr

feat: unconstrained optimizations for BoundedVec

---

compiler/noirc_evaluator/src/ssa/ir/printer.rs
compiler/noirc_evaluator/src/ssa/opt/normalize_value_ids.rs
compiler/noirc_evaluator/src/ssa/parser/ast.rs
compiler/noirc_evaluator/src/ssa/parser/into_ssa.rs
compiler/noirc_evaluator/src/ssa/parser/mod.rs
compiler/noirc_evaluator/src/ssa/parser/tests.rs

feat: parse globals in SSA parser

---

compiler/noirc_frontend/src/ast/statement.rs
compiler/noirc_frontend/src/ast/visitor.rs
compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/elaborator/statements.rs
compiler/noirc_frontend/src/hir/comptime/display.rs
compiler/noirc_frontend/src/hir/comptime/hir_to_display_ast.rs
compiler/noirc_frontend/src/hir/resolution/errors.rs
compiler/noirc_frontend/src/parser/parser/statement.rs
compiler/noirc_frontend/src/tests.rs
docs/docs/noir/concepts/control_flow.md
tooling/nargo_fmt/src/formatter/statement.rs

feat: `loop` must have at least one `break`

---

compiler/noirc_evaluator/src/acir/mod.rs
test_programs/execution_success/regression_7143/Nargo.toml
test_programs/execution_success/regression_7143/Prover.toml
test_programs/execution_success/regression_7143/src/main.nr

Resolves #7143
This pulls out a fix that @aakoshh made in the sync PR so we have a regression test for it.
Check one:

fix: preserve types when reading from calldata arrays

---

.github/workflows/test-rust-workspace-msrv.yml
.github/workflows/test-rust-workspace.yml

This PR runs all of our rust tests in debug mode so that we can catch overflows such as in #7143 which appear in tests.
Check one:

chore: turn on overflow checks in CI rust tests

---

tooling/lsp/src/requests/inlay_hint.rs
tooling/lsp/src/requests/mod.rs
tooling/lsp/test_programs/inlay_hints/src/main.nr

No issue, just something I wanted to originally do when implementing inlay hints but then forgot about it.
The test example:
An example from Aztec-Packages:
To be honest, there aren't that many chains in Noir code compared to usual Rust code (maybe because of iterators) but it still might make the code a bit easier to understand.
Check one:

feat: LSP chain inlay hints

---

compiler/noirc_evaluator/src/ssa/ir/dfg.rs

Does not resolve any issues, just a small optimization I noticed while working on #7109. This PR is much simpler than what #7109 requires as it checks for constants which have been already declared as globals by the program. 
I keep the `constants` context map from the DFG in the `GlobalsGraph`. Now when checking whether to reuse a value id when making a constant we also check whether that constants exists in the globals space.
Check one:

feat(ssa): Reuse constants from the globals graph when making constants in a function DFG

---

compiler/fm/src/file_map.rs
compiler/noirc_frontend/src/ast/statement.rs
compiler/noirc_frontend/src/parser/parser/module.rs
tooling/lsp/src/requests/completion.rs

No issue, just something that Rust Analyzer does but our current LSP doesn't.
Example for a "main" module:
Example for a "non-main" module:
Check one:

feat: LSP autocomplete module declaration

---

compiler/noirc_evaluator/src/brillig/brillig_gen.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_globals.rs
compiler/noirc_evaluator/src/brillig/brillig_ir.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/registers.rs
compiler/noirc_evaluator/src/brillig/mod.rs
compiler/noirc_evaluator/src/ssa/opt/unrolling.rs
cspell.json

Resolves #7107 
The `Brillig` codegen context structure now also carries a new `globals_memory_size` field. This is then used to set the globals memory size in a Brillig context. When generating an entry point the BrilligContext is now expected to have a specified globals memory size. It then uses this globals memory size to set the calldata start offset for when copying and casting calldata.
I had thought about using an atomic global for the max global size, but I felt passing a local variable was cleaner and it is more clear where the value is set.
Check one:

feat(brillig): Set global memory size at program compile time

---

tooling/lsp/src/requests/hover.rs
tooling/lsp/test_programs/workspace/two/src/lib.nr

Reported to me privately by Nico, hovering over a function with `&mut self` would show it as `self` instead of `&mut self`.
Check one:

fix: LSP hover over function with `&mut self`

---

compiler/noirc_evaluator/src/ssa/opt/inlining.rs
compiler/noirc_evaluator/src/ssa/opt/preprocess_fns.rs

chore: let `Function::inlined` take a `should_inline_call` function

---

compiler/noirc_evaluator/src/acir/mod.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_fn.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_globals.rs
compiler/noirc_evaluator/src/brillig/mod.rs
compiler/noirc_evaluator/src/ssa/ir/dfg.rs
compiler/noirc_evaluator/src/ssa/ir/printer.rs
compiler/noirc_evaluator/src/ssa/opt/die.rs
compiler/noirc_evaluator/src/ssa/opt/inlining.rs
compiler/noirc_evaluator/src/ssa/opt/normalize_value_ids.rs
compiler/noirc_evaluator/src/ssa/opt/unrolling.rs
compiler/noirc_evaluator/src/ssa/parser/into_ssa.rs
compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs
compiler/noirc_evaluator/src/ssa/ssa_gen/program.rs

No issue, but just a general refactor. We have repeated declaration of globals (the shared `globals: Arc<GlobalsGraph>` field on `DataFlowGraph` and the `globals: Function` on `Ssa`). We need the globals field on the DFG for resolving constants https://github.com/noir-lang/noir/pull/7040. However, the globals field on the `Ssa` object is only used by the SSA printer and the brillig codegen. Which in both case could use the globals graph from any function.
I removed `globals: Function` from `Ssa` and use the globals graph from a function in the places where the `Ssa` field was being used. 
Certain interfaces such as the printer and Brillig codegen still utilize the `DataFlowGraph` type so some conversions from a `GlobalsGraph` to a `DataFlowGraph` were necessary to avoid larger changes. …

chore(refactor): Remove globals field on Ssa object and use only the shared globals graph

---

compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
compiler/noirc_evaluator/src/ssa/ir/dfg.rs

Resolves https://github.com/noir-lang/noir/pull/7160#issuecomment-2610662250
This does not cause failures on master, but it does once we start to change our inlining handling in #7160 
Check one:

fix(ssa): Resolve value before fetching from DFG in a couple cases

---

compiler/noirc_evaluator/src/ssa.rs
compiler/noirc_evaluator/src/ssa/opt/inlining.rs
compiler/noirc_evaluator/src/ssa/opt/preprocess_fns.rs

Part of #7148
Pending: add a few tests for this.
Check one:

feat: inline simple functions

---

compiler/noirc_evaluator/src/ssa/opt/die.rs
compiler/noirc_evaluator/src/ssa/opt/preprocess_fns.rs
compiler/noirc_evaluator/src/ssa/opt/unrolling.rs
tooling/nargo_cli/src/cli/info_cmd.rs

Resolves failures in https://github.com/AztecProtocol/aztec-packages/pull/11294 from the preprocessing pass. https://github.com/noir-lang/noir/pull/7163 is a bit too conservative with marking that we should keep the inc rcs on any parameters. Doing so happens to also fix the test case, but marking arrays passed to terminators is the more accurate fix for how the RC tracker should be looking at mutated arrays. 
We want to make sure we do not remove inc rcs on arrays that are potentially mutated elsewhere. To do so, we check whether an array was passed to a store instruction or a call. We used to only run DIE (which removes these RCs) at the end of the SSA optimizations where we were aggressively inlining. 
Now that we are starting to process functions in isolation we triggered a bug as …

fix(ssa): Check arrays used as a terminator argument in the RC tracker 

---

compiler/noirc_frontend/src/elaborator/enums.rs
compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/elaborator/patterns.rs
compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
compiler/noirc_frontend/src/hir/def_map/module_data.rs
compiler/noirc_frontend/src/hir_def/function.rs
compiler/noirc_frontend/src/hir_def/types.rs
compiler/noirc_frontend/src/locations.rs
compiler/noirc_frontend/src/node_interner.rs
tooling/lsp/src/modules.rs
tooling/lsp/src/requests/code_action/fill_struct_fields.rs
tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/completion_items.rs
tooling/lsp/src/requests/completion/tests.rs
tooling/lsp/src/requests/hover.rs
tooling/lsp/src/requests/inlay_hint.rs
tooling/lsp/src/requests/signature_help.rs
tooling/lsp/src/requests/signature_help/tests.rs
tooling/lsp/test_programs/workspace/two/src/lib.nr

Part of #988
Now enum variants show up as they do in Rust Analyzer.
Completion:
Signature help:
Hover:
Check one:

chore(LSP): several improvements for enums and enum variants

---

tooling/lsp/src/requests/signature_help.rs
tooling/lsp/src/requests/signature_help/tests.rs

The signature shown in LSP for `assert` and `assert_eq` is slightly misleading.
Just a small thing, but some days ago Nico told me that it would be nice if the assertion failure message could be a `fmtstr` and it turns out you can use any type for it. I wrote that signature when I didn't know that was the case.
Check one:

fix(LSP): correct signature for assert and assert_eq

---

compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
compiler/noirc_frontend/src/locations.rs
compiler/noirc_frontend/src/node_interner.rs

chore: let `add_definition_location` take a Location

---

.github/workflows/reports.yml

Resolves 
We currently measure the time to download these in the compilation benchmarks (on the first iteration) so this step goes and downloads these ahead of time.
Check one:

chore: exclude dependency fetching time from benchmarks

---

compiler/noirc_evaluator/src/ssa/ir/call_stack.rs

Set the correct order for the call stack.
This fix is included in #7034, but we are waiting for the Aztec-Packages noir-sync to pass before merging it. However the sync is failing due to not having the fix.
In order to resolve this, the fix has been manually applied to the sync, and with this PR I also apply it on the Noir repo.
Check one:
- [X ] I have tested the changes locally.

fix: correct reversed callstacks

---

docs/docs/how_to/how-to-oracles.md
docs/docs/how_to/how-to-solidity-verifier.mdx
docs/docs/how_to/using-devcontainers.mdx
docs/docs/tutorials/noirjs_app.md

As decided in our mid/long-term sustainability plan, we're slowly moving out noir-starter as the go-to starter. This PR replaces them in docs by Awesome Noir

chore(docs): moving references to noir-starter to awesome-noir

---

Cargo.lock
compiler/noirc_driver/src/lib.rs
compiler/noirc_evaluator/src/ssa.rs
compiler/noirc_evaluator/src/ssa/opt/hint.rs
tooling/nargo_cli/build.rs

Resolves #7171
In light of the pass currently making protocol-cicuits unable to finish compilation, switching it off by default.
Check one:

chore(ssa): Flip the SSA Brillig constraint check to off by default

---

docs/docs/how_to/using-devcontainers.mdx

Resolves 
This PR updates documentation to use the noir devcontainer feature rather than a dockerfile.
Check one:

chore: update docs to use devcontainer feature

---

compiler/noirc_evaluator/src/ssa/ir/dfg.rs
compiler/noirc_evaluator/src/ssa/opt/defunctionalize.rs
compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs

Resolves https://github.com/noir-lang/noir/pull/7197#issuecomment-2620087708
Breaks out the defunctionalization pass changes from https://github.com/noir-lang/noir/pull/7197 into a separate PR to better look at any compilation time regressions and if we can fix them.
Check one:

chore: Rework defunctionalize pass to not rely on DFG bugs

---

.github/workflows/test-js-packages.yml

chore: start tracking time to run critical library tests

---

noir_stdlib/src/field/mod.nr

The current example always forces my brain to think, because the choice of converting `2` to base `256` doesn't actually demonstrate what to_radix does, because `2` base `256` is just `2`.
I'm suggesting using a number larger than the base instead (`259`), so that we can see that it results in `[3, 1]` and `[1, 3]` for le and be cases resp.
Check one:

chore: clarify to_radix docs examples

---

compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/monomorphization/mod.rs
compiler/noirc_frontend/src/parser/parser/expression.rs
compiler/noirc_frontend/src/parser/parser/types.rs
test_programs/compile_success_empty/resolved_type_in_constructor/Nargo.toml
test_programs/compile_success_empty/resolved_type_in_constructor/src/main.nr

From a private ask by Jan
Allows already resolved types in constructor expressions. These types are the result of comptime code and simplify creating constructors by not requiring you to specify the full path to an unresolved type - which you may not be able to get at all.
Allows, e.g:
```noir
fn main() {
// Unquotes to `let _ = Foo {}` which resolves despite Foo not being in scope
let _ = my_macro!();
}
mod foo {
pub struct Foo {}
comptime fn my_macro() {
// quote Foo without needing to specify the full path to it in the quoted snippet
let typ = quote[Foo].as_type();
quote[$typ {}]
}
}
```
Check one:

feat: Allow resolved types in constructors

---

compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/tests.rs

Resolves a private issue from slack: we errored previously when trying to call a value with a function alias type.
Check one:

fix: Avoid type error when calling something with a type alias of a function

---

compiler/noirc_frontend/src/hir/mod.rs
tooling/lsp/src/lib.rs
tooling/lsp/src/requests/code_lens_request.rs
tooling/lsp/src/requests/test_run.rs
tooling/nargo_cli/src/cli/test_cmd.rs
tooling/nargo_cli/src/cli/test_cmd/formatters.rs
tooling/nargo_cli/tests/stdlib-tests.rs

Resolves #7150
For this, no need to do `nargo test -- one two`, just doing `nargo test one two` works.
Also adds a space before "..." in nargo test output for each test because otherwise double-clicking the name would include the trailing "..." and copying that after `nargo test` wouldn't find the test. This is now the same as the output of `cargo test`.
Check one:

feat: allow specifying multiple patterns in nargo test

---

compiler/noirc_evaluator/src/ssa/ir/function.rs
compiler/noirc_evaluator/src/ssa/opt/unrolling.rs

Pulls a change out of https://github.com/noir-lang/noir/pull/7236 that was causing panics with less aggressive inliner settings. Comment for reference: https://github.com/noir-lang/noir/pull/7236#discussion_r1935634486.
I labelled this PR a fix rather than a chore as it does prevent possible panics. 
After performing an unroll in the Brillig runtime we have a setting that lets us set an upper bound on the bytecode size increase percentage. However, we have certain intrinsics (e.g. DerivePedersenGenerators) that we expect to entirely compile-time and fully resolved by Brillig gen. 
Another possible fix would be to set any method which calls `derive_generators` (such as `pedersen_hash_with_separator`) as `#[inline_always]`. However, we still do not have a guarantee that the `separator` has …

fix(ssa): Use number of SSA instructions for the Brillig unrolling bytecode size limit

---

compiler/noirc_evaluator/src/ssa/opt/unrolling.rs

Resolves silly bug from https://github.com/noir-lang/noir/pull/7242
Actually use the original function for fetching the bytecode size.
Check one:

fix(unrolling): Fetch original bytecode size from the original function

---

compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs

Resolves a comment: https://github.com/AztecProtocol/aztec-packages/pull/11294/files/feca4ed10f4978832b51d39d3c055a972073826f#r1937967005
This check shouldn't have caused any existing bugs since enums are still experimental, but we'll need it going forward if people want to generate new enums in comptime code.
Check one:

fix: Add missing `is_empty` check for enums

---

compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
test_programs/compile_success_empty/comptime_enums/src/main.nr

Resolves https://github.com/noir-lang/noir/issues/7249
Also includes a small refactor since neither `zeroed` nor `option` needed to return Results.
Check one:

feat(experimental): Implement zeroed for enums

---

tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/completion_items.rs
tooling/lsp/src/requests/completion/tests.rs

Now that enum variants without parameters can be referenced without `()`, those variants weren't offered in LSP completion.
Let's LSP suggest enum variants without parameters.
Also changes these completions to use the `EnumMember` kind so that they end up with a different icon than the one for functions. Finally, also changes the icon for enum types themselves (previously they would use the icon for structs).
Check one:

feat(LSP): suggest enum variants without parameters

---

compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs

Resolves 
This adds a quick fix for the panic in https://github.com/AztecProtocol/aztec-packages/pull/11696 that @vezenovm raised. 
I (or someone) needs to look at this more closely as we should potentially distinguish between local and global arrays here. For the time being it fixes the panic however.
Check one:

fix: prevent panic within `remove_possibly_mutated_cached_make_arrays`

---

compiler/noirc_evaluator/src/ssa.rs
compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs

Silly bug leftover from https://github.com/noir-lang/noir/pull/7260, but also fixes this removal pass to be more accurate. We are not checking the new call graph of unused functions.
e.g. for the following SSA:
```
g0 = Field 2
acir(inline) fn main f0 {
b0():
v1 = call f1() -> Field
return v1
}
brillig(inline) fn entry_point f1 {
b0():
v1 = call f2() -> Field
return v1
}
brillig(inline) fn one f2 {
b0():
v1 = add g0, Field 3
return v1
}
```
After constant folding we would still have:
```
brillig(inline) fn one f2 {
b0():
v1 = add g0, Field 3
return v1
}
```
even though it would be unused. This is because we would only inline Brillig calls for ACIR entry points. Thus, we would still have a call to f2, even though f1 is now unused, thus f2 is also unused.
I simply moved to using our …

fix(ssa): Unused functions removals post folding constant Brillig calls

---

compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/elaborator/statements.rs
compiler/noirc_frontend/src/tests.rs

Follow up to https://github.com/noir-lang/noir/pull/7088 with more scenarios where we can infer the type of lambda parameters
These are just for completeness. There are actually a couple of these cases in Aztec-Packages, but I just thought at this point it's relatively straight-forward to implement this, and it's also how it works in Rust (I mean semantically, not how it's implemented).
It's fine if you think this isn't worth it, it's mostly experimental and for completeness.
I'm also unsure about how the code ended up looking like, though I tried to avoid modifying existing code as much as possible.
Check one:

feat: infer lambda parameter types from return type and let type

---

EXTERNAL_NOIR_LIBRARIES.yml

Resolves 
This adds the sha256 library to our suite of libraries to check against.
Check one:

chore: add sha256 library to test suite

---

.github/actions/download-nargo/action.yml
.github/workflows/formatting.yml
.github/workflows/reports.yml
.github/workflows/test-js-packages.yml

Resolves 
This adds an action which downloads nargo from an artifact and adds it to the path.
Unsure if this will work due to being in an action context. :shrug: 
Check one:

chore: create a CI action to download nargo and add to path

---

compiler/noirc_evaluator/src/acir/acir_variable.rs
compiler/noirc_evaluator/src/acir/mod.rs
compiler/noirc_evaluator/src/ssa/ir/instruction.rs
compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs
test_programs/execution_success/signed_inactive_division_by_zero/Nargo.toml
test_programs/execution_success/signed_inactive_division_by_zero/Prover.toml
test_programs/execution_success/signed_inactive_division_by_zero/src/main.nr

Resolves #7283 
This PR fixes an issue where division and modulo operations were marked as only requiring a predicate in the case where it's acting on an unsigned type. This is incorrect as we need to handle a zero denominator for field and signed integer types.
This showed that we weren't handling predicates related to signed division more generally so I've rolled that into this PR.
Check one:

fix: mark field division and modulo as requiring predicate for all necessary types

---

compiler/noirc_evaluator/src/ssa.rs

If you used `--show-ssa-pass` it would sometimes crash depending on the program.
Resolves #7235
I'm not sure why that is the case, but it works fine with `--show-ssa` which normalized the SSA after every pass. As a quick fix, we now also always normalize the SSA after every pass, but we just print the relevant pass(es) if we are told to do so.
Check one:

fix: always normalize ssa when priting at least one pass

---

compiler/noirc_frontend/src/parser/parser/item.rs

Resolves #7298
The issue was that the relevant snippt:
```noir
pub contract ScarySlash {
fn what() {}
/// docs:end:exit_to_l1_private
}
```
should have produced an error in the first place. That's what this PR does.
Check one:

fix: error on trailing doc comment

---

compiler/noirc_frontend/src/ast/expression.rs
compiler/noirc_frontend/src/ast/mod.rs
compiler/noirc_frontend/src/ast/statement.rs

I noticed `Recoverable` is unused, probably a left-over from the chumsky parser.
Check one:

chore: remove Recoverable

---

.github/workflows/reports.yml
.github/workflows/test-js-packages.yml
noir_stdlib/src/cmp.nr

feat: simplify `Ord` implementation for arrays

---

.github/workflows/reports.yml
.github/workflows/test-js-packages.yml
EXTERNAL_NOIR_LIBRARIES.yml

chore: add timeouts to reports CI

---

test_programs/execution_success/signed_cmp/Prover.toml
test_programs/execution_success/signed_div/Prover.toml
tooling/noir_js/test/node/cjs.test.cjs
tooling/noir_js/test/node/smoke.test.ts
tooling/noirc_abi/src/errors.rs
tooling/noirc_abi/src/input_parser/json.rs
tooling/noirc_abi/src/input_parser/mod.rs
tooling/noirc_abi/src/input_parser/toml.rs

Resolves #7304
I accidentally started fixing this when parsing strings, but I think that's also good to have. (edit: it turns out the original issue was about strings 😅)
Then I added a similar check for integers... though here we only need to check the maximum value because input values are always unsigned (~is there a reason for this?~ -> this PR now also allows negative integers in at least Prover.toml (I hope that's fine!)).
Finally, I noticed that the error message produced in this case was very barebones: it didn't mention which parameter name errored. So now that's shown, and also if the value is inside an array, that index is shown (a similar thing is done for tables where we show which field we are in).
The error shown for the program in #7304 is now this:
```
The value passed for …
```

fix!: check abi integer input is within signed range

---

EXTERNAL_NOIR_LIBRARIES.yml

Resolves https://github.com/noir-lang/noir/pull/7317#issuecomment-2643320036
Check one:

chore: bump noir_bigcurve timeout

---

compiler/noirc_frontend/src/lexer/lexer.rs
compiler/noirc_frontend/src/tests.rs

Resolves #6975
Turns recursion into a loop for skipping comments.
Check one:

fix: avoid stack overflow on many comments in a row

---

tooling/nargo/src/constants.rs
tooling/nargo/src/workspace.rs

Resolves 
These are leftovers from the split of nargo and bb
Check one:

chore: remove unnecessary constants

---

tooling/nargo_cli/src/cli/mod.rs
tooling/nargo_cli/tests/hello_world.rs

Resolves 
This removes a `./` from within the printed path which was bugging me.
Check one:

chore: normalize path displayed by `nargo new`

---

compiler/noirc_evaluator/src/ssa.rs
test_programs/compile_success_no_bug/regression_7292/Nargo.toml
test_programs/compile_success_no_bug/regression_7292/src/main.nr

Resolves #7292 
We're currently performing the safety checks on the SSA before we do constant folding with brillig calls. This prevents bugs being shown for unconstrained calls which are optimized out. 
Check one:

fix: perform SSA constraints check on final SSA

---

Cargo.lock
tooling/nargo_toml/Cargo.toml
tooling/nargo_toml/src/flock.rs
tooling/nargo_toml/src/git.rs
tooling/nargo_toml/src/lib.rs

Resolves 
This PR adds a simple file lock on the `~/nargo` directory to prevent two instances of nargo attempting to download dependencies into the same folder at the same time.
This can't cause deadlock with the nargo.toml file lock.
Check one:

fix: lock git dependencies folder when resolving workspace

---

cspell.json

Resolves https://github.com/noir-lang/noir/actions/runs/13248973880/job/36982121704?pr=7341.
I'm getting cspell errors on various PRs after merging master. I guess it no longer accepts `Vecs` and `vecs.
Add Vecs and vecs to cspell.
Check one:

chore(ci): Add Vecs and vecs to cspell

---

compiler/noirc_frontend/src/ast/expression.rs
compiler/noirc_frontend/src/ast/mod.rs
compiler/noirc_frontend/src/ast/statement.rs
compiler/noirc_frontend/src/ast/type_alias.rs

While working on #7333 I noticed some types and functions were never called. They are probably a left-over from the old parser.
Check one:

chore: remove some unused types and functions in the AST

---

tooling/lsp/src/notifications/mod.rs

While working on #7333 I noticed secondary errors land on an incorrect file, so I extracted just this change here.
Check one:

fix: incorrect secondary file in LSP errors

---

noir_stdlib/src/hash/sha256.nr
noir_stdlib/src/sha256.nr

Part of #1258 
This PR adds deprecation warnings into the stdlib directing people to use https://github.com/noir-lang/sha256 instead.
Check one:

chore: mark sha256 as deprecated from the stdlib

---

acvm-repo/brillig_vm/src/arithmetic.rs

Resolves 
This PR replaces the current integer arithmetic functions in the brillig VM which treat all values as u128s with a proper generic function which allows us to simply cast down to the relevant type, do the operation and then cast back up to u128.
I've implemented the solver for `U1` as working on boolean types as rust doesn't have a u1 type, this could probably do with some scrutiny.
Check one:

chore: avoid doing all brillig integer arithmetic on u128s

---

compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs
compiler/noirc_evaluator/src/ssa/opt/unrolling.rs

Resolves #7353 
This is an expansion of the optimization from https://github.com/noir-lang/noir/pull/7344 and https://github.com/noir-lang/noir/pull/6910. In those PRs we simply handled add/mul operations as they only needed to be checked against the upper bound of a loop. This PR now tracks the lower bounds of our induction variables and special cases for when the induction variable is on the LHS during a sub operation. 
I have added a basic unit test for when the induction var is on the LHS of a sub operation with a lower bound that would trigger an overflow.
Check one:

feat(performance): Check sub operations against induction variables

---

compiler/noirc_frontend/src/elaborator/patterns.rs
compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
compiler/noirc_frontend/src/hir/comptime/value.rs
compiler/noirc_frontend/src/lexer/token.rs
docs/docs/noir/standard_library/meta/function_def.md
noir_stdlib/src/meta/function_def.nr
test_programs/compile_success_empty/comptime_function_definition/src/main.nr

Resolves #7314
Resolves #7315
Will make https://github.com/AztecProtocol/aztec-packages/issues/11863 possible.
First adds `FunctionDefinition::as_typed_expr`, which does the same logic of type-checking the function and turning it into an `ExprId`.
Then, allows unquoting `TypedExpr` in a way that preserves the underlying `ExprId`.
In the code there's a `let generics = None;`. Those would be the generics resulting from turbofish on the function. Eventually we could add a `as_typed_expr_with_turbofish` or similar that takes a `[Type]` for for the generics... if really needed.
Check one:

feat: `FunctionDefinition::as_typed_expr`

---

tooling/lsp/src/requests/mod.rs
tooling/nargo_fmt/build.rs
tooling/nargo_fmt/src/config.rs
tooling/nargo_fmt/src/errors.rs

Resolves #7340
Also changes the logic of `nargo fmt` to try to find the configuration file in the current directory or parent directories.
It seems `rustfmt` also allows the config file to be called ".rustfmt.toml", or for it to be placed in the global config directory (`.config/rustfmt/`) but those could be done in follow-up PRs.
Check one:

fix: let LSP read `noirfmt.toml` for formatting files

---

docs/docs/noir/concepts/data_types/integers.md

Resolves #7367
The code in the docs doesn't end up producing an overflow so here it's changed to do so. Also an explanation of when overflows might not be triggered is added.
Check one:

chore: update docs about integer overflows

---

compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/hir/resolution/errors.rs

Resolves #7080
The issue seems to have been fixed in a past PR (I can't remember which one) but with a misleading error about using unquote. This PR changes the error to something more accurate.
Check one:

fix: give "correct" error when trying to use AsTraitPath

---

acvm-repo/brillig_vm/src/arithmetic.rs
acvm-repo/brillig_vm/src/black_box.rs
acvm-repo/brillig_vm/src/lib.rs
acvm-repo/brillig_vm/src/memory.rs

Resolves 
This PR avoids creating references which will then immediately be dereferenced within the brillig VM. I've also switched a lot of usage of `TryFrom` methods over to use the `expect_uN` methods in order to be explicit.
Check one:

chore: remove unnecessary dereferencing within brillig vm

---

acvm-repo/brillig_vm/src/arithmetic.rs
acvm-repo/brillig_vm/src/lib.rs

Brillig VM allowed division by zero for field operations
Added validation to prevent division by zero in field operations, with a regression test to verify the fix. 
Check one:

fix: field zero division in brillig

---

compiler/noirc_evaluator/src/ssa/ir/instruction.rs
compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs

No issue just a bug I found while working on other tasks.
If the rhs of a div/mod was a zero we would `false` from `requires_acir_gen_predicate`. This would also deduplicating a div/mod by a zero constant.
e.g. this SSA:
```
acir(inline) fn main f0 {
b0(v0: u32, v1: u32, v2: u1):
enable_side_effects v2
v4 = div v1, u32 0
v5 = not v2
enable_side_effects v5
v6 = div v1, u32 0
return
}
```
would turn into this SSA:
```
acir(inline) fn main f0 {
b0(v0: u32, v1: u32, v2: u1):
enable_side_effects v2
v4 = div v1, u32 0
v5 = not v2
enable_side_effects v5
return
}
```
If `v2` was inactive and `v5` was active, we would miss needing to fail when processing the second division.
Check one:

fix(ssa): Do not deduplicate division by a zero constant

---

Cargo.lock
compiler/noirc_evaluator/proptest-regressions/acir/acir_variable.txt
compiler/noirc_evaluator/proptest-regressions/ssa/ir/instruction/binary.txt
compiler/noirc_evaluator/src/acir/acir_variable.rs
compiler/noirc_evaluator/src/acir/generated_acir.rs
compiler/noirc_evaluator/src/acir/mod.rs
compiler/noirc_evaluator/src/ssa/ir/instruction.rs
compiler/noirc_evaluator/src/ssa/ir/instruction/binary.rs
compiler/noirc_printable_type/Cargo.toml
compiler/noirc_printable_type/src/lib.rs

Resolves 
This PR pulls out some refactorings from #7301 which are helpful but not explicitly connected to adding u128s.
Check one:

chore: pull out refactored methods from u128 branch

---

compiler/noirc_frontend/src/hir/comptime/display.rs
compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
compiler/noirc_frontend/src/hir/comptime/value.rs

Resolves 
Followup to #7373 
Check one:

chore: box `ExprValue` in `Value` enum

---

.github/workflows/reports.yml
.github/workflows/test-js-packages.yml

Resolves 
See https://github.com/noir-lang/noir/pull/7388#issuecomment-2660017557
This PR allows printing of the benchmarks into the PR comments if the `bench-show` label is set.
Check one:

chore: allow opting in to displaying benchmark comments

---

compiler/noirc_frontend/src/hir/comptime/interpreter.rs
compiler/noirc_frontend/src/hir/comptime/value.rs

Follow-up to #7388
This makes `Value` go from 280 to 152 bytes. Doing `nargo check` on `rollup-base-private` I notice a slight improvement, maybe not much but this is an easy change.
Check one:

chore: box `Closure` in `comptime::Value` enum

---

.github/benchmark_projects.yml
.github/workflows/reports.yml
.github/workflows/test-js-packages.yml
EXTERNAL_NOIR_LIBRARIES.yml

Resolves 
This PR pushes the config for all of our benchmarking projects out into a separate file similar to the external repo checks. I've also added a fixed commit for aztec packages which we can test against.
Check one:

chore(ci): lock aztec-packages commit in CI

---

noir_stdlib/src/merkle.nr

Resolves 
This function should really not be in the stdlib so I'm deprecating it so we can remove it after the next release goes out.
Check one:

chore: deprecate `merkle` module of stdlib

---

compiler/noirc_frontend/src/hir/comptime/errors.rs
test_programs/compile_failure/primary_attribute_struct/src/main.nr
test_programs/compile_success_empty/trait_method_mut_self/src/main.nr
test_programs/execution_success/brillig_conditional/src/main.nr
tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/tests.rs

Thanks maximevtush for https://github.com/noir-lang/noir/pull/7420. Our policy is to redo typo changes to dissuade metric farming. This is an automated script.

chore: redo typo PR by maximevtush

---

compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
compiler/noirc_frontend/src/locations.rs
compiler/noirc_frontend/src/node_interner.rs
tooling/lsp/src/modules.rs
tooling/lsp/src/requests/code_action.rs
tooling/lsp/src/requests/code_action/import_or_qualify.rs
tooling/lsp/src/requests/code_action/import_trait.rs
tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/auto_import.rs
tooling/lsp/src/requests/completion/completion_items.rs
tooling/lsp/src/requests/completion/tests.rs
tooling/lsp/src/requests/mod.rs
tooling/lsp/src/trait_impl_method_stub_generator.rs
tooling/lsp/src/visibility.rs

Resolves #7378
This is a new feature but also a bug fix.
The bug was that if a type was directly visible from the current module it was offered for autocompletion. However, that didn't take into account if the type was actually in a crate that's in one of the current crate's dependencies. That's why in the original issue `protocol_types::traits::Packable` was offered: if it were a dependency it's good to suggest that... but it's not!
Then the feature is that we now track all of an item's reexports (not just traits). Then, if the item isn't directly visible we search for that item's parent module's reexports. If there's one visible, we can suggest importing the item via the parent module's reexport. This is done recursively so that if the parent doesn't have a reexport but the grandparent …

feat(LSP): auto-import via visible reexport

---

compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs

No issue, small optimization I found while exploring other Brillig gen optimizations.
For every slice access, we code gen a slice access check against its dynamic index: https://github.com/noir-lang/noir/blob/988adae231c1aca09fd4d08d5e7bf5e72deecf9d/compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs#L475
In Brillig gen we use `!dfg.is_safe_index` to determine whether to code gen an array index. This always returns false for slice types as we cannot check against their length. However, we already have generated a check the precedes the array access. We should generate this validation code for array types in Brillig gen.
Check one:

fix(performance): Remove redundant slice access check from brillig

---

docs/docs/explainers/cspell.json
docs/docs/tooling/cspell.json
docs/docs/tooling/security.md

Adds a short description of the SSA security passes in `docs/docs/tooling/security.md` (per @Rumata888's suggestion).
Resolves #6707 
Check one:

chore: Add SSA security checks description

---

compiler/noirc_evaluator/src/ssa/ir/instruction/constrain.rs

Something I noticed when reviewing #7301 
We currently don't simplify 
```
v1 = mul v0, v0
constrain v1 == u1 0
```
into
```
constrain v0 == u1 0
```
I've then added this as an optimization when decomposing constraints.
This looks like it should be safe to me due to us using a prime field so there's no nonzero solutions to `v0 * v0 == 0`.
Check one:

feat: simplify assertions that squared values are equal to zero

---

compiler/noirc_frontend/src/ast/expression.rs
compiler/noirc_frontend/src/ast/statement.rs
compiler/noirc_frontend/src/elaborator/enums.rs
compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/elaborator/statements.rs
compiler/noirc_frontend/src/tests.rs

Resolves #7408
In addition to that:
1. It fixes an issue where the error span when the "then" and "else" branches of an "if" didn't match was wrong (I introduced that bug some weeks ago)
2. A new feature where some type errors will now point to more precise spans
For point 2, here's the error you got when the branches of an "if" didn't match:
And this is how it looks now:
That is, for a given expression we now point the type mismatch in the innermost expression that gives it its type.
The same is done for loops:
I made this change in places where a block usually happens. We could eventually do it in other places (prefix expression, index expressions, call arguments, etc.) as we find them, though using blocks there is pretty rare.
Check one:

fix: require loop/for/while body to be unit

---

compiler/noirc_frontend/src/hir/comptime/interpreter.rs
compiler/noirc_frontend/src/parser/parser/global.rs
test_programs/compile_success_empty/regression_7433/Nargo.toml
test_programs/compile_success_empty/regression_7433/src/main.nr

…
Resolves #7433 
We are currently throwing away the sign when evaluating `Field` type literals in the interpreter which causes nasty weird behaviour as seen in #7433. I've updated the interpreter to negate the field properly in this case.
A regression test has been added along with a sanity check test I wrote while debugging to ensure that we parse these correctly.
Check one:

fix: do not discard negative sign from field literals in comptime interpreter

---

compiler/noirc_frontend/src/parser/parser/doc_comments.rs
compiler/noirc_frontend/src/parser/parser/expression.rs
compiler/noirc_frontend/src/parser/parser/statement.rs
tooling/nargo_fmt/src/formatter/expression.rs

Resolves #7394
It seems that Rust allows doc comments on top of statements and expressions, but warns if that happens. That's also the case now in Noir except that the formatter didn't support doc comments on top of expressions. This PR fixes that, but also documents the code to say that all of this is expected, and refactors the code a bit.
(so this PR doesn't do what #7394 says, but warning instead of erroring is probably better, especially if Rust does the same thing)
Check one:

chore: standardize that doc comments on top of statements and expression are allowed but warn

---

docs/versioned_docs/version-v1.0.0-beta.2/noir/concepts/traits.md

Copy https://github.com/noir-lang/noir/pull/7387's doc updates into v1.0.0-beta.2's versioned_docs.
Check one:

chore: Copy #7387 docs into v1.0.0-beta.2 versioned_docs

---

.github/workflows/publish-nargo.yml

Resolves #7438 
I was thinking we could resolve the above issue and then make individual issues for new binaries we are ready to add to our releases (e.g. the artifact_cli)
Add `noir-inspector` binary to our releases.
Check one:

feat(ci): Release noir-inspector in binaries

---

Cargo.lock
acvm-repo/acir_field/Cargo.toml
acvm-repo/acir_field/benches/field_element.rs
acvm-repo/acir_field/src/field_element.rs

No issue. While sampling a compilation it landed on `FieldElement::num_bits` so I was wondering if optimizing it would have any visible effect.
Before this PR `num_bits` would allocate the bytes in `Vec`, now I think there would be no allocations.
I didn't try it locally but it was a simple optimization so trying it here to see what CI says.
Check one:

feat: optimize FieldElement::num_bits

---

compiler/noirc_driver/src/lib.rs

Resolves 
> Disables the builtin Aztec macros being used in the compiler
what_year_is_it.jpg
Check one:

chore: remove `disable_macros` compile option

---

.github/benchmark_projects.yml
EXTERNAL_NOIR_LIBRARIES.yml

Automated update of the pinned commit of [aztec-packages](https://github.com/AztecProtocol/aztec-packages) repository against which we run benchmarks.

chore: bump external pinned commits

---

compiler/noirc_frontend/src/debug/mod.rs

Resolves #7479
I thought about adding a test for this but the infrastructure for that is in https://github.com/noir-lang/noir/pull/7233 which is not yet merged.
Check one:

fix: don't use dummy location when inserting debug code

---

docs/docs/tooling/profiler.md
docs/versioned_docs/version-v1.0.0-beta.3/tooling/profiler.md

No issue just observed when looking at the docs. 
Images were not correctly referenced in the profiler docs so this is what we would see instead:
We now display the correct images. From the docs preview:
Check one:

chore(docs): Profiler images reference

---

tooling/profiler/src/cli/execution_flamegraph_cmd.rs
tooling/profiler/src/cli/gates_flamegraph_cmd.rs
tooling/profiler/src/cli/opcodes_flamegraph_cmd.rs
tooling/profiler/src/flamegraph.rs

No issue, just a QOL improvement I found while doing other documentation.
We are using the brillig function index when writing a flamegraph file. 
e.g. Running `noir-profiler opcodes` on this program:
```noir
fn main(ptr: pub u32, mut array: [u32; 5]) -> pub [u32; 5] {
// Safety: Sets all elements after `ptr` in `array` to zero.
let new_array = unsafe { write_to_array(ptr, array) };
for i in 0..5 {
if i > ptr {
assert_eq(new_array[i], 0);
} else {
assert_eq(new_array[i], array[i]);
}
}
new_array
}
unconstrained fn write_to_array(ptr: u32, mut array: [u32; 5]) -> [u32; 5] {
for i in 0..5 {
if i > ptr {
array[i] = 0;
}
}
array
}
```
Will result in the following flamegraph files: `main_opcodes.svg`, `0_brillig_opcodes.svg`, `1_brillig_opcodes.svg`, `2_brillig_opcodes.svg`. The indices are …

chore(profiler): Use brillig names for outputted flamegraphs 

---

compiler/noirc_frontend/src/elaborator/enums.rs
compiler/noirc_frontend/src/hir/resolution/errors.rs
compiler/noirc_frontend/src/tests.rs

Resolves https://github.com/noir-lang/noir/issues/7424
Fairly straightforward change.
Check one:

fix(experimental): Allow shadowing in match patterns

---

compiler/noirc_evaluator/src/ssa/ir/dfg.rs

No issue but something I noticed while working towards Brillig execution trace optimizations. 
We flatten complex types within arrays. 
For example this program:
```noir
struct Foo {
bar: Field,
baz: Field,
}
fn main(foos: [Foo; 3]) -> pub Field {
foos[2].bar + foos[2].baz
}
```
Will have the following SSA:
```
brillig(inline) fn main f0 {
b0(v0: [(Field, Field); 3]):
v2 = array_get v0, index u32 4 -> Field
v4 = array_get v0, index u32 5 -> Field
v5 = array_get v0, index u32 4 -> Field
v6 = array_get v0, index u32 5 -> Field
v7 = add v2, v6
return v7
}
```
When it comes times to generate Brillig we will check whether to generate bytecode for array index validation by checking this method:
https://github.com/noir-lang/noir/blob/8e68ce6403e99ff5af4fb9973b203070d8a9898c/compiler/noirc_evaluat …

fix(performance): Accurately mark safe constant indices for arrays of complex types

---

compiler/noirc_frontend/src/ast/expression.rs
compiler/noirc_frontend/src/ast/statement.rs
compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/hir/comptime/hir_to_display_ast.rs
compiler/noirc_frontend/src/hir/comptime/value.rs
compiler/noirc_frontend/src/parser/parser/expression.rs
test_programs/compile_success_empty/unquote_struct/src/main.nr
tooling/lsp/src/with_file.rs

Something I noticed while reviewing https://github.com/noir-lang/noir/pull/7489
`ConstructorExpression` has a field, `struct_type`, that stores a resolved type from macro expansion. Instead of it we can use `Type::Resolved` for the actual type inside an unresolved type. This works the same way but there's one less field needed.
Additionally, this actually allows more valid programs to compile. For example this one:
```noir
use std::meta::unquote;
struct Foo<T> {}
fn main() {
let x = comptime {
let x = quote { Foo::<i32> };
let q = quote { $x {} };
unquote!(q)
};
}
```
Previously when unquoting `Foo::<i32>` as `$x` the generics were lost, so the above program errored with "Type annotation needed". Now the above program compiles fine.
Check one:

feat: use resolved type instead of needing Constructor.struct_type

---

compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/elaborator/patterns.rs
compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/hir/comptime/interpreter.rs
compiler/noirc_frontend/src/node_interner.rs
compiler/noirc_frontend/src/tests.rs

Resolves #7483
~The first commit has the fix. The second one is a refactor.~
It turned out the first commit fixed the bug but introduced another one. So there's a third (fourth, after merge) commit that fixes both. The idea is to always store the type methods are added to and later check this type against the type a method is being added to.
Check one:

fix: issue duplicate error on impl function without self

---

docs/docs/how_to/how-to-solidity-verifier.mdx
docs/versioned_docs/version-v1.0.0-beta.2/how_to/how-to-solidity-verifier.mdx
docs/versioned_docs/version-v1.0.0-beta.3/how_to/how-to-solidity-verifier.mdx

zkSync reported that `modexp` should be an EVM precompile required for Barretenberg's Solidity verifier, but it is not currently documented.
This PR supplements documentation of `modexp` being required, alongside minor wording updates on the section to improve readability.
The Barretenberg team advised the opcode is used for field inversions.
Check one:

chore(docs): Supplement docs on `modexp` as a required precompile for Barretenberg's Solidity verifier

---

compiler/noirc_evaluator/src/ssa/ir/instruction.rs

Resolves 
We previously wouldn't optimize out a range check where the value fits exactly into the specified number of bits. This PR adds handling for the edge case along with a smoke test.
Check one:

feat: optimize out range checks on limiting cases

---

compiler/noirc_frontend/src/elaborator/mod.rs
test_programs/compile_failure/broken_impl/Nargo.toml
test_programs/compile_failure/broken_impl/src/main.nr

I noticed that LSP would crash whenever starting to write an impl's generics. It was because the compiler actually crashed.
This PR prevents this crash.
I'll try to fix LSP crashes as soon as I find them because I heard LSP crashes often.
Check one:

fix: don't crash on broken impl syntax

---

EXTERNAL_NOIR_LIBRARIES.yml

Resolves 
Unblock current PRs by bumping the time allowed to compile base64 by 1s.
I elected not to lock us to a given commit in this PR since we have many external repos that may need to be locked to a commit for similar reasons. So I preferred consistency and unblocking current PRs quickly. We could maybe have a discussion in the future on whether more or all repos should be locked to a commit.
Check one:

chore: Increaes base64's allotted time

---

tooling/nargo_fmt/src/formatter/traits.rs
tooling/nargo_fmt/src/formatter/where_clause.rs

No issue, just something I noticed while working on something else.
The bug was that the comma separating the two where clauses was missing after formatting.
Check one:

fix: correctly format trait function with multiple where clauses

---

compiler/noirc_frontend/src/elaborator/enums.rs
compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/hir/resolution/errors.rs
compiler/noirc_frontend/src/tests.rs
compiler/noirc_frontend/src/tests/enums.rs
test_programs/compile_success_empty/enums/src/main.nr

Resolves 
Replaces most remaining panic/println cases in the match compiler with friendly user errors.
The only two remaining errors are what I consider to be the meatier ones: redundant cases & unhandled cases since these require more analysis of the match tree itself. The later also typically requires constructing an example of a value that wouldn't be matched as part of the error message.
I've moved the frontend tests which deal with enums & matches to a new `tests/enums.rs` file since the frontend tests file is quite large. I'll add a comment noting where the new tests in this file are - the old ones are unchanged.
Check one:

fix(experimental): Replace most remaining match panics with errors

---

Cargo.lock

chore: revert bump of base64ct to `v1.6.0` after `v1.7.0` yanked

---

compiler/noirc_frontend/src/parser/parser.rs
compiler/noirc_frontend/src/parser/parser/expression.rs
compiler/noirc_frontend/src/parser/parser/statement.rs

fix: fix a few cases where safety comment wasn't correctly identified

---

.gitignore
acvm-repo/acvm/src/pwg/arithmetic.rs
acvm-repo/acvm/src/pwg/blackbox/hash.rs
acvm-repo/acvm/src/pwg/blackbox/range.rs
acvm-repo/blackbox_solver/src/curve_specific_solver.rs

Resolves 
Some small test changes I made while experimenting with https://github.com/sourcefrog/cargo-mutants
Check one:

chore: add some extra tests

---

compiler/noirc_driver/src/lib.rs
compiler/noirc_driver/tests/contracts.rs
compiler/noirc_errors/src/lib.rs
compiler/noirc_errors/src/reporter.rs
compiler/noirc_evaluator/src/errors.rs
compiler/noirc_frontend/src/hir/def_collector/errors.rs
compiler/noirc_frontend/src/hir/resolution/errors.rs
compiler/noirc_frontend/src/hir/type_check/errors.rs
compiler/noirc_frontend/src/monomorphization/errors.rs
compiler/wasm/src/compile.rs
compiler/wasm/src/compile_new.rs
compiler/wasm/src/errors.rs
tooling/lsp/src/notifications/mod.rs
tooling/lsp/src/requests/test_run.rs
tooling/nargo/src/errors.rs
tooling/nargo/src/ops/check.rs
tooling/nargo/src/ops/test.rs
tooling/nargo_cli/src/cli/export_cmd.rs
tooling/nargo_cli/src/cli/fmt_cmd.rs
tooling/nargo_cli/src/cli/test_cmd/formatters.rs

Addresses this comment: https://github.com/noir-lang/noir/pull/7486#discussion_r1967841707
Now that `CustomDiagnostic` almost always carries a Location, I change it to also always carry a `file: FileId` so that we no longer need an extra `FileDiagnostic` type, and code becomes a bit simpler.
Check one:

chore: remove FileDiagnostic

---

compiler/noirc_frontend/src/ast/expression.rs
compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/elaborator/statements.rs
compiler/noirc_frontend/src/elaborator/traits.rs
compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/hir/def_collector/errors.rs
compiler/noirc_frontend/src/hir/resolution/errors.rs
compiler/noirc_frontend/src/hir/type_check/errors.rs
compiler/noirc_frontend/src/hir_def/types.rs
compiler/noirc_frontend/src/node_interner.rs
compiler/noirc_frontend/src/parser/parser/function.rs
compiler/noirc_frontend/src/tests.rs
compiler/noirc_frontend/src/tests/enums.rs
compiler/noirc_frontend/src/tests/traits.rs
tooling/lsp/src/requests/document_symbol.rs

Part of #7540
Addresses the TODOs that are straight-forward to solve. I left others which are a bit more complex.
Check one:

chore: address some frontend tests TODOs

---

.github/benchmark_projects.yml
EXTERNAL_NOIR_LIBRARIES.yml
compiler/noirc_evaluator/src/ssa/ir/instruction/call.rs
compiler/noirc_evaluator/src/ssa/ir/instruction/call/blackbox.rs

feat: perform constant sha256 compressions at compile-time

---

tooling/acvm_cli/src/main.rs
tooling/artifact_cli/src/bin/execute.rs
tooling/nargo_cli/src/main.rs
tooling/profiler/src/main.rs

Resolves something I noticed while reviewing https://github.com/noir-lang/noir/pull/7578
The `profiler` to `stdout`, while also aims to display information that the users should be able to pick up in scripting, which is made difficult if log messages and program output are mixed. The solution is to send all logs to `stderr`, in which case piping the output to another program ignores it unless it's redirected with `2>&1`. 
I tested that the default behaviour of `tracing_subscriber` was indeed to log to `stdout` by adding a `tracing::info!(<msg>)` call and looking for the message with `| grep <msg>`, which was highlighted with red. If we apply the changes in this PR, it is no longer highlighted, as it appears on `stderr`.
Check one:

fix: Log to `stderr`

---

compiler/noirc_frontend/src/elaborator/enums.rs
compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/hir/type_check/errors.rs
compiler/noirc_frontend/src/hir/type_check/mod.rs
compiler/noirc_frontend/src/hir_def/expr.rs
compiler/noirc_frontend/src/hir_def/types.rs
compiler/noirc_frontend/src/signed_field.rs
compiler/noirc_frontend/src/tests/enums.rs

Resolves 
Issues a missing case(s) error for match expressions missing any cases. This includes constructing an example of a value which fails to match.
~~Limitation: if the match doesn't match on any cases such as `match foo {}` we don't issue a helpful error like `Missing cases Foo, Bar, Baz` and instead issue `Missing cases: _`. This could be fixed but it is the end of the week so I wanted to get this work out.~~ This has been implemented along with ranges for integers (see tests).
Check one:

feat(experimental): Issue missing case error for match expressions

---

CRITICAL_NOIR_LIBRARIES
EXTERNAL_NOIR_LIBRARIES.yml
compiler/integration-tests/package.json
scripts/install_bb.sh
yarn.lock

Resolves 
This PR adds more libraries for us to track in CI
Check one:

chore: track more critical libraries

---

compiler/noirc_frontend/src/hir/comptime/display.rs

This is hard to test, but a code like this (regardless of its validity):
```noir
struct Foo {}
fn main() {
comptime {
let foo = quote { Foo }.as_type();
let q = quote { impl $foo for $foo {} };
println(q);
}
}
```
printed this:
```
quote {
implFooforFoo {
}
}
```
Now it prints:
```
quote {
impl Foo for Foo {
}
}
```
Three changes were made here:
1. Printing a quoted typed by wrapping it in a `Value`, then calling `print_value` which handles spaces
2. Adding a space before printing a value, if it's needed
3. Making `last_was_alphanumeric` take into account only the last byte, not the entire string (for example if a quoted expression had a space but still ended with an alphanumeric, we'd consider that as not ending in alphanumeric)
Check one:

fix: TokensPrettyPrinter was missing some spaces between tokens

---

compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
test_programs/compile_success_empty/comptime_quoted/Nargo.toml
test_programs/compile_success_empty/comptime_quoted/src/main.nr

Resolves #5979
Compares two Quoted values by turning them into strings, then comparing the strings.
Another way to do this would be to expand interned nodes to the nodes they represent, then turning those nodes into tokens, then finally comparing all tokens. However, that involves more code (or at least code that we currently don't have) while comparing strings works as well and might have more or less the same performance (we might need to allocate tokens with the other approach).
Check one:

fix: compare Quoted by expanding interned values

---

compiler/noirc_frontend/src/elaborator/comptime.rs
compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/hir/comptime/errors.rs
compiler/noirc_frontend/src/hir/comptime/interpreter.rs
compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs

Resolves #7459
Now this code:
```noir
fn main() {
comptime {
let x = quote { Hello };
let _ = x.as_type();
}
}
```
Gives this error:
```
error: Could not resolve 'Hello' in path
┌─ src/main.nr:3:25
│
3 │         let x = quote { Hello };
│                         -----
4 │         let _ = x.as_type();
│                 ----------- While evaluating `Quoted::as_type`
```
Check one:

feat: relate errors to macro built-ins errors

---

docs/docs/noir/concepts/data_types/integers.md

chore: update docs to reflect u128 type

---

compiler/noirc_frontend/src/ast/mod.rs
compiler/noirc_frontend/src/tests.rs

Resolves 
This is a leftover from #7301.
We're not showing 128 bits as a valid size if someone provides an invalid bit size for an integer type. This PR updates this logic so it'll remain up to date on future updates to the supported bitsizes.
Check one:

fix: update error message to display 128 bits as valid bit size

---

acvm-repo/acir/src/circuit/opcodes.rs
acvm-repo/acir/src/circuit/opcodes/black_box_function_call.rs
acvm-repo/acir/src/native_types/expression/mod.rs
acvm-repo/acir/src/native_types/witness_map.rs
acvm-repo/acir/src/native_types/witness_stack.rs
acvm-repo/acir/src/proto/convert/acir.rs
acvm-repo/acir/src/proto/convert/brillig.rs
acvm-repo/acir/src/proto/convert/mod.rs

Resolves 
This PR starts removing unnecessary trait bounds added in https://github.com/noir-lang/noir/pull/7513
Check one:

chore: remove unnecessary trait bounds

---

cspell.json
docs/docs/explainers/explainer-writing-noir.md
docs/versioned_docs/version-v0.36.0/explainers/explainer-writing-noir.md
docs/versioned_docs/version-v1.0.0-beta.0/explainers/explainer-writing-noir.md
docs/versioned_docs/version-v1.0.0-beta.1/explainers/explainer-writing-noir.md
docs/versioned_docs/version-v1.0.0-beta.2/explainers/explainer-writing-noir.md
docs/versioned_docs/version-v1.0.0-beta.3/explainers/explainer-writing-noir.md

Resolves 
This PR deals with a recurring cspell issue which pops up in the release PRs. where Guillaume's talk name throws an error.
I've also removed the "Tips from Tom, Jake and Zac." reference as this is non-actionable by readers.
Check one:

chore: address recurring typo in docs

---

compiler/noirc_frontend/src/parser/parser/expression.rs
compiler/noirc_frontend/src/parser/parser/function.rs
compiler/noirc_frontend/src/parser/parser/statement.rs

Resolves #7654
It's a minor thing, but with #7613 generating code it can sometimes happen that the code ends up like this, and then it's not valid code.
In reality Rust also allows the same for `for`, `loop` and `while`. I think, like in Rust, they should be expressions that return `()` (except `loop` which could have a `break`) but as it's very rare to do a call after these (they are usually `()`) and because it implies a larger change, I didn't do it.
Check one:

fix: allow method call after block, if and match

---

compiler/noirc_frontend/src/elaborator/lints.rs
compiler/noirc_frontend/src/hir/comptime/hir_to_display_ast.rs
compiler/noirc_frontend/src/hir/comptime/interpreter.rs
compiler/noirc_frontend/src/hir_def/expr.rs
compiler/noirc_frontend/src/monomorphization/mod.rs

I noticed this while working on #7613
Another thing I noticed is that `HirExpression::Unquote` is created [here](https://github.com/noir-lang/noir/blob/1fa0dd95a95b01652332e94952ade14019a51fd1/compiler/noirc_frontend/src/hir/comptime/value.rs#L451) but I don't know if that should be `HirExpression::Quoted` (if so, `HirExpression::Unquote` could also be removed)
Check one:

chore: remove some unused HIR code

---

test_programs/compile_success_empty/regression_7570_nested/Nargo.toml
test_programs/compile_success_empty/regression_7570_nested/src/main.nr
test_programs/compile_success_empty/regression_7570_serial/Nargo.toml
test_programs/compile_success_empty/regression_7570_serial/src/main.nr

Two more tests for https://github.com/noir-lang/noir/pull/7570
I found these failing (panicking) cases while implementing the new lambda calculus interpreter test.
These cases aren't explicitly tested in https://github.com/noir-lang/noir/pull/7570, so adding them here.
Check one:

chore: add regression tests for PR #7570 from lambda interpreter test

---

test_programs/gates_report_brillig.sh
test_programs/gates_report_brillig_execution.sh

In https://github.com/noir-lang/noir/pull/7660 I was not getting an opcode diff that I am getting locally.
Although the CI jobs for the Brillig opcode reports are passing, we are getting this failure:
```
error: This requires the unstable feature 'enums' which is not enabled
┌─ execution_success/regression_7323/src/main.nr:5:5
│  
5 │ ╭     match x {
6 │ │         1 => panic(f"Branch 1 should not be taken"),
7 │ │         2 => panic(f"Branch 2 should not be taken"),
8 │ │         3 => panic(f"Branch 3 should not be taken"),
9 │ │         _ => (),
10 │ │     }
│ ╰─────' Pass -Zenums to nargo to enable this feature at your own risk.
│  
```
Here is an example from an entirely unrelated PR where we see the same failure: https://github.com/noir-lang/noir/actions/runs/13788593062/job/3856255429 …

chore(ci): Exclude enum tests from Brillig reports

---

compiler/noirc_evaluator/src/ssa/checks/check_for_underconstrained_values.rs

No issue just something I noticed while running a Noir program with a trace activated.
We should not be printing the entire function where we may have tainted Brillig calls. A function's SSA could potentially be massive. This litters the trace and also most likely affects our compilation timing reports (which have `NOIR_LOG=trace` activated) as we are printing much more than necessary. 
This was initially done here https://github.com/noir-lang/noir/pull/6814 but looks like a trace was missed. We now use a combo of function name and id. 
Check one:

chore(ssa): Do not print entire functions in underconstrained values check trace

---

compiler/noirc_frontend/src/hir/resolution/errors.rs

Resolves 
This is never meaningful so we should reject it rather than ignoring this which allows confusing syntax.
Check one:

chore!: make `ResolverError::UnnecessaryPub` a hard error

---

compiler/noirc_frontend/src/monomorphization/tests.rs
compiler/noirc_frontend/src/tests.rs

No issue, just something I wanted to do for completeness.
Check one:

chore: easier way to test monormophization errors

---

compiler/noirc_frontend/src/elaborator/patterns.rs
compiler/noirc_frontend/src/node_interner.rs
compiler/noirc_frontend/src/tests/metaprogramming.rs
test_programs/execution_success/comptime_variable_at_runtime/Nargo.toml
test_programs/execution_success/comptime_variable_at_runtime/src/main.nr

fix: allow referring to comptime locals at runtime

---

docs/src/pages/index.jsx

chore: add trailing slash to link on docs homepage

---

docs/README.md
docs/package.json

- Supplement missing step of generating `versions.json` in `yarn dev`
- Fix missing cache cleaning in `yarn clean`
- Trim unnecessary commands and supplement missing commands in README
- Improve readability of steps in README
Check one:

chore(docs): Minor fixes on local documentation development workflows

---

docs/scripts/setStable.ts

The _setStable.ts_ script currently omits building and serving documentations for older patch versions. It was and will be great for skipping largely redundant builds for multiple _y_ when Noir was on _0.x.y_ versioning and when Noir is on _1.x.y_ versioning.
As Noir is currently on _1.0.0-beta.n_ versioning though, this skips all _n_ version documentations except the latest, albeit them not necessarily being patches.
E.g. Only _1.0.0-beta.2_ docs are currently served:
This PR:
- Comments out patch version omission logic in _setStable.ts_
- Add temporary command to generate _versions.json_ with just filtered stables instead
Which enables serving of docs for the two most-recent versions as intended for doc readers:
This PR should be reverted / the patch omission logic should be restored …

chore(docs): Extend stable documentation versions to build to cover multiple `beta.n` releases

---

compiler/noirc_frontend/src/tests/traits.rs

Resolves 
This PR adds tests for the behaviour we want to implement for #7632. Once that issue is addressed we can remove the `should_panic` attributes.
Check one:

chore: add tests for trait renaming in imports

---

.github/workflows/rustdoc.yml

Resolves #7683 
This PR sets up a build of rustdoc to be hosted at https://noir-lang.github.io/noir/docs. This is automatically update on each commit to master.
Check one:

chore: add workflow to publish rustdoc to github pages

---

compiler/noirc_evaluator/src/ssa/ir/dom.rs

Working towards handling control dependence 
This work was originally part of https://github.com/noir-lang/noir/pull/7660, but I decided to split it out for easier separation of concerns and reviewing. 
Implements the algorithm in [Cooper, Keith D. et al. “A Simple, Fast Dominance Algorithm.” (1999).](https://www.cs.tufts.edu/comp/150FP/archive/keith-cooper/dom14.pdf). The algorithm is under the "Dominance Frontiers" section, but earlier sections are useful to have the full context. 
I also added tests for a simple loop with a conditional inside. I added additional dom/post-dom tree tests as well as dom/post-dom frontiers tests. 
Check one:

feat(ssa): Dominance frontiers

---

tooling/artifact_cli/src/execution.rs

Resolves an issue raised by aztec team wanting to extract the output from stdout
In https://github.com/noir-lang/noir/pull/7406 we removed printing the return value of a program to stdout. 
This simply brings it back.
Check one:

chore(artifact_cli): Print circuit output to stdout

---

compiler/noirc_frontend/src/hir/comptime/display.rs

fix: wrong printing of line comment in quoted

---

acvm-repo/acir/README.md
acvm-repo/acir/src/circuit/black_box_functions.rs
acvm-repo/acir/src/circuit/opcodes/black_box_function_call.rs
cspell.json
noir_stdlib/src/ecdsa_secp256k1.nr
test_programs/execution_success/brillig_arrays/src/main.nr

Towards general documentation effort
I was looking at the rust docs [here](https://noir-lang.github.io/noir/docs/acir/circuit/opcodes/enum.BlackBoxFuncCall.html) and I was expecting to see documentation on `BlackBoxFuncCall` as that is the actual circuit opcode. The black box func docs live on `BlackBoxFunc`, but that enum is basically a naming wrapper used internally by the compiler. The actual opcode is `BlackBoxFuncCall`.
1. New doc comments on `RecursiveAggregation` black box func call
2. Moved doc comments from `BlackBoxFunc` enum to `BlackBoxFuncCall` enum
I think we could consider removing `BlackBoxFunc` from the `acir` crate entirely. I have not fully checked how annoying this would be, but it seems like it should live inside of the compiler. It looks to only be used in …

chore(docs): Document BlackBoxFuncCall enum

---

compiler/noirc_frontend/src/ast/statement.rs
compiler/noirc_frontend/src/parser/errors.rs
compiler/noirc_frontend/src/parser/parser/expression.rs

Resolves #7704
Our comments said "To match Rust" but they didn't, maybe because Rust then changed.
With this PR:
- assignments, `break` and `continue` are allowed to appear without a semicolon if they are the last statement in a block (this matches Rust)
- `let` still requires a semicolon if it's the last statement in a block, and the error message in this case is improved
Check one:

fix: allow omitting ';' after last block statement if it's an assignment

---

compiler/noirc_frontend/src/parser/parser/types.rs
test_programs/execution_success/reference_only_used_as_alias/src/main.nr
tooling/nargo_fmt/src/formatter/types.rs

feat: allow `fn` returning `()` without having to write `-> ()`

---

compiler/noirc_frontend/src/parser/errors.rs
compiler/noirc_frontend/src/parser/parser/doc_comments.rs
compiler/noirc_frontend/src/parser/parser/function.rs
compiler/noirc_frontend/src/parser/parser/item.rs
noir_stdlib/src/ecdsa_secp256k1.nr
tooling/nargo_fmt/src/formatter/attribute.rs
tooling/nargo_fmt/src/formatter/item.rs

Resolves #7711
Two things:
1. Doc comments and attributes can now be intermixed, like in Rust
2. Trying to document a function parameter will result in an error, like in Rust (and this error is clearer than the previous warning)
For point 2, I considered whether to produce a warning, given that we produce warnings for stray doc comments in other places. However, I think it should be an error to make it clear that that doc comment does nothing there (Rust will sometimes warn, sometimes error too, and it's not clear why).
Error here:
No warnings here:
Check one:

fix: doc comments on functions warn unexpectedly

---

acvm-repo/acvm/src/compiler/transformers/csat.rs
acvm-repo/acvm/src/pwg/brillig.rs
compiler/noirc_evaluator/src/acir/mod.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_memory.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/instructions.rs
compiler/noirc_evaluator/src/ssa/ir/dfg.rs
compiler/noirc_evaluator/src/ssa/ir/map.rs
compiler/noirc_evaluator/src/ssa/ir/types.rs
compiler/noirc_evaluator/src/ssa/ir/value.rs
compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs
compiler/noirc_evaluator/src/ssa/opt/inlining/inline_info.rs
compiler/noirc_evaluator/src/ssa/opt/remove_enable_side_effects.rs
compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs
compiler/noirc_evaluator/src/ssa/ssa_gen/value.rs
compiler/noirc_frontend/src/ast/statement.rs
compiler/noirc_frontend/src/elaborator/enums.rs
compiler/noirc_frontend/src/elaborator/patterns.rs
compiler/noirc_frontend/src/elaborator/traits.rs
compiler/noirc_frontend/src/graph/mod.rs
compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
compiler/noirc_frontend/src/node_interner.rs
compiler/noirc_frontend/src/resolve_locations.rs
tooling/fuzzer/src/dictionary/mod.rs
tooling/fuzzer/src/strategies/mod.rs

No issue, part of general documentation drive
I was generating docs locally with `cargo doc`. Resolving a bunch of various warnings.
One example of an issue that currently exists: text such as Tree<T> is seen as an unclosed html tag. It needs to be wrapped in a source code block `Tree<T>`. In this case it caused unnecessary underlining:
Check one:

chore: Resolve various rustdoc warnings

---

.github/workflows/reports.yml

Resolves 
Some of these jobs were hanging but not being terminated. I've added some timeouts to stop them from hanging around and locking up runners.
Check one:

chore: add timeouts to CI

---

acvm-repo/brillig/src/black_box.rs
acvm-repo/brillig/src/opcodes.rs
cspell.json

Towards general documentation drive.
1. Included missing documentation under variant of `BrilligOpcode` and `BlackBoxOp`
2. Documented `ToRadix` black box variant as it is unique to the Brillig VM
Check one:

chore(docs): Brillig opcodes

---

acvm-repo/acir/src/circuit/mod.rs
acvm-repo/acvm/src/pwg/brillig.rs
acvm-repo/acvm/src/pwg/mod.rs
acvm-repo/acvm_js/src/execute.rs
acvm-repo/acvm_js/src/js_execution_error.rs
tooling/nargo/src/errors.rs
tooling/nargo/src/ops/execute.rs
tooling/noirc_abi_wasm/src/lib.rs

No issue, just something I noticed while working on docs.
We have structures that are only created only for resolution of errors that live in the acir crate. This location feels unnatural.
Move `ResolvedOpcodeLocation`, `RawAssertionPayload`, and `ResolvedAssertionPayload` out of the `acir` crate.  `RawAssertionPayload` and `ResolvedAssertionPayload` are part of the `acvm` crate where they are instantiated and `ResolvedOpcodeLocation` has been moved to `nargo`.
I want to move `ErrorSelector` out of the `acir` crate as well as it has nothing to do with the circuit definition and is only used for resolving errors in the ABI. As we lean into the ABI for error resolution we should not need any error context as part of the `acir` definition. I didn't do it in this PR yet as it is used across …

chore(refactor): Move resolved error structures out of acir crate

---

compiler/noirc_evaluator/src/acir/mod.rs
test_programs/execution_success/regression_7612/Nargo.toml
test_programs/execution_success/regression_7612/Prover.toml
test_programs/execution_success/regression_7612/src/main.nr

Resolves #7612
The databus redirect usage of call data parameters to reads into the call data array, but these reads where not reducing the returned value in case a false predicate makes use of an incompatible type.
Check one:

fix: handle predicate value reduction in array get also for the databus

---

.github/workflows/formatting.yml
tooling/nargo/src/errors.rs

Resolves 
This PR enforces that we don't trigger any rustdoc lints due to broken links and the such in future.
Check one:

chore(ci): enforce rustdoc lints

---

.github/workflows/formatting.yml
compiler/fm/src/lib.rs

chore: add extra docs lint

---

.github/workflows/test-js-packages.yml

Occasionally we get limited in https://github.com/noir-lang/noir/actions/runs/13932331691/job/38992290927#step:6:1
Adds the `GITHUB_TOKEN` to the workflow to avoid getting rate limited.
The build happens [here](https://github.com/noir-lang/noir/blob/24e2217347cf8a0021d419fa992e1c09316e77b0/acvm-repo/acvm_js/build.sh#L49).
Check one:

chore: Add GITHUB_TOKEN for downloading prost_prebuilt to acvm.js build

---

docs/docs/tutorials/noirjs_app.md

Resolves https://github.com/noir-lang/noir/pull/7736#issuecomment-2738373174 (https://github.com/noir-lang/tiny-noirjs-app still needs to be updated) 
This PR removes usage of `bun` with `yarn` in the docs
Check one:

chore: remove bun from docs in favour of yarn

---

noir_stdlib/src/embedded_curve_ops.nr
test_programs/compile_success_empty/embedded_curve_add_simplification/src/main.nr
test_programs/compile_success_empty/embedded_curve_msm_simplification/src/main.nr
test_programs/execution_success/embedded_curve_ops/src/main.nr
test_programs/noir_test_success/comptime_blackbox/src/main.nr
test_programs/noir_test_success/embedded_curve_ops/src/main.nr

Resolves https://github.com/noir-lang/noir/issues/7707
This PR adds a method to `EmbeddedCurvePoint` so that we can quickly get the generator point.
Check one:

feat: add `EmbeddedCurvePoint::generator()` to return generator point

---

acvm-repo/acir/src/circuit/opcodes/black_box_function_call.rs
test_programs/compile_success_empty/regression_7749/Nargo.toml
test_programs/compile_success_empty/regression_7749/src/main.nr
test_programs/execution_success/regression_7744/Nargo.toml
test_programs/execution_success/regression_7744/Prover.toml
test_programs/execution_success/regression_7744/src/main.nr
test_programs/execution_success/regression_7744/stdout.txt
test_programs/format.sh

Resolves #7744
Resolves #7749
Check one:

fix: add missing inputs to `BlackBoxFuncCall::get_inputs_vec` for EcAdd

---

.github/benchmark_projects.yml
test_programs/gates_report_brillig_execution.sh

Resolves the failures seen under `Generate Brillig execution report` in https://github.com/noir-lang/noir/actions/runs/13971802272/job/39115494211
In https://github.com/noir-lang/noir/pull/7629 we added reference count tests that only work with specific inliner settings. This causes our Brillig trace reports to fail. 
I excluded `reference_counts_inliner_min`, `reference_counts_inliner_0`, and `reference_counts_inliner_max` from the brillig trace report. 
Check one:

fix(ci): Exclude inliner specific reference count tests from Brillig trace report

---

compiler/wasm/test/compiler/browser/compile.test.ts
compiler/wasm/test/compiler/node/compile.test.ts
compiler/wasm/test/compiler/shared/compile.test.ts

Resolves 
This PR updates `noir_wasm` tests to run over the `execution_success` and `compile_success_empty` test programs. We currently basically just check that the compiler doesn't throw an exception on these but we can beef up those checks later.
I've had to ignore a few cases where the tests fail which seem to fall into two categories:
- Using workspaces
- using experimental features, i.e. enums.
Check one:

chore: run `noir_wasm` over `test_programs`

---

noir_stdlib/src/embedded_curve_ops.nr

Resolves 
This PR removes all the juggling around ECAdd to ensure that the inputs are separate witnesses, etc. when we're running in an unconstrained context.
Check one:

feat: optimize unconstrained `embedded_curve_add`

---

compiler/integration-tests/package.json
compiler/integration-tests/test/node/smart_contract_verifier.test.ts
scripts/install_bb.sh
yarn.lock

chore: bump bb to 0.82.0

---

noir_stdlib/src/field/bn254.nr

Resolves 
I noticed that we hadn't updated this to take advantage of the native u128 type so I've done so.
Check one:

feat: faster `Field` decomposition

---

acvm-repo/brillig_vm/src/black_box.rs
compiler/noirc_evaluator/src/acir/mod.rs
compiler/noirc_evaluator/src/ssa/ir/instruction/call/blackbox.rs
compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
compiler/noirc_frontend/src/hir/comptime/interpreter/foreign.rs
noir_stdlib/src/embedded_curve_ops.nr
noir_stdlib/src/hash/mod.nr

Embedded curve opcodes returned 3 fields on noir land, but on barretenberg side is_infinite is a boolean. This mismatch is problematic for the AVM.
I've changed ecadd and msm to return an array of 1 EmbeddedCurvePoint. I can't return an EmbeddedCurvePoint directly since the AVM doesn't handle proving opcodes with more than one return register. By making it an array, we just have one pointer in the opcode, which also makes it smaller. This quirk is not exposed since the opcode is wrapped in the stdlib. No change should happen for users.
Check one:

chore: Make embedded curve opcodes return embedded curve points

---

test_programs/format.sh

Resolves https://github.com/noir-lang/noir/issues/7790
I'm not sure if this was intended to be applied to format.sh in the first place tbh.
Check one:

chore: include `eddsa` test in format check

---

tooling/artifact_cli/src/execution.rs
tooling/nargo_cli/src/cli/debug_cmd.rs
tooling/noirc_artifacts/src/debug.rs

No issue, just something I wanted to do for some time now.
For example, an output before this PR looked like this:
```
error: Failed constraint
┌─ /Users/asterite/Sandbox/one/src/main.nr:9:16
│
9 │         assert(array[index - 1].counter < 3);
│                ----------------------------
│
= Call stack:
1. /Users/asterite/Sandbox/one/src/main.nr:9:16
```
Now it's:
```
error: Failed constraint
┌─ src/main.nr:9:16
│
9 │         assert(array[index - 1].counter < 3);
│                ----------------------------
│
= Call stack:
1. src/main.nr:9:16
```
Similarly, if the program executes fine it would show:
```
[one] Circuit witness successfully solved
[one] Witness saved to /Users/asterite/Sandbox/one/target/one.gz
```
Now it shows:
```
[one] Circuit witness successfully solved
[one] Witness …
```

feat: use relative paths in "Call stack" and "Witness saved to"

---

compiler/noirc_evaluator/src/ssa/parser/ast.rs
compiler/noirc_evaluator/src/ssa/parser/into_ssa.rs
compiler/noirc_evaluator/src/ssa/parser/lexer.rs
compiler/noirc_evaluator/src/ssa/parser/mod.rs
compiler/noirc_evaluator/src/ssa/parser/tests.rs
compiler/noirc_evaluator/src/ssa/parser/token.rs

While taking a look at #7770 and trying to write a test for it I noticed the SSA parser doesn't parse `constrain v0 != v1` so this is what this PR does.
Check one:

chore: parse `!=` in SSA parser

---

compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/elaborator/patterns.rs
compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/tests.rs

fix: improve misleading error message when object type is unknown

---

tooling/nargo_fmt/src/formatter/expression.rs
tooling/nargo_fmt/src/formatter/statement.rs

fix: format last statement in block with optional semicolon

---

acvm-repo/brillig_vm/src/cast.rs
acvm-repo/brillig_vm/src/lib.rs

Resolves 
Small refactoring PR as part of casting work. the `cast` method in the brillig VM is actually pure so I've pulled it out so that we can run tests in isolation.
Check one:

chore: make brillig vm's `cast` implementation pure.

---

compiler/noirc_driver/src/lib.rs
compiler/noirc_evaluator/src/brillig/brillig_gen.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_fn.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_globals.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_slice_ops.rs
compiler/noirc_evaluator/src/brillig/brillig_ir.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_stack.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/entry_point.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/procedures/array_copy.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/procedures/mod.rs
compiler/noirc_evaluator/src/brillig/mod.rs
tooling/nargo/src/foreign_calls/print.rs

Working towards https://github.com/noir-lang/noir/issues/7287 but this is also just a good debugging utility in general
Adds a new flag `--count-array-copies` to count how many array copies are implicitly performed through brillig's copy on write semantics. This count is performed per brillig entry point so a program with multiple brillig entry points will also output multiple counts. Resultingly, this is easiest to use with `--force-brillig` or an entirely brillig program to see just one count.
This flag helps bring some hard data to the problem of array copies where we previously only had vague notions of "this program is too slow" or "this program seems fast enough." When passing this flag we output `Total arrays copied: {number}` after running each brillig entry point.
~~This is a …

feat(debugging): Add `--count-array-copies` flag

---

noir_stdlib/src/embedded_curve_ops.nr
test_programs/execution_success/multi_scalar_mul/src/main.nr

Small fix which makes sure to use embedded_curve_add_unsafe() properly in underconstrained mode. 
Checking for infinity, it is easy to do in underconstrained function.
Check one:

fix: proper use of add_unsafe in unconstrained

---

acvm-repo/brillig/README.md

Part of general documentation effort
Move the docs from the acvm-docs repository into Noir repo.
Check one:

chore: move brillig docs into noir repo

---

compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/elaborator/statements.rs
compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/hir/resolution/errors.rs
compiler/noirc_frontend/src/tests.rs
test_programs/compile_success_empty/numeric_generics/src/main.nr
test_programs/compile_success_empty/numeric_generics_explicit/src/main.nr

Part of #7795
This PR only changes test programs that would fail to pass if this warning isn't fixed. Other than that, the stdlib and other test programs aren't modified here (the stdlib produces warnings, but these can't be seen from outside the stdlib).
Check one:

feat: warn if array index type is not u32

---

tooling/nargo_cli/build.rs
tooling/nargo_cli/tests/execute.rs

Resolves 
The generated `execute.rs` file is currently ~23k lines long due to a lot of repeated code which we're generating. This seemed a bit wasteful so I did some research and Rust has this nifty feature called "functions".
Turns out we can move a lot of the logic into these "functions" which then sit in `execute.rs` so we get type checking and all that nice stuff in our test code.
This ends up cutting the file size down to ~6k lines
I have no idea why I didn't write it this way originally but :shrug:.
Check one:

chore: use functions inside of test generation

---

acvm-repo/acir/src/circuit/black_box_functions.rs
compiler/noirc_evaluator/src/ssa/ir/instruction.rs
compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs
compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs

Resolves #7803
A bunch of commits that either try to move methods closer to where they are (inlining them if that's a possibility too) or try to make match branches clearer (some branches relied on `requires_acir_gen_predicate` which always returned `true` or `false`, so I moved that boolean up to that branch). Now it's clearer that `Binary`, `ArrayGet` and `ArraySet` are the "most" side-effectful instructions.
I also introduced `BlackBoxFunc::has_side_effects` in case new black box functions are added, and also for someone to verify if any of the existing ones have side effects but are currently marked as `false`.
Check one:

chore: more SSA refactors

---

compiler/noirc_evaluator/src/ssa.rs
compiler/noirc_evaluator/src/ssa/opt/mod.rs
compiler/noirc_evaluator/src/ssa/opt/remove_truncate_after_range_check.rs

Resolves #7828
I don't know if truncate's `max_bit_size` is relevant here (it's ignored in this PR).
Check one:

feat(opt): remove truncate after range_check

---

compiler/noirc_frontend/src/monomorphization/errors.rs
compiler/noirc_frontend/src/monomorphization/mod.rs
compiler/noirc_frontend/src/tests.rs

Not existing issue, just something I noticed.
If you have code like this:
```noir
fn main() {
foo();
}
fn foo<T>() {}
```
the error you get before this PR is:
```
error: Type annotation needed
┌─ src/main.nr:2:5
│
2 │     foo();
│     --- Could not determine type of generic argument
```
I think by now we probably know that it refers to a generic argument on the function `foo`, though it's not clear which generic argument it is (there could be many) and the error Rust gives is a bit clearer, so users without too much Noir experience might be confused.
With this PR, the error is now this:
```
error: Type annotation needed
┌─ src/main.nr:2:5
│
2 │     foo();
│     --- Could not determine the type of the generic argument `T` declared on the function `foo`
```
The same thing is done when a …

feat: better error message when generic argument cannot be determined

---

compiler/noirc_driver/src/lib.rs

fix: show-ssa-pass implies force-compile

---

tooling/nargo_fmt/src/chunks.rs
tooling/nargo_fmt/src/formatter/expression.rs

Resolves #7407
The formatter is pretty complex when it comes to deciding how to format method calls, call chains and lambdas but I think the fix here is the "correct" one. The explanation for this change is a bit on line 642-664 of chunks.rs, then on 674-680.
The code in the issue:
```noir
comptime fn generate_compute_note_hash_and_optionally_a_nullifier() -> Quoted {
let notes = NOTES.entries();
if notes.len() > 0 {
for i in 0..notes.len() {
let (typ, (_, _, _, _)) = notes[i];
let get_note_type_id = typ.get_trait_impl(NOTE_INTERFACE).unwrap().methods().filter(|m| {
m.name() == quote { get_note_type_id }
})[0]
.as_typed_expr();
}
quote {}
} else {
quote {}
}
}
```
now gets formatted like this:
```noir
comptime fn generate_compute_note_hash_and_optionally_a_nullifier() -> Quoted {
let …
```

fix(formatter): account lambda beginning when formatting method call

---

compiler/noirc_evaluator/src/acir/mod.rs

chore: replace ssa builder usage with parser in test

---

compiler/noirc_frontend/src/elaborator/patterns.rs
compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/node_interner.rs
compiler/noirc_frontend/src/parser/errors.rs
compiler/noirc_frontend/src/parser/parser/expression.rs
compiler/noirc_frontend/src/parser/parser/path.rs
compiler/noirc_frontend/src/resolve_locations.rs
test_programs/compile_success_empty/type_path/src/main.nr
tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/tests.rs
tooling/nargo_fmt/src/formatter/expression.rs

Resolves #7767
In addition to implementing the feature I tried to improve some parser errors. For example if you write:
```noir
fn main() {
let _ = ()::foo();
}
```
you get this error (in addition to the one about not finding `foo`):
```
error: Missing angle brackets surrounding type in associated item path
┌─ src/main.nr:2:11
│
2 │   let _ = ()::foo();
│           -- Types that don't start with an identifier need to be surrounded with angle brackets: `<`, `>`
```
That's actually how I learned in Rust that you need to surround types with `<..>`.
For other types there's a bit of error recovery and cleanup too to make it clear that `<...>` is missing.For example for:
```noir
fn main() {
(Field, i32)::foo()
}
```
we get:
```
error: Missing angle brackets surrounding type in associated item …
```

feat: type path for any type

---

compiler/noirc_frontend/src/hir/comptime/display.rs
compiler/noirc_frontend/src/lexer/errors.rs
compiler/noirc_frontend/src/lexer/lexer.rs
compiler/noirc_frontend/src/lexer/token.rs
compiler/noirc_frontend/src/parser/errors.rs
compiler/noirc_frontend/src/parser/parser/expression.rs
compiler/noirc_frontend/src/parser/parser/infix.rs
compiler/noirc_frontend/src/parser/parser/types.rs

fix(parser): parse double `&` in type

---

EXTERNAL_NOIR_LIBRARIES.yml
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs

Breakout change from https://github.com/noir-lang/noir/pull/7837
We were testing `1 < rc` when we want to allow an rc of 0 (just not for it to decrement below 0 or back up to 1).
I changed it to `0 < rc` and added another check while incrementing that we do not go from 0 back to 1.
Check one:

fix(debug): Fix RC underflow check

---

docs/versioned_docs/version-v1.0.0-beta.2/getting_started/quick_start.md
docs/versioned_docs/version-v1.0.0-beta.2/how_to/how-to-solidity-verifier.mdx
docs/versioned_docs/version-v1.0.0-beta.3/getting_started/quick_start.md
docs/versioned_docs/version-v1.0.0-beta.3/how_to/how-to-solidity-verifier.mdx

Update `bb` commands in `1.0.0-beta2` and `1.0.0-beta3` version docs as we have changed the "matching" bb version to be `0.82.0` for these versions. (copying the current dev docs to the versioned_docs folder for these pages)
A new person coming today will install `Noir 1.0.0-beta2` and `bb 0.82.0` and sees incorrect commands in Quick Start.
Note: Leaving `1.0.0-beta1` and `1.0.0-beta0` docs as it is for now, even though we advice to use `bb 0.82.0` for these as well.
Check one:

chore: update bb commands in beta2 and beta3 versioned docs

---

compiler/noirc_evaluator/src/acir/acir_context/mod.rs
compiler/noirc_evaluator/src/acir/mod.rs

Resolves underconstrained quotient during field truncation
Division uses non-deterministic in Noir and as result quotient and remainder must be properly constrained, which is easy to do because it must be less than the dividend.
However this does not work when doing 'unbounded division', i.e when the dividend is a field. In that case, we must ensure that the euclidian division does not overflow.
Check one:

fix: properly constrain quotient during field truncation

---

tooling/nargo_fmt/src/formatter/pattern.rs
tooling/nargo_fmt/src/formatter/statement.rs

Resolves #7898
Copied the logic of formatting struct constructors for formatting patterns (it can't be extracted because they are slightly different and use different types, but it's also not a lot of code).
Check one:

feat(formatter): improved formatting of long struct patterns

---

compiler/noirc_evaluator/src/acir/acir_context/brillig_call.rs
compiler/noirc_evaluator/src/acir/acir_context/generated_acir/brillig_directive.rs
compiler/noirc_evaluator/src/acir/acir_context/generated_acir/mod.rs
compiler/noirc_evaluator/src/acir/acir_context/mod.rs
compiler/noirc_evaluator/src/acir/mod.rs
compiler/noirc_evaluator/src/acir/ssa.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/artifact.rs

Resolves 
This PR does a small refactoring to add a wrapper around stdlib brillig calls.
Check one:

chore: allow injecting custom brillig stdlib implementations in ACIRgen

---

compiler/noirc_frontend/src/monomorphization/mod.rs

Resolves https://github.com/noir-lang/noir/issues/7915
Found while working on the `-Zownership` work. This doesn't cause any known bugs on master but was panicking in that PR when I was trying to unwrap a tuple type and discovered the tuple didn't have a tuple type.
Check one:

fix: Fix type of internal variable created while destructuring tuples and structs during monomorphization

---

tooling/nargo_cli/src/cli/test_cmd/formatters.rs

chore: let `nargo test` write to stdout, not stderr

---

compiler/noirc_evaluator/src/brillig/brillig_gen/constant_allocation.rs

Quick fix to an issue discovered in aztec testnet. 
We were having nondeterministic contract builds between aarch64 and amd64 builds of the noir compiler, reproduced locally. The iterators generated from the FxHashMaps/FxHashSets used in constant_allocation were yielding differently ordered items. I did log the insertions and the input was in the same order (if the insertion ordering was nondeterministic the iteration order is expected to be nondeterministic) so I have no idea what was creating the nondeterminism there. 
Switched to a BTreeMap/BTreeSet in that file and nondeterminism is gone.
Check one:

fix: Fix nondeterminsm on aarch64 vs amd64

---

Cargo.lock
acvm-repo/acir/Cargo.toml
acvm-repo/acir/src/circuit/opcodes.rs
acvm-repo/acir/src/circuit/opcodes/black_box_function_call.rs
cspell.json

Resolves #7904
Resolves #7918 
This PR starts work on #7902 by adding missing info from memory init and blackbox opcodes.
Check one:

feat: print initialization witnesses and show all blackbox witnesses

---

.github/workflows/test-rust-workspace-msrv.yml
.github/workflows/test-rust-workspace.yml

Resolves 
I noticed that we weren't enforcing a timeout here on a separate PR.
Check one:

chore: add timeouts to rust CI

---

Cargo.lock

fix: bump tokio to 1.44.2

---

docs/docs/noir/concepts/data_types/index.md
docs/versioned_docs/version-v0.36.0/noir/concepts/data_types/index.md
docs/versioned_docs/version-v1.0.0-beta.0/noir/concepts/data_types/index.md
docs/versioned_docs/version-v1.0.0-beta.1/noir/concepts/data_types/index.md
docs/versioned_docs/version-v1.0.0-beta.2/noir/concepts/data_types/index.md
docs/versioned_docs/version-v1.0.0-beta.3/noir/concepts/data_types/index.md

Remove references to the outdated community BigInt library https://github.com/shuklaayush/noir-bigint.
Check one:

chore(docs): Remove outdated BigInt library reference

---

Cargo.lock
compiler/noirc_evaluator/Cargo.toml
compiler/noirc_evaluator/src/ssa/ir/types.rs

Resolves #7933
I'm not familiar with the proptest library so let me know if there's a more idiomatic way of doing this.
Check one:

fix: correct proptest Arbitrary for NumericType

---

tooling/nargo/src/foreign_calls/rpc.rs

Restart http-client used for rpc on `ClientError::Transport`
workaround for noir-lang/noir#7463
This is a workaround to be able to use rpc connections on slow interactions like debugging a test function
Check one:

fix(nargo-rpc): restart http-client on ClientError::Transport error

---

test_programs/compile_failure/dep_impl_primitive/stderr.txt
test_programs/compile_failure/invalid_dependency_name/stderr.txt
tooling/nargo_cli/tests/execute.rs

Resolves https://github.com/noir-lang/noir/pull/7970#issuecomment-2789617899
Check one:

fix: don't use relative path in nargo_cli build script

---

Cargo.lock
Cargo.toml
acvm-repo/acir/Cargo.toml
compiler/noirc_frontend/Cargo.toml
compiler/noirc_frontend/src/monomorphization/tests.rs

Resolves 
This PR switches us over to using insta.rs for snapshot testing the rewritten noir generated from ast.
Check one:

chore: switch to using insta for snapshot testing

---

tooling/nargo/src/errors.rs
tooling/nargo/src/ops/compile.rs
tooling/nargo/src/ops/execute.rs
tooling/nargo/src/ops/mod.rs
tooling/nargo_cli/src/cli/check_cmd.rs
tooling/nargo_cli/src/cli/export_cmd.rs
tooling/nargo_cli/src/cli/fuzz_cmd.rs
tooling/nargo_cli/src/cli/test_cmd.rs

- extract logic of mapping a `OpcodeResolutionError` to an `ExecutionError` from `nargo::ops::execute::execute_circuit` into a new function `nargo::errors::execution_error_from` - so that it can be used in other places without repeating logic
- move `check_crate_and_report_errors` from `check_cmd` to `nargo::ops::compile` since it was being used in different commands
- The new `execution_error_from` is necessary for the debugger
Check one:

chore(nargo): extract common functions

---

Cargo.lock
Cargo.toml
acvm-repo/acir/Cargo.toml
compiler/noirc_frontend/Cargo.toml
compiler/noirc_frontend/src/monomorphization/ast.rs
compiler/noirc_frontend/src/monomorphization/printer.rs
compiler/noirc_frontend/src/monomorphization/tests.rs
tooling/ast_fuzzer/examples/sample.rs
tooling/ast_fuzzer/fuzz/Cargo.toml
tooling/ast_fuzzer/fuzz/src/lib.rs
tooling/ast_fuzzer/src/lib.rs
tooling/ast_fuzzer/src/program/mod.rs

Resolves #7978 
Adds some customisation options to the `AstPrinter` to try to keep the printed code closer to Noir by not printing e.g. `a$l1` for a local variable but simply `a`. This saves us the trouble of having to get rid of all those IDs when we're trying to turn an AST printed when the fuzzer failed into a Noir integration test.
The printer now also shows the _main return visibility_ of the program, because Noir always complains if we try to return a value without `pub`. The generator will no longer generate private non-unit return types for `main`.
The PR also changes the display of input values when a program fails to TOML, so it's easier to paste into `Prover.toml`. 
Check one:

chore: Support printing the AST without variable IDs

---

Cargo.lock

Resolves 
Fixes `cargo-deny` advisory
Check one:

chore: bump `crossbeam-channel` to `v0.5.15`

---

compiler/noirc_frontend/src/ast/visitor.rs
compiler/noirc_frontend/src/elaborator/comptime.rs
compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs
compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
compiler/noirc_frontend/src/lexer/token.rs
compiler/noirc_frontend/src/parser/parser.rs
compiler/noirc_frontend/src/parser/parser/attributes.rs
compiler/noirc_frontend/src/parser/parser/expression.rs
test_programs/compile_success_empty/comptime_attribute/Nargo.toml
test_programs/compile_success_empty/comptime_attribute/src/main.nr
tooling/lsp/src/attribute_reference_finder.rs
tooling/lsp/src/requests/completion.rs
tooling/lsp/src/with_file.rs
tooling/nargo_fmt/src/formatter/attribute.rs

feat: allow splicing a resolved function into an attribute name

---

compiler/noirc_frontend/src/parser/errors.rs
compiler/noirc_frontend/src/parser/parser/function.rs
test_programs/compile_failure/builtin_function_declaration/src/main.nr
test_programs/compile_failure/builtin_function_declaration/stderr.txt

Resolves #7997
The issue was that when the parser didn't find `{ ... }` for a function, it would return an empty body but not error. Without an error the formatter tried to format it and panicked. Now the parser will produce an error in this case.
Also fixes a syntax error in a test.
Check one:

fix(parser): error on missing function body

---

compiler/wasm/src/noir/dependencies/github-dependency-resolver.ts

Resolves 
This PR addresses a false positive security alert warning of incomplete sanitation of urls. Any malicious urls which get through this check will be caught by `resolveGithubCodeArchive` however there's no reason to not do the secure check everywhere.
Check one:

chore: improve checking of github urls in `noir_wasm`

---

tooling/lsp/src/requests/code_action/implement_missing_members.rs

fix(LSP): implement missing members associated constants

---

Cargo.lock
compiler/noirc_evaluator/Cargo.toml
compiler/noirc_evaluator/src/ssa/ir/dfg/simplify.rs
compiler/noirc_evaluator/src/ssa/ir/dfg/simplify/call.rs
compiler/noirc_evaluator/src/ssa/ir/dfg/simplify/call/blackbox.rs
compiler/noirc_evaluator/src/ssa/ir/dfg/simplify/constrain.rs
compiler/noirc_evaluator/src/ssa/opt/as_slice_length.rs
compiler/noirc_evaluator/src/ssa/opt/basic_conditional.rs
compiler/noirc_evaluator/src/ssa/opt/brillig_array_gets.rs
compiler/noirc_evaluator/src/ssa/opt/brillig_entry_points.rs
compiler/noirc_evaluator/src/ssa/opt/check_u128_mul_overflow.rs
compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs
compiler/noirc_evaluator/src/ssa/opt/defunctionalize.rs
compiler/noirc_evaluator/src/ssa/opt/die.rs
compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs
compiler/noirc_evaluator/src/ssa/opt/hint.rs
compiler/noirc_evaluator/src/ssa/opt/inlining.rs
compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs
compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
compiler/noirc_evaluator/src/ssa/opt/mod.rs
compiler/noirc_evaluator/src/ssa/opt/pure.rs
compiler/noirc_evaluator/src/ssa/opt/remove_truncate_after_range_check.rs
compiler/noirc_evaluator/src/ssa/opt/remove_unreachable.rs
compiler/noirc_evaluator/src/ssa/opt/simplify_cfg.rs
compiler/noirc_evaluator/src/ssa/opt/unrolling.rs

Resolves 
Follow on from #7984 .
This PR adds an example of using insta for our snapshot testing in SSA passes. I've created a `assert_ssa_snapshot!` macro which will automatically normalize the SSA before snapshotting it for devex.
I'd really recommend having a quick read of https://insta.rs/docs/quickstart/ if you're not familiar.
Check one:

chore: use insta snapshots for ssa tests

---

tooling/nargo_cli/tests/hello_world.rs

Running the tests on arm64 currently fail because of one test.
This test actually always failed for me (I have a Mac) but always thought that test didn't run in CI.
See the comment in the PR's code for the fix. I have no idea why Mac does this...
Check one:

chore: fix failing test on MacOS

---

docs/docs/how_to/how-to-solidity-verifier.mdx
docs/versioned_docs/version-1.0.0-beta.4/how_to/how-to-solidity-verifier.mdx
docs/versioned_docs/version-v1.0.0-beta.2/how_to/how-to-solidity-verifier.mdx
docs/versioned_docs/version-v1.0.0-beta.3/how_to/how-to-solidity-verifier.mdx

Fix proof split script to match bb 0.82.2 in solidity verifier docs
Check one:

fix(docs): fix proof splitting script in solidity guide

---

compiler/noirc_evaluator/src/ssa/ir/dfg.rs
compiler/noirc_evaluator/src/ssa/opt/remove_truncate_after_range_check.rs

Slowly trying to migrate away from `set_value_from_id`
Check one:

chore: don't use `set_value_from_id` in `remove_truncate_after_range_checks`

---

acvm-repo/acvm/src/pwg/arithmetic.rs

Resolves 
I held off on this previously as supposedly this didn't affect benchmarks but it causes a 90% drop in the ACVM benchmarks I added recently.
We now skip the inversion when solving an `AssertZero` opcode in cases where the denominator is +-1 as we can convert them into a multiplication.
Check one:

feat: skip inverting field elements with values +-1 in ACVM

---

.github/workflows/reports.yml
.github/workflows/rustdoc.yml
.github/workflows/test-js-packages.yml
.github/workflows/test-rust-workspace-arm64.yml
.github/workflows/test-rust-workspace-msrv.yml
.github/workflows/test-rust-workspace.yml

Fixes https://github.com/noir-lang/noir/actions/runs/14418135582
Adds `GITHUB_TOKEN` env to more `cargo` commands to intermittent API limiting.
This is because of https://github.com/noir-lang/noir/pull/7513
We don't plan to use protobuf at the moment, although it can be selected by the user in https://github.com/noir-lang/noir/pull/7716 which could be used by someone who wants to bootstrap their side of the stack from the protobuf schemas, but I thought that if we wanted to keep the bytecode model we use internally separate from the DTOs (which protobuf achieves, but the reflection based approach does not), we might want to look at using https://docs.rs/prost-reflect/latest/prost_reflect/ to write some kind of custom format that utilises the number tags specified in the protobuf schema. …

chore: Add `GITHUB_TOKEN` to more workflow steps

---

compiler/integration-tests/package.json
examples/prove_and_verify/prove_and_verify.sh
examples/recursion/generate_recursive_proof.sh
examples/solidity_verifier/solidity_verifier.sh
scripts/install_bb.sh
yarn.lock

bump bb to 0.84.0
bb `0.84.0` saves proof and publicInputs as separate files
Will update the docs in a separate PR
Check one:

chore: bump bb to 0.84.0

---

compiler/noirc_evaluator/src/ssa.rs

Resolves an issue introduced by https://github.com/noir-lang/noir/pull/8035
The ` ({cnt})` part was not included in the SSA message based print filtering, so trying to filter `--show-ssa-pass "My Pass (1)"` did not work, only `--show-ssa-pass "My Pass"`.
Check one:

fix: SSA pass print filter to include the count

---

compiler/noirc_frontend/src/monomorphization/printer.rs

Resolves an issue I found when trying to copy-paste printed AST as Noir: it's easy to get rid of `$f1` IDs, but it's not easy to identify all calls made from ACIR functions to `unconstrained` ones and add `unsafe { }` around them to satisfy the compiler. 
Adds an `in_unconstrained` flag to the `AstPrinter`, set in `print_function`, and used in `print_call` to decide whether `unsafe` should be surrounding the call.
_We could make this optional like with the `show_ids` field, so it only kicks in with the `DisplayAstAsNoir(&program)` construct. At the moment I'm still printing the AST with IDs if the compiler crashes, just in case that extra detail helps (it did once, but usually doesn't), and because IDs are easy to get rid of, whereas `unsafe` isn't easy to add, I thought I'd include it by …

chore: Print `unsafe { ... }` around calls to Brillig from ACIR in AST

---

EXTERNAL_NOIR_LIBRARIES.yml

Resolves 
https://github.com/noir-lang/noir-bignum/pull/157 added a bunch of heavy tests which increased the testing time for this library.
Check one:

chore: bump bignum timeout

---

compiler/noirc_evaluator/src/ssa/opt/array_set.rs

None, just something I noticed.
While looking at existing SSA optimizations I noticed that in `array_set` we change some instructions. These are modified directly through the dfg but the code was traversing all blocks, taking instructions, etc., and there's no need to do that.
It likely won't improve performance in a noticeable way but at least it makes the code shorter and clearer.
Check one:

chore: simpler `make_mutable` in `array_set` optimization

---

compiler/noirc_evaluator/src/ssa/opt/unrolling.rs
test_programs/compile_success_empty/loop_over_u1_range/Nargo.toml
test_programs/compile_success_empty/loop_over_u1_range/src/main.nr
tooling/nargo_cli/tests/snapshots/compile_success_empty/loop_over_u1_range/execute__tests__force_brillig_false_inliner_0.snap

Resolves #8107 
We simplify equality operations with booleans like `(boolean == false)` into `!boolean`.
Thus, using a u1 in a loop bound can possibly lead to a Not instruction
as a loop header's jump condition.
Where `x: u1`, `for i in 0..x` is turned into:
```
b1(v0: u1):
v2 = eq v0, u32 0
jmpif v2 then: b2, else: b3
```
Which is further simplified into:
```
b1(v0: u1):
v2 = not v0
jmpif v2 then: b2, else: b3
```
We handle Not instructions as the loop header condition when fetching the upper const bound now.
Check one:

fix(ssa): Loop range with u1

---

compiler/noirc_evaluator/src/ssa/opt/inlining.rs
test_programs/execution_failure/simple_infinite_recursive_function/Nargo.toml
test_programs/execution_failure/simple_infinite_recursive_function/src/main.nr
test_programs/execution_failure/simple_infinite_recursive_lambda/Nargo.toml
test_programs/execution_failure/simple_infinite_recursive_lambda/src/main.nr

Resolves #8078
We were not taking into account whether the single instruction a single function has may be a recursive call.
I chose to add a special check for this inside of `inline_simple_functions` rather than computing the `InlineInfos` as done in `inline_functions` and `inline_functions_with_no_predicates`. The simple functions check can avoid running through every function to compute the inline infos when we can just directly check the single instruction that we have. 
I added a test similar to what is in #8081 but that test is failing due to different reasons than #8078. If we were appropriately marking `bar` as unconstrained input it would not be appropriately inlined and execute with a stack overflow as expected.
Check one:

fix(ssa): Do not inline simple recursive functions

---

docs/versioned_docs/version-v1.0.0-beta.3/tutorials/noirjs_app.md

Patching web app tutorial in `1.0.0-beta3` versioned docs with recent changes made in this doc (using nargo instead of wasm, yarn instead of bun, updated vite.config)
Could be useful for NoirHack builders using `1.0.0-beta3`
Check one:

chore(docs): patch web app tutorial in 1.0.0-beta3 versioned docs

---

tooling/noir_codegen/package.json
yarn.lock

Solves failing `yarn build:js:only` 
Check one:

chore: bump glob package

---

docs/docs/how_to/how-to-solidity-verifier.mdx
docs/versioned_docs/version-1.0.0-beta.4/how_to/how-to-solidity-verifier.mdx
docs/versioned_docs/version-v1.0.0-beta.3/how_to/how-to-solidity-verifier.mdx

- Fix a minor typo in bb command
- Remove plonk reference
- Update proof split script in beta3 docs 
Check one:

chore(docs): minor updates in solidity doc

---

compiler/noirc_frontend/src/parser/parser/function.rs
compiler/noirc_frontend/src/parser/parser/global.rs
compiler/noirc_frontend/src/parser/parser/impls.rs
compiler/noirc_frontend/src/parser/parser/statement.rs
compiler/noirc_frontend/src/parser/parser/traits.rs
compiler/noirc_frontend/src/parser/parser/type_alias.rs

While working on another thing I noticed that LSP Document Symbol would crash on this code:
```noir
trait Bar {
let N;
}
```
That is, an associated constant without a type. The reason it crashed is that the Document Symbol logic eventually relied on a dummy location.
Here all references to `Location::dummy` are replaced with a location right where the parser is currently is (an empty span at the last token end) which should prevent these crashes. I didn't add tests for these as they are many and in general locations aren't tested by the parser, but I verified the crash no longer happens.
Check one:

fix(parser): avoid using `Location::dummy()`

---

tooling/debugger/src/repl.rs
tooling/debugger/tests/debug.rs

Resolves https://github.com/AztecProtocol/aztec-packages/pull/13755#issuecomment-2823802201
This PR has two fixes:
1. The debugger communicated over channels now since the last debugger PR. An "idle" status is expected after sending a command over one channel. The problem (I think) is that the "idle" status was reported **before** commands were processes instead of after.
2. A test was ignoring lines that matched "At {path}", but the debugger will try to use relative paths when possible so when the test ran from the top level, that line didn't match. Trying to use relative paths in the test fixes that (and this is the one that should unblock the merge on Aztec-Packages, but I fixed 1 first and then noticed the test was still failing, so...)
Check one:

fix(debugger): send idle at loop end + fix test

---

tooling/greybox_fuzzer/src/lib.rs
tooling/greybox_fuzzer/src/mutation/dictionary.rs
tooling/greybox_fuzzer/src/mutation/mod.rs

Changing a fuzzing harness with an existing corpus could lead to panics, if former elements couldn't be cast to appropriate types. 
Before fuzzing with the starting corpus we now try to decode all testcases with the current ABI. If a testcase fails, then we collect parse it for dictionary elements.
For example, if you first fuzz 
```rust
#[fuzz(should_fail)]
fn fuzz_main(x: Field, y: u64, z: u64) {
let prod=y*z;
assert(y<0x100000000);
assert(z<0x100000000);
assert(prod-0xdeadbeefdeadbeef<0xdeadbeef);
assert(x==0xdeadbeefdeadbeefdeadbeefdeadbeef);
}
```
and find a failure (`nargo fuzz`), after changing to 
```rust
#[fuzz(should_fail)]
fn fuzz_main(x: u64, y: u64, z: u64) {
let prod=y*z;
assert(x<0x100000000);
assert(y<0x100000000);
assert(z<0x100000000); …
```

fix: Detect ABI change of fuzzing harnesses

---

tooling/ast_fuzzer/src/lib.rs
tooling/ast_fuzzer/src/program/expr.rs
tooling/ast_fuzzer/src/program/func.rs
tooling/ast_fuzzer/src/program/mod.rs
tooling/ast_fuzzer/src/program/rewrite.rs
tooling/ast_fuzzer/src/program/tests.rs
tooling/ast_fuzzer/src/program/types.rs

Resolves intermittent slow tests in #8048 
Replaces `mut ctx_depth: u32` with `ctx_limit: &mut u32`, to handle exponential cases similar to Fibonacci by limiting the overall number of recursive calls before shortcutting functions to return a random value, rather than allowing the maximum depth to be reached. 
The complication is that it's not possible to pass a mutable reference from ACIR to Brillig. To overcome this we: create a `func_{i}_proxy` for unconstrained functions, which takes `mut ctx_limit: u32` by value and passes it to `func_{i}` by reference.
Here's an example of a function which was slow with `ctx_depth`, rewritten to use mutable references:
<details>
<summary>Slow due to recursion</summary>
```rust
global G_A: [(Field, Field, bool, bool); 0] = [];
global G_B: [[u16; 0]; …
```

chore: Change AST fuzzer recursion limit

---

compiler/noirc_evaluator/src/ssa/opt/inlining.rs

Resolves #8155
In reality this already had some docs but I wrote a bit more to make it clear what inlining is. The docs aren't long but with the tests in the file it should be clear what's going on. I also added a test for the recursive case.
I also took this opportunity to transform some SSA tests to use the SSA parser.
I wonder if this `inline_simple_functions` pass should be moved to its own file as it doesn't rely on the other methods (though it's a form of inlining so maybe it makes sense for all to be in the same file?)
Check one:

chore: document ssa `inline_simple_functions`

---

compiler/noirc_evaluator/src/ssa/opt/checked_to_unchecked.rs

Another try at #8111 but this time memoizing values max bit sizes to see if it doesn't make performance worse.
If we have code like this:
```noir
fn main(x: u1, z: u32) -> pub u32 {
let m = x as u32;
z * m
}
```
then we don't check for overflow in that multiplication because we know `m` was casted from `u1` which can only be 0 or 1.
If we have code like this:
```noir
fn main(x: u1, y: u1, z: u32) -> pub u32 {
let x = x as u32;
let y = y as u32;
let m = x * y;
z * m
}
```
then we shouldn't need to check for overflow either as we know `x * y` can be 1 or 0. However, there was no such check in our code so that's what this PR does.
I tried this in the past in #8111 but it turned out to be slow. The likely reason is that it was recursing without memoizing so hitting the same logic over and …

feat: optimize `checked_to_unchecked` to take into account multiplications

---

compiler/noirc_evaluator/src/ssa/opt/checked_to_unchecked.rs

No issue, just another optimization I thought of.
For example here:
https://github.com/noir-lang/noir-bignum/blob/ff2db6058cfe5906d60edcac1c89a9935bc688d2/src/fns/constrained_ops.nr#L185
We have `1 - more_than_N_minus_one_limbs` where `more_than_N_minus_one_limbs` is a boolean that was turned into `u32`. In this case it can never overflow. That's what this PR does but it generalizes this to any bit size (probably not very useful, but still...)
Check one:

feat: avoid overflow check when subtracting from a value that is the maximum for its bitsize

---

compiler/noirc_evaluator/src/ssa/function_builder/mod.rs
compiler/noirc_evaluator/src/ssa/parser/tests.rs
tooling/ast_fuzzer/src/program/mod.rs
tooling/ast_fuzzer/src/program/types.rs

fix: validate numeric types when passing them to a FunctionBuilder

---

test_programs/execution_panic/regression_8210/Nargo.toml
test_programs/execution_panic/regression_8210/src/main.nr

Resolves 
This PR adds a minimal reproduction for the panics being experienced in https://github.com/noir-lang/noir_bigcurve/pull/46
The issue for this panic is https://github.com/noir-lang/noir/issues/8210
Check one:

chore: add regression test for panic encountered in bigcurve library.

---

compiler/noirc_frontend/src/lib.rs
compiler/noirc_frontend/src/monomorphization/printer.rs
compiler/noirc_frontend/src/ownership/mod.rs
tooling/ast_fuzzer/fuzz/src/targets/acir_vs_brillig.rs
tooling/ast_fuzzer/fuzz/src/targets/init_vs_final.rs
tooling/ast_fuzzer/src/lib.rs
tooling/ast_fuzzer/src/program/func.rs
tooling/ast_fuzzer/src/program/mod.rs
tooling/ast_fuzzer/src/program/rewrite.rs
tooling/ast_fuzzer/tests/calibration.rs

Resolves #8240
Makes `Program::handle_ownership` public and calls it in `Context::finalize` to insert `Clone` into `unconstrained` functions where necessary. Added a `change_functions_into_unconstrained` to flip the `unconstrained` flag in every function of a `Program` and run the `handle_ownership` on them, which can now also be called on `Function`. 
I went back and forth between calling `handle_ownership` in `Context::finalize`, versus calling it in `create_ssa_or_die`. I thought we might have _rewrites_ in the future which could result in this method having to run again on an unconstrained function (where it would panic). In the end I put it in `finalize`, because that way the `CompareSsa::program` field contains an AST which is as close as possible to what we will execute, which …

fix: Call the ownership analysis

---

tooling/ast_fuzzer/fuzz/src/lib.rs
tooling/ast_fuzzer/fuzz/src/targets/acir_vs_brillig.rs
tooling/ast_fuzzer/fuzz/src/targets/init_vs_final.rs
tooling/ast_fuzzer/fuzz/src/targets/orig_vs_mutant.rs
tooling/ast_fuzzer/src/compare.rs

Resolves #8260 
Created a `CompareOptions` struct, currently with only the `inliner_aggressiveness` field, which is randomised during fuzzing so that we can compare ACIR vs Brillig with both having arbitrary inlining settings, and similarly the minimal pipeline vs the final, varying the setting of the latter.
We could add a separate target that compares the program to itself with a different pipeline setting, but I figured the ACIR vs Brillig case should cover it, since ACIR has to inline everything anyway.
Check one:

feat: Fuzz the inliner aggressiveness along with the AST

---

Cargo.lock
tooling/nargo/Cargo.toml
tooling/nargo/src/ops/test.rs

Should fix https://github.com/AztecProtocol/aztec-packages/issues/13921
Check one:

fix: use temporary dirs when fuzzing during `nargo test`

---

compiler/noirc_evaluator/src/ssa/ir/instruction.rs

Resolves #8130
Document Cast instruction.
Check one:

chore: document cast

---

acvm-repo/acvm/src/compiler/simulator.rs

Resolves 
This fixes an issue that @MirandaWood was running into on her [batched blobs branch](https://github.com/AztecProtocol/aztec-packages/pull/13817).
@kashbrti and I found the root cause is that if a memory block is passed as an argument to a brillig call then the `CircuitSimulator` marks it as "used" at which point it will reject any future writes to that memory block. I don't see any reason for why the simulator should reject this so I've replaced this logic with a simple check to ensure that we don't perform any reads/writes from uninitialized memory blocks.
@guipublic I think you originally wrote this logic, can you explain the motivation behind the old behaviour in case I'm missing something?
Check one:

fix: don't disallow writing to memory after passing it to brillig

---

tooling/nargo/src/ops/mod.rs
tooling/nargo/src/ops/test.rs
tooling/nargo_cli/src/cli/test_cmd.rs

feat: allow specifying fuzz-related dirs when invoking `nargo test`

---

compiler/noirc_driver/src/lib.rs
compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
compiler/noirc_frontend/src/hir/def_map/item_scope.rs
compiler/noirc_frontend/src/node_interner.rs
test_programs/compile_success_contract/contract_with_comptime_attributes/Nargo.toml
test_programs/compile_success_contract/contract_with_comptime_attributes/src/main.nr
tooling/nargo_cli/build.rs
tooling/nargo_cli/tests/execute.rs
tooling/nargo_cli/tests/snapshots/compile_success_contract/abi_attribute/execute__tests__force_brillig_false_inliner_0.snap
tooling/nargo_cli/tests/snapshots/compile_success_contract/contract_with_comptime_attributes/execute__tests__force_brillig_false_inliner_0.snap
tooling/nargo_cli/tests/snapshots/compile_success_contract/contract_with_impl/execute__tests__force_brillig_false_inliner_0.snap
tooling/nargo_cli/tests/snapshots/compile_success_contract/fold_non_contract_method/execute__tests__force_brillig_false_inliner_0.snap
tooling/nargo_cli/tests/snapshots/compile_success_contract/non_entry_point_method/execute__tests__force_brillig_false_inliner_0.snap
tooling/nargo_cli/tests/snapshots/compile_success_contract/simple_contract/execute__tests__force_brillig_false_inliner_0.snap

Resolves #8255
To do this:
- I wanted a test for this and one thing we can do is to start capturing snapshots of contract artifacts, which is what I did here (second commit)
- However, when I did that I noticed the output of functions was not deterministic. So the first commit makes it deterministic by sorting by function name.
- The third commit is the actual fix to the issue, and you can see in the diff how "(quoted)" changed to "utility" (and also how "super::add_utility" changed to "add_utility"), proving that the fix works 😊 
Check one:

fix: use correct meta attribute names in contract custom attributes

---

compiler/noirc_frontend/src/lexer/errors.rs
compiler/noirc_frontend/src/lexer/lexer.rs

Resolves #5163
Here's an example error we get now:
```
error: Unknown start of token: \u{a0}
┌─ src/main.nr:3:16
│
3 │     if true {}   else { // Placing "} else {" on the same line causes the issue
│                - Unicode character ' ' (No-Break Space) looks like ' ' (Space), but is it not
```
This is similar to what Rust outputs.
Check one:

feat: better error message on unicode whitespace that isn't ascii whitespace

---

acvm-repo/acvm/src/compiler/simulator.rs

Resolves #8288 
I'm not sure how barretenberg would handle this but if we emit two of these instructions for the same block id then there's a 99% chance that it's a bug.
Check one:

feat: disallow emitting multiple `MemoryInit` opcodes for the same block

---

docs/docusaurus.config.ts

Thanks dedyshkaPexto for https://github.com/noir-lang/noir/pull/8327. Our policy is to redo typo changes to dissuade metric farming. This is an automated script.

chore: redo typo PR by dedyshkaPexto

---

tooling/nargo_cli/build.rs
tooling/nargo_cli/src/cli/expand_cmd/printer/hir.rs
tooling/nargo_cli/tests/snapshots/expand/compile_success_empty/regression_4436/execute__tests__expanded.snap
tooling/nargo_cli/tests/snapshots/expand/compile_success_empty/regression_4635/execute__tests__expanded.snap
tooling/nargo_cli/tests/snapshots/expand/compile_success_no_bug/noirc_frontend_tests_traits_returns_self_in_trait_method_1/execute__tests__expanded.snap
tooling/nargo_cli/tests/snapshots/expand/compile_success_no_bug/noirc_frontend_tests_traits_returns_self_in_trait_method_2/execute__tests__expanded.snap
tooling/nargo_cli/tests/snapshots/expand/compile_success_no_bug/noirc_frontend_tests_traits_returns_self_in_trait_method_3/execute__tests__expanded.snap
tooling/nargo_cli/tests/snapshots/expand/compile_success_no_bug/noirc_frontend_tests_uses_self_type_for_struct_function_call/execute__tests__expanded.snap
tooling/nargo_cli/tests/snapshots/expand/compile_success_no_bug/noirc_frontend_tests_uses_self_type_inside_trait/execute__tests__expanded.snap
tooling/nargo_cli/tests/snapshots/expand/compile_success_no_bug/noirc_frontend_tests_visibility_does_not_error_if_calling_private_struct_function_from_same_struct/execute__tests__expanded.snap
tooling/nargo_cli/tests/snapshots/expand/execution_success/binary_operator_overloading/execute__tests__expanded.snap
tooling/nargo_cli/tests/snapshots/expand/execution_success/unary_operator_overloading/execute__tests__expanded.snap

fix(expand): try to use "Self" in function calls

---

tooling/nargo/src/ops/test.rs
tooling/nargo_cli/src/cli/test_cmd.rs

Part of #8214
I let the default timeout be 1 second. The original issue says 10 seconds but I think that's too long if tests are supposed to pass. But let me know otherwise! (additionally: 1 second was the default value before this PR too, though just for `nargo test`).
Check one:

feat: add `--fuzz-timeout` to `nargo test` options

---

.github/workflows/publish-nargo.yml

Resolves https://github.com/noir-lang/noir/actions/runs/14843771760/job/41672674126?pr=8307#step:6:123
Adds `GITHUB_TOKEN` to "Build binaries" in `publish-nargo.yml`
Check one:

chore: Add GITHUB_TOKEN to cross build

---

Cargo.lock
Cargo.toml
deny.toml

Resolves 
This PR bumps jsonrpsee to address https://github.com/rustls/rustls-platform-verifier/issues/164 which breaks the checks for whether the ACVM crates can be published.
I've also bumped all of the ACVM deps.
Check one:

chore: bump dependencies

---

tooling/nargo_cli/tests/execute.rs

Resolves #8351 
This shifts us from having target directory inside of `test_programs` to it being a designated temp directory. This avoids the need for us to rebuild after running the tests as we're no longer writing to the `test_programs` directory.
Check one:

chore: avoid need to rebuild after running tests

---

CONTRIBUTING.md

chore: add note on AI generated PRs in `CONTRIBUTING.md`

---

tooling/ast_fuzzer/src/lib.rs
tooling/ast_fuzzer/src/program/freq.rs
tooling/ast_fuzzer/src/program/func.rs
tooling/ast_fuzzer/src/program/scope.rs

Resolves 
This PR applies the `unreachable_pub` lint to the `ast_fuzzer` crate like the rest of our crates.
Check one:

chore: apply lints to `ast_fuzzer`

---

docs/docs/tooling/fuzzing.md
tooling/greybox_fuzzer/src/lib.rs
tooling/nargo/src/ops/fuzz.rs
tooling/nargo_cli/src/cli/fuzz_cmd.rs
tooling/nargo_cli/src/cli/test_cmd.rs

It is now possible to limit fuzzing not just by time, but also by the number of executions. It should come in handy with fuzz tests.
Check one:

feat(greybox_fuzzer): Maximum executions parameter added

---

SUPPORT.md
scripts/redo-typo-pr.sh

Thanks shystrui1199 for https://github.com/noir-lang/noir/pull/8320. Our policy is to redo typo changes to dissuade metric farming. This is an automated script.

chore: redo typo PR by shystrui1199

---

EXTERNAL_NOIR_LIBRARIES.yml

Resolves 
This PR bumps the commits of the noir jwt library so that we can compile it and run tests.
Check one:

chore: bumping external libraries

---

compiler/noirc_evaluator/src/ssa/ir/types.rs
compiler/noirc_evaluator/src/ssa/parser/tests.rs

Resolves #8408
Let me know if composite types shouldn't be surrounded by parentheses. It's something I already did for arrays a long time ago (when writing the SSA parser, or maybe even before that).
I can't remember why I added those parentheses, it was maybe for clarity or to avoid an ambiguity.
Then I just tried to generate SSA for this code:
```noir
fn main() {
let _ = [(); 4];
}
```
The result is:
```noir
acir(inline) fn main f0 {
b0():
v0 = make_array [] : [(); 4]
return
}
```
I guess without those `()` it would look like `[; 4]` so we'd have to assume, when parsing, that if no type comes it's an empty list... but maybe that makes it harder to distinguish between that and a mistake.
I think back when I implemented the SSA parser I wasn't sure what all types were, so when parsing …

fix: print slice composite types surrounded by parentheses

---

compiler/noirc_frontend/src/hir/comptime/mod.rs

Resolves 
Some docs I wrote while writing another PR. I'm pulling this our here so that we can merge separately.
Check one:

chore: add minor docs for interpreter

---

compiler/noirc_evaluator/src/acir/tests/intrinsics.rs
compiler/noirc_evaluator/src/acir/tests/mod.rs

Resolves https://github.com/noir-lang/noir/pull/8355#discussion_r2078441068
So although this resolves the comment on #8355, this functionality can be tested in isolation without considering that PR at all. The following was done to determine whether a predicate affected a certain instruction:
1. Setup an SSA where there is only instruction after `EnableSideEffectIf` instruction on a dynamic predicate
2. Check the ACIR and final witness index for an SSA where that `EnableSideEffectIf` is in place and an SSA where there is no `EnableSideEffectIf`.
3.  If the instruction is meant to be unaffected by the predicate, check for equality. If the predicate is meant to have an affect, check for inequality.
For example we may have this SSA:
```
acir(inline) predicate_pure fn main f0 {
b0(v0: u32, …
```

chore(acir): Test whether the predicate has an effect on slice intrinsics

---

EXTERNAL_NOIR_LIBRARIES.yml
docs/docs/tooling/testing.md
tooling/nargo_cli/src/cli/test_cmd.rs

Resolves 
Fuzzing tests are now run after the main tests and each fuzzing test uses parallelisation internally instead of just being assigned 1 thread. The limits have also been changed to 100k executions and 1 second.
Check one:

feat(greybox_fuzzer): Parallel fuzz tests

---

tooling/ast_fuzzer/src/program/func.rs
tooling/ast_fuzzer/src/program/mod.rs
tooling/ast_fuzzer/src/program/types.rs

Resolves us having to deal with https://github.com/noir-lang/noir/issues/8451 and constantly being pinged from smoke tests failing in aztec-packages such as http://ci.aztec-labs.com/3ecfe93088757b18
0 length arrays and strings produce no witnesses, but the code generated for them currently differs when they are in the databus vs when they are accessed as normal variables. When they are accessed as both, we run into problems. 
Since they are not expected in real programs, we can save ourselves jumping through hoops if we disallow them altogether. Expecting that to happen, this PR changes the AST fuzzer to stop using these types in the input and output of `main`. 
Check one:

chore(fuzz): Do not use zero length types in the main input output

---

tooling/ast_fuzzer/src/program/mod.rs

Resolves a typo in filtering logic
Fixes `!is_main || !types::can_be_main(typ)` to be `!is_main || types::can_be_main(typ)`. 
The impact isn't huge, because it only filters the use of types that exist at the time already, which, when we pick parameters for `main`, is only the globals. In other words, we did not exclusively use anathema types for `main`. 
(I think I originally wanted to write `!is_main || !types::is_zero_length(typ)` before I changed my mind to match `can_be_global`, but didn't notice the `!` I already laid down 🤦 )
Check one:

fix: Typo in filtering of types that can be used in `main`

---

compiler/noirc_evaluator/src/ssa/opt/remove_unreachable.rs
test_programs/execution_success/function_ref/Nargo.toml
test_programs/execution_success/function_ref/Prover.toml
test_programs/execution_success/function_ref/src/main.nr
test_programs/execution_success/function_ref/stdout.txt
tooling/nargo_cli/tests/snapshots/execution_success/function_ref/execute__tests__force_brillig_false_inliner_-9223372036854775808.snap
tooling/nargo_cli/tests/snapshots/execution_success/function_ref/execute__tests__force_brillig_false_inliner_0.snap
tooling/nargo_cli/tests/snapshots/execution_success/function_ref/execute__tests__force_brillig_false_inliner_9223372036854775807.snap
tooling/nargo_cli/tests/snapshots/execution_success/function_ref/execute__tests__force_brillig_true_inliner_-9223372036854775808.snap
tooling/nargo_cli/tests/snapshots/execution_success/function_ref/execute__tests__force_brillig_true_inliner_0.snap
tooling/nargo_cli/tests/snapshots/execution_success/function_ref/execute__tests__force_brillig_true_inliner_9223372036854775807.snap
tooling/nargo_cli/tests/snapshots/expand/execution_success/function_ref/execute__tests__expanded.snap

Part of https://github.com/noir-lang/noir/issues/8218
Adds tests that would fail if the `remove_unreachable_functions` did not consider function references as reachable.
Check one:

chore(test): Add more tests for the removal of unused functions

---

compiler/noirc_frontend/src/ast/mod.rs
compiler/noirc_frontend/src/parser/errors.rs
compiler/noirc_frontend/src/parser/parser/expression.rs
compiler/noirc_frontend/src/parser/parser/types.rs
tooling/nargo_fmt/src/formatter/expression.rs

Related to #8470
This is valid Noir code:
```noir
fn foo<let N: u32>(fields: [Field; N]) -> str<N> {
str<N>::from(fields.map(|value| value as u8))
}
```
However, the syntax `str<N>` is inconsistent with the rest of the language. For example for a `Vec` you'd write `Vec::<N>::from(...)`, that is, with colons between `Vec` and `<`.
This PR will now parse:
- `str::<N>::from` as correct syntax (same with `fmtstr`)
- warn if there's no `::` between `str` and `<` (only in a TypePath)
- have the formatter fix the incorrect syntax to the new syntax, so the upgrade path is easy (just run `nargo fmt` on your project)
After this is merged we can fix the syntax in Aztec-Packages, then https://github.com/noir-lang/noir/pull/8470 wouldn't produce errors in Aztec-Packages anymore.
Check one:

fix: warn if no double colon on generic type in type path

---

compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
compiler/noirc_frontend/src/hir/def_collector/errors.rs
compiler/noirc_frontend/src/hir_def/types.rs
test_programs/compile_failure/main_with_generics/Nargo.toml
test_programs/compile_failure/main_with_generics/src/main.nr
test_programs/compile_failure/main_with_generics/stderr.txt

fix: disallow generics on entry points

---

compiler/noirc_evaluator/src/ssa/interpreter/tests/mod.rs

and mutable references to functions
Resolves 
Made a quick test of how the interpreter handles higher-order functions, based on the `After initial SSA` output:
```noir
fn f(x: u8) -> bool {
x == 0
}
fn g(x: u8) -> bool {
x == 1
}
fn foo(fg: fn(u8) -> bool) -> bool {
fg(0) != fg(1)
}
fn bar(f: &mut (fn(u8) -> bool), g: fn(u8) -> bool) {
*f = g;
}
fn main(b: bool) {
let mut h = f;
if b {
bar(&mut h, f);
} else {
bar(&mut h, g);
}
assert(foo(h));
}
```
Check one:

chore: add SSA interpreter test for higher order functions

---

noir_stdlib/src/meta/typ.nr
noir_stdlib/src/meta/unresolved_type.nr

Resolves 
There's a number of documented methods which look like they're intended to be public but are marked as private here. This PR marks them as public.
Check one:

fix: fix visibility of methods in `std::meta`

---

compiler/noirc_frontend/src/ast/statement.rs
compiler/noirc_frontend/src/ast/visitor.rs
compiler/noirc_frontend/src/debug/mod.rs
compiler/noirc_frontend/src/elaborator/patterns.rs
compiler/noirc_frontend/src/hir/comptime/display.rs
compiler/noirc_frontend/src/hir_def/types.rs
compiler/noirc_frontend/src/parser/parser/pattern.rs
compiler/noirc_frontend/src/tests.rs
compiler/noirc_printable_type/src/lib.rs
test_programs/compile_failure/noirc_frontend_tests_do_not_infer_partial_global_types/stderr.txt
tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/inlay_hint.rs
tooling/lsp/src/with_file.rs
tooling/nargo_fmt/src/formatter/global.rs
tooling/nargo_fmt/src/formatter/pattern.rs

Resolves #8475
Resolves #8476
The first commit introduces a new pattern, the parenthesized pattern, which is when you do `let (x) = ...;`, which is similar to `let x = ...;`, but previously was parsed as a 1-element tuple. This is to match Rust's syntax and semantic.
The rest of the commits make sure that printing 1-element tuples in several contexts always includes a trailing comma.
Check one:

fix: parenthesized pattern, and correct 1-element tuple printing

---

tooling/ast_fuzzer/src/program/mod.rs
tooling/ast_fuzzer/src/program/rewrite.rs
tooling/ast_fuzzer/src/program/tests.rs

Preparation for https://github.com/noir-lang/noir/issues/8484
So far the `ctx_limit: &mut u32` parameter has only been added to functions which called other functions. Now it will be part of the signature of all functions except `main`.  
The PR also changes generation so only those Brillig functions which are called from ACIR get a `_proxy` variant, to reduce noise. We also stop generating ACIR functions if `main` is Brillig, because in code generated by the monomorphizer Brillig will only call other Brillig functions (apart from the #7279 problem). This is also to reduce noise. 
In #8484 I want to pass function pointers as arguments in the generated AST. 
Say we had program like this:
```rust
fn main() -> u32 {
baz(bar)
}
fn foo() -> u32 {
1 
}
fn bar() -> u32 {
2 + foo()
}
fn baz(f: …
```

chore(fuzz): AST generator to add `ctx_limit` to all functions

---

compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs

No issue but something leftover from https://github.com/noir-lang/noir/pull/7660
We handle `PureWithPredicate` functions the same way we do `Constrain`, `ConstrainNotEqual`, and `RangeCheck`. 
Check one:

chore(performance): Enable hoisting pure with predicate calls

---

compiler/noirc_evaluator/src/ssa/interpreter/mod.rs

Accidentally merged as part of https://github.com/noir-lang/noir/pull/8469 which was set to auto-merge
Check one:

chore: Remove println in ssa interpreter

---

tooling/ast_fuzzer/src/lib.rs
tooling/ast_fuzzer/src/program/func.rs
tooling/ast_fuzzer/src/program/mod.rs
tooling/ast_fuzzer/src/program/rewrite.rs
tooling/ast_fuzzer/src/program/rewrite/limit.rs
tooling/ast_fuzzer/src/program/rewrite/mod.rs
tooling/ast_fuzzer/tests/smoke.rs

Resolves #8484
Call and pass on function pointers in code generated by the AST fuzzer. 
I refactored the `rewrite` module in the fuzzer because it was difficult to see what was going on, and also needed recursion.
Blocked by ICE in https://github.com/noir-lang/noir/issues/8543 
For now I added a flag to turn lambdas off in the smoke test for now so we can merge this and not fail on aztec-packages.
Here's an example, generated by the following sample:
```shell
NOIR_ARBTEST_SEED=0x5824e5b200100000 cargo test -p noir_ast_fuzzer --test smoke 
```
It shows the `&mut u32` or `u32` added to the function pointers in the parameters
```rust
...
unconstrained fn main(a: i64, b: call_data(1) i64, c: i64) -> pub ((i64, i64), (bool, bool, bool, i64), u64, i16, Field) {
let mut ctx_limit = 25;
let d = …
```

chore(fuzz): Call function pointers

---

compiler/noirc_evaluator/src/ssa/opt/die/prune_dead_parameters.rs

Resolves 
We're currently printing a huge number of elements which isn't really useful.
Check one:

fix: avoid logging all unused params in DIE pass

---

compiler/noirc_frontend/src/hir_def/types.rs

Resolves #8565 
I have tested locally that I can compile the `noir-protocol-circuits` zero variants by prefixing a call to `nargo` with `ALLOW_EMPTY_INPUT=1`.
I went with an environment variable as it felt like the least instructive hot fix (e.g. threading a compilation flag or a patch on aztec-packages felt more complicated that simply providing an override).
Once https://github.com/AztecProtocol/aztec-packages/issues/14388 is resolved we can remove this environment variable.
Check one:

fix(frontend): Override to allow empty array input

---

compiler/noirc_frontend/src/elaborator/comptime.rs
compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/elaborator/patterns.rs
compiler/noirc_frontend/src/elaborator/traits.rs
compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/hir/comptime/tests.rs
compiler/noirc_frontend/src/hir_def/types.rs
compiler/noirc_frontend/src/hir_def/types/arithmetic.rs
compiler/noirc_frontend/src/monomorphization/mod.rs
compiler/noirc_frontend/src/node_interner.rs
tooling/nargo_cli/src/cli/expand_cmd/printer/hir.rs

Resolves 
Minor speedup, not expected to be noticeable. Broken out of the optimize canonicalize change.
Check one:

chore: Use FxHashMap for TypeBindings

---

compiler/noirc_evaluator/src/ssa.rs
tooling/ast_fuzzer/fuzz/src/targets/acir_vs_brillig.rs
tooling/ast_fuzzer/src/lib.rs

Follow up for https://github.com/noir-lang/noir/pull/8573
Stop avoiding lambdas in AST fuzzing.
Check one:

chore(test): Allow lambdas in fuzzing

---

compiler/noirc_evaluator/src/errors.rs

Resolves #6407 
This PR updates the warning to be more explicit about what the ACVM does when encountering this opcode.
Check one:

chore: update warning on `std::verify_proof`

---

compiler/noirc_evaluator/src/ssa/interpreter/mod.rs
compiler/noirc_evaluator/src/ssa/interpreter/tests/instructions.rs
compiler/noirc_frontend/src/hir/comptime/interpreter/infix.rs

Resolves #8615 
As overflowing shift left returns zero just like a shift right during execution:
https://github.com/noir-lang/noir/blob/8f660a3a6c8b1e48b9e988d181a65df44e0bc715/acvm-repo/brillig_vm/src/arithmetic.rs#L245
However, in both the comptime interpreter and and the SSA interpreter we simply errored out with an overflow.
https://github.com/noir-lang/noir/pull/8638#issuecomment-2902061280
Check one:

fix(ssa interpreter): Default to zero when we have an overflowing shl

---

tooling/ast_fuzzer/fuzz/src/targets/acir_vs_brillig.rs
tooling/ast_fuzzer/fuzz/src/targets/orig_vs_morph.rs

Resolves https://github.com/noir-lang/noir/pull/8452#issuecomment-2901736666
This fuzzer test is failing on all several PRs non-deterministically.
Just blocks the test in CI for now, we can bring it back later once the failures are resolved.
Check one:

chore(ci): Do not run ast_fuzzer orig vs. morph in ci

---

compiler/noirc_evaluator/src/ssa/ir/printer.rs
compiler/noirc_evaluator/src/ssa/parser/tests.rs

fix(SSA): don't use string literal if byte is "form feed" ('\f')

---

.config/nextest.toml
.github/workflows/test-rust-workspace-arm64.yml
.github/workflows/test-rust-workspace-msrv.yml
.github/workflows/test-rust-workspace.yml

Resolves 
This PR disables running the fuzzer in the merge queue as it's just causing unnecessary friction as people need to push an otherwise good PR back in to the queue.
Check one:

chore(ci): avoid running fuzzer tests in the merge queue

---

compiler/noirc_evaluator/src/ssa/ir/function.rs
compiler/noirc_evaluator/src/ssa/opt/inlining.rs
compiler/noirc_evaluator/src/ssa/opt/simplify_cfg.rs
compiler/noirc_evaluator/src/ssa/parser/into_ssa.rs
compiler/noirc_evaluator/src/ssa/parser/tests.rs

…formed
Resolves 
This PR adds a quick sanity check when parsing SSA that we satisfy some rules on block terminator instructions.
Check one:

chore: add an assertion when parsing SSA that all functions are well-formed

---

compiler/noirc_evaluator/src/ssa/parser/into_ssa.rs
compiler/noirc_evaluator/src/ssa/parser/tests.rs

fix: (SSA parser) translate blocks in logical order rather than syntax order

---

compiler/noirc_frontend/src/ast/expression.rs
compiler/noirc_frontend/src/ast/mod.rs
compiler/noirc_frontend/src/ast/statement.rs
compiler/noirc_frontend/src/hir_def/types.rs
compiler/noirc_frontend/src/monomorphization/ast.rs
compiler/noirc_frontend/src/monomorphization/tests.rs

While debugging https://github.com/noir-lang/noir/issues/8592#issuecomment-2913363410 I noticed 1-tuple printing was off in a few more places.
Maybe this logic could be in a helper function? Though I don't know where we'd put it, and things like `utils.rs` might not be a good pattern, not sure.
Check one:

chore: more 1-tuple printing fixes

---

Cargo.lock
Cargo.toml
tooling/ast_fuzzer/src/compare/interpreted.rs
tooling/ast_fuzzer/src/compare/mod.rs
tooling/ast_fuzzer/src/lib.rs
tooling/nargo_cli/Cargo.toml
tooling/nargo_cli/src/cli/compile_cmd.rs
tooling/nargo_cli/src/cli/interpret_cmd.rs
tooling/nargo_cli/src/cli/mod.rs

@guipublic said he would like to use the SSA interpreter to evaluate the SSA at a certain point in the pipeline to debug some issue. 
This is related to https://github.com/noir-lang/noir/issues/8503 , but instead of working on a stand-alone SSA snippet where we would have to come up with some input format as well, it taps into the existing flow of `nargo`, dealing with Noir source code and TOML/JSON input, which I thought was a low hanging fruit and fits into our typical workflow.
Adds a new `nargo interpret` command compiles the source code, looks for binary packages, parses their `Prover.toml` file, then uses the SSA Interpreter to evaluate the SSA after each pass, according to the `--ssa-pass` filter, which can accept multiple passes, similar to `--show-ssa-pass`. 
At the moment it …

feat(cli): Add `nargo interpret` command

---

compiler/noirc_frontend/src/hir_def/types.rs

This PR reverts #8568 as aztec-packages has been updated to remove these zero length inputs.
Check one:

chore: remove override for zero length inputs

---

tooling/ast_fuzzer/fuzz/src/targets/comptime_vs_brillig.rs
tooling/ast_fuzzer/src/program/func.rs

While generating loops, the fuzzer would often place `break` inside a let stament in a loop, leading to https://github.com/noir-lang/noir/issues/8629. This should be a quick fix for these appearances.
Check one:

fix(fuzz): Prevent breaking/continuing out from let blocks in the AST fuzzer

---

compiler/noirc_frontend/src/ast/expression.rs
compiler/noirc_frontend/src/ast/mod.rs
compiler/noirc_frontend/src/elaborator/expressions.rs
compiler/noirc_frontend/src/parser/parser/expression.rs
tooling/lsp/src/with_file.rs
tooling/nargo_fmt/src/formatter/expression.rs

Resolves 
`StatementOrExpressionOrLValue` is screaming at me for being over a kilobyte in size. This PR shrinks it down to being 416 bytes so we don't need to move so much memory around all the time.
Check one:

chore: box `AsTraitPath` and `TypePath` in `ExpressionKind`

---

.github/critical_libraries_status/noir-lang/noir_rsa/.failures.jsonl
EXTERNAL_NOIR_LIBRARIES.yml

The library is archived and it won't compile anymore with some breaking changes that are going to happen with the language.
Check one:

chore: remove noir-lang/noir_rsa from external libraries

---

compiler/noirc_evaluator/src/ssa/opt/defunctionalize.rs

Resolves "Missing ArraySet case in Defunctionalize pass" [issue](https://audithub.veridise.com/app/organizations/85/projects/277/project-viewer?version=433&bpt=1&issue=15&thread=2873) from Veridise
Instead of adding only ArraySet I figured it'd be more future-proof to match on the values from any instruction.
Check one:

fix: Add missing cases for finding function values in `find_functions_as_values`

---

compiler/noirc_evaluator/src/ssa/ir/dfg.rs
compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs
compiler/noirc_evaluator/src/ssa/parser/tests.rs

Resolves #8544
Also added a check that for other binary operations the types of lhs and rhs is the same.
Check one:

chore(SSA): restrict `shr` and `shl` right-hand side to u8

---

compiler/noirc_evaluator/src/ssa/opt/defunctionalize.rs

Resolves the following audit issues:
* [Array and slice types with deeply nested function types are not fully updated](https://audithub.veridise.com/app/organizations/85/projects/277/project-viewer?bpt=1&version=433&issue=21)
* [Missing/incorrect cases when replacing function types](https://audithub.veridise.com/app/organizations/85/projects/277/project-viewer?bpt=1&version=433&issue=18)
* Removes `is_function_type` and changes `replacement_type` to return an `Option`, so there is no need for guarding the latter with the former. 
* Makes `replacement_type` recursive. 
* Uses `replacement_type` to handle types in arrays and slices.
* Extends `replacement_type` to consider arrays/slices that contain types with functions, recursively.
Check one:

fix: Merge `replacement_type` and `is_function_type` in `defunctionalization`

---

Cargo.toml

Resolves #4754 
This PR switches us over to using some of the optimized assembly implementations of arkworks logic for free performance.
Check one:

feat: use `asm` feature flag in arkworks

---

compiler/noirc_evaluator/src/ssa/validation/mod.rs

Resolves #8517 
Builds upon #8765 
We simply now type check calls to the ToRadix and ToBits intrinsics that their first arguments is a field type and the second argument is an unsigned 32 bit integer.
Check one:

fix(ssa): Type check ToRadix and ToBits intrinsic calls

---

compiler/noirc_evaluator/src/ssa/ir/map.rs

chore: small fix for outdated docs

---

compiler/noirc_frontend/src/elaborator/enums.rs
compiler/noirc_frontend/src/elaborator/path_resolution.rs
compiler/noirc_frontend/src/elaborator/patterns.rs
compiler/noirc_frontend/src/elaborator/types.rs
test_programs/compile_success_empty/type_trait_method_call_multiple_candidates/Nargo.toml
test_programs/compile_success_empty/type_trait_method_call_multiple_candidates/src/main.nr
tooling/nargo_cli/build.rs
tooling/nargo_cli/tests/snapshots/compile_success_empty/type_trait_method_call_multiple_candidates/execute__tests__force_brillig_false_inliner_0.snap

Resolves #8794
The main issue here was that when you had a call like this:
```noir
SomeConcreteType::trait_method(...)
```
that would resolve to a trait method, but we'd throw away the information that this was called on `SomeConcreteType`.
So in the example of #8794:
- when we elaborate `MyU128::from` we end up with a type `fn('4) -> '5`
- then when we elaborate the call, `MyU128::from(x)`, given `x : u64` we end up with `fn(u64) -> '5`
The problem is that the return type is still unknown at this point.
Checking with Rust, it could figure out the return type even if we didn't call the function, for example like this:
```rust
// Rust doesn't know the argument types, but it knows it returns MyU128
let f = MyU128::from;
```
We already have specific code to solve …

fix: bind self generic type in trait calls via a concrete type

---

compiler/noirc_frontend/src/hir_def/types.rs
compiler/noirc_frontend/src/hir_def/types/arithmetic.rs

Resolves 
This PR removes the call to `follow_bindings` which happens multiple times on the same type per `canonicalize` call. This method does a large amount of cloning and a single call goes through the full `Type` structure. We can then call `follow_bindings` once on the entrypoint and consider all bindings as having been followed after that.
I've done a small amount of reworking of this module so that all the `pub(crate)` methods call `follow_bindings` so an external consumer of the module doesn't need to manually call `follow_bindings` themselves.
Check one:

chore: only follow bindings on interface to `arithmetic` module

---

compiler/noirc_evaluator/src/errors.rs
compiler/noirc_evaluator/src/ssa.rs
compiler/noirc_evaluator/src/ssa/ir/dfg/simplify/call.rs
compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs
compiler/noirc_evaluator/src/ssa/opt/flatten_cfg/value_merger.rs
compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs
compiler/noirc_evaluator/src/ssa/opt/simple_optimization.rs

Working towards https://github.com/noir-lang/noir/issues/8741
Unfortunately this does not 100% solve the issue. We issue a RuntimeError now but panic when reporting the error since the call stack is empty. It turns out none of the call stacks for then_value, else_value, then_condition, or else_condition have any call stacks. This PR is already quite large though so I thought I'd keep this one focused on just error handling.
~~These changes are all just threading RuntimeError through more places in SSA to account for the fact we can now error when inserting instructions.~~ The above is still true but we only thread through remove_if_else now and fail to optimize slice_push_back instead of propagating up further.
Check one:

fix: Thread errors through remove_if_else instead of panicing when the value merger finds reference values

---

compiler/noirc_evaluator/src/ssa/interpreter/errors.rs
compiler/noirc_evaluator/src/ssa/interpreter/mod.rs
compiler/noirc_frontend/src/monomorphization/printer.rs
compiler/noirc_frontend/src/ownership/tests.rs
tooling/ast_fuzzer/fuzz/src/targets/comptime_vs_brillig.rs
tooling/ast_fuzzer/fuzz/src/targets/orig_vs_morph.rs
tooling/ast_fuzzer/src/compare/interpreted.rs
tooling/ast_fuzzer/src/compare/mod.rs
tooling/ast_fuzzer/src/lib.rs
tooling/ast_fuzzer/src/program/func.rs
tooling/ast_fuzzer/tests/calibration.rs

Resolves #7932 
Generate arbitrary constraints in the AST fuzzer. Using a low frequency so not every execution results in constraint failure. 
Changed the AST printer to show `assert` instead of the deprecated `constrain` keyword, and display the message as well. Also added the message to the SSA interpreter to make it easier to find which constraint caused the failure.
I noticed during testing that the SSA changes the types it runs the constraints on, and thus their display value as well:
```
both programs failed:
constrain v37 == v38, "TBF" failed:
Field 313339671284855045676773137498590239475 != Field 0
!=
constrain v49 == v42, "TBF" failed:
u128 313339671284855045676773137498590239475 != u128 0
```
and
```
both programs failed:
constrain v86 == v94, "ISC" failed:
i64 -1615928006 != …
```

feat(fuzz): Generate arbitrary constraints

---

compiler/noirc_evaluator/src/ssa/parser/into_ssa.rs
compiler/noirc_evaluator/src/ssa/parser/tests.rs

Resolves #8737
There was already forward-declarations for functions, except that an entry was missing for the main function (because it's handled a bit differently).
Check one:

fix: support recursive call to main function in SSA parser

---

docs/docs/tutorials/noirjs_app.md
docs/versioned_docs/version-v1.0.0-beta.6/tutorials/noirjs_app.md

Update to use the latest version
Resolves 
Check one:

chore(docs): Update noirjs app page to use to beta.6

---

EXTERNAL_NOIR_LIBRARIES.yml

Updating the commit for the external lib [tdd.nr](https://github.com/teddav/tdd.nr), due to a breaking change in Noir: https://github.com/noir-lang/noir/pull/8804#issuecomment-2949260604

fix: update external lib commit tdd.nr

---

compiler/noirc_evaluator/src/ssa/interpreter/mod.rs
compiler/noirc_evaluator/src/ssa/interpreter/tests/instructions.rs

Resolves #8864
Also uncomments a couple of tests that now can be written.
Check one:

fix: (SSA interpreter) check requires_acir_gen_predicate for enable_side_effects

---

compiler/noirc_evaluator/src/ssa/ir/dfg/simplify.rs

No issue just something I noticed when looking at the Truncate simplification.
If we are truncating to a `bit_size` but the `max_bit_size` is less than that value, we can return the value.
Check one:

chore(ssa): Simplify truncate when the bit size we are truncating to is greater than the value's max bit size

---

compiler/noirc_driver/src/abi_gen.rs
compiler/noirc_driver/src/lib.rs
tooling/nargo_cli/build.rs
tooling/nargo_cli/src/cli/interpret_cmd.rs
tooling/nargo_cli/tests/execute.rs
tooling/noirc_abi/src/errors.rs
tooling/noirc_abi/src/input_parser/json.rs
tooling/noirc_abi/src/input_parser/toml.rs
tooling/noirc_abi_wasm/test/browser/errors.test.ts
tooling/noirc_abi_wasm/test/node/errors.test.ts

No issue, but will help us improve the interpreter.
Runs `nargo interpret` against all execution_success test programs, except a few that currently don't work well.
Also fixes one issue where the ABI was built in a way that doesn't match how it's built everywhere else (this made some tests fail, which were around 43, and then the number got down to 35).
I decided to not keep fixing issues here as there seem to be a few of them. Some of them might be easier to fix (like the "IntrinsicArgumentCountMismatch" ones), but in any case we can probably fix them in follow-up PRs.
Check one:

chore: interpret all execution_success programs

---

compiler/noirc_evaluator/src/ssa/opt/defunctionalize.rs

Resolves 
We often get some suboptimal CFG coming out of the defunctionalization pass. `simplify_cfg` is a very lightweight pass and would be acting on small functions so I think it's worth simplifying the apply functions immediately.
Check one:

feat: simplify apply function cfg immediately

---

compiler/noirc_evaluator/src/errors.rs
compiler/noirc_evaluator/src/ssa.rs
compiler/noirc_evaluator/src/ssa/validation/dynamic_array_indices.rs
compiler/noirc_evaluator/src/ssa/validation/mod.rs
docs/docs/noir/concepts/data_types/arrays.md

Resolves https://github.com/noir-lang/noir/issues/8750
It's not clear how we'll support this in the future so let's ban any dynamic indexing of arrays which have reference elements. We can always lift this later when we're able. Since this panics at the moment it is not expected to break existing code.
This does not fix https://github.com/noir-lang/noir/issues/8779 since the array get is optimized out beforehand there.
Check one:

chore: Ban dynamic array indices with reference elements

---

compiler/noirc_evaluator/src/ssa/interpreter/value.rs
compiler/noirc_evaluator/src/ssa/ir/function.rs
tooling/nargo_cli/build.rs
tooling/nargo_cli/src/cli/interpret_cmd.rs

Resolves #8450
Now the SSA interpreter CLI won't fail against an expected return value if the main function returns `return_data`. This is done by flattening all values in the expected return value. See the comment in the code for an explanation of why I decided to do it that way.
Check one:

fix: handle return_data in the interpreter SSA CLI

---

docs/docs/noir/concepts/data_types/arrays.md
tooling/ast_fuzzer/src/program/func.rs

Resolves #8930 
Changes the fuzzer to not call Brillig functions to produce an index which is to be used with an array that contains references, as these values are opaque for the compiler in the ACIR function.
Check one:

fix(fuzz): Consider values returned from Brillig to ACIR as dynamic

---

README.md

We should make the status of nightly fuzzing visible somewhere.
Adds a status badge to the README.
Maybe some Slack notifications would be useful as well. As I understand the last person to edit the workflow gets an email notification, so I can keep an eye on it.
Check one:

chore(fuzz): Display nightly fuzz status badge

---

.github/benchmark_projects.yml
.github/workflows/reports.yml
.github/workflows/test-js-packages.yml

Resolves 
These parts of CI fail on external PRs as we restrict access to the relevant access token permissions. This results in a decent amount of confusion for external contributors so it's worth adding a couple of lines to just skip these steps in these situations rather than just letting them fail.
Check one:

chore: disable noncritical workflow steps which fail on external prs

---

compiler/noirc_frontend/src/hir/comptime/interpreter.rs
compiler/noirc_frontend/src/hir/comptime/interpreter/builtin/builtin_helpers.rs
compiler/noirc_frontend/src/hir/comptime/interpreter/unquote.rs
compiler/noirc_frontend/src/hir/comptime/value.rs
test_programs/compile_failure/comptime_error_on_macro_expansion/Nargo.toml
test_programs/compile_failure/comptime_error_on_macro_expansion/src/main.nr
test_programs/compile_failure/comptime_error_on_macro_expansion/src/other.nr
tooling/nargo_cli/tests/snapshots/compile_failure/comptime_error_on_macro_expansion/execute__tests__stderr.snap
tooling/nargo_cli/tests/snapshots/compile_failure/comptime_parse_all_tokens/execute__tests__stderr.snap

No issue, just something confusing mentioned over Slack that could be improved.
Two things here:
1. When a macro parse error happened we'd show the just first error. The issue was that in the list of "errors" warnings could exist too. So here we discard warnings and truly show the first error. (Maybe ideally we'd show all errors and warnings here but I'm not sure how we'd show that as a result of a macro expansion, so I did the minimum thing to improve the situation without introducing a large change).
2. The location of the `$expr` token ended up being the location of the `quote` expression that held it, making errors point to that entire quote (as can be seen in the second commit). This was likely done before everything started holding a Location instead of a Span. The second …

fix: when macro parse error happens, discard warnings; also preserve unquoted token locations

---

compiler/noirc_evaluator/src/ssa.rs
tooling/nargo_cli/build.rs

Resolves #8941
Changes the order of "Dead Instruction Elimination" and "Brillig Array Get and Set Optimizations" in the `--minimal-ssa` pipeline to do the DIE as the last step. 
The reason is the Brillig array index optimisations shift constant indexes by an offset, and then insert the new constants into the DFG; when that happens the DFG tries to reuse existing constants and return their IDs, and these constants can come from the global as well as local values. If it comes from a global, it can mark a global value as _used_ even when it wasn't otherwise referenced. 
The DIE pass gathers used global values, but in the minimal pipeline it came before the index offsets, so it worked with stale data. 
I don't know if this is an intended reuse, I suppose it might save some allocations the …

fix(ssa): Swap Brillig index shift and DIE in minimal pipeline

---

tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/completion/tests.rs

No issue, but something I noticed while coding.
LSP didn't offer any suggestions for `Option::`. I think it used to, maybe it stopped working at some point, likely because there wasn't a test for exactly that.
This PR adds a regression test and also fixes the issue.
Before:
After:
Check one:

fix(LSP): suggest generic type methods

---

tooling/ast_fuzzer/src/compare/interpreted.rs

Resolves #8863 
Relaxes the `Comparable` implementation for the SSA interpreter errors to consider the errors from a range check equivalent to the internal error we get when a constant does not fit into the intended type, as long as the value they mention is the same. This is because SSA passes might reorder some instructions that result in failure for the same reason, but with a different manifestation in the interpreter depending on which instruction comes first.
This is a follow up for the discussion in https://github.com/noir-lang/noir/issues/8910 without going all the way to consider every failure equivalent. That would be too aggressive at the moment, because the SSA interpreter doesn't handle prints yet (I'll do that next).
Check one:

chore(fuzz): Consider `RangeCheckFailed` equivalent to `ConstantDoesNotFitType` if the value matches

---

compiler/noirc_evaluator/src/ssa/ir/printer.rs
compiler/noirc_evaluator/src/ssa/ir/types.rs
compiler/noirc_evaluator/src/ssa/parser/into_ssa.rs
compiler/noirc_evaluator/src/ssa/parser/lexer.rs
compiler/noirc_evaluator/src/ssa/parser/tests.rs
compiler/noirc_evaluator/src/ssa/validation/mod.rs
compiler/noirc_frontend/src/hir/comptime/value.rs

Resolves #8906 
1. We now have an additional `type_check_globals` method we run during validation. This simply fetches the SSA type of the global value and determines whether it contains a `Value::Function`. If it does contain a function value it panics. 
2. The SSA printer and parser had to be updated to handle function pointers in globals. This was necessary in order to be able to use the SSA parser for the validation test.
Check one:

chore(validation): Ban function pointers in SSA globals 

---

tooling/ast_fuzzer/src/program/func.rs

Resolves one of the errors in https://github.com/noir-lang/noir/actions/runs/15748645365/job/44389551968
Fixes the AST generator to consider the mutability of the variable when it generates a target type from a source expression, and avoid taking a mutable reference over the non-mutable parts of an immutable variable, that might also contain a mutable ref. 
To reproduce the error:
```shell
NOIR_AST_FUZZER_SEED=0x89a06e3200100000 cargo test -p noir_ast_fuzzer_fuzz comptime_vs_brillig 
```
What happened was that we had a type like this: `let d = (false, &mut false);` and we were looking to produce an `&mut bool`; we know `d` can produce it as `d.1`, so we chose `d` as the producer. However, the generator that considered how to produce `&mut bool` from `(bool, &mut bool)` thought that it can …

fix(fuzz): Do not take a mutable reference over immutable vars which contain a mutable ref

---

Cargo.lock
tooling/lsp/Cargo.toml
tooling/lsp/src/lib.rs
tooling/lsp/src/requests/code_action.rs
tooling/lsp/src/requests/completion.rs
tooling/lsp/src/requests/expand.rs
tooling/lsp/src/requests/hover/from_reference.rs
tooling/lsp/src/requests/mod.rs
tooling/lsp/src/types.rs
tooling/nargo_cli/src/cli/expand_cmd.rs
tooling/nargo_expand/src/lib.rs

No issue, just something nice to have: allow invoking `nargo expand` via LSP.
Goes together with https://github.com/noir-lang/vscode-noir/pull/104
Check one:

feat: `nargo expand` for LSP

---

tooling/ast_fuzzer/src/program/func.rs

Follow up for https://github.com/noir-lang/noir/pull/9014#issuecomment-3004731151
Fixes one of the nightly errors in https://github.com/noir-lang/noir/actions/runs/15892240538/job/44816776896
Changes `gen_unary` in the AST fuzzer go avoid `UnaryOp::Minus` when we want to avoid overflows.
```shell
NOIR_AST_FUZZER_SEED=0x1f4683b600100000 cargo test -p noir_ast_fuzzer_fuzz comptime_vs_brillig_direct
```
Check one:

fix(fuzz): Avoid overflow in `gen_unary`

---

compiler/noirc_evaluator/src/ssa.rs
compiler/noirc_evaluator/src/ssa/opt/remove_unreachable_functions.rs

Resolves 
~I noticed in #9016 that we start our SSA pipeline with `remove_unreachable_functions` which I would expect to do nothing as the initial SSA codegen should not generate any unreachable functions afaik. This PR adds a check to enforce this.~
Pivoting this PR to just add an idempotency check to this SSA pass.
Check one:

chore: add idempotency check to `remove_unreachable_functions`

---

compiler/noirc_frontend/src/elaborator/mod.rs
tooling/ast_fuzzer/src/compare/comptime.rs

The current code would give a warning saying that the `InterpreterError` import was unused, because it was only used if `test_utils` was enabled. I considered changing the usage to a fully-qualified path but maybe it's better to put everything inside its own module so that imports need to be defined again and they don't clash with the non-gated module.
Check one:

chore: move a couple of test_utils functions into a module

---

.github/workflows/test-js-packages.yml

Resolves 
The filter which prevented attempting a benchmark upload on external PRs was also blocking uploads on master so these benchmarks weren't being updated.
Check one:

chore(ci): fix upload of benchmark results on master

---

compiler/noirc_driver/src/lib.rs

No issue, just something I would like post https://github.com/noir-lang/noir/pull/9001.
Sometimes I like to write small programs in Noir so that I can print their SSA and then transfer it to SSA unit tests. To do this always having SSA locations adds some extra friction, especially when indents don't perfectly line up. 
I simply added a new compiler options `no_ssa_locations` to determine whether we pass a file manager during `compile_no_check`. 
I debated expanding our `SsaLogging` enum to a struct to contain more settings, but as this print detail was already being toggled through an optional file manager I felt adding a compile option was simpler and touched less code. 
Running on `test_programs/assert_statement`:
The default `nargo compile --show-ssa`:
```
acir(inline) predicate_pure …
```

chore(debug): Toggle SSA locations when printing SSA 

---

compiler/noirc_frontend/src/hir_def/traits.rs
compiler/noirc_frontend/src/node_interner.rs

No issue. This was just the easiest part to break out from my debugging on https://github.com/noir-lang/noir/pull/9041
Provides an easy way to convert a `TraitConstraint` (or its constituent parts) to a string.
I often find myself rewriting this or a similar helper when debugging so it'd be nice to just always have it.
Check one:

chore(debug): Add trait constraint to string helper

---

compiler/noirc_evaluator/src/brillig/brillig_gen.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_black_box.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block_variables.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_fn.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_globals.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_slice_ops.rs
compiler/noirc_evaluator/src/brillig/brillig_ir.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/codegen_calls.rs
compiler/noirc_evaluator/src/brillig/mod.rs

Resolves #8126
Most of the missing documentation surrounds `brillig_gen/brillig_block.rs`
`BlockVariables` and the `gen_brillig_for` function needed some documentation as well. We can add any additional missing documentation in follow-ups. 
Check one:

chore(docs): Brillig gen

---

tooling/ast_fuzzer/src/program/func.rs

Resolves #9084 
Adds the ability to the AST fuzzer to generate assignments where the lvalue is an sub-level item in a multi-dimensional array, or a nested tuple member.
Check one:

chore(fuzz): Recursively generate lvalue for multi dimensional arrays and nested tuples

---

compiler/noirc_evaluator/src/ssa/interpreter/value.rs

Resolves 
Fixes a clippy warning.
Check one:

chore: clippy

---

compiler/noirc_frontend/src/elaborator/patterns.rs

Now that #9041 is merged there's one code path that isn't reached anymore (now this is done in a different way).
Check one:

chore: remove redundant associated constant lookup

---

compiler/noirc_evaluator/src/ssa/opt/check_u128_mul_overflow.rs
compiler/noirc_evaluator/src/ssa/opt/simple_optimization.rs

Resolves #9099 
u128 overflow checks take the current 'enable_side_effects' into account so that the check is disabled if there if side effects are disabled as well.
Check one:

fix: use enable_side_effects for u128 multiplication overflow checks

---

compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
test_programs/execution_success/regression_9119/Nargo.toml
test_programs/execution_success/regression_9119/Prover.toml
test_programs/execution_success/regression_9119/src/main.nr
tooling/nargo_cli/tests/snapshots/execution_success/regression_9119/execute__tests__expanded.snap
tooling/nargo_cli/tests/snapshots/execution_success/regression_9119/execute__tests__force_brillig_false_inliner_-9223372036854775808.snap
tooling/nargo_cli/tests/snapshots/execution_success/regression_9119/execute__tests__force_brillig_false_inliner_0.snap
tooling/nargo_cli/tests/snapshots/execution_success/regression_9119/execute__tests__force_brillig_false_inliner_9223372036854775807.snap
tooling/nargo_cli/tests/snapshots/execution_success/regression_9119/execute__tests__force_brillig_true_inliner_-9223372036854775808.snap
tooling/nargo_cli/tests/snapshots/execution_success/regression_9119/execute__tests__force_brillig_true_inliner_0.snap
tooling/nargo_cli/tests/snapshots/execution_success/regression_9119/execute__tests__force_brillig_true_inliner_9223372036854775807.snap
tooling/nargo_cli/tests/snapshots/execution_success/regression_9119/execute__tests__stdout.snap

Resolves #9119 
Handle the case when a value passed in the `jmp` arguments contains references, so those references don't get their stores removed.
This handles the case where an array with references is returned from an `if` expression in Brillig, which the compiler does not reject, unlike with ACIR.
The problematic SSA looked like this:
```rust
After Inlining (step 6):
brillig(inline) fn main f0 {
b0(v0: u1):
jmpif v0 then: b1, else: b2
b1():
v6 = allocate -> &mut u1
store u1 1 at v6
v7 = make_array [v6, Field 1] : [(&mut u1, Field); 1]	// src/main.nr:3:22
jmp b3(v7)
b2():
v2 = allocate -> &mut u1                      	// src/main.nr:3:22
store u1 1 at v2                              	// src/main.nr:3:22
v5 = make_array [v2, Field 1] : [(&mut u1, Field); 1]	// src/main.nr:5:22
jmp …
```

fix(mem2reg): Look for aliases in `jmp` arguments

---

compiler/noirc_evaluator/src/ssa/interpreter/tests/mod.rs
compiler/noirc_evaluator/src/ssa/interpreter/value.rs
tooling/ast_fuzzer/src/compare/interpreted.rs
tooling/nargo_cli/src/cli/interpret_cmd.rs

No issue, just something I noticed.
For this program:
```noir
fn main() -> pub [(Field, Field); 2] {
[(1, 2), (3, 4)]
}
```
`nargo interpret` would show this:
```
--- Interpreter result after Verifying no dynamic array indices to reference value elements (step 39):
Ok([ArrayOrSlice(ArrayValue { elements: Shared(RefCell { value: [Numeric(Field(1)), Numeric(Field(2)), Numeric(Field(3)), Numeric(Field(4))] }), rc: Shared(RefCell { value: 1 }), element_types: [Numeric(NativeField), Numeric(NativeField)], is_slice: false })])
```
which is... fine! I was about to change it by implementing a nicer `Display` for `Value` but that was already implemented, we just weren't using it. Together with improving how arrays are shown, the new output is:
```
--- Interpreter result after Verifying no dynamic …
```

chore: nicer way to show nargo interpret results

---

tooling/ast_fuzzer/fuzz/src/lib.rs

"Left program failed" would in fact indicate comptime failure, and comptime source came after AST listing in the report, which was confusing. Fixed 
Check one:

fix(fuzz): fix wrong source listing order for comptime

---

acvm-repo/blackbox_solver/src/ecdsa/secp256k1.rs
acvm-repo/blackbox_solver/src/ecdsa/secp256r1.rs

ECDSA checked compressed point representation instead of full during nargo execute.
Check one:

fix: Execution and proving discrepancy in ecdsa

---

.github/critical_libraries_status/noir-lang/noir_bigcurve/.failures.jsonl
README.md

Resolves 
Adds an expected failure to the CI for our external bigcurve test while we are working on fixing assumed trait constraints to unblock other PRs.
Check one:

chore: Add expected bigcurve failure

---

docs/docs/tooling/fuzzer.md

chore(docs): add forgotten import to RPC example

---

tooling/ssa_fuzzer/fuzzer/src/fuzz_lib/base_context.rs
tooling/ssa_fuzzer/fuzzer/src/fuzz_lib/fuzzer.rs
tooling/ssa_fuzzer/fuzzer/src/fuzz_lib/options.rs

Resolves 
1) Added ProgramContextOptions from FuzzerOptions
2) Got rid of taking return witness as NUMBER_OF_VARIABLES_INITIAL or 0 for constant mode 
Check one:

chore(ssa_fuzzer): taking witnesses from program

---

tooling/ast_fuzzer/tests/mono.rs

Resolves the test failure in https://github.com/noir-lang/noir/actions/runs/16321067297/job/46099671705?pr=9221#step:6:1587
Treat `-0` as `0` in the parsing and monomorphization roundtrip test. 
To replicate the failure:
```shell
NOIR_AST_FUZZER_SEED=0x5be5e27a00001900 cargo test -p noir_ast_fuzzer --test mono
```
My initial thought was to tweak the AST generator not to produce `-0` in the first place, but then I remembered we had a [0 != -0 bug](https://github.com/noir-lang/noir/issues/8498), so we should rather keep it, and just ignore it in the test. Actually the fix for that bug is probably what caused this test failure, but we probably shouldn't assume that it can never happen again.
Check one:

fix(fuzz): Ignore `-0` vs `0` in parsing roundtrip

---

compiler/noirc_evaluator/src/ssa/interpreter/mod.rs
tooling/nargo_toml/src/lib.rs
tooling/ssa_fuzzer/fuzzer/Cargo.toml
tooling/ssa_fuzzer/fuzzer/src/fuzz_lib/fuzz_target_lib.rs
tooling/ssa_fuzzer/fuzzer/src/fuzz_lib/options.rs
tooling/ssa_fuzzer/fuzzer/src/fuzz_target.rs
tooling/ssa_fuzzer/fuzzer/src/mutations/functions/commands_mutator.rs
tooling/ssa_fuzzer/fuzzer/src/mutations/functions/mod.rs
tooling/ssa_fuzzer/fuzzer/src/mutations/instructions/argument_mutator.rs
tooling/ssa_fuzzer/fuzzer/src/mutations/instructions/instruction_block_mutator.rs
tooling/ssa_fuzzer/fuzzer/src/mutations/instructions/instruction_mutator.rs
tooling/ssa_fuzzer/fuzzer/src/mutations/instructions/mod.rs
tooling/ssa_fuzzer/fuzzer/src/mutations/witness_mutator.rs

chore: enforce clippy in `ssa_fuzzer`

---

compiler/noirc_frontend/src/parser/parser/type_expression.rs
test_programs/compile_success_empty/as_trait_path_type_expression/Nargo.toml
test_programs/compile_success_empty/as_trait_path_type_expression/src/main.nr
tooling/nargo_cli/build.rs
tooling/nargo_cli/tests/snapshots/compile_success_empty/as_trait_path_type_expression/execute__tests__expanded.snap
tooling/nargo_cli/tests/snapshots/compile_success_empty/as_trait_path_type_expression/execute__tests__force_brillig_false_inliner_0.snap
tooling/nargo_cli/tests/snapshots/compile_success_empty/serialize_1/execute__tests__expanded.snap
tooling/nargo_cli/tests/snapshots/compile_success_empty/serialize_2/execute__tests__expanded.snap
tooling/nargo_cli/tests/snapshots/compile_success_empty/serialize_3/execute__tests__expanded.snap
tooling/nargo_fmt/src/formatter/type_expression.rs
tooling/nargo_fmt/src/formatter/types.rs

Resolves #5794
I don't know if I missed this while porting the old parser.
That said, this currently doesn't work if `AsTraitPath` is used in a function signature. That is, this doesn't compile:
```noir
use std::mem::zeroed;
trait Trait {
let N: u32;
}
impl Trait for Field {
let N: u32 = 10;
}
fn main() {}
fn foo(x: [Field; <Field as Trait>::N]) {} // No matching impl found for `Field: Trait<N = _>`
```
I think the reason is that function signatures are checked before impls are processed, not sure. In any case this PR at least makes the use case in the linked issue work.
Check one:

fix: parse AsTraitPath in type expressions

---

compiler/noirc_evaluator/src/ssa/opt/simplify_cfg.rs

Resolves 
This PR modifies the `simplify_cfg` pass so it's more likely to catch further simplifications which are uncovered. This is done by pushing the current block back onto the stack if we've successfully simplified it.
I've also added an explicit check for unreachable blocks which may exist on the stack (e.g. an orphaned block from a constant condition jmpif) so we can ensure that its successors are removed and we don't consider it any further.
Check one:

feat: add better handling for follow-on optimizations in `simplify_cfg`

---

docs/docs/noir/concepts/data_types/coercions.md
docs/versioned_docs/version-v1.0.0-beta.8/noir/concepts/data_types/coercions.md

Resolves https://github.com/noir-lang/noir/pull/9292#discussion_r2225895989
Adds a missed coercion with fmtstr to the coercions docs
Check one:

chore: Add fmtstr to coercions list

---

compiler/noirc_frontend/src/hir/mod.rs
compiler/noirc_frontend/src/hir/resolution/import.rs
compiler/noirc_frontend/src/hir/resolution/visibility.rs
compiler/noirc_frontend/src/modules.rs
tooling/lsp/src/lib.rs
tooling/lsp/src/notifications/mod.rs
tooling/lsp/src/requests/code_lens_request.rs
tooling/lsp/src/requests/mod.rs
tooling/nargo_expand/src/lib.rs

No issue, just something I noticed.
While I was recently looking at some LSP code I noticed that whenever we type-check a package we compute code lenses for the changed file, then when code lenses are requested from the client we'd try to use that cache or compute them again. This code exists since before I started making changes to LSP and now there's no need to compute code lenses when type-checking, nor there's a need to cache that information. This makes that request work more like every other LSP request handler and simplifies some code.
I checked that after this change the time it took to respond to a code lens request was still fast (for example it's less than a millisecond in `token_contract`).
I also changed a few `BTreeMap<CrateId, CrateDefMap>` to the `DefMaps` alias, and had …

chore(LSP): simplify code lens request handling

---

compiler/noirc_frontend/src/elaborator/types.rs
compiler/noirc_frontend/src/hir/comptime/interpreter.rs
compiler/noirc_frontend/src/hir_def/types.rs
compiler/noirc_frontend/src/hir_def/types/arithmetic.rs
compiler/noirc_frontend/src/hir_def/types/unification.rs
compiler/noirc_frontend/src/monomorphization/mod.rs

Resolves https://github.com/noir-lang/noir/issues/9326
Alternative to #9327
This was another issue related to type variables, their ordering, and `sort_commutative`.
The idea of `sort_commutative` is to transform an expression like `(1 + a) + 2` into `(a + 1) + 2`, that is, always place constants on the right-hand side (that way when we need to simplify the addition above we can rely on the constants always being in those places).
For types that aren't constants, they are rearranged according to the order given by `impl Ord for Type`, which, for type variables, depends on their ID.
The problem was that we ended up with an expression like `(a + b) - 1` where, depending on the entire code to compile, the same expression could end up having `a: '1, b: '2` or `a: '2, a: '1`, that is, both are …

fix: substitute bindings in type before canonicalization

---

compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/hir/type_check/errors.rs
test_programs/compile_failure/test_invalid_argument_type/Nargo.toml
test_programs/compile_failure/test_invalid_argument_type/src/main.nr
tooling/nargo_cli/tests/snapshots/compile_failure/array_oob_regression_7952/execute__tests__stderr.snap
tooling/nargo_cli/tests/snapshots/compile_failure/databus_dead_param/execute__tests__stderr.snap
tooling/nargo_cli/tests/snapshots/compile_failure/databus_in_fn_with_empty_arr/execute__tests__stderr.snap
tooling/nargo_cli/tests/snapshots/compile_failure/main_with_generics/execute__tests__stderr.snap
tooling/nargo_cli/tests/snapshots/compile_failure/test_invalid_argument_type/execute__tests__stderr.snap
tooling/nargo_cli/tests/snapshots/compile_failure/unit_in_main/execute__tests__stderr.snap

fix: prevent invalid types in test/fuzz functions

---

compiler/noirc_frontend/src/hir/type_check/errors.rs
compiler/noirc_frontend/src/hir_def/types.rs
compiler/noirc_frontend/src/tests/arithmetic_generics.rs
test_programs/compile_success_empty/comptime_u128_ops/Nargo.toml
test_programs/compile_success_empty/comptime_u128_ops/src/main.nr
tooling/nargo_cli/tests/snapshots/compile_success_empty/comptime_u128_ops/execute__tests__expanded.snap
tooling/nargo_cli/tests/snapshots/compile_success_empty/comptime_u128_ops/execute__tests__force_brillig_false_inliner_0.snap

fix: do u128 operations with u128, not i128

---

compiler/noirc_evaluator/src/ssa/interpreter/value.rs
compiler/noirc_evaluator/src/ssa/ir/mod.rs
compiler/noirc_evaluator/src/ssa/ir/printer.rs

No issue.
While debugging https://github.com/noir-lang/noir/issues/9270 with `nargo interpret` it was hard to remember which values were correct or incorrect by looking at numbers. With this PR byte arrays that are likely strings will be shown as such, like we do everywhere else when it comes to SSA. For example:
```
--- Interpreter result after Initial SSA:
Ok(rc3 [rc1 [rc2 b"EN"], rc2 [rc2 b"EN"]])
```
Check one:

chore: try printing byte arrays as strings in the SSA interpreter

---

tooling/nargo/src/ops/compile.rs
tooling/nargo/src/ops/mod.rs

No issue.
I noticed that this function is unused. Can it be removed? I don't know if it was intended to be used as an API though.
Check one:

chore: remove unused `compile_workspace`

---

compiler/noirc_frontend/src/elaborator/patterns.rs

Follow up to #9354
Yesterday I didn't feel satisfied with the comment I wrote. Apparently my brain kept thinking about this and now I understand a bit more how things work, so I decided to write it so things are clearer.
Check one:

chore: enhance trait constraint comment

---

docs/docs/noir/concepts/comptime.md

Resolves https://github.com/noir-lang/noir/issues/9197
Check one:

chore(docs): Add example for `$crate` in docs

---

compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
compiler/noirc_evaluator/src/ssa/opt/mem2reg/block.rs

No issue, just part of the mem2reg audit.
While browsing the code I noticed this case where aliases is empty, in which case we have to invalidate all references. I wondered what piece of code could produce a reference for which we don't have at least one alias (itself) so I added a debug print in that case. The debug print was hit, but then I checked if, when it's hit, there were references and last stores to invalidate at all. At least when running all tests I couldn't find such case so this PR turns that into an assertion.
Well, when creating this PR it turns out the fuzzer found some code that triggered that case. I reduced that code, got an SSA for it and added a test for that scenario, trying to explain the reasoning behind it.
Check one:

chore: add a mem2reg test for when all references need to be invalidated

---

compiler/noirc_evaluator/src/acir/mod.rs
compiler/noirc_evaluator/src/errors.rs

Resolves 
This PR handles a couple of TODO comments now that elaborator is default + #1438 is resolved.
Check one:

chore: address TODO comments

---

tooling/nargo_cli/src/cli/info_cmd.rs

Resolves #9380 
We now specify that we expect zero comptime printing when requesting a machine readable output.
Check one:

fix: disable comptime printing when requesting json output

---

EXTERNAL_NOIR_LIBRARIES.yml
compiler/noirc_evaluator/src/ssa/opt/inlining.rs
compiler/noirc_evaluator/src/ssa/opt/inlining/inline_info.rs

Part of the internal audit
These are additional unit tests I built while working on the audit for the inlining pass.
Check one:

chore(inlining): Unit tests for global values and conditional inlining

---

compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs

Part of the mem2reg internal audit.
This PR adds a few unit tests for mem2reg code paths that weren't executed by the existing tests.
Check one:

chore: add some mem2reg unit tests

---

docs/docs/noir/standard_library/cryptographic_primitives/ecdsa_sig_verification.mdx
docs/versioned_docs/version-v1.0.0-beta.10/noir/standard_library/cryptographic_primitives/ecdsa_sig_verification.mdx
noir_stdlib/src/ecdsa_secp256k1.nr
noir_stdlib/src/ecdsa_secp256r1.nr

Resolves 
This is just fundamentally broken as it cannot handle dynamic length slices properly so we should remove these.
Check one:

feat: mark slice variants of ecdsa verification as deprecated

---

compiler/noirc_evaluator/src/ssa/opt/as_slice_length.rs
compiler/noirc_evaluator/src/ssa/opt/brillig_array_get_and_set.rs
compiler/noirc_evaluator/src/ssa/opt/check_u128_mul_overflow.rs
compiler/noirc_evaluator/src/ssa/opt/checked_to_unchecked.rs
compiler/noirc_evaluator/src/ssa/opt/expand_signed_checks.rs
compiler/noirc_evaluator/src/ssa/opt/make_constrain_not_equal.rs
compiler/noirc_evaluator/src/ssa/opt/remove_bit_shifts.rs
compiler/noirc_evaluator/src/ssa/opt/remove_enable_side_effects.rs
compiler/noirc_evaluator/src/ssa/opt/remove_if_else.rs
compiler/noirc_evaluator/src/ssa/opt/remove_truncate_after_range_check.rs
compiler/noirc_evaluator/src/ssa/opt/remove_unreachable_instructions.rs
compiler/noirc_evaluator/src/ssa/opt/simple_optimization.rs

Resolves panics in https://github.com/noir-lang/noir/pull/9373 where we have unknown values when we reach inlining
I switched to using the reverse post order (RPO) during the `simple_optimization` abstraction. This was necessary as during `remove_bit_shifts` we were replace old results with the new results but these were not being seen by the canonical block ordering. This concern was raised on the initial PR https://github.com/noir-lang/noir/pull/8102#discussion_r2047325251. It looks like we finally found a situation which breaks the usage of `reachable_blocks` over the actual canonical block ordering. 
I decided it would be best to just be safe and use the RPO during `simple_optimization`. If we are replacing values, we want to make sure that the replacement values are propagated to all …

fix(ssa): Use reverse post order when traversing blocks in simple_optimization

---

compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
compiler/noirc_evaluator/src/ssa/opt/mem2reg/block.rs
test_programs/execution_success/regression_9538/Nargo.toml
test_programs/execution_success/regression_9538/Prover.toml
test_programs/execution_success/regression_9538/src/main.nr
tooling/debugger/ignored-tests.txt
tooling/nargo_cli/tests/snapshots/execution_success/regression_9538/execute__tests__expanded.snap
tooling/nargo_cli/tests/snapshots/execution_success/regression_9538/execute__tests__force_brillig_false_inliner_-9223372036854775808.snap
tooling/nargo_cli/tests/snapshots/execution_success/regression_9538/execute__tests__force_brillig_false_inliner_0.snap
tooling/nargo_cli/tests/snapshots/execution_success/regression_9538/execute__tests__force_brillig_false_inliner_9223372036854775807.snap
tooling/nargo_cli/tests/snapshots/execution_success/regression_9538/execute__tests__force_brillig_true_inliner_-9223372036854775808.snap
tooling/nargo_cli/tests/snapshots/execution_success/regression_9538/execute__tests__force_brillig_true_inliner_0.snap
tooling/nargo_cli/tests/snapshots/execution_success/regression_9538/execute__tests__force_brillig_true_inliner_9223372036854775807.snap
tooling/nargo_cli/tests/snapshots/execution_success/regression_9538/execute__tests__stdout.snap

Resolves #9538 
Fixes `mem2reg` to add the aliases of the `address` in a `Load` instruction to the `last_loads` of the `PerFunctionContext`. 
In https://github.com/noir-lang/noir/pull/9305 I added handling of `IfElse` instructions to `mem2reg` where if the result of the `IfElse` was a reference, then the `then_value` and the `else_value` were considered to be aliases of that result address. For example consider this SSA in the new integration test:
```rust
After Simplifying (4) (step 31):
brillig(inline) predicate_pure fn main f0 {
b0(v0: u1, v1: [u8; 3], v2: [u8; 3]):
v4 = allocate -> &mut [u8; 3]
store v1 at v4
v5 = allocate -> &mut [u8; 3]
store v2 at v5
v6 = not v0
jmpif v0 then: b1, else: b2
b1():
v9 = not v0
v10 = if v0 then v5 else (if v9) v4
v11 = load v10 -> [u8; 3] …
```

fix(mem2reg): Consider aliases of a loaded address to be loaded from as well

---

compiler/noirc_evaluator/src/ssa/ir/dfg/simplify/binary.rs

Resolves #9595
Resolves https://github.com/noir-lang/noir/pull/9587#issuecomment-3210560032
Even if a bit shift of zero will always result in zero we want to maintain consistency that bit shifting by an amount larger than the type's size will result in an error.
Remove the lhs_is_zero simplification from Shl/Shr
Check one:

fix(ssa): Do not simplify on lhs being zero for shifts

---

compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
compiler/noirc_evaluator/src/ssa/opt/mem2reg/block.rs

Resolves one refactor in #9393
Check one:

chore: simplify Expression in mem2reg

---

compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
compiler/noirc_evaluator/src/ssa/opt/mem2reg/alias_set.rs
compiler/noirc_evaluator/src/ssa/opt/mem2reg/block.rs

Part of #9393
This PR tries to make the code more meaningful by removing some duplicated code and trying to avoid leaking some implementation details (although mem2reg is not very bug and it mostly knowns how everything is actually implemented). But the goal is to make the code easier to read, with less `if`s.
Then I also found out that `is_store_alias_used` could be slightly refactored as well. Now it doesn't call the `any` method on `AliasSet`, which had checks like `value == Some(true)`, and I also think it might be slightly faster as we need to traverse the alias set just once.
Now `AliasSet` has an `iter()` method. I wanted to have `impl IntoIterator for &AliasSet` so it can be iterated without having to call `.iter()` but I couldn't find a way to do it without having `IntoIterator` …

chore: some mem2reg refactors regarding expressions and aliases

---

compiler/noirc_evaluator/src/ssa/opt/checked_to_unchecked.rs

Resolves #9519
I added some math explanations mainly to avoid having to do these mentally when going over the code.
Check one:

chore: greenlight `checked_to_unchecked` for audits

---

compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs

Part of #9393
Just a small refactor to avoid computing PostOrder redundantly.
Check one:

chore(mem2reg): avoid redundant PostOrder computation

---

compiler/noirc_evaluator/src/ssa/opt/rc.rs

chore: only run remove_paired_rc in brillig functions

---

compiler/noirc_evaluator/src/acir/mod.rs
compiler/noirc_evaluator/src/acir/ssa.rs
compiler/noirc_evaluator/src/brillig/mod.rs
compiler/noirc_evaluator/src/ssa/opt/inlining.rs
compiler/noirc_evaluator/src/ssa/ssa_gen/program.rs

Resolves #9408 
Resolves #9409 
Before globals existed in SSA all globals were inlined in the frontend. Globals were then added, but treated as a Brillig exclusive concept. The inlining of globals was then moved to inlining. As per #9408 and #9409 this can cause some confusion in the IR output. I decided to move to that we keep globals throughout our SSA IR for any runtime. It is then up to the code gen of that runtime to handle globals lowering. ACIR then gets the same compilation benefits that Brillig does with globals (e.g., a more succinct IR in the case of large global arrays, reduced duplication). This compilation benefit can be seen in the `rollup-block-root` [benchmarks](https://github.com/noir-lang/noir/pull/9626#pullrequestreview-3152390126).
Check one:

fix(inlining): Do not inline globals and lower them during ACIR gen

---

compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs

Something pending from https://github.com/noir-lang/noir/pull/9628
I found an SSA code that breaks with the incorrect PR.
I still didn't have time to investigate why that regression happens in that PR. Tomorrow I'll try to bring back #9613 while trying to fix the bug as I think the logic there is mostly fine (and if I manage to do so I'll check that it doesn't break Aztec-Packages).
Check one:

chore: add a regression test for #9613

---

compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
test_programs/compile_success_empty/nested_ref_param_regression_9500/Nargo.toml
test_programs/compile_success_empty/nested_ref_param_regression_9500/src/main.nr
tooling/nargo_cli/tests/snapshots/compile_success_empty/nested_ref_param_regression_9500/execute__tests__expanded.snap
tooling/nargo_cli/tests/snapshots/compile_success_empty/nested_ref_param_regression_9500/execute__tests__force_brillig_false_inliner_0.snap

Resolves #9500 
As per the comment on `add_aliases_for_reference_parameters` the method attempts to do the following:
```
/// Go through each parameter and register that all reference parameters of the same type are
/// possibly aliased to each other. If there are parameters with nested references (arrays of
/// references or references containing other references) we give up and assume all parameter
/// references are `AliasSet::unknown()`.
```
However, we never actually do what the comment says in the method. This PR fixes that and appropriately mark all parameters as unknown in the case of a nested reference.
Check one:

fix(mem2reg): Assume all function reference parameters have an unknown alias set with nested references

---

tooling/nargo_fmt/src/chunks.rs
tooling/nargo_fmt/src/formatter/expression.rs

Resolves #9556
A quick fix for the issue. Ideally the formatting could be better but at least we don't end up with a wrong indentation later on...
(but this fix is good on its own, regardless of it not leading to an ideal code formatting)
Check one:

fix(formatter): don't revert indentation increase after popping it

---

compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs
compiler/noirc_evaluator/src/ssa/opt/loop_invariant/simplify.rs

`LoopContext` had a bunch of `current_block_*` fields which had to be reset for each block we iterated over in `hoist_loop_invariants`, and assigned new values in various methods that also mutated other fields on `LoopContext`. Some were unrelated, like `is_control_dependent_post_pre_header` also set the block purity, seemingly just because `all_predecessors` was available there. This made it hard to find where various flags on `LoopContext` came from.
* Breaks out the `current_block_*` fields from `LoopContext` into a `BlockContext` and introduces an `LoopInvariantContext::init_block_context` method to create it, so we cannot forget to set the values, and there is no risk of reusing something from the previous iteration. 
* Changes all query methods for the `BlockContext` initialisation …

chore(licm): Break things up further in LICM

---

compiler/noirc_evaluator/src/ssa/ir/dom.rs
compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs

`compute_dominance_frontiers` contained a confusing `while` condition.
Changes `compute_dominance_frontiers` to compute `immediate_dominator` once and use `loop`, instead of computing it repeatedly with the same arguments in a `while` condition. Added some extra comments and examples as well.
On an earlier bug fix I found this `while` suspicious: I wasn't sure if we should have been calling it with the `runner` instead of the `block_id`, since the latter doesn't change during the iteration.
For the record, this is the pseudo code from the paper; it might be where the `while` was coming from.
Check one:

chore: Refactor `compute_dominance_frontiers`

---

compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_fn.rs
compiler/noirc_evaluator/src/brillig/brillig_gen/variable_liveness.rs
compiler/noirc_evaluator/src/ssa/ir/post_order.rs
compiler/noirc_evaluator/src/ssa/opt/normalize_value_ids.rs
compiler/noirc_evaluator/src/ssa/opt/simple_optimization.rs

Maxim said we should move away from `reachable_blocks` towards using reverse-post-order, which is used in multiple places already, but always in an ad-hoc fashion.
Adds a `PostOrder::into_vec_reverse` method to encapsulate reversing the post-order vector to get the forward order. Makes it easier to discover this option and reduces the need for copy pasting.
Check one:

chore: Add `PostOrder::into_vec_reverse`

---

.config/nextest.toml

Followup for https://github.com/noir-lang/noir/pull/9717#issuecomment-3249172898
Changes the default `nextest` profile to exclude the `ram_blowup_test`. 
It will be tested on [ci-master](https://github.com/noir-lang/noir/blob/910cd9349e0b9382c1512935bc3e1d791891bd21/.github/workflows/test-rust-workspace.yml#L86)
Check one:

chore(test): Filter `ram_blowup_regression` by default on local testing

---

compiler/noirc_frontend/src/tests.rs
compiler/noirc_frontend/src/tests/aliases.rs
compiler/noirc_frontend/src/tests/enums.rs
compiler/noirc_frontend/src/tests/metaprogramming.rs
compiler/noirc_frontend/src/tests/traits.rs
compiler/noirc_frontend/src/tests/unused_items.rs
compiler/noirc_frontend/src/tests/visibility.rs
justfile

No issue.
Now that frontend tests don't generate a test program they don't need to have a main function.
This PR also fixes a small issue in the justfile.
Check one:

chore: remove empty main from frontend tests

---

compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs
compiler/noirc_evaluator/src/ssa/opt/loop_invariant/simplify.rs

Increase test coverage.
Implement unit tests for code identified in https://github.com/noir-lang/noir/pull/9718 
Fixes the logic for `ConstrainNotEqual` which had min/max swapped.
Check one:

chore(licm): More unit tests and a fix

---

compiler/noirc_evaluator/src/ssa/ir/value.rs
compiler/noirc_evaluator/src/ssa/opt/constant_folding/interpret.rs
compiler/noirc_evaluator/src/ssa/opt/constant_folding/mod.rs
compiler/noirc_evaluator/src/ssa/opt/constant_folding/result_cache.rs
compiler/noirc_evaluator/src/ssa/opt/constant_folding/simplification_cache.rs

Resolves 
This PR breaks up the constant folding pass into a couple of submodules so that we can place the different caches and their associated logic into separate files to build a proper interface between them and the rest of the pass.
Check one:

chore: encapsulate constant folding logic better

---

compiler/noirc_evaluator/src/ssa/interpreter/mod.rs

Resolves #9830
This will unblock adding the tests in #9789.
When fetching arrays in ACIR we treat them as entirely fresh objects. However, in the interpreter we implement arrays use shared mutable references. Thus, when we returned a nested array and then marked it mutable in the array set optimization we were in fact mutating the parent array we fetched from as well. This breaks the semantics of arrays in ACIR.
Looking at the SSA after the array set optimization:
```
acir(inline) predicate_pure fn main f0 {
b0(v0: u1, v1: u32):
v4 = make_array [u1 1, u1 0, u1 1] : [u1; 3]
v5 = make_array [v4] : [[u1; 3]; 1]
v7 = add v1, u32 1
v8 = array_get v5, index v1 -> [u1; 3]
v9 = array_set mut v8, index u32 1, value u1 1
v10 = array_get v9, index v7 -> u1
enable_side_effects v0
v11 = add v1, u32 1 …
```

fix(interpreter): Return fresh nested array on array get in ACIR

---

compiler/noirc_evaluator/src/acir/acir_context/mod.rs
compiler/noirc_evaluator/src/acir/tests/mod.rs

Resolves #9847
check for overflow during signed division
Check one:

fix: check for signed division overflow

---

.github/benchmark_projects.yml
EXTERNAL_NOIR_LIBRARIES.yml
compiler/noirc_frontend/src/elaborator/mod.rs
compiler/noirc_frontend/src/tests.rs
test_programs/compile_failure/wildcards_in_wrong_places/src/main.nr
tooling/nargo_cli/tests/snapshots/compile_failure/broken_impl/execute__tests__stderr.snap
tooling/nargo_cli/tests/snapshots/compile_failure/wildcards_in_wrong_places/execute__tests__stderr.snap

fix: disallow `_` in where clauses, and disallow unused trait impl generics

---

compiler/noirc_evaluator/src/acir/acir_context/black_box.rs
compiler/noirc_evaluator/src/acir/acir_context/brillig_call.rs
compiler/noirc_evaluator/src/acir/acir_context/mod.rs
compiler/noirc_evaluator/src/acir/mod.rs

Working towards green-lighting ACIR gen.
Quite some time ago we introduced the ability to execute the Brillig VM if a call was made with all constant inputs. This was a bit of a workaround as we did not run any SSA optimizations over Brillig and did not yet constant fold Brillig entry points.    
I removed Brillig execution logic from the `brillig_call` module of ACIR gen. This should simplify the logic and lets us keep a better separation of concerns for each pass. 
With regards to stdlib functions, we already check for constant inputs before we lay down an Inverse or Quotient and perform the appropriate computation. This will be necessary for any new Brillig stdlib functions.
We also get the nice side benefit of removing the `B: BlackBoxFunctionSolver<F>` generic on the `AcirContext`. …

chore(acir_gen): Remove Brillig execution with constant arguments 

---

tooling/ast_fuzzer/README.md
tooling/ast_fuzzer/fuzz/src/lib.rs
tooling/ast_fuzzer/fuzz/src/targets/acir_vs_brillig.rs
tooling/ast_fuzzer/fuzz/src/targets/comptime_vs_brillig_direct.rs
tooling/ast_fuzzer/fuzz/src/targets/comptime_vs_brillig_nargo.rs
tooling/ast_fuzzer/fuzz/src/targets/min_vs_full.rs
tooling/ast_fuzzer/fuzz/src/targets/mod.rs
tooling/ast_fuzzer/fuzz/src/targets/orig_vs_morph.rs
tooling/ast_fuzzer/src/compare/compiled.rs
tooling/ast_fuzzer/src/compare/comptime.rs
tooling/ast_fuzzer/src/compare/interpreted.rs
tooling/ast_fuzzer/src/compare/mod.rs

Follow up for the issue @vezenovm encountered in https://github.com/noir-lang/noir/pull/9882#issuecomment-3300370867
* Changes the way we can tell the AST fuzzer to log the generated artifacts to be triggered by the `RUST_LOG=debug` env var, which now causes everything to be printed as logs from the `arb` methods. 
* Removes the `NOIR_AST_FUZZER_SHOW_AST` options, which was used to print the AST before trying to convert it into SSA, but if `NOIR_AST_FUZZER_SEED` is present, it will automatically print the AST _iff_ there is an error during compilation. 
* Renames `create_ssa_or_die` to `compile_into_circuit_or_die`, because some passes actually create `Ssa`, while the `SsaProgramArtifact` doesn't actually have the `Ssa` in it, which is a bit confusing.
* Omits the Brillig bytecode from …

chore(fuzz): Refactor logging in the AST fuzzer

---

compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs
compiler/noirc_evaluator/src/ssa/opt/mem2reg.rs
compiler/noirc_evaluator/src/ssa/opt/preprocess_fns.rs
compiler/noirc_evaluator/src/ssa/validation/mod.rs
compiler/noirc_frontend/src/monomorphization/debug.rs

chore: validate SSA call arguments

---

acvm-repo/acir/src/circuit/mod.rs
acvm-repo/brillig/src/black_box.rs
acvm-repo/brillig/src/opcodes.rs
compiler/noirc_evaluator/src/acir/tests/brillig_call.rs
compiler/noirc_evaluator/src/acir/tests/mod.rs

No issue, I just found Brillig output hard to understand, and Brillig is the only language we have that doesn't have a "proper" language.
I'm mainly opening this PR for feedback as it's unfinished (blackbox ops are not implemented yet) and I'm unsure about how I'm currently displaying some things.
For the empty Noir program
```noir
unconstrained fn main() {}
```
we now get this when using `--print-acir`:
```
Compiled ACIR for main (non-transformed):
func 0
current witness: w0
private parameters: []
public parameters: []
return values: []
BRILLIG CALL func 0: inputs: [], outputs: []
unconstrained func 0
0: @2 = const u32 1
1: @1 = const u32 32836
2: @0 = const u32 3
3: sp[1] = const u32 0
4: sp[2] = const u32 0
5: @32836 = calldata copy [sp[2]; sp[1]]
6: call 11
7: call 12
8: sp[1] = const …
```

chore: implement Display for brillig

---

tooling/nargo_fmt/src/formatter/expression.rs

fix(fmt): missing skip whitespace when formatting match

---

compiler/noirc_evaluator/src/ssa/opt/loop_invariant.rs

Resolves https://github.com/noir-lang/noir/pull/9807#discussion_r2342125956
Adds `CanBeHoistedResult::WithRefCount` from https://github.com/noir-lang/noir/pull/9807 regardless of whether we adopt anything else from that PR.
Changes `LoopInvariantContext::can_hoist_invariant` to return an extra `bool` to signal whether `IncrementRc` needs to be inserted, so we don't need to keep in sync the decision when `WithRefCount` is returned and the actual insertion of the RC, with a comment that we will do so. I went back and forth between returning `CanBeHoistedResult` from `can_hoist_invariant` and matching it in `hoist_loop_invariants`, but in the past I found it useful to debug the various decision points in `can_hoist_invariant`, and thought it was better to keep these close together, rather …

chore(licm): Add `CanBeHoistedResult::WithRefCount`

---

compiler/noirc_evaluator/src/ssa/opt/remove_enable_side_effects.rs
compiler/noirc_evaluator/src/ssa/validation/mod.rs

Resolves #9931 
Add SSA validation for the `array` type in `ArrayGet` and `ArraySet`.
Fix the SSA in unit tests in `remove_enable_side_effects`.
Check one:

chore(ssa): Validate array operands

---

compiler/noirc_evaluator/src/ssa/opt/constant_folding/mod.rs

No issue, just part of the audit.
Just some things I noticed, doesn't change the pass's functionality. Each commit is self-contained.
Check one:

chore: minor constant_folding refactors

---

Cargo.lock
tooling/ssa_executor/Cargo.toml
tooling/ssa_executor/examples/compilation.rs
tooling/ssa_executor/src/compiler.rs
tooling/ssa_executor/src/lib.rs

chore(ssa_executor): add compilation example 

---

.github/critical_libraries_status/noir-lang/noir_base64/.failures.jsonl
.github/workflows/test-rust-workspace-arm64.yml
.github/workflows/test-rust-workspace-msrv.yml
.github/workflows/test-rust-workspace.yml
EXTERNAL_NOIR_LIBRARIES.yml

chore(ci): free up space on github runner

---

compiler/noirc_evaluator/src/ssa/mod.rs

Resolves failures in https://github.com/AztecProtocol/aztec-packages/pull/17203
I was able to get the `state_vars::private_mutable::test::initialize_and_get_pending` test passing by disabling this run.
We will need to create a reproduction separately but this provides a quick fix to get Noir synced in aztec-packages. 
Here is a picture of the commit history:
Run `noirup -C b2452725d8a6778bd9e9617c7e80d1c502ec397a` (the commit at which PR #9744 was merged). The aztec-nr tests in https://github.com/AztecProtocol/aztec-packages/pull/17203 will pass at that commit.
Building Noir on master will cause the test to fail. However, once we comment out that mem2reg test we will start to pass again. So it looks like some other changes in mem2reg since that PR have now have started causing breakages. …

fix: Disable early mem2reg

---

tooling/ast_fuzzer/minimizer/README.md
tooling/ast_fuzzer/minimizer/scripts/docker-entry.sh
tooling/ast_fuzzer/minimizer/scripts/minimize.sh

No issue but something I needed to minimize the program from this min_vs_full fuzzer failure https://github.com/noir-lang/noir/actions/runs/17981940230/job/51151135676?pr=9985. 
When minimizing programs with `cvise` you can now pass compilation flags to nargo. This is most useful if the fuzz program uses experimental features (which need `-Zenums`) or only fails when run with `--minimal-ssa`. 
Check one:

chore(ast_fuzzer): Allow passing compilation options to cvise tool

---

examples/browser/package.json
examples/browser/test.sh
package.json
yarn.lock

chore(ci): fix docs breaking JS releases

---

.github/benchmark_projects.yml
.github/workflows/reports.yml
EXTERNAL_NOIR_LIBRARIES.yml

Resolves 
This PR updates the timeouts appropriately for some of the heavier benchmark projects.
I've also had to disable the rolluplib tests.
Check one:

chore(ci): fix external checks

---

compiler/noirc_frontend/src/ast/expression.rs
compiler/noirc_frontend/src/parser/parser/expression.rs

Resolves #9911
The code in the issue should have produced an error but didn't.
Check one:

fix(parser): enforce left brace after match expression

---

tooling/ssa_fuzzer/fuzzer/src/acir_vs_brillig.rs
tooling/ssa_fuzzer/fuzzer/src/brillig.rs
tooling/ssa_fuzzer/fuzzer/src/fuzz_lib/block_context.rs
tooling/ssa_fuzzer/fuzzer/src/fuzz_lib/fuzzer.rs
tooling/ssa_fuzzer/src/typed_value.rs

New type system introduced in https://github.com/noir-lang/noir/pull/9651 broke array ops
Resolves 
Check one:

chore(ssa_fuzzer): fix array get/set 

---

acvm-repo/acvm/src/compiler/optimizers/general.rs
acvm-repo/acvm/src/compiler/optimizers/merge_expressions.rs
acvm-repo/acvm/src/compiler/optimizers/unused_memory.rs
acvm-repo/acvm/src/pwg/mod.rs

No issue, just part of auditing.
Note: I don't want to run `GeneralOptimizer` on `merge_expressions`. However, for the test I wrote it fails because it ends up generating:
```
ASSERT w2 = -4*w1 + 2*w0 + 4*w1 + 14
```
and that can't be solved (though I think it should?)
That said, I don't know how merge expressions is working right now if in this example it ends up adding and subtracting the same expression, which ends up not being solvable.
Check one:

chore: use new ACIR syntax in docs, and some tests

---

.github/workflows/rustdoc.yml

chore(ci): fix permissions about publishing rustdoc

---

acvm-repo/acvm/src/pwg/memory_op.rs
acvm-repo/acvm/src/pwg/mod.rs

Resolves #10078
Memory operations don't have predicates applied to them so we can remove this code entirely.
Check one:

chore: remove unused predicate from mem-op solver

---

compiler/integration-tests/package.json
examples/browser/package.json
scripts/install_bb.sh
yarn.lock

chore: bump version of bb used in tests

---

docs/docs/noir/concepts/comptime.md
docs/docs/noir/concepts/data_types/arrays.md
docs/docs/noir/concepts/data_types/fields.md
docs/docs/noir/concepts/data_types/index.md
docs/docs/noir/concepts/data_types/slices.mdx
docs/docs/noir/concepts/ops.md
docs/docs/noir/concepts/traits.md
docs/docs/noir/modules_packages_crates/dependencies.md
docs/docs/noir/standard_library/containers/vec.mdx
docs/docs/noir/standard_library/logging.md
docs/docs/tooling/fuzzer.md
docs/docs/tooling/tests.md
tooling/nargo_cli/src/cli/noir_template_files/binary.nr

Resolves 
We want to discourage people defaulting to the `Field` type so this is a nudge to use integer types instead.
Check one:

chore: use `u64` over `Field` in template program

---

compiler/noirc_evaluator/src/acir/acir_context/mod.rs

No issue, just something I noticed and wanted to try out.
Check one:

chore(ACIR): inline `maybe_eq_predicate`

---

acvm-repo/acvm/src/compiler/simulator.rs

Resolves #10102 
Removes an unnecessary allocation in `expr_wit`
Check one:

chore: Remove unnecessary allocation in `expr_with`

---

compiler/noirc_evaluator/src/acir/arrays.rs
compiler/noirc_evaluator/src/ssa/ir/types.rs

Resolves #10085
This is just trying this out. But the explanation to this is: I found it odd that `compute_offset` would sometimes return an offset, but sometimes not. Why not? In which cases we wouldn't be able to compute an offset? An what happens in those cases? (maybe we are lacking tests?)
The problem was that `compute_offset` searched a type, in the array item types, that was equal to the type of the instruction result. This works fine for `ArrayGet`, but for `ArraySet` the type of the result is always the same array and it will **never** match the type of an item type. For `ArraySet` we must search the type of the store value. Then we can always compute an offset.
Now, I don't know if computing an offset is always desirable, and there's a chance that this will make performance …

chore(ACIRgen): always compute array offset
