crates/nargo/src/cli/prove_cmd.rs
crates/nargo/src/cli/verify_cmd.rs
crates/noirc_abi/src/input_parser/mod.rs

This adds a helpful error if the user does not enter the right parameter types.
In another PR, write_stderr will be removed, as it uses exit() which prevents drops from happening. Furthermore, the red text is not appealing to the eyes.

Check consistency between Toml and Abi

---

crates/nargo/examples/simple_shield/Nargo.toml
crates/nargo/examples/simple_shield/Prover.toml
crates/nargo/examples/simple_shield/Verifier.toml
crates/nargo/examples/simple_shield/src/main.nr

Example shows how one may create a circuit for a 1input 1output transaction, where:
- Note denominations are the same
- Notes are stored in a merkle tree
- Instead of a signature, ownership of a note is proven by computing the corresponding public key from a private for that note.

Add 1in-1out example

---

crates/noirc_frontend/src/ast/mod.rs
crates/noirc_frontend/src/hir/type_check/expr.rs

- Loosens the restrictions on the arguments when the parameter is a Field. Eg. a u8 can be passed to a function that requests a Field. This should allow for less casting 
- Moves more of the type checking code to the ast module section as methods on Type

Loosen type checking rules when the parameter type is Field

---

Cargo.lock
crates/acvm/src/backends/csat_3_plonk_aztec/pwg/gadget_call.rs
crates/acvm/src/backends/csat_3_plonk_aztec/pwg/merkle.rs
crates/acvm/src/pwg/hash/mod.rs
crates/aztec_backend/src/barretenberg_rs/blake2s.rs
crates/aztec_backend/src/barretenberg_rs/pedersen.rs
crates/aztec_backend/src/barretenberg_rs/scalar_mul.rs
crates/noir_field/Cargo.toml
crates/noir_field/src/lib.rs

This further removes arkwork specific code in the implementation, and also removes from_bytes method which was also doing a reduction.
closes #64

Further simplify field element implementation

---

crates/noirc_evaluator/src/object/integer.rs

When multiplying integers, we result is constrained to be the same number of bits.
closes #80

Change semantics of multiplying Integers

---

.github/workflows/rust.yml

These tools updated a bit too quickly on nightly and required developers to update often to keep up. This should hopefully lessen that need a bit.

Change clippy and fmt to use stable toolchains

---

crates/noirc_evaluator/src/environment.rs
crates/noirc_evaluator/src/lib.rs
crates/noirc_frontend/src/ast/expression.rs
crates/noirc_frontend/src/ast/mod.rs
crates/noirc_frontend/src/ast/statement.rs
crates/noirc_frontend/src/hir/def_map/mod.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/scope/mod.rs
crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir/type_check/mod.rs
crates/noirc_frontend/src/hir/type_check/stmt.rs
crates/noirc_frontend/src/hir_def/expr.rs
crates/noirc_frontend/src/hir_def/function.rs
crates/noirc_frontend/src/lib.rs
crates/noirc_frontend/src/parser/errors.rs
crates/noirc_frontend/src/parser/parser.rs
crates/noirc_frontend/src/util/mod.rs

This PR is mostly minor cleanup in the frontend, though also implements type checking and name resolution for if expressions, and type checking for predicate expressions. Predicate expressions also seem not to have been used before, so I merged them with the `InfixExpression` node. 
Part of the cleanup is the addition of a `vecmap` utility function for `xs.into_iter().map(...).collect::<Vec<_>>()` which was a common pattern throughout the codebase. This function would be useful for more than just the frontend, though I saw no better package to put it in, so for now it lives in `noirc_frontend/src/util/mod.rs`. If we ever want to expand these utility functions it may be helpful to create a new package to isolate them in the future.

Minor cleanup

---

Cargo.lock
crates/noirc_errors/Cargo.toml
crates/noirc_errors/src/position.rs
crates/noirc_frontend/Cargo.toml
crates/noirc_frontend/src/ast/statement.rs
crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir/type_check/stmt.rs
crates/noirc_frontend/src/lexer/lexer.rs
crates/noirc_frontend/src/parser/errors.rs
crates/noirc_frontend/src/parser/mod.rs
crates/noirc_frontend/src/parser/parser.rs

Currently, the parser expects semicolons separating each statement in a block, with an optional final semicolon at the end of a block. This is incorrect if we want to strictly follow rust's grammar however. The proper rules should be:
- Semicolons are always required after non-expression statements - even at the end of a block.
- Semicolons are optional for `if`, `for`, and `block` expressions.
- Semicolons are optional for other expressions only at the end of a block. They are required otherwise.
This PR updates chumsky so that we can use the `validate` parser to map our input from `A -> B` rather than just `A -> A`, while also emitting non-fatal errors along the way. This is used to emit semicolon errors and recover from them.
Edit: This PR now also adds the check we discussed for …

Update semicolon handling to be more like rust's

---

crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/parser/parser.rs

I noticed we assumed in the type checker code that arrays always had at least one element. I added a better error message for this case and refactored some so we can continue type checking without hitting the assert.

Array code cleanup

---

crates/noirc_evaluator/src/ssa/acir_gen.rs
crates/noirc_evaluator/src/ssa/integer.rs

- correctly compute coeficient that prevent underflow
- use max value for substraction when handling overflow

Fix integer substraction:

---

Cargo.lock
crates/noirc_frontend/src/ast/expression.rs
crates/noirc_frontend/src/ast/mod.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir_def/expr.rs
crates/noirc_frontend/src/parser/parser.rs

Turns out this field was never actually used. `Type::Unknown` has also been removed since it was only used for this unused field.

Remove ArrayLiteral r#type field in Ast and Hir

---

crates/noirc_driver/tests/pass/basic_import.nr
crates/noirc_evaluator/src/lib.rs
crates/noirc_evaluator/src/ssa/code_gen.rs
crates/noirc_frontend/src/ast/mod.rs
crates/noirc_frontend/src/ast/statement.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/type_check/mod.rs
crates/noirc_frontend/src/hir/type_check/stmt.rs
crates/noirc_frontend/src/hir_def/stmt.rs
crates/noirc_frontend/src/lexer/lexer.rs
crates/noirc_frontend/src/lexer/token.rs
crates/noirc_frontend/src/parser/mod.rs
crates/noirc_frontend/src/parser/parser.rs
examples/10/src/main.nr
examples/13/src/main.nr
examples/2/src/main.nr
examples/3/src/main.nr
examples/4/src/main.nr
examples/assign_ex/src/main.nr
examples/pred_eq/src/main.nr
examples/simple_shield/src/main.nr

This PR is more minimalist than the previous PR. It:
- Merges 'priv' and 'const' statements into 'let' statements.
- Removes the 'priv' modifier (it remains the default modifier - no need to explicitly state priv)
It is worth noting there should be no loss of functionality with the removal of `const` statements since users can already specify `const` types. The following is valid:
```rs
let x: const Field = 2;
```

Remove 'priv' and 'const' statements

---

crates/noirc_evaluator/src/ssa/acir_gen.rs
crates/noirc_evaluator/src/ssa/block.rs
crates/noirc_evaluator/src/ssa/code_gen.rs
crates/noirc_evaluator/src/ssa/flatten.rs
crates/noirc_evaluator/src/ssa/integer.rs
crates/noirc_evaluator/src/ssa/node.rs
crates/noirc_evaluator/src/ssa/optim.rs
crates/noirc_evaluator/src/ssa/ssa_form.rs

This PR is meant as a cleanup with no intended behavior changes*.
It:
- Replaces `arena::Index` in favor of `BlockId` and `NodeId` which gives us more type safety. Since we are effectively using indices as pointer, it is similar to replacing `void*` in favor of `BasicBlock*` and `NodeObj*`.
- Renames some parameters. I had no formal way of doing this change, I only changed some parameter names to be more descriptive as I saw them rather than attempting to go through every function. I tried to name all uses of `IRGenerator` as `igen` where before it was split between `igen`, `cfg` and `eval`.
*Refactoring to using stronger types via BlockId and InstructionId did reveal a bug in unrolling for loops where a node index was being passed as a block index.

Use typed IDs over arena::Index in ssa pass

---

crates/noirc_evaluator/src/lib.rs
crates/noirc_evaluator/src/ssa/code_gen.rs
crates/noirc_frontend/src/ast/expression.rs
crates/noirc_frontend/src/ast/function.rs
crates/noirc_frontend/src/ast/statement.rs
crates/noirc_frontend/src/hir/resolution/errors.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/type_check/mod.rs
crates/noirc_frontend/src/hir/type_check/stmt.rs
crates/noirc_frontend/src/hir_def/function.rs
crates/noirc_frontend/src/hir_def/stmt.rs
crates/noirc_frontend/src/lexer/token.rs
crates/noirc_frontend/src/parser/parser.rs

This adds support for the above patterns which allows for:
- Destructuring structs:
```rs
let Foo { a, b: bar } = Foo { a: 0, b: 1 };
a + bar
```
- Destructuring tuples:
```rs
let (a, b, c) = (1, 2, (3, 4));
a + b
```
- Mut patterns:
```
let mut a = 32;
a = 5;
let mut (b, c) = (1, 2);
let (d, mut e) = (3, 4);
// ...etc
```
- And identifier patterns.
Note that some functionality to fully make use of these patterns is still unimplemented:
- Structs and tuples are not implemented in the backend
- Tuples are not implemented at all, this PR is their first inclusion in noir.
- Mutability of a variable isn't tracked yet. Ideally we track this and issue an error when attempting to mutate an immutable variable.

Implement struct, tuple, and mut patterns in the frontend

---

crates/noirc_frontend/src/hir/type_check/expr.rs

In a talk with Guillaume, we discovered the index of index expressions wasn't being type checked. This PR adds this functionality, asserting that the type of the index is always a `const Field`.

Type check index expressions

---

crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir/type_check/mod.rs
crates/noirc_frontend/src/hir/type_check/stmt.rs
crates/noirc_frontend/src/hir_def/types.rs

I noticed there were still some times we check if a type is exactly equal to another, without checking if either is the error type. This PR adds `Type::matches` for checking `==` or `is_error` and goes through every use of `Type::eq` to ensure we no longer expose the Error type to users in error messages. This ensures that if a particular expression fails to typecheck the user doesn't get an error in every spot that uses that expression saying `expected xxx but found type Error`.
This PR also fills in a TODO to check that type casting is valid in the type checker rather than the evaluator.

Hide error type from being shown in error messages

---

crates/acvm/src/pwg/arithmetic.rs
crates/aztec_backend/src/acvm_interop/pwg.rs

Before the partial witness generator would retry instructions that failed in case they were generated out of order. This was potentially problematic as it could lead to e.g. assignment instructions being performed in different orders changing the final results of variables.

Enforce Partial Witness Generator expects an ordered IR

---

crates/nargo/tests/test_data/1_mul/src/main.nr
crates/nargo/tests/test_data/2_div/src/main.nr
crates/nargo/tests/test_data/3_add/src/main.nr
crates/nargo/tests/test_data/4_sub/src/main.nr
crates/nargo/tests/test_data/5_over/src/main.nr
crates/noirc_evaluator/src/builtin/setpub.rs
crates/noirc_evaluator/src/lib.rs
crates/noirc_evaluator/src/ssa/code_gen.rs
crates/noirc_evaluator/src/ssa/mem.rs
crates/noirc_evaluator/src/ssa/node.rs
crates/noirc_frontend/src/hir/def_collector/dc_crate.rs
crates/noirc_frontend/src/hir/def_collector/dc_mod.rs
crates/noirc_frontend/src/hir/def_map/item_scope.rs
crates/noirc_frontend/src/hir/def_map/module_def.rs
crates/noirc_frontend/src/hir/resolution/errors.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir/type_check/mod.rs
crates/noirc_frontend/src/hir/type_check/stmt.rs
crates/noirc_frontend/src/hir_def/expr.rs
crates/noirc_frontend/src/hir_def/function.rs
crates/noirc_frontend/src/hir_def/stmt.rs
crates/noirc_frontend/src/hir_def/types.rs
crates/noirc_frontend/src/node_interner.rs
examples/assign_ex/src/main.nr

This PR separates IdentIds from the new DefinitionIds, the former is removed entirely and all variables referencing the same definition will have the same DefinitionId. The names and types of definitions are still deduplicated in the interner. A new 'mutable' field was also added to track mutability.
This change was made purely to be more like rust, there were no runtime changes required/made for this to be made.
Example Error:
```
error: Variable z must be mutable to be assigned to
┌─ /Users/jakefecher/Code/Noir/noir/crates/nargo/../../examples/assign_ex/src/main.nr:5:5
│
5 │     z = x * y;
│     -
```

Enforce variables must be 'mut' to be assigned to

---

crates/noirc_evaluator/src/lib.rs
crates/noirc_evaluator/src/ssa/code_gen.rs
crates/noirc_frontend/src/ast/statement.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir/type_check/stmt.rs
crates/noirc_frontend/src/hir_def/stmt.rs
crates/noirc_frontend/src/hir_def/types.rs
crates/noirc_frontend/src/parser/mod.rs
crates/noirc_frontend/src/parser/parser.rs

Currently for assignment expressions we only support `ident = expr;`. This PR adds support for field assignment (`lvalue.ident = expr`) and array index assignment (`lvalue[expr] = expr;`) to the frontend - as well as nested forms of each.
Further work is needed to get these lvalue expressions working in the backend.

Add support for assignment of fields and indices in frontend

---

crates/noirc_evaluator/src/ssa/code_gen.rs
crates/noirc_evaluator/src/ssa/ssa_form.rs

Variable_values were not updated.
We now use a helper function instead of adding the variable manually

Small fix regarding function parameters

---

crates/acvm/src/pwg/logic.rs
crates/aztec_backend/src/acvm_interop/pwg.rs

The logic gate solver follows now the same pattern of other solvers:
It can delay the solve until witnesses are available

Logic gate solver follows now

---

crates/noirc_evaluator/src/lib.rs
crates/noirc_evaluator/src/ssa/code_gen.rs
crates/noirc_frontend/src/ast/expression.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir_def/expr.rs
crates/noirc_frontend/src/parser/parser.rs

Per a request from @guipublic. 
This PR adds support for nested arrays such as `[[1, 2], [3, 4]]` in the frontend. It also supports some related features like nested indexing `a[0][2]`. Part of the requirement for this change was that array indexing nodes in the ast used to only accept an Ident as their lhs, this has been changed to accept an arbitrary expression such that, e.g. `foo()[5]` or `[1, 2][0]` are now valid. Both ssa and the interpreter now need code to handle this case since both seemed to store arrays by name previously when they aren't guaranteed to have one.
Additionally the parser that parses postfix unary expressions has been rewritten since it did not allow for expressions like `a[0].foo[6].baz[3]` before.

Support multi-dimensional arrays in the frontend

---

crates/noirc_frontend/src/hir/type_check/expr.rs

Adds a special check for if the index is a field type but non-const to issue "Array index must be const (known at compile-time), but here a non-const {} was used instead" instead of the usual type mismatch, expected const Field error.

Slightly improve array access error message

---

crates/noirc_frontend/src/hir/type_check/stmt.rs

This PR allows you to specify more general types for let statements than that of the rhs. For example, previously `let x: Field = 32` was rejected since the rhs is `const Field` rather than Field itself.
This PR changes this to allow such code as long as the assigned type is a subtype of the annotated type.
Note that creating a variable initialized to a constant value still requires explicit annotation to remove the const-ness. So creating a non-const u32 looks like
`let x: u32 = 1234 as u32;` compared to today where you would have to do:
`let x = 1234 as u32 + private_var - private_var;`
This is only desirable for mutable variables but the repetition can be annoying nonetheless (though it is an improvement from the current constraints of needing to use a private variable to force …

Allow rhs of Let statements to be subtypes of the annotated type

---

crates/noirc_evaluator/src/ssa/context.rs
crates/noirc_evaluator/src/ssa/inline.rs

by the merge of the ssa refactoring into function-return PR, the previous behavior is restored but it should be refactored again when we will support multiple return values.

Fix the behavior that was broken

---

crates/nargo/tests/test_data/7_function/src/main.nr
crates/noirc_evaluator/src/ssa/code_gen.rs
crates/noirc_evaluator/src/ssa/context.rs
crates/noirc_evaluator/src/ssa/function.rs
crates/noirc_evaluator/src/ssa/inline.rs
crates/noirc_evaluator/src/ssa/optim.rs

I have removed the optimisation for returned arrays, I will add it back in a separate PR.
A function call returns a Value where each NodeId of the Value correspond to a result instruction.
We add dummy load and stores as long as the function call is not inlined, to take into account for by-value array arguments and by-value array results.

Handle multiple return values from function calls

---

crates/noirc_evaluator/src/lib.rs
crates/noirc_evaluator/src/ssa/node.rs
crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir/type_check/mod.rs
crates/noirc_frontend/src/hir/type_check/stmt.rs
crates/noirc_frontend/src/hir_def/types.rs
crates/noirc_frontend/src/node_interner.rs

These use type variables internally which can be bound to any Field, Integer, or other PolymorphicInteger type.
Difference in functionality versus the old `const Field` subtyping:
```rs
let foo = 5;
... foo + my_u8 ...
... foo + my_u32 ...
```
Is valid for the old approach and invalid for this PR since `foo: u8` after it is unified with u8 on the second line.
Motivation for this PR is primarily for it to be easier for the backend to track types. Alternatively, we could keep the old approach and add in explicit casts `_ as u32` each time subtyping is used.

Implement polymorphic integer literals

---

crates/nargo/tests/test_data/6/src/main.nr
crates/nargo/tests/test_data/7_function/src/main.nr
crates/noirc_evaluator/src/ssa/acir_gen.rs
crates/noirc_evaluator/src/ssa/code_gen.rs
crates/noirc_evaluator/src/ssa/context.rs
crates/noirc_evaluator/src/ssa/function.rs
crates/noirc_evaluator/src/ssa/mem.rs
crates/noirc_evaluator/src/ssa/optim.rs
crates/noirc_evaluator/src/ssa/ssa_form.rs

When constrain or intrinsic use arrays we disable CSE because arrays are not in SSA form.
Furthermore, we add dummy load/store to avoid over-simplification of memory operations during CSE
Finally, we put all writing to arrays inside the memory_map to ensure the correct value is used.

Fix CSE for constrain and intrinsic

---

noirpacker.py

Adds a small python script to pack a project directory of noir files into a single noir file.
- Removes `mod foo;` declarations in each file and adds submodule declarations `mod foo { ... }` wrapping files as needed.
Not sure if this repository is the best place for this tool but I put it here for now for visibility.
Example of running in `crates/nargo/tests/test_data/modules_more/src`:
```rs
mod foo {
mod bar {
fn from_bar(x : Field) -> Field {
x
}
}
fn hello(x : Field) -> Field {
x
}
}
// An example of the module system
fn main(x : Field, y : Field) {
constrain x != foo::bar::from_bar(y);
}
```
Which still correctly proves and verifies.

Add packer script to pack a directory into one file

---

crates/aztec_backend/src/barretenberg_rs/composer.rs

While trying to work on a more thorough Noir example I wanted to construct a verifier contract using `nargo contract`. However, I would arrive at this error every time: 
```
nargo(89530,0x11e781e00) malloc: *** error for object 0x7fbdba80c600: pointer being freed was not allocated
nargo(89530,0x11e781e00) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      nargo contract
```
It looks to be happening here when interoperating with barretenberg using FFI: 
https://github.com/noir-lang/noir/blob/e9494ffd754a6a0cf7b6453d5749041035ef8bfb/crates/aztec_backend/src/barretenberg_rs/composer.rs#L520
As per the comments in the method it looks like there are some bytes getting mangled and I am suspicious that this is why when Rust would later deallocate the `Vec` the program …

Fix for nargo contract cmd

---

crates/noirc_evaluator/src/ssa/acir_gen.rs
crates/noirc_evaluator/src/ssa/code_gen.rs
crates/noirc_evaluator/src/ssa/context.rs
crates/noirc_evaluator/src/ssa/inline.rs
crates/noirc_evaluator/src/ssa/integer.rs
crates/noirc_evaluator/src/ssa/mem.rs

This is a small PR that change the absolute memory addresses in LOAD and STORE instructions , into relative addressing.
It makes memory instructions easier to handle as we do not need to compute the offset anymore. If the absolute addresses are required to support dynamic memory indexing, it will be trivial to re-construct them at that point.

Use relative index for arrays

---

crates/nargo/tests/test_data/6_array/src/main.nr
crates/nargo/tests/test_data/7_function/src/main.nr
crates/nargo/tests/test_data/8_integration/src/main.nr
crates/nargo/tests/test_data/9_conditional/src/main.nr
crates/nargo/tests/test_data/generics/src/main.nr
crates/noir_field/src/generic_ark.rs
crates/noirc_evaluator/src/lib.rs
crates/noirc_evaluator/src/ssa/code_gen.rs
crates/noirc_evaluator/src/ssa/mem.rs
crates/noirc_frontend/src/ast/mod.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir_def/types.rs
crates/noirc_frontend/src/parser/parser.rs

Removes variable-length arrays in favor of length-polymorphic arrays. Additionally the array type syntax has been changed to match rust's. Now:
- `[Field; 4]` is an array type of 4 Fields
- `[Field]` is an array type of polymorphic length of Fields. The main difference between variable-length arrays are that these can later be resolved to a known length and will be used to monomorphise functions accepting any length array into a new copy per each new array length.

Remove variable length arrays, Add length-polymorphic arrays

---

Cargo.lock
crates/acvm/src/lib.rs
crates/nargo/Cargo.toml
crates/noirc_abi/Cargo.toml
crates/noirc_driver/Cargo.toml
crates/noirc_evaluator/Cargo.toml
crates/noirc_frontend/Cargo.toml

This is the PR to implement issue #47. 
The main change is switching to having a default trait implementation for `solve` in the PWG generator. Currently, aside from the gadget call gate, all the code in gate solver is the same between both the aztec and arkworks backend. A separate method was created to solve a gadget call which will be overridden in each backend's PWG where the GadgetCaller specified in the respective backend's `acvm_interop` will be called. A similar strategy can then be employed for any backend that requires a different solver implementation for a given gate. A backend will now override a specific gate solver within the PWG `solve` method rather than having to reimplement the entire arithmetic section of the PWG.  
Now that we have moved the backends out of the noir …

Refactor API for PWG

---

crates/nargo/src/lib.rs
crates/noirc_evaluator/src/binary_op/xor.rs
crates/noirc_evaluator/src/ssa/block.rs
crates/noirc_evaluator/src/ssa/context.rs
crates/noirc_evaluator/src/ssa/function.rs
crates/noirc_evaluator/src/ssa/node.rs
crates/noirc_frontend/src/ast/function.rs
crates/noirc_frontend/src/parser/mod.rs

PR #315 showed no errors on the CI when pushed and locally when running `cargo clippy -- -D warnings`. There must have been a new push to the stable build for clippy as there were a couple lint errors that appeared once the PR was merged to master.

Quick fix clippy lint errs

---

crates/noirc_evaluator/src/ssa/conditional.rs
crates/noirc_evaluator/src/ssa/context.rs

A loop with a big range (>1000) may create a 1000-depth CFG and we were parsing it using recursion in order to build the decision tree, causing an overflow of the stack. This PR uses an iterative traversal of the graph, which fix the stack overflow.

Build the decision tree without recursion

---

crates/noirc_evaluator/src/ssa/block.rs
crates/noirc_evaluator/src/ssa/conditional.rs
crates/noirc_evaluator/src/ssa/optim.rs

Although simplifying early is better (e.g during unrolling), simplification of IF statements has a lot of implications; not only on the structure of the CFG itself but also on some PHI instructions. Handling all these impacts is not straightforward and it is much simpler to handle this during the IF reduction by simply ignoring the instructions coming from the dead branch.
We should investigate later on whether this could also be handled during the construction of the decision tree.

Move the constant folding for IF statements at the time they are processed

---

Cargo.lock
crates/fm/src/file_reader.rs
crates/nargo/tests/test_data/8_integration/src/main.nr
crates/noirc_evaluator/src/ssa/anchor.rs
crates/noirc_evaluator/src/ssa/context.rs
crates/noirc_evaluator/src/ssa/function.rs
crates/noirc_evaluator/src/ssa/inline.rs
crates/noirc_evaluator/src/ssa/integer.rs
crates/noirc_evaluator/src/ssa/mod.rs
crates/noirc_evaluator/src/ssa/node.rs
crates/noirc_evaluator/src/ssa/optim.rs

The CSE implementation required to parse the list of previous instructions for each instruction, making it a quadratic algorithm.
This PR makes the CSE linear by using hashmaps so the whole list is not searched everytime.
The handling of memory instructions is trickier because the ordering kind of matter, depending on whether or not the index of the memory is known. Most of the work was related to make the CSE linear also for memory instructions but at the end it did not have much impact on the performances with the examples I tried.
I also reviewed the usage of CSE and tried lighten its use.

Linear cse

---

crates/nargo/tests/test_data/3_add/src/main.nr
crates/noirc_evaluator/src/ssa/acir_gen.rs

Small fix to use the correct bit size in a range check.
Alternatively, we could use the max of the operands bit size but we would need some dataflow analysis to benefit from this.
I also added a test that should have failed before the fix.

Use correct bit size in a range check

---

crates/noirc_frontend/src/hir/def_collector/dc_crate.rs

The global consts PR was safe to merge, however, an interner was still being passed to the `into_diagnostic` method when type checking the consts. This simply removes that interner from being passed in

Quick fix remove unnecessary field

---

crates/nargo/tests/test_data/tuples/src/main.nr
crates/noirc_evaluator/src/ssa/code_gen.rs
crates/noirc_frontend/src/hir/type_check/stmt.rs

Previously there was a bug where doing `let (a, b) = ...` would fail with a `todo!(...)` in the code. This PR implements the todo.
The original test case used an if: `let (a, b) = if true { (0, 1) } else { (2, 3) };` but ifs returning tuples currently fail in SSA as the value returned by an if is a Value::Single rather than the expected Value::Struct. This is considered a separate issue from this PR.

Fix tuple patterns

---

crates/nargo/tests/test_data/5_over/src/main.nr
crates/noirc_frontend/src/lexer/token.rs

Odd bits integers were already supported so I am just removing the `todo!()`

Enable integers with odd bits

---

crates/noirc_evaluator/src/ssa/code_gen.rs
crates/noirc_evaluator/src/ssa/function.rs
crates/noirc_evaluator/src/ssa/mem.rs
crates/noirc_frontend/src/hir_def/types.rs

Small fix so that function calls are properly translated in codegen in case of recursion calls.
Note that call recursion is not currently allowed, but now instead of having a random crash, users will get 'not implemented'.

Fix function call translation in case of recursion

---

crates/nargo/tests/test_data/6_array/src/main.nr
crates/nargo/tests/test_data/tuples/src/main.nr
crates/noirc_evaluator/src/ssa/code_gen.rs
crates/noirc_evaluator/src/ssa/conditional.rs
crates/noirc_evaluator/src/ssa/context.rs

This allows to use syntax like: `let (a, b) = if true { (0, 1) } else { (2, 3) };`
It highlighted  an issue caused by the iterative version of the parsing of the CFG when building the decision tree. The parsing is finally correct now.

Handle return values from IF blocks

---

crates/acir/src/circuit/gate.rs
crates/nargo/src/cli/gates_cmd.rs
crates/nargo/src/cli/mod.rs

closes #343 
This PR adds the `nargo gates` command which counts the number of each gate in the circuit. I've reused the existing names for the gadget calls and added names in a similar style for the "standard" gates.
Running this command on [mastermind-noir](https://github.com/vezenovm/mastermind-noir/tree/43516b105294162522d4de24ebb7a31192fa99db) gives the output below.
```
$ nargo gates
Gates successfully counted
Total gates: 336
By type:
arithmetic: 269
invert: 43
odd_range: 1
pedersen: 1
range: 13
split: 8
truncate: 1
```
Open to any opinions on formatting, etc.

Add cli command to count various types of gates

---

crates/acir/src/native_types/arithmetic.rs
crates/acir/src/optimiser/csat_optimiser.rs
crates/acvm/src/compiler.rs
crates/acvm/src/lib.rs
crates/nargo/tests/test_data/config.toml

This PR fixes issue #364 by sorting the intermediate gates created by the optimizer, so that intermediate values can be computed in the first pass. The gates must be internally sorted by witness index in order for the comparison function added to Expression to work properly.

Sort gates by witness index

---

crates/nargo/tests/test_data/bit_and/src/main.nr
crates/noirc_evaluator/src/ssa/acir_gen.rs

AND and XOR custom gates in barretenberg do not support odd bit size, which is the root cause of the issue reported here: https://github.com/snjax/zkships/tree/master/issues/segfault
One bits operation do not use the custom gate anymore (I assume this is more efficient)
Other odd-size operations are done with one more bit to get an even number

fix odd bitsize for bitwise operations

---

crates/nargo/tests/test_data/pedersen_check/Prover.toml
crates/nargo/tests/test_data/pedersen_check/src/main.nr

I added the test case to the pedersen check test. If we remove the guard on gadget inputs and the sorting of the optimised gates, this test case fails.

Add regression test for the bug fixed by PR373

---

crates/nargo/tests/test_data/struct/src/main.nr
crates/noirc_evaluator/src/ssa/code_gen.rs
crates/noirc_evaluator/src/ssa/node.rs

We were getting the struct object rather than the field element of the structure when accessing an array inside a struct via index.
I added a regression test.

Accessing array inside a struct bug fix

---

crates/nargo/src/resolver.rs

closes #399 
This PR allows us to specify paths of local dependencies inside a crate's `Nargo.toml` dependencies array.
i.e. For a project with structure:
```
root
├── bin
│     ├──src
│     │   └── main.nr
│     └── Nargo.toml
└── lib
├──src
│   └── lib.nr
└── Nargo.toml
```
by adding the following line to the dependencies array in `bin/Nargo.toml`
```
local = {path = "../lib"}
```
`bin/src/main.nr` can then make use of the functions contained within `lib/src/lib.nr`
Local dependencies can now be specified in `Nargo.toml` which will then be available inside the crate.
~~I haven't tested this past the immediate imports (i.e. I've tested local dependencies but not local dependencies of dependencies) however, even without this, it's a useful addition as it allows proper testing of …

Add support for local dependencies

---

crates/nargo/src/cli/contract_cmd.rs
crates/nargo/src/cli/gates_cmd.rs
crates/nargo/src/cli/verify_cmd.rs

Compilation of circuits now uses the `compile_circuit` function rather than duplicating this logic in each location. This shouldn't affect functionality but improves clarity. 
N/A
N/A
N/A

Prefer usage of `compile_circuit` in nargo

---

crates/nargo/tests/test_data/9_conditional/src/main.nr
crates/noirc_evaluator/src/ssa/conditional.rs
crates/noirc_evaluator/src/ssa/context.rs

The instructions for computing block assumption were not inserted in correct order, which make the solver unable to compute witnesses in some cases, as reported in #421.
Test case has been added to 9_conditional.

Fix block assumption computation

---

.github/build-x86_64-apple-darwin
.github/workflows/publish-x86_64-apple-darwin.yml

Add binary build GitHub Action for x86_64-apple-darwin target (Apple Mac on Intel CPU)
Resolves (link to issue)
#225 Releases don't contain binaries anymore _- resolves partially as it provides Mac Intel only, others to follow._
`.github/workflows/publish-x86_64-apple-darwin.yml` where the base of GitHub Action is defined 
`.github/build-x86_64-apple-darwin` where shell script is defined to compile releasable binary along with std_lib contents 
N/A
N/A
N/A

Adds binary x86_64-apple-darwin 

---

.github/build-nix
.github/workflows/publish-x86_64-unknown-linux-gnu.yml
nix/mixed.nix

#225 Releases don't contain binaries anymore _- resolves partially as it provides Linux Intel only, others to follow._
`.github/workflows/publish-x86_64-unknown-linux-gnu.yml` - where the base of GitHub Action is defined
`.github/build-nix` -  where shell script is defined to compile releasable binary along with std_lib contents
`nix/mixed.nix` - nix definition to fix the linux build environment
N/A
N/A
N/A

Adds binary build GitHub Action for x86_64-unknown-linux-gnu target

---

.github/workflows/publish-x86_64-apple-darwin.yml
.github/workflows/publish-x86_64-unknown-linux-gnu.yml

#225 - Partially Releases don't contain binaries anymore - _enables nightly schedule to upload binaries_
`.github/workflows/publish-x86_64-apple-darwin.yml`
`.github/workflows/publish-x86_64-unknown-linux-gnu.yml`
both received cron schedules to run at 2 AM UTC
N/A
N/A
N/A

Adds nightly build schedule

---

crates/nargo/tests/test_data/global_consts/src/main.nr
crates/noirc_frontend/src/hir/def_collector/dc_crate.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs

This is a quick fix for a problem that a user just brought up to me. I didn't make an issue as it was a fast fix
They were getting an error when trying to build this snippet
```
global NUM_LIMBS: Field = 8;
// This defines a BigInt, a smart wrapper around a sequence of u32 limbs, least-significant limb first
struct BigInt {
limbs: [u32; NUM_LIMBS]
}
```
I was able to then recreate the error with similar code. 
The build would fail when a local global was used in an array type within a struct definition. 
1. Globals needed to be resolved before struct definitions. 
2. We needed to resolve globals in the local module before resolving the struct fields (this is the same thing we do in `resolve_function`). This is necessary with the current resolver infrastructure which creates a new Resolver …

Fix globals in array types of struct fields

---

crates/nargo/src/cli/prove_cmd.rs

When a noir program returns a value but one of the constraints is failing, noir is not be able to compute the return value. However it will try to use it to write the verifier.toml
We return the failing constraint error before using the return value.

use return value only when witness are all solved

---

crates/noirc_evaluator/src/ssa/inline.rs
crates/noirc_evaluator/src/ssa/optim.rs

False constraints like in #474 panic instead of generating an error.
#474 is not an issue but when getting an always false constraint like in the issue (using a=1), it leads to panic instead of having an error message.
With this PR, errors inside simple_cse are propagated to the caller.
- [X ] I have tested the changes locally.
- [X ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [X ] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [ X] I have reviewed the changes on GitHub, line by line.
- [ X] I have ensured all changes are covered in the description.

propagate error from cse

---

crates/nargo/tests/test_data/bool_or/src/main.nr
crates/noirc_evaluator/src/ssa/acir_gen.rs

Bit operations (i.e bitwise operation of length 1) do not use an acir opcode so they do not need a witness. However they may need some nonetheless because they involve multiplication. This PR make sure we create a witness if needed.
Added a regression test case in bool_or

fix bit operation with non-linear expressions

---

.github/workflows/publish-x86_64-unknown-linux-gnu.yml

Fixes Adds binary build GitHub Action for x86_64-unknown-linux-gnu target PR #460 and aligns to #443

Aligns build to (#443) Refactor stdlib into a separate noir library

---

.github/workflows/publish-x86_64-pc-windows-wasm.yml

#225 Releases don't contain binaries anymore _- resolves partially as it provides Windows, wasm based binaries, others to follow._
`.github/workflows/publish-x86_64-pc-windows-wasm.yml` - adds workflow to build binary on windows based runner. This uses static wasm build of the backend hence performance is going to be suboptimal.
N/A
N/A
N/A

Adds binary(wasm) build GitHub Action for x86_64-pc-windows-wasm

---

crates/nargo/tests/prove_and_verify.rs

integration tests in the CI have issue due to the output log:
`This step has been truncated due to its large size. Download the full logs from the menu once the workflow run has completed. `
Disable the debug log when running integration tests

Disable debug output during integration tests

---

crates/noirc_frontend/src/hir/type_check/expr.rs

Related to #498
The type system used to allow field comparisons, but since these operations are invalid we would eventually fail in SSA with a compiler crash. This fixes the check in the type system to disallow comparison for fields, but allow eq and neq operations.

Improve field comparison error message

---

crates/noirc_abi/src/input_parser/toml.rs

This is a very small change so an issue is overkill.
Currently we call `check_toml_map_duplicates` in each arm of the match statement in `toml_map_to_field`, the only difference between arms is in the mapped value being inserted. Instead we can just return the value to be inserted from the match statement and insert values into `field_map` in a single place below it.
IMO, this improves readability and reducing LOC is always nice. For consistency I've also changed `toml_remap` to match.
N/A
N/A

Remove duplication in `toml_map_to_field` and `toml_remap`

---

.github/build-x86_64-apple-darwin
.github/workflows/publish-x86_64-apple-darwin.yml

#225 Releases don't contain binaries anymore _- switches apple builds to WASM, adds aarch64 (M1) target._
`.github/workflows/publish-x86_64-apple-darwin.yml` - Adds `aarch64-apple-darwin` build target and switches to WASM based backend.
`.github/build-x86_64-apple-darwin` - accepts target as parameter instead of hard coded value.
N/A
N/A
N/A

Adds `aarch64-apple-darwin` build target, switches to WASM backend

---

crates/nargo/tests/test_data/global_consts/src/main.nr
crates/noirc_frontend/src/ast/mod.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/parser/parser.rs

Resolves #495
Allows expressions using basic operators to be used in array length types. This was previously allowed in array length expressions and is now added here for consistency.
This PR also allows the array-length mini evaluator to evaluate immutable variables recursively as we previously allowed their evaluation when we had several separate ways of evaluating array lengths. All of these separate ways have now been removed as of this PR and changed so that the mini evaluator during name resolution is the only thing evaluating array lengths.
Changes a couple types in the global_consts test to evaluate to the same array lengths but less directly.

Allow expressions in array length types

---

crates/noirc_abi/src/input_parser/toml.rs

No issue as this is a small refactor.
It was kinda bugging me how we're converting an integer to a string and back and having to unwrap the result multiple times.
Instead we now convert the `u64` directly into an `i128` to pass into the `FieldElement` without using `parse_str`.
N/A
N/A
- [] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.

Reduce amount of type conversions in `toml_map_to_field`

---

crates/acvm/src/lib.rs

Resolves  #534 
We check if a witness was already solved or not before setting its value. If the previous value does not match the new one, then the gate is not satisfied
No change, it is not easy to validate the behavior currently as the test should fail and was also failing to verify before the fix.

Check for solved witness before setting its value

---

.gitattributes

No issue exists for this - it is a minor, quick change.
Noir files (*.nr) currently have no syntax highlighting when viewing them on github. This PR hints to github that it should use rust syntax highlighting for these files instead - which should be close enough.
- Cannot test these changes locally, it is on github only. It works for me in other repositories though.

Use rust syntax highlighting for .nr files in this repo

---

crates/nargo/tests/test_data/9_conditional/src/main.nr
crates/noirc_evaluator/src/ssa/conditional.rs

Resolves #530
We handle predicate in binary instructions during inlining
I also added a small refactor of short_circuit() which was suggested in PR #437 review but was not implemented.
Regression test case added to 9_conditional

Handle predicate operator during inlining

---

crates/nargo/src/cli/mod.rs

Resolves #558.
- Add a setting to the existing `clap` `App` requiring a subcommand (see [this forum post](https://users.rust-lang.org/t/clap-how-to-group-require-top-level-subcommands/24789/2)).
None.
None.
None.

Improve `nargo`'s handling of absent subcommand

---

.github/workflows/release.yml
.github/workflows/rust.yml

(None - github CI has started to fail for more recent commits failing to link libomp).
Locks ubuntu version to ubuntu-20.04 which is known to work. We should update this to work on ubuntu-latest later on and remove this change.

Update workflow to run on 20.04 to fix CI

---

crates/nargo/tests/test_data/9_conditional/src/main.nr
crates/noirc_evaluator/src/ssa/conditional.rs
crates/noirc_evaluator/src/ssa/context.rs
crates/noirc_evaluator/src/ssa/inline.rs

Resolves #579 
We need to know if arrays are initialised when handling conditional store instructions (with predicate), because the array initialisation cannot be 'conditionalised'. However, as returned arrays may not be initialised in function call, it results that store instructions in functions under a condition were never 'conditionalised'
To fix this issue, we ensure returned arrays are initialised and notify the conditionalize() method with the returned arrays so it can conditionalise them.
regression test is added to 9_conditional
There are several ways to solve this issue, for instance we could force users to always initialise arrays in the frontend:
let a = [0,2,3];   ....OK
let a = f(b);      ...NOT OK
but this seems to be a bit artificial to me and I'd rather fix the issue. …

Fix for 579: Always intialise returned arrays so they can be properly conditionalized

---

crates/acir/src/circuit/mod.rs
crates/fm/src/lib.rs
crates/nargo/build.rs
crates/nargo/src/cli/contract_cmd.rs
crates/nargo/tests/prove_and_verify.rs
crates/noirc_frontend/src/hir_def/types.rs

Resolves CI issues on recent PRs such as #591 
I've fixed the clippy warnings which are failing CI on recent PRs. No changes to functionality.
N/A
N/A

Fix clippy warnings

---

Cargo.lock
crates/wasm/Cargo.toml
crates/wasm/README.md
crates/wasm/build-wasm
crates/wasm/pkg/package.json

closes #590
I've bumped the crate version to match the version on [npm](https://www.npmjs.com/package/@noir-lang/noir_wasm) as `package.json` pulls the version from `Cargo.toml`.
I've also added `build-wasm` which produces a fresh build of the wasm package and manually inserts any missing values into `package.json` (`wasm-pack` doesn't allow customisation of the generated `package.json`).
N/A
N/A.

Add build script for `wasm` crate

---

crates/noirc_abi/src/errors.rs
crates/noirc_abi/src/input_parser/mod.rs
crates/noirc_abi/src/lib.rs
crates/noirc_evaluator/src/lib.rs
crates/noirc_evaluator/src/ssa/code_gen.rs
crates/noirc_frontend/src/ast/expression.rs
crates/noirc_frontend/src/ast/function.rs
crates/noirc_frontend/src/ast/mod.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/type_check/mod.rs
crates/noirc_frontend/src/hir_def/function.rs
crates/noirc_frontend/src/hir_def/types.rs
crates/noirc_frontend/src/parser/parser.rs

Resolves (partially) https://github.com/noir-lang/noir/pull/554#pullrequestreview-1225777575
This PR removes the concept of visibility from `AbiType` and moves it onto an `AbiParameter` struct. The reasoning for this is that, due to nested types, we currently include the visibility of a parameter potentially many times.
Removing this duplication simplifies serialisation of the `Abi` struct as we no longer need to strip out these extraneous visibility fields.
N/A
N/A

Separate `AbiType` from visibility

---

Cargo.lock
crates/noir_field/Cargo.toml

https://github.com/noir-lang/noir/issues/602#issue-1511279328
(If it does not already exist, first create a GitHub issue that describes the problem this Pull Request (PR) solves before creating the PR and link it here.)
Resolves (link to issue)
don't think blake2 is used in noir_field crate
delete blake 2 dependency
(Describe the changes in this PR. Point out breaking changes if any.)
delete blake 2 dependency

delete unused blake2 crate

---

Cargo.lock
crates/wasm/Cargo.toml
crates/wasm/src/lib.rs

The `wasm` crate is showing up in yellow with warnings.
I've updated the `from_serde` and `into_serde` method calls according to https://github.com/rustwasm/wasm-bindgen/issues/2770
```
use of deprecated associated function `wasm_bindgen::JsValue::into_serde`: causes dependency cycles, use `serde-wasm-bindgen` or `gloo_utils::format::JsValueSerdeExt` instead
```
I've chosen the `gloo_utils::format::JsValueSerdeExt` method as this is closest to the current implementation.
None
None

update deprecated `into_serde`/`from_serde`

---

crates/noirc_evaluator/src/ssa/acir_gen.rs

Resolves #580
Generates an intermediate variable for multiplication when needed during division.
No test added as the fix is using a function already tested.

issue 580: generate a witness if needed during division

---

crates/nargo/tests/test_data/to_bytes/src/main.nr
crates/noirc_evaluator/src/ssa/acir_gen.rs

Resolves #617 
After a byte decomposition, I want to be able to pass the full byte array along without having to do any hack-y methods to get around the compiler. Currently, this is not possible as we are panicking during acir generation. This is due to us incorrectly mapping the outputs of our bit/byte decomposition methods. Further information can be found in issue #617.
The outputs from `to_bits` and `to_bytes` are equal to the size of the bit size or byte size specified in the Noir program. However, we currently restrict this to be less than the full bit size or byte size of a Field for safety. Both methods return fully decomposed arrays with [u1; 256] and [u8; 32] respectively. If I specified a `byte_size` of 16 for example and I want to access any elements past index 15 in the array …

Fix for mapping the full array during acir gen for to_bytes and to_bits

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

Resolves #641
Replaces the parens with `` (html comments) so the help text is hidden when we render markdown on an issue. This avoids needing to delete the help text or having unnecessary noise in the issue/PR.
None
None

Make issue template help text hidden comments

---

crates/fm/Cargo.toml
crates/fm/src/file_reader.rs
crates/nargo/Cargo.toml
crates/noirc_driver/Cargo.toml
crates/wasm/Cargo.toml

Resolves #639
This removes the `std` and `wasm` features added by `fm` and then re-exported by `noirc_driver` and instead relies on checking if the `target_arch` is `wasm32` which gets set when building for the wasm target. This also removes the flags specified by other crates when depending on `noirc_driver`.
None
None

Remove wasm & std features by using target_arch

---

Cargo.lock
Cargo.toml
crates/acir/Cargo.toml
crates/acvm/Cargo.toml
crates/acvm/src/pwg/signature/ecdsa.rs
crates/arena/Cargo.toml
crates/fm/Cargo.toml
crates/iter-extended/Cargo.toml
crates/nargo/Cargo.toml
crates/noir_field/Cargo.toml
crates/noirc_abi/Cargo.toml
crates/noirc_driver/Cargo.toml
crates/noirc_errors/Cargo.toml
crates/noirc_evaluator/Cargo.toml
crates/noirc_frontend/Cargo.toml
crates/wasm/Cargo.toml

#629
(If it does not already exist, first create a GitHub issue that describes the problem this Pull Request (PR) solves before creating the PR and link it here.)
Resolves (link to issue)
use workspace inheritance for the codebase. 
change dependencies in the toml file. 
the minimal rust version supported by this is 1.64, so its added to the workspace toml file
sled doesn't seem to be used in acvm so it was removed.
there are two versions of tempfile used, one is 3.1.0, the other is 3.2.0, I changed both to 3.2.0. hope it won't be an issue.
There are other dependencies that have different version, for example both dirs 4.0 and dirs 3.0 is used, I'm not sure if it should be merged.
Most crate edition is 2018, some is 2021. I changed all to 2021
(Describe the changes in this PR. Point out …

use workspace inheritance

---

crates/fm/src/lib.rs

Resolves #663 
This avoids a panic if `add_file` is called with a file path that doesn't end in `.nr`
I removed the check against the extension so we don't return `None` if the extension is something other than `.nr`. It doesn't seem like this check is necessary because we read the source code and then virtualize the path to remove the extension entirely.
Added a test that `add_file` can accept a file with a different extension and virtualizes the path by removing the extension.

Avoid panic if add_file path does not have `.nr` extension

---

.github/ISSUE_TEMPLATE/bug_report.md

We're getting less setup issues now.
This deletes setup info from the bug report template and focuses on the version of `nargo` / NPM packages the user was using instead.

Update Bug Report "Environment" Section

---

Cargo.lock
crates/nargo/Cargo.toml
crates/nargo/src/backends.rs

Resolves #666 
It also makes https://github.com/noir-lang/book/issues/36 easier/nicer. And I thought I saw another issue before but can't find it now.
This adds a `plonk_bn254_wasm` feature that enables the `barretenberg_wasm` backend instead of `barretenberg_static_lib`. It will streamline the setup instructions for people building from source and avoid them needing to edit Cargo.toml files.
Adds the `plonk_bn254_wasm` feature flag to nargo and selects the wasm backend if it is set.
Adds `barretenberg_wasm` if the feature is enabled.
After this, the book can be updated to this command for building from source:
```bash
cargo install --path=crates/nargo --no-default-features --features plonk_bn254_wasm
```

Add feature flag for wasm backend when building nargo

---

Cargo.lock

Resolves # 
This locks barrenenberg_wrapper to the latest commit. Even though we are using the `kw/noir-dsl` branch in the dependency graph, it will still resolve to the older commit if you install exactly from the lock.
I just ran `cargo update --package barretenberg_wrapper` to update it.
`barretenberg_wrapper` is now the latest commit.

Ensure barrenenberg_wrapper is locked to latest commit

---

Cargo.lock
crates/nargo/Cargo.toml

Resolves #662 
PR in aztec_backend: https://github.com/noir-lang/aztec_backend/pull/48
While migrating to noir-lang/aztec-connect/barretenberg I fixed the hash_to_field interop in barretenberg. However, due to us currently having a manual build process for the barretenberg.wasm file I missed that I needed to rebuild the wasm file for the aztec backend. The wasm aztec backend is what is currently used for binary releases so that is why the error still existed in the issue linked. I tested this update locally and was able to use hash_to_field with the wasm aztec backend and not just the static lib.
Our CI only runs the static lib so `hash_to_field` would still pass our Github tests. 
I changed the commit to for the aztec backend in the nargo `Cargo.toml` file to reflect the newly updated …

update backend commits for a missing hash_to_field bb.wasm fix

---

crates/noirc_abi/src/lib.rs

Related to #679 
I've updated the function signature to use slices instead of a reference to a vector.
N/A
N/A

use &[FieldElement] arg instead of &Vec<FieldElement> in abi.decode

---

crates/nargo/src/cli/gates_cmd.rs

Resolves #701 
Newlines have been remove from the print statements in `nargo gates`.
Before:
```
$ nargo gates
ACIR opcodes generated : 18
Total ACIR opcodes generated for language PLONKCSat { width: 3 }: 20
check_circuit result: 1
Backend circuit size: 62
$
```
After:
```
$ nargo gates
ACIR opcodes generated : 18
Total ACIR opcodes generated for language PLONKCSat { width: 3 }: 20
check_circuit result: 1
Backend circuit size: 62
$
```
N/A
N/A

Remove unnecessary newlines in `nargo gates`

---

Cargo.lock
crates/nargo/Cargo.toml
crates/nargo/src/errors.rs
crates/noirc_abi/Cargo.toml
crates/noirc_abi/src/errors.rs
crates/noirc_abi/src/input_parser/toml.rs

No issue as this is a small refactor.
Rather than implementing `std::fmt::Display` manually for `CliError`, `InputParserError` and `AbiError`, I've used `thisError` to derive these implementations.
I've also implemented `InputParserError::from` for `toml::{ser,de}:Error` to map these errors automatically.
`thisError` added to `nargo` and `noirc_abi`
N/A
- N/A I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.

Replace handwritten error display methods with `thisError`

---

crates/nargo/src/cli/check_cmd.rs
crates/nargo/src/cli/compile_cmd.rs
crates/nargo/src/cli/contract_cmd.rs
crates/nargo/src/cli/mod.rs
crates/nargo/src/cli/new_cmd.rs
crates/nargo/src/cli/prove_cmd.rs
crates/nargo/src/cli/verify_cmd.rs
crates/nargo/src/constants.rs
crates/nargo/src/lib.rs

Resolves #644
The constants defined in `cli/mod.rs` have been moved to `constants.rs`, I've added a line for each on which described how it's used.
N/A
N/A

Create a `constants.rs` file for Nargo

---

crates/noirc_abi/src/lib.rs

Closes #636 
Rather than passing a slice of field elements along with an initial index to read from, we now pass an iterator over the encoded field elements to `Abi.decode_value`.
Note that decoding arrays will now silently truncate the array rather than panicking. We could add a check to enforce this again but we already perform a check in `Abi.decode` to ensure that we have enough field elements in order to decode all the ABI's parameters so this is safe.
N/A
N/A

Remove index counting in abi decoding

---

crates/noirc_evaluator/src/lib.rs

Related to #684 as it makes the witness indices of each param more accessible.
An argument to `main` can either be public or private, we disallow situations where e.g. an array has a mixture of public and private elements. This means that we can simplify the evaluator by rather than eagerly pushing each witness onto the `public_inputs` vector, we can instead calculate all the witnesses associated with a parameter and push all of them if the parameter is public.
This is also useful as it surfaces all the witnesses associated with a particular parameter which makes it easier to build a mapping from a param to its witness indices when it comes to abi encoding.
N/A
N/A

Apply witness visibility on a parameter level rather than witness level

---

Cargo.lock
crates/iter-extended/src/lib.rs
crates/noirc_abi/Cargo.toml
crates/noirc_abi/src/input_parser/toml.rs

I've replaced the functions `toml_map_to_field` and `toml_remap` with implementations of `TomlTypes::from<InputValue>()` and `InputValue::try_from<TomlTypes>()`, i.e. rather than mapping the entire set of arguments at once we specify how to map a single input from one type to another.
We can then just iterate over each argument and map them individually.
N/A
N/A

Replace `toml_map_to_field` and `toml_remap` with traits to map between `InputValue`s and `TomlTypes`

---

crates/nargo/src/cli/mod.rs
crates/nargo/src/cli/prove_cmd.rs

Resolves #702 
I've reworked `prove_with_path` so that it either prints to console or writes to file based on whether it has been passed a name for the proof its generating.
After this PR, the output of `nargo prove` is as follows
```
$ nargo prove
ACIR opcodes generated : 18
Total Proving time (Rust + Static Lib) : 103622032ns ~ 0seconds
Proof successfully created
14208d4085eb58be92293e07faec661997e0229d6df1fe0721dae6ce959810a3180d69edde0530819878d89c839728d81115c902fb64a0e548e3b42f5def18af01dba2a835d4db405afe379f88180a9ace50dd299037cab0525d2520045bb58405ed26b820e1d6b4af20257a639e01efac3b322c01952822faecdd5b6c82eb95230b6eea86f72d7a13770da2e93b9900c6bbb4c513b923d0399b1d382f081a5119de74636dcf483a589a6c20b71635375016e11c0c1f45f1287744047b2c3db00a5be2ed6892f94a447238e45376c411002d396bbe6da910 …
```

Remove print to console for named proofs in `nargo prove`

---

.github/workflows/release.yml
CONTRIBUTING.md
Cargo.toml
SUPPORT.md

Resolves #607 
This introduces a process for Noir releases that leverages Conventional Commits and the release-please tool to produce a "release pull request" containing an auto-generated changelog, appropriate SemVer bumps, and lockfile updates.
I reorganized the `SUPPORT.md` file to contain community-facing things, and then updated `CONTRIBUTING.md` to discuss my proposed release solution. I also updated the `release.yml` workflow to use release-please.
I'll be discussing our workflow changes at the scheduled meeting time 🎉 
We'll also want to tag a version right before we land this so we can have everything onward follow the convention.

feat(docs): Introduce Conventional Commits & release process docs

---

.github/workflows/pull-request.yml

N/A
This is a follow on to #717 that adds a PR title validation to CI. This should help to ensure we don't accidentally merge a PR with the wrong message when used in conjunction with these github settings:
While not perfect, it'll catch our common mistakes.
Adds the CI action that happens on `pull_request` or `pull_request_target` using only `pull-request: read` permissions which will check the PR title is valid or fail a check.

feat(ci): Add workflow to validate PR title

---

.github/workflows/bors.yml

Resolves #292  
This removes the bors.yml workflow file. We're instead opting for a GitHub branch protection that requires a branch to be up-to-date before it can be squashed into master.
Just removing the file since it is creating failing CI runs.

chore(ci): Remove failing bors workflow

---

.github/workflows/labeler.yml

Resolves # 
We continue-on-error because the action is buggy and tries to remove labels when they don't exist.

chore(ci): Avoid reporting errors if labeler action fails

---

.github/workflows/rust.yml

- We want to build the compiler on a stable version of Rust, whereas nightly has no stable guarantees.
- If we introduce a nightly only feature, we will need to feature gate it as it would break the stable release which is something we don't plan to do for the foreseeable future.

chore(ci): remove nightly builds and run tests only on stable Rust 

---

Cargo.lock
crates/nargo/Cargo.toml

(Currently a draft to discuss) This updates the `aztec_backend` package to point at my commit in https://github.com/noir-lang/aztec_backend/pull/46 - which replaces the `openssl` dependency with `rustls`. This is a dependency that doesn't require openssl to exist on a system, and helps with cross-compilation. I found out that they don't have complete support (e.g. RISC-V is unsupported) but they seem to support all the platforms we really care about.
This allows us to remove a hack that we have in the `build-nargo` workflows to cross-compile the linux binaries.
Updates `aztec_backend`, which still needs to be reviewed and merged upstream.
`aztec_backend`

feat(nargo): Leverage rustls instead of openssl for downloads

---

crates/noirc_evaluator/src/ssa/block.rs

Related to https://github.com/noir-lang/noir/issues/679.
- Update function signatures to accept slice instead of vec.
- Change an instance of argument (to the modified function) to slice instead of vec.
N/A
N/A
N/A

chore: Use &[NodeId] instead of &Vec<NodeId> in noirc_evaluator

---

.github/workflows/pull-request.yml

Resolves # 
This updates the conventional commit workflow to check when something is added to a merge queue; however, it just skips the check step because we've already had it successful on the PR (and that title is being used for the merge queue).

fix(ci): Skip the title check if handling a merge group

---

crates/noirc_evaluator/src/ssa/acir_gen/operations/binary.rs
crates/noirc_evaluator/src/ssa/node.rs
crates/noirc_evaluator/src/ssa/optimizations.rs

Revert PR #760 by fixing the issue in a different way.
It turned out that deleting instructions with false predicate had side effects on nested if as it could delete the condition of a nested if, so that the code would then keep both branches.
Instead of deleting them, we keep them but ignore them when generating ACIR.
Test case added by #760 is kept.

chore(ssa): keep instructions with false predicate

---

Cargo.toml
README.md
crates/nargo/build.rs

I've bumped any references to Rust 1.64.0 to 1.66.0
N/A
N/A

chore(nargo)!: bump MSRV to 1.66.0

---

crates/nargo/tests/test_data/generics/src/main.nr
crates/noirc_driver/src/lib.rs
crates/noirc_errors/src/lib.rs
crates/noirc_errors/src/reporter.rs
crates/noirc_evaluator/src/errors.rs
crates/noirc_frontend/src/ast/expression.rs
crates/noirc_frontend/src/ast/mod.rs
crates/noirc_frontend/src/ast/structure.rs
crates/noirc_frontend/src/hir/def_collector/dc_crate.rs
crates/noirc_frontend/src/hir/def_collector/dc_mod.rs
crates/noirc_frontend/src/hir/def_collector/errors.rs
crates/noirc_frontend/src/hir/def_map/mod.rs
crates/noirc_frontend/src/hir/resolution/errors.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/type_check/errors.rs
crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir/type_check/stmt.rs
crates/noirc_frontend/src/hir_def/expr.rs
crates/noirc_frontend/src/hir_def/stmt.rs
crates/noirc_frontend/src/hir_def/types.rs
crates/noirc_frontend/src/lexer/errors.rs
crates/noirc_frontend/src/node_interner.rs
crates/noirc_frontend/src/parser/errors.rs
crates/noirc_frontend/src/parser/parser.rs

Resolves #638
Implements generics on implementations where the `impl` keyword can introduce type variables that are visible to each method within.
This PR involved a larger amount of changes than expected. The bulk of changes are in name resolution and include changing impls to carry around a generics field, changing type lookups to carry around generics if necessary and instantiate automatically otherwise, a few added error types mostly related to applying generic to a non-struct type or attempting to apply generics to `Self`, among other changes.
None
Added a short test of impl generics to the `generics` test case.

feat: Impls with generics

---

.github/workflows/rust.yml

Resolves # 
This adds a concurrency group for the rust workflow to ensure that old, unnecessary runs aren't still happening when all we really care about is the latest run.

feat(ci): Add concurrency group for rust workflow

---

crates/arena/src/lib.rs
crates/fm/src/lib.rs
crates/iter-extended/src/lib.rs
crates/nargo/src/lib.rs
crates/noirc_abi/src/lib.rs
crates/noirc_driver/src/lib.rs
crates/noirc_errors/src/lib.rs
crates/noirc_evaluator/src/lib.rs
crates/noirc_frontend/src/lib.rs
crates/wasm/src/lib.rs

Resolves #813.
Add `#![forbid(unsafe_code)]` to crate roots.

chore: Forbid unsafe code

---

crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/type_check/mod.rs
crates/noirc_frontend/src/hir_def/function.rs

As per this issue https://github.com/noir-lang/noir/issues/812
Renamed
``HirFunction::unsafe_from_expr``
You can use the search function in your IDE to search for unsafe_from_expr, I cannot find it elsewhere only three places
to
``HirFunction::unchecked_from_expr``
Resolves #812 
``crates\noirc_frontend\src\hir\resolution\resolver.rs line number 299``
from
``HirFunction::unsafe_from_expr(expr_id)``
to
``HirFunction::unchecked_from_expr(expr_id)``
``crates\noirc_frontend\src\hir\type_check\mod.rs line number 137``
from
``let func = HirFunction::unsafe_from_expr(expr_id);``
to
``let func = HirFunction::unchecked_from_expr(expr_id);``
Added a comment in ``crates\noirc_frontend\src\hir_def\function.rs line number: 21 ``
``crates\noirc_frontend\src\hir_def\function.rs line number 23/24``
from …

chore: updated "HirFunction::unsafe_from_expr" to "HirFunction::unchecked_from_expr"

---

crates/noirc_frontend/src/hir_def/function.rs

Related to https://github.com/noir-lang/noir/issues/812
I've removed a comment which referred to the old name of `unsafe_from_expr`. The new name gives the info which was included in the comment so it is no longer neccessary.
N/A
N/A

chore: remove stale comment on HirFunction.unchecked_from_expr

---

.github/workflows/release.yml

Resolves # 
This adds `NOIR_RELEASES_TOKEN` as the token for our release workflow. This will allow our CI to run against our "release PR".  We need to add the token because GitHub skips CI triggers for anything generated by `GITHUB_TOKEN` which is the default.
cc @kevaundray to double check the permissions on the token before we land this.

chore(ci): Add release token to enable runs against release PR

---

crates/nargo/src/cli/compile_cmd.rs

Resolves # 
Removes unwanted print statement

chore: remove unwanted print of Ok(<path>) in nargo compile

---

crates/noirc_evaluator/src/ssa/acir_gen.rs
crates/noirc_evaluator/src/ssa/acir_gen/acir_mem.rs
crates/noirc_evaluator/src/ssa/acir_gen/operations/binary.rs
crates/noirc_evaluator/src/ssa/acir_gen/operations/cmp.rs
crates/noirc_evaluator/src/ssa/acir_gen/operations/intrinsics.rs
crates/noirc_evaluator/src/ssa/acir_gen/operations/load.rs
crates/noirc_evaluator/src/ssa/acir_gen/operations/return.rs
crates/noirc_evaluator/src/ssa/acir_gen/operations/store.rs
crates/noirc_frontend/src/hir/resolution/errors.rs

This is a fourth preparation step for dynamic memory. Instead of having a one big VM that holds all the arrays, we assign one per array, which enable support for variable length arrays.
We also use a more generic name for the structure which abstract the memory_map as it will be extended for the dynamic array feature.

chore(ssa): per array memory map

---

crates/noirc_evaluator/src/ssa/context.rs
crates/noirc_evaluator/src/ssa/node.rs

Resolves https://github.com/noir-lang/noir/issues/837
Add `Display` for `BinaryOp` in `ssa`
1. Implement `Display` for `BinaryOp`
2. Deleted matching `BinaryOp` to `str` part in `context.rs`

chore: Add display for binaryop

---

crates/nargo/tests/test_data/higher-order-functions/src/main.nr
crates/noirc_frontend/src/hir/type_check/expr.rs
noir_stdlib/src/array.nr

Resolves #831
Adds some higher order array functions to the stdlib.
Adds:
- ~~`std::array::map`~~, `map` has been removed as we would need to support the syntax `[expr; comptime expr]` where we can initialize an array of any comptime length. Today it is limited to only integer literals or globals rather than any length expression.
- `std::array::fold`
- `std::array::reduce` - like fold but uses the first element in the array as the accumulator value.
- ~~`std::array::find`~~ `find` has also been removed. The negative numbers seemed to cause issues that prevented proving/verification.
- `std::array::sort_via`
- `std::array::all`
- `std::array::any`
Tests these functions in the higher_order_functions test.

feat(stdlib): Add higher order array functions

---

.github/workflows/release.yml

Follow up to #840
We were triggering the builds on the PR itself, but the push of the lockfile was not running checks and blocking the merge. This adds the token to checkout the repo & push the new lockfile as @kevaundray so CI will run. Tested on my fork.

chore(ci): Make Kev the committer on release lockfile updates

---

crates/noirc_evaluator/src/ssa/acir_gen/internal_var_cache.rs
crates/noirc_evaluator/src/ssa/acir_gen/operations/intrinsics.rs
crates/noirc_evaluator/src/ssa/context.rs
crates/noirc_evaluator/src/ssa/flatten.rs
crates/noirc_evaluator/src/ssa/integer.rs
crates/noirc_evaluator/src/ssa/node.rs

Resolves #756 
Renames `Obj` variant to `Variable` since `NodeObject::Object(Variable)` is not clear., unless this is implying that a NodeObject's Object variant and Variable are equal in some way.

chore: Rename NodeObject::Obj variant to NodeObject:Variable

---

crates/noirc_evaluator/src/ssa/acir_gen/operations/sort.rs

Resolves # 
`a_val.sort()` returns `()` so this equality will always succeed. We now sort prior to passing these arrays into the `assert_eq`.
N/A

fix: avoid testing equality between unit values in acir_gen test

---

Cargo.lock

Resolves # 
The dependencies of `noir_wasm` are now in order to match how they're reformatted when running `cargo build` on [fd64be5](https://github.com/noir-lang/noir/commit/fd64be55fc905a032d53c9ac7a7f7b71da899c37)

chore: update lockfile

---

crates/nargo/src/cli/verify_cmd.rs

Related to https://github.com/noir-lang/noir/issues/701
We now no longer print an empty line after the proof verification output.

chore: remove newline from print output of `nargo verify`

---

crates/nargo/src/cli/compile_cmd.rs
crates/nargo/src/cli/execute_cmd.rs
crates/nargo/src/cli/mod.rs
crates/nargo/src/cli/prove_cmd.rs
crates/nargo/src/cli/verify_cmd.rs
crates/noirc_abi/src/input_parser/mod.rs
crates/noirc_abi/src/input_parser/toml.rs
crates/noirc_driver/src/lib.rs

Resolves #855 
We don't get any benefit to allowing `CompiledProgram` to be created without an ABI as we always unwrap it. We then require the ABI to be included which allows us to remove repeated boilerplate to extract the ABI from the `CompiledProgram`
This revealed that we didn't need to clone the ABI in a number of places when reading in inputs so we can instead just borrow it from the `CompiledProgram`.

chore!: Make `abi` field non-optional in `CompiledProgram`

---

.github/workflows/rust.yml
.github/workflows/spellcheck.yml

Currently a PR which contains spelling errors will have two warnings thrown (one from `push`, one from `pull_request`). 
The only situation where these two jobs don't produce the same output is when the PR is behind master and either
1. master adds a new word to the dictionary and the PR uses that word. (Very niche situation)
2. master includes a spelling mistake which isn't in the PR. (Will be caught when master is merged into PR)
It's then sensible to only run spellchecks on each `push`.

chore(ci): only run spellcheck job on push

---

crates/nargo/src/cli/execute_cmd.rs
crates/nargo/src/cli/mod.rs
crates/nargo/src/cli/prove_cmd.rs
crates/nargo/src/cli/verify_cmd.rs
crates/noirc_abi/src/errors.rs
crates/noirc_abi/src/input_parser/mod.rs
crates/noirc_abi/src/lib.rs
crates/noirc_driver/src/lib.rs
crates/noirc_evaluator/src/lib.rs
crates/noirc_evaluator/src/ssa/acir_gen/operations/return.rs
crates/noirc_evaluator/src/ssa/acir_gen/operations/sort.rs
crates/noirc_frontend/src/hir_def/function.rs

Resolves #684 
This PR builds out the logic for passing up an explicit mapping for ABI parameters to their witness indices.
This is done in the `Evaluator` as rather than pushing a public param's witnesses onto the `public_inputs` vector we insert all params' witnesses into the `param_witnesses` `BTreeMap<String, Vec<Witness>>`. This allows us to get the witness indices for any parameter defined in the ABI.
The `Circuit` struct still uses a `PublicInputs` as this can be easily calculated from `param_witnesses`.
This new `param_witnesses` map is passed up and stored in the ABI as it's crucial to be able to abi encode inputs into the initial witness. As we're now directly encoding into a witness map, I've split the ABI `encode` method into `encode_to_witness` and `encode_to_array` …

feat(abi)!: add an explicit mapping from ABI params to witness indices

---

crates/nargo/src/cli/execute_cmd.rs
crates/nargo/src/cli/mod.rs
crates/nargo/src/cli/prove_cmd.rs
crates/nargo/src/cli/verify_cmd.rs
crates/noirc_abi/src/errors.rs
crates/noirc_abi/src/lib.rs
crates/noirc_evaluator/src/lib.rs

Resolves https://github.com/noir-lang/noir/pull/851#discussion_r1108927283
We've switched to tracking public inputs in the evaluator in `BTreeSet` rather than a `Vec` which naturally deduplicates them, this allows us to:
- stop deduplicating these inputs manually up in the Nargo CLI.
- always encode to a `WitnessMap` for both proving and verifying (before flattening this into an naturally deduped array for verification but we can remove this as well if the backends take a `WitnessMap` for verifier inputs)
The only sad thing about this PR is it brings back the boolean flag in the abi encoding functions (but we'll be able to handle this better with #678)

feat(abi)!: merge both abi encoding/decoding methods

---

crates/noirc_evaluator/src/ssa/acir_gen/operations/sort.rs

Resolves # 
We're currently not creating a valid `Evaluator` in this test as the `public_inputs` field isn't specified. I've switched this to use the `new` method fix this and make this test less sensitive to changes in `Evaluator`.
Note this wasn't caught as we don't compile and run any tests outside of `nargo` pending https://github.com/noir-lang/.github/pull/13.

fix: properly initialise `Evaluator` in test

---

crates/nargo/src/cli/execute_cmd.rs
crates/nargo/src/cli/verify_cmd.rs
crates/noirc_abi/src/errors.rs
crates/noirc_abi/src/input_parser/mod.rs
crates/noirc_abi/src/input_parser/toml.rs
crates/noirc_abi/src/lib.rs

Consequence of #731 
After #731 there's never a situation in which leaving an undefined parameter in a toml file is a valid input. This PR then removes support for this variant of `InputValue` which allows us to remove a lot of the error handling associated with it.

chore: remove support for InputValue::Undefined

---

crates/nargo/src/cli/compile_cmd.rs
crates/nargo/src/cli/execute_cmd.rs
crates/nargo/src/cli/prove_cmd.rs

Resolves # 
We only really make use of the decoded circuit return value which is returned from `execute_program` inside `execute_cmd::run` - in all other usages we just immediately drop it and just use the returned witness map.
This PR then moves the return value decoding up into `execute_with_path` and inlines `solve_witness` into `execute_program`.

chore: remove abi decoding from `execute_program`

---

crates/noirc_frontend/src/parser/parser.rs

Resolves #791 
Optimizes the `expression_with_precedence` parser which was the main cause of performance lost in the frontend.
The command used for testing was `nargo prove p` on the source project
```rs
fn main(x: bool) {
constrain x;
}
```
Timing details are averages of 10 runs and the results are as follows:
```
master     this branch
debug      1.758s        0.350s
release    0.470s        0.163s
```
So it is roughly a 5x speedup in debug and a 2.9x speedup on release.
For a more detailed flamegraph, see the graphs uploaded in #791.
The old `expression_with_precedence` parser recursively called itself for each precedence level, but also called each child level twice when constructing `expr <op> expr`, leading to an exponential blowup. Note though that this is from the time it takes to …

fix: Optimize parser

---

crates/nargo/src/cli/execute_cmd.rs
crates/nargo/src/cli/prove_cmd.rs
crates/nargo/src/cli/verify_cmd.rs
crates/noirc_abi/src/errors.rs
crates/noirc_abi/src/lib.rs
crates/noirc_evaluator/src/lib.rs
crates/noirc_frontend/src/hir_def/function.rs

Resolves #678 
Draft pending proper error types.
The ABI now has separate fields for the type and witness assignments of the return value. As a know on effect, the circuit's return value is now no longer included in the `InputMap` and so is taken as a separate argument to `Abi.encode` and returned separately by `Abi.decode`.
Some care needs to be taken now when checking to see if an ABI contains a public input as this could either be a public param or a return value, whereas previously we could just search `abi.parameters` for a public parameter. I've added a getter to perform this check for us.

feat(abi)!: add explicit return type field to ABI.

---

.github/workflows/release.yml

Resolves # 
This adds a dispatch that is triggered when we make a release, which fetches the correct version of noir and publishes the `@noir-lang/noir_wasm` package to npm.

feat(ci): Publish noir_wasm when we cut a release

---

crates/nargo/src/cli/mod.rs
crates/nargo/src/cli/prove_cmd.rs
crates/nargo/src/cli/verify_cmd.rs

Resolves # 
`fetch_pk_and_vk` only needs ownership of the circuit if we don't have any preprocessed keys (in order to generate them using the backend). We can delay cloning the circuit until we've checked for if we have preprocessed keys and avoid this clone when we don't need it.

chore: remove clone when using preprocessed keys

---

crates/nargo/src/cli/compile_cmd.rs

Resolves #877 
This PR removes the ability to save a witness to file from the `nargo compile` command. This should instead be done through the `nargo execute` command for reasons stated in the issue.

chore: remove `witness` flag from `nargo compile`

---

crates/nargo/src/cli/compile_cmd.rs
crates/nargo/src/cli/test_cmd.rs
crates/noirc_driver/src/lib.rs
crates/noirc_driver/src/main.rs

Resolves #880 
I've removed `np_language` from the interface of `Driver` and it now just uses the locally stored language when compiling.
**We could make this a non-breaking change** by maintaining the same interface while adding an `assert_eq(np_language, &self.langauge)` to each method which uses it. My feeling however is that we're going to be the only consumer of this API currently so we can make this breaking change safely.

fix!: prevent inconsistent language usage in `Driver`

---

crates/noirc_abi/src/input_parser/toml.rs

Resolves https://github.com/noir-lang/noir/pull/860#pullrequestreview-1306415549
When loading inputs from toml we need their `AbiType` to be included in the map `abi_map`. Due to #865, this doesn't get inserted automatically so we panic when loading return values.
We now insert the return type into the map so we can load toml files correctly again.

fix(abi): ensure that return value is loaded from toml

---

crates/nargo/tests/test_data/merkle_insert/src/main.nr
crates/nargo/tests/test_data/strings/src/main.nr
crates/noirc_evaluator/src/ssa/acir_gen/operations/intrinsics.rs

No issue as found issue while debugging separate project and is a quick fix
I was attempting to print the hash result of `mimc_bn254` in the std lib, but was hitting an unreachable case in the recently adding `evaluate_println` method in the acir_gen. It looks as though the println was being evaluated before the mimc result thus resulting in a situation where the non-constant expression had no cached witness. 
During `evaluate_println` we instead use `get_or_compute_witness` to compute the witness for InternalVar's that do not have a cached_witness rather than panicking. 
I tested this by adding a println to the `merkle_insert` test where we check that we can print the mimc hash. I also checked the output of the mimc hash in `merkle_insert`, where the printed output was correct.

fix: compute witness when println evaluated before input

---

crates/nargo/src/cli/execute_cmd.rs
crates/nargo/src/cli/mod.rs
crates/nargo/src/cli/prove_cmd.rs
crates/nargo/src/cli/verify_cmd.rs
crates/noirc_abi/src/lib.rs

Resolves # 
We currently had some special logic related to:
- avoiding reading files which we expect to be empty
- splitting off return value from BTreeMap loaded from file / inserting return value to be saved to file.
which exists in the CLI business logic. As this is purely an IO implementation detail I've pushed it inside the relevant helpers.

chore: encapsulate IO logic in IO functions

---

crates/nargo/src/cli/compile_cmd.rs

Quick fix found while working on a separate project so no issue
During `nargo compile` the checksum file is being written first followed by the acir file. We set an extension `.acir.sha256` for the sha checksum. When we reset the extension we were mistakenly only resetting the last extension of `.sha256` so the acir file being written to `target` was `.acir.acir`. 
We write the ACIR file followed by the checksum now. Running `nargo compile p` for example will now correctly give `p.acir` and `p.acir.sha256`.

fix(nargo): Switch order of writing acir file and acir checksum file

---

crates/noirc_abi/src/input_parser/mod.rs

Resolves #889 
`FieldElement.num_bits()` returns 0 for `FieldElement::zero() so the current check for satisfying the AbiType fails. I've relaxed the check to accept 0 or 1 bits to address this.

fix: correct type checking to handle `false` bools

---

crates/nargo/src/cli/prove_cmd.rs
crates/nargo/src/cli/verify_cmd.rs
crates/nargo/src/errors.rs

Resolves #873
Silences output of `nargo prove` and `nargo verify`, unless either encounter an error.
If approved, we should likely follow this example and do this for other commands as well, where it makes sense. E.g. `cargo compile`.

feat: Silence output of prove and verify

---

crates/nargo/src/cli/check_cmd.rs
crates/nargo/src/cli/compile_cmd.rs
crates/nargo/src/cli/contract_cmd.rs
crates/nargo/src/cli/execute_cmd.rs
crates/nargo/src/cli/fs/acir.rs
crates/nargo/src/cli/fs/inputs.rs
crates/nargo/src/cli/fs/keys.rs
crates/nargo/src/cli/fs/mod.rs
crates/nargo/src/cli/fs/proof.rs
crates/nargo/src/cli/fs/witness.rs
crates/nargo/src/cli/mod.rs
crates/nargo/src/cli/new_cmd.rs
crates/nargo/src/cli/prove_cmd.rs
crates/nargo/src/cli/verify_cmd.rs

Resolves #884 
The majority of the changes are just moving functions which load/write to file into the new `fs` module. I've also removed the preprocessing logic from `fetch_pk_and_vk` so that it's pure I/O as it's the CLI's responsibility to perform preprocessing where necessary.

chore: move nargo I/O into separate module

---

crates/wasm/src/lib.rs

No issue yet as discovered while quickly iterating development
Resolves #
We switched to using `read` and `write` on a `Circuit` in Noir. 
I switched the `noir_wasm` to use `Circuit::read` and and `circuit.write` instead of `Circuit::from_bytes` and `circuit.to_bytes()`.

fix(noir_wasm): Update wasm ACIR serialization

---

crates/nargo/tests/test_data/main_bool_arg/Prover.toml
crates/nargo/tests/test_data/main_bool_arg/src/main.nr
crates/noirc_abi/src/input_parser/toml.rs

Resolves #844 
We previously didn't support loading arrays of booleans from toml which makes it very annoying to have an array of bools in your ABI. I've added the necessary `TomlType` to support this along with a test.

feat: add support for reading boolean arrays from toml

---

Cargo.lock
crates/noirc_frontend/Cargo.toml
crates/noirc_frontend/src/lexer/token.rs

Addresses review comment https://github.com/noir-lang/noir/pull/903#discussion_r1116349549
I've added a test so that the `std::fmt:Display` of any `Keyword` can be looked up to recover the original keyword token.
This follows the pattern used here: https://github.com/noir-lang/acvm/blob/f57ba57c2bb2597edf2b02fb1321c69cf11993ee/acir/src/circuit/black_box_functions.rs#L200-L211
`Keyword::lookup_keyword` also includes some non-keyword entries which might benefit from being split off. Tthey don't entirely gel with the purpose of this function and require us to return an `Option<Token>` rather than an `Option<Keyword>` which is what I would expect.
I've added strum as a dev dependency

chore: add test for Keyword::lookup_keyword completeness

---

crates/noirc_evaluator/src/ssa/acir_gen/operations/cmp.rs

Check for equality before creating a witness and a constraint, in case the equality is known at compile-time.
This issue happens with the poseidonsponge_x5_254 test, but it is not part of the CI because it would be too long.

fix(ssa): fix the compile-time check for equality in acir-gen

---

crates/fm/src/file_map.rs
crates/fm/src/lib.rs
crates/noirc_evaluator/src/lib.rs
crates/noirc_evaluator/src/ssa/acir_gen/internal_var.rs
crates/noirc_evaluator/src/ssa/acir_gen/operations/sort.rs
crates/noirc_evaluator/src/ssa/context.rs
crates/noirc_evaluator/src/ssa/ssa_gen.rs
crates/noirc_frontend/src/graph/mod.rs
crates/noirc_frontend/src/hir/mod.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/scope/mod.rs
crates/noirc_frontend/src/main.rs

Related to https://github.com/noir-lang/noir/issues/874
See `Constructors` section of the guide in the issue 
1. Add `impl Default` to `new()` functions that do not take inputs. 
2. Change `new()` to call the default function. (update: remove empty new())
// 3. `vec![]` to `Vec::new()` (discarded this change)
// I'm not sure if removing `new()` functions is a good idea (this seems to be what the guide is suggesting from my //understanding) so I changed them to calling the `default` function.

chore: replace usage of `new()` with `default()` 

---

crates/noirc_evaluator/src/ssa/acir_gen/operations/binary.rs

Fix constant division by evaluating it at compile time
The test that raised the error is too complex to be included as a unit test, although it is most certainly possible to get a simple test with some research, I don't think it matters considering the fix. For the record the constant value was coming from evaluating a  condition with predicate.
The division by 0 panic should become a user error but it should be done when we refactor the acir_gen pass to add error handling.

fix: evaluate constant division

---

Cargo.lock
Cargo.toml
crates/nargo/Cargo.toml
crates/nargo/src/cli/compile_cmd.rs
crates/nargo/src/cli/contract_cmd.rs
crates/nargo/src/cli/gates_cmd.rs
crates/nargo/src/cli/prove_cmd.rs
crates/nargo/src/cli/verify_cmd.rs
crates/noirc_evaluator/src/lib.rs
crates/noirc_evaluator/src/ssa/acir_gen/constraints.rs
crates/noirc_evaluator/src/ssa/builtin.rs
cspell.json

Resolves # 
This PR updates the backend commit to work off of ACVM 0.5.0.

feat: update to ACVM 0.5.0

---

crates/nargo/src/cli/check_cmd.rs
crates/nargo/src/cli/compile_cmd.rs
crates/nargo/src/cli/fs/inputs.rs
crates/nargo/src/cli/fs/mod.rs
crates/nargo/src/cli/gates_cmd.rs
crates/nargo/src/cli/mod.rs
crates/nargo/src/cli/prove_cmd.rs
crates/nargo/src/errors.rs
crates/nargo/src/resolver.rs
crates/nargo/src/toml.rs

Followup to #907 
`CliError` shouldn't be made public so I've adjusted its visibility to ensure that it stays only visible within the crate. I've had to adjust the visibility of other functions to match ~~(we don't change the crate's interface doing this however)~~.
This PR is technically breaking as we've removed the `check_from_path` from the crate interface.

chore(nargo)!: restrict `CliError` visibility to crate

---

crates/noirc_evaluator/src/lib.rs

Resolves # 
After moving to ACVM 0.5.0 this line is converting a `BTreeSet` to a `BTreeSet`. I've then removed it as it's a noop.

chore: remove unnecessary conversion of public inputs

---

crates/wasm/src/lib.rs

Resolves # 
I've silenced the warnings for using deprecated functions inside the deprecated functions in the `wasm` crate.
None
None

chore: silence deprecation warnings in wasm crate

---

crates/arena/src/lib.rs
crates/fm/src/file_reader.rs
crates/fm/src/lib.rs
crates/iter-extended/src/lib.rs
crates/nargo/src/backends.rs
crates/nargo/src/cli/fs/mod.rs
crates/nargo/src/cli/mod.rs
crates/nargo/src/git.rs
crates/nargo/src/lib.rs
crates/nargo/src/resolver.rs
crates/nargo/src/toml.rs
crates/noirc_abi/src/lib.rs
crates/noirc_abi/src/serialization.rs
crates/noirc_driver/src/lib.rs
crates/noirc_errors/src/lib.rs
crates/noirc_errors/src/reporter.rs
crates/wasm/src/lib.rs

Addresses #919 for all crates other than `noirc_evaluator` and `noirc_frontend`
I've added the `unreachable_pub` to several crates and restricted function visibility to the minimum necessary.
- [x ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.

chore: restrict function visibility where overly broad

---

crates/nargo/src/cli/compile_cmd.rs
crates/nargo/src/errors.rs

Addresses (partially) #729 
We now pass a specific error type for issues during compilation up rather than immediately exiting.

chore(nargo): create a specific error variant for compilation

---

crates/noirc_evaluator/src/ssa/conditional.rs
crates/noirc_evaluator/src/ssa/flatten.rs
crates/noirc_evaluator/src/ssa/inline.rs

chore: debug_assert to assert

---

crates/nargo/src/cli/check_cmd.rs
crates/noirc_abi/src/lib.rs
crates/noirc_driver/src/lib.rs
crates/noirc_evaluator/src/lib.rs
crates/noirc_frontend/src/hir_def/function.rs
crates/noirc_frontend/src/monomorphization/ast.rs
crates/noirc_frontend/src/monomorphization/mod.rs

Following #851, we're now exposing methods to compute an "ABI" which doesn't contain half the fields of an actual ABI (namely, the witness maps). We then need some reduced ABI-ish format which just tells us what the arguments/return values are and should look like.
This PR introduces this as a `FunctionSignature` type alias which just describes the arguments and return values of a function.

chore!: replace dummy ABIs with `FunctionSignature` type alias

---

Cargo.lock
Cargo.toml
crates/nargo/tests/test_data/struct_inputs/Prover.toml
crates/nargo/tests/test_data/struct_inputs/src/foo.nr
crates/noirc_abi/src/input_parser/toml.rs

Resolves #934 
`toml` wasn't automatically ordering fields before tables in the toml it generated so we were manually partitioning the input map to ensure this happens. We however not we're enforcing this for nested tables which also include non-table fields.
`toml` has been since updated to handle this automatically so I've updated to the new version.
`toml` has been bumped to 0.7.2
Added a regression test for #934

fix:  generate valid toml when outputting nested structs 

---

crates/noirc_evaluator/src/ssa/acir_gen/constraints.rs
crates/noirc_evaluator/src/ssa/acir_gen/operations/binary.rs

We're currently using an implementation of  `a + k*b` in a situation where we know `a = 0`. We can then simplify to use our implementation of `k*b`.

chore: optimize `mul` for constant expressions

---

.github/pull_request_template.md

Resolves # 
Separate the documentation needs checkbox in the PR template of this repo from the pre-merge checklist.

chore(github): Separate `doc needed` Checkbox in PR Template

---

Cargo.lock
Cargo.toml
crates/nargo/Cargo.toml
crates/noirc_driver/Cargo.toml
crates/noirc_driver/src/program.rs

Resolves # 
We now output the `CompiledProgram` json file with the circuit represented as a hex string rather than as a long array of byte values. This is more consistent with standard solidity tooling.
Note that this hex is not 0x-prefixed, in case there are strong feelings around this.
- Relevant to https://github.com/noir-lang/book/issues/63

chore: serialize circuit as hex string in build artifact file

---

crates/noirc_evaluator/src/ssa/conditional.rs

Decision tree is compatible with loops in the CFG
Because we unroll before handling the IF statements, the decision tree was assuming the CFG does not contains any cycle. We do not do this assumption anymore and are now able to handle cycles in the CFG when building the decision tree.
This will enable us to do the unrolling after handling the IF statements. The later we unroll the better as unrolling has a big impact on performance.

chore(ssa): Handle loops when building the decision tree

---

crates/noirc_evaluator/src/ssa/ssa_gen.rs
crates/noirc_frontend/src/monomorphization/ast.rs
crates/noirc_frontend/src/monomorphization/printer.rs

Resolves #822
handle literals in one function, and remove the Unit literal which is not used.
- [ X] I have ensured all changes are covered in the description.

chore(ssa): consolidate literal handling

---

crates/nargo/src/cli/codegen_verifier_cmd.rs
crates/nargo/src/cli/mod.rs

Resolves #945 
I've renamed the `nargo contract` command to `nargo codegen-verifier`. `codegen` is shorter than `generate` and is more descriptive so I opted for this name instead of what's discussed in #945 (happy to switch if there's strong feelings about this).

chore(nargo)!: rename `contract` command to `codegen-verifier`

---

crates/nargo/src/main.rs

Resolves # 
I noticed that I forgot to update this link when I changed the templates, so users got dropped into an empty issue when following the link.

fix(nargo): Use yml extension for bug report link presented upon panic

---

crates/nargo/src/cli/check_cmd.rs
crates/nargo/src/cli/compile_cmd.rs
crates/nargo/src/cli/test_cmd.rs
crates/noirc_driver/src/lib.rs
crates/wasm/src/lib.rs

Resolves https://github.com/noir-lang/noir/issues/729
replacing std::process::exit to either
1. `CliError` if its in nargo or
2. `ReportedError` if its in driver
4. add a `panic!` to wasm crate

fix: Remove uses of std::process::exit

---

crates/nargo/src/cli/compile_cmd.rs

Resolves #873 for `compile` command
We now no longer print the paths where we've saved the build artifact and proving/verification keys when running `nargo compile`.

chore: silence `nargo compile` command

---

crates/nargo/src/cli/compile_cmd.rs

Resolves #966 (Although we'll need to do more on this in future)
I've created a separate function to compile a Noir contract compared to a single Noir program which returns a specialised struct for the compilation output of contracts.
These two functions are also now separated from IO, so could be reused in future for compilation in wasm (Most likely after the `nargo-core`/`nargo-cli` split?).

feat: separate contract/program compilation from IO

---

crates/noirc_abi/src/errors.rs
crates/noirc_abi/src/input_parser/toml.rs

Resolves the second part of https://github.com/noir-lang/noir/issues/969
Previously we'd iterate over the fields in `Prover.toml`, assume there's a matching entry in the ABI and then decode the data. This throws an unhelpful panic if `Prover.toml` contains an entry which doesn't exist in the ABI when looking up its type.
I've updated this loop to instead work over the expected ABI fields, check if an entry exists in `Prover.toml` and if not we raise an error saying that the argument with a certain name hasn't been found. As part of this we now pass the argument name into `try_from_toml` so that we can throw a meaningful error for struct fields.

fix: add more readable error for missing argument in toml

---

crates/noirc_frontend/src/hir/resolution/errors.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs

Resolves the first part of #969
This PR issues an error when a type constructor is given an incorrect number of generic arguments. If these are not checked, we later fail an assert while instantiating struct types later on during type checking. To ensure we do not hit this assert even in the presence of bad input, we resize the generics vector on error. Either truncating it or filling it with fresh type variables until it is the desired size.

fix: check the argument count of generic types

---

crates/noirc_frontend/src/hir/type_check/errors.rs
crates/noirc_frontend/src/hir/type_check/expr.rs

Resolves #939
Improves our error message when users try to access fields of an inferred type.
The previous error message:
```rs
error: Type _ has no member named x
┌─ /.../src/main.nr:3:20
│
3 │     let _f = |foo| foo.x;
│                    ---
error: aborting due to 1 previous errors
```
The new error message:
```
error: Type annotations needed before this point.
┌─ /.../src/main.nr:3:20
│
3 │     let _f = |foo| foo.x;
│                    --- Try adding a type annotation for this value before it is used here
error: aborting due to 1 previous errors
```
None
None
None

fix: Improve member access error

---

crates/nargo/build.rs

#973 #951  
Resolves 
N/A
Drops unnecessary build step code which copies stdlib.
N/A
N/A
N/A

chore: drop unnecessary build code copying stdlib

---

crates/fm/src/file_reader.rs

Resolves #981
We now reverse the slash direction for the prefix associated with `StdLibAssets` on windows.  This ensures that the path `std/lib.nr` matches this once it has converted into a `PathBuf` and back turning it into `std\lib.nr`

fix: reverse slash direction in `StdLibAssets` prefix on windows

---

crates/iter-extended/src/lib.rs
crates/nargo/tests/test_data/contracts/src/main.nr
crates/noirc_frontend/src/hir/def_collector/dc_crate.rs
crates/noirc_frontend/src/hir/def_collector/errors.rs
crates/noirc_frontend/src/hir/resolution/errors.rs
crates/noirc_frontend/src/hir/resolution/import.rs
crates/noirc_frontend/src/hir/resolution/path_resolver.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/type_check/mod.rs

Resolves #955
Prevents referencing items defined within a contract's scope from outside of a contract. Note that this currently will still allow calling these functions within another contract in the same program.
Updated contracts test to no longer reference contract functions within main.

fix: Prevent calling contract functions from outside the contract

---

crates/fm/src/file_reader.rs

Noticed while looking into #981
I noticed that we're not converting through an OsStr here which looks like a candidate for the root cause of #981. I can't test this as I don't have a windows install however.

chore: remove unnecessary conversion through `OsStr` in `read_file_to_string`

---

crates/nargo/src/cli/fs/keys.rs
crates/nargo/src/cli/preprocess_cmd.rs

Followup PR to #994
We don't need to take ownership here so let's pass the keys as slices.

chore: pass keys to `save_key_to_dir` as slice

---

crates/nargo/src/cli/check_cmd.rs
crates/nargo/src/cli/codegen_verifier_cmd.rs
crates/nargo/src/cli/compile_cmd.rs
crates/nargo/src/cli/execute_cmd.rs
crates/nargo/src/cli/fs/inputs.rs
crates/nargo/src/cli/fs/keys.rs
crates/nargo/src/cli/fs/mod.rs
crates/nargo/src/cli/fs/program.rs
crates/nargo/src/cli/fs/proof.rs
crates/nargo/src/cli/fs/witness.rs
crates/nargo/src/cli/mod.rs
crates/nargo/src/cli/new_cmd.rs
crates/nargo/src/cli/prove_cmd.rs
crates/nargo/src/cli/verify_cmd.rs

Addresses all instances of https://github.com/noir-lang/aztec_backend/pull/86#discussion_r1137806664 in `nargo`
I've replaced the instances of pushing onto mutable `PathBuf`s with using the `join` api with immutable `PathBuf`s. This is much clearer imo.

chore: switch from mutable to immutable api for building paths

---

crates/nargo/src/cli/check_cmd.rs
crates/nargo/src/cli/compile_cmd.rs
crates/nargo/src/cli/mod.rs
crates/nargo/src/cli/test_cmd.rs
crates/nargo/src/resolver.rs

Addresses https://github.com/noir-lang/noir/pull/973#issuecomment-1463998180
Currently we need to remember to explicitly add the std lib whenever we resolve a crate. Instead of this I've merged this into `Resolver::resolve_root_config` to happen automatically.
The `wasm` crate still has to add the stdlib manually as it doesn't use the `Resolver`

chore: automatically inject stdlib when resolving crate

---

crates/nargo/src/errors.rs

Resolves # 
I'd like to move to `CliError` being an umbrella error type which contains different types of errors for IO, abi encoding, compiling, solving, proving, etc. There's no reason to throw away all the information here and convert to a generic error.

chore: maintain structure of errors in `CliError`

---

crates/nargo/tests/test_data/higher-order-functions/src/main.nr
crates/noirc_frontend/src/hir/resolution/errors.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/scope/mod.rs
crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir_def/expr.rs
crates/noirc_frontend/src/hir_def/types.rs
crates/noirc_frontend/src/monomorphization/mod.rs
crates/noirc_frontend/src/node_interner.rs
noir_stdlib/src/array.nr

Resolves #972 
Allows numeric generics to be referenced like normal values. This resolves a common stumbling block for users when writing a function like the following:
```rs
fn foo<N>(array: [Field; N]) {
for i in 0 .. N {
....
}
}
```
Previously, we would error that there is no `N` in scope (since `N` is a type and not a value). With this PR, this code works as expected.
Notably, this PR now allows us to write the array `map` function and add it to our stdlib. This was not possible previously due to the syntax limitations placed on array-length expressions which prevented us from initializing an array using `let mut ret = [0; array.len()];`. This has been reworked slightly to reuse the same array length evaluation mechanism types use, which notably now allows us to use numeric generic …

feat: Allow numeric generics to be referenced and add `map`

---

crates/nargo/src/cli/check_cmd.rs
crates/nargo/src/cli/compile_cmd.rs
crates/nargo/src/cli/test_cmd.rs
crates/nargo/src/lib.rs
crates/nargo/src/manifest.rs
crates/nargo/src/resolver.rs

Resolves # 
Our `Nargo.toml` file is an analogue to Cargo's `Cargo.toml`. Cargo refers to this file as a package [manifest](https://doc.rust-lang.org/cargo/reference/manifest.html) whereas we refer to it as the package config.
For consistency's sake we should rename this to match Cargo as it adds an unnecessary translation layer. I also find the term "config" for `Nargo.toml` a bit confusing as it implies settings rather than dependencies, etc.
This PR then makes the renamings:
- `Config` -> `PackageManifest`
- `Package` -> `PackageMetadata`

chore(nargo): rename struct representing `Nargo.toml` from `Config` to `PackageManifest`

---

crates/nargo/src/cli/compile_cmd.rs
crates/nargo/src/errors.rs
crates/nargo/src/lib.rs
crates/nargo/src/manifest.rs
crates/nargo/src/resolver.rs

Addresses most instances of #11 in `nargo`.
This PR defines `InvalidPackageError` and `DependencyResolutionError` to handle issues with malformed packages or invalid dependencies. Previously we would make all of these `CliError::Generic` errors.

feat(nargo): add `InvalidPackageError` and `DependencyResolutionError` error types.

---

Cargo.lock
crates/nargo/src/cli/compile_cmd.rs
crates/noirc_driver/Cargo.toml
crates/noirc_driver/src/contract.rs
crates/noirc_driver/src/lib.rs
crates/wasm/src/lib.rs

Followup PR for #966
Currently a lot of the compilation logic for contract lives inside `nargo`. In order to make them a first class citizen, ideally we'd be able to just tell the driver to compile the contracts within a crate similarly to how we can do for standard noir programs.
This PR then pushes much of this logic inside of `noirc_driver` so we just need to call  `driver.compile_contracts(&args.compile_options)`

feat: make `noirc_driver` aware of contracts

---

crates/nargo/src/resolver.rs

Resolves # 
I've removed the `cached_packages` field from the `Resolver` struct as it doesn't need to exist. It's both constructed and consumed within `resolve_config` so we can just have it be a variable within the function.
This allows us to remove the cloning of the dependency manifest.

chore(nargo): remove `cached_packages` field from `Resolver`

---

crates/nargo/src/cli/mod.rs
crates/nargo/src/lib.rs

Baby step towards #794 
Currently `nargo` cannot run except in the root directory of a noir package. This is a little annoying if you're in the `src` directory of a package but `nargo` isn't smart enough to compile the program inside it.
When running the `nargo` CLI we now search all ancestor directories for a `Nargo.toml` file and then run in the context of that directory.

feat(nargo): allow running `nargo` from any directory in package

---

crates/noirc_driver/src/lib.rs
crates/noirc_frontend/src/hir/def_collector/dc_crate.rs
crates/noirc_frontend/src/hir/mod.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/monomorphization/mod.rs
crates/noirc_frontend/src/node_interner.rs

Resolves #1018
This PR assigns a storage slot to each global, starting from 1, and resetting back each time a new contract is identified.
Note that this PR does not add a way to actually access this value within noir code yet. I expect this to be more difficult since we will need to track whether e.g. a parameter of a function will have its storage slot taken, requiring us to verify the function is either called with a global as its argument or with another parameter.

feat: Add storage slots to globals

---

crates/nargo/src/cli/mod.rs

Resolves # 
This PR fixes the issue where running `nargo new` unsuccessfully searches for a `Nargo.toml` file resulting in an error of the following form:
```
Error: cannot find a Nargo.toml in /tmp
Location:
crates/nargo/src/cli/mod.rs:67:26
```
- Condition added to check command before searching for project root.

fix(nargo): only search for `Nargo.toml` in commands which act on a Nargo package

---

crates/nargo/src/cli/mod.rs
crates/nargo/src/cli/print_acir_cmd.rs

Resolves #1030
Adds the ability to print a compiled circuit to stdout such that the ACIR can be inspected.
```
aztec@Aztecs-MBP pedersen % nargo print-acir
current witness index : 6
public input indices : [2, 4]
EXPR [ (1, _1) (2, _2) (-1, _3) 0 ]
BLACKBOX::PEDERSEN [(_1, num_bits: 254), (_2, num_bits: 254), (_3, num_bits: 254)] [ _4, _5]
```
It's a new feature that could be made known to devs as it's very useful for education.

feat(nargo): print-acir command

---

crates/nargo/src/manifest.rs
crates/nargo/src/resolver.rs

Resolves #1014 
This PR updates the logic around the `DependencyResolutionError::RemoteDepWithLocalDep` as discussed in #1014.
I've also reworked the `PackageManifest.has_local_path()` function to make it a bit clearer.

fix(nargo): correct logic for rejecting transitive local dependencies

---

crates/nargo/src/cli/mod.rs
crates/nargo/src/resolver.rs

Resolves # 
When running `nargo` in a subdirectory of a package whose `Nargo.toml` file contains a local dependency expressed as a relative path (e.g. `pkg = { path = "../../lib" }`), the dependency is parsed relative to the subdirectory, resoluting in an error of the form
```
Error: cannot find src directory in path ../../lib
Location:
crates/nargo/src/cli/mod.rs:69:5
```
This PR sets the current directory to the project root before executing `nargo` commands.
- A call to `std::env::set_current_dir` after determining the project root.

fix(nargo): Set current dir to package root before executing commands

---

crates/noirc_frontend/src/hir/type_check/expr.rs

Resolves #1028
If the user provides an incorrect number of fields, this error _is_ caught and issues during name resolution, however typechecking would later panic with an assert rather than continuing typechecking and skipping these malformed sections. Since the compiler should continue on error rather than abort, this behavior is incorrect and has been fixed so that the compiler no longer crashes.

fix: Avoid asserting in typechecker if struct field count is not correct

---

Cargo.lock
crates/nargo/Cargo.toml
crates/nargo/tests/hello_world.rs

Related to why https://github.com/noir-lang/noir/pull/1029 wasn't caught before nightly release
I've added an integration test which tests that, using the built binary, it is possible to complete the steps listed at https://noir-lang.org/getting_started/hello_world.html
Integration test added for performing the "hello world" example from the book.

chore(nargo): add integration test for "hello world" flow

---

crates/noirc_frontend/src/hir/def_collector/dc_crate.rs
crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir/type_check/mod.rs
crates/noirc_frontend/src/hir/type_check/stmt.rs

Resolves #1049 
Allows loops over any field values (not just comptime Fields) in unconstrained functions.
The diff is quite large to account for the change of the type checker from free functions to methods of a new TypeChecker struct (to hold the current_function id used to check if the current function is unconstrained).

feat: Allow non-comptime field indices in unconstrained functions

---

crates/nargo/tests/test_data/contracts/src/main.nr
crates/noirc_frontend/src/hir/resolution/errors.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs

No formal issue but resolves an issue in example 1.3 of the noir-aztec3-examples.
Allows 'secret' functions in contracts to take public parameters and have public return values.
With this the generated abi for the file looks like the following. (`...` marks omitted lines)
```json
{
"name": "PrivateToken",
"functions": {
"constructor": {
"func_type": "secret",
"function": {
"circuit": [
...
],
"abi": {
"parameters": [ ... ],
"param_witnesses": {
"call_context": [1, 2, 3, 4, 5, 6],
"contract_deployment_data": [7, 8, 9, 10, 11],
"value": [12],
"owner": [13, 14]
},
"return_type": {
"kind": "struct",
"fields": [...],
},
"return_witnesses": [15, 15, 15, 15, 15]
}
}
}
}
}
```
Once contract functions are documented, we'll need to also document that `secret` functions (the default) can use `pub` …

feat: Allow secret functions to use public parameters

---

crates/noirc_frontend/src/hir/def_collector/dc_crate.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/monomorphization/mod.rs
crates/noirc_frontend/src/parser/parser.rs

Resolves #439 
Allows non-integers such as structs and arrays to be used as globals, as long as they're initialized as constants. There is nothing verifying the sub-expressions for these are also constants currently though, so it is possible to have unexpected behavior (calling a function which tries to use the uninitialized global internally).
Attempting to use these in an array-length context will not crash the compiler, but will issue a somewhat confusing error that can be improved later.
We'll need to document that, in addition to integers, arbitrary structs and arrays can also be defined as globals. They must be initialized to struct or array literals however.
We should likely mention the sub-expressions within these struct/array literals should also be literals themselves even …

feat: Allow structs and arrays as globals

---

crates/noirc_frontend/src/monomorphization/ast.rs
crates/noirc_frontend/src/monomorphization/mod.rs

Resolves # 
Adds a `unconstrained: bool` field to `monomorphization::ast::Function` so that the SSA pass can check this to find whether a function is unconstrained or not.

chore: Add unconstrained to monomorphized functions

---

crates/noirc_evaluator/src/ssa/acir_gen/operations/return.rs

Resolves # 
Previously, the handling of Return instructions in ACIR-gen was incorrect since it would overwrite the "return" param_witness on each loop iteration. This fixes that by appending to it on each iteration instead.

fix!: Fix returning of structs in ACIR

---

crates/wasm/src/circuit.rs
crates/wasm/src/compile.rs
crates/wasm/src/lib.rs

Resolves https://github.com/noir-lang/noir/pull/1026#discussion_r1146040202
This PR updates the `wasm` crate to split up the functions into submodules.

chore: split wasm crate into submodules

---

crates/noirc_frontend/src/monomorphization/ast.rs
crates/noirc_frontend/src/monomorphization/mod.rs
crates/noirc_frontend/src/monomorphization/printer.rs

Resolves #none
Implements arrays of structs by converting them into structs of arrays during monomorphization.
This PR has 1 issue / TODO that I will create a separate issue for and fix in a later PR if this is merged. It is that during the SOA conversion, some elements of the Ast are cloned naively without regard as to whether cloning them may cause side-effects to be re-evaluated. This issue should be rare as it should only occur if e.g. array elements contain a `constrain` or mutate values, which they would need to contain a BlockExpression for.
We can remove the note in our documentation that one cannot define arrays of structs as it is now possible. Crucially however, we still cannot have arrays of arrays (nested arrays), or arrays of structs where the structs themselves contain …

feat: Implement arrays of structs

---

crates/noirc_frontend/src/hir/type_check/stmt.rs

Fixes a crash when attempting to type check a field that isn't present. This can happen if the user destructures a struct into a struct pattern in a let statement.

fix: crash when typechecking fields that don't exist

---

crates/noirc_evaluator/src/lib.rs
crates/noirc_evaluator/src/ssa/acir_gen/operations/return.rs

Adds proper support for https://github.com/noir-lang/acvm/pull/56
We weren't separating parameters and return values in order to be able to pass them to the `Circuit` without pulling them out of a temporary field on `param_witnesses`. This PR adds a `return_values` field to the evaluator so we can pass these through directly.

chore: handle public parameters and return values separately in evaluator

---

crates/nargo_cli/src/cli/check_cmd.rs

Resolves # 
Currently running `nargo check` on a new project generates the `Prover.toml` file as below
```toml
x = ""
y = "[]"
```
This isn't ideal as unless users remove the quotes around the array, they'll get the error message `Error: cannot parse a string toml type into Array { length: 2, typ: Field }`.
This PR updates `build_placeholder_input_map` so that we get the generated toml file
```toml
x = ""
y = []
```

feat(nargo): remove misleading quotes in generated `Prover.toml`

---

crates/nargo/Cargo.toml
crates/nargo/src/backends.rs

Resolves #1084 
I've updated the checks to match the feature flags which are in use.
I've also removed the default feature flag for the `nargo` package. This should be set in the `nargo_cli` crate (and by any direct consumers of `nargo`)

fix: correct test for mutually exclusive feature flags

---

Cargo.lock
crates/nargo/Cargo.toml
crates/nargo/src/lib.rs
crates/nargo_cli/Cargo.toml
crates/nargo_cli/src/backends.rs
crates/nargo_cli/src/cli/check_cmd.rs
crates/nargo_cli/src/cli/codegen_verifier_cmd.rs
crates/nargo_cli/src/cli/compile_cmd.rs
crates/nargo_cli/src/cli/execute_cmd.rs
crates/nargo_cli/src/cli/gates_cmd.rs
crates/nargo_cli/src/cli/preprocess_cmd.rs
crates/nargo_cli/src/cli/prove_cmd.rs
crates/nargo_cli/src/cli/test_cmd.rs
crates/nargo_cli/src/cli/verify_cmd.rs
crates/nargo_cli/src/lib.rs

Followup to https://github.com/noir-lang/noir/pull/1085#issuecomment-1494618926
This PR moves all logic related to selection of proving backends from `nargo` to `nargo_cli`. This is necessary as we'll be wanting to build multiple crates within the workspace with different backends which all use `nargo` so this must be generic (as otherwise it will have mutually exclusive feature flags set).

chore: move backends to `nargo_cli` crate

---

crates/noirc_frontend/src/graph/mod.rs

Resolves #119 
I've restricted the lint to only cover `CyclicDependenciesError` as this is the only instance of dead code. We should consolidate the crate graph and resolver code at some point at which we can remove this dead code.

chore: move `allow(dead_code)` to only cover `CyclicDependenciesError`

---

crates/nargo_cli/src/cli/mod.rs

Resolves [failing build acceptance test ](https://github.com/noir-lang/build-nargo/actions/runs/4605982988/jobs/8146517196?pr=20)
The CLI tool currently thinks it's called `nargo_cli` rather than `nargo` so I've manually set this value.

fix(nargo): correct name in CLI output from `nargo_cli` to `nargo`

---

crates/nargo_cli/src/cli/fs/keys.rs
crates/nargo_cli/src/cli/fs/program.rs
crates/nargo_cli/src/cli/preprocess_cmd.rs

Resolves https://github.com/noir-lang/noir/issues/870
We now use the faster `checksum_constraint_system` function over `hash_constraint_system` when preprocessing programs to generate their keys.
One important thing to note here is that it means that we'll be using a different hash function when saving programs to disk in comparison to the hash function we'll be using for contract functions in the A3 context. We'll need to ensure that we keep these separate. As part of that, I have updated any references to "hashes" to "checksums".

chore(nargo)!: use faster hash function for checking preprocessed keys

---

crates/nargo_cli/src/cli/check_cmd.rs

Resolves # 
Consider the program 
```
struct MyStruct {
d1: Field,
d2: [Field; 2],
}
fn main(a: Field, b: u32, c: [Field; 2], d: MyStruct, e: bool) {}
```
Currently this gets templated into `Prover.toml` by `nargo check` as 
```
a = ""
b = ""
c = []
d = ""
e = ""
```
This adds unnecessary friction as `d` is really a table and will need to be moved down to the bottom of the file and the user is responsible for adding all of its fields. This can lead to an annoying back and forth with `ABIError`s when trying to fill in this file.
To address this, we now template each `AbiType` recursively to produce
```
a = ""
b = ""
c = ["", ""]
e = ""
[d]
d1 = ""
d2 = ["", "", ""]
````
Users no longer have to rebuild their struct types or worry about lengths of array, just replace anywhere there's a `""` …

feat(nargo): add skeleton of composite types in template input tomls

---

crates/noirc_frontend/src/hir/def_collector/dc_crate.rs
crates/noirc_frontend/src/hir/def_collector/dc_mod.rs
crates/noirc_frontend/src/hir/def_map/item_scope.rs
crates/noirc_frontend/src/hir/def_map/mod.rs
crates/noirc_frontend/src/hir/def_map/module_data.rs
crates/noirc_frontend/src/hir/resolution/import.rs
crates/noirc_frontend/src/main.rs

…the module
Resolves #1111
Separates imported items in a module's scope from those originally defined within the module. Then we can use this separate list of items defined within the module to find all functions that should be part of the contract.
Previously we were using the module's scope which can include imported functions as well. I've separated these two constructs and made ModuleData more of an opaque wrapper to prevent this error in the future.
None
None

fix: compiler identifying imported functions as being part of a contract

---

crates/noirc_evaluator/src/lib.rs
crates/noirc_evaluator/src/ssa/ssa_gen.rs

Resolves # 
We don't actually require ownership of the witnesses in `abi_array` and `abi_struct` so I've changed these to take references which allows us to avoid some clones.

chore: borrow instead of cloning witness vectors in IR gen

---

Cargo.lock
crates/nargo/Cargo.toml
crates/nargo/src/errors.rs
crates/nargo/src/lib.rs
crates/nargo/src/ops/codegen_verifier.rs
crates/nargo/src/ops/execute.rs
crates/nargo/src/ops/mod.rs
crates/nargo/src/ops/preprocess.rs
crates/nargo/src/ops/prove.rs
crates/nargo/src/ops/verify.rs
crates/nargo_cli/src/cli/codegen_verifier_cmd.rs
crates/nargo_cli/src/cli/compile_cmd.rs
crates/nargo_cli/src/cli/execute_cmd.rs
crates/nargo_cli/src/cli/fs/keys.rs
crates/nargo_cli/src/cli/fs/program.rs
crates/nargo_cli/src/cli/preprocess_cmd.rs
crates/nargo_cli/src/cli/prove_cmd.rs
crates/nargo_cli/src/cli/test_cmd.rs
crates/nargo_cli/src/cli/verify_cmd.rs
crates/nargo_cli/src/errors.rs

Related to https://github.com/noir-lang/noir/issues/1063
This PR adds the concept of "ops" to `nargo` which are going to be the core operations which will be shared between the CLI and TS packages (e.g. compile, execute, prove, verify, preprocess, codegen_verifier and eventually test).
I've pushed this PR up a little early to unblock https://github.com/noir-lang/noir/pull/1126#discussion_r1164093059. Trying to migrate those two functions across to `nargo` would result in a huge number of merge conflicts, etc. (as well as needing a fair amount of boilerplate copied from this PR) where it would be simpler to merge this first and then fixup on that PR.

feat: import core logic in cli from `nargo` crate

---

crates/nargo_cli/tests/test_data/numeric_generics/src/main.nr
crates/noirc_frontend/src/hir/type_check/expr.rs

Resolves # 
In `aztec3-packages` we get this error on the vec type in the Noir contracts:
```
error: Integer cannot be used with type error
┌─ /Users/aztec/Documents/GitHub/aztec3-packages/yarn-project/noir-contracts/src/contracts/zk_token_contract/../noir-aztec3/src/types/vec.nr:18:19
│
18 │         constrain self.len as u64 < MaxLen as u64;
│                   -------------------------------
error: aborting due to 1 previous errors
```
This was due to a mismatched ordering when reporting errors in the type rules. I added a regression test in the `numeric_generics` test under the `nargo_cli`.

fix: Numeric generics with impls error

---

crates/noirc_driver/src/lib.rs

Related noir-lang/docs#86 
This flag is not limited to just tests but any time we execute the circuit, i.e. executing/proving. We should then remove references to testing in documentation.

chore: update documentation of `show_output` flag

---

Cargo.lock
crates/nargo_cli/Cargo.toml
crates/nargo_cli/src/backends.rs

Related to https://github.com/noir-lang/marlin_arkworks_backend/issues/8
I've removed the marlin backend it's using an extremely outdated interface and pulling in a version of ACVM which is multiple breaking releases behind. We shouldn't be "advertising" this feature if people can't activate this feature flag and have it work.
Once https://github.com/noir-lang/marlin_arkworks_backend/issues/8 has been resolved then we can re-add this optional dependency.

chore!: remove outdated arkworks backend

---

.github/workflows/release.yml

Resolves # 
This marks the GitHub Release that is produced by Release-Please as a "Pre-release" (see https://github.com/phated/phated/releases for an example).
Noirup and our various guides utilize the "latest" release because GitHub provides a handy redirect: https://github.com/noir-lang/noir/releases/latest and sometimes the docs and demos lag behind. This change allows the previous release to be marked as "latest" until we manually update the GitHub Release to be latest (such as when documentation is done).
Note: In the PR that [added this feature](https://github.com/googleapis/release-please/pull/1181) on Release-Please, they restricted it to 0.x.x versions, which would not work for our workflow after 1.0; however, I think this decision was arbitrary and I'll work with them to allow …

chore(ci): mark github releases as pre-release

---

Cargo.toml

I'm seeing that we've got a proper email inbox set up here: https://github.com/noir-lang/barretenberg-sys/blob/79f8ae5dbe95a3d35c145abbd455ee1105f7b8f8/Cargo.toml#L5
This PR updates Cargo.toml to reference this.

chore: update author email to point to `team@noir-lang.org`

---

crates/nargo_cli/src/cli/compile_cmd.rs

Resolves #1157 
This PR includes the contract name in the build artifact's file name to allow us to compile multiple contracts from the same crate.

fix(nargo): give contract artifacts unique names to prevent overwrites

---

crates/noirc_evaluator/src/ssa/acir_gen/operations/intrinsics.rs
crates/noirc_evaluator/src/ssa/builtin.rs
crates/noirc_evaluator/src/ssa/optimizations.rs

Adds builtins for read and write of public storage for A3.
- `StorageRead` takes a storage slot as a field, and returns its contents as a field 
- `StorageWrite` takes a storage slot as a field and a new value as a field, and returns the written value
Note that StorageWrite cannot be made to return void since [the acvm expects oracle calls to return _something_](https://github.com/noir-lang/acvm/blob/7352802ca8c4abc9be21ac4f88c8c6b7064d9650/acir/src/circuit/opcodes.rs#L190-L196).

feat: add storage access builtins for A3

---

crates/nargo_cli/tests/test_data/regression/src/main.nr
crates/noirc_evaluator/src/ssa/ssa_gen.rs

Resolves #1169
Set the proper predecessor block for IF joins
Test case added in regression integration test

fix(ssa): set correct predecessors of IF join

---

crates/noirc_frontend/src/hir/type_check/expr.rs

Resolves # 
The previous check for type checking unconstrained for loops erroneously always unified with a non-comptime Field which produced type errors when used with a comptime one.
This wasn't caught previously since numeric literals are polymorphically comptime and would just bind to CompTime::No previously. It would only trigger if using a variable which was explicitly declared with a comptime type like `let a: comptime Field = 2;`.
Fixes the above check by unifying against a polymorphically comptime field instead of a non-comptime one.

fix: allow comptime or non comptime fields in unconstrained for loops

---

crates/noirc_evaluator/src/lib.rs
crates/noirc_evaluator/src/ssa/acir_gen/operations/return.rs

Resolves #1174 
This PR switches the evaluator to track the witnesses for the return value in a `Vec<Witness>` rather than a `BTreeSet<Witness>`. While it's correct to store them as a set inside the `Circuit`, we rely on the ordering of these witnesses for proper ABI decoding and so we need to maintain this when we're constructing the ABI.
See #1174 for an example of this causing improper ABI decoding.

fix: maintain ordering of return value witnesses when constructing ABI

---

crates/nargo_cli/Cargo.toml
crates/nargo_cli/src/cli/mod.rs
crates/nargo_cli/tests/prove_and_verify.rs

Pulling out code from #1179 to separate it from a more controversial change.
This PR pulls out the code readability improvements from #1179 while maintaining the existing method of proving/verifying. We then get the benefits of this refactoring without increasing CI times.

chore: simplify setup code in `noir_integration` test

---

crates/nargo_cli/src/cli/codegen_verifier_cmd.rs
crates/nargo_cli/tests/codegen-verifier.rs

Resolves # 
Looks like we got a bit ahead of ourselves and started using `eth_contract_from_vk` against a commit of `aztec_backend` where that isn't implemented yet. If you run `nargo codegen-verifier` on v0.4.0 you get
```shell
$ nargo codegen-verifier
The application panicked (crashed).
Message:  not yet implemented: use `eth_contract_from_cs` for now
Location: /home/tom/.cargo/git/checkouts/aztec_backend-a697fb631cbad807/2617835/barretenberg_static_lib/src/acvm_interop/smart_contract.rs:10
This is a bug. Consider opening an issue at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```
This PR reverts to `eth_contract_from_cs` and adds an integration test that if you run `codegen-verifier` the command succeeds and you get *some* file created.
I haven't …

fix(nargo): restore `nargo codegen-verifier` functionality

---

crates/noirc_evaluator/src/ssa_refactor/dfg.rs
crates/noirc_evaluator/src/ssa_refactor/ir.rs
crates/noirc_evaluator/src/ssa_refactor/ir/extfunc.rs
crates/noirc_evaluator/src/ssa_refactor/ir/instruction.rs
crates/noirc_evaluator/src/ssa_refactor/ir/map.rs
crates/noirc_evaluator/src/ssa_refactor/ir/types.rs
crates/noirc_evaluator/src/ssa_refactor/ir/value.rs

Refactors a common pattern of having:
- `HashMap<MyStructId, MyStruct>` into a `SparseMap<MyStruct>`
- `Vec<MyStruct>` which also returns and is acccessed by unique Ids into a `DenseMap<MyStruct>`.
- Instead of having a different type for each Id type, there is now a single `Id<T>`. So for example a ValueId is now a `Id<Value>` or a "Id that can be used to retrieve a Value." Type aliases are provided to keep the familiar ValueId name though.
This is a PR for the SSA Refactoring only, it shouldn't cause any observable changes and only touches the ssa-refactor folder.

chore(ssa refactor): Add DenseMap and SparseMap types

---

crates/noirc_evaluator/src/ssa_refactor/ir/instruction.rs

`JmpIf` isn't sufficient for encoding block arguments for the fall through successor. It is also more convenient if block terminator instructions describe all successors, such that we do not have to infer fall throughs from some block ordering.

chore(ssa): Replace JmpIf with BrIf

---

.github/workflows/test.yml
flake.lock
flake.nix

Resolves # 
This adds cache logic to the Nix CI workflow. It uses a `cachix` binary store to load barretenberg & barretenberg.wasm and it exports all cargo dependencies from the Nix store after a successful run, which it can then re-use on subsequent runs.

chore(ci): add cache for Nix workflow

---

crates/noirc_evaluator/src/ssa_refactor/ir.rs
crates/noirc_evaluator/src/ssa_refactor/ir/basic_block.rs
crates/noirc_evaluator/src/ssa_refactor/ir/dfg.rs
crates/noirc_evaluator/src/ssa_refactor/ir/function.rs
crates/noirc_evaluator/src/ssa_refactor/ir/instruction.rs
crates/noirc_evaluator/src/ssa_refactor/ir/map.rs
crates/noirc_evaluator/src/ssa_refactor/ir/printer.rs
crates/noirc_evaluator/src/ssa_refactor/ir/types.rs
crates/noirc_evaluator/src/ssa_refactor/ssa_builder/function_builder.rs
crates/noirc_evaluator/src/ssa_refactor/ssa_gen/context.rs
crates/noirc_evaluator/src/ssa_refactor/ssa_gen/mod.rs

Resolves # 
Implements `Display` for `Function` to print out a representation of all of the function's instructions for debugging purposes.

chore(ssa refactor): Add debug printing for the new ssa ir

---

flake.nix

Resolves # 
This adds `RUST_BACKTRACE=1` to the nix environment. This means it will be set in any direnv shell and any nix commands run. This should help with debugging.

chore: add RUST_BACKTRACE environment variable to nix config

---

crates/noirc_evaluator/src/ssa_refactor/ir/dfg.rs
crates/noirc_evaluator/src/ssa_refactor/ir/instruction.rs
crates/noirc_evaluator/src/ssa_refactor/ir/types.rs
crates/noirc_evaluator/src/ssa_refactor/ir/value.rs
crates/noirc_evaluator/src/ssa_refactor/ssa_builder/function_builder.rs
crates/noirc_evaluator/src/ssa_refactor/ssa_gen/context.rs
crates/noirc_evaluator/src/ssa_refactor/ssa_gen/mod.rs
crates/noirc_evaluator/src/ssa_refactor/ssa_gen/value.rs

Resolves #1218 
Result types are already stored in results so I've updated the handling a bit to try to make the API easier to use and less reliant on getting the `ctrl_typevar` correct. Now the `ctrl_typevars` (plural) are only needed for Load, Call, and Intrinsic (although Intrinsic can likely be removed once it is implemented and each variant is known). `ctrl_typevars` is also now taken in as an option so it can be easily omitted. In case it is required but was not specified we panic instead of returning an empty Vec.

chore(ssa refactor): Update how instruction result types are retrieved

---

crates/noirc_evaluator/src/ssa_refactor/ir/cfg.rs
crates/noirc_evaluator/src/ssa_refactor/ir/constant.rs
crates/noirc_evaluator/src/ssa_refactor/ir/dfg.rs
crates/noirc_evaluator/src/ssa_refactor/ir/function.rs
crates/noirc_evaluator/src/ssa_refactor/ir/instruction.rs
crates/noirc_evaluator/src/ssa_refactor/ir/printer.rs
crates/noirc_evaluator/src/ssa_refactor/ssa_builder/function_builder.rs
crates/noirc_evaluator/src/ssa_refactor/ssa_gen/context.rs
crates/noirc_evaluator/src/ssa_refactor/ssa_gen/mod.rs
crates/noirc_evaluator/src/ssa_refactor/ssa_gen/value.rs
crates/noirc_frontend/src/monomorphization/ast.rs
crates/noirc_frontend/src/monomorphization/mod.rs

Resolves # 
Implements ssa-gen for a few more expression types

chore(ssa refactor): Implement ssa-gen for indexing, cast, constrain, if, unary

---

crates/noirc_evaluator/src/ssa_refactor/ssa_gen/context.rs
crates/noirc_evaluator/src/ssa_refactor/ssa_gen/mod.rs

Resolves # 
Implements ssa-gen for for loops

chore(ssa refactor): Implement for loops

---

crates/wasm/src/compile.rs

Resolves #1244
Adding the std library after all dependencies so all dependencies get the std lib.

fix(wasm): add std after dependencies

---

.github/workflows/release.yml

Resolves # 
This updates the release workflow to use the new workflow introduced in https://github.com/noir-lang/build-nargo/pull/24. It also simplifies the calls because the workflow completion triggers the 3 platform workflows itself.

chore(ci): Utilize new workflow to build binaries

---

crates/noirc_evaluator/src/ssa_refactor/ir.rs
crates/noirc_evaluator/src/ssa_refactor/ir/basic_block.rs
crates/noirc_evaluator/src/ssa_refactor/ir/dom.rs
crates/noirc_evaluator/src/ssa_refactor/ir/dom/post_order.rs
crates/noirc_evaluator/src/ssa_refactor/ir/post_order.rs
crates/noirc_evaluator/src/ssa_refactor/ssa_gen/program.rs

Resolves #1116
- Add `PostOrder` for calculating the post-order of a function reachable blocks
- Adds `DominatorTree` for querying one block's dominance over another
- Make finished `Ssa`'s function collection accessible so that the `FunctionBuilder` can be used in unit tests
Unit test for both of the above

feat(ssa refactor): Implement dominator tree

---

crates/noirc_evaluator/src/ssa_refactor.rs
crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs

Resolves # 
Adds an entry point for the (not yet started) acir-gen pass for the new SSA IR. The entry point is `Ssa::into_acir`, and it is called within the new entry point function `optitmize_into_acir` which converts Program -> Ssa -> (optimizations) -> Acir.

chore(ssa refactor): Add entry point for acir gen pass

---

crates/nargo_cli/tests/test_data/array_dynamic/src/main.nr

chore(tests): use assert instead of constrain

---

crates/nargo_cli/src/cli/mod.rs
crates/noirc_driver/src/lib.rs
crates/noirc_evaluator/src/lib.rs
crates/noirc_evaluator/src/ssa_refactor.rs

feat(ssa refactor): experimental-ssa compiler flag

---

.github/labeler.yml

The `doc needed` labeling CI was able to detect `- [x]` but not `- [X]` documentation checkbox on PRs. (See https://github.com/noir-lang/noir/pull/1271 as an example.)
This PR fixes the labeling CI to label a PR when either a `- [x]` or `- [X]` documentation checkbox is detected.
PR in testing repo for reference: https://github.com/noir-lang-test/noir/pull/9

fix(ci): Labeling `doc needed` PRs with uppercase checkbox `- [X]`

---

crates/noirc_driver/src/contract.rs
crates/wasm/src/compile.rs

Resolves #1280
Updated the wasm package to serialize the vector of CompiledContract instead, and add annotations in CompiledContract to serialize using the serialize_circuit fn to get the expected representation of the bytecode.

feat(wasm): improved serialization of contracts in wasm

---

crates/noirc_evaluator/src/ssa/acir_gen/operations/sort.rs
crates/noirc_evaluator/src/ssa_refactor/ir/printer.rs
crates/noirc_frontend/src/hir_def/types.rs

Related to https://github.com/noir-lang/noir/issues/679.
- updated the function signature to use slices instead of a reference to a vector.
- solved the clippy lint `uninlined_format_args`
N/A
N/A

chore: replace usage of `&Vec<T>` with `&[T]` in `noirc_evaluator`

---

crates/noirc_frontend/src/hir/type_check/stmt.rs

Resolves #1315 
Fixes an issue where we forgot to call `.follow_bindings()` before matching on a type to see if it was a struct, tuple, or neither. This led to the issue described in #1315 where the compiler did not see the type as a struct and thus thought there was no field of the given name.
None
None

fix: Fix struct or tuple field assignment failing with generics

---

crates/nargo_cli/tests/test_data/tuples/src/main.nr
crates/noirc_driver/src/contract.rs
crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir/type_check/stmt.rs
crates/noirc_frontend/src/parser/parser.rs

Resolves #1309 
A parser bug parsing fields using `ident()` instead of `field_name()` (which is an ident or integer literal) lead to assignment to tuple fields not being possible. This was overlooked before, as the relevant code to handle tuple-field assignments was not in the type checker either. To fix this I've merged the code that handles tuple field assignments and tuple field access (a normal a.b expression not in an LValue context) so that this will not happen again. I've also slightly improved the error message if a user accesses a tuple field that is out of bounds.

fix: Assigning to tuple fields

---

crates/noirc_evaluator/src/ssa_refactor/ssa_gen/mod.rs

Resolves # 
Adds documentation comments with examples to some functions in the SSA-gen pass of the SSA refactoring. Particular attention was payed to codegen_if and codegen_for which are the only functions which insert new blocks.

chore(ssa refactor): Document some SSA-gen functions

---

crates/nargo_cli/tests/test_data/generics/src/main.nr
crates/noirc_driver/src/contract.rs
crates/noirc_frontend/src/lexer/lexer.rs
crates/noirc_frontend/src/parser/errors.rs
crates/noirc_frontend/src/parser/parser.rs

Resolves #1316
Generics always expect to end with a `Token::Greater`, however nested generics would use the syntax `A<B<T>>` where the final token(s) would be a `Token::ShiftRight` rather than two separate greater-than tokens.
Changing the type parser to also handle right shifts would be difficult as the shift would have to terminate two levels of nesting in the recursive parser. I opted instead for the other route of changing the lexer to always issue two greater-than tokens rather than combining them. From there I needed to add a few special cases in expression operators and the assign-operator shorthands.
Added a small regression test line in the generics test.

fix: Parsing nested generics

---

crates/noirc_evaluator/src/ssa_refactor/opt/inlining.rs

Resolves # 
I found this bug while working on loop unrolling: we never call `translate_value` on function arguments before during inlining which could cause the functions to be called with the incorrect values. This wasn't obvious because ValueIds are only valid for the function they're created in, so the untranslated ones were being used outside of their function and were referring to different values than they were meant to.

chore(ssa refactor): Fix inlining bug

---

Cargo.lock
Cargo.toml
crates/nargo/Cargo.toml
crates/nargo/src/ops/codegen_verifier.rs
crates/nargo/src/ops/preprocess.rs
crates/nargo/src/ops/prove.rs
crates/nargo/src/ops/verify.rs
crates/nargo_cli/Cargo.toml
crates/nargo_cli/src/cli/check_cmd.rs
crates/nargo_cli/src/cli/codegen_verifier_cmd.rs
crates/nargo_cli/src/cli/compile_cmd.rs
crates/nargo_cli/src/cli/execute_cmd.rs
crates/nargo_cli/src/cli/fs/inputs.rs
crates/nargo_cli/src/cli/fs/mod.rs
crates/nargo_cli/src/cli/fs/program.rs
crates/nargo_cli/src/cli/fs/proof.rs
crates/nargo_cli/src/cli/fs/witness.rs
crates/nargo_cli/src/cli/gates_cmd.rs
crates/nargo_cli/src/cli/mod.rs
crates/nargo_cli/src/cli/new_cmd.rs
crates/nargo_cli/src/cli/print_acir_cmd.rs
crates/nargo_cli/src/cli/prove_cmd.rs
crates/nargo_cli/src/cli/test_cmd.rs
crates/nargo_cli/src/cli/verify_cmd.rs
crates/nargo_cli/src/errors.rs

Resolves #1301 
This updates the project to ACVM 0.11.0
This is the version of ACVM that introduced the Result return type to many of the functions on the Backend trait. This allows us to better surface errors from backends—and as such, aztec_backend has been updated to return results for almost all errors (the only unwraps remaining are in the merkle implementation).
This version of ACVM also introduced keccak into the constraint system, so we needed to upgrade barretenberg also. This may cause the same OOM error that the other Keccak PR is exhibiting.

chore!: Update to acvm 0.11.0

---

crates/nargo_cli/src/cli/check_cmd.rs
crates/nargo_cli/src/cli/compile_cmd.rs
crates/nargo_cli/src/cli/mod.rs
crates/nargo_cli/src/cli/test_cmd.rs
crates/nargo_cli/src/resolver.rs
crates/noirc_driver/src/lib.rs
crates/noirc_driver/src/main.rs
crates/noirc_frontend/src/hir/mod.rs
crates/noirc_frontend/src/main.rs
crates/noirc_frontend/src/node_interner.rs
crates/wasm/src/compile.rs

Related to #1102 as it makes the backend dependency explicit.
This PR makes the Noir compiler frontend's dependency on a backend explicit as we now pass in a closure to describe which opcodes it supports to use when dealing with foreign functions.
For now this still uses the default support function but should be updated once https://github.com/noir-lang/acvm/pull/273 makes its way into this repository. Once this is done then we can remove those functions for the 0.13.0 release of ACVM.

feat: pass in closure to `Driver` to signal backend opcode support

---

noir_stdlib/src/ecdsa_secp256k1.nr

Motivated by slack messages
This updates the argument name in the `verify_signature` function to specify that it receives the hash of the message rather than the message itself.

chore: clarify that `verify_signature` takes a hashed message

---

crates/nargo_cli/tests/test_data/2_div/src/main.nr
crates/noirc_evaluator/src/ssa/node.rs

Resolves #1346
Resolves #774 
Use the operands type during modulo simplification
regression test added to 2_div

fix: Fix modulo operator for comptime values

---

crates/noirc_evaluator/src/ssa_refactor/ir/basic_block.rs
crates/noirc_evaluator/src/ssa_refactor/ir/dfg.rs
crates/noirc_evaluator/src/ssa_refactor/opt/mem2reg.rs
crates/noirc_evaluator/src/ssa_refactor/opt/mod.rs
crates/noirc_evaluator/src/ssa_refactor/ssa_gen/program.rs

feat(ssa refactor): mem2reg opt pass

---

crates/noirc_driver/src/lib.rs
crates/noirc_frontend/src/ast/function.rs
crates/noirc_frontend/src/hir/mod.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/lexer/token.rs
crates/noirc_frontend/src/main.rs
crates/noirc_frontend/src/node_interner.rs
noir_stdlib/src/merkle.nr
noir_stdlib/src/sha256.nr

Removes blocker for #1102 
This PR removes the concept of fallback functions inside the stdlib instead the blackbox function opcodes will always be generated.
This can be reintroduced in future using some form of https://github.com/noir-lang/noir/issues/1258#issuecomment-1529134163 or alternatively a fallback can be implemented inside ACVM.

feat!: remove concept of noir fallbacks for foreign functions

---

noir_stdlib/src/eddsa.nr

Related to #1313 
This PR resolves an error that occurs when generating a proof involving EdDSA signature verification: Calling `eddsa_poseidon_verify` leads to an error on the following example:
```rust
use dep::std::eddsa::eddsa_poseidon_verify;
fn main(data: [Field; 6])
{
assert(eddsa_poseidon_verify(data[0], data[1], data[2], data[3], data[4], data[5]));
}
#[test]
fn test_main()
{
let data = [0x1f3581c1eb058355ad574689b0bf37ab4e02433492eac1fbcd9fe5ce9272099e,0x0f72436cb679e0fa77342a92342d271bdd869ac14ce1f13a2afcccc5b6f75714,0x03ec6779f0250bb9852b3bc71cfb3dbb21420294fe8ce16ac6469049171b987e, 0x0b317e5deb2cbbc171f7c70ee5f6634563bb3a23f67d001ed9750380bbaf60cf,0x1cad3257ef27851ebd24587ff64230f3be41dfac3e8170878116190527448373,0x1d7ecd14bf6ec1bf60b655ef74e99bc874c76d179b1adc9a81bb55dd4bbacf …
```

fix(stdlib): Workaround for Field comparison error in EdDSA signature verification

---

.github/ISSUE_TEMPLATE/feature_request.yml

Updating the feature request template:
- Add a "Would you like to submit a PR for this Issue?" section to encourage external contributions
- Remove project board checkbox
- Minor word & formatting changes
Try it out: https://github.com/noir-lang-test/noir/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.yml
Demo Issue: https://github.com/noir-lang-test/noir/issues/14
Once this is merged, I'll create a PR to update the template in noir-lang/.github accordingly.

chore(github): Update GitHub Feature Request Template

---

crates/noirc_evaluator/src/ssa_refactor/ir/function.rs
crates/noirc_evaluator/src/ssa_refactor/opt/mem2reg.rs

Resolves # 
Previously the mem2reg pass relied on only operating on a single-block program so that it could remove stores properly. I've edited it so that it only removes stores after checking if the program is only one block. With this and some small changes to the entry it should now work on any program. I've also added a test with 2 blocks to test this.

chore(ssa refactor): Update mem2reg pass to work with multiple functions and blocks

---

.github/ISSUE_TEMPLATE/bug_report.yml

Updating the bug report template:
- Add a "Would you like to submit a PR for this Issue?" section to encourage external contributions
- Remove project board checkbox
- Minor word & formatting changes
Try it out: https://github.com/noir-lang-test/noir/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml
Demo Issue: https://github.com/noir-lang-test/noir/issues/13
Once this is merged, I'll create a PR to update the template in noir-lang/.github (minus the "Environment" section) accordingly.

chore(github): Update GitHub Bug Report Template

---

.github/pull_request_template.md

Updating the PR template:
- Remove "Dependency additions / changes" and "Test additions / changes" sections, which should be covered in the "Summary" section
- Add "Example" section
- Add followup options when PR requires documentation updates
- Trim checklist
- Minor word & formatting changes
Demo PR: https://github.com/noir-lang-test/noir/pull/12
Once this is merged, I'll create a PR to update the template in noir-lang/.github accordingly.

chore(github): Update GitHub Pull Request Template

---

crates/nargo_cli/src/cli/check_cmd.rs
crates/nargo_cli/src/cli/mod.rs
crates/noirc_driver/src/lib.rs
crates/noirc_errors/src/reporter.rs

Resolves #1382
Allows warnings by default. The old default behavior of treating warnings like errors is now opt-in with the `--deny-warnings` flag. The old `--allow-warnings` flag has been removed as it is no longer useful.
We should remove references to `--allow-warnings` in the documentation and add references to `--deny-warnings`. Additionally, we should mention that unused variables are warnings rather than errors if we mention them at all. Deprecated constructs like `constrain` do not need to be mentioned.

feat: Allow warnings by default

---

crates/noirc_evaluator/src/ssa_refactor/ir/cfg.rs

Loop unrolling was crashing on single block programs due the cfg not holding a node for the entry block (which had no edges)
```
Message:  ICE: Attempted to iterate predecessors of block not found within cfg.
Location: crates/noirc_evaluator/src/ssa_refactor/ir/cfg.rs:102
...
18: noirc_evaluator::ssa_refactor::ir::cfg::ControlFlowGraph::predecessors::h40675d9252c86030
at /Users/aztec/Documents/GitHub/noir-lang/noir/crates/noirc_evaluator/src/ssa_refactor/ir/cfg.rs:100
19: noirc_evaluator::ssa_refactor::opt::unrolling::find_all_loops::h750f7171170cccd7
```
Init the cfg with an empty node for the entry block

fix(ssa refactor): safe to query cfg for single block programs

---

crates/noirc_evaluator/src/ssa_refactor/ssa_gen/mod.rs

Fixes a problem where the experimental ssa IR would crash while compiling nested if statements.
Although the crash was during function inlining, the error was actually the ssa-gen pass generated malformed SSA IR that was later given as input to inlining. The issue was when codegening if statements we would compile the then branch, then switch to compile the else branch, then switch back to the then branch to set its terminator. This is invalid if the then branch itself contains several blocks as we'd be setting the terminator of the first block rather than the final block. This caused nested if statements to be essentially erased from the program, but it was still possible to refer to their block arguments from blocks that are unreachable, which triggers the assert during function …

fix(ssa refactor): Fix ssa-gen of nested ifs

---

crates/nargo_cli/tests/test_data/merkle_insert/src/main.nr
crates/nargo_cli/tests/test_data/simple_shield/src/main.nr
noir_stdlib/src/merkle.nr

Related to #1258 and https://github.com/noir-lang/acvm/issues/295
This PR removes the unnecessary functions from the `merkle` module in the stdlib (`check_membership` and `compute_root_from_leaf`).
We no longer use the black box version of `compute_merkle_root` in preparation for the opcode being removed and just use the noir implementation (which has been shown to be more efficient anyway). `compute_root_from_leaf` is then removed/renamed to `compute_merkle_root`

chore(stdlib)!: remove unnecessary merkle functions from stdlib

---

crates/noirc_evaluator/src/ssa_refactor.rs

Until #1394 is merged, we need to include the optimization and transformation pass after we have generated the ACIR bytecode.
Resolves 
Before:
```
```
After:
```
```

chore(ssa refactor): Add optimization and transformation pass to Circuit

---

.github/workflows/test.yml
crates/noirc_driver/src/main.rs
flake.nix

Resolves #1303 
This updates the flake to enable better caching. When building the dependencies, we were injecting the `GIT_COMMIT` and `GIT_DIRTY` variables, which made the dependencies rebuild from scratch on each commit. It also reworks the flake to have better delineation between native backend and wamer backend build targets (this will avoid needing the bb.wasm file during checks).

chore(nix): Fix dependency caching

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs

Resolves 
Automatically add range constraints for integers found in the parameters to main
```rs
fn main(x : u8) -> pub u8 {
x
}
```
produces:
```
current witness index : 2
public parameters indices : []
return value indices : [1]
BLACKBOX::RANGE [(_1, num_bits: 8)] [ ]
```

chore(ssa refactor): range constraints for integer params to main

---

README.md

Resolves #1199 
This removes the documentation from the readme about building from source and instead links to that documentation on the website.
I also removed the information about nargo because that's on the website too and linked higher up in the readme.
Depends upon my changes in noir-lang/docs#170

chore(docs): Replace instructions that exist on the website with link

---

crates/nargo_cli/tests/test_data_ssa_refactor/blackbox_func_simple_call/src/main.nr
crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/acir_variable.rs
crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/memory.rs
crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs

ACIR gen didn't support array arguments to black boxes
Resolves 
`acir_gen/mod` Forwards blackbox arguments to `acir_variable` as a mix of `AcirVar` and `ArrayIds`. `acir_variable` they take responsibility for rationalising the arguments
```rs
use dep::std;
fn main(x: Field) {
let _p1 = std::scalar_mul::fixed_base(x);
let _p2 = std::hash::pedersen([x]);
}
```
compiles to
```
current witness index : 6
public parameters indices : []
return value indices : []
BLACKBOX::FIXED_BASE_SCALAR_MUL [(_1, num_bits: 254)] [ _2, _3]
BLACKBOX::PEDERSEN [(_1, num_bits: 254)] [ _4, _5]
```

chore(ssa refactor): blackbox array arg support

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/acir_variable.rs
crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/generated_acir.rs

Unbreaks #1475 by removing AES and ComputeMerkleRoot, and by handling pedersen domain separators.

chore(ssa refactor): Remove dead blackboxes and handle pedersen domain separator

---

.github/workflows/test.yml

Resolves 
This separates the name of the test from the runner being used. Previously, when @kevaundray would change the runner to ubuntu-large, he'd need to modify the required checks.

chore(ci): Separate test name from runner

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/generated_acir.rs

Resolves #1524 
This PR sets out to prevent extra witnesses by checking to see if we can unwrap the expression into a witness before creating a new one and constraining its value to the expression.
Before:
```
```
After:
```
```

chore(ssa refactor): Rename `expression_to_witness` to `create_witness_for_expression` to make purpose clearer.

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/acir_variable.rs
crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs

An example of what #1529 could look like
Resolves 
Before:
```
```
After:
```
```

chore(ssa refactor): Use types from ssa ir directly in acir context

---

crates/noirc_frontend/src/ast/statement.rs
crates/noirc_frontend/src/parser/mod.rs
crates/noirc_frontend/src/parser/parser.rs

Implement multiple item imports in use statement: `use foo::{bar, hello}`.
Added support for multiple item imports in the use statement, allowing for more flexible and targeted module imports. Updated the parser, AST, and desugaring logic to handle the new syntax.

feat: multiple item imports in use statement

---

Cargo.lock
Cargo.toml
crates/wasm/Cargo.toml
crates/wasm/src/lib.rs

This version reverted a fix that was causing Noir to fail See #1509 and adds a fix so that acvm does not panic when it sees a Brillig opcode
Resolves 
Before:
```
```
After:
```
```

chore: use ACVM 0.13.3

---

crates/nargo_cli/build.rs

This will re-rerun the build.rs script if the test files have changed.
Its main usecase will be:
- If a new test has been added
- If the directory name for a test has changed
Resolves 
Before:
```
```
After:
```
```

chore: Re-run build.rs if the tests have changed

---

crates/noirc_frontend/src/hir/type_check/expr.rs

`sort_by_key` -> `sort_by_key_ref` to avoid an extraneous clone

chore: `sort_by_key` -> `sort_by_key_ref` to avoid an extraneous clone

---

crates/noirc_evaluator/src/brillig/brillig_gen.rs

This tries to clean up that logic a bit by encapsulating the differences in representation by SSA and Brillig.
Resolves 
Before:
```
```
After:
```
```

chore(brillig): Clean up handling of Binary operations

---

crates/nargo_cli/src/cli/execute_cmd.rs
crates/nargo_cli/src/cli/prove_cmd.rs
crates/nargo_cli/src/cli/verify_cmd.rs

A short modification of `nargo_cli` to allow the user to specify which `.toml` file to use when generating a proof instead of being forced to use `Prover.toml`.
The user had no choice but to use `Prover.toml` when generating a proof.
This is leading to race conditions when running forge tests (which run in parallel), in particular when these tests use on-the-fly proof generation.
Allows the user to optionnally specify which `.toml` file to use with the `-p` or `--prover-name` flag.
Before:
```
nargo prove p
```
After:
```
nargo prove -p OtherProver pp 
```

feat(nargo): Allow user-specified file for prover inputs instead of `Prover.toml`

---

crates/noirc_evaluator/src/ssa_refactor.rs
crates/noirc_evaluator/src/ssa_refactor/opt/constant_folding.rs
crates/noirc_evaluator/src/ssa_refactor/opt/mod.rs

Normally constant folding is performed automatically when instructions are inserted via `Instruction::simplify`. A manual pass can, however, become necessary after `DataFlowGraph::set_value` or `DataFlowGraph::set_value_from_id` are called and enable an instruction dependent on the updated value to be simplified.
This pass is added since it was used in a test case for the immutable arrays PR.
Before:
```
```
After:
```
```

chore(ssa refactor): Add constant folding pass

---

crates/noirc_evaluator/src/ssa_refactor/ir/dfg.rs

Bad type information was used when creating a constant that matched a previously cached constant without considering its type
Cache constants by both numeric value and type
```rs
fn main(x: u2) -> pub u2 {
0 - x
}
```
Before:
```
Initial SSA:
fn main f0 {
b0(v0: u2):
v2 = sub unit 0, v0
return v2
}
```
After:
```
Initial SSA:
fn main f0 {
b0(v0: u2):
v2 = sub u2 0, v0
return v2
}
```

fix(ssa refactor): fix bad constant type caching

---

Cargo.lock
Cargo.toml
crates/nargo/src/ops/prove.rs
crates/nargo/src/ops/verify.rs
crates/nargo_cli/Cargo.toml
crates/noirc_evaluator/src/ssa/acir_gen/operations/intrinsics.rs
crates/noirc_evaluator/src/ssa/builtin.rs
crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/generated_acir.rs
flake.lock
noir_stdlib/src/lib.nr

ACVM 0.14.0 includes the RecursiveAggregation opcode, which needs to be handled in ACIR gen. This update is needed to match up to the most recent commit in the [acvm-backend-barretenberg](https://github.com/AztecProtocol/barretenberg/tree/acvm-backend-barretenberg) branch of barretenberg. That temporary branch on barretenberg aims to stay in-line with the acir format used by bb.js and barretenberg master
Resolves 
Before:
```
```
After:
```
```

feat!: Update to acvm 0.14.0

---

Cargo.lock
crates/nargo_cli/Cargo.toml
crates/nargo_cli/src/cli/check_cmd.rs
crates/nargo_cli/src/cli/test_cmd.rs
crates/noirc_driver/Cargo.toml
crates/noirc_driver/src/lib.rs
crates/noirc_errors/Cargo.toml
crates/noirc_errors/src/lib.rs
crates/noirc_errors/src/reporter.rs
crates/noirc_evaluator/src/errors.rs
crates/wasm/src/compile.rs

Resolves #1537 
This refactors `noirc_driver` functions to return `Vec<FileDiagnostic>` if there is a problem compiling. The error reporter calls are then moved into `nargo_cli` since that is the only place we'd want them reported on stderr.
These changes make it possible for the LSP server to compile a file and send diagnostics back to the client (ref #1584).
I wasn't super happy to return non-Error types in the `Err` of the result, but I also don't think that these make sense to be an error, since we have to use a custom reporter to display them. I'm open to suggestions on how to clean this up.
Additional work:
* Added some `impl From` because it made converting between diagnostics/RuntimeError nicer.
* Removed `try_vecmap` because it bails at the first error, but we want to collect all …

fix(noirc_driver): Move error printing into nargo

---

crates/noirc_evaluator/src/ssa_refactor/opt/constant_folding.rs

If any loops are still present in the program, constant folding in the ssa refactor would loop forever since the visited block list was never updated.
Adds the visited block to the visited block list
Before:
```
```
After:
```
```

fix(ssa refactor): Fix constant folding looping forever

---

crates/noirc_evaluator/src/ssa_refactor/ssa_gen/mod.rs
crates/noirc_frontend/src/hir/type_check/expr.rs

This means that for loop ranges can be either a Field or an integer. Currently we only allow Field. 
Resolves 
Before:
```
```
After:
```
```

feat: Make for-loop range be a polymorphic integer instead of just Field in unconstrained functions

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/generated_acir.rs

Jointly done with @guipublic 
Resolves 
Before:
```
```
After:
```
```

chore(ssa refactor): Add more documentation for truncation 

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs
crates/noirc_evaluator/src/ssa_refactor/ir/dfg.rs
crates/noirc_evaluator/src/ssa_refactor/ir/printer.rs
crates/noirc_evaluator/src/ssa_refactor/opt/constant_folding.rs
crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs
crates/noirc_evaluator/src/ssa_refactor/opt/inlining.rs
crates/noirc_evaluator/src/ssa_refactor/opt/unrolling.rs

Expands the HashMap solution of the existing PR to resolve any updated ValueIds in every pass instead of just the SSA printer.
Resolves #1451
Before:
```
```
After:
```
```

fix(ssa refactor): Expand PR #1535 to resolve ValueIds in all SSA passes

---

Cargo.lock
Cargo.toml
crates/fm/src/file_map.rs

Resolves 
This updates the codespan dependencies to v0.11.x, which is needed to make our FileManager implementation work with the `codespan-lsp` crate.

chore: Upgrade codespan dependencies

---

crates/noirc_evaluator/src/ssa_refactor/ir/instruction.rs

This was a small issue I saw while testing `main_bool_arg` where when an Eq or Lt are simplified from known constants, the result was the operand type rather than bool. This later prevented optimizing the `not` instruction afterward.
Before:
```
```
After:
```
```

fix(ssa refactor): Change the result of simplifying Eq and Lt to bool

---

crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs

Resolves #1420
Adds a small check to flatten_cfg to avoid inlining a branch if the branch start matches the branch end.
Before:
```
```
After:
```
```

fix(ssa refactor): Fix flatten_cfg for ifs with no else

---

crates/noirc_evaluator/src/ssa_refactor/ir/dfg.rs
crates/noirc_evaluator/src/ssa_refactor/ir/instruction.rs
crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs

The lack of these calls was causing some instructions to fail to simplify.
Before:
```
```
After:
```
```

fix(ssa refactor): Add missing calls to resolve in Instruction::simplify

---

crates/noirc_abi/src/input_parser/json.rs
crates/noirc_abi/src/input_parser/toml.rs
crates/noirc_abi/src/lib.rs

Reduces diff for #1651 
In `noirc_abi` we often require some knowledge about the value being used as well as the expected type which it is supposed to be. We currently handle this by using nested match statements however this is a little unwieldy.
This PR replaces these with a single level match statement over a tuple of (value, type).

chore: replace nested matches in `noirc_abi`

---

.github/pull_request_template.md

The "Example" section is not commonly applicable to PRs and can be distracting.
This PR removes the section and adds a minor reminder in the template on supplementing examples whenever applicable.

chore(github): Remove PR template's example section

---

crates/noirc_evaluator/src/ssa_refactor/opt/inlining.rs

The change to add handling for brillig functions changed `failed_to_inline_a_function` to be true whenever a function failed to inline. We want this not to be set if the function we found is an intrinsic since those do not need to be inlined and added a comment since this is otherwise a subtle difference.
Fixes #1659 
Before:
```
```
After:
```
```

fix(ssa refactor): Fix failed_to_inline_a_function being set for intrinsics

---

crates/noirc_evaluator/src/ssa_refactor/opt/die.rs

The Dead Instruction Elimination (DIE) pass was removing the enable_side_effects instructions previously as they had no result values, and thus all results were unused. This is problematic because these instructions are side-effectful so we want them to stay around.
Before:
```
```
After:
```
```

fix(ssa refactor): Do not remove enable_side_effects instructions in die pass

---

crates/nargo_cli/src/cli/check_cmd.rs
crates/nargo_cli/src/cli/compile_cmd.rs
crates/nargo_cli/src/cli/mod.rs
crates/nargo_cli/src/cli/test_cmd.rs
crates/nargo_cli/src/errors.rs
crates/noirc_driver/src/lib.rs
crates/noirc_errors/src/reporter.rs
crates/noirc_evaluator/src/ssa_refactor/opt/inlining.rs
crates/wasm/src/compile.rs

Fixes an issue where if there are any compiler errors or warnings Nargo would map them into a CompilationError without reporting them first, leading to no errors being reported.
Resolves #1645

fix: Fix nargo not showing compiler errors or warnings

---

crates/noirc_evaluator/src/ssa_refactor/ir/instruction.rs
crates/noirc_evaluator/src/ssa_refactor/opt/unrolling.rs

Resolves #1650 
Fixes an issue causing loop unrolling to overflow the stack. Note that this does not fix 9_conditional completely since it runs into issues with the flatten_cfg pass. I believe this may be related to #1420.
Before:
```
```
After:
```
```

fix(ssa refactor): Fix stack overflow during loop unrolling

---

crates/noirc_evaluator/src/ssa_refactor/opt/inlining.rs
crates/noirc_evaluator/src/ssa_refactor/ssa_gen/context.rs

Resolves #1625
Implements array equality in ssa-gen. This way we should not need a separate pass in brillig.
We could still improve this code-gen with, e.g. an early exit if any `eq` returns false but I elected for the more straightforward approach for now since this code is temporary.

fix(ssa refactor): Implement array equality in SSA-gen

---

crates/nargo/src/artifacts/contract.rs
crates/nargo/src/ops/preprocess.rs
crates/nargo_cli/src/cli/compile_cmd.rs

Variation of #1709 that removes the pk / vk from noir contracts entirely
Resolves

fix(aztec3-hacky): remove pk / vk verbatim

---

crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir/type_check/mod.rs
crates/noirc_frontend/src/node_interner.rs

The current implementation of the node interner in the codebase appears to be handling multiple responsibilities and exhibiting signs of complexity.

chore: move `delayed_type_checks` field from `NodeInterner` to `TypeChecker`

---

crates/noirc_frontend/src/hir/resolution/import.rs

Resolves #1718 
This resolves a panic in dependency resolution. When I make this change, I can get error diagnostics for unresolved deps (and the rest of the file) because it no longer crashes the LSP.

fix(frontend): Avoid panic if dependency cannot be resolved

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs
crates/noirc_evaluator/src/ssa_refactor/ir.rs
crates/noirc_evaluator/src/ssa_refactor/ir/function_inserter.rs
crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs
crates/noirc_evaluator/src/ssa_refactor/opt/unrolling.rs

Resolves #1688 but at what cost? I've spammed `.clone()`s everywhere due to the function for mapping ValueIds now requiring an `&mut self`. I'm not satisfied with this approach as a result. I've tried replacing each with the set_value_from_id approach but it caused bugs in loop unrolling presumably from setting the same valueids on each loop iteration.

fix(ssa refactor): Fix array elements not being mapped to new values

---

.github/workflows/test.yml
.vscode/settings.json

Resolves 
According to https://github.com/cachix/install-nix-action/issues/183, the nix github action doesn't fail on macos-13. Hopefully the stops our CI from flaking on mac.
I also updated the workspace settings to ensure the workflows are validated correctly by the yaml plugin.

chore(ci): Run on macos-13 to avoid nix failure

---

crates/noirc_evaluator/src/brillig/brillig_gen.rs
crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
crates/noirc_evaluator/src/brillig/brillig_gen/brillig_fn.rs
crates/noirc_evaluator/src/brillig/brillig_ir.rs
crates/noirc_evaluator/src/brillig/brillig_ir/registers.rs

Incremental towards https://github.com/noir-lang/noir/issues/1720

chore(brillig): Add a register abstraction

---

Cargo.lock
Cargo.toml
crates/lsp/Cargo.toml
crates/lsp/src/lib.rs
crates/nargo_cli/src/cli/lsp_cmd.rs
crates/noirc_errors/src/reporter.rs

Resolves #1584 
This adds diagnostic publishing to the LSP. We decided to only run the diagnostic check on file save and then we perform the "push" diagnostic pattern. This is due to the compiler not being built to operate in "pull" diagnostic mode since the client can request them at any time with source code provided; however, the compiler expects a filesystem graph and builds it from scratch. We also decided to only run this on save because "file change" notifications can come in quicker than we can compile them.
I need to create some follow up issues related to TODOs before I move this out of draft.

feat(lsp): Publish diagnostics on file save

---

.github/workflows/test.yml

Resolves 
This `install-nix-action` maintainer quickly put together a fix for the macos issues and released v22. This updates the action and restores the `macos-latest` runner so we aren't using the beta macos runner.

chore(ci): Upgrade install-nix-action and restore macos-latest runner

---

crates/noirc_evaluator/src/ssa_refactor/opt/mem2reg.rs

Resolves GH-1756
The existing test for whether or not it is safe to remove store instructions is sufficient in the presence of unconstrained functions.
This PR generalises store instruction removal such that it can be done safely regardless of the use case. This is done by amassing a set of all protected allocations across all blocks, which is subsequently queried when removing stores in each individual block.

chore(ssa refactor): generalize store instruction removal

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/acir_variable.rs
crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs

ACIR gen assumed `NOT` to only handle `bool`s.
Resolves GH-1748
Add `NOT` integer support

fix(ssa refactor): ACIR gen NOT integer

---

crates/noirc_evaluator/src/ssa_refactor/opt/inlining.rs

Resolves GH-1626
Tracking of call depth wasn't "popping" when exiting a call.

fix(ssa refactor): recursion_level decrement

---

crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs
crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg/branch_analysis.rs

Resolves GH-1664
The existing implementation of `analyze_function` used a queue + stack-based approach to to associating a branch start with an end. I couldn't convince myself that there was a way to make this approach safe, so I've written a recursion-based alternative that passes the failing case surfaced by GH-1664.
This alternative recursion based-approach associates a branch start to its end at the point that a recursion exits, such that the association is encapsulated. A disadvantage to this approach is that it does result in extra allocations, because `visited` hash sets and `Stepper`s are allocated for each level of recursion.

fix(ssa refactor): recursive branch analysis

---

Cargo.lock
Cargo.toml
crates/nargo/src/ops/execute.rs
crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
crates/noirc_evaluator/src/brillig/brillig_ir.rs
crates/noirc_evaluator/src/brillig/brillig_ir/debug_show.rs

feat: update acvm to 0.15.1

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs
crates/noirc_evaluator/src/ssa_refactor/ir/instruction.rs
crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs

Resolves #1486
Merges array values by recursively merging each element and creating a new array from the result.

fix(ssa refactor): Implement merging of array values during flattening pass

---

crates/noirc_evaluator/src/brillig/brillig_gen.rs
crates/noirc_evaluator/src/brillig/brillig_gen/brillig_directive.rs
crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/acir_variable.rs
crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/generated_acir.rs

Avoid using the invert directive when we generate acir
Directives are deprecated in favour of brillig opcode, which can replace all directives in theory.
Resolves

chore: Use brillig instead of invert directive

---

crates/nargo_cli/tests/test_data/to_bits/Nargo.toml
crates/nargo_cli/tests/test_data/to_bits/src/main.nr
crates/noirc_evaluator/src/ssa/optimizations.rs

Resolves https://github.com/noir-lang/noir/issues/1400

fix(old ssa): fix to_be_bits

---

crates/noirc_evaluator/src/ssa_refactor/opt/inlining.rs

After inlining the following program:
```rs
use dep::std;
fn main(cond: bool) {
let res = inner1(cond);
std::println(res);
}
fn inner1(cond: bool) -> Field {
inner2(cond)
}
fn inner2(cond: bool) -> Field {
if cond { 1 } else { 2 }
}
```
it would incorrectly reduce to:
```
fn main f3 {
b0(v0: u1):
call println(v3)
return 
}
```
This was happening because at the close of the call to `inner1`, the block mapping was inappropriately used for identifying the location of the "return terminator", thus the function builder was switching to `b0`, instead of continuing from the end of the last inlined function.
Annotate the inlined location analogous to a "return terminator" by using the the `current_block` instead of a stale mapping.

fix(ssa refactor): function inlining orphans calls

---

Cargo.lock
Cargo.toml
crates/nargo_cli/Cargo.toml

Resolves 
This updates acvm-backend-barretenberg to a version that removes the wasm32 target. There seems to be conflicting dependencies between the backend and the `noir_wasm` crate. Since we aren't going to target wasm32 target with the backend, we can just remove it.

fix(nargo): Update acvm-backend-barretenberg to allow wasm backend compilation

---

crates/noirc_evaluator/src/ssa_refactor/ir/function_inserter.rs
crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs

Resolves #1756
When an `allocate` instruction occurred in only one branch of an `if` expression, the flattening pass would still try to create a load instruction before the first store to the allocation in an attempt to save its previous (non-existent) value to merge later. This pass adds a field to track these local allocations and avoid merging stores for them since there is no value to merge in the opposite branch of the if.

fix(ssa refactor): Fix flattening pass inserting loads before stores occur

---

crates/noirc_evaluator/src/ssa_refactor/ir/dom.rs
crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg/branch_analysis.rs
crates/noirc_evaluator/src/ssa_refactor/opt/unrolling.rs

The `find_branch_ends` function was recurring forever on the `eddsa` and `sha2_byte` tests so I've replaced it with a different algorithm that is O(N) and never revisits a block.
This is related to https://github.com/noir-lang/noir/issues/1750 but is not related to the acir-gen issue that was taking forever there.

fix(ssa refactor): Speedup find-branch-ends

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/acir_variable.rs

Resolves #1763
Not for signed integers was a todo!() in the code, but in fact bitwise operations are the same for signed and unsigned integers thanks to the 2-complement representation.

chore: enable NOT for signed integers

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/acir_variable.rs

Resolves https://github.com/noir-lang/noir/issues/1750
After a flamegraph profiling I found out that most time in acir-gen for the `eddsa` test was spent in `mul_var` and `sub_var`, and most time in those methods was spent in `TwoWayMap::insert` where to insert a new AcirVar, AcirVarData pair we were calling `FieldElement::eq` repeatedly which uses `to_bytes_be` internally.
To fix this, I changed the `TwoWayMap` to a single-way map. The downside of this fix is if an identical `AcirVarData` is ever tried to be inserted, it will be assigned a new id instead of an existing one. This may slow down proving later on.

fix(ssa refactor): Speedup acir-gen

---

Cargo.lock
Cargo.toml
crates/nargo_cli/Cargo.toml
crates/nargo_cli/src/cli/lsp_cmd.rs

Resolves 
This updates async-lsp to support windows. I needed to add a conditional implementation for the stdio stuff because Windows doesn't have non-blocking stdio (this is the same as async-lsp tests).

fix(lsp): Ensure LSP can compile on Windows

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/acir_variable.rs
crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs

When `enable_side_effects` is false, we are meant to be in a false branch of an `if` that was not taken, so we should ignore side effects causing the program to fail, such as array out of bounds errors. I've added a check for this to only panic for array index of out of bounds errors if enable side effects is not known to be false.
This fixes the bug in #1629 ~~but means the issue will still appear if the `if` uses a witness as its condition, as it would not be known to be false.~~ I've changed the logic to only panic if `enable_side_effects` is known to be true rather than not known to be false.
Resolves #1629

fix(ssa refactor): Ignore array out of bounds errors when enable_side_effects is false

---

.github/workflows/pull-request.yml
.github/workflows/test.yml
.github/workflows/wasm.yml
flake.nix

Resolves 
This updates the mac runner to `macos-latest-xl` which is a 12-core hosted runner. I also removed `push` event from the workflow since `merge_queue` was fixed since we implemented this and it is the more correct event. We'll be timing out tests after 30 minutes to keep costs down.

chore(ci): Use large mac runner for tests

---

.github/workflows/spellcheck.yml

Resolves 
This workflow seems to get cancelled on master. If we only run it on PR, we should get a green checkmark on the head commit.

chore(ci): Only run spellcheck on pull_request event

---

crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs

Resolves #1792 / #1806 
When flattening the cfg there is an optimization to set the value of an `if`'s condition to a constant `true`/`false` within the then/else branch respectively since there is no other way to get to these branches without this being true.
This means for code such as:
```rs
fn main(c: bool) {
if c {
constrain c;
}
}
```
We can optimize it to:
```rs
fn main(c: bool) {
if c {
constrain true;
}
}
```
Since we know `c` is always true within the then branch. This allows us to remove this particular `constrain` entirely afterward.
The problem in #1792 arised when we forgot to reset the condition `c` back to `c`, so even after the if ended we still had `c = true` or `c = false` in the context. This PR fixes this by simply resetting `c` to its old value after finishing an if …

fix(ssa refactor): Reset condition value during flattening pass

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs

The "missing assignment for witness index" error was caused by an incorrect call in the array-element case of `create_value_from_type` which should have been a recursive call but instead was still calling `convert_ssa_block_param`. This was an oversight from PR #1797.
Resolves #1799
With this PR `sha2_byte` and `sha2_block` no longer hit this error and instead run into a "cannot satisfy all constraints" error as in #1800.

fix(ssa refactor): Fix recursive call to `create_value_from_type`

---

crates/nargo_cli/tests/test_data_ssa_refactor/ec_baby_jubjub/Nargo.toml
crates/nargo_cli/tests/test_data_ssa_refactor/ec_baby_jubjub/src/main.nr
crates/noirc_evaluator/src/ssa_refactor/ir/function_inserter.rs

Resolves #1801
This one took much longer than it should have. It ended up being a simple missed call to `resolve` to resolve aliased instructions. Without this call, a block parameter was left in the IR which acir-gen later found and panicked on.
`ec_baby_jubjub` now proves successfully.

fix(ssa refactor): Add missed call to resolve

---

crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs

Resolves #1826
Previously, any stores in the `then` branch of an `if` would be picked up by the `else` branch as well (See the linked issue for more details). This PR adds an extra step to the flattening pass to restore the old values of each store between the then and else branches to fix this.
I've also altered the `merge_stores_with_offset` test since we no longer support offsets from allocations after the switch to immutable arrays. I changed the test to a simple merge stores test but with an else block.

fix(ssa refactor): Prevent stores in 'then' branch from affecting the 'else' branch

---

crates/noirc_evaluator/src/ssa_refactor/ir/dfg.rs
crates/noirc_evaluator/src/ssa_refactor/ir/instruction.rs

When running larger programs with several `if` statements the ssa refactor can often spit out code such as:
```
...
enable_side_effects_if v0
enable_side_effects_if u1 0
enable_side_effects_if u1 1
enable_side_effects_if u1 1
...
```
In which only the last instruction is useful since `enable_side_effects` overrides any previous calls of itself.
This PR adds a check in `Instruction::simplify` to check if the last instruction inserted was also a `enable_side_effects_if` instruction, and if so, replace it with the new instruction instead of inserting another.

chore(ssa refactor): Remove extra 'enable_side_effects' instructions

---

Cargo.lock
crates/lsp/Cargo.toml
crates/lsp/src/lib.rs
crates/noirc_driver/src/lib.rs

First implementation of #1834 
This adds the infrastructure to display codelenses via the LSP. The first codelens that we support is the `> Run Test` action above functions marked via `#[test]`. The lens will display in any version of the vscode extension, but there is no command registered for `nargo.test` in the currently released version. We are adding the `nargo.test` command in https://github.com/noir-lang/vscode-noir/pull/25 (you can package it into a vsix and install manually to try).

feat(lsp): Add a codelens that runs test when clicked

---

crates/noirc_driver/src/lib.rs

Resolves 
Minor refactor I noticed while reviewing #1840

chore: replace `.filter().count() > 0` with `.any()`

---

crates/nargo_cli/src/cli/mod.rs
crates/nargo_cli/src/resolver.rs
crates/noirc_driver/src/lib.rs
crates/wasm/src/compile.rs

Resolves #1833  
This moves the addition of the stdlib to the dependency graph into `Driver::check_crate`, which is the point we know the root is configured and all other dependencies have been added to the driver. This ensures that no matter how or when you call `driver.check_crate` (e.g. `nargo_cli`, `lsp`, or `noir_wasm`), the stdlib will always be available.
This solution is sub-optimal because the stdlib should probably be the first crate added to the dependency graph and then it should be propagated to each new dep as it is added, but that seemed like a much larger refactor because a lot of the code in the compiler expects `FileId(0)` to be the crate root.
In making this change I also discovered #1839

fix(lsp): Ensure stdlib is always added before the `check_crate` phase

---

crates/nargo_cli/tests/test_data/higher_order_functions/src/main.nr
crates/noirc_frontend/src/ast/expression.rs
crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir_def/types.rs
noir_stdlib/src/sha256.nr
noir_stdlib/src/sha512.nr

Adds missed checks to the type system to prevent comparison operators (other than `==` and `!=`) from being used on Fields even if at least 1 operand is a type variable. These are implemented the same way we prevent this with bitwise operators - with a delayed type check.
Resolves #1857

fix: Prevent comparisons from being used on `Field`s

---

crates/lsp/src/lib.rs
crates/nargo_cli/src/cli/check_cmd.rs
crates/nargo_cli/src/cli/compile_cmd.rs
crates/nargo_cli/src/cli/mod.rs
crates/nargo_cli/src/cli/test_cmd.rs
crates/nargo_cli/src/resolver.rs
crates/noirc_driver/src/lib.rs
crates/noirc_driver/src/main.rs
crates/noirc_frontend/src/hir/def_collector/dc_crate.rs
crates/noirc_frontend/src/hir/def_map/mod.rs
crates/noirc_frontend/src/hir/mod.rs
crates/noirc_frontend/src/main.rs
crates/wasm/src/compile.rs

Towards #1838  
This removes the `Driver` struct that takes ownership over a `Context`. The struct is replaced by functions that take a `Context` and work with it, which allows for various parts of the system to own a `Context` they create, such as the `LspState` or nargo CLI.
Functions in the driver that were related to retrieving information about the program were moved onto the `Context`.

feat(driver): Remove `Driver` struct and refactor functions to take `Context`

---

crates/noirc_evaluator/src/ssa/optimizations.rs

Very small fix to restrict the xor constant folding to 128 bits as the simplification done does not support more than that.
Resolves

chore: restrict xor optimisation to 128 bits

---

Cargo.lock
Cargo.toml
crates/nargo_cli/Cargo.toml
crates/nargo_cli/src/backends.rs
crates/nargo_cli/src/cli/fs/witness.rs

We are moving to have our ACIR tests run in bb.js for proving and verification while nargo will just handle circuit execution.
Resolves 
This PR changes the format in which witnesses are saved to file. bberg is currently the only consumer of our witness output however this may be breaking for any old programs that still save the witness to file and use it elsewhere (however I see this as unlikely due to the large divergence in the TS bberg packages and Noir master). 
In order to be in line with bb.js we also need to enable the RecursiveAggregation opcode in acvm-backend-barretenberg as per this PR: https://github.com/noir-lang/acvm-backend-barretenberg/pull/225

chore: Save witness in correct format that bb.js expects

---

crates/nargo/src/artifacts/contract.rs
crates/nargo/src/artifacts/program.rs
crates/nargo/src/ops/preprocess.rs
crates/nargo_cli/src/cli/codegen_verifier_cmd.rs
crates/nargo_cli/src/cli/compile_cmd.rs
crates/nargo_cli/src/cli/mod.rs
crates/nargo_cli/src/cli/prove_cmd.rs
crates/nargo_cli/src/cli/verify_cmd.rs

The proving and verifying keys are quite large, so now we give users the option to include or not include those keys.
Resolves

chore(nargo)!: Make proving and verification keys optional

---

.github/workflows/test.yml

The Mac runner in this PR https://github.com/noir-lang/noir/pull/1728 fails with a `pointer being freed was not allocated error` coming from barretenberg. However, all tests pass on my local intel Mac and other's ARM Mac laptops. 
We also have moved to just performing execution in the prove_and_verify tests w/ barretenberg handling proving and verification. The error is still happening after the move execution, thus there is most likely some internal bug w/ barretenberg on the Mac runner. 
This is blocking slices which is blocking a lot of other work by others, so we are going to remove the Mac runner and create an issue to barretenberg to handle running Noir tests on the different architectures. 
Resolves

chore(ci): Remove mac runner

---

crates/lsp/src/lib.rs

Resolves 
Currently, the compiler doesn't know how to recompile code. Instead if just returns immediately. By storing a context on the LSP state, no diagnostics would be sent because the codelens handler runs first.
We need to create a new Context on each message until we can make the compiler recompile files.

fix(lsp): Avoid storing Context until recompiles are possible

---

crates/fm/src/lib.rs
crates/noirc_driver/src/lib.rs
crates/noirc_frontend/src/hir/def_map/mod.rs
crates/noirc_frontend/src/main.rs

Towards #1838  
This removes the concept of `FileType`. The reason this seemed to exist was an artifact of not creating the correct "candidates" in the `resolve_path` function on FileManager.
We want to store all files as their extensionless filename and then search for a directory with the same name and fallback to the sibling file if the directory structure doesn't exist.

chore(fm): Remove the concept of FileType

---

Cargo.toml

Dependency changes between even minor versions of wasm-bindgen are surfacing errors in the CI. 
We pin the version of wasm-bindgen in this PR, so that it does not get automatically updated. 
Resolves

chore: Pin `wasm-bindgen` dependency to 0.28.6

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/generated_acir.rs

chore: Add abstraction layer around ACIR gen of quotient directives

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/generated_acir.rs

Fixes test cases for #1729 
Previously we would
```
1. Apply range constraints to limbs.
2. Apply arithmetic constraint to limbs.
3. Insert limb values with directive.
```
It's impossible to solve 1 and 2 without 3 so we have reordered these as
```
1. Insert limb values with directive.
2. Apply range constraints to limbs.
3. Apply arithmetic constraint to limbs.
```

fix: emit `Opcode`s in correct order from `GeneratedAcir::radix_le_decompose`

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/acir_variable.rs
crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs

`enable_side_effects` should always be initialized to a constant `true` value so there is no need for an Option. Handling it as an Option lead to an inconsistency discovered by @vezenovm where the check to see if side effects were known to be disabled was false if the option was None, rather than the desired default of true. This lead to e.g. out of bound array accesses being ignored until after the first if statement of a program.

chore: Change `enable_side_effects` in acir_gen from an `Option<AcirVar>` to an `AcirVar`

---

crates/nargo_cli/tests/test_data_ssa_refactor/references/src/main.nr
crates/noirc_frontend/src/hir/type_check/expr.rs

Resolves #1899
When we encounter `foo.bar` where `foo` is a reference, we automatically dereference foo, transforming the code into `(*foo).bar`. When this happens, we previously accidentally set the type of `foo` to `T` and `*foo` to `&mut T` instead of the reverse. I've switched the two cases.

fix: Fix auto-deref operations assigning the wrong result type

---

crates/noirc_frontend/src/parser/parser.rs

In the code:
```rs
if x {
y
} else {
z
}
```
The parser would parse an expression for the if condition and `x { y }` is a valid constructor expression using the shorthand field syntax. I've resolved this to more closely follow rust's official grammar (https://doc.rust-lang.org/reference/expressions/if-expr.html) in which constructor expressions are forbidden as part of an if condition:
Note the "except struct expression" subscript.
Resolves #1915 and #152
Unfortunately this PR is quite messy. I'm not sure of a good way to clean it up at the moment without duplicating the expression parser. Chumsky requiring us to pass each recursive parser as a parameter makes it quite a bit more verbose.

fix: Prevent `if` and `for` from parsing constructor expressions

---

crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
crates/noirc_frontend/src/parser/parser.rs

We were passing the size of an array from `Type::Array` directly when generating the inputs for a brillig foreign call. This wouldn't break for normal arrays or singular structs, but breaks in the case of an array of structs. For example if we have an array of two structs with two fields each, only the first two fields would be passed to the foreign call as the entire array is of size 2.
Quick issue found while doing logging PR
I held off on adding a struct test directly as my println PR will have much more comprehensive tests that deserialize arrays of structs.

fix(brillig_gen): Pass correct size of complex types input for brillig foreign calls

---

crates/noirc_frontend/src/ast/expression.rs
crates/noirc_frontend/src/parser/parser.rs

Resolves #1310
Previously an `if` followed by a tuple expression was parsed as a function call, with the return result of the `if` being the function. This is ambiguous with the grammar of an `if` expression sequenced with a tuple. Since the later parse is more desirable (and matches what rust does in this scenario) I've resolved the parse by arbitrarily always taking the later over the former.
Since I've added a check when constructing an `Expression::call` this means unfortunately that any `if` expression surrounded by parenthesis is also affected. So `(if c { f } else { g })(1, 2)` is also parsed as a sequence rather than a function call.

fix: Parse an if followed by a tuple as a block

---

crates/noirc_evaluator/src/ssa_refactor.rs
crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/acir_variable.rs
crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/errors.rs
crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/generated_acir.rs
crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs

Resolves #1918 
Adds `Result` pervasively to AcirGen. I've also added `Location`s to each `AcirGenError` to improve the error messages.
Now, when running on the example code from the linked issue the compiler no longer crashes and instead issues an error message:
```
error: 
┌─ /.../aztec-packages/yarn-project/noir-contracts/src/libs/noir-aztec/src/types/vec.nr:18:16
│
18 │         assert(self.len as u64 < MaxLen as u64);
│                ------------------------------- Failed constraint
Error: Aborting due to 1 previous error
```
This error message could still be nicer (in a future PR):
- It is in a library function rather than the original contract, so a stack trace would be very helpful (but difficult).
- We could interpolate failing asserts more precisely. So the error could be …

fix: Add Result to acir gen

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/acir_variable.rs
crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/generated_acir.rs

Resolves 
This pulls out the changes from #1929 which don't rely on changes to the ACVM.

fix: Emit opcodes for sorting variables in order of execution

---

crates/noirc_frontend/src/lexer/lexer.rs

support for multi-line comments: https://doc.rust-lang.org/reference/comments.html

feat: Add multi-line comments

---

crates/nargo_cli/tests/test_data_ssa_refactor/references/src/main.nr
crates/noirc_frontend/src/hir/type_check/expr.rs

Resolves #1946
This was a simple missed case in `lookup_method` for handling the MutableReference type. More details are given in the linked issue.

fix: method resolution when calling an `&mut` method with an `&mut` object type

---

crates/noirc_frontend/src/lexer/errors.rs
crates/noirc_frontend/src/lexer/lexer.rs

fix lexer errors for unexpected characters and attribute parsing
Resolves #1943

chore: fix lexer errors for unexpected characters

---

crates/noirc_frontend/src/lexer/errors.rs
crates/noirc_frontend/src/lexer/lexer.rs

fix unterminated block comment
Resolves https://github.com/noir-lang/noir/pull/1936#discussion_r1266769989

chore: fix unterminated block comment

---

crates/nargo_cli/tests/test_data_ssa_refactor/brillig_calls/src/main.nr
crates/nargo_cli/tests/test_data_ssa_refactor/brillig_fns_as_values/src/main.nr
crates/nargo_cli/tests/test_data_ssa_refactor/brillig_loop/src/main.nr
crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
crates/noirc_evaluator/src/brillig/brillig_ir.rs
crates/noirc_evaluator/src/ssa_refactor/ir/function.rs
crates/noirc_evaluator/src/ssa_refactor/opt/defunctionalize.rs

- Fix register overwrite when returning from functions that return more than two registers (Resolves #1976)
- Extract convert function call to its own method
- Allow lessthan operations for comparisons of fields issued by the compiler (loops) (Resolves #1977)
- Refactor defunctionalization 
- No longer try to guess runtime of callees (Resolves #1974)
- Use Signature struct of ssa ir 
- Fix dynamic dispatch collection
- Fix transformation of functions as values to numeric constants (Resolves #1975)

fix: Various fixes for defunctionalization & brillig gen

---

crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs

Resolves #1978
Flattening the CFG is only needed for the main function, that is the one which will be converted to ACIR. Doing it in all the functions of the SSA implies that it will try to do it in functions that were compiled to brillig, and some of them are not supported by branch analysis, making it panic.

fix: Only flatten main

---

crates/nargo_cli/tests/test_data_ssa_refactor/6_array/src/main.nr
crates/noirc_evaluator/src/ssa_refactor/ir/value.rs
crates/noirc_evaluator/src/ssa_refactor/ssa_gen/context.rs

Resolves #1997
Removes a TODO/assumption when assigning to arrays that the element type would be a single element rather than several of them (e.g. a tuple/struct). This only started triggering recently due to the recent println PR which disabled the array of structs to struct of arrays conversion for the ssa refactor.

fix: Assignment to arrays of structs

---

crates/noirc_driver/src/lib.rs
crates/noirc_evaluator/src/brillig/brillig_gen.rs
crates/noirc_evaluator/src/brillig/brillig_gen/brillig_slice_ops.rs
crates/noirc_evaluator/src/brillig/brillig_ir.rs
crates/noirc_evaluator/src/brillig/brillig_ir/debug_show.rs
crates/noirc_evaluator/src/brillig/mod.rs
crates/noirc_evaluator/src/ssa_refactor.rs
crates/noirc_frontend/src/hir/def_map/mod.rs
crates/noirc_frontend/src/monomorphization/mod.rs

Reference this comment: https://github.com/noir-lang/noir/pull/1755#pullrequestreview-1487752018
Currently we have a hardcoded constant in the code for whether we display a Brillig debug trace. It is currently set to true which means anytime that a Brillig function is used in a program the trace is printed as well. Now that println has been set to use Brillig it means that every time println is used in a program the full brillig debug trace will be first outputted. 
I have added a flag `--show-brillig` that toggles this feature. I had to thread it further into the Brillig gen module than I would have liked due to how the current Brillig printer is implemented. The Brillig debug trace is more high-level and is more of a Brillig codegen printer than a full Brillig printer. For example, when …

chore(nargo): Toggle brillig debug trace from CLI

---

crates/noirc_frontend/src/hir/resolution/resolver.rs

Match rust by allowing variable shadowing by default for local variables.
- When declaring variables, they may now shadow previous names.
- This means we can declare a new variable of the same name as a previous variable.
- The previous variable will not be modified, but it will be inaccessible until the new variable goes out of scope.

feat: Allow shadowing by default

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/acir_variable.rs
crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs
crates/noirc_evaluator/src/ssa_refactor/ir/value.rs

Resolves https://github.com/noir-lang/noir/issues/1972
think `fn brillig` is the only one

chore: remove `Option` in `predicate: Option<AcirVar>`

---

crates/noirc_frontend/src/hir/type_check/expr.rs

Resolves #1875
Types should generally never be shallowly matched on before calling `follow_bindings`. This adds a missed case to catch the above issue in which a bound TypeVariable was not checked that it was bound to a Field.

fix: Add missing `follow_bindings` when checking if a type can be casted

---

crates/nargo_cli/src/cli/init_cmd.rs
crates/nargo_cli/src/cli/mod.rs
crates/nargo_cli/src/cli/new_cmd.rs

Resolves #1852 
This PR adds the `nargo init` command. Marking this as draft for the time being as I want to test some edge cases.
- Nargo will have a new `nargo init` command which will create a new project in the current directory.

feat: add `nargo init` command

---

crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir_def/types.rs

Resolves #2009
Previously when type checking function calls if the function was an unbound type variable we'd bind the type variable without performing an `occurs` check first. This lead to us creating infinitely recursive types such as `a = (fn(a) -> ())` as in the issue above. Since we should never bind without performing an occurs check in general, I've made a helper function to help avoid this in the future.

fix: Perform `occurs` check before binding function types

---

crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs

Resolves issue with non-deterministic circuit bytecode when using HashMap for `merge_stores`
Move from HashMap to BTreeMap in merge_stores

fix: Switch from HashMap to BTreeMap in merge_stores

---

crates/nargo_cli/build.rs
crates/nargo_cli/src/cli/check_cmd.rs
crates/nargo_cli/src/cli/test_cmd.rs
crates/nargo_cli/tests/test_data_ssa_refactor/rebuild.sh
crates/noirc_driver/src/lib.rs
crates/noirc_evaluator/src/lib.rs
crates/noirc_evaluator/src/ssa_refactor.rs
crates/noirc_frontend/src/hir/def_map/mod.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/monomorphization/mod.rs
crates/noirc_frontend/src/node_interner.rs

Resolves 
This PR does the minimal changes to move `nargo` over to use the new SSA code by default. You can continue to use the old SSA by using the `legacy-ssa` flag (which replaces `experimental-ssa`) although this should be removed soon.
References to `experimental-ssa` should be removed. I would leave `legacy-ssa` undocumented as it will be removed soon.

feat!: Change CLI to default to new SSA code for compilation

---

crates/lsp/src/lib_hacky.rs
crates/nargo_cli/src/resolver.rs
crates/noirc_driver/src/lib.rs
crates/noirc_frontend/src/graph/mod.rs
crates/wasm/src/compile.rs

Resolves #2060 
This implements proper traits for `CrateName` instead of relying on an ad-hoc API. Implementing `FromStr` allows us to use `.parse()` on a `&str` to get a CrateName, and it allows us to use `CrateName` as a type with `clap` derivers (or any other APIs that use `.parse()`.
This work fell out of https://github.com/noir-lang/noir/pull/1992 but should be merged as a prerequisite.

chore: Implement `FromStr` and `Into<String>` for CrateName

---

crates/noirc_evaluator/src/ssa_refactor/ir/value.rs
crates/noirc_frontend/src/hir/resolution/errors.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs

Add validation for 'pub' keyword on non-entry point functions
Resolves #1220

chore: add validation for 'pub' keyword on non-entry point functions

---

crates/noirc_frontend/src/hir/resolution/errors.rs

Change unnecessary pub error to a warning 
Resolves #2059

chore: change 'unnecessary pub' error to a warning

---

crates/noirc_evaluator/src/ssa_refactor/ir/function.rs
crates/noirc_evaluator/src/ssa_refactor/ir/types.rs
crates/noirc_evaluator/src/ssa_refactor/opt/defunctionalize.rs

In preparation of https://github.com/noir-lang/noir/issues/2036
Avoid using hasmap/hashset for maps/sets that will be iterated on to avoid generating non-deterministic acir/brillig.

fix: Avoid non-determinism in defunctionalization

---

crates/nargo_cli/tests/test_data_ssa_refactor/brillig_slices/src/main.nr
crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs

After @jfecher PR https://github.com/noir-lang/noir/pull/2070 now Value::Array can have Type::Slice. This PR tries to handle it appropiately.

fix: Slice initialization

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/generated_acir.rs

Resolves 
`GeneratedAcir::two_complement` will currently panic if `lhs` is a degree 2 expression. This PR uses `mul_with_witness` to avoid this potential panic.

fix: avoid potential panic in `two_complement`

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/acir_ir/generated_acir.rs

Resolves 
This PR relaxes an overly strict condition in `mul_with_witness`. In case 1 we are checking that we can apply the multiplication to the expressions directly so their product must be degree 2 or less.
| lhs  | rhs | now | previously |
|-------|-------|---------|---------|
|    0   |   0   |  :heavy_check_mark:  | :heavy_check_mark:  |
|    1   |   0   |  :heavy_check_mark:  | :heavy_check_mark:  |
|    0   |  1    |  :heavy_check_mark:  | :heavy_check_mark:  |
|    1   |   1   |  :heavy_check_mark:  | :heavy_check_mark:  |
|    0   |   2   |  :heavy_check_mark:  | :x:   |
|    2   |   0   |  :heavy_check_mark:  | :x:   |
This PR handles the two remaining cases for which we used to create an unnecessary intermediate variable.

feat: Remove an unnecessary witness in `mul_with_witness`

---

crates/wasm/package.json

Updating noir-wasm to point to noir-source-resolver version 1.1.3

chore: Update `noir-source-resolver` to v1.1.3

---

crates/fm/src/lib.rs

Resolves 
This PR applies clippy fixes where we're unnecessarily creating references to / cloning variables.

chore: clippy fixes

---

crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs
crates/noirc_frontend/src/monomorphization/mod.rs

Relates to https://github.com/noir-lang/noir/issues/1344#issuecomment-1656017435 but does not solve the issue.
Slices cannot be supported for println yet as we do support slices as an entry point for Brillig generation. This is because the Brillig entry point expects a set amount of expressions and it cannot be unknown. Slices will not be supported in Brillig gen until we add another pass or some other context information to track slice sizes. Once slices are enabled for Brillig entry points the linked issue will be able to be fully resolved. 
For now, this PR simply clarifies the error so that the user does not get information about the main func and the ABI:
```
Message:  internal error: entered unreachable code: println does not support slices. Convert the slice to an array before …
```

chore: Make a more clear error for slices passed to std::println

---

crates/lsp/src/lib.rs
crates/lsp/src/lib_hacky.rs
crates/nargo_cli/src/cli/mod.rs
crates/nargo_cli/src/lib.rs
crates/noirc_driver/src/lib.rs
crates/wasm/src/compile.rs

Resolves 
While working on my CrateType PR, I noticed that these functions are now exactly the same. This can land before the CrateType work is finished.

chore(noirc_driver): Unify crate preparation

---

crates/nargo_cli/tests/test_data/regression_2099/Nargo.toml
crates/nargo_cli/tests/test_data/regression_2099/src/main.nr
crates/noirc_evaluator/src/ssa_refactor/ir/function_inserter.rs
crates/noirc_evaluator/src/ssa_refactor/opt/flatten_cfg.rs

Resolves #2099 and the issue in #1954, although #2099 is now failing with another error that looks to require #2106.
When resetting the mapping of the condition value during flattening, we were mapping it to its old value directly, rather than the value it was previously mapped to. This had the effect of forgetting any previous mappings which made it possible for (among other things) block parameters of previously deleted blocks to remain in the code.
CC @TomAFrench since this unblocks his PR.

fix: flattening pass no longer overwrites previously mapped condition values

---

crates/noirc_evaluator/src/ssa_refactor/ir/instruction.rs

Resolves 
This PR adds additional simplification rules for `BinaryOps` for special cases of the operations where the operation is a no-op.
```rust
fn main(x: u32) -> distinct pub [u32; 3] {
let mut result : [u32; 3] = [0; 3];
result[0] = x ^ 0;
result[1] = x & x;
result[2] = x | x;
result
}
```
On the latest nightly this compiles to
```
Compiled ACIR for main (unoptimized):
current witness index : 11
public parameters indices : []
return value indices : [9, 10, 11]
BLACKBOX::RANGE [(_1, num_bits: 32)] [ ]
EXPR [ (-1, _2) 0 ]
BLACKBOX::XOR [(_1, num_bits: 32), (_2, num_bits: 32)] [ _3]
BLACKBOX::AND [(_1, num_bits: 32), (_1, num_bits: 32)] [ _4]
EXPR [ (-1, _1) (-1, _5) 4294967295 ]
EXPR [ (-1, _1) (-1, _6) 4294967295 ]
BLACKBOX::AND [(_5, num_bits: 32), (_6, num_bits: 32)] [ _7]
EXPR [ …
```

feat: Add additional `BinaryOp` simplifications

---

noir_stdlib/src/option.nr

Following discussion on #1781
Renames the pseudo-private `value` field of `Option<T>` to `_value` to make it more difficult for users to accidentally use it.
This also adds an `unwrap_unchecked` to return the inner `_value` without performing an assertion. It is expected that this function is called after checking if `option.is_some()` or similar.
- There is now a new method on options: `Option::unwrap_unchecked()`
- This method is similar to `unwrap` but it will not assert `option.is_some()`. This method can be useful within an if condition when we already know that `option.is_some()`. If the option is None, there is no guarantee what value will be returned, only that it will be of type `T` for an `Option<T>`.

fix: Rename `Option::value` to `Option::_value`

---

crates/noirc_evaluator/src/ssa_refactor/ir/instruction.rs
crates/noirc_evaluator/src/ssa_refactor/ir/instruction/call.rs

Resolves #1962 
Quick and dirty implementation of #1962, opening a draft PR for visibility. I'll clean this up on Monday.
This PR replaces any calls to AND, XOR, SHA256, Keccak256, Blake2s, HashToField128 and ECDSA verification with constant arguments with direct assignments of the call's outputs.
~~We can also do the same with the ECDSA functions (Although I'm not sure on the usecase for embedding a constant signature into a circuit).~~

feat: Optimize away constant calls to black box functions

---

crates/noirc_driver/src/lib.rs

Resolves #2131 
PR title
References to the short form of these flags should be removed from the docs.

chore: remove short flags for `--show-ssa` and `--deny-warnings`

---

crates/nargo_cli/tests/test_data/slices/src/main.nr
crates/noirc_evaluator/src/ssa/ir/dfg.rs
crates/noirc_evaluator/src/ssa/ir/instruction/call.rs
crates/noirc_evaluator/src/ssa/ir/types.rs
crates/noirc_evaluator/src/ssa/ssa_gen/context.rs

Resolves #2083, although additional work is needed to implement these same changes in Brillig (CC @sirasistant)
We needed to account for cases in the slice functions where we need to push/pop multiple elements. Additionally, all indexes must be multiplied by the element count.

fix: Implement slices of structs

---

crates/fm/src/lib.rs
crates/noirc_frontend/src/hir/def_collector/dc_mod.rs

Resolves 
This reworks the API of FileManager by renaming `resolve_path` to `find_crate` to better explain what it is doing and then replaces the `resolve_path` API with the `normalize_path` function that appends the FileManager root if the path is not absolute already.

chore: Refactor `normalize_path` into an API on FileManager

---

crates/nargo_cli/src/errors.rs
crates/nargo_cli/src/manifest.rs

Resolves #2086 
This relaxes the TOML parsing around package name and moves validation into `resolve_to_package` to provide better error messages to the user that contain the toml file missing the `name` field.
I also removed the TODO since we should just keep this validation logic going forward.

fix(nargo): Indicate which TOML file is missing package name

---

Cargo.lock
Cargo.toml

Resolves 
Clap's had a number of build-time improvements and fixes since 4.1.4. This PR updates so we can take advantage of them.

chore: bump `clap` to 4.3.19

---

crates/noirc_driver/src/lib.rs

Resolves partially #2130 
This PR hides the `show_ssa` and `show_brillig` flags as they're unnecessary for 99.9% of users. I've left `print_acir` as is pending us splitting up this struct.

chore: Hide the `show_ssa` and `show_brillig` flags

---

crates/nargo_cli/src/cli/lsp_cmd.rs

Resolves 
The LSP command does not use any arguments yet we are providing it with all the flags in `CompileOptions`. This PR removes these unused flags.

chore!: remove unused flags on LSP command

---

crates/nargo_cli/src/cli/init_cmd.rs
crates/nargo_cli/src/cli/new_cmd.rs

Resolves #2132 
`package_name` positional argument has been replaced by the `name` option. `name` defaults to the package directory if unspecified.
Arguments to `nargo new` and `nargo init` have changed.

feat!: Allow specifying new package name with `--name` flag

---

crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs

Resolves 
We can return the result of the match statement directly

chore: clippy fix

---

Cargo.lock
crates/fm/Cargo.toml
crates/fm/src/lib.rs
cspell.json

Resolves 
While trying to integrate #2156 into Nargo CLI toml resolution, I found that it was a bad API due to the current way that Nargo CLI reads from the filesystem.
Instead of using that API, I believe we should implement `normalize` on `PathBuf` and `&Path` so we can import the trait to normalize any paths we have in the codebase.
Sorry for the churn!

chore: Replace `resolve_path` function with a trait that impls normalize

---

.github/Cross.toml
.github/workflows/wasm.yml

Resolves 
This is a pretty hacky solution to the mismatch of noirc versions between CLI and WASM. We should in future get wasm to reuse the build artifacts we have commited.

chore: Ensure that CLI and wasm compilers are sync in `noir_wasm_testing`

---

crates/noirc_evaluator/src/ssa.rs
crates/noirc_evaluator/src/ssa/acir_gen/mod.rs
crates/noirc_evaluator/src/ssa/ir/post_order.rs
crates/noirc_evaluator/src/ssa/opt/array_use.rs
crates/noirc_evaluator/src/ssa/opt/mod.rs

Array_set was always creating a new copy of an acir MemoryBlock, because it creates a new ssa array
Resolves #2014
We implement a new ssa pass which maps ssa arrays with their last use.
In acir-gen, when we process the instruction corresponding to the last use of an array, we can avoid to create a new one and copy it, and we can directly operate on that array.
In order to do this, we take benefit from the ssa array-> acir block Id map and map the new ssa array to the block ID of the original ssa array.

chore: Do not create new memory block when not needed

---

crates/nargo_cli/src/manifest.rs

Resolves #2114 
This makes the `[dependencies]` section of the Nargo.toml optional because it is weird that we'd require the section if we have no dependencies.

fix(nargo): Make dependencies section optional in TOML

---

crates/nargo_cli/src/cli/lsp_cmd.rs

Resolves 
We've currently got a very conspicuous blank space next to `lsp` when we run `nargo --help`. If someone were to run the command to find out what it does then they appear to just have the terminal hang until they terminate the program.
My thoughts are that we should either hide the command or add some explanatory documentation.

chore: add documentation to the `nargo lsp` command

---

crates/nargo_cli/src/cli/new_cmd.rs

Resolves #2182 
I've removed the copying across of all `nargo init` arguments into `nargo new` as this was causing panics.
BEGIN_COMMIT_OVERRIDE
END_COMMIT_OVERRIDE

fix: remove duplicated `name` option in `nargo new`

---

crates/noirc_frontend/src/hir/type_check/errors.rs
crates/noirc_frontend/src/hir/type_check/expr.rs

Resolves https://github.com/noir-lang/noir/issues/2152
```rust
fn main() {
let a = -[1,2];
}
```
will now return
```rust
[Field; 2] cannot be used in an unary operation
```

chore: Improve unary error

---

crates/nargo_cli/tests/compile_tests_data/fail/different-lambda-env-reassign-disallow.nr
crates/noirc_frontend/src/hir/type_check/stmt.rs
crates/noirc_frontend/src/hir_def/types.rs

This code type-checks properly, but an assertion fails during SSA generation.
The reassignment is invalid since the two lambdas have different environment types, and should be caught during type-checking.
```
fn main() {
let a: u32 = 1;
let b: u32 = 1;
let mut f = || a;
f = || a + b;
f();
}
```
Resolves https://github.com/noir-lang/noir/issues/2139
This adds an additional check to assignments, to cover this case and throw an error if an invalid assignment happens.

fix: Fix an ICE when reassigning a mutable lambda variable to one with a different environment type

---

crates/noirc_evaluator/src/errors.rs
crates/noirc_evaluator/src/ssa/ssa_gen/mod.rs
crates/noirc_frontend/src/monomorphization/ast.rs
crates/noirc_frontend/src/monomorphization/mod.rs

Resolves #2193 
This PR fixes the crash and shortens the error message, but the error message is a bit confusing now for the code snippet from the issue since it is off by one:
```
error: 
┌─ /Users/jakefecher/Code/Noir/noir/short/src/main.nr:3:13
│
3 │     assert((x as u253) < (y as u253));
│             --------- Range constraint of 254 bits is too large for the Field size
```
Although since we actually do perform a range constraint to 254 bits during a euclidean division call I'm not sure of an obvious solution to make it less confusing.

fix: Set location before cast instructions in SSA

---

crates/nargo_cli/Cargo.toml
crates/nargo_cli/src/backends.rs
crates/nargo_cli/src/cli/fs/witness.rs

Resolves #2010
This PR removes the unnecessary `flat_witness` feature flag.

chore(nargo)!: remove `flat_witness` feature flag

---

crates/noirc_evaluator/src/ssa/ir/instruction.rs
crates/noirc_evaluator/src/ssa/ir/types.rs

Resolves 
Currently we don't make use of type information when simplifying the `Lt` operator. As we know that unsigned values can't be negative then `x < 0` can be simplified to `false`.

feat: Optimize `x < 0` for unsigned `x` to false

---

crates/nargo/src/package.rs
crates/nargo_cli/src/cli/compile_cmd.rs
crates/nargo_cli/src/cli/init_cmd.rs
crates/nargo_cli/src/cli/new_cmd.rs
crates/nargo_cli/src/manifest.rs
crates/nargo_cli/tests/execution_success/contracts/Nargo.toml
crates/noirc_driver/src/lib.rs

Ref #2075  
This implements the `contract` package type in Nargo.toml but only replaces the `--contracts` flag on `nargo compile`; it doesn't implement contract support for other commands.
Technically this could close #2075 since we only supported `nargo compile` for contracts, but I think we should work to support the `contract` package type uniformly across all commands. I've started diving down this rabbit hole but there are still some unanswered questions so I wanted to unblock @Ethan-000's #2088 without causing unnecessary churn.
The `--contracts` flag was removed from the `nargo compile` command and instead the `contract` package type needs to be specified in Nargo.toml

feat(nargo)!: Replace `--contracts` flag with `contract` package type

---

crates/nargo_cli/tests/execution_success/references/src/main.nr
crates/noirc_frontend/src/monomorphization/mod.rs

Resolves #2030
It turns out that #2030 was caused by some aos -> soa conversion code for LValues that was meant to be removed but was forgotten about. This swapped the position of the dereference and the indexing LValues causing the odd type error in SSA.

fix: Remove last vestige of array of structs to struct of arrays conversion

---

Cargo.lock
Cargo.toml
crates/nargo_cli/Cargo.toml
crates/nargo_cli/src/cli/check_cmd.rs
crates/nargo_cli/src/cli/codegen_verifier_cmd.rs
crates/nargo_cli/src/cli/compile_cmd.rs
crates/nargo_cli/src/cli/execute_cmd.rs
crates/nargo_cli/src/cli/info_cmd.rs
crates/nargo_cli/src/cli/mod.rs
crates/nargo_cli/src/cli/prove_cmd.rs
crates/nargo_cli/src/cli/test_cmd.rs
crates/nargo_cli/src/cli/verify_cmd.rs
crates/nargo_cli/src/errors.rs
crates/nargo_cli/src/lib.rs
crates/nargo_toml/Cargo.toml
crates/nargo_toml/src/errors.rs
crates/nargo_toml/src/git.rs
crates/nargo_toml/src/lib.rs

Towards #1838 
This moves the operations on `Nargo.toml` files into its own crate. This will make the functions available to the `noir_lsp` and `nargo_cli` without causing a circular dependency.

chore: Split `Nargo.toml` operations into separate package

---

Cargo.lock
Cargo.toml
crates/lsp/Cargo.toml
crates/nargo_cli/Cargo.toml
crates/nargo_cli/src/cli/lsp_cmd.rs

Ref #2168 
WIP to get us on latest async-lsp changes to make sure they work and then we can request a new official release

chore: Bump `async-lsp` to v0.0.5

---

crates/nargo_cli/tests/execution_success/slices/src/main.nr
noir_stdlib/src/slice.nr

Resolves #2239
- `append` should be added to the list of methods on slices. It appends one slice to the end of another.

feat: Add slice append

---

crates/nargo_cli/src/cli/info_cmd.rs

Resolves https://github.com/noir-lang/noir/issues/1970
Resolves https://github.com/noir-lang/noir/pull/2088
```rust
fn main(x : Field, y : pub Field) {
assert(x * 2 == y * 3);
}
contract Foo {
fn double(x: Field) -> pub Field { x * 2 }
fn triple(x: Field) -> pub Field { x * 3 }
internal fn quadruple(x: Field) -> pub Field { x * 4 }
open internal fn skibbidy(x: Field) -> pub Field { x * 5 }
}
```
run `nargo info`
```rust
[Foo] Total ACIR opcodes generated for language PLONKCSat { width: 3 }: 4
[Foo] Backend circuit size: 7 
[Foo](quadruple) Total ACIR opcodes generated: 1
[Foo](quadruple) Backend circuit size: 2
[Foo](skibbidy) Total ACIR opcodes generated: 1
[Foo](skibbidy) Backend circuit size: 1
[Foo](double) Total ACIR opcodes generated: 1
[Foo](double) Backend circuit size: 2 …
```

feat: Support `contract` package type in `nargo info` command

---

crates/noirc_frontend/src/hir/resolution/resolver.rs

Resolves 
This PR addresses various clippy warnings.

chore: Address clippy warnings

---

crates/noirc_frontend/src/hir/def_collector/dc_crate.rs
crates/noirc_frontend/src/hir/def_collector/dc_mod.rs
crates/noirc_frontend/src/hir/def_collector/errors.rs

Def Collector issues several errors that has to do with duplicates. I united them into one common error type: Duplicate. It will be used in next steps when def collector collects trait definitions. This changes can be merged without conflicts, so I separated them into their own PR.

chore: Refactor DefCollector duplicate errors

---

crates/noirc_errors/src/reporter.rs
crates/noirc_frontend/src/ast/traits.rs
crates/noirc_frontend/src/parser/errors.rs
crates/noirc_frontend/src/parser/parser.rs

Parser support for traits
* The functions within trait definitions can now have a body ( Expand trait definition in AST to include body )
* Parsing support for trait-associated constants (using the let keyword for now to avoid introducing a new keyword such as const).
* Traits can have a where clause
* The where clause is only allowed on generic definitions
* The parsing of where clauses with multiple constraints has been fixed
* More parsing tests for functions using traits and trait definitions.
* Parser tests now pass by ignore warnings
After the first prototype of traits implementation we agreed to split into small PRs and merge them one by one in master branch.
This is the first from many to follow. Enjoy
Resolves 
After this PR the parser with parse ( with traits are experimental …

feat: Implement traits - parser support #2094

---

crates/nargo_cli/src/cli/compile_cmd.rs
crates/nargo_cli/src/cli/info_cmd.rs

Resolves #2256 
This PR ensures that we optimize contracts before querying the number of gates they result in in `nargo info`.

fix: Optimize contracts built by `nargo info`

---

crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/monomorphization/mod.rs

Work towards resolving  https://github.com/noir-lang/noir/issues/2120
Previously LValues weren't scanned & added to closure environments. This PR fixes that.
However, the example given in https://github.com/noir-lang/noir/issues/2120 still doesn't work due to an unrelated codegen issue (https://github.com/noir-lang/noir/issues/2255):
```
fn main() {
let x1 = &mut 42;
let set_x1 = |y| { *x1 = y; };
assert(*x1 == 42);
set_x1(44);
assert(*x1 == 44);
set_x1(*x1);
assert(*x1 == 44);
}
```

fix: properly capture lvalues in closure environments (#2120)

---

.github/workflows/publish.yml

Resolves 
There seems to be some sort of conflict with this caching and cargo-cross downloading a new image. We should remove it for now so we can get PRs through but figure out a better caching strategy (perhaps as part of #2265?)

chore(ci): Create cache key with consideration to target

---

.github/workflows/wasm.yml

Resolves 
The wasm test job should be a required check, but it is finding this name in the github required checks UI is hard. This makes it more specific.

chore(ci): Name wasm job more clearly

---

crates/nargo_cli/src/cli/check_cmd.rs

Resolves #2219 
We now no longer try to write a `Prover.toml` file for contract packages so `nargo check` can succeed.
`nargo check` will work for contracts

feat(nargo): Add support for contracts in `nargo check`

---

crates/lsp/src/lib.rs
crates/nargo_cli/src/cli/test_cmd.rs
crates/noirc_frontend/src/hir/mod.rs

Resolves #2271  
This adds the `--exact` flag to `nargo test` which allows us to select tests based on an exact name. I also refactored the code to make it more clear which tests we were selecting and fixed problems with running tests in the vscode plugin inside a workspace (relies on https://github.com/noir-lang/vscode-noir/pull/29)
The `--exact` flag needs to be documented on the `nargo test` command.

feat(nargo): Add `--exact` flag to `nargo test`

---

crates/nargo_cli/src/cli/check_cmd.rs
crates/noirc_abi/src/input_parser/json.rs
crates/noirc_abi/src/input_parser/mod.rs
crates/noirc_abi/src/input_parser/toml.rs
crates/noirc_abi/src/lib.rs
crates/noirc_abi/src/serialization.rs
crates/noirc_frontend/src/hir_def/types.rs

Include struct names in the output ABI, which is useful for autogenerating types that follow the same naming. 
Related to #2238. It doesn't fix the issue since it'd need the full path to the struct, which I couldn't find on the `StructType`. My guess is there may be a mapping from `CrateId` (part of the `StructId`) to files somewhere. Any tips on where to get this info from would be appreciated, and I can try including it in a follow up PR or this one.
```diff
{
"name": "entrypoint",
"functionType": "secret",
"isInternal": false,
"parameters": [
{
"name": "payload",
"type": {
"kind": "struct",
+           "name": "EntrypointPayload",
"fields": [
{
"name": "flattened_args_hashes",
"type": {
"kind": "array",
"length": 4,
"type": {
"kind": "field"
}
}
},
```

feat: Include struct names in ABIs

---

crates/nargo_cli/src/cli/mod.rs

Resolves #2289  
This allows us to put `--program-dir` anywhere in a command. This enables me to work on https://github.com/noir-lang/vscode-noir/issues/28 easily.

fix(nargo): Allow `--program-dir` flag anywhere in a command

---

crates/lsp/src/lib.rs
crates/nargo_cli/src/cli/mod.rs

Resolves #2291  
Resolves https://github.com/noir-lang/vscode-noir/issues/28
This passes the `--program-dir` flag when a user runs a test via a codelens. This ensures that the `Run Test` lens will always work, even if there is no Nargo.toml file at the root of the vscode workspace.

fix(lsp): Pass `--program-dir` to test command from codelens

---

crates/nargo_cli/src/cli/mod.rs

The recently added `--program-name` conflicts with the `--prover-name` argument of `nargo prove`, and `nargo prove` panics with the following error:
```
Message:  Command prove: Short option names must be unique for each argument, but '-p' is in use by both 'prover_name' and 'program_dir'
```
Resolves  https://github.com/noir-lang/noir/issues/2299
Remove the option to have --program-dir as a short argument so it doesn't conflict with --prover-name

fix(nargo)!: Remove `-p` short flag from the `--program-dir` flag

---

crates/nargo_cli/src/cli/init_cmd.rs
crates/nargo_cli/src/cli/mod.rs
crates/nargo_cli/src/cli/new_cmd.rs
crates/nargo_cli/src/errors.rs
crates/nargo_cli/tests/compile_failure/invalid_dependency_name/Nargo.toml
crates/nargo_cli/tests/compile_failure/invalid_dependency_name/src/main.nr
crates/nargo_cli/tests/compile_failure/package_name_empty/Nargo.toml
crates/nargo_cli/tests/compile_failure/package_name_empty/src/main.nr
crates/nargo_cli/tests/compile_failure/package_name_hyphen/Nargo.toml
crates/nargo_cli/tests/compile_failure/package_name_hyphen/src/main.nr
crates/nargo_cli/tests/test_libraries/bad_name/Nargo.toml
crates/nargo_toml/src/errors.rs
crates/nargo_toml/src/lib.rs
crates/noirc_frontend/src/graph/mod.rs

Resolves #2287 
This PR requires that `CrateNames` must have a non-empty string to avoid the issue described in #2287 
We also weren't validating these on package creation, so I've added a custom value parser to clap in order to error on invalid user input as soon as possible so we don't get `nargo new` half-creating the new package.
BEGIN_COMMIT_OVERRIDE
fix: Require package names to be non-empty (#2293)
feat: Perform input validation on user's package names (#2293)
END_COMMIT_OVERRIDE

fix: Require package names to be non-empty

---

crates/noirc_errors/src/reporter.rs
crates/noirc_frontend/src/parser/parser.rs

Fixed some test code in parser. The biggest change is 
* parse_all_failing test function is now satisfied by errors only ( previous version treated warning as errors )
* Fix 3 parser test cases from failing to passing
* Fix typo in is_warning
Prior to this PR this test cases triggered errors by in the parser
```
trait GenericTrait<T> { fn elem(&mut self, index: Field) -> T; }
trait GenericTraitWithConstraints<T> where T: SomeTrait { fn elem(self, index: Field) -> T; }
trait TraitWithMultipleGenericParams<A, B, C> where A: SomeTrait, B: AnotherTrait<C> { let Size: Field; fn zero() -> Self; }
```
Resolves

fix: Fix 3 parser test cases in parsing

---

crates/noirc_frontend/src/hir/def_collector/dc_crate.rs
crates/noirc_frontend/src/hir/def_collector/dc_mod.rs
crates/noirc_frontend/src/hir/def_map/mod.rs
crates/noirc_frontend/src/hir/def_map/module_data.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/type_check/mod.rs
crates/noirc_frontend/src/monomorphization/mod.rs

Resolves 
As discussed with @jfecher today, I removed `ModuleOrigin` from the `ModuleData` struct and replaced it with the `Location` instead.

chore(frontend): Replace `ModuleOrigin` with `Location` on `ModuleData`

---

crates/lsp/src/lib.rs
crates/nargo_cli/src/cli/check_cmd.rs
crates/nargo_cli/src/cli/codegen_verifier_cmd.rs
crates/nargo_cli/src/cli/compile_cmd.rs
crates/nargo_cli/src/cli/execute_cmd.rs
crates/nargo_cli/src/cli/info_cmd.rs
crates/nargo_cli/src/cli/prove_cmd.rs
crates/nargo_cli/src/cli/test_cmd.rs
crates/nargo_cli/src/cli/verify_cmd.rs
crates/nargo_toml/src/lib.rs

Resolves #2311  
This adds the `--workspace` flag to subcommands that process workspace packages. This flag allows users to "opt-out" of running the command against only the `default-member` package and instead run it against all packages in the workspace. It also makes sure the LSP always prepares the entire workspace instead of the default member.
The `--workspace` flag needs to be documented for the subcommands that accept it.

feat(nargo): Add `--workspace` flag to run commands in every package

---

crates/wasm/build.sh
crates/wasm/buildPhaseCargoCommand.sh
flake.nix

Resolves 
This PR updates the build scripts for the `wasm` crate so that it reuses the workspace's `target` directory rather than creating a new one at `crates/wasm/target`.

chore: Reuse workspace target directory in wasm build script

---

.github/workflows/wasm.yml
crates/wasm/test/browser/index.test.ts
crates/wasm/test/shared.ts

chore: Make `wasm` tests pull from `result` directory

---

crates/nargo_cli/tests/compile_failure/overflowing_assignment/Nargo.toml
crates/nargo_cli/tests/compile_failure/overflowing_assignment/src/main.nr
crates/noirc_frontend/src/hir/type_check/errors.rs
crates/noirc_frontend/src/hir/type_check/stmt.rs
crates/noirc_frontend/src/hir_def/types.rs

Resolves https://github.com/noir-lang/noir/issues/2236
`nargo execute` code
```rust
use dep::std;
fn main() {
let x:u8 = 300;
std::println(x);
}
```
will result in
```rust
error: The literal `300` cannot fit into `u8` which has range `0..=255`
```
`nargo execute` code
```rust
use dep::std;
fn main() {
let x:u8 = -1;
std::println(x);
}
```
will result in
```rust
error: u8 cannot be used in a unary operation
```

fix: Overflowing assignment will result in an error

---

crates/nargo_cli/src/cli/mod.rs

Resolves comment in https://github.com/noir-lang/noir/pull/2322#pullrequestreview-1578966511
This PR fixes an issue where using relative paths in the `--program-dir` flag causes nargo to panic. This is done by joining any relative paths to the current working directory.

fix: Prevent panic when passing relative paths to `--program-dir`

---

crates/lsp/src/lib.rs
crates/nargo_cli/src/cli/check_cmd.rs
crates/nargo_cli/src/cli/codegen_verifier_cmd.rs
crates/nargo_cli/src/cli/compile_cmd.rs
crates/nargo_cli/src/cli/execute_cmd.rs
crates/nargo_cli/src/cli/info_cmd.rs
crates/nargo_cli/src/cli/prove_cmd.rs
crates/nargo_cli/src/cli/test_cmd.rs
crates/nargo_cli/src/cli/verify_cmd.rs
crates/nargo_toml/src/errors.rs
crates/nargo_toml/src/lib.rs

Resolves #2261 
This reworks the crawling for Nargo.toml files. When searching for the `program_dir`, we still search to the root using `find_package_root`; however, `find_package_manifest` requires a root where we stop the crawling. Additionally, we now read the `<program_dir>/Nargo.toml` exactly instead of traversing.
These changes allowed me to fix a problem with the LSP where it would crawl past the `root_uri` and find a Nargo.toml outside of the directory you have opened.

fix(lsp): Ensure lsp does not crawl past the root specified

---

crates/noirc_frontend/src/ast/expression.rs
crates/noirc_frontend/src/ast/function.rs
crates/noirc_frontend/src/ast/traits.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/type_check/errors.rs
crates/noirc_frontend/src/hir/type_check/mod.rs
crates/noirc_frontend/src/hir_def/function.rs
crates/noirc_frontend/src/parser/parser.rs

better return type error message
Resolves #2105

feat: Improved error message for unexpected return type

---

.github/workflows/release.yml

Resolves https://github.com/noir-lang/noir/actions/runs/5870717891/job/15918335872
Fixes issue with publishing binaries in 0.10.0 release. We can run the publish workflow manually to create these binaries however so no need to make a 0.10.1.

chore(ci): fix mismatched input name to publish workflow

---

crates/noirc_frontend/src/ast/statement.rs
crates/noirc_frontend/src/graph/mod.rs
crates/noirc_frontend/src/hir/type_check/errors.rs
crates/noirc_frontend/src/hir/type_check/expr.rs

We normally throw an error on unused expression:
```rust
fn foo() {
3 + 2; // error: expected (), got field
5;
}
```
However we currently fail to catch the case where there's only one expression:
```rust
fn foo() {
3 + 2; // no error :(
}
```
This PR fixes that, and per suggestion of @jfecher (https://github.com/noir-lang/noir/issues/2304#issuecomment-1677969357) converts that error to a warning. This is probably also needed, since otherwise it breaks a few tests that rely on the old behavior, and potentially user code.
Nicer error message is also provided:
Before:
```
error: Expected type (), found type Field
┌─ /home/vitkov/code/repos/metacraft-labs/noir/proj/src/main.nr:3:5
│
3 │     5;
│     -
```
After:
```
warning: Unused expression result (of type Field)
┌─ …
```

fix: Display warning if last expression of block is unused

---

crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir/type_check/mod.rs
crates/noirc_frontend/src/hir_def/types.rs

Initial work towards https://github.com/noir-lang/noir/issues/2334
This is work towards allowing higher-order functions to be called with closure arguments. The bulk of the work will be done in the monomorphizer in the next PRs, this is a prerequisite that  allows higher-order functions called with closures to pass type-checking.
A method called `try_unify_allow_incompat_lambdas` is added that is used instead of `try_unify` for function arguments. The only difference between it and `try_unify` is that it doesn't check function type capture groups.
This also fixes some comments that reference the removed `make_subtype_of` functions

feat: Allow calling higher-order functions with closures

---

crates/lsp/src/lib.rs
crates/noirc_frontend/src/hir/def_map/mod.rs

Another implementation of #1834  
This adds a `> Compile` code lens above contracts (in contract packages) and `main` functions (in bin packages). Currently a draft because it relies on #2308 and it outputs the artifacts in each package in a workspace instead of at the workspace root (so I want to solve that problem first).

feat(lsp): Add `Compile` code lens for `main` function and contracts

---

crates/nargo_cli/tests/execution_success/brillig_to_le_bytes/src/main.nr
crates/nargo_cli/tests/execution_success/to_le_bytes/src/main.nr
crates/noirc_evaluator/src/brillig/brillig_ir.rs
crates/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs

References this comment and the preceding discussion: https://github.com/noir-lang/noir/pull/2348#issuecomment-1681214310

chore(brillig): Fix brillig radix instruction return vector size

---

crates/noirc_frontend/src/hir/type_check/errors.rs
crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir/type_check/mod.rs
crates/noirc_frontend/src/hir/type_check/stmt.rs

Resolves #2351
The same `other` variable was used for both types in the error message, leading to a confusing error.

fix: Remove duplicte `T` in `expected T, found T` error on tuple assignment

---

crates/noirc_evaluator/src/ssa/acir_gen/mod.rs
crates/noirc_evaluator/src/ssa/ir/instruction.rs
crates/noirc_evaluator/src/ssa/ir/instruction/call.rs
crates/noirc_evaluator/src/ssa/opt/die.rs
crates/noirc_evaluator/src/ssa/opt/flatten_cfg.rs
crates/noirc_evaluator/src/ssa/opt/inlining.rs
crates/noirc_evaluator/src/ssa/opt/mem2reg.rs

Resolves https://github.com/noir-lang/noir/issues/2115

chore: Remove unused `Intrinsic::Println`

---

crates/noirc_frontend/src/hir/def_map/item_scope.rs
crates/noirc_frontend/src/hir/def_map/module_data.rs
crates/noirc_frontend/src/hir/def_map/module_def.rs
crates/noirc_frontend/src/hir/resolution/import.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir_def/types.rs
crates/noirc_frontend/src/monomorphization/mod.rs
crates/noirc_frontend/src/node_interner.rs

This is the next PR from the series of Trait Implementation. I expected to be merged quickly, because it's some simple definition that will be used later

feat: Add trait definition representation in DefCollector and HIR

---

crates/noirc_evaluator/src/ssa/acir_gen/acir_ir/generated_acir.rs

https://github.com/noir-lang/noir/pull/2358#issuecomment-1682597799

chore: Remove unused `Directive::Log`

---

crates/nargo_cli/tests/execution_success/closure_explicit_types/Nargo.toml
crates/nargo_cli/tests/execution_success/closure_explicit_types/src/main.nr
crates/noirc_frontend/src/ast/mod.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/type_check/expr.rs
crates/noirc_frontend/src/hir/type_check/mod.rs
crates/noirc_frontend/src/hir_def/types.rs
crates/noirc_frontend/src/monomorphization/mod.rs
crates/noirc_frontend/src/parser/parser.rs

Work towards https://github.com/noir-lang/noir/issues/2334
In https://github.com/noir-lang/noir/pull/2335  we allowed higher order with closure arguments to pass type-checking -- this PR implements the monomorphizer changes needed to make those calls work.
A new property `overridden_types` is added in the Monomorphizer. It allows us to change the type of an expression, for the currently monomorphized function instance only. It's used for adding capture environments to function types.
A function `propagate_overridden_types_expr` is added in a new file - propagate.rs. After we override the type of a parameter to add a capture group, we need to walk the body of the function and also update the types of all expressions where it is used.

feat: add syntax for specifying function type environments

---

crates/noirc_abi/src/lib.rs
crates/noirc_evaluator/src/ssa/acir_gen/mod.rs
crates/noirc_frontend/src/ast/expression.rs
crates/noirc_frontend/src/ast/function.rs
crates/noirc_frontend/src/ast/mod.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/type_check/mod.rs
crates/noirc_frontend/src/hir_def/function.rs
crates/noirc_frontend/src/monomorphization/ast.rs
crates/noirc_frontend/src/monomorphization/mod.rs
crates/noirc_frontend/src/parser/parser.rs

Towards #2238 
This separates the `Visibility` and `Distinctness` as parsed in the frontend from the `AbiVisibility` and `AbiDistinctness` as defined by the ABI. These are mostly the same, but this is the first step in detangling the `noirc_abi` and `noirc_frontend` crates. I will be following up with additional PRs that continues this work.

chore: Separate frontend `Visibility` and `Distinctness` from the ABI

---

Cargo.lock
Cargo.toml
crates/nargo_cli/Cargo.toml
crates/nargo_cli/src/cli/compile_cmd.rs
crates/nargo_cli/src/cli/execute_cmd.rs
crates/noirc_errors/Cargo.toml
crates/noirc_errors/src/debug_info.rs
crates/noirc_evaluator/src/ssa/acir_gen/acir_ir/generated_acir.rs

Starts using acvm 0.22 and backend 0.11. It also substitutes direct acir indexes with the new OpcodeLocation enum.

feat: Update to `acvm` 0.22.0

---

crates/nargo_cli/src/cli/check_cmd.rs
crates/noirc_abi/src/lib.rs
crates/noirc_driver/src/lib.rs
crates/noirc_evaluator/src/lib.rs
crates/noirc_evaluator/src/ssa.rs
crates/noirc_evaluator/src/ssa/abi_gen/mod.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/hir/type_check/mod.rs
crates/noirc_frontend/src/hir_def/function.rs
crates/noirc_frontend/src/monomorphization/ast.rs
crates/noirc_frontend/src/monomorphization/mod.rs

Towards #2238 
This removes the `FunctionSignature` type alias from the `noirc_abi` crate and instead defines the `main_function_signature` in terms of types defined in the HIR. These types are only converted into an ABI when an ABI is needed.
This is another step in decoupling the `noirc_abi` package from the frontend and will have additional follow ups that cleanup some of the leaky APIs (such as `noirc_evaluator::into_abi_params` which should just be in the ABI crate).

chore: Remove `noirc_abi::FunctionSignature` and define in terms of HIR

---

.github/workflows/cache-cleanup.yml

Looking at our current cache entries, we've got a number of these which are associated with merged pull requests
I don't think that these will actually ever be used past when the PR is actually merged so this just takes up cache space and contributes to churn.
I've taken a workflow from 
https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries so that we automatically evict these from the cache once they are merged.

chore(ci): automatically delete cache entries associated with closed PRs

---

crates/noirc_frontend/src/parser/parser.rs

allow parenthesizing in two type locations:
```
fn foo2<Bar>(bar: [Bar; (123)]) {}
fn foo<Foo>(bar: str<(Foo)>) {}
```
Resolves #2375

chore: allow parenthesizing in two type locations 

---

Cargo.lock
crates/noirc_frontend/Cargo.toml
crates/noirc_frontend/src/ast/expression.rs

Resolves 
Follow on to #2373 that removes the serde from the frontend. The project continues to compile, so I don't think serde was required here.

chore: Remove `serde` from `noirc_frontend`

---

crates/noirc_evaluator/src/ssa/ssa_gen/mod.rs
crates/noirc_frontend/src/ast/function.rs
crates/noirc_frontend/src/lexer/lexer.rs
crates/noirc_frontend/src/lexer/token.rs

Includes the ability to create custom attributes. This work comes after a discussion with the noir team to enable library flexibility. 
Resolves

feat(attributes): enable custom attributes

---

crates/nargo/src/lib.rs
crates/noirc_driver/src/lib.rs
crates/noirc_frontend/src/graph/mod.rs
crates/noirc_frontend/src/hir/mod.rs
crates/wasm/src/compile.rs

Towards #2238  
This reworks the `CrateGraph` to only have one root crate. This allows us to lookup the root crate when building an ABI for it. I also cleaned up the Dummy case so we aren't storing a `std::usize::MAX` for each dummy id.
This significantly cleans up my prototype solution in #2374

chore: Rework `CrateGraph` to only have one root crate

---

crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
crates/noirc_evaluator/src/brillig/brillig_gen/brillig_directive.rs
crates/noirc_evaluator/src/brillig/brillig_ir.rs
crates/noirc_evaluator/src/brillig/brillig_ir/artifact.rs
crates/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
crates/noirc_evaluator/src/ssa/acir_gen/acir_ir/generated_acir.rs
crates/noirc_evaluator/src/ssa/acir_gen/mod.rs

Introduces the same system of opcode locations that ACIR has for Brillig.
We were only generating location metadata for acir opcodes. 
This PR basically replicates the exact same approach that we're applying for ACIR to brillig. 
In the future we can improve the errors in the Brillig VM to produce a proper runtime callstack, because right now we'd only get the last inlined calls of the call stack (since the brillig VM only provides the opcode location that failed but not the opcode locations of the previous CALL instructions)

feat(brillig): Added locations for brillig artifacts

---

crates/noirc_errors/src/position.rs
crates/noirc_errors/src/reporter.rs
crates/noirc_evaluator/src/errors.rs
crates/noirc_frontend/src/lexer/lexer.rs

Closes #1682 
Resolves #1683
This PR addresses the off-by-one errors in how we deal with spans in a way which makes sense to me.
For example in `parse_block_comment` we're creating a span which goes from the start of the comment to the very last character in the file. We should then have an inclusive span here. Similarly when we have a `&&` we were previously creating a span of size 1 which doesn't really make sense for when we're capturing two characters.
Based on this, I noticed that `from_position` was creating exclusive end spans whereas we're calling it in the same way where logically we should have inclusive spans. I then switched this and the red squigglies are all appearing where I expect them to be.

fix: Correct off-by-one errors in lexer spans

---

.github/workflows/publish.yml

Resolves 
This PR updates CI to use `cross` v0.2.5 rather than building from whatever is currently on the tip of the master branch. This fixes CI failing due to it breaking our MSRV.

chore(ci): Fix version of `cross` to 0.2.5

---

crates/noirc_driver/src/lib.rs
crates/noirc_frontend/src/graph/mod.rs
crates/noirc_frontend/src/hir/mod.rs
crates/wasm/src/compile.rs

Resolves #1681  
This removes the stdlib propagation from the internals of `check_crate` and instead adds it to each crate in the CrateGraph as they are being added. We can do this because the Stdlib CrateId is a separate variant and we know that each crate should have access to it.

chore: Add stdlib to every crate as it is added to graph

---

crates/noirc_evaluator/src/errors.rs

improve error message for InternalError
Resolves https://github.com/noir-lang/noir/pull/2386#discussion_r1304477309

chore: improve error message for InternalError

---

crates/nargo_toml/src/errors.rs
crates/nargo_toml/src/lib.rs

Resolves https://github.com/noir-lang/noir/issues/2102

feat(nargo): Support optional directory in git dependencies

---

crates/nargo_cli/tests/compile_success_empty/closure_explicit_types/src/main.nr
crates/noirc_frontend/src/ast/function.rs
crates/noirc_frontend/src/ast/mod.rs
crates/noirc_frontend/src/hir/resolution/errors.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/parser/mod.rs
crates/noirc_frontend/src/parser/parser.rs

The syntax for closure environment types that I added in https://github.com/noir-lang/noir/pull/2357 is sub-optimal as it does not play well with generics. 
Resolves: https://github.com/noir-lang/noir/issues/2334
- As suggested in https://github.com/noir-lang/noir/pull/2357#discussion_r1298487380 this PR changes it changed from `fn[envarg1, envarg2](arg1, arg2, ...) -> ret` to `fn[env_type](arg1, arg2, ...) -> ret` so that a named generic can be used an environment. 
- Additional error checking is also added, since the new syntax allows passing any type as an environment, but the only valid ones are Unit/NamedGeneric/Tuple.
- Added tests for generic closure environments

feat: Syntax for environment types now works with generics

---

crates/nargo_cli/tests/execution_success/closures_mut_ref/src/main.nr
crates/noirc_frontend/src/monomorphization/mod.rs

Resolves  https://github.com/noir-lang/noir/issues/2120
We used to not capture lvalues in closures properly, which was fixed in https://github.com/noir-lang/noir/pull/2257, however a few codegen issue popped up (https://github.com/noir-lang/noir/issues/2255, https://github.com/noir-lang/noir/issues/2316) which still prevented the following example from verifying:
```rust
fn issue_2120() {
let x1 = &mut 42;
let set_x1 = |y| { *x1 = y; };
assert(*x1 == 42);
set_x1(44);
assert(*x1 == 44);
set_x1(*x1);
assert(*x1 == 44);
}
```
Those are now both fixed, but the code above still doesn't verify, because in the previous PR I've forgotten to mark the closure environment's ast::Ident as mutable, which causes us to take a wrong branch later on in ssa_gen.
This PR fixes that and adds the example …

fix: Closure lvalue capture bugfix

---

crates/noirc_evaluator/src/ssa.rs
crates/noirc_evaluator/src/ssa/opt/constant_folding.rs
crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/parser/parser.rs

Quick fix found when working on (https://github.com/noir-lang/noir/pull/2446) so no issue
In order to get dynamic slices working I included a constant folding pass before flattening. In this PR (https://github.com/noir-lang/noir/pull/2460) we reuse duplicate instructions with no side effects. However, Allocate instructions are not explicitly marked as having side effects so that they can be removed in DIE. 
For example in `execution_success/slices` executing just this method:
```rust
fn merge_slices_mutate(x: Field, y: Field) -> [Field] {
let mut slice = [0; 2];
if x != y {
slice = slice.push_back(y);
slice = slice.push_back(x);
} else {
slice = slice.push_back(x);
};
slice
}
```
Will lead to this SSA (with constant folding before flattening):
```
After Mem2Reg:
acir fn main f4 {
b0(v0: …
```

fix(ssa): Do not optimize for allocates in constant folding

---

crates/noirc_frontend/src/hir/resolution/resolver.rs
crates/noirc_frontend/src/parser/parser.rs
flake.nix

Resolves 
This adds `cargo fmt` to the list of checks in the flake so CI will fail if there's improper formatting.

chore(ci): enforce compliance with `cargo fmt`

---

crates/nargo_cli/tests/compile_success_empty/option/src/main.nr
crates/nargo_cli/tests/execution_success/generators/Nargo.toml
crates/nargo_cli/tests/execution_success/generators/src/main.nr
crates/nargo_cli/tests/execution_success/higher_order_functions/src/main.nr
noir_stdlib/src/array.nr
noir_stdlib/src/option.nr

Progress towards https://github.com/noir-lang/noir/issues/2334
This PR adds a generic Env argument for all higher-order functions in stdlib, allowing them to be called with both closures and regular functions.
It also adds a few test cases for functions returning closures that are possible now that https://github.com/noir-lang/noir/pull/2457 has been merged

feat: Standard library functions can now be called with closure args 

---

crates/nargo/src/ops/mod.rs
crates/nargo/src/ops/test.rs
crates/nargo_cli/src/cli/test_cmd.rs

Resolves 
This moves the core `run_test` functionality into nargo core and ensures the stdout/stderr printing only happens within `nargo_cli`.

chore: Move independent `run_test` function into nargo core

---

crates/nargo_cli/tests/execution_success/bit_shifts_comptime/src/main.nr
crates/noirc_evaluator/src/ssa/ir/instruction.rs
crates/noirc_evaluator/src/ssa/ssa_gen/context.rs

Resolves #2250 
The poster of the issue this PR aims to solve was correct in their assessment as to what was causing the panic. We were truncating the divisor into the operand type (which comes from the dividend). This caused the rhs to be `0`. When we have `0` in the divisor we should not simplify and instead leave the computation to runtime so we can handle it correctly. In this case, both bit shifts should result in `0`. This is similar to one of the fixes that had to be done in PR https://github.com/noir-lang/noir/pull/2475

fix(ssa): Handle right shift with constants

---

crates/noirc_frontend/src/hir/def_map/aztec_library.rs

Makes the aztec macro code a bit more robust by performing required imports. It also turns anything that didnt need to be a macro into a function
Resolves: https://github.com/AztecProtocol/aztec-packages/issues/1888

chore(aztec_noir): import aztec library if not found yet

---

crates/noirc_frontend/src/hir/def_map/aztec_library.rs

Resolves:
- https://github.com/AztecProtocol/aztec-packages/issues/1889
Emits an error message if the user uses the #aztec tags without the aztec library installed

chore: check if the noir aztec library is installed

---

crates/acvm_backend_barretenberg/src/lib.rs
crates/acvm_backend_barretenberg/src/proof_system.rs

Resolves 
`acvm_backend_barretenberg` no longer has feature flags so we can remove these lines.

chore: Remove dead code from `acvm_backend_barretenberg`

---

crates/acvm_backend_barretenberg/src/lib.rs
crates/acvm_backend_barretenberg/src/proof_system.rs
crates/acvm_backend_barretenberg/src/smart_contract.rs
crates/nargo_cli/src/backends.rs
crates/nargo_cli/src/cli/check_cmd.rs
crates/nargo_cli/src/cli/codegen_verifier_cmd.rs
crates/nargo_cli/src/cli/compile_cmd.rs
crates/nargo_cli/src/cli/execute_cmd.rs
crates/nargo_cli/src/cli/info_cmd.rs
crates/nargo_cli/src/cli/init_cmd.rs
crates/nargo_cli/src/cli/lsp_cmd.rs
crates/nargo_cli/src/cli/mod.rs
crates/nargo_cli/src/cli/new_cmd.rs
crates/nargo_cli/src/cli/prove_cmd.rs
crates/nargo_cli/src/cli/test_cmd.rs
crates/nargo_cli/src/cli/verify_cmd.rs
crates/nargo_cli/src/errors.rs

Resolves 
We're planning on removing the `Backend` trait as the backend interface is now being defined through the command line (i.e. the contents of `acvm-backend-barretenberg::bb`). We should then stop conforming to this trait.
This PR replaces the `Barretenberg` struct which implements the `Backend` trait with a `Backend` struct which will be a generic wrapper around the CLI interface which backends will conform to. This can in future hold config information about which backend we're wanting to interact with as we add support for multiple backends.

chore: remove usage of `Backend` trait

---

crates/noirc_frontend/src/hir/def_map/aztec_library.rs

Part of ongoing syntactic sugaring of aztec noir. 
resolves: https://github.com/AztecProtocol/aztec-packages/issues/1885
`aztec-packages` side of the issue: https://github.com/AztecProtocol/aztec-packages/pull/1924

feat(aztec_noir): abstract kernel return types

---

crates/nargo_cli/build.rs

Tests in the compiler_error subdirectory are treated as successful even if they cause the compiler to crash. This patch fixes that.

chore(ci): Distinguish between expected failures and compiler panics in `compile_failure` tests.

---

flake.nix

Resolves 
We currently fail to build through nix due to being unable to find `contract.sol` in `acvm-backend-barretenberg`. This fixes the build by adding new source filters so that we include the files we need.
The bytecode/witness filters are going to pick up the committed ACIR artifacts as well so we probably want to refine these before merging.

chore: fix building through `nix build`

---

crates/nargo_cli/src/cli/compile_cmd.rs

Resolves 
This PR adds `save_program` and `save_contracts` functions to `compile_cmd` so `run` isn't so comically huge.

chore: create helper functions for writing programs and contracts to file

---

crates/noirc_frontend/src/hir/def_map/aztec_library.rs

Issue caught in aztec end to end test,

fix(aztec_noir): generalise loop to not always inject a hasher instance

---

crates/nargo_cli/build.rs
crates/nargo_cli/src/cli/info_cmd.rs

Resolves 
This PR adds a hidden `--json` flag to `nargo info` which formats the information printed to stdout as JSON. This is then easier for other programs to parse and use.
I've made this a hidden flag for now so I can iterate on the exact format without it being a breaking change.

feat(nargo): add hidden option to produce JSON output from `nargo info`

---

Cargo.lock
crates/noirc_abi/Cargo.toml
crates/noirc_abi/src/input_parser/mod.rs

Resolves #2545
Resolves partly #2456 
When parsing fields from strings, we're currently converting the string into an `i128` temporarily if it's a decimal representation. This limits the size of values which can be passed in as a decimal string compared to hex strings.
We now instead parse using a `BigUint` to ensure that we can handle all inputs.
Note that `FieldElement` has a `try_from_str` implementation but as it returns an `Option<FieldElement>` rather than a `Result<FieldElement, Err>`, it's then not suitable for dealing with user input.
https://github.com/noir-lang/acvm/blob/5ad18bf8b365b57ba4c6f84004b5178e54562e7e/acir_field/src/generic_ark.rs#L204-L211

fix: allow usage of decimal string encoding for fields larger than a `i128`

---

crates/acvm_backend_barretenberg/src/lib.rs
crates/nargo_cli/src/backends.rs
crates/nargo_cli/src/cli/backend_cmd/ls_cmd.rs
crates/nargo_cli/src/cli/backend_cmd/mod.rs
crates/nargo_cli/src/cli/backend_cmd/use_cmd.rs
crates/nargo_cli/src/cli/mod.rs

Resolves #2527 
This PR adds the `nargo backend` subcommand. All the commands related to dynamic backends are going to be stored under this.
This PR in particular creates the `nargo backend ls` command which lists all of the directories in `~/.nargo/backends`. The user can then pass one of these names to `nargo backend use` to switch to that backend.
I've hidden the `nargo backend` command for the meantime as we build out dynamic backends.

feat: add `nargo backend ls` and `nargo backend use` command to switch between backends

---

crates/acvm_backend_barretenberg/src/lib.rs
crates/acvm_backend_barretenberg/src/proof_system.rs
crates/acvm_backend_barretenberg/src/smart_contract.rs

This PR moves the CRS for backends into a `crs` directory within the backend's directory. This makes it easier for us to clear this in future without knowing the CRS format.

chore: move CRS files into their own directory

---

crates/noirc_frontend/src/ast/expression.rs
crates/noirc_frontend/src/ast/function.rs
crates/noirc_frontend/src/hir/def_collector/dc_crate.rs
crates/noirc_frontend/src/hir/type_check/errors.rs
crates/noirc_frontend/src/parser/parser.rs

We have a struct called `FunctionReturnType`, that has a UnresolvedType and a Span. Recently we added a Span to `UnresolvedType` itself, so the Span is no longer needed

chore: remove duplicate span from FunctionReturnType

---

crates/acvm_backend_barretenberg/src/proof_system.rs
crates/noirc_evaluator/src/ssa/opt/mem2reg.rs
crates/noirc_evaluator/src/ssa/opt/mem2reg/alias_set.rs
crates/noirc_evaluator/src/ssa/opt/mem2reg/block.rs

Resolves 
Cleans up the mem2reg pass a bit by adding a wrapper type for `AliasSet`s and putting types in different modules.
Compared to the old `BTreeMap<ValueId, ReferenceValue>`, the new `AliasSet` makes it harder to accidentally handle unifying zero values as a set union (`A U {} = A`) instead of the correct `A U {} = {}`. In addition, it turns out an original assumption that a value will never be known to have exactly 0 aliases was incorrect. This can happen if we have an empty array of references. The array is empty, so although it has reference-typed elements, we know it does not actually alias anything at all. This means alias sets can no longer use an empty btree to represent the unknown case. It is now represented as an `Option<BTreeMap<...>>` internally instead.
I was working on …

chore: Cleanup mem2reg pass

---

.github/workflows/wasm.yml

chore: Temporarily disable `noir_wasm` test

---

crates/acvm_backend_barretenberg/src/bb.rs
crates/acvm_backend_barretenberg/src/download.rs
crates/acvm_backend_barretenberg/src/lib.rs
crates/nargo_cli/src/backends.rs
crates/nargo_cli/src/cli/backend_cmd/current_cmd.rs
crates/nargo_cli/src/cli/backend_cmd/install_cmd.rs
crates/nargo_cli/src/cli/backend_cmd/ls_cmd.rs
crates/nargo_cli/src/cli/backend_cmd/mod.rs
crates/nargo_cli/src/cli/backend_cmd/uninstall_cmd.rs

Resolves #2228 
This PR adds the following commands:
`nargo backend current`: prints the name of the currently active backend
`nargo backend install <name> <url>`: installs a backend from <url> under the name <name>
`nargo backend uninstall <name>`: uninstalls a backend  with the the name <name>

feat(nargo): Add commands to install and uninstall custom backends

---

crates/nargo_cli/tests/compile_failure/div_by_zero_modulo/Nargo.toml
crates/nargo_cli/tests/compile_failure/div_by_zero_modulo/src/main.nr
crates/noirc_evaluator/src/ssa/ir/instruction.rs

Resolves #2572 
In PR #2475 we make sure that we have a constraint failure if we attempt to divide by zero. This required preventing simplifications even if both the lhs and rhs of a binary op are known so that we can fail when processing the ACIR opcodes.
This PR simply adds the modulus case for simplification.

fix: Modulo with divisor of zero should fail constraints

---

crates/nargo/src/artifacts/debug.rs
crates/nargo_cli/Cargo.toml
crates/nargo_cli/src/cli/check_cmd.rs
crates/nargo_cli/src/cli/compile_cmd.rs
crates/nargo_cli/src/cli/execute_cmd.rs

Resolves 
This PR passes back just the `FileManager` from the compilation functions to restrict how much of the compilation context leaks into the rest of Nargo.

chore: return `FileManager` instead of `Context` from compilation functions

---

crates/fm/src/file_map.rs
crates/fm/src/lib.rs
crates/lsp/src/lib.rs
crates/nargo_cli/src/cli/compile_cmd.rs
crates/nargo_cli/src/cli/execute_cmd.rs
crates/nargo_cli/src/cli/test_cmd.rs
crates/noirc_errors/src/reporter.rs

We want to be able to report errors from using the `DebugArtifact` but `noirc_errors` requires a `FileManager`. This prevents us from reporting errors unless I have compiled the circuit myself.
This PR replaces `FileManager` in `noirc_error` with a trait bound on the `files` argument. This requires us to implement the `Files` trait on `FileMap`.

chore: Remove reliance on `FileManager` in `noirc_errors`

---

noir_stdlib/src/grumpkin_scalar.nr
noir_stdlib/src/grumpkin_scalar_mul.nr
noir_stdlib/src/lib.nr

Grumpkin scalar does not fit into the default `Field` type and for this reason we can't use the `fixed_base_embedded_curve` method which is already present in the stdlib. Kev advised me to first make a function which takes the full `GrumpkinScalar` and calls `fixed_base_embedded_curve` just with the high "half" of the grumpkin scalar because so that we have the API ready.

feat(stdlib): grumpkin scalar multiplication API

---

crates/noirc_evaluator/src/ssa/opt/unrolling.rs

Unrolling loops in brillig can lead to a code size explosion in some cases. Although this may not always happen, the easiest solution for now is to disable loop unrolling in brillig code. In the future we may want to revisit this with a maximum loop iterations unrolled heuristic or something else.

fix: Disable loop unrolling in brillig

---

Cargo.lock
crates/acvm_backend_barretenberg/Cargo.toml
crates/acvm_backend_barretenberg/src/cli/contract.rs
crates/acvm_backend_barretenberg/src/cli/gates.rs
crates/acvm_backend_barretenberg/src/cli/info.rs
crates/acvm_backend_barretenberg/src/cli/mod.rs
crates/acvm_backend_barretenberg/src/cli/prove.rs
crates/acvm_backend_barretenberg/src/cli/verify.rs
crates/acvm_backend_barretenberg/src/cli/write_vk.rs
crates/acvm_backend_barretenberg/src/smart_contract.rs

Resolves 
We used to require this as we were installing the mocked backend in each test (which resulted in many backends being simultaneously written to the same location. We now allow using backends at arbitrary paths so no longer need to do this.
We then run these tests in parallel.

chore: remove usage of `serial_test` dependency

---

crates/nargo_cli/tests/execution_success/slice_dynamic_index/src/main.nr
crates/nargo_cli/tests/execution_success/slices/src/main.nr
crates/noirc_evaluator/src/ssa/ir/instruction.rs
crates/noirc_evaluator/src/ssa/ir/instruction/call.rs
crates/noirc_evaluator/src/ssa/opt/flatten_cfg.rs

Resolves 
No issue as this was found and quickly patched as part of #374 
The handling of `get_slice_length` was incorrect in that for some instruction cases it used the slice capacity (the total number of slice elements in an array value) and in some cases it used the slice length prefix. During slice merger we should _only_ ever use the capacity. The length is to be used only for checking against user out of bounds accesses. This was not a problem in the existing tests, but when trying to do a push back outside of an if statement where there was a slice merger we get mismatched slice values as the length is not correct.

fix(ssa): Slice mergers with multiple ifs

---

crates/nargo/src/errors.rs
crates/nargo/src/ops/mod.rs
crates/nargo/src/ops/optimize.rs
crates/nargo_cli/src/cli/codegen_verifier_cmd.rs
crates/nargo_cli/src/cli/compile_cmd.rs
crates/nargo_cli/src/cli/execute_cmd.rs
crates/nargo_cli/src/cli/info_cmd.rs
crates/nargo_cli/src/cli/prove_cmd.rs
crates/nargo_cli/src/cli/verify_cmd.rs

Resolves 
This PR centralises the querying of opcode support from the backend to once per workspace. We then pass around a reference to this data for each package to avoid needing to call out to `bb` many times (and so needing to allocate memory for a massive circuit each time)

chore: query opcode support from backend once per workspace

---

crates/acvm_backend_barretenberg/src/cli/contract.rs
crates/acvm_backend_barretenberg/src/cli/gates.rs
crates/acvm_backend_barretenberg/src/cli/info.rs
crates/acvm_backend_barretenberg/src/cli/mod.rs
crates/acvm_backend_barretenberg/src/cli/prove.rs
crates/acvm_backend_barretenberg/src/cli/verify.rs
crates/acvm_backend_barretenberg/src/cli/write_vk.rs
crates/acvm_backend_barretenberg/src/lib.rs
crates/acvm_backend_barretenberg/src/proof_system.rs
crates/acvm_backend_barretenberg/src/smart_contract.rs

Resolves 
This PR turns `BackendError` into an enum of the main error variants. 
This PR also fixes a bug where attempting to use a backend with a missing binary will install barretenberg in its place.

chore: first pass at adding proper errors to dynamic backends

---

.github/workflows/abi_wasm.yml
.github/workflows/publish.yml
.github/workflows/test.yml
.github/workflows/wasm.yml

Resolves 
This is an experiment as the CI results associated with the merge queue are being applied to the `master` branch. We then check to see if cache entries are then applied to `master` branch as well.
If this doesn't work then we can revert this PR and explicitly run CI on `master` to generate cache entries.

chore(ci): create cache entries in merge queue

---

.github/workflows/abi_wasm.yml
.github/workflows/publish.yml
.github/workflows/test.yml
.github/workflows/wasm.yml

Reverts #2618 
This PR reverts #2618 and adds new triggers to CI to run on pushes to master. This will ensure that master has cache entries for all workflows.

chore(ci): Run CI on master to populate cache

---

.github/workflows/abi_wasm.yml

Resolves 
This PR adds a cache for the playwright binaries to reduce CI times by a whopping 40 seconds

chore(ci): cache binaries for playwright

---

crates/nargo_cli/src/cli/mod.rs

Resolves #2164 
This PR unhides the `backends` command in the CLI so that users can see how to install and switch to custom backends.

feat(nargo): Allow installing custom backends from the CLI

---

.github/workflows/abi_wasm.yml
.github/workflows/wasm.yml
crates/wasm/web-test-runner.config.mjs

Resolves #2565 
This PR fixes out `noir_wasm` testing in CI.

chore(ci): reenable CI for `noir_wasm`

---

Cargo.lock
Cargo.toml

Resolves 
Up until this change, we've been unable to build `noir_wasm` on Mac. When trying to compile, we'd get this message:
```
Compiling libc v0.2.147
Compiling psm v0.1.21
error: failed to build archive: section too large
The following warnings were emitted during compilation:
warning: warning: /bin/ranlib: archive library: /private/tmp/nix-build-noir_wasm-deps-0.11.1.drv-0/source/target/wasm32-unknown-unknown/release/build/psm-015060b7823c61b7/out/libpsm_s.a the table of contents is empty (no object file members in the library define global symbols)
error: could not compile `psm` due to previous error
```
While the error was "Section too large", I felt like it might be a red herring since the `libpsm_s.a` was mentioned in the warning. In the [psm docs](https://crates.io/crates/psm), …

fix(wasm): Remove stacker from dependencies

---

crates/lsp/src/lib.rs
crates/nargo_cli/src/cli/check_cmd.rs
crates/nargo_cli/src/cli/compile_cmd.rs
crates/noirc_driver/src/lib.rs

Resolves 
This PR codifies the `Result<(T, Warnings), ErrorsAndWarnings>` return type which we use in `noirc_driver` into a type alias. This is useful for some work related to #2613 where we need to pass around and map this result more.

chore: add `CompilationResult` helper type

---

compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs
compiler/noirc_evaluator/src/brillig/brillig_ir/debug_show.rs
compiler/noirc_evaluator/src/errors.rs
compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs
compiler/noirc_evaluator/src/ssa/opt/defunctionalize.rs
compiler/noirc_frontend/src/ast/statement.rs
compiler/noirc_frontend/src/ast/traits.rs
compiler/noirc_frontend/src/hir/def_collector/errors.rs
compiler/noirc_frontend/src/lexer/errors.rs
compiler/noirc_frontend/src/lexer/token.rs
compiler/noirc_frontend/src/parser/labels.rs
tooling/acvm_backend_barretenberg/build.rs
tooling/lsp/src/lib.rs
tooling/nargo/src/ops/foreign_calls.rs
tooling/nargo_cli/src/cli/backend_cmd/ls_cmd.rs
tooling/nargo_cli/src/cli/fs/program.rs

Fix clippy warnings for rust version 1.67.0

chore: Fix clippy warnings for rust version 1.67.0

---

compiler/noirc_errors/src/reporter.rs

Resolves #2654 
`path` already contains the extension so we're just adding a duplicate here.

fix: remove duplicate file extension in stack trace

---

compiler/noirc_frontend/src/hir/def_map/aztec_library.rs

#2537 broke compilation under the `aztec` feature flag.
This PR updates the `aztec` code to handle multiple attributes so it can compile again.

fix: fix compilation using `aztec` feature flag

---

tooling/nargo_cli/src/cli/codegen_verifier_cmd.rs
tooling/nargo_cli/src/cli/compile_cmd.rs
tooling/nargo_cli/src/cli/execute_cmd.rs
tooling/nargo_cli/src/cli/info_cmd.rs
tooling/nargo_cli/src/cli/prove_cmd.rs
tooling/nargo_cli/src/cli/verify_cmd.rs

Progress towards #2613 
This PR reworks `compile_contracts` and `compile_package` so that they return a `CompilationResult<T>`. This means that they no longer report their errors/warnings as soon as they can, but delegate this to `compile_cmd::run`. This is useful for #2613 as we can now construct two vectors of `CompilationResult<T>` (one for programs, one for contracts) in parallel and then simply iterate through them to print out the warnings/errors safely.
~The file manager is leaking again as we need to get `report_all_errors` to pick up the debug artifacts.~ This would require us to have a debug artifact for a failed compilation which seems uglier in my mind. We should probably maintain the usage of `FileManager` for compilation errors and just use `DebugArtifact` for execution …

chore: defer reporting of errors until after compilation and optimization is finished

---

tooling/nargo_cli/src/cli/execute_cmd.rs
tooling/nargo_cli/src/cli/prove_cmd.rs

Resolves 
Small refactor of this code for better separation of concerns.

chore: refactor `execute_cmd`

---

.github/workflows/test-integration.yml
.vscode/extensions.json
.vscode/settings.json
compiler/fm/src/file_reader.rs
compiler/fm/src/lib.rs
compiler/integration-tests/test/integration/browser/compile_prove_verify.test.ts
compiler/integration-tests/web-test-runner.config.mjs
compiler/noirc_errors/src/debug_info.rs
compiler/wasm/test/browser/index.test.ts

Resolves #1244 
This fixes the noir_wasm integration tests, such that they succeed. The fundamental problem was that the implementation of `source-resolver` isn't actually checking file paths to know what files to load. Instead, it was always returning the entry file as the source code, so this meant the stdlib was setup all wrong inside the compiler.
While this is a lazy way to implement the source-resolver, none of the stdlib file paths should be reaching it in the first place. So I've added an extra case in the `file_reader.rs` to never go to the filesystem for the stdlib, which we always embed.
Also note that some stuff in the integration test needed to change because proving takes 6.5 minutes and verifying takes 5 minutes.

fix(wasm): Avoid requesting stdlib paths from the source-resolver

---

tooling/acvm_backend_barretenberg/src/cli/info.rs
tooling/acvm_backend_barretenberg/test-binaries/mock_backend/src/info_cmd.rs
tooling/nargo_cli/build.rs

Resolves 
This PR uses the mock backend for all of the main integration test suite. This should speed up CI significantly as we don't have `bb` allocating a load of memory in order to return JSON.

chore(ci): use mock backend for all tests

---

.github/workflows/formatting.yml
.github/workflows/publish.yml
.github/workflows/test.yml
.github/workflows/wasm.yml
README.md

chore(ci): switch to using `Swatinem/rust-cache` action

---

.github/workflows/deny.yml
Cargo.lock
Cargo.toml
compiler/fm/Cargo.toml
compiler/noirc_driver/Cargo.toml
compiler/noirc_errors/Cargo.toml
compiler/noirc_evaluator/Cargo.toml
compiler/noirc_frontend/Cargo.toml
compiler/noirc_printable_type/Cargo.toml
compiler/utils/arena/Cargo.toml
compiler/utils/iter-extended/Cargo.toml
compiler/wasm/Cargo.toml
deny.toml
tooling/acvm_backend_barretenberg/Cargo.toml
tooling/lsp/Cargo.toml
tooling/nargo/Cargo.toml
tooling/nargo_cli/Cargo.toml
tooling/nargo_cli/src/cli/fs/inputs.rs
tooling/nargo_cli/tests/execute.rs
tooling/nargo_toml/Cargo.toml
tooling/noirc_abi/Cargo.toml
tooling/noirc_abi_wasm/Cargo.toml

Resolves 
This PR adds the same workflow as exists in https://github.com/noir-lang/acvm/pull/549 as well as fixing any issues causing errors.

chore(ci): Add `cargo deny` workflow

---

Cargo.lock
compiler/noirc_frontend/src/hir/def_map/mod.rs
tooling/lsp/Cargo.toml
tooling/lsp/src/lib.rs
tooling/lsp/src/types.rs

Resolves #2442 
This reworks types for the LSP to allow us to send back custom capabilities, such as
```json
{
"capabilities": {
"codeLensProvider": {
"resolveProvider": false
},
"nargo": {
"tests": {
"fetch": true,
"run": true,
"update": true
}
},
"textDocumentSync": {
"save": true
}
}
}
```
This also adds support for requesting metadata about tests, asking the LSP to run a test, and notifications for updating tests upon file save. These custom capabilities are in service of the Test Panel in vscode, but other LSP clients can decide not to implement them if they don't have testing APIs like vscode.
It's probably worth documenting the new UI elements that will be added to the vscode extension. I'll be including screenshots in the related PR that will be linked to this.

feat(lsp): Add nargo capabilities for test metadata

---

compiler/noirc_driver/src/lib.rs
compiler/noirc_frontend/src/hir/def_map/mod.rs
compiler/noirc_frontend/src/hir/mod.rs
compiler/noirc_frontend/src/lexer/lexer.rs
compiler/noirc_frontend/src/lexer/token.rs
compiler/noirc_frontend/src/node_interner.rs
tooling/nargo_cli/tests/compile_success_contract/non_entry_point_method/Nargo.toml
tooling/nargo_cli/tests/compile_success_contract/non_entry_point_method/src/main.nr

feat: Allow methods defined in a contract to be non-entry points

---

.github/workflows/release-source-resolver.yml

Resolves 
This PR pulls in the changes from https://github.com/noir-lang/noir/pull/2681

chore: switch `release-source-resolver.yml` to use yarn

---

.github/workflows/release-source-resolver.yml
.github/workflows/release.yml
.github/workflows/test-source-resolver.yml
.github/workflows/wasm.yml
compiler/fm/src/file_reader.rs
compiler/integration-tests/package.json
compiler/integration-tests/test/integration/browser/compile_prove_verify.test.ts
compiler/source-resolver/package.json
compiler/source-resolver/src/index.ts
compiler/source-resolver/src/index_node.ts
compiler/source-resolver/test/cjs_initialization.test.cjs
compiler/source-resolver/test/esm_initialization.test.mjs
compiler/source-resolver/types/index.d.ts
compiler/source-resolver/types/index_node.d.ts
compiler/wasm/package.json
compiler/wasm/test/index.d.ts
compiler/wasm/test/shared.ts
release-please-config.json
yarn.lock

The source-resolver is at version 1.1.3 -- this PR stops updating that package and creates a new package which will synced up with our noir version
Resolves

chore!: Change `noir-lang/noir-source-resolver` to `noir-lang/source-resolver`

---

compiler/noirc_frontend/src/hir/type_check/mod.rs
compiler/noirc_frontend/src/parser/errors.rs
compiler/noirc_frontend/src/parser/parser.rs

chore: Add deprecation message for default type in for loop

---

.github/workflows/release-noir-wasm.yml
.github/workflows/release.yml
compiler/wasm/build.sh

noir wasm is currently being published from a separate repo. This brings publishing of it in here, so its like the other repos
Resolves

chore: Add noir-wasm publishing as a workflow

---

.github/workflows/publish.yml

Unlike nightly which already has a tag, when a new tag is created, it gets set as the latest.
Resolves

chore: Make new daily nightly releases be pre-releases and non latest

---

compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs
tooling/nargo_cli/tests/execution_success/regression/src/main.nr

fix: keep the correct type for bitshift

---

compiler/noirc_frontend/src/hir/type_check/stmt.rs

Resolves #2583 
We now checks for literal overflows inside expressions.
If the result of the expression overflows, this should be handled during constant folding in PR #2713

fix: check for literal overflows in expressions

---

tooling/acvm_backend_barretenberg/src/cli/info.rs
tooling/acvm_backend_barretenberg/src/lib.rs
tooling/acvm_backend_barretenberg/src/proof_system.rs
tooling/nargo_cli/src/cli/codegen_verifier_cmd.rs
tooling/nargo_cli/src/cli/compile_cmd.rs
tooling/nargo_cli/src/cli/execute_cmd.rs
tooling/nargo_cli/src/cli/info_cmd.rs
tooling/nargo_cli/src/cli/prove_cmd.rs
tooling/nargo_cli/src/cli/verify_cmd.rs

Returning a boxed closure from `Backend,get_backend_info` makes it harder for us to pass the opcode support between functions while making use of `rayon`.
This PR defines a struct to contain information on the opcodes which the backend supports and a method to query this. We can then pass this around as we like.

chore: wrap backend info response in a struct instead of boxed closure

---

.github/workflows/test-integration.yml
.github/workflows/track-acvm.yml
compiler/integration-tests/package.json
compiler/integration-tests/test/integration/browser/compile_prove_verify.test.ts
yarn.lock

- Updates integration testing to use noirjs instead of individual packages
- Update ACVM tracking workflow
Resolves https://github.com/noir-lang/noir/issues/2738

chore: noirjs integration testing

---

.github/ISSUE_TEMPLATE/idea_action_plan.yml

As brought up in https://github.com/noir-lang/noir/pull/2672#issuecomment-1717667137 and first-hand experiences, the removal of the "Feature Request" GitHub Issue template in https://github.com/noir-lang/noir/pull/2672 adds extra frictions to creating well-defined enhancement issues ready to be worked on.
This PR restores the issue template as "Idea Action Plan" for better clarity on the distinctions between:
- **"Ideas" (GitHub Discussions)** that could use further grooming, discussing and upvoting
- **"Idea Action Plan" (GitHub Issue)** as scoped and directly tacklable tasks
Demo: https://github.com/noir-lang-test/noir/issues/new/choose

chore(github): Add "Idea Action Plan" Issue template

---

compiler/noirc_driver/src/lib.rs

Resolves 
This PR has a quick fix for the panic that Lisa was experiencing where Nargo cannot find any contracts within a contract package.
Rather than panicking when we assert that we have a single contract, we return an error message similar to that for when a binary crate has no `main` function.

fix: add error message for a contract package with no contracts

---

Cargo.lock
Cargo.toml
compiler/wasm/Cargo.toml
compiler/wasm/src/lib.rs
tooling/lsp/Cargo.toml
tooling/lsp/src/lib.rs
tooling/nargo_cli/Cargo.toml
tooling/nargo_cli/src/cli/execute_cmd.rs
tooling/nargo_cli/src/cli/test_cmd.rs
tooling/noir_js/package.json
tooling/noirc_abi_wasm/Cargo.toml
tooling/noirc_abi_wasm/src/lib.rs
yarn.lock

Resolves 
This PR migrates to ACVM 0.27.0 to unblock getting the LSP working in the browser.

chore: migrate to ACVM 0.27.0

---

compiler/fm/Cargo.toml
compiler/fm/src/file_reader.rs

Resolves 
This change avoids the `source-resolver` in a WASI environment, which works with normal rust filesystem calls. This is needed to remove wasm-bindgen from the LSP with the WASI target.

chore: Avoid source-resolver in a WASI environment

---

rust-toolchain.toml

Resolves 
This adds the WASI target to the toolchain. This will allow us to compile the LSP into the WASI target.

chore: Add wasm32-wasi target to the toolchain

---

Cargo.toml
tooling/lsp/src/lib.rs
tooling/nargo_cli/src/cli/lsp_cmd.rs

Resolves 
This removes the hardcoded `barretenberg_blackbox_solver` from the LSP and instead requires it to be passed when the LSP server is constructed. This removes the wasm-bindgen code added to the LSP when trying to compile to the WASI target.
It required a new struct to wrap the dynamic trait and proxies to the backend.

chore(lsp): Construct the LSP with a blackbox solver

---

noir_stdlib/src/collections/vec.nr

Resolves #2775
`Vec::get` used to require a mutable Vec since we did not automatically dereference `&mut T` -> `T` for objects of method calls before PR #2581. Now that this PR is merged, it can be immutable.
- The type signature of `Vec::get` will need to be updated

fix: Make `Vec::get` accept immutable `Vec`s

---

compiler/noirc_frontend/src/hir/type_check/mod.rs
compiler/noirc_frontend/src/hir_def/types.rs
compiler/noirc_frontend/src/monomorphization/mod.rs
compiler/noirc_frontend/src/parser/errors.rs
compiler/noirc_frontend/src/parser/parser.rs

Remove the deprecation warning about loop iterators.
Default integers to u64 instead of field, since it was only used for loops and array indexing.
Related to #2723

feat!: Default integers to u64

---

.github/workflows/acvm-release.yml

Changes ACVM_RELEASE_TOKEN to NOIR_RELEASE_TOKEN
Resolves

chore: use `secrets.NOIR_RELEASES_TOKEN` for ACVM

---

acvm-repo/blackbox_solver/src/lib.rs

Resolves #2755
Supercedes https://github.com/noir-lang/acvm/pull/557

fix(acvm): return false rather than panicking on invalid ECDSA signatures

---

tooling/nargo_cli/src/cli/fs/program.rs
tooling/nargo_cli/src/errors.rs

This changes the unwrap to a FileSystemError incase there is a malformed serialized program. 
Resolves

chore: Change .unwrap to an error variant when reading program from file

---

tooling/backend_interface/src/cli/contract.rs
tooling/backend_interface/src/cli/gates.rs
tooling/backend_interface/src/cli/info.rs
tooling/backend_interface/src/cli/mod.rs
tooling/backend_interface/src/cli/prove.rs
tooling/backend_interface/src/cli/write_vk.rs
tooling/backend_interface/src/lib.rs

When we get a backend error, this makes it so that we can see what error the backend displayed as a utf8 encoded string.
Resolves

chore: Add more information to backend errors

---

noir_stdlib/src/lib.nr

fix: Silence unused variable warnings in stdlib

---

compiler/noirc_driver/src/lib.rs

Resolves 
This PR skips the program caching logic if the user has specified that they want to see brillig, SSA or ACIR printed to the console.

chore: force compilation if debug flags are set

---

compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs

Resolves #2787
The error message in the issue is outdated and already fixed, but attempting to run it still results in a panic with "attempting to subtract with overflow."
~~This PR adds a check in the flattening pass that resembles a check done in the simplify cfg pass. If a jmpif condition is constant, inline the block it jumps to and discard the other, unreachable block(s). Adding this check in the flattening pass makes the pass slightly larger bug means there is no need to always have the simplify cfg pass directly before flattening.~~
~~Note that this avoids the "attempting to subtract with overflow" issue rather than fixing the underlying cause. I'm still investigating this and will make a separate PR.~~
All of the above is invalid, I've added a commit to reverse the previous …

fix: Fix subtract with underflow in flattening pass

---

compiler/fm/src/lib.rs
compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
compiler/noirc_frontend/src/hir/def_collector/errors.rs
compiler/noirc_frontend/src/hir/mod.rs
compiler/noirc_frontend/src/hir_def/types.rs

Resolves https://github.com/noir-lang/noir/issues/2658
This is a rather comprehensive fix for the issue where a module can be declared twice. It is comprehensive because it includes two fixes (and some error message improvements), either individually would fix the issue but I've included all for completeness.
1. Keep track of which files were already used as modules and report an error if one is ever used twice. Although this error is more difficult (but still possible) to trigger now after the next change.
2. Change the path a `mod foo;` statement looks at to import `foo`. Previously we checked both `./foo.nr` and `./current_mod_name/foo.nr`. Now we only check the first if the current module is named `main.nr`, `lib.nr`, `mod.nr`, or `{foo}/{foo}.nr` where `foo` can be anything as long …

fix!: Issue an error when a module is declared twice & fix module search path

---

compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
compiler/noirc_frontend/src/monomorphization/mod.rs
compiler/noirc_frontend/src/node_interner.rs

Resolves 
Found while testing https://github.com/noir-lang/noir/issues/2658.
In short: we were using `interner.function_name` while reporting errors for private functions. Since a function's name requires the FuncMeta which is only filled out during name resolution itself, it may not be initialized at the time of reporting. This crate happened to be one case where it was not. To fix this, I've moved the function's name to the FunctionModifiers struct which is filled out before name resolution.

fix: Fix panic in some cases when calling a private function

---

compiler/noirc_frontend/src/hir/type_check/stmt.rs

Resolves #2804
The actual and expected types when issuing a type error for an assignment of different types were swapped so I've swapped them back.

fix: Error message for assigning the wrong type is backwards #2804 

---

compiler/noirc_frontend/src/lexer/errors.rs
compiler/noirc_frontend/src/lexer/lexer.rs
tooling/nargo_cli/tests/execution_success/strings/src/main.nr

Resolves https://github.com/noir-lang/noir/issues/2657
Implements escape sequences for string literals
- String literals can now use "\t" to insert a tab character, "\n" for a newline, "\r" for a carriage return, "\0" for a null character, "\"" for a quote, and "\\" to insert a backslash. As an example, the string `"Hi\tHello\"There"` will be printed out as `Hi	Hello"There`

feat: Implement string escape sequences

---

.github/workflows/abi_wasm.yml
.github/workflows/acvm-rust.yml
.github/workflows/test-integration.yml
.github/workflows/wasm.yml

Use Nix cache for WASM based builds
Resolves

chore: utilize nix cache for wasm builds

---

tooling/noirc_abi_wasm/src/errors.rs
tooling/noirc_abi_wasm/src/lib.rs
tooling/noirc_abi_wasm/test/browser/errors.test.ts
tooling/noirc_abi_wasm/test/node/errors.test.ts
tooling/noirc_abi_wasm/test/shared/array_as_field.ts
tooling/noirc_abi_wasm/test/shared/field_as_array.ts
tooling/noirc_abi_wasm/test/shared/uint_overflow.ts

Resolves 
This PR changes the behaviour of `noirc_abi_wasm` to throw on errors rather than returning a string.

feat(abi): throw errors rather than returning string from `noirc_abi_wasm`

---

compiler/noirc_frontend/src/hir/resolution/resolver.rs
compiler/noirc_frontend/src/hir/type_check/expr.rs
compiler/noirc_frontend/src/hir/type_check/mod.rs
compiler/noirc_frontend/src/hir_def/expr.rs
compiler/noirc_frontend/src/hir_def/traits.rs
compiler/noirc_frontend/src/hir_def/types.rs
compiler/noirc_frontend/src/monomorphization/mod.rs
tooling/nargo_cli/tests/execution_success/trait_where_clause/Nargo.toml
tooling/nargo_cli/tests/execution_success/trait_where_clause/src/main.nr

This needs to be merged after https://github.com/noir-lang/noir/pull/2652 and https://github.com/noir-lang/noir/pull/2716 - this PR also unfortunately includes the changes from that and the diff is currently quite ugly
Progress on https://github.com/noir-lang/noir/issues/2568
This implements the type checker & monomorphizer passes for trait bounds. Changes include:
1. Added `HirMethodReference` which can reference either a concrete func id, or a trait method, which will be resolved to a concrete FuncId during monomorphization:
```rust
pub struct TraitMethodId {
pub trait_id: TraitId,
pub method_index: usize, // index in Trait::methods
}
pub enum HirMethodReference {
FuncId(FuncId),
TraitMethodId(TraitMethodId),
}
```
2. `lookup_method` now returns a `HirMethodReference`. if it sees a …

feat(traits): Implement trait bounds typechecker + monomorphizer passes

---

.github/workflows/auto-pr-rebuild-script.yml

Resolves 
Currently the PR to automatically update the build artifacts is being committed by the `github-actions` bot but this [doesn't allow for workflows to run on the created PR](https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-536204092). A workaround for this is for us to make the PR as @kevaundray which will then run CI as usual.
The alternative for this is that we have to always close and reopen the PR before CI will run.

chore(ci): ensure that the artifact rebuilding PR will run CI

---

compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_directive.rs
compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/generated_acir.rs

Resolves 
Currently we're inserting a predicate into the `directive_quotient` brillig bytecode as well as into the actual Brillig ACIR opcode. This means that we've got an entire codepath which is never used (as it corresponds to a situation in which the brillig bytecode is never executed.)
We should then remove this predicate from `directive_quotient` and rely on the predicate on the Brillig ACIR opcode instead.

feat: remove redundant predicate from brillig quotients

---

.github/workflows/acvm-test-acvm-js.yml

chore(ci): fix `acvm_js` tests

---

.github/workflows/auto-pr-rebuild-script.yml

The last github action was failing when there was nothing to commit, so we conditionally run this step if there is something to commit
Resolves

fix: Conditionally run the "Create or Update PR" step in acir artifacts rebuild workflow

---

compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs
compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs

Resolves 
This PR uses `AcirType::field()` to reduce some verbosity and removes some unnecessary `AcirValues` which just get unwrapped again immediately.

chore: remove unnecessary `AcirValue`s

---

compiler/noirc_driver/src/lib.rs
compiler/noirc_errors/src/reporter.rs
compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
compiler/noirc_frontend/src/hir/def_collector/errors.rs
compiler/noirc_frontend/src/hir/def_collector/mod.rs
compiler/noirc_frontend/src/hir/def_map/aztec_library.rs
compiler/noirc_frontend/src/hir/def_map/mod.rs
compiler/noirc_frontend/src/hir/resolution/resolver.rs
compiler/noirc_frontend/src/parser/parser.rs

Refactoring DefCollector to return CompilationErrors
```
pub struct CompilationErrors {
pub parser_errors: Vec<(ParserError, FileId)>,
pub def_errors: Vec<(DefCollectorErrorKind, FileId)>,
pub resolver_errors: Vec<(ResolverError, FileId)>,
pub type_errors: Vec<(TypeCheckError, FileId)>,
}
```
The motivation for this changes are:
The refactoring of the test will be in next code review, to keep this one as short as possible

chore(errors): Refactor errors representation in compiler

---

tooling/noir_js/test/backend/backend_interface.ts
tooling/noir_js/test/backend/barretenberg.ts
tooling/noir_js/test/node/e2e.test.ts

Resolves 
This PR defined a `Backend` interface which defines how a JS backend will expose proving and verifying. This can be refined later.

chore: add initial version of `Backend` interface for `noir_js`

---

compiler/fm/src/file_reader.rs

Resolves 
Breaking out a necessary change from #2649 to keep PRs small.
This PR moves the code relevant to loading stdlib files out from the two architecture specific functions into a single entrypoint function.

fix: remove duplication of code to load stdlib files

---

compiler/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs

fix: Remove cast for field comparisons in brillig

---

acvm-repo/acvm/src/compiler/transformers/csat.rs
acvm-repo/acvm/src/compiler/transformers/fallback.rs

Resolves 
This PR removes some unnecessary cloning from the CSAT transformer and replaces some for-loops with iterators.

chore: miscellaneous ACVM fixups

---

compiler/noirc_driver/src/contract.rs
compiler/noirc_driver/src/lib.rs
compiler/noirc_frontend/Cargo.toml
compiler/noirc_frontend/src/hir/def_map/mod.rs
compiler/noirc_frontend/src/hir/def_map/module_data.rs
compiler/noirc_frontend/src/lexer/token.rs
compiler/noirc_frontend/src/node_interner.rs
tooling/nargo/src/artifacts/contract.rs
tooling/nargo_cli/src/cli/compile_cmd.rs
tooling/noirc_abi/src/lib.rs

Exposes in the contract artifacts all events of a given contract. An event is identified by using the `event` attribute in a contract scope:
```
contract Example {
#[event]
struct MyEvent {
a: Field,
}
...
```
Working towards https://github.com/AztecProtocol/aztec-packages/issues/2323

feat: Contract events in artifacts

---

Cargo.lock
acvm-repo/acir/Cargo.toml
acvm-repo/acir/src/circuit/mod.rs
acvm-repo/acir/src/native_types/witness_map.rs

Resolves 
This logic is now incompatible with the entirety of the Noir ecosystem so there's no reason to include it anymore.

chore: remove messagepack serialization logic

---

compiler/noirc_driver/src/lib.rs
compiler/wasm/src/compile.rs
tooling/nargo/src/ops/test.rs
tooling/nargo_cli/src/cli/codegen_verifier_cmd.rs
tooling/nargo_cli/src/cli/compile_cmd.rs
tooling/nargo_cli/src/cli/execute_cmd.rs
tooling/nargo_cli/src/cli/info_cmd.rs
tooling/nargo_cli/src/cli/prove_cmd.rs
tooling/nargo_cli/src/cli/verify_cmd.rs

Resolves 
This PR removes the hardcoding of `output_debug` and forces a recompilation if it is set.

fix: force recompilation when `output_debug` flag is set.

---

tooling/backend_interface/Cargo.toml

Resolves 
This switches `backend-interface` over to using the workspace MSRV so that it stays in line.

chore: use workspace rust version in `backend-interface` crate

---

release-please-config.json

This will now have the release PR say `chore: Release Noir(0.13.0)`
Resolves

chore: use Noir number in release PR

---

Cargo.lock
acvm-repo/acir/src/circuit/black_box_functions.rs
acvm-repo/acir/src/circuit/mod.rs
acvm-repo/acir/src/circuit/opcodes/black_box_function_call.rs
acvm-repo/acir/src/lib.rs
acvm-repo/acir/src/native_types/expression/mod.rs
acvm-repo/acir_field/src/generic_ark.rs
acvm-repo/acir_field/src/lib.rs
acvm-repo/acvm/src/compiler/mod.rs
acvm-repo/acvm/src/compiler/optimizers/redundant_range.rs
acvm-repo/acvm/src/lib.rs
acvm-repo/acvm/src/pwg/brillig.rs
acvm-repo/acvm/src/pwg/directives/mod.rs
acvm-repo/acvm/src/pwg/directives/sorting.rs
acvm-repo/acvm_js/src/lib.rs
acvm-repo/barretenberg_blackbox_solver/src/lib.rs
acvm-repo/barretenberg_blackbox_solver/src/wasm/mod.rs
acvm-repo/blackbox_solver/src/lib.rs
acvm-repo/brillig/src/lib.rs
acvm-repo/brillig_vm/src/lib.rs
acvm-repo/stdlib/src/blackbox_fallbacks/blake2s.rs
acvm-repo/stdlib/src/blackbox_fallbacks/utils.rs
acvm-repo/stdlib/src/lib.rs
tooling/lsp/Cargo.toml
tooling/lsp/src/lib.rs
tooling/nargo_toml/src/lib.rs

Resolves 
A number of crates didn't have our standard linting setup so I've added it and fixed all the warnings. As a result of this I've removed a number of unnecessary dependencies.

chore: add standard linting setup to all crates

---

compiler/integration-tests/test/integration/browser/compile_prove_verify.test.ts

Resolves 
This PR refactors the `compile_prove_verify` test to make use of more helper functions and generally easier to work with.

chore: refactor integration test

---

acvm-repo/acvm_js/package.json

This field indicates that we don't want to publish the package to npm registry
Resolves

chore: remove `private: true` on package.json in acvm_js

---

Cargo.lock
compiler/fm/Cargo.toml
tooling/lsp/Cargo.toml

Resolves 
This should have been done as part of #2649

chore: move `wasm-bindgen` dependency to `noir_lsp`

---

deny.toml

The deny action is failing on master due to some of our dependencies using MPL-2.0 and also an issue with respects to duplicate entries in Cargo.toml.
For the first, I added MPL-2.0 to deny.toml and the for the second I regenerated the .lock file, but this got rolled back for now. This PR only adds the MPL license
Resolves

chore: Add MPL-2.0 to allow list for deny action

---

Cargo.lock
acvm-repo/barretenberg_blackbox_solver/Cargo.toml
tooling/backend_interface/Cargo.toml

Resolves 
This PR fixes `cargo deny`.

chore: bump `reqwest` to 0.11.20

---

acvm-repo/acvm/src/pwg/brillig.rs
acvm-repo/acvm/tests/solver.rs
acvm-repo/acvm_js/src/foreign_call/inputs.rs
acvm-repo/acvm_js/src/foreign_call/outputs.rs
acvm-repo/brillig/src/foreign_call.rs
acvm-repo/brillig/src/lib.rs
acvm-repo/brillig_vm/src/lib.rs
compiler/noirc_evaluator/src/brillig/brillig_ir.rs
compiler/noirc_printable_type/src/lib.rs
tooling/nargo/src/ops/foreign_calls.rs

feat!: Maintain shape of foreign call arguments

---

.github/workflows/test-noir-js.yml

See [here](https://github.com/noir-lang/noir/issues/2930#issuecomment-1742870802)
Not sure why github only shows the job name and not workflow-name/job-name
Resolves

chore(ci): Rename Noir.js test job

---

.github/workflows/test-integration.yml
compiler/integration-tests/package.json
compiler/integration-tests/test/integration/browser/compile_prove_verify.test.ts
compiler/integration-tests/test/integration/browser/recursion.test.ts
yarn.lock

Resolves #2832
This PR updates the integration tests to use the new JS packages in order to simplify the code. I've also fixed all the breakages in this test suite.

chore: use new JS packages in integration tests

---

tooling/nargo_cli/tests/execution_success/assert_statement/src/main.nr

No issue as minor chore
I want to make a script to enable easy regeneration of the artifacts for `double_verify_proof` when the inner proof circuit has changed due to internal bb changes. I want to maintain in the test that the inner proof has public inputs, however, none of our simple assertion program use a public input.

chore: Make one input public in simple assertion program

---

compiler/integration-tests/test/integration/browser/compile_prove_verify.test.ts
tooling/noir_js/src/program.ts

Provides lazy initialization when noirProgram.init() is not called before.
Resolves noir_js should not "require" to .init()#2952

chore: Perform lazy initialization inside `noir_js`

---

compiler/noirc_frontend/src/hir/type_check/errors.rs
compiler/noirc_frontend/src/hir/type_check/expr.rs

Resolves 
Working on #2911 I realized the error message issued was that the result of the multiplication didn't match the function type. When first two checks should have occured:
1. This should not have been a multiplication at all, but a sequnce of a for loop and dereference. This requires parser changes I'll address in another PR.
2. We should have checked that the operand types `()` and `&mut ...` aren't valid to multiply together. This was caused by a catch-all case to make all unit operations valid, for some unknown reason. I've removed this case and improved the error message to mention the specific binary operator that was used.

fix: Improve error message when multiplying unit values

---

Cargo.lock
compiler/noirc_driver/src/lib.rs
compiler/noirc_evaluator/src/lib.rs
tooling/lsp/src/lib.rs
tooling/nargo/Cargo.toml
tooling/nargo/src/errors.rs
tooling/nargo/src/ops/test.rs
tooling/nargo_cli/src/cli/execute_cmd.rs
tooling/nargo_cli/src/cli/test_cmd.rs

Resolves https://github.com/noir-lang/noir/issues/2929
Also removes string matching in nargo test by exposing an error in compile_no_check instead of a diagnostic.

feat: Nargo test runtime callstacks and assert messages without string matching

---

tooling/nargo_cli/tests/execution_success/trait_function_calls/Nargo.toml
tooling/nargo_cli/tests/execution_success/trait_function_calls/src/main.nr

This test proves that trait function calls from inside the body of other trait functions are resolved and executed correctly. All combinations of:
default implementation
override with default
override with no default
are tested, for both the caller and callee. For now, this tests method calls only (functions with self as first parameter). Once function calls via `Self::function_name()` are implemented, the test can be extended to cover that as well.

chore(traits): added exhaustive test for trait function calls

---

compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
compiler/noirc_frontend/src/hir/resolution/resolver.rs
compiler/noirc_frontend/src/hir/type_check/expr.rs
compiler/noirc_frontend/src/hir_def/expr.rs
compiler/noirc_frontend/src/hir_def/traits.rs
compiler/noirc_frontend/src/monomorphization/mod.rs
compiler/noirc_frontend/src/node_interner.rs
tooling/nargo_cli/tests/execution_success/trait_self/src/main.nr
tooling/nargo_cli/tests/execution_success/trait_where_clause/src/main.nr
tooling/nargo_cli/tests/execution_success/trait_where_clause/src/the_trait.nr

Progress towards https://github.com/noir-lang/noir/issues/2568
This adds support for two trait method resolution cases that previously didn't work:
1. Trait methods calling static trait methods in the default implementation via Self. Now the call is properly resolved as `HirExpression::HirMethodReference`
```rust
trait ATrait {
fn static_method() -> Field {
Self::static_method_2() // This used to fail, ok now
};
fn static_method_2() -> Field;
}
```
2. The second is something I missed when implementing where clauses - static methods need to be resolvable with a colon syntax via the NamedGeneric
```rust
fn whatever<T>(t: T) -> Field where T: ATrait {
T::static_method() // this used to fail, ok now
}
```
Even though the `Self::whatever` and `T::whatever` are Paths, I've handled the …

feat(traits): Improve support for traits static method resolution

---

tooling/lsp/src/codelens/mod.rs
tooling/lsp/src/codelens/test_run.rs
tooling/lsp/src/codelens/tests.rs
tooling/lsp/src/lib.rs

Groundwork for #2941 
There's two issues with the LSP as it currently stands:
1. Most of the code resides in a single file whilst the logic is very amenable to breaking it down into components.
2. The usage of futures has been allowed to infect all levels of the LSP logic. This makes it difficult to use nice language features such as `Result` and `?` due to the need to wrap the result in a future.
This PR tackles these issues by creating new modules for code lenses which are responsible for serving these requests. Now that they're isolated, we could have an "inner" implementation which is synchronous and only have futures on a facade which is called by the LSP router.

chore: refactor LSP code for readability and dev ex

---

compiler/integration-tests/test/browser/compile_prove_verify.test.ts
compiler/integration-tests/test/browser/recursion.test.ts
compiler/integration-tests/test/node/smart_contract_verifier.test.ts
compiler/wasm/src/compile.rs
compiler/wasm/test/browser/index.test.ts
compiler/wasm/test/node/index.test.ts
compiler/wasm/test/shared.ts

Resolves #2972 
This PR changes `noir_wasm` to output the same artifacts as Nargo does.

feat(wasm)!: update wasm artifacts to match cli artifacts

---

acvm-repo/acvm/src/compiler/mod.rs
acvm-repo/acvm/src/compiler/optimizers/mod.rs
acvm-repo/acvm/src/compiler/transformers/mod.rs
compiler/noirc_evaluator/src/ssa.rs

Resolves 
Currently we perform any fallback transformations before we perform any ACIR-level optimizations, this is suboptimal for a couple of reasons:
- We're potentially decomposing ACIR opcodes which may have been optimized away (e.g. range opcodes) which we then won't optimize away.
- We cannot perform optimization separately from transformation.
This PR delays the fallback transformation until after all the optimizations have been made. This allows us to split `acvm::compiler::compiler` into two discrete steps: Optimizations which don't target a particular backend and transformations which modify the ACIR to match a backend.
As a result of this I've updated `create_circuit` to automatically perform ACIR-level optimizations immediately after generation. This ensures that the Noir …

feat(acvm): separate ACVM optimizations and transformations

---

tooling/lsp/src/codelens/mod.rs

Resolves #2942
This PR adds a codelens to run `nargo info` on programs/contracts.

feat(lsp): add "info" codelens

---

compiler/noirc_frontend/src/hir/aztec_library.rs
compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
compiler/noirc_frontend/src/hir/def_map/mod.rs
compiler/noirc_frontend/src/hir/mod.rs

Transforming after type unification made the code to transform the hir very brittle. Updated that transformation to happen before type unification. Also fixed for statements in aztec_library and updated the compute selector path.

fix: Transform hir before type checks 

---

tooling/noirc_abi/src/input_parser/mod.rs

It turns out we were already checking for overflow of the inputs but not in the hexadecimal case. So I simply added the check also for inputs in hex.
Resolves #2858

fix: check for overflow with hexadecimal inputs

---

acvm-repo/acvm/src/compiler/optimizers/mod.rs
tooling/nargo/src/ops/test.rs
tooling/nargo_cli/tests/noir_test_failure/should_fail_mismatch/src/main.nr
tooling/nargo_cli/tests/noir_test_success/should_fail_with_matches/src/main.nr

ACIR optimization was leaving assertion messages untouched, breaking those in some scenarios and causing issues with assertion failed matching with nargo test. Also, compile time errors without messages were considered always an error, when they might be a success if the test states that it should always fail.

fix: ACIR optimizer should update assertion messages

---

acvm-repo/brillig_vm/src/lib.rs

The structure `VM` of crate `brillig_vm` has method `program_counter` that should return copy of field. The signature of method is wrong because the getter consumes instance. 
Resolves issues of VM work. 
The PR change one line in method `program_counter`, it changes type of self from `self` to `&self`.

fix: fix method `program_counter`, change method signature

---

compiler/noirc_frontend/src/hir/aztec_library.rs
compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
compiler/noirc_frontend/src/parser/mod.rs
compiler/noirc_frontend/src/parser/parser.rs

Fixes the aztec_library after adding nargo fmt. Changes the new SortedModule to include also sorted submodules.

fix: Fix aztec library after nargo fmt

---

flake.nix

This PR restores an older Nix filter to include `.nr` and `.sol` files in builds.
WASM builds of the compiler would fail compiling because they couldn't add `noir_stdlib` to the build.
The stdlib wasn't being embedded into the wasm file. The output wasm file was lighter (~1.2MB lighter compared to previous builds) but it couldn't compile contracts.
N/A
N/A
Thanks @sirasistant for the help debugging this!

fix: include .nr and .sol files in builds

---

compiler/wasm/test/node/index.test.ts

Resolves 
This PR fixes the CI failure in #3039 by making the paths provided to `noir_wasm` absolute.

chore: make paths in `wasm` tests absolute

---

noir_stdlib/src/grumpkin_scalar.nr
noir_stdlib/src/grumpkin_scalar_mul.nr

This PR fixes an issue with compiling Aztec.nr packages with noir v0.16.0
v0.16.0 of the compiler would error saying some functions were not publicly accessible from the Noir standard library.
Adds `pub` modifiers to Grumpkin functions used in Aztec.nr.
N/A
Related to AztecProtocol/aztec-packages#2644

fix: add `pub` modifier to grumpkin functions

---

acvm-repo/acvm/src/compiler/mod.rs
acvm-repo/acvm/src/compiler/optimizers/mod.rs
acvm-repo/acvm/src/compiler/transformers/mod.rs

`acvm::compiler::compile` builds up a transformation map over the optimization and transformation steps and transforms the assert messsages using this once at the end. https://github.com/noir-lang/noir/pull/3010 broke assert message transformations as it applied the map after the optimization transformation resulting in the final transformation map being incorrect.
This PR fixes #3010 by adding an internal optimize function which avoids this extra transformation.

fix: prevent duplicated assert message transformation

---

compiler/noirc_driver/src/lib.rs
compiler/noirc_errors/src/reporter.rs
tooling/nargo_cli/src/cli/check_cmd.rs
tooling/nargo_cli/src/cli/compile_cmd.rs
tooling/nargo_cli/src/cli/fmt_cmd.rs
tooling/nargo_cli/src/cli/test_cmd.rs

chore: Add a flag to nargo to silence warnings

---

compiler/noirc_frontend/src/hir/type_check/expr.rs
compiler/noirc_frontend/src/hir/type_check/stmt.rs
compiler/noirc_frontend/src/parser/parser.rs
tooling/nargo_cli/tests/execution_success/assign_ex/src/main.nr

Resolves #3057
The left hand side of an assignment previously did not allow any parenthesis. This made parsing something like `(*a)[0]` impossible since doing `*a[0]` would dereference the result of the index rather than the other way around. This PR also fixes 2 quick, related type errors to the issue.

fix: Parse parenthesized lvalues

---

tooling/noir_js_backend_barretenberg/src/index.ts

Makes `BarretenbergBackend.instantiate()` available for user to call.
This makes api consistent with `noir_js` approach to lazilly instatiate when user does not choose to do so upfront, while enabling user to initialize before any execution steps.
This is to wrap: Cleanup Noir.js#2910
Resolves

chore: make backend instantiate available

---

tooling/noir_js/test/node/e2e.test.ts
tooling/noir_js/test/node/smoke.test.ts

Resolves 
This PR updates the noir.js tests to import using resolution through the `package.json` to ensure that the imports it's using are publicly available.

chore: update imports in noir_js tests

---

compiler/noirc_frontend/src/hir/type_check/expr.rs
tooling/nargo_cli/tests/compile_success_empty/auto_deref/Nargo.toml
tooling/nargo_cli/tests/compile_success_empty/auto_deref/src/main.nr

Resolves part of #3042
Implements automatic dereferencing when indexing references pointing to arrays. Notably, this PR does not include automatic dereferencing for lvalues on the lhs of an assignment so `a[0] = 1;` will not work if `a : &mut [Field]`, yet `a[0]` in an expression context will. I'm going to split the handling of lvalues into another PR.

feat: Implement automatic dereferencing for index expressions

---

tooling/noir_js/src/program.ts
tooling/noir_js_backend_barretenberg/src/index.ts
tooling/noir_js_backend_barretenberg/src/types.ts
tooling/noir_js_types/src/types.ts

Working on autogenerated docs at #3035 I came up with some improvements to UX and Devex for NoirJS.
Not really a problem, just addressing some DevEx concerns and UX. Before this PR, standard usage was:
```js
const backend = new BarretenbergBackend(circuit, 4);
const noir = new Noir(circuit, backend);
```
This could be improved
- It adds the destroy method to proxy to backend_barretenberg, saving user's resources.
- Adds an "options" object that is passed to the initialisation of barretenberg:
```js
// previously
new Backend(circuit, 4) // what's the 4?
// now
new Backend(circuit { numOfThreads : 4}) // oh it's the number of threads!
```
BEGIN_COMMIT_OVERRIDE
feat: Add `destroy` method to `Noir` (#3105)
feat: Add an options object to `BarretenbergBackend` constructor (#3105) …

feat: adding destroy and options object

---

compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs

chore: remove unnecessary clone when executing brillig

---

acvm-repo/acvm_js/src/execute.rs
tooling/nargo/src/ops/execute.rs

Resolves 
We currently don't use `circuit.get_assert_message` as previously it caused issues related to ownership over the circuit's opcodes. Now we pass the opcodes to the ACVM by reference, we can just use the `circuit.get_assert_message` directly.

chore: use `circuit.get_assert_message` instead of closure/helper function

---

compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs

Resolves 
It's unnecessary to truncate after `x * <u1 value>` as the result is bounded by `x`. We can then omit this instruction when multiplying integers of width 1 together.
I'm not sure if signed integers of width 1 need special casing on this.

feat: Remove unnecessary truncation of boolean multiplication

---

compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/acir_variable.rs

Resolves 
This PR fixes an issue I was experiencing on another branch where I was getting an infinite loop due to `1 * witness` being represented as an expression instead of a witness. We now automatically simplify any `AcirVarData` to the simplest allowed form to avoid this.

chore: simplify `AcirVarData` where possible in multiplication

---

.vscode/extensions.json

The Noir repo does not currently enforce any spell checks, which could lead to:
- Misspelt APIs, commands, flags, etc. --> user confusions
- Mismatched interfaces due to e.g. American vs British spelling of the same function --> dev frictions and/or user confusions
This PR doesn't enforce a spell check, but adds [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) as a recommended VS Code extension for users building in this repo.
Further spell alignments can then be made and enforced more easily through the shared config file [cspell.json](https://github.com/noir-lang/noir/blob/004f8dd733cb23da4ed57b160f6b86d53bc0b5f1/cspell.json) of this repo.
Referenced https://github.com/AztecProtocol/aztec-packages/pull/2817.

chore: Add Spell Checker to recommended VS Code extensions

---

deny.toml

Resolves 
This PR allows dependencies using the BSL license. This is needed to use `easy-repl` in #2995.
https://fossa.com/blog/open-source-licenses-101-boost-software-license/

chore: allow dependencies with the boost source license (BSL-1.0)

---

compiler/noirc_evaluator/src/ssa/ir/instruction.rs

Do not simplify div/mod when denominator is not known, because if it is null, it will have side-effects.
Resolves #2584
Closes #2741
Closes #3053
We do not simplify div or mod in dead instruction elimination, except if the denominator is constant and not null, in which case there will not be any side effect and we can simplify it.
I do not add a test case because I requires  'execution failure', as  div/mod side effects occur during execution.
This PR supersede PR #2741 and #3053, which can be closed.
Allowing simplification for constant denominator solves the issue with the sha256 test cases on these PRs.

fix: do not perform dead instruction elimination on mod,div unless rhs is constant

---

tooling/debugger/src/lib.rs
tooling/nargo_cli/src/cli/debug_cmd.rs

This is a follow up PR to https://github.com/noir-lang/noir/pull/2995, addressing this comment: https://github.com/noir-lang/noir/pull/2995#discussion_r1358237222.
Passes circuit to debugger by reference instead of moving it.

chore(debugger): avoid taking ownership of Circuit when building debug context 

---

tooling/debugger/src/lib.rs

Resolves https://github.com/noir-lang/noir/pull/2995#discussion_r1358235413
This PR addresses a workaround for the borrow checker in #2995.
`repl` holds two references to `Context` so we can't move the witness map out of the contained `ACVM` instance while `repl` (and so the references) exists.
As we don't need `repl` once we've finished execution, this PR explicitly drops `repl` to remove those references, We can then unwrap the `RefCell` and get at the contained `Context` to pull out the witness map.
cc @mverzilli @ggiraldez as you may be interested in this solution.

chore: make `acvm` a non-optional field on `DebugContext`

---

compiler/noirc_frontend/src/lexer/errors.rs
compiler/noirc_frontend/src/parser/errors.rs
compiler/noirc_frontend/src/parser/parser.rs

chore: transforming lexical errors into parser errors
Resolves #3125

chore: transforming lexical errors into parser errors

---

compiler/noirc_frontend/src/hir/aztec_library.rs

The lookup method was updated. Aztec's macros was calling it, but it was not updated
Resolves

chore: Fix aztec branch

---

docs/docusaurus.config.js

update the editUrl that links to github to "edit this page".
links to old docs repo

fix(docs): update `editUrl` path for docusaurus

---

acvm-repo/acir/src/circuit/mod.rs
compiler/noirc_driver/src/program.rs
tooling/nargo/src/artifacts/mod.rs

Resolves 
This PR pulls out the changes related to not panicking on an invalid circuit from https://github.com/noir-lang/noir/pull/3156.

fix: return error rather than panicking on unreadable circuits

---

tooling/backend_interface/src/cli/contract.rs
tooling/backend_interface/src/cli/verify.rs
tooling/backend_interface/src/cli/write_vk.rs
tooling/backend_interface/src/proof_system.rs
tooling/backend_interface/src/smart_contract.rs
tooling/backend_interface/test-binaries/mock_backend/src/write_vk_cmd.rs

Resolves 
This argument is unused by `bb` ([see here](https://github.com/AztecProtocol/aztec-packages/blob/434228050ffc65277191aa5b8df6207a3323f466/barretenberg/cpp/src/barretenberg/bb/main.cpp#L375)). I've then removed it.

chore: remove unused argument from `write_vk` command

---

tooling/nargo_cli/src/cli/init_cmd.rs
tooling/nargo_cli/src/cli/noir_template_files/binary.nr
tooling/nargo_cli/src/cli/noir_template_files/contract.nr
tooling/nargo_cli/src/cli/noir_template_files/library.nr

Resolves 
This PR moves the template noir programs into their own files to remove some noise from the rust source files.

chore: move noir program templates into separate files

---

compiler/noirc_frontend/src/parser/parser.rs

Fixes #2996
Resolves #2996 
Modifies `expression_no_constructors`.

fix: Allow constructors in parentheses in `if` conditions and `for` ranges

---

compiler/noirc_driver/src/lib.rs
compiler/noirc_frontend/src/monomorphization/mod.rs
tooling/nargo_cli/tests/compile_success_empty/let_stmt/src/main.nr

Resolves #2786
We were panicking previously whenever using the repeated array element syntax where the element defined a new variable internally. This is because we were simply cloning the expression which leads to redefining the same variable. Running `self.expr` each time instead will create a new variable.

fix: Fix panic when using repeated arrays which define variables

---

compiler/noirc_frontend/src/lexer/lexer.rs
compiler/noirc_frontend/src/lexer/token.rs
tooling/nargo_fmt/src/utils.rs

chore: lex doc comments

---

compiler/noirc_frontend/src/hir_def/types.rs
tooling/nargo_cli/tests/execution_success/slices/src/main.nr

Resolves #2370
Previously if we had two unbound type variables, `TypeVariable::Constant(N)` and `TypeVariable::Constant(M)`, they would not unify unless `N == M`. Since both are unbound however, this PR allows us to instead bind both to `Type::NotConstant` if `N != M`. This effectively allows us to infer a mutable variable whose array changes in size to be a slice instead of an array (as in the linked issue).

fix: Allow two `TypeVariable::Constant(N)` to unify even if their constants are not equal

---

compiler/noirc_driver/src/debug.rs
tooling/nargo/src/artifacts/debug.rs

Debug metadata only included files that had the last item of any callstack. Since we resolve complete callstacks, we need all files present on those.
Resolves

fix: Complete debug metadata

---

.github/workflows/gates_report.yml
.gitignore
Cargo.lock
cspell.json
tooling/nargo_cli/Cargo.toml
tooling/nargo_cli/tests/gates_report.sh

Resolves #3182 
This PR adds benchmarking for how PRs affect the number of opcodes/constraints generated for the programs in the `execution_success` test suite. If a PR changes the ACIR generated then a sticky comment will be added to the PR with a summary of the changes.

chore(ci): Generate circuit benchmark summaries on PRs

---

noir_stdlib/src/sha256.nr
noir_stdlib/src/sha512.nr

Resolves 
This PR optimizes the sha256 and sha512 implementations to use a simple addition instead of an OR black box function. We can do this as none of the bits in the two operands overlap so the operations are equivalent.

feat(stdlib): optimize constraint counts in sha256/sha512

---

docs/docs/nargo/01_commands.md

Resolves https://github.com/noir-lang/noir/issues/3240.
Briefly document that `nargo fmt` is now available on the "Nargo - Commands" page.
Prettier seems to have also suggested table formatting changes.

chore(docs): Document `nargo fmt`

---

docs/docs/language_concepts/01_functions.md

Documents the usage of method specialisation
Resolves #3238

chore: method specialization

---

compiler/noirc_frontend/src/lexer/errors.rs
compiler/noirc_frontend/src/parser/errors.rs

This is something I noticed while working on #3236. Lexer errors would display a short printout like `error: TooManyBits` instead of the full formatting.
This was a result of the parser using the error/debug trait to display lexer errors instead of the conversion to a custom diagnostic.

fix: Fix lexer error formatting

---

.github/workflows/test-acvm-js.yml

chore: standardize workflow triggers

---

.github/actions/docs/build-status/script.sh
.github/workflows/build-docs.yml
docs/docs/language_concepts/01_functions.md

Somehow a previous PR passed CI without a valid deployment. This broke master.
- Undos the mess that broke master
- Tries to stop continuing on error if deployment fails, I don't even know why i had it there in the first place

chore: adding fix to master branch

---

compiler/noirc_frontend/Cargo.toml

This PR fixes 'Publish Noir ES Packages' CI job by removing the empty 'default' features.
```
error: while parsing a TOML string: [error] toml::insert_value: value ("default") already exists.
```
N/A

chore: remove `default` empty features array

---

docs/docs/language_concepts/data_types/05_slices.mdx
docs/docs/language_concepts/data_types/06_vectors.mdx
docs/docs/standard_library/cryptographic_primitives/00_hashes.mdx
docs/docs/standard_library/cryptographic_primitives/01_scalar.mdx
docs/docs/standard_library/cryptographic_primitives/02_schnorr.mdx
docs/docs/standard_library/cryptographic_primitives/05_eddsa.mdx

chore: update relative paths for docs imports

---

CONTRIBUTING.md

Cutting a new doc version with:
```bash
npm run docusaurus docs:version <new_version_tag>
```
did not work on my machine, gave the error of:
```bash
npm ERR! Lifecycle script `docusaurus` failed with error: 
npm ERR! Error: Missing script: "docusaurus"
To see a list of scripts, run:
npm run 
npm ERR!   in workspace: docs@0.0.0 
npm ERR!   at location: /Users/s/Dev/noir-lang/noir/docs 
npm ERR! Missing script: docusaurus
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/s/.npm/_logs/2023-10-25T14_01_36_763Z-debug-0.log
```
Using:
```bash
yarn docusaurus docs:version <new_version_tag>
```
instead worked.
Both approaches are recommended on [Docusaurus's docs](https://docusaurus.io/docs/versioning#tagging-a-new-version).

chore(docs): Recommend `yarn` instead of for cutting doc versions

---

compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
compiler/noirc_frontend/src/node_interner.rs
compiler/noirc_frontend/src/tests.rs
tooling/nargo_cli/tests/compile_success_empty/trait_generics/Nargo.toml
tooling/nargo_cli/tests/compile_success_empty/trait_generics/src/main.nr

Trait impl methods are all placed within a struct's namespace which doesn't allow for the same trait to be implemented on different instances of a generic type, such as `Foo<u32>` and `Foo<u64>`.
This PR allows implementing a trait multiple times for the same struct, although still does not allow fully generic impls such as `impl<T> Bar for Foo<T>`. This was a bit awkward to fit in with the existing way trait impls are put in modules. In the future when we have fully generic traits this will need to be reworked entirely so that only the abstract trait definition is visible and an impl is chosen later during type checking.
No documentation yet - I'm waiting until traits are fully finished and no longer marked experimental.

feat: Allow a trait to be implemented multiple times for the same struct

---

.github/pull_request_template.md

To better promote secure and best development practices through documentation, Noir's contribution workflow now requires code authors to include documentation updates per their code changes (if applicable) in the same PRs.
The workflow would be very helpful for capturing design philosophies, contexts, details and caveats from the original authors in the Noir documentation that otherwise could easily go missing in translation.
This PR updates the GitHub PR template to reflect the new workflow.
Additionally the PR also trims the verbose comments in the template.
Related effort: https://github.com/noir-lang/noir/pull/3162

chore(github): Update PR template per new documentation workflow

---

compiler/noirc_frontend/src/hir/def_collector/dc_crate.rs
compiler/noirc_frontend/src/hir/def_collector/dc_mod.rs
tooling/nargo_cli/tests/compile_success_empty/trait_generics/src/main.nr

Resolves 
This PR makes generic trait impls like `impl<T> Foo for Bar<T>` callable. Note that this PR does the bare minimum - there is no overlap checking for these impls currently so you can define two identical generic impls without error. The error will come in a later PR.
Check one:

feat: Make generic impls callable

---

tooling/bb_abstraction_leaks/build.rs
tooling/noir_js_backend_barretenberg/package.json
yarn.lock

Resolves 
This PR bumps bb to a version which will work on mainframe. I've tested this and it works.
Check one:

chore: bump bb version to 0.12.0

---

.github/workflows/auto-pr-rebuild-script.yml
tooling/nargo_cli/tests/rebuild.sh

Keeping the `acir_artifacts` directory in sync causes us (well..  me at least) a bunch of trouble due to merge conflicts.
This PR acts as a first step on moving us away from having committed ACIR artifacts in this repository. We now publish an artifact containing the acir + witnesses.
`aztec-packages` can then pull these artifacts from workflow runs attached to master. At this point we'll no longer need to commit artifacts to this repository.

chore: upload acir artifacts as a github artifact
